package net.sonic0810.copperinferno.feature.handbook;

import java.util.function.Consumer;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.Item;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * The in-game handbook item + entries (backed by core.handbook.HandbookEntries).
 *
 * <p>One item ({@code copper_inferno_handbook}, max stack 1) crafted shapelessly from a book
 * and a copper ingot ({@code data/copper_inferno/recipe/handbook/copper_inferno_handbook.json}).
 * Right-clicking it opens the client-only handbook screen through
 * {@link #handbookScreenOpener}. Assets are generated by {@code devtools/gen/handbook_gen.py}.
 */
public final class HandbookFeature {
	private HandbookFeature() {
	}

	/** Assigned in init(). */
	public static Item HANDBOOK;

	/**
	 * Installed by {@code HandbookFeatureClient}; opens the client-side handbook screen.
	 * Null on a dedicated server.
	 */
	public static Consumer<PlayerEntity> handbookScreenOpener;

	public static void init() {
		HANDBOOK = ModItems.register("copper_inferno_handbook", HandbookItem::new,
				new Item.Settings().maxCount(1));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY)
				.register(entries -> entries.add(HANDBOOK));

		registerHandbookEntries();
	}

	private static void registerHandbookEntries() {
		// The handbook documents its own recipe...
		HandbookEntries.add(new HandbookEntry("items", "copper_inferno_handbook",
				"copper_inferno:copper_inferno_handbook", "handbook/copper_inferno_handbook",
				new String[]{"", "", "", "minecraft:book", "minecraft:copper_ingot", "", "", "", ""},
				"copper_inferno:copper_inferno_handbook", 1,
				"Craft the COPPER INFERNO Handbook from a book and a copper ingot. It documents every block, item, mob and recipe this mod adds.",
				"Das COPPER-INFERNO-Handbuch wird aus einem Buch und einem Kupferbarren hergestellt. Es dokumentiert jeden Block, jeden Gegenstand, jedes Wesen und jedes Rezept dieses Mods."));

		// ...and carries a "?" hint page explaining how to use it.
		HandbookEntries.add(new HandbookEntry("items", "copper_inferno_handbook_hint",
				"copper_inferno:copper_inferno_handbook", null, null, null, 0,
				"? Hold the handbook and right-click to open it. Pick a category on the left, flip pages with the arrows below, and press the DE/EN button to switch the text between German and English. The Recipes tab collects every entry with a crafting grid.",
				"? Halte das Handbuch in der Hand und \u00f6ffne es mit Rechtsklick. W\u00e4hle links eine Kategorie, bl\u00e4ttere mit den Pfeilen unten und dr\u00fccke den DE/EN-Knopf, um den Text zwischen Deutsch und Englisch umzuschalten. Der Rezepte-Reiter sammelt jeden Eintrag mit Craftingraster."));
	}
}
