package net.sonic0810.kupferbienen.feature.bees;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.Item;
import net.sonic0810.kupferbienen.core.ModCreativeTab;
import net.sonic0810.kupferbienen.core.ModItems;

/**
 * Copper bees: kupferwabe (copper comb), the base material produced by copper bee apiaries.
 * Assets are generated by devtools/gen/kupferbienen_gen.py.
 */
public final class BeesFeature {
	private BeesFeature() {
	}

	public static Item KUPFERWABE;

	public static void init() {
		KUPFERWABE = ModItems.register("kupferwabe", Item::new, new Item.Settings());

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			entries.add(KUPFERWABE);
		});
	}
}
