package net.sonic0810.kupferbienen.feature.bees;

import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.SpawnLocationTypes;
import net.minecraft.entity.SpawnReason;
import net.minecraft.entity.SpawnRestriction;
import net.minecraft.entity.passive.AnimalEntity;
import net.minecraft.entity.passive.BeeEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.random.Random;
import net.minecraft.world.Heightmap;
import net.minecraft.world.ServerWorldAccess;
import net.minecraft.world.biome.BiomeKeys;
import net.sonic0810.kupferbienen.core.ModBlockEntities;
import net.sonic0810.kupferbienen.core.ModBlocks;
import net.sonic0810.kupferbienen.core.ModCreativeTab;
import net.sonic0810.kupferbienen.core.ModEntities;
import net.sonic0810.kupferbienen.core.ModItems;

/**
 * Copper bees and the apiary loop that makes copper farmable: two {@code BeeEntity} subclasses
 * (Kupferbiene, Gruenspanbiene), the Kupferbluete flower they pollinate (injected into
 * {@code #minecraft:bee_attractive}, {@code #minecraft:flowers} and {@code #minecraft:bee_food}
 * via data/minecraft tag files), the Kupferstock apiary that turns nearby bees + blooms into
 * Kupferwaben, and the Gruenspanpollen byproduct. Assets are generated by
 * devtools/gen/kupferbienen_gen.py.
 */
public final class BeesFeature {
	private BeesFeature() {
	}

	public static EntityType<KupferbieneEntity> KUPFERBIENE;
	public static EntityType<GruenspanbieneEntity> GRUENSPANBIENE;

	public static Item KUPFERWABE;
	public static Item GRUENSPANPOLLEN;
	public static Item KUPFERBIENE_SPAWN_EGG;
	public static Item GRUENSPANBIENE_SPAWN_EGG;

	public static Block KUPFERBLUETE;
	public static Block KUPFERSTOCK;
	public static BlockEntityType<KupferstockBlockEntity> KUPFERSTOCK_BLOCK_ENTITY;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerBlocks();
		registerItems();
		registerSpawning();
	}

	private static void registerEntityTypes() {
		// Dimensions/eye height/tracking range copied from the vanilla bee EntityType
		// registration (bytecode: bee = SpawnGroup.CREATURE, dimensions(0.7f, 0.6f)
		// .eyeHeight(0.3f).maxTrackingRange(8)).
		KUPFERBIENE = ModEntities.register("kupferbiene",
				EntityType.Builder.create(KupferbieneEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.7f, 0.6f)
						.eyeHeight(0.3f)
						.maxTrackingRange(8));
		GRUENSPANBIENE = ModEntities.register("gruenspanbiene",
				EntityType.Builder.create(GruenspanbieneEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.7f, 0.6f)
						.eyeHeight(0.3f)
						.maxTrackingRange(8));
	}

	private static void registerAttributes() {
		// BeeEntity.createBeeAttributes() is the exact 1.21.9 static name (verified via javap).
		FabricDefaultAttributeRegistry.register(KUPFERBIENE, BeeEntity.createBeeAttributes());
		FabricDefaultAttributeRegistry.register(GRUENSPANBIENE, BeeEntity.createBeeAttributes());
	}

	private static void registerBlocks() {
		KUPFERBLUETE = ModBlocks.register("kupferbluete", KupferblueteBlock::new,
				AbstractBlock.Settings.create()
						.noCollision()
						.breakInstantly()
						.sounds(BlockSoundGroup.GRASS),
				"tooltip.kupferbienen.kupferbluete");
		KUPFERSTOCK = ModBlocks.register("kupferstock", KupferstockBlock::new,
				AbstractBlock.Settings.create()
						.strength(2.0f)
						.sounds(BlockSoundGroup.WOOD),
				"tooltip.kupferbienen.kupferstock.1", "tooltip.kupferbienen.kupferstock.2");
		KUPFERSTOCK_BLOCK_ENTITY = ModBlockEntities.register("kupferstock",
				KupferstockBlockEntity::new, KUPFERSTOCK);
	}

	private static void registerItems() {
		KUPFERWABE = ModItems.register("kupferwabe", Item::new, new Item.Settings());
		GRUENSPANPOLLEN = ModItems.register("gruenspanpollen", Item::new, new Item.Settings());
		// Item.Settings.spawnEgg(type) stores the entity type the vanilla SpawnEggItem reads in
		// 1.21.9 (InfernoMobsFeature pattern, signature verified via javap).
		KUPFERBIENE_SPAWN_EGG = ModItems.register("kupferbiene_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(KUPFERBIENE));
		GRUENSPANBIENE_SPAWN_EGG = ModItems.register("gruenspanbiene_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(GRUENSPANBIENE));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BIENEN_KEY).register(entries -> {
			entries.add(KUPFERWABE);
			entries.add(GRUENSPANPOLLEN);
			entries.add(KUPFERBLUETE);
			entries.add(KUPFERSTOCK);
			entries.add(KUPFERBIENE_SPAWN_EGG);
			entries.add(GRUENSPANBIENE_SPAWN_EGG);
		});
	}

	private static void registerSpawning() {
		// SpawnRestriction.register is private in vanilla but access-widened by Fabric's
		// transitive access wideners (InfernoMobsFeature/MoltenFaunaFeature pattern). Vanilla
		// registers NO SpawnRestriction entry for the bee (it only spawns with worldgen nests).
		// The Kupferbiene uses the standard animal predicate
		// AnimalEntity::isValidNaturalSpawn(EntityType<? extends AnimalEntity>, WorldAccess,
		// SpawnReason, BlockPos, Random) — assignable to SpawnPredicate<T> because
		// ServerWorldAccess extends WorldAccess (both signatures verified via javap).
		// The Gruenspanbiene is a cave dweller: the standard animal predicate (grass/light)
		// near-never passes in LUSH/DRIPSTONE_CAVES, so it gets a cave-tuned predicate
		// instead (below sea level, on stone/moss/dripstone/animal-spawnable floors, no
		// light requirement — deliberate, caves are dark).
		SpawnRestriction.register(KUPFERBIENE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, AnimalEntity::isValidNaturalSpawn);
		SpawnRestriction.register(GRUENSPANBIENE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, BeesFeature::isValidGruenspanbieneSpawn);

		BiomeModifications.addSpawn(
				BiomeSelectors.includeByKey(BiomeKeys.FLOWER_FOREST, BiomeKeys.MEADOW,
						BiomeKeys.LUSH_CAVES, BiomeKeys.DRIPSTONE_CAVES),
				SpawnGroup.CREATURE, KUPFERBIENE, 8, 2, 3);
		BiomeModifications.addSpawn(
				BiomeSelectors.includeByKey(BiomeKeys.LUSH_CAVES, BiomeKeys.DRIPSTONE_CAVES),
				SpawnGroup.CREATURE, GRUENSPANBIENE, 4, 1, 2);
	}

	/** Cave spawn predicate for the Gruenspanbiene (matches SpawnRestriction.SpawnPredicate). */
	private static boolean isValidGruenspanbieneSpawn(EntityType<GruenspanbieneEntity> type,
			ServerWorldAccess world, SpawnReason reason, BlockPos pos, Random random) {
		BlockState floor = world.getBlockState(pos.down());
		return pos.getY() < 63 && (floor.isIn(BlockTags.BASE_STONE_OVERWORLD)
				|| floor.isIn(BlockTags.MOSS_REPLACEABLE)
				|| floor.isIn(BlockTags.DRIPSTONE_REPLACEABLE_BLOCKS)
				|| floor.isIn(BlockTags.ANIMALS_SPAWNABLE_ON));
	}
}
