package net.sonic0810.copperinferno.feature.infernodim;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.item.Item;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * The Inferno dimension feature: terrain/ore blocks for the data-driven
 * {@code copper_inferno:inferno} dimension (dimension/dimension_type/worldgen JSON under
 * {@code data/copper_inferno/}), the infernium portal frame + inferno portal pane, and the
 * infernium igniter that lights 4x5 frames. Assets are generated by
 * {@code devtools/gen/infernodim_gen.py}.
 */
public final class InfernoDimensionFeature {
	private InfernoDimensionFeature() {
	}

	// Terrain blocks.
	public static Block CINDERSTONE;
	public static Block COBBLED_CINDERSTONE;
	public static Block SLAGSTONE;
	public static Block ASH_BLOCK;
	public static Block EMBER_SOIL;
	public static Block SCORCHED_SAND;
	public static Block CINDER_GRAVEL;

	// Ores / glowing terrain.
	public static Block INFERNIUM_ORE;
	public static Block SMOLDER_CRYSTAL_ORE;
	public static Block MOLTEN_SLAG;

	// Portal.
	public static Block INFERNIUM_PORTAL_FRAME;
	public static Block INFERNO_PORTAL;

	public static Item INFERNIUM_IGNITER;

	/** Fresh settings per block: ModBlocks.register writes a registry key into the instance. */
	private static AbstractBlock.Settings stoneSettings(float hardness, float resistance) {
		return AbstractBlock.Settings.create()
				.mapColor(MapColor.STONE_GRAY)
				.requiresTool()
				.strength(hardness, resistance)
				.sounds(BlockSoundGroup.NETHERRACK);
	}

	public static void init() {
		CINDERSTONE = ModBlocks.register("cinderstone", Block::new,
				stoneSettings(0.6f, 0.6f), true);
		COBBLED_CINDERSTONE = ModBlocks.register("cobbled_cinderstone", Block::new,
				stoneSettings(2.0f, 6.0f).sounds(BlockSoundGroup.STONE), true);
		SLAGSTONE = ModBlocks.register("slagstone", Block::new,
				stoneSettings(1.5f, 6.0f).mapColor(MapColor.GRAY).sounds(BlockSoundGroup.BASALT), true);
		ASH_BLOCK = ModBlocks.register("ash_block", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.LIGHT_GRAY)
						.strength(0.5f)
						.sounds(BlockSoundGroup.SOUL_SAND),
				true);
		EMBER_SOIL = ModBlocks.register("ember_soil", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.ORANGE)
						.strength(0.5f)
						.sounds(BlockSoundGroup.SOUL_SOIL)
						.luminance(state -> 3),
				true);
		SCORCHED_SAND = ModBlocks.register("scorched_sand", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.LIGHT_GRAY)
						.strength(0.5f)
						.sounds(BlockSoundGroup.SAND),
				true);
		CINDER_GRAVEL = ModBlocks.register("cinder_gravel", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.GRAY)
						.strength(0.6f)
						.sounds(BlockSoundGroup.GRAVEL),
				true);

		INFERNIUM_ORE = ModBlocks.register("infernium_ore", Block::new,
				stoneSettings(3.0f, 3.0f).sounds(BlockSoundGroup.NETHER_ORE), true);
		SMOLDER_CRYSTAL_ORE = ModBlocks.register("smolder_crystal_ore", Block::new,
				stoneSettings(3.0f, 3.0f).sounds(BlockSoundGroup.NETHER_ORE), true);
		MOLTEN_SLAG = ModBlocks.register("molten_slag", Block::new,
				stoneSettings(0.5f, 0.5f)
						.mapColor(MapColor.ORANGE)
						.sounds(BlockSoundGroup.BASALT)
						.luminance(state -> 10),
				true);

		INFERNIUM_PORTAL_FRAME = ModBlocks.register("infernium_portal_frame", Block::new,
				stoneSettings(3.0f, 9.0f)
						.mapColor(MapColor.ORANGE)
						.sounds(BlockSoundGroup.NETHER_BRICKS)
						.luminance(state -> 5),
				true);
		INFERNO_PORTAL = ModBlocks.register("inferno_portal", InfernoPortalBlock::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.ORANGE)
						.noCollision()
						.strength(-1.0f, 3600000.0f)
						.sounds(BlockSoundGroup.GLASS)
						.luminance(state -> 11)
						.nonOpaque(),
				true);

		INFERNIUM_IGNITER = ModItems.register("infernium_igniter", InferniumIgniterItem::new,
				new Item.Settings().maxDamage(64));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			entries.add(CINDERSTONE);
			entries.add(COBBLED_CINDERSTONE);
			entries.add(SLAGSTONE);
			entries.add(ASH_BLOCK);
			entries.add(EMBER_SOIL);
			entries.add(SCORCHED_SAND);
			entries.add(CINDER_GRAVEL);
			entries.add(INFERNIUM_ORE);
			entries.add(SMOLDER_CRYSTAL_ORE);
			entries.add(MOLTEN_SLAG);
			entries.add(INFERNIUM_PORTAL_FRAME);
			entries.add(INFERNO_PORTAL);
		});
		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			entries.add(INFERNIUM_IGNITER);
		});

		registerHandbookEntries();
	}

	private static void registerHandbookEntries() {
		// Recipe entries (one per JSON under data/copper_inferno/recipe/infernodim/).
		HandbookEntries.add(new HandbookEntry("gear", "infernodim_infernium_igniter",
				"copper_inferno:infernium_igniter", "infernodim/infernium_igniter",
				new String[] {"", "minecraft:flint", "", "", "minecraft:copper_ingot", "", "", "minecraft:blaze_rod", ""},
				"copper_inferno:infernium_igniter", 1,
				"Flint struck against a copper striker on a blaze-rod handle. Use it on an Infernium Portal Frame to ignite an Inferno portal. 64 uses.",
				"Feuerstein an einem Kupferschläger mit Lohenruten-Griff. Auf einem Infernium-Portalrahmen benutzen, um ein Inferno-Portal zu entzünden. 64 Verwendungen."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernodim_infernium_portal_frame",
				"copper_inferno:infernium_portal_frame", "infernodim/infernium_portal_frame",
				new String[] {"minecraft:polished_blackstone", "minecraft:copper_ingot", "minecraft:polished_blackstone",
						"minecraft:copper_ingot", "minecraft:magma_block", "minecraft:copper_ingot",
						"minecraft:polished_blackstone", "minecraft:copper_ingot", "minecraft:polished_blackstone"},
				"copper_inferno:infernium_portal_frame", 4,
				"Portal frame blocks: polished blackstone and copper around a magma core - all Overworld/Nether materials, so you craft the frame BEFORE ever entering the Inferno. Fourteen make one 4x5 portal ring.",
				"Portalrahmen-Blöcke: polierter Schwarzstein und Kupfer um einen Magmakern - alles Materialien aus Oberwelt und Nether, du baust den Rahmen also, BEVOR du das Inferno betrittst. Vierzehn ergeben einen 4x5-Portalring."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernodim_cobbled_cinderstone",
				"copper_inferno:cobbled_cinderstone", "infernodim/cobbled_cinderstone",
				new String[] {"copper_inferno:cinderstone", "copper_inferno:cinderstone", "",
						"copper_inferno:cinderstone", "copper_inferno:cinderstone", "", "", "", ""},
				"copper_inferno:cobbled_cinderstone", 4,
				"Knapped cinderstone rubble. Sturdier than raw cinderstone and good for ember-proof foundations.",
				"Behauener Zunderstein-Schutt. Robuster als roher Zunderstein und gut für glutfeste Fundamente."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernodim_cinderstone_from_smelting",
				"copper_inferno:cinderstone", "infernodim/cinderstone_from_smelting",
				new String[] {"", "", "", "", "copper_inferno:cobbled_cinderstone", "", "", "", ""},
				"copper_inferno:cinderstone", 1,
				"Smelting cobbled cinderstone fuses it back into smooth cinderstone, the Inferno's bedrock-to-ceiling terrain stone.",
				"Durch Schmelzen verschmilzt Bruchzunderstein wieder zu glattem Zunderstein, dem Terrainstein des Infernos."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernodim_cobbled_cinderstone_stonecutting",
				"copper_inferno:cobbled_cinderstone", "infernodim/cobbled_cinderstone_from_cinderstone_stonecutting",
				new String[] {"", "", "", "", "copper_inferno:cinderstone", "", "", "", ""},
				"copper_inferno:cobbled_cinderstone", 1,
				"The stonecutter splits cinderstone into cobbled cinderstone one block at a time, with no waste.",
				"Die Steinsäge zerteilt Zunderstein verlustfrei Block für Block in Bruchzunderstein."));

		// Non-recipe dimension lore entries.
		HandbookEntries.add(new HandbookEntry("dimension", "infernodim_portal_howto",
				"copper_inferno:infernium_portal_frame", null, null, null, 0,
				"Build an upright 4x5 Infernium Portal Frame ring (2x3 air interior), then ignite the interior with the Infernium Igniter. Step in to travel to the Inferno; you arrive at your existing portal within 16 blocks, or a safe return platform with a pre-lit frame is built near y=70 if none exists.",
				"Baue einen aufrechten 4x5-Ring aus Infernium-Portalrahmen (2x3 Luft innen) und entzünde das Innere mit dem Infernium-Anzünder. Tritt hinein, um ins Inferno zu reisen; du kommst an deinem bestehenden Portal im Umkreis von 16 Blöcken an, oder eine sichere Rückkehr-Plattform mit entzündetem Rahmen wird nahe y=70 errichtet, falls keines existiert."));
		HandbookEntries.add(new HandbookEntry("dimension", "infernodim_biome_cinder_wastes",
				"copper_inferno:cinderstone", null, null, null, 0,
				"Cinder Wastes: the Inferno's open ember plains. Bare cinderstone, drifting sparks and lava seas under an orange haze.",
				"Aschenöde: die offenen Glut-Ebenen des Infernos. Nackter Zunderstein, treibende Funken und Lavaseen unter orangefarbenem Dunst."));
		HandbookEntries.add(new HandbookEntry("dimension", "infernodim_biome_ember_grove",
				"copper_inferno:ember_soil", null, null, null, 0,
				"Ember Grove: a smouldering forest biome. Glowing ember soil underfoot and thick verdigris-tinted air.",
				"Gluthain: ein schwelendes Waldbiom. Glühender Glutboden unter den Füßen und dichte, grünspanfarbene Luft."));
		HandbookEntries.add(new HandbookEntry("dimension", "infernodim_biome_slag_sea",
				"copper_inferno:slagstone", null, null, null, 0,
				"Slag Sea: ash-gray delta flats of slagstone and cinder gravel, dusted with white ash and pocked by molten slag.",
				"Schlackenmeer: aschgraue Delta-Ebenen aus Schlackenstein und Aschenkies, bestäubt mit weißer Asche und durchsetzt von geschmolzener Schlacke."));
		HandbookEntries.add(new HandbookEntry("dimension", "infernodim_infernium_ore",
				"copper_inferno:infernium_ore", null, null, null, 0,
				"Infernium Ore: copper-orange veins in cinderstone throughout the Inferno. Mine with a pickaxe.",
				"Infernium-Erz: kupferorange Adern im Zunderstein überall im Inferno. Mit einer Spitzhacke abbauen."));
		HandbookEntries.add(new HandbookEntry("dimension", "infernodim_smolder_crystal_ore",
				"copper_inferno:smolder_crystal_ore", null, null, null, 0,
				"Smolder Crystal Ore: verdigris-green crystal shards seeded through cinderstone. Rarer than infernium.",
				"Schwelkristall-Erz: grünspanfarbene Kristallsplitter im Zunderstein. Seltener als Infernium."));
		HandbookEntries.add(new HandbookEntry("dimension", "infernodim_molten_slag",
				"copper_inferno:molten_slag", null, null, null, 0,
				"Molten Slag: glowing blobs near the lava seas (light level 10). Safe to walk on, hot to look at.",
				"Geschmolzene Schlacke: glühende Blasen nahe der Lavaseen (Lichtstärke 10). Sicher zu begehen, heiß anzusehen."));
	}
}
