package net.sonic0810.copperinferno.feature.inferno;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlockFamilies.BlockFamily;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Fire-themed "inferno" stone blocks: charred copper + ember masonry. 17 blocks total — three
 * full cube families (base/slab/stairs/wall) plus five singles. Assets (blockstates, models,
 * textures, item definitions, loot tables, recipes, lang fragment) are generated by
 * {@code devtools/gen/inferno_gen.py} into {@code src/main/resources}.
 */
public final class InfernoFeature {
	private InfernoFeature() {
	}

	public static BlockFamily INFERNO_BRICKS;
	public static BlockFamily INFERNO_TILES;
	public static BlockFamily CHARRED_COPPER_BRICKS;

	public static Block CRACKED_INFERNO_BRICKS;
	public static Block CHISELED_INFERNO_BRICKS;
	public static Block CHARRED_COPPER;
	public static Block INFERNO_PILLAR;
	public static Block INFERNO_CORE;

	/**
	 * Fresh settings instance per block (a Settings instance must never be shared: the registry
	 * key is written into it). Consistent inferno look: black map color, nether-bricks sounds.
	 */
	private static AbstractBlock.Settings settings() {
		return AbstractBlock.Settings.create()
				.mapColor(MapColor.BLACK)
				.strength(3.5F, 8.0F)
				.requiresTool()
				.sounds(BlockSoundGroup.NETHER_BRICKS);
	}

	public static void init() {
		INFERNO_BRICKS = ModBlockFamilies.registerCubeFamily("inferno_bricks", "inferno_brick", InfernoFeature::settings, true);
		INFERNO_TILES = ModBlockFamilies.registerCubeFamily("inferno_tiles", "inferno_tile", InfernoFeature::settings, true);
		CHARRED_COPPER_BRICKS = ModBlockFamilies.registerCubeFamily("charred_copper_bricks", "charred_copper_brick", InfernoFeature::settings, true);

		CRACKED_INFERNO_BRICKS = ModBlocks.register("cracked_inferno_bricks", Block::new, settings(), true);
		CHISELED_INFERNO_BRICKS = ModBlocks.register("chiseled_inferno_bricks", Block::new, settings(), true);
		CHARRED_COPPER = ModBlocks.register("charred_copper", Block::new, settings(), true);
		INFERNO_PILLAR = ModBlocks.register("inferno_pillar", PillarBlock::new, settings(), true);
		INFERNO_CORE = ModBlocks.register("inferno_core", Block::new, settings().luminance(state -> 12), true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			for (BlockFamily family : new BlockFamily[] {INFERNO_BRICKS, INFERNO_TILES, CHARRED_COPPER_BRICKS}) {
				entries.add(family.block());
				entries.add(family.slab());
				entries.add(family.stairs());
				entries.add(family.wall());
			}
			entries.add(CRACKED_INFERNO_BRICKS);
			entries.add(CHISELED_INFERNO_BRICKS);
			entries.add(CHARRED_COPPER);
			entries.add(INFERNO_PILLAR);
			entries.add(INFERNO_CORE);
		});
	}
}
