package net.sonic0810.copperinferno.feature.enchants;

import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4.1 "Enchants" feature: six DATA-DRIVEN enchantments. The enchantments themselves are
 * pure datapack JSON under {@code data/copper_inferno/enchantment/<id>.json} (the 1.21+
 * registry format — no code registration), generated by devtools/gen/enchants_gen.py;
 * acquisition (enchanting table / villager trades) comes from the vanilla
 * {@code #minecraft:enchantment/*} tags via devtools/tagfrag/enchants.json.
 *
 * <ul>
 * <li>ember_edge — swords ignite victims on hit (a weaker Fire Aspect)</li>
 * <li>verdigris_guard — armor, reduces fire damage and burn time (weaker Fire Protection)</li>
 * <li>fizz_burst — boots, melee hits pop a fizzy knockback burst around you</li>
 * <li>coppersoul — tools, chance to not consume durability (flatter Unbreaking curve)</li>
 * <li>slag_breaker — mining tools, flat +2 mining efficiency per level</li>
 * <li>doomtouch — swords apply Weakness I on hit</li>
 * </ul>
 *
 * <p>{@code init()} only registers the handbook pages documenting them.
 */
public final class EnchantsFeature {
	private EnchantsFeature() {
	}

	public static void init() {
		HandbookEntries.add(new HandbookEntry("gear", "enchants_ember_edge",
				"copper_inferno:emberite_sword", null, null, null, 0,
				"Ember Edge (sword enchantment, max II): every direct hit sets the victim on fire for 3 seconds per level - a copper-forged little sibling of Fire Aspect. Found in the enchanting table and on villager trades.",
				"Glutklinge (Schwertverzauberung, max. II): Jeder direkte Treffer setzt das Ziel f\u00fcr 3 Sekunden pro Stufe in Brand - der kupfergeschmiedete kleine Bruder von Feueraspekt. Am Zaubertisch und bei Dorfbewohnern erh\u00e4ltlich."));
		HandbookEntries.add(new HandbookEntry("gear", "enchants_verdigris_guard",
				"copper_inferno:oxidized_copper_chestplate", null, null, null, 0,
				"Verdigris Guard (armor enchantment, max III): a patina ward that blocks 1 point of fire damage per level and shortens burn time by 10% per level. Weaker than Fire Protection, but it turns up more cheaply.",
				"Gr\u00fcnspanschutz (R\u00fcstungsverzauberung, max. III): Ein Patina-Schild, das pro Stufe 1 Punkt Feuerschaden abf\u00e4ngt und die Brenndauer um 10 % pro Stufe verk\u00fcrzt. Schw\u00e4cher als Feuerschutz, daf\u00fcr g\u00fcnstiger zu bekommen."));
		HandbookEntries.add(new HandbookEntry("gear", "enchants_fizz_burst",
				"copper_inferno:dr_pepper", null, null, null, 0,
				"Fizz Burst (boots enchantment, max II): your melee hits uncork a carbonated shockwave at your feet that shoves nearby enemies away - stronger fizz per level. No blocks are harmed.",
				"Sprudelsto\u00df (Stiefelverzauberung, max. II): Deine Nahkampftreffer entkorken eine Kohlens\u00e4ure-Druckwelle an deinen F\u00fc\u00dfen, die Gegner in der N\u00e4he wegschubst - pro Stufe mehr Sprudel. Bl\u00f6cke bleiben heil."));
		HandbookEntries.add(new HandbookEntry("gear", "enchants_coppersoul",
				"copper_inferno:copper_alloy_ingot", null, null, null, 0,
				"Coppersoul (tool enchantment, max III): a patient copper spirit that sometimes absorbs wear - 25/33/38% chance to not consume durability. A flatter curve than Unbreaking, and it stacks its own way.",
				"Kupferseele (Werkzeugverzauberung, max. III): Ein geduldiger Kupfergeist, der Verschlei\u00df bisweilen schluckt - 25/33/38 % Chance, keine Haltbarkeit zu verbrauchen. Flachere Kurve als Haltbarkeit, mit eigenem Charakter."));
		HandbookEntries.add(new HandbookEntry("gear", "enchants_slag_breaker",
				"copper_inferno:infernium_pickaxe", null, null, null, 0,
				"Slag Breaker (mining enchantment, max III): a steady +2 mining speed per level. It never reaches Efficiency V heights, but the early levels dig noticeably faster through the Inferno's slag and stone.",
				"Schlackenbrecher (Abbauverzauberung, max. III): Konstant +2 Abbaugeschwindigkeit pro Stufe. Die H\u00f6hen von Effizienz V erreicht er nie, aber die fr\u00fchen Stufen graben sp\u00fcrbar schneller durch Schlacke und Stein des Infernos."));
		HandbookEntries.add(new HandbookEntry("gear", "enchants_doomtouch",
				"copper_inferno:doom_emblem", null, null, null, 0,
				"Doomtouch (sword enchantment, max II): every direct hit brands the victim with Weakness I - 3 seconds at level I, 5 at level II. The DOOM in your Dr.Pepper, now on a blade.",
				"Verh\u00e4ngnisgriff (Schwertverzauberung, max. II): Jeder direkte Treffer belegt das Ziel mit Schw\u00e4che I - 3 Sekunden auf Stufe I, 5 auf Stufe II. Das DOOM aus deiner Dr.Pepper, jetzt auf einer Klinge."));
	}
}
