package net.sonic0810.copperinferno.feature.smolderquartz;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlockFamilies.BlockFamily;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Smolder Quartz block set: 224 building blocks across 14 crystal / glassy-stone
 * materials (smolder quartz, cinder crystal, flame opal, ember prism, ashglass stone,
 * glowspar, heatlens stone, magma geode, pyrite crystal, sulfur crystal, obsid
 * glassblock, ember amber, fire agate, lava pearl). Each material ships three full cube
 * families (base, polished, bricks; each base/slab/stairs/wall) plus tiles, cracked
 * bricks, chiseled bricks and a pillar. All plain opaque requires-tool stone blocks;
 * any glow or translucency is texture flavor only.
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes,
 * EN+DE lang fragments) are generated by {@code devtools/gen/smolderquartz_gen.py}; the
 * tag fragment lives at {@code devtools/tagfrag/smolderquartz.json}; handbook pages are
 * registered by {@link SmolderQuartzHandbook}.
 */
public final class SmolderQuartzFeature {
	private SmolderQuartzFeature() {
	}

	// Full cube families (base + slab + stairs + wall).
	public static BlockFamily SMOLDER_QUARTZ;
	public static BlockFamily POLISHED_SMOLDER_QUARTZ;
	public static BlockFamily SMOLDER_QUARTZ_BRICKS;
	public static BlockFamily CINDER_CRYSTAL;
	public static BlockFamily POLISHED_CINDER_CRYSTAL;
	public static BlockFamily CINDER_CRYSTAL_BRICKS;
	public static BlockFamily FLAME_OPAL;
	public static BlockFamily POLISHED_FLAME_OPAL;
	public static BlockFamily FLAME_OPAL_BRICKS;
	public static BlockFamily EMBER_PRISM;
	public static BlockFamily POLISHED_EMBER_PRISM;
	public static BlockFamily EMBER_PRISM_BRICKS;
	public static BlockFamily ASHGLASS_STONE;
	public static BlockFamily POLISHED_ASHGLASS_STONE;
	public static BlockFamily ASHGLASS_STONE_BRICKS;
	public static BlockFamily GLOWSPAR;
	public static BlockFamily POLISHED_GLOWSPAR;
	public static BlockFamily GLOWSPAR_BRICKS;
	public static BlockFamily HEATLENS_STONE;
	public static BlockFamily POLISHED_HEATLENS_STONE;
	public static BlockFamily HEATLENS_STONE_BRICKS;
	public static BlockFamily MAGMA_GEODE;
	public static BlockFamily POLISHED_MAGMA_GEODE;
	public static BlockFamily MAGMA_GEODE_BRICKS;
	public static BlockFamily PYRITE_CRYSTAL;
	public static BlockFamily POLISHED_PYRITE_CRYSTAL;
	public static BlockFamily PYRITE_CRYSTAL_BRICKS;
	public static BlockFamily SULFUR_CRYSTAL;
	public static BlockFamily POLISHED_SULFUR_CRYSTAL;
	public static BlockFamily SULFUR_CRYSTAL_BRICKS;
	public static BlockFamily OBSID_GLASSBLOCK;
	public static BlockFamily POLISHED_OBSID_GLASSBLOCK;
	public static BlockFamily OBSID_GLASSBLOCK_BRICKS;
	public static BlockFamily EMBER_AMBER;
	public static BlockFamily POLISHED_EMBER_AMBER;
	public static BlockFamily EMBER_AMBER_BRICKS;
	public static BlockFamily FIRE_AGATE;
	public static BlockFamily POLISHED_FIRE_AGATE;
	public static BlockFamily FIRE_AGATE_BRICKS;
	public static BlockFamily LAVA_PEARL;
	public static BlockFamily POLISHED_LAVA_PEARL;
	public static BlockFamily LAVA_PEARL_BRICKS;

	// Single blocks.
	public static Block SMOLDER_QUARTZ_TILES;
	public static Block CRACKED_SMOLDER_QUARTZ_BRICKS;
	public static Block CHISELED_SMOLDER_QUARTZ_BRICKS;
	public static Block SMOLDER_QUARTZ_PILLAR;
	public static Block CINDER_CRYSTAL_TILES;
	public static Block CRACKED_CINDER_CRYSTAL_BRICKS;
	public static Block CHISELED_CINDER_CRYSTAL_BRICKS;
	public static Block CINDER_CRYSTAL_PILLAR;
	public static Block FLAME_OPAL_TILES;
	public static Block CRACKED_FLAME_OPAL_BRICKS;
	public static Block CHISELED_FLAME_OPAL_BRICKS;
	public static Block FLAME_OPAL_PILLAR;
	public static Block EMBER_PRISM_TILES;
	public static Block CRACKED_EMBER_PRISM_BRICKS;
	public static Block CHISELED_EMBER_PRISM_BRICKS;
	public static Block EMBER_PRISM_PILLAR;
	public static Block ASHGLASS_STONE_TILES;
	public static Block CRACKED_ASHGLASS_STONE_BRICKS;
	public static Block CHISELED_ASHGLASS_STONE_BRICKS;
	public static Block ASHGLASS_STONE_PILLAR;
	public static Block GLOWSPAR_TILES;
	public static Block CRACKED_GLOWSPAR_BRICKS;
	public static Block CHISELED_GLOWSPAR_BRICKS;
	public static Block GLOWSPAR_PILLAR;
	public static Block HEATLENS_STONE_TILES;
	public static Block CRACKED_HEATLENS_STONE_BRICKS;
	public static Block CHISELED_HEATLENS_STONE_BRICKS;
	public static Block HEATLENS_STONE_PILLAR;
	public static Block MAGMA_GEODE_TILES;
	public static Block CRACKED_MAGMA_GEODE_BRICKS;
	public static Block CHISELED_MAGMA_GEODE_BRICKS;
	public static Block MAGMA_GEODE_PILLAR;
	public static Block PYRITE_CRYSTAL_TILES;
	public static Block CRACKED_PYRITE_CRYSTAL_BRICKS;
	public static Block CHISELED_PYRITE_CRYSTAL_BRICKS;
	public static Block PYRITE_CRYSTAL_PILLAR;
	public static Block SULFUR_CRYSTAL_TILES;
	public static Block CRACKED_SULFUR_CRYSTAL_BRICKS;
	public static Block CHISELED_SULFUR_CRYSTAL_BRICKS;
	public static Block SULFUR_CRYSTAL_PILLAR;
	public static Block OBSID_GLASSBLOCK_TILES;
	public static Block CRACKED_OBSID_GLASSBLOCK_BRICKS;
	public static Block CHISELED_OBSID_GLASSBLOCK_BRICKS;
	public static Block OBSID_GLASSBLOCK_PILLAR;
	public static Block EMBER_AMBER_TILES;
	public static Block CRACKED_EMBER_AMBER_BRICKS;
	public static Block CHISELED_EMBER_AMBER_BRICKS;
	public static Block EMBER_AMBER_PILLAR;
	public static Block FIRE_AGATE_TILES;
	public static Block CRACKED_FIRE_AGATE_BRICKS;
	public static Block CHISELED_FIRE_AGATE_BRICKS;
	public static Block FIRE_AGATE_PILLAR;
	public static Block LAVA_PEARL_TILES;
	public static Block CRACKED_LAVA_PEARL_BRICKS;
	public static Block CHISELED_LAVA_PEARL_BRICKS;
	public static Block LAVA_PEARL_PILLAR;

	/**
	 * Fresh settings per block ({@link ModBlocks#register} writes a registry key into the
	 * instance, so settings must never be shared). Standard requires-tool stone profile
	 * (same numbers as the cinderstone feature); any glow is texture flavor only, every
	 * block stays a plain opaque stone block.
	 */
	private static AbstractBlock.Settings stoneSettings(MapColor color, BlockSoundGroup sounds) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.5F, 8.0F)
				.requiresTool()
				.sounds(sounds);
	}

	private static AbstractBlock.Settings smolderQuartzSettings() {
		return stoneSettings(MapColor.OFF_WHITE, BlockSoundGroup.AMETHYST_BLOCK);
	}

	private static AbstractBlock.Settings cinderCrystalSettings() {
		return stoneSettings(MapColor.DULL_RED, BlockSoundGroup.AMETHYST_BLOCK);
	}

	private static AbstractBlock.Settings flameOpalSettings() {
		return stoneSettings(MapColor.ORANGE, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings emberPrismSettings() {
		return stoneSettings(MapColor.BRIGHT_RED, BlockSoundGroup.AMETHYST_BLOCK);
	}

	private static AbstractBlock.Settings ashglassStoneSettings() {
		return stoneSettings(MapColor.LIGHT_GRAY, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings glowsparSettings() {
		return stoneSettings(MapColor.PALE_YELLOW, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings heatlensStoneSettings() {
		return stoneSettings(MapColor.GOLD, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings magmaGeodeSettings() {
		return stoneSettings(MapColor.DARK_RED, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings pyriteCrystalSettings() {
		return stoneSettings(MapColor.TERRACOTTA_YELLOW, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings sulfurCrystalSettings() {
		return stoneSettings(MapColor.YELLOW, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings obsidGlassblockSettings() {
		return stoneSettings(MapColor.BLACK, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings emberAmberSettings() {
		return stoneSettings(MapColor.TERRACOTTA_ORANGE, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings fireAgateSettings() {
		return stoneSettings(MapColor.TERRACOTTA_RED, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings lavaPearlSettings() {
		return stoneSettings(MapColor.DARK_CRIMSON, BlockSoundGroup.AMETHYST_BLOCK);
	}

	public static void init() {
		SMOLDER_QUARTZ = ModBlockFamilies.registerCubeFamily(
				"smolder_quartz", "smolder_quartz", SmolderQuartzFeature::smolderQuartzSettings, true);
		POLISHED_SMOLDER_QUARTZ = ModBlockFamilies.registerCubeFamily(
				"polished_smolder_quartz", "polished_smolder_quartz", SmolderQuartzFeature::smolderQuartzSettings, true);
		SMOLDER_QUARTZ_BRICKS = ModBlockFamilies.registerCubeFamily(
				"smolder_quartz_bricks", "smolder_quartz_brick", SmolderQuartzFeature::smolderQuartzSettings, true);
		CINDER_CRYSTAL = ModBlockFamilies.registerCubeFamily(
				"cinder_crystal", "cinder_crystal", SmolderQuartzFeature::cinderCrystalSettings, true);
		POLISHED_CINDER_CRYSTAL = ModBlockFamilies.registerCubeFamily(
				"polished_cinder_crystal", "polished_cinder_crystal", SmolderQuartzFeature::cinderCrystalSettings, true);
		CINDER_CRYSTAL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"cinder_crystal_bricks", "cinder_crystal_brick", SmolderQuartzFeature::cinderCrystalSettings, true);
		FLAME_OPAL = ModBlockFamilies.registerCubeFamily(
				"flame_opal", "flame_opal", SmolderQuartzFeature::flameOpalSettings, true);
		POLISHED_FLAME_OPAL = ModBlockFamilies.registerCubeFamily(
				"polished_flame_opal", "polished_flame_opal", SmolderQuartzFeature::flameOpalSettings, true);
		FLAME_OPAL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"flame_opal_bricks", "flame_opal_brick", SmolderQuartzFeature::flameOpalSettings, true);
		EMBER_PRISM = ModBlockFamilies.registerCubeFamily(
				"ember_prism", "ember_prism", SmolderQuartzFeature::emberPrismSettings, true);
		POLISHED_EMBER_PRISM = ModBlockFamilies.registerCubeFamily(
				"polished_ember_prism", "polished_ember_prism", SmolderQuartzFeature::emberPrismSettings, true);
		EMBER_PRISM_BRICKS = ModBlockFamilies.registerCubeFamily(
				"ember_prism_bricks", "ember_prism_brick", SmolderQuartzFeature::emberPrismSettings, true);
		ASHGLASS_STONE = ModBlockFamilies.registerCubeFamily(
				"ashglass_stone", "ashglass_stone", SmolderQuartzFeature::ashglassStoneSettings, true);
		POLISHED_ASHGLASS_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_ashglass_stone", "polished_ashglass_stone", SmolderQuartzFeature::ashglassStoneSettings, true);
		ASHGLASS_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"ashglass_stone_bricks", "ashglass_stone_brick", SmolderQuartzFeature::ashglassStoneSettings, true);
		GLOWSPAR = ModBlockFamilies.registerCubeFamily(
				"glowspar", "glowspar", SmolderQuartzFeature::glowsparSettings, true);
		POLISHED_GLOWSPAR = ModBlockFamilies.registerCubeFamily(
				"polished_glowspar", "polished_glowspar", SmolderQuartzFeature::glowsparSettings, true);
		GLOWSPAR_BRICKS = ModBlockFamilies.registerCubeFamily(
				"glowspar_bricks", "glowspar_brick", SmolderQuartzFeature::glowsparSettings, true);
		HEATLENS_STONE = ModBlockFamilies.registerCubeFamily(
				"heatlens_stone", "heatlens_stone", SmolderQuartzFeature::heatlensStoneSettings, true);
		POLISHED_HEATLENS_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_heatlens_stone", "polished_heatlens_stone", SmolderQuartzFeature::heatlensStoneSettings, true);
		HEATLENS_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"heatlens_stone_bricks", "heatlens_stone_brick", SmolderQuartzFeature::heatlensStoneSettings, true);
		MAGMA_GEODE = ModBlockFamilies.registerCubeFamily(
				"magma_geode", "magma_geode", SmolderQuartzFeature::magmaGeodeSettings, true);
		POLISHED_MAGMA_GEODE = ModBlockFamilies.registerCubeFamily(
				"polished_magma_geode", "polished_magma_geode", SmolderQuartzFeature::magmaGeodeSettings, true);
		MAGMA_GEODE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"magma_geode_bricks", "magma_geode_brick", SmolderQuartzFeature::magmaGeodeSettings, true);
		PYRITE_CRYSTAL = ModBlockFamilies.registerCubeFamily(
				"pyrite_crystal", "pyrite_crystal", SmolderQuartzFeature::pyriteCrystalSettings, true);
		POLISHED_PYRITE_CRYSTAL = ModBlockFamilies.registerCubeFamily(
				"polished_pyrite_crystal", "polished_pyrite_crystal", SmolderQuartzFeature::pyriteCrystalSettings, true);
		PYRITE_CRYSTAL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"pyrite_crystal_bricks", "pyrite_crystal_brick", SmolderQuartzFeature::pyriteCrystalSettings, true);
		SULFUR_CRYSTAL = ModBlockFamilies.registerCubeFamily(
				"sulfur_crystal", "sulfur_crystal", SmolderQuartzFeature::sulfurCrystalSettings, true);
		POLISHED_SULFUR_CRYSTAL = ModBlockFamilies.registerCubeFamily(
				"polished_sulfur_crystal", "polished_sulfur_crystal", SmolderQuartzFeature::sulfurCrystalSettings, true);
		SULFUR_CRYSTAL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"sulfur_crystal_bricks", "sulfur_crystal_brick", SmolderQuartzFeature::sulfurCrystalSettings, true);
		OBSID_GLASSBLOCK = ModBlockFamilies.registerCubeFamily(
				"obsid_glassblock", "obsid_glassblock", SmolderQuartzFeature::obsidGlassblockSettings, true);
		POLISHED_OBSID_GLASSBLOCK = ModBlockFamilies.registerCubeFamily(
				"polished_obsid_glassblock", "polished_obsid_glassblock", SmolderQuartzFeature::obsidGlassblockSettings, true);
		OBSID_GLASSBLOCK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"obsid_glassblock_bricks", "obsid_glassblock_brick", SmolderQuartzFeature::obsidGlassblockSettings, true);
		EMBER_AMBER = ModBlockFamilies.registerCubeFamily(
				"ember_amber", "ember_amber", SmolderQuartzFeature::emberAmberSettings, true);
		POLISHED_EMBER_AMBER = ModBlockFamilies.registerCubeFamily(
				"polished_ember_amber", "polished_ember_amber", SmolderQuartzFeature::emberAmberSettings, true);
		EMBER_AMBER_BRICKS = ModBlockFamilies.registerCubeFamily(
				"ember_amber_bricks", "ember_amber_brick", SmolderQuartzFeature::emberAmberSettings, true);
		FIRE_AGATE = ModBlockFamilies.registerCubeFamily(
				"fire_agate", "fire_agate", SmolderQuartzFeature::fireAgateSettings, true);
		POLISHED_FIRE_AGATE = ModBlockFamilies.registerCubeFamily(
				"polished_fire_agate", "polished_fire_agate", SmolderQuartzFeature::fireAgateSettings, true);
		FIRE_AGATE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"fire_agate_bricks", "fire_agate_brick", SmolderQuartzFeature::fireAgateSettings, true);
		LAVA_PEARL = ModBlockFamilies.registerCubeFamily(
				"lava_pearl", "lava_pearl", SmolderQuartzFeature::lavaPearlSettings, true);
		POLISHED_LAVA_PEARL = ModBlockFamilies.registerCubeFamily(
				"polished_lava_pearl", "polished_lava_pearl", SmolderQuartzFeature::lavaPearlSettings, true);
		LAVA_PEARL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"lava_pearl_bricks", "lava_pearl_brick", SmolderQuartzFeature::lavaPearlSettings, true);

		SMOLDER_QUARTZ_TILES = ModBlocks.register("smolder_quartz_tiles", Block::new, smolderQuartzSettings(), true);
		CRACKED_SMOLDER_QUARTZ_BRICKS = ModBlocks.register("cracked_smolder_quartz_bricks", Block::new, smolderQuartzSettings(), true);
		CHISELED_SMOLDER_QUARTZ_BRICKS = ModBlocks.register("chiseled_smolder_quartz_bricks", Block::new, smolderQuartzSettings(), true);
		SMOLDER_QUARTZ_PILLAR = ModBlocks.register("smolder_quartz_pillar", PillarBlock::new, smolderQuartzSettings(), true);
		CINDER_CRYSTAL_TILES = ModBlocks.register("cinder_crystal_tiles", Block::new, cinderCrystalSettings(), true);
		CRACKED_CINDER_CRYSTAL_BRICKS = ModBlocks.register("cracked_cinder_crystal_bricks", Block::new, cinderCrystalSettings(), true);
		CHISELED_CINDER_CRYSTAL_BRICKS = ModBlocks.register("chiseled_cinder_crystal_bricks", Block::new, cinderCrystalSettings(), true);
		CINDER_CRYSTAL_PILLAR = ModBlocks.register("cinder_crystal_pillar", PillarBlock::new, cinderCrystalSettings(), true);
		FLAME_OPAL_TILES = ModBlocks.register("flame_opal_tiles", Block::new, flameOpalSettings(), true);
		CRACKED_FLAME_OPAL_BRICKS = ModBlocks.register("cracked_flame_opal_bricks", Block::new, flameOpalSettings(), true);
		CHISELED_FLAME_OPAL_BRICKS = ModBlocks.register("chiseled_flame_opal_bricks", Block::new, flameOpalSettings(), true);
		FLAME_OPAL_PILLAR = ModBlocks.register("flame_opal_pillar", PillarBlock::new, flameOpalSettings(), true);
		EMBER_PRISM_TILES = ModBlocks.register("ember_prism_tiles", Block::new, emberPrismSettings(), true);
		CRACKED_EMBER_PRISM_BRICKS = ModBlocks.register("cracked_ember_prism_bricks", Block::new, emberPrismSettings(), true);
		CHISELED_EMBER_PRISM_BRICKS = ModBlocks.register("chiseled_ember_prism_bricks", Block::new, emberPrismSettings(), true);
		EMBER_PRISM_PILLAR = ModBlocks.register("ember_prism_pillar", PillarBlock::new, emberPrismSettings(), true);
		ASHGLASS_STONE_TILES = ModBlocks.register("ashglass_stone_tiles", Block::new, ashglassStoneSettings(), true);
		CRACKED_ASHGLASS_STONE_BRICKS = ModBlocks.register("cracked_ashglass_stone_bricks", Block::new, ashglassStoneSettings(), true);
		CHISELED_ASHGLASS_STONE_BRICKS = ModBlocks.register("chiseled_ashglass_stone_bricks", Block::new, ashglassStoneSettings(), true);
		ASHGLASS_STONE_PILLAR = ModBlocks.register("ashglass_stone_pillar", PillarBlock::new, ashglassStoneSettings(), true);
		GLOWSPAR_TILES = ModBlocks.register("glowspar_tiles", Block::new, glowsparSettings(), true);
		CRACKED_GLOWSPAR_BRICKS = ModBlocks.register("cracked_glowspar_bricks", Block::new, glowsparSettings(), true);
		CHISELED_GLOWSPAR_BRICKS = ModBlocks.register("chiseled_glowspar_bricks", Block::new, glowsparSettings(), true);
		GLOWSPAR_PILLAR = ModBlocks.register("glowspar_pillar", PillarBlock::new, glowsparSettings(), true);
		HEATLENS_STONE_TILES = ModBlocks.register("heatlens_stone_tiles", Block::new, heatlensStoneSettings(), true);
		CRACKED_HEATLENS_STONE_BRICKS = ModBlocks.register("cracked_heatlens_stone_bricks", Block::new, heatlensStoneSettings(), true);
		CHISELED_HEATLENS_STONE_BRICKS = ModBlocks.register("chiseled_heatlens_stone_bricks", Block::new, heatlensStoneSettings(), true);
		HEATLENS_STONE_PILLAR = ModBlocks.register("heatlens_stone_pillar", PillarBlock::new, heatlensStoneSettings(), true);
		MAGMA_GEODE_TILES = ModBlocks.register("magma_geode_tiles", Block::new, magmaGeodeSettings(), true);
		CRACKED_MAGMA_GEODE_BRICKS = ModBlocks.register("cracked_magma_geode_bricks", Block::new, magmaGeodeSettings(), true);
		CHISELED_MAGMA_GEODE_BRICKS = ModBlocks.register("chiseled_magma_geode_bricks", Block::new, magmaGeodeSettings(), true);
		MAGMA_GEODE_PILLAR = ModBlocks.register("magma_geode_pillar", PillarBlock::new, magmaGeodeSettings(), true);
		PYRITE_CRYSTAL_TILES = ModBlocks.register("pyrite_crystal_tiles", Block::new, pyriteCrystalSettings(), true);
		CRACKED_PYRITE_CRYSTAL_BRICKS = ModBlocks.register("cracked_pyrite_crystal_bricks", Block::new, pyriteCrystalSettings(), true);
		CHISELED_PYRITE_CRYSTAL_BRICKS = ModBlocks.register("chiseled_pyrite_crystal_bricks", Block::new, pyriteCrystalSettings(), true);
		PYRITE_CRYSTAL_PILLAR = ModBlocks.register("pyrite_crystal_pillar", PillarBlock::new, pyriteCrystalSettings(), true);
		SULFUR_CRYSTAL_TILES = ModBlocks.register("sulfur_crystal_tiles", Block::new, sulfurCrystalSettings(), true);
		CRACKED_SULFUR_CRYSTAL_BRICKS = ModBlocks.register("cracked_sulfur_crystal_bricks", Block::new, sulfurCrystalSettings(), true);
		CHISELED_SULFUR_CRYSTAL_BRICKS = ModBlocks.register("chiseled_sulfur_crystal_bricks", Block::new, sulfurCrystalSettings(), true);
		SULFUR_CRYSTAL_PILLAR = ModBlocks.register("sulfur_crystal_pillar", PillarBlock::new, sulfurCrystalSettings(), true);
		OBSID_GLASSBLOCK_TILES = ModBlocks.register("obsid_glassblock_tiles", Block::new, obsidGlassblockSettings(), true);
		CRACKED_OBSID_GLASSBLOCK_BRICKS = ModBlocks.register("cracked_obsid_glassblock_bricks", Block::new, obsidGlassblockSettings(), true);
		CHISELED_OBSID_GLASSBLOCK_BRICKS = ModBlocks.register("chiseled_obsid_glassblock_bricks", Block::new, obsidGlassblockSettings(), true);
		OBSID_GLASSBLOCK_PILLAR = ModBlocks.register("obsid_glassblock_pillar", PillarBlock::new, obsidGlassblockSettings(), true);
		EMBER_AMBER_TILES = ModBlocks.register("ember_amber_tiles", Block::new, emberAmberSettings(), true);
		CRACKED_EMBER_AMBER_BRICKS = ModBlocks.register("cracked_ember_amber_bricks", Block::new, emberAmberSettings(), true);
		CHISELED_EMBER_AMBER_BRICKS = ModBlocks.register("chiseled_ember_amber_bricks", Block::new, emberAmberSettings(), true);
		EMBER_AMBER_PILLAR = ModBlocks.register("ember_amber_pillar", PillarBlock::new, emberAmberSettings(), true);
		FIRE_AGATE_TILES = ModBlocks.register("fire_agate_tiles", Block::new, fireAgateSettings(), true);
		CRACKED_FIRE_AGATE_BRICKS = ModBlocks.register("cracked_fire_agate_bricks", Block::new, fireAgateSettings(), true);
		CHISELED_FIRE_AGATE_BRICKS = ModBlocks.register("chiseled_fire_agate_bricks", Block::new, fireAgateSettings(), true);
		FIRE_AGATE_PILLAR = ModBlocks.register("fire_agate_pillar", PillarBlock::new, fireAgateSettings(), true);
		LAVA_PEARL_TILES = ModBlocks.register("lava_pearl_tiles", Block::new, lavaPearlSettings(), true);
		CRACKED_LAVA_PEARL_BRICKS = ModBlocks.register("cracked_lava_pearl_bricks", Block::new, lavaPearlSettings(), true);
		CHISELED_LAVA_PEARL_BRICKS = ModBlocks.register("chiseled_lava_pearl_bricks", Block::new, lavaPearlSettings(), true);
		LAVA_PEARL_PILLAR = ModBlocks.register("lava_pearl_pillar", PillarBlock::new, lavaPearlSettings(), true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.SETS_KEY).register(entries -> {
			entries.add(SMOLDER_QUARTZ.block());
			entries.add(SMOLDER_QUARTZ.stairs());
			entries.add(SMOLDER_QUARTZ.slab());
			entries.add(SMOLDER_QUARTZ.wall());
			entries.add(POLISHED_SMOLDER_QUARTZ.block());
			entries.add(POLISHED_SMOLDER_QUARTZ.stairs());
			entries.add(POLISHED_SMOLDER_QUARTZ.slab());
			entries.add(POLISHED_SMOLDER_QUARTZ.wall());
			entries.add(SMOLDER_QUARTZ_BRICKS.block());
			entries.add(SMOLDER_QUARTZ_BRICKS.stairs());
			entries.add(SMOLDER_QUARTZ_BRICKS.slab());
			entries.add(SMOLDER_QUARTZ_BRICKS.wall());
			entries.add(SMOLDER_QUARTZ_TILES);
			entries.add(CRACKED_SMOLDER_QUARTZ_BRICKS);
			entries.add(CHISELED_SMOLDER_QUARTZ_BRICKS);
			entries.add(SMOLDER_QUARTZ_PILLAR);
			entries.add(CINDER_CRYSTAL.block());
			entries.add(CINDER_CRYSTAL.stairs());
			entries.add(CINDER_CRYSTAL.slab());
			entries.add(CINDER_CRYSTAL.wall());
			entries.add(POLISHED_CINDER_CRYSTAL.block());
			entries.add(POLISHED_CINDER_CRYSTAL.stairs());
			entries.add(POLISHED_CINDER_CRYSTAL.slab());
			entries.add(POLISHED_CINDER_CRYSTAL.wall());
			entries.add(CINDER_CRYSTAL_BRICKS.block());
			entries.add(CINDER_CRYSTAL_BRICKS.stairs());
			entries.add(CINDER_CRYSTAL_BRICKS.slab());
			entries.add(CINDER_CRYSTAL_BRICKS.wall());
			entries.add(CINDER_CRYSTAL_TILES);
			entries.add(CRACKED_CINDER_CRYSTAL_BRICKS);
			entries.add(CHISELED_CINDER_CRYSTAL_BRICKS);
			entries.add(CINDER_CRYSTAL_PILLAR);
			entries.add(FLAME_OPAL.block());
			entries.add(FLAME_OPAL.stairs());
			entries.add(FLAME_OPAL.slab());
			entries.add(FLAME_OPAL.wall());
			entries.add(POLISHED_FLAME_OPAL.block());
			entries.add(POLISHED_FLAME_OPAL.stairs());
			entries.add(POLISHED_FLAME_OPAL.slab());
			entries.add(POLISHED_FLAME_OPAL.wall());
			entries.add(FLAME_OPAL_BRICKS.block());
			entries.add(FLAME_OPAL_BRICKS.stairs());
			entries.add(FLAME_OPAL_BRICKS.slab());
			entries.add(FLAME_OPAL_BRICKS.wall());
			entries.add(FLAME_OPAL_TILES);
			entries.add(CRACKED_FLAME_OPAL_BRICKS);
			entries.add(CHISELED_FLAME_OPAL_BRICKS);
			entries.add(FLAME_OPAL_PILLAR);
			entries.add(EMBER_PRISM.block());
			entries.add(EMBER_PRISM.stairs());
			entries.add(EMBER_PRISM.slab());
			entries.add(EMBER_PRISM.wall());
			entries.add(POLISHED_EMBER_PRISM.block());
			entries.add(POLISHED_EMBER_PRISM.stairs());
			entries.add(POLISHED_EMBER_PRISM.slab());
			entries.add(POLISHED_EMBER_PRISM.wall());
			entries.add(EMBER_PRISM_BRICKS.block());
			entries.add(EMBER_PRISM_BRICKS.stairs());
			entries.add(EMBER_PRISM_BRICKS.slab());
			entries.add(EMBER_PRISM_BRICKS.wall());
			entries.add(EMBER_PRISM_TILES);
			entries.add(CRACKED_EMBER_PRISM_BRICKS);
			entries.add(CHISELED_EMBER_PRISM_BRICKS);
			entries.add(EMBER_PRISM_PILLAR);
			entries.add(ASHGLASS_STONE.block());
			entries.add(ASHGLASS_STONE.stairs());
			entries.add(ASHGLASS_STONE.slab());
			entries.add(ASHGLASS_STONE.wall());
			entries.add(POLISHED_ASHGLASS_STONE.block());
			entries.add(POLISHED_ASHGLASS_STONE.stairs());
			entries.add(POLISHED_ASHGLASS_STONE.slab());
			entries.add(POLISHED_ASHGLASS_STONE.wall());
			entries.add(ASHGLASS_STONE_BRICKS.block());
			entries.add(ASHGLASS_STONE_BRICKS.stairs());
			entries.add(ASHGLASS_STONE_BRICKS.slab());
			entries.add(ASHGLASS_STONE_BRICKS.wall());
			entries.add(ASHGLASS_STONE_TILES);
			entries.add(CRACKED_ASHGLASS_STONE_BRICKS);
			entries.add(CHISELED_ASHGLASS_STONE_BRICKS);
			entries.add(ASHGLASS_STONE_PILLAR);
			entries.add(GLOWSPAR.block());
			entries.add(GLOWSPAR.stairs());
			entries.add(GLOWSPAR.slab());
			entries.add(GLOWSPAR.wall());
			entries.add(POLISHED_GLOWSPAR.block());
			entries.add(POLISHED_GLOWSPAR.stairs());
			entries.add(POLISHED_GLOWSPAR.slab());
			entries.add(POLISHED_GLOWSPAR.wall());
			entries.add(GLOWSPAR_BRICKS.block());
			entries.add(GLOWSPAR_BRICKS.stairs());
			entries.add(GLOWSPAR_BRICKS.slab());
			entries.add(GLOWSPAR_BRICKS.wall());
			entries.add(GLOWSPAR_TILES);
			entries.add(CRACKED_GLOWSPAR_BRICKS);
			entries.add(CHISELED_GLOWSPAR_BRICKS);
			entries.add(GLOWSPAR_PILLAR);
			entries.add(HEATLENS_STONE.block());
			entries.add(HEATLENS_STONE.stairs());
			entries.add(HEATLENS_STONE.slab());
			entries.add(HEATLENS_STONE.wall());
			entries.add(POLISHED_HEATLENS_STONE.block());
			entries.add(POLISHED_HEATLENS_STONE.stairs());
			entries.add(POLISHED_HEATLENS_STONE.slab());
			entries.add(POLISHED_HEATLENS_STONE.wall());
			entries.add(HEATLENS_STONE_BRICKS.block());
			entries.add(HEATLENS_STONE_BRICKS.stairs());
			entries.add(HEATLENS_STONE_BRICKS.slab());
			entries.add(HEATLENS_STONE_BRICKS.wall());
			entries.add(HEATLENS_STONE_TILES);
			entries.add(CRACKED_HEATLENS_STONE_BRICKS);
			entries.add(CHISELED_HEATLENS_STONE_BRICKS);
			entries.add(HEATLENS_STONE_PILLAR);
			entries.add(MAGMA_GEODE.block());
			entries.add(MAGMA_GEODE.stairs());
			entries.add(MAGMA_GEODE.slab());
			entries.add(MAGMA_GEODE.wall());
			entries.add(POLISHED_MAGMA_GEODE.block());
			entries.add(POLISHED_MAGMA_GEODE.stairs());
			entries.add(POLISHED_MAGMA_GEODE.slab());
			entries.add(POLISHED_MAGMA_GEODE.wall());
			entries.add(MAGMA_GEODE_BRICKS.block());
			entries.add(MAGMA_GEODE_BRICKS.stairs());
			entries.add(MAGMA_GEODE_BRICKS.slab());
			entries.add(MAGMA_GEODE_BRICKS.wall());
			entries.add(MAGMA_GEODE_TILES);
			entries.add(CRACKED_MAGMA_GEODE_BRICKS);
			entries.add(CHISELED_MAGMA_GEODE_BRICKS);
			entries.add(MAGMA_GEODE_PILLAR);
			entries.add(PYRITE_CRYSTAL.block());
			entries.add(PYRITE_CRYSTAL.stairs());
			entries.add(PYRITE_CRYSTAL.slab());
			entries.add(PYRITE_CRYSTAL.wall());
			entries.add(POLISHED_PYRITE_CRYSTAL.block());
			entries.add(POLISHED_PYRITE_CRYSTAL.stairs());
			entries.add(POLISHED_PYRITE_CRYSTAL.slab());
			entries.add(POLISHED_PYRITE_CRYSTAL.wall());
			entries.add(PYRITE_CRYSTAL_BRICKS.block());
			entries.add(PYRITE_CRYSTAL_BRICKS.stairs());
			entries.add(PYRITE_CRYSTAL_BRICKS.slab());
			entries.add(PYRITE_CRYSTAL_BRICKS.wall());
			entries.add(PYRITE_CRYSTAL_TILES);
			entries.add(CRACKED_PYRITE_CRYSTAL_BRICKS);
			entries.add(CHISELED_PYRITE_CRYSTAL_BRICKS);
			entries.add(PYRITE_CRYSTAL_PILLAR);
			entries.add(SULFUR_CRYSTAL.block());
			entries.add(SULFUR_CRYSTAL.stairs());
			entries.add(SULFUR_CRYSTAL.slab());
			entries.add(SULFUR_CRYSTAL.wall());
			entries.add(POLISHED_SULFUR_CRYSTAL.block());
			entries.add(POLISHED_SULFUR_CRYSTAL.stairs());
			entries.add(POLISHED_SULFUR_CRYSTAL.slab());
			entries.add(POLISHED_SULFUR_CRYSTAL.wall());
			entries.add(SULFUR_CRYSTAL_BRICKS.block());
			entries.add(SULFUR_CRYSTAL_BRICKS.stairs());
			entries.add(SULFUR_CRYSTAL_BRICKS.slab());
			entries.add(SULFUR_CRYSTAL_BRICKS.wall());
			entries.add(SULFUR_CRYSTAL_TILES);
			entries.add(CRACKED_SULFUR_CRYSTAL_BRICKS);
			entries.add(CHISELED_SULFUR_CRYSTAL_BRICKS);
			entries.add(SULFUR_CRYSTAL_PILLAR);
			entries.add(OBSID_GLASSBLOCK.block());
			entries.add(OBSID_GLASSBLOCK.stairs());
			entries.add(OBSID_GLASSBLOCK.slab());
			entries.add(OBSID_GLASSBLOCK.wall());
			entries.add(POLISHED_OBSID_GLASSBLOCK.block());
			entries.add(POLISHED_OBSID_GLASSBLOCK.stairs());
			entries.add(POLISHED_OBSID_GLASSBLOCK.slab());
			entries.add(POLISHED_OBSID_GLASSBLOCK.wall());
			entries.add(OBSID_GLASSBLOCK_BRICKS.block());
			entries.add(OBSID_GLASSBLOCK_BRICKS.stairs());
			entries.add(OBSID_GLASSBLOCK_BRICKS.slab());
			entries.add(OBSID_GLASSBLOCK_BRICKS.wall());
			entries.add(OBSID_GLASSBLOCK_TILES);
			entries.add(CRACKED_OBSID_GLASSBLOCK_BRICKS);
			entries.add(CHISELED_OBSID_GLASSBLOCK_BRICKS);
			entries.add(OBSID_GLASSBLOCK_PILLAR);
			entries.add(EMBER_AMBER.block());
			entries.add(EMBER_AMBER.stairs());
			entries.add(EMBER_AMBER.slab());
			entries.add(EMBER_AMBER.wall());
			entries.add(POLISHED_EMBER_AMBER.block());
			entries.add(POLISHED_EMBER_AMBER.stairs());
			entries.add(POLISHED_EMBER_AMBER.slab());
			entries.add(POLISHED_EMBER_AMBER.wall());
			entries.add(EMBER_AMBER_BRICKS.block());
			entries.add(EMBER_AMBER_BRICKS.stairs());
			entries.add(EMBER_AMBER_BRICKS.slab());
			entries.add(EMBER_AMBER_BRICKS.wall());
			entries.add(EMBER_AMBER_TILES);
			entries.add(CRACKED_EMBER_AMBER_BRICKS);
			entries.add(CHISELED_EMBER_AMBER_BRICKS);
			entries.add(EMBER_AMBER_PILLAR);
			entries.add(FIRE_AGATE.block());
			entries.add(FIRE_AGATE.stairs());
			entries.add(FIRE_AGATE.slab());
			entries.add(FIRE_AGATE.wall());
			entries.add(POLISHED_FIRE_AGATE.block());
			entries.add(POLISHED_FIRE_AGATE.stairs());
			entries.add(POLISHED_FIRE_AGATE.slab());
			entries.add(POLISHED_FIRE_AGATE.wall());
			entries.add(FIRE_AGATE_BRICKS.block());
			entries.add(FIRE_AGATE_BRICKS.stairs());
			entries.add(FIRE_AGATE_BRICKS.slab());
			entries.add(FIRE_AGATE_BRICKS.wall());
			entries.add(FIRE_AGATE_TILES);
			entries.add(CRACKED_FIRE_AGATE_BRICKS);
			entries.add(CHISELED_FIRE_AGATE_BRICKS);
			entries.add(FIRE_AGATE_PILLAR);
			entries.add(LAVA_PEARL.block());
			entries.add(LAVA_PEARL.stairs());
			entries.add(LAVA_PEARL.slab());
			entries.add(LAVA_PEARL.wall());
			entries.add(POLISHED_LAVA_PEARL.block());
			entries.add(POLISHED_LAVA_PEARL.stairs());
			entries.add(POLISHED_LAVA_PEARL.slab());
			entries.add(POLISHED_LAVA_PEARL.wall());
			entries.add(LAVA_PEARL_BRICKS.block());
			entries.add(LAVA_PEARL_BRICKS.stairs());
			entries.add(LAVA_PEARL_BRICKS.slab());
			entries.add(LAVA_PEARL_BRICKS.wall());
			entries.add(LAVA_PEARL_TILES);
			entries.add(CRACKED_LAVA_PEARL_BRICKS);
			entries.add(CHISELED_LAVA_PEARL_BRICKS);
			entries.add(LAVA_PEARL_PILLAR);
		});

		SmolderQuartzHandbook.register();
	}
}
