package net.sonic0810.copperinferno.feature.companions;

import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.SpawnLocationTypes;
import net.minecraft.entity.SpawnRestriction;
import net.minecraft.entity.passive.AnimalEntity;
import net.minecraft.entity.passive.CatEntity;
import net.minecraft.entity.passive.WolfEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.util.math.Vec3d;
import net.minecraft.world.Heightmap;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4.1 "Companions" feature: two tameable pets, each extending a vanilla tameable and reusing
 * a vanilla renderer with a copper_inferno entity texture (see {@code CompanionsFeatureClient}).
 * EntityType dimensions/eye heights are copied from the vanilla EntityType registrations (same
 * bytecode-verified values as the copperfauna Gutter Cat and infernofauna Cinder Hound).
 *
 * <ul>
 * <li>{@link CopperKitEntity Copper Kit} — a cat whose sitting purr grants its owner Haste.</li>
 * <li>{@link EmberHoundEntity Ember Hound} — a fire-immune wolf whose bite ignites.</li>
 * </ul>
 *
 * Both get a spawn egg (FAUNA creative tab), an entity loot table and rare natural Overworld
 * spawns (assets/loot/lang generated by {@code devtools/gen/companions_gen.py}).
 */
public final class CompanionsFeature {
	private CompanionsFeature() {
	}

	public static EntityType<CopperKitEntity> COPPER_KIT;
	public static EntityType<EmberHoundEntity> EMBER_HOUND;

	public static Item COPPER_KIT_SPAWN_EGG;
	public static Item EMBER_HOUND_SPAWN_EGG;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		registerSpawning();
		registerHandbookEntries();
	}

	private static void registerEntityTypes() {
		// cat = dimensions(0.6, 0.7).eyeHeight(0.35).passengerAttachments(0.5125).maxTrackingRange(8)
		COPPER_KIT = ModEntities.register("copper_kit",
				EntityType.Builder.create(CopperKitEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.6f, 0.7f)
						.eyeHeight(0.35f)
						.passengerAttachments(0.5125f)
						.maxTrackingRange(8));
		// wolf = dimensions(0.6, 0.85).eyeHeight(0.68)
		// .passengerAttachments(new Vec3d(0.0, 0.81875, -0.0625)).maxTrackingRange(10);
		// makeFireImmune() is the pet's fire-immunity tweak (Entity.isFireImmune reads the
		// EntityType flag — same mechanism as the infernofauna Magma Hopper).
		EMBER_HOUND = ModEntities.register("ember_hound",
				EntityType.Builder.create(EmberHoundEntity::new, SpawnGroup.CREATURE)
						.makeFireImmune()
						.dimensions(0.6f, 0.85f)
						.eyeHeight(0.68f)
						.passengerAttachments(new Vec3d(0.0, 0.81875, -0.0625))
						.maxTrackingRange(10));
	}

	private static void registerAttributes() {
		FabricDefaultAttributeRegistry.register(COPPER_KIT, CatEntity.createCatAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_HOUND, WolfEntity.createWolfAttributes());
	}

	private static void registerItems() {
		// Item.Settings.spawnEgg(type) stores the ENTITY_DATA component the vanilla SpawnEggItem
		// reads its entity type from in 1.21.9 (same proven pattern as the fauna-pack eggs).
		COPPER_KIT_SPAWN_EGG = ModItems.register("copper_kit_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(COPPER_KIT));
		EMBER_HOUND_SPAWN_EGG = ModItems.register("ember_hound_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_HOUND));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.FAUNA_KEY).register(entries -> {
			entries.add(COPPER_KIT_SPAWN_EGG);
			entries.add(EMBER_HOUND_SPAWN_EGG);
		});
	}

	private static void registerSpawning() {
		// Same proven pattern as CopperFaunaFeature.registerSpawning: SpawnRestriction.register
		// is access-widened by Fabric's transitive access wideners; both pets are animals, so
		// they reuse AnimalEntity::isValidNaturalSpawn.
		SpawnRestriction.register(COPPER_KIT, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, AnimalEntity::isValidNaturalSpawn);
		SpawnRestriction.register(EMBER_HOUND, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, AnimalEntity::isValidNaturalSpawn);

		// Rare natural Overworld spawns: weight 2, singletons — companions should be a find,
		// not a flood.
		var overworld = BiomeSelectors.foundInOverworld();
		BiomeModifications.addSpawn(overworld, SpawnGroup.CREATURE, COPPER_KIT, 2, 1, 1);
		BiomeModifications.addSpawn(overworld, SpawnGroup.CREATURE, EMBER_HOUND, 2, 1, 1);
	}

	private static void registerHandbookEntries() {
		HandbookEntries.add(new HandbookEntry("mobs", "copper_kit",
				"copper_inferno:copper_kit_spawn_egg", null, null, null, 0,
				"Copper Kit - a copper-furred kitten, tameable like any cat. While it sits and purrs, "
						+ "its owner nearby is granted Haste every so often. Drops String.",
				"Kupferkätzchen - ein kupferfarbenes Kätzchen, zähmbar wie jede Katze. Sitzt es schnurrend, "
						+ "erhält sein Besitzer in der Nähe regelmäßig Eile. Lässt Fäden fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "ember_hound",
				"copper_inferno:ember_hound_spawn_egg", null, null, null, 0,
				"Ember Hound - a hound with embers under its coat, tameable like any wolf. Fire cannot "
						+ "harm it, and its bite sets prey alight. Drops Bones.",
				"Gluthund - ein Hund mit Glut unter dem Fell, zähmbar wie jeder Wolf. Feuer kann ihm "
						+ "nichts anhaben, und sein Biss entzündet die Beute. Lässt Knochen fallen."));
	}
}
