package net.sonic0810.copperinferno.feature.depthstone;

import net.minecraft.block.AbstractBlock;
import net.minecraft.block.MapColor;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.content.PaletteSets;
import net.sonic0810.copperinferno.core.content.PaletteSets.PaletteSet;

/**
 * v4 "Depthstone" feature: 16 dark-stone palettes x the 20-block PaletteSets template
 * = 320 building blocks for deep/underground builds, all in the "The Depths" creative tab.
 *
 * <p>AUDIT CONTRACT: every {@link PaletteSets#registerPaletteSet} call below passes a string
 * literal as the leading palette argument (16 literal call sites, one per palette).
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes, EN+DE lang
 * fragments) are generated by {@code devtools/gen/depthstone_gen.py}; the tag fragment lives at
 * {@code devtools/tagfrag/depthstone.json}; handbook pages are registered by
 * {@link DepthStoneHandbook}.
 */
public final class DepthStoneFeature {
	private DepthStoneFeature() {
	}

	public static PaletteSet VOIDSTONE;
	public static PaletteSet DUSKSHALE;
	public static PaletteSet PYROCLAST;
	public static PaletteSet CINDERMARL;
	public static PaletteSet FUMAROLITE;
	public static PaletteSet SCORCHSLATE;
	public static PaletteSet EMBERCHERT;
	public static PaletteSet SLAGBASALT;
	public static PaletteSet ASHFLINT;
	public static PaletteSet CHARWACKE;
	public static PaletteSet SMOKESTONE;
	public static PaletteSet KILNROCK;
	public static PaletteSet MAGMARL;
	public static PaletteSet SOOTSTONE;
	public static PaletteSet VITRICITE;
	public static PaletteSet COALSPAR;

	/**
	 * Fresh stone settings per block ({@code ModBlocks.register} writes a registry key into the
	 * instance, so settings must never be shared). Standard depthstone stone profile.
	 */
	private static AbstractBlock.Settings depthStoneSettings(MapColor color, BlockSoundGroup sounds) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.5F, 8.0F)
				.requiresTool()
				.sounds(sounds);
	}

	/** Copies the cinderstone glass profile: fragile, glass sounds, nonOpaque, NO requiresTool. */
	private static AbstractBlock.Settings depthGlassSettings() {
		return AbstractBlock.Settings.create()
				.strength(0.4F)
				.sounds(BlockSoundGroup.GLASS)
				.nonOpaque();
	}

	/** Shared lamp/lantern profile: full light, requiresTool (PaletteSets adds nonOpaque for the lantern). */
	private static AbstractBlock.Settings depthLampSettings(MapColor color) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.5F, 8.0F)
				.requiresTool()
				.luminance(state -> 15)
				.sounds(BlockSoundGroup.LANTERN);
	}

	public static void init() {
		VOIDSTONE = PaletteSets.registerPaletteSet("voidstone",
				() -> depthStoneSettings(MapColor.BLACK, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.BLACK),
				ModCreativeTab.DEPTHS_KEY);
		DUSKSHALE = PaletteSets.registerPaletteSet("duskshale",
				() -> depthStoneSettings(MapColor.DEEPSLATE_GRAY, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.DEEPSLATE_GRAY),
				ModCreativeTab.DEPTHS_KEY);
		PYROCLAST = PaletteSets.registerPaletteSet("pyroclast",
				() -> depthStoneSettings(MapColor.DARK_RED, BlockSoundGroup.BASALT),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.DARK_RED),
				ModCreativeTab.DEPTHS_KEY);
		CINDERMARL = PaletteSets.registerPaletteSet("cindermarl",
				() -> depthStoneSettings(MapColor.TERRACOTTA_BROWN, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.TERRACOTTA_BROWN),
				ModCreativeTab.DEPTHS_KEY);
		FUMAROLITE = PaletteSets.registerPaletteSet("fumarolite",
				() -> depthStoneSettings(MapColor.TERRACOTTA_YELLOW, BlockSoundGroup.BASALT),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.TERRACOTTA_YELLOW),
				ModCreativeTab.DEPTHS_KEY);
		SCORCHSLATE = PaletteSets.registerPaletteSet("scorchslate",
				() -> depthStoneSettings(MapColor.TERRACOTTA_BLACK, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.TERRACOTTA_BLACK),
				ModCreativeTab.DEPTHS_KEY);
		EMBERCHERT = PaletteSets.registerPaletteSet("emberchert",
				() -> depthStoneSettings(MapColor.TERRACOTTA_ORANGE, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.TERRACOTTA_ORANGE),
				ModCreativeTab.DEPTHS_KEY);
		SLAGBASALT = PaletteSets.registerPaletteSet("slagbasalt",
				() -> depthStoneSettings(MapColor.TEAL, BlockSoundGroup.BASALT),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.TEAL),
				ModCreativeTab.DEPTHS_KEY);
		ASHFLINT = PaletteSets.registerPaletteSet("ashflint",
				() -> depthStoneSettings(MapColor.LIGHT_GRAY, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.LIGHT_GRAY),
				ModCreativeTab.DEPTHS_KEY);
		CHARWACKE = PaletteSets.registerPaletteSet("charwacke",
				() -> depthStoneSettings(MapColor.SPRUCE_BROWN, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.SPRUCE_BROWN),
				ModCreativeTab.DEPTHS_KEY);
		SMOKESTONE = PaletteSets.registerPaletteSet("smokestone",
				() -> depthStoneSettings(MapColor.GRAY, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.GRAY),
				ModCreativeTab.DEPTHS_KEY);
		KILNROCK = PaletteSets.registerPaletteSet("kilnrock",
				() -> depthStoneSettings(MapColor.TERRACOTTA_RED, BlockSoundGroup.BASALT),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.TERRACOTTA_RED),
				ModCreativeTab.DEPTHS_KEY);
		MAGMARL = PaletteSets.registerPaletteSet("magmarl",
				() -> depthStoneSettings(MapColor.DULL_RED, BlockSoundGroup.BASALT),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.DULL_RED),
				ModCreativeTab.DEPTHS_KEY);
		SOOTSTONE = PaletteSets.registerPaletteSet("sootstone",
				() -> depthStoneSettings(MapColor.BLACK, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.BLACK),
				ModCreativeTab.DEPTHS_KEY);
		VITRICITE = PaletteSets.registerPaletteSet("vitricite",
				() -> depthStoneSettings(MapColor.LAPIS_BLUE, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.LAPIS_BLUE),
				ModCreativeTab.DEPTHS_KEY);
		COALSPAR = PaletteSets.registerPaletteSet("coalspar",
				() -> depthStoneSettings(MapColor.STONE_GRAY, BlockSoundGroup.DEEPSLATE),
				DepthStoneFeature::depthGlassSettings,
				() -> depthLampSettings(MapColor.STONE_GRAY),
				ModCreativeTab.DEPTHS_KEY);

		DepthStoneHandbook.register();
	}
}
