package net.sonic0810.copperinferno.feature.infernium;

import java.util.EnumMap;
import java.util.Map;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.item.AxeItem;
import net.minecraft.item.HoeItem;
import net.minecraft.item.Item;
import net.minecraft.item.ShovelItem;
import net.minecraft.item.SmithingTemplateItem;
import net.minecraft.item.ToolMaterial;
import net.minecraft.item.equipment.ArmorMaterial;
import net.minecraft.item.equipment.EquipmentAsset;
import net.minecraft.item.equipment.EquipmentAssetKeys;
import net.minecraft.item.equipment.EquipmentType;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * Infernium: the Inferno dimension's material economy plus a full new tool &amp; armor tier.
 *
 * <p>21 items (raw ore drop, ingot/nugget, smolder crystal, ember dust, slag chunk, ash pile,
 * cinder rod, plate/gear/lens machining parts, an upgrade smithing template, 5 tools, 4 armor
 * pieces) and 2 storage blocks. Raw Infernium and Smolder Crystals are mined in the Inferno
 * dimension; everything else derives from them via the recipes in
 * {@code data/copper_inferno/recipe/infernium/}. Assets are generated by
 * {@code devtools/gen/infernium_gen.py}.
 *
 * <p>Tier stats sit between diamond and netherite (slightly below netherite): tools use a
 * {@link ToolMaterial} with durability 1100 / speed 7.5 / +2.5 damage / enchantability 18,
 * armor defends like iron+1 per piece with 2.5 toughness and a little knockback resistance.
 * Both repair from the {@code copper_inferno:infernium_repair} item tag (infernium ingots).
 *
 * <p>Worn-armor rendering uses the CUSTOM equipment asset
 * {@code copper_inferno:infernium} ({@code assets/copper_inferno/equipment/infernium.json} +
 * ember-recolored humanoid / humanoid_leggings layer textures) — not the COPPER fallback.
 */
public final class InferniumFeature {
	private InferniumFeature() {
	}

	/** Repair tag, backed by data/copper_inferno/tags/item/infernium_repair.json. */
	public static final TagKey<Item> REPAIRS_INFERNIUM = TagKey.of(RegistryKeys.ITEM, CopperInferno.id("infernium_repair"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed, attackDamageBonus,
	 * enchantmentValue, repairItems) — verified via javap. Netherite-adjacent but slightly
	 * below (netherite: 2031/9.0/4.0/15, diamond: 1561/8.0/3.0/10).
	 */
	public static final ToolMaterial TOOL_MATERIAL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_DIAMOND_TOOL, 1100, 7.5F, 2.5F, 18, REPAIRS_INFERNIUM);

	/** Custom worn-armor asset: assets/copper_inferno/equipment/infernium.json. */
	public static final RegistryKey<EquipmentAsset> EQUIPMENT_ASSET_ID =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("infernium"));

	/**
	 * ArmorMaterial is a record: (durability, defense map, enchantmentValue, equipSound,
	 * toughness, knockbackResistance, repairIngredient, assetId) — verified via javap.
	 * Defense is iron+1 per piece (iron is boots 2 / leggings 5 / chestplate 6 / helmet 2;
	 * vanilla ArmorMaterials.createDefenseMap order confirmed from bytecode:
	 * boots, leggings, chestplate, helmet, body).
	 */
	public static final ArmorMaterial ARMOR_MATERIAL = new ArmorMaterial(
			30, defenseMap(3, 6, 7, 3, 6), 14, SoundEvents.ITEM_ARMOR_EQUIP_NETHERITE,
			2.5F, 0.05F, REPAIRS_INFERNIUM, EQUIPMENT_ASSET_ID);

	// Materials
	public static Item RAW_INFERNIUM;
	public static Item INFERNIUM_INGOT;
	public static Item INFERNIUM_NUGGET;
	public static Item SMOLDER_CRYSTAL;
	public static Item EMBER_DUST;
	public static Item SLAG_CHUNK;
	public static Item ASH_PILE;
	public static Item CINDER_ROD;
	public static Item INFERNIUM_PLATE;
	public static Item INFERNIUM_GEAR;
	public static Item SMOLDER_LENS;
	public static Item INFERNIUM_UPGRADE_SMITHING_TEMPLATE;

	// Tools
	public static Item INFERNIUM_SWORD;
	public static Item INFERNIUM_PICKAXE;
	public static Item INFERNIUM_AXE;
	public static Item INFERNIUM_SHOVEL;
	public static Item INFERNIUM_HOE;

	// Armor
	public static Item INFERNIUM_HELMET;
	public static Item INFERNIUM_CHESTPLATE;
	public static Item INFERNIUM_LEGGINGS;
	public static Item INFERNIUM_BOOTS;

	// Blocks
	public static Block INFERNIUM_BLOCK;
	public static Block SMOLDER_CRYSTAL_BLOCK;

	private static Map<EquipmentType, Integer> defenseMap(int boots, int leggings, int chestplate, int helmet, int body) {
		Map<EquipmentType, Integer> map = new EnumMap<>(EquipmentType.class);
		map.put(EquipmentType.BOOTS, boots);
		map.put(EquipmentType.LEGGINGS, leggings);
		map.put(EquipmentType.CHESTPLATE, chestplate);
		map.put(EquipmentType.HELMET, helmet);
		map.put(EquipmentType.BODY, body);
		return map;
	}

	public static void init() {
		// ----- materials (fresh Settings per item; infernium itself is fire-born -> fireproof)
		RAW_INFERNIUM = ModItems.register("raw_infernium", Item::new, new Item.Settings().fireproof());
		INFERNIUM_INGOT = ModItems.register("infernium_ingot", Item::new, new Item.Settings().fireproof());
		INFERNIUM_NUGGET = ModItems.register("infernium_nugget", Item::new, new Item.Settings().fireproof());
		SMOLDER_CRYSTAL = ModItems.register("smolder_crystal", Item::new, new Item.Settings());
		EMBER_DUST = ModItems.register("ember_dust", Item::new, new Item.Settings());
		SLAG_CHUNK = ModItems.register("slag_chunk", Item::new, new Item.Settings());
		ASH_PILE = ModItems.register("ash_pile", Item::new, new Item.Settings());
		CINDER_ROD = ModItems.register("cinder_rod", Item::new, new Item.Settings());
		INFERNIUM_PLATE = ModItems.register("infernium_plate", Item::new, new Item.Settings().fireproof());
		INFERNIUM_GEAR = ModItems.register("infernium_gear", Item::new, new Item.Settings().fireproof());
		SMOLDER_LENS = ModItems.register("smolder_lens", Item::new, new Item.Settings());

		// Mirrors the shipped copper_upgrade_smithing_template registration (feature/music):
		// SmithingTemplateItem.of(Item.Settings) — verified via javap.
		INFERNIUM_UPGRADE_SMITHING_TEMPLATE = ModItems.register("infernium_upgrade_smithing_template",
				SmithingTemplateItem::of, new Item.Settings().rarity(Rarity.UNCOMMON));

		// ----- tools: sword/pickaxe are component-driven via the Settings profile; axe/shovel/hoe
		// keep their vanilla strip/path/till behavior and take PLAIN Settings because their
		// constructors apply the tool profile themselves (see CopperToolsFeature).
		INFERNIUM_SWORD = ModItems.register("infernium_sword", Item::new,
				new Item.Settings().sword(TOOL_MATERIAL, 3.0F, -2.4F).fireproof());
		INFERNIUM_PICKAXE = ModItems.register("infernium_pickaxe", Item::new,
				new Item.Settings().pickaxe(TOOL_MATERIAL, 1.0F, -2.8F).fireproof());
		INFERNIUM_AXE = ModItems.register("infernium_axe",
				s -> new AxeItem(TOOL_MATERIAL, 5.0F, -3.0F, s), new Item.Settings().fireproof());
		INFERNIUM_SHOVEL = ModItems.register("infernium_shovel",
				s -> new ShovelItem(TOOL_MATERIAL, 1.5F, -3.0F, s), new Item.Settings().fireproof());
		INFERNIUM_HOE = ModItems.register("infernium_hoe",
				s -> new HoeItem(TOOL_MATERIAL, -3.0F, 0.0F, s), new Item.Settings().fireproof());

		// ----- armor
		INFERNIUM_HELMET = ModItems.register("infernium_helmet", Item::new,
				new Item.Settings().armor(ARMOR_MATERIAL, EquipmentType.HELMET).fireproof());
		INFERNIUM_CHESTPLATE = ModItems.register("infernium_chestplate", Item::new,
				new Item.Settings().armor(ARMOR_MATERIAL, EquipmentType.CHESTPLATE).fireproof());
		INFERNIUM_LEGGINGS = ModItems.register("infernium_leggings", Item::new,
				new Item.Settings().armor(ARMOR_MATERIAL, EquipmentType.LEGGINGS).fireproof());
		INFERNIUM_BOOTS = ModItems.register("infernium_boots", Item::new,
				new Item.Settings().armor(ARMOR_MATERIAL, EquipmentType.BOOTS).fireproof());

		// ----- blocks (fresh Settings per block; both need a pickaxe -> tagfrag mineable/pickaxe)
		INFERNIUM_BLOCK = ModBlocks.register("infernium_block", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.DARK_RED)
						.strength(5.0F, 6.0F)
						.requiresTool()
						.sounds(BlockSoundGroup.METAL),
				true);
		SMOLDER_CRYSTAL_BLOCK = ModBlocks.register("smolder_crystal_block", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.ORANGE)
						.strength(3.0F, 5.0F)
						.requiresTool()
						.sounds(BlockSoundGroup.AMETHYST_BLOCK)
						.luminance(state -> 9),
				true);

		// ----- creative tab: materials, then tools, then armor (EQUIPMENT); storage blocks (BLOCKS)
		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.EQUIPMENT_KEY).register(entries -> {
			entries.add(RAW_INFERNIUM);
			entries.add(INFERNIUM_INGOT);
			entries.add(INFERNIUM_NUGGET);
			entries.add(SMOLDER_CRYSTAL);
			entries.add(EMBER_DUST);
			entries.add(SLAG_CHUNK);
			entries.add(ASH_PILE);
			entries.add(CINDER_ROD);
			entries.add(INFERNIUM_PLATE);
			entries.add(INFERNIUM_GEAR);
			entries.add(SMOLDER_LENS);
			entries.add(INFERNIUM_UPGRADE_SMITHING_TEMPLATE);
			entries.add(INFERNIUM_SWORD);
			entries.add(INFERNIUM_PICKAXE);
			entries.add(INFERNIUM_AXE);
			entries.add(INFERNIUM_SHOVEL);
			entries.add(INFERNIUM_HOE);
			entries.add(INFERNIUM_HELMET);
			entries.add(INFERNIUM_CHESTPLATE);
			entries.add(INFERNIUM_LEGGINGS);
			entries.add(INFERNIUM_BOOTS);
		});
		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			entries.add(INFERNIUM_BLOCK.asItem());
			entries.add(SMOLDER_CRYSTAL_BLOCK.asItem());
		});

		registerHandbookEntries();
	}

	private static void registerHandbookEntries() {
		final String ING = "copper_inferno:infernium_ingot";
		final String NUG = "copper_inferno:infernium_nugget";
		final String RAW = "copper_inferno:raw_infernium";
		final String CRY = "copper_inferno:smolder_crystal";
		final String DUS = "copper_inferno:ember_dust";
		final String SLG = "copper_inferno:slag_chunk";
		final String ASH = "copper_inferno:ash_pile";
		final String ROD = "copper_inferno:cinder_rod";
		final String BLK = "copper_inferno:infernium_block";
		final String CBK = "copper_inferno:smolder_crystal_block";
		final String TPL = "copper_inferno:infernium_upgrade_smithing_template";

		// Overview page for the whole tier.
		HandbookEntries.add(new HandbookEntry("gear", "infernium_gear_overview",
				"copper_inferno:infernium_sword", null, null, null, 0,
				"Infernium gear sits between diamond and netherite: tools have 1100 durability, 7.5 mining speed, +2.5 attack damage and enchantability 18; armor protects one point above iron per piece with 2.5 toughness and light knockback resistance. Everything repairs with Infernium Ingots and never burns.",
				"Infernium-Ausr\u00fcstung liegt zwischen Diamant und Netherit: Werkzeuge haben 1100 Haltbarkeit, 7,5 Abbaugeschwindigkeit, +2,5 Angriffsschaden und Verzauberbarkeit 18; R\u00fcstung sch\u00fctzt pro Teil einen Punkt besser als Eisen, mit 2,5 Z\u00e4higkeit und leichter R\u00fccksto\u00dfresistenz. Alles wird mit Infernium-Barren repariert und verbrennt nie."));

		// ----- material economy
		HandbookEntries.add(new HandbookEntry("items", "infernium_ingot_from_smelting_raw_infernium",
				ING, "infernium/infernium_ingot_from_smelting_raw_infernium",
				new String[]{"", "", "", "", RAW, "", "", "", ""}, ING, 1,
				"Smelt Raw Infernium from the Inferno dimension into Infernium Ingots in a furnace.",
				"Rohinfernium aus der Inferno-Dimension im Ofen zu Infernium-Barren schmelzen."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_ingot_from_blasting_raw_infernium",
				ING, "infernium/infernium_ingot_from_blasting_raw_infernium",
				new String[]{"", "", "", "", RAW, "", "", "", ""}, ING, 1,
				"A blast furnace smelts Raw Infernium twice as fast.",
				"Ein Schmelzofen schmilzt Rohinfernium doppelt so schnell."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_ingot_from_smelting_infernium_ore",
				ING, "infernium/infernium_ingot_from_smelting_infernium_ore",
				new String[]{"", "", "", "", "copper_inferno:infernium_ore", "", "", "", ""}, ING, 1,
				"Infernium Ore blocks smelt straight into ingots too.",
				"Auch Infernium-Erzbl\u00f6cke schmelzen direkt zu Barren."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_ingot_from_blasting_infernium_ore",
				ING, "infernium/infernium_ingot_from_blasting_infernium_ore",
				new String[]{"", "", "", "", "copper_inferno:infernium_ore", "", "", "", ""}, ING, 1,
				"A blast furnace smelts Infernium Ore twice as fast.",
				"Ein Schmelzofen schmilzt Infernium-Erz doppelt so schnell."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_ingot_from_nuggets",
				ING, "infernium/infernium_ingot_from_nuggets",
				new String[]{NUG, NUG, NUG, NUG, NUG, NUG, NUG, NUG, NUG}, ING, 1,
				"Nine Infernium Nuggets combine back into one ingot.",
				"Neun Infernium-Klumpen ergeben wieder einen Barren."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_nugget",
				NUG, "infernium/infernium_nugget",
				new String[]{"", "", "", "", ING, "", "", "", ""}, NUG, 9,
				"Split an Infernium Ingot into nine nuggets.",
				"Ein Infernium-Barren l\u00e4sst sich in neun Klumpen teilen."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernium_block",
				BLK, "infernium/infernium_block",
				new String[]{ING, ING, ING, ING, ING, ING, ING, ING, ING}, BLK, 1,
				"Nine ingots compact into a Block of Infernium for storage.",
				"Neun Barren werden zu einem Infernium-Block zur Lagerung gepresst."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_ingot_from_infernium_block",
				ING, "infernium/infernium_ingot_from_infernium_block",
				new String[]{"", "", "", "", BLK, "", "", "", ""}, ING, 9,
				"A Block of Infernium unpacks into nine ingots.",
				"Ein Infernium-Block ergibt wieder neun Barren."));
		HandbookEntries.add(new HandbookEntry("blocks", "smolder_crystal_block",
				CBK, "infernium/smolder_crystal_block",
				new String[]{CRY, CRY, CRY, CRY, CRY, CRY, CRY, CRY, CRY}, CBK, 1,
				"Nine Smolder Crystals fuse into a glowing storage block.",
				"Neun Schwelkristalle verschmelzen zu einem leuchtenden Lagerblock."));
		HandbookEntries.add(new HandbookEntry("items", "smolder_crystal_from_smolder_crystal_block",
				CRY, "infernium/smolder_crystal_from_smolder_crystal_block",
				new String[]{"", "", "", "", CBK, "", "", "", ""}, CRY, 9,
				"A Smolder Crystal Block breaks apart into nine crystals.",
				"Ein Schwelkristallblock zerf\u00e4llt wieder in neun Kristalle."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_ember_dust",
				DUS, "infernium/ember_dust",
				new String[]{"", "", "", "", CRY, "", "", "", ""}, DUS, 4,
				"Crush a Smolder Crystal into four piles of Ember Dust.",
				"Ein Schwelkristall zersto\u00dfen ergibt vier Haufen Glutstaub."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_ash_pile",
				ASH, "infernium/ash_pile",
				new String[]{"", "", "", "", DUS, "", "", "", ""}, ASH, 1,
				"Ember Dust burns out to an Ash Pile in a furnace.",
				"Glutstaub verbrennt im Ofen zu einem Aschehaufen."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_slag_chunk",
				SLG, "infernium/slag_chunk",
				new String[]{ASH, ASH, "", ASH, ASH, "", "", "", ""}, SLG, 1,
				"Four Ash Piles press into a fused Slag Chunk.",
				"Vier Aschehaufen werden zu einem Schlackebrocken gepresst."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_cinder_rod",
				ROD, "infernium/cinder_rod",
				new String[]{"", SLG, "", "", SLG, "", "", "", ""}, ROD, 1,
				"Two Slag Chunks stacked vertically form a Cinder Rod — the handle of every Infernium tool.",
				"Zwei \u00fcbereinander gestapelte Schlackebrocken ergeben einen Zunderstab — den Griff jedes Infernium-Werkzeugs."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_plate",
				"copper_inferno:infernium_plate", "infernium/infernium_plate",
				new String[]{ING, ING, "", "", "", "", "", "", ""}, "copper_inferno:infernium_plate", 1,
				"Two ingots hammered flat make an Infernium Plate.",
				"Zwei flachgeh\u00e4mmerte Barren ergeben eine Infernium-Platte."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_gear",
				"copper_inferno:infernium_gear", "infernium/infernium_gear",
				new String[]{"", NUG, "", NUG, ING, NUG, "", NUG, ""}, "copper_inferno:infernium_gear", 1,
				"Four nuggets around an ingot mesh into an Infernium Gear.",
				"Vier Klumpen um einen Barren greifen zu einem Infernium-Zahnrad ineinander."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_smolder_lens",
				"copper_inferno:smolder_lens", "infernium/smolder_lens",
				new String[]{"", "minecraft:glass", "", "minecraft:glass", CRY, "minecraft:glass", "", "minecraft:glass", ""},
				"copper_inferno:smolder_lens", 1,
				"A Smolder Crystal set in glass focuses into a Smolder Lens.",
				"Ein in Glas gefasster Schwelkristall wird zu einer Schwellinse geschliffen."));

		// ----- machining-part & boss-drop sinks (recipes in recipe/infernium/)
		HandbookEntries.add(new HandbookEntry("blocks", "infernium_forge_heart_from_titan_ember",
				"copper_inferno:forge_heart", "infernium/forge_heart_from_titan_ember",
				new String[]{"copper_inferno:infernium_plate", "copper_inferno:infernium_plate", "copper_inferno:infernium_plate",
						"copper_inferno:infernium_plate", "copper_inferno:titan_ember", "copper_inferno:infernium_plate",
						"copper_inferno:infernium_plate", "copper_inferno:infernium_plate", "copper_inferno:infernium_plate"},
				"copper_inferno:forge_heart", 1,
				"Eight Infernium Plates sealed around a Titan Ember forge a Forge Heart - a trophy use for the Inferno Titan's drop.",
				"Acht Infernium-Platten um eine Titanglut versiegelt ergeben ein Schmiedeherz - eine Troph\u00e4en-Verwendung f\u00fcr den Drop des Inferno-Titanen."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernium_smolder_lamp_from_smolder_lens",
				"copper_inferno:smolder_lamp", "infernium/smolder_lamp_from_smolder_lens",
				new String[]{"copper_inferno:infernium_plate", "copper_inferno:smolder_lens", "copper_inferno:infernium_plate",
						"", "", "", "", "", ""},
				"copper_inferno:smolder_lamp", 4,
				"A Smolder Lens framed by two Infernium Plates focuses into 4 Smolder Lamps.",
				"Eine Schwellinse zwischen zwei Infernium-Platten b\u00fcndelt ihr Licht zu 4 Schwellampen."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_igniter_from_gear",
				"copper_inferno:infernium_igniter", "infernium/infernium_igniter_from_gear",
				new String[]{"copper_inferno:infernium_gear", "minecraft:flint", "", "", "", "", "", "", ""},
				"copper_inferno:infernium_igniter", 1,
				"An Infernium Gear spun against flint sparks into a fresh Infernium Igniter - handy when you are already in the Inferno.",
				"Ein Infernium-Zahnrad an Feuerstein gerieben ergibt einen neuen Infernium-Anz\u00fcnder - praktisch, wenn man schon im Inferno ist."));
		HandbookEntries.add(new HandbookEntry("items", "infernium_cyan_dye_from_verdigris_scale",
				"minecraft:cyan_dye", "infernium/cyan_dye_from_verdigris_scale",
				new String[]{"copper_inferno:verdigris_scale", "", "", "", "", "", "", "", ""},
				"minecraft:cyan_dye", 2,
				"Grind a Verdigris Scale from The Oxidizer into 2 Cyan Dye.",
				"Eine Gr\u00fcnspanschuppe des Oxidierers zermahlen ergibt 2 T\u00fcrkisen Farbstoff."));

		// ----- smithing template + duplication
		HandbookEntries.add(new HandbookEntry("gear", "infernium_upgrade_smithing_template",
				TPL, "infernium/infernium_upgrade_smithing_template",
				new String[]{ING, CRY, ING, ING, "minecraft:blackstone", ING, ING, ING, ING}, TPL, 1,
				"The Infernium Upgrade template: forged from ingots, a Smolder Crystal and blackstone. Use it in a smithing table to upgrade copper gear.",
				"Die Infernium-Aufwertungsvorlage: geschmiedet aus Barren, einem Schwelkristall und Schwarzstein. Am Schmiedetisch wertet sie Kupferausr\u00fcstung auf."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_upgrade_smithing_template_duplication",
				TPL, "infernium/infernium_upgrade_smithing_template_duplication",
				new String[]{ING, TPL, ING, ING, "minecraft:blackstone", ING, ING, ING, ING}, TPL, 2,
				"Duplicate the template with ingots and blackstone.",
				"Die Vorlage l\u00e4sst sich mit Barren und Schwarzstein duplizieren."));

		// ----- tool crafting
		HandbookEntries.add(new HandbookEntry("gear", "infernium_sword",
				"copper_inferno:infernium_sword", "infernium/infernium_sword",
				new String[]{"", ING, "", "", ING, "", "", ROD, ""}, "copper_inferno:infernium_sword", 1,
				"Two ingots on a Cinder Rod: the Infernium Sword (9.5 attack damage).",
				"Zwei Barren auf einem Zunderstab: das Infernium-Schwert (9,5 Angriffsschaden)."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_pickaxe",
				"copper_inferno:infernium_pickaxe", "infernium/infernium_pickaxe",
				new String[]{ING, ING, ING, "", ROD, "", "", ROD, ""}, "copper_inferno:infernium_pickaxe", 1,
				"The Infernium Pickaxe mines at speed 7.5 and harvests everything a diamond pickaxe can.",
				"Die Infernium-Spitzhacke gr\u00e4bt mit Geschwindigkeit 7,5 und baut alles ab, was eine Diamantspitzhacke kann."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_axe",
				"copper_inferno:infernium_axe", "infernium/infernium_axe",
				new String[]{ING, ING, "", ING, ROD, "", "", ROD, ""}, "copper_inferno:infernium_axe", 1,
				"The Infernium Axe chops, strips logs and hits hard.",
				"Die Infernium-Axt f\u00e4llt B\u00e4ume, entrindet St\u00e4mme und schl\u00e4gt kr\u00e4ftig zu."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_shovel",
				"copper_inferno:infernium_shovel", "infernium/infernium_shovel",
				new String[]{"", ING, "", "", ROD, "", "", ROD, ""}, "copper_inferno:infernium_shovel", 1,
				"The Infernium Shovel digs and flattens paths.",
				"Die Infernium-Schaufel gr\u00e4bt und ebnet Wege."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_hoe",
				"copper_inferno:infernium_hoe", "infernium/infernium_hoe",
				new String[]{ING, ING, "", "", ROD, "", "", ROD, ""}, "copper_inferno:infernium_hoe", 1,
				"The Infernium Hoe tills soil and swings fast.",
				"Die Infernium-Hacke pfl\u00fcgt Boden und schwingt schnell."));

		// ----- armor crafting
		HandbookEntries.add(new HandbookEntry("gear", "infernium_helmet",
				"copper_inferno:infernium_helmet", "infernium/infernium_helmet",
				new String[]{ING, ING, ING, ING, "", ING, "", "", ""}, "copper_inferno:infernium_helmet", 1,
				"The Infernium Helmet: 3 armor points, one above iron.",
				"Der Infernium-Helm: 3 R\u00fcstungspunkte, einer mehr als Eisen."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_chestplate",
				"copper_inferno:infernium_chestplate", "infernium/infernium_chestplate",
				new String[]{ING, "", ING, ING, ING, ING, ING, ING, ING}, "copper_inferno:infernium_chestplate", 1,
				"The Infernium Chestplate: 7 armor points, one above iron.",
				"Der Infernium-Harnisch: 7 R\u00fcstungspunkte, einer mehr als Eisen."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_leggings",
				"copper_inferno:infernium_leggings", "infernium/infernium_leggings",
				new String[]{ING, ING, ING, ING, "", ING, ING, "", ING}, "copper_inferno:infernium_leggings", 1,
				"The Infernium Leggings: 6 armor points, one above iron.",
				"Der Infernium-Beinschutz: 6 R\u00fcstungspunkte, einer mehr als Eisen."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_boots",
				"copper_inferno:infernium_boots", "infernium/infernium_boots",
				new String[]{ING, "", ING, ING, "", ING, "", "", ""}, "copper_inferno:infernium_boots", 1,
				"The Infernium Boots: 3 armor points, one above iron.",
				"Die Infernium-Stiefel: 3 R\u00fcstungspunkte, einer mehr als Eisen."));

		// ----- smithing upgrades (vanilla copper gear -> infernium)
		HandbookEntries.add(new HandbookEntry("gear", "infernium_sword_smithing",
				"copper_inferno:infernium_sword", "infernium/infernium_sword_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_sword", ING, "", "", ""}, "copper_inferno:infernium_sword", 1,
				"Smithing table: template + Copper Sword + Infernium Ingot upgrades to an Infernium Sword.",
				"Schmiedetisch: Vorlage + Kupferschwert + Infernium-Barren ergibt ein Infernium-Schwert."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_pickaxe_smithing",
				"copper_inferno:infernium_pickaxe", "infernium/infernium_pickaxe_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_pickaxe", ING, "", "", ""}, "copper_inferno:infernium_pickaxe", 1,
				"Smithing table: upgrade a Copper Pickaxe with the template and an ingot.",
				"Schmiedetisch: Kupferspitzhacke mit Vorlage und Barren aufwerten."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_axe_smithing",
				"copper_inferno:infernium_axe", "infernium/infernium_axe_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_axe", ING, "", "", ""}, "copper_inferno:infernium_axe", 1,
				"Smithing table: upgrade a Copper Axe with the template and an ingot.",
				"Schmiedetisch: Kupferaxt mit Vorlage und Barren aufwerten."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_shovel_smithing",
				"copper_inferno:infernium_shovel", "infernium/infernium_shovel_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_shovel", ING, "", "", ""}, "copper_inferno:infernium_shovel", 1,
				"Smithing table: upgrade a Copper Shovel with the template and an ingot.",
				"Schmiedetisch: Kupferschaufel mit Vorlage und Barren aufwerten."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_hoe_smithing",
				"copper_inferno:infernium_hoe", "infernium/infernium_hoe_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_hoe", ING, "", "", ""}, "copper_inferno:infernium_hoe", 1,
				"Smithing table: upgrade a Copper Hoe with the template and an ingot.",
				"Schmiedetisch: Kupferhacke mit Vorlage und Barren aufwerten."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_helmet_smithing",
				"copper_inferno:infernium_helmet", "infernium/infernium_helmet_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_helmet", ING, "", "", ""}, "copper_inferno:infernium_helmet", 1,
				"Smithing table: upgrade a Copper Helmet with the template and an ingot.",
				"Schmiedetisch: Kupferhelm mit Vorlage und Barren aufwerten."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_chestplate_smithing",
				"copper_inferno:infernium_chestplate", "infernium/infernium_chestplate_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_chestplate", ING, "", "", ""}, "copper_inferno:infernium_chestplate", 1,
				"Smithing table: upgrade a Copper Chestplate with the template and an ingot.",
				"Schmiedetisch: Kupferharnisch mit Vorlage und Barren aufwerten."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_leggings_smithing",
				"copper_inferno:infernium_leggings", "infernium/infernium_leggings_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_leggings", ING, "", "", ""}, "copper_inferno:infernium_leggings", 1,
				"Smithing table: upgrade Copper Leggings with the template and an ingot.",
				"Schmiedetisch: Kupferbeinschutz mit Vorlage und Barren aufwerten."));
		HandbookEntries.add(new HandbookEntry("gear", "infernium_boots_smithing",
				"copper_inferno:infernium_boots", "infernium/infernium_boots_smithing",
				new String[]{"", "", "", TPL, "minecraft:copper_boots", ING, "", "", ""}, "copper_inferno:infernium_boots", 1,
				"Smithing table: upgrade Copper Boots with the template and an ingot.",
				"Schmiedetisch: Kupferstiefel mit Vorlage und Barren aufwerten."));
	}
}
