package net.sonic0810.copperinferno.feature.arsenal;

import java.util.EnumMap;
import java.util.Map;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.AxeItem;
import net.minecraft.item.HoeItem;
import net.minecraft.item.Item;
import net.minecraft.item.ShovelItem;
import net.minecraft.item.ToolMaterial;
import net.minecraft.item.equipment.ArmorMaterial;
import net.minecraft.item.equipment.EquipmentAsset;
import net.minecraft.item.equipment.EquipmentAssetKeys;
import net.minecraft.item.equipment.EquipmentType;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Arsenal &amp; Trinkets" feature (WP6): ~90 standalone items.
 *
 * <p>Content: 4 full gear tiers built on the WP5 gem/alloy ingots (pyrium, emberite,
 * ashsteel, voidsteel — 9 pieces each, 36 items; stats between iron and netherite, each
 * tier distinct, repairing from {@code copper_inferno:<tier>_repair} item tags), plus 54
 * singles: throwing weapons, charms &amp; talismans, utility gadgets and crafting catalysts.
 * Ten of the singles have real use-behavior (javelin, hammer, grenade, magnet, 3 status
 * charms, grapnel, prospector lens, signal horn); the rest are crafting materials with a
 * flavor tooltip ({@link ArsenalMaterialItem}).
 *
 * <p>Assets (textures, item defs/models, recipes under {@code recipe/arsenal/}, the 4 repair
 * tags, equipment assets + worn-armor layers, lang fragments, the vanilla-tag fragment) are
 * generated by {@code devtools/gen/arsenal_gen.py}. Every crafting recipe includes the
 * Arsenal Catalyst or another arsenal-unique item, so no vanilla/mod input collisions are
 * possible (checked by devtools/check_recipe_collisions.py).
 *
 * <p>Tier stat ladder (iron 250/6.0/+2.0 ... netherite 2031/9.0/+4.0):
 * <ul>
 * <li>Pyrium — fast, light, super-enchantable: 455 dur / 6.8 speed / +2.2 dmg / ench 22;
 *     armor 2/5/6/2, toughness 0.5 (iron-level mining).</li>
 * <li>Emberite — aggressive: 780 / 7.2 / +2.8 / ench 14; armor 2/6/7/3, toughness 1.0
 *     (iron-level mining).</li>
 * <li>Ashsteel — durable workhorse: 1180 / 7.6 / +2.4 / ench 12; armor 3/6/7/2,
 *     toughness 1.5 (diamond-level mining).</li>
 * <li>Voidsteel — near-netherite: 1650 / 8.2 / +3.2 / ench 16; armor 3/6/8/3,
 *     toughness 2.5, +0.05 knockback resistance (diamond-level mining).</li>
 * </ul>
 */
public final class ArsenalFeature {
	private ArsenalFeature() {
	}

	// ----- repair tags (data/copper_inferno/tags/item/<tier>_repair.json -> WP5 ingot)
	public static final TagKey<Item> REPAIRS_PYRIUM = TagKey.of(RegistryKeys.ITEM, CopperInferno.id("pyrium_repair"));
	public static final TagKey<Item> REPAIRS_EMBERITE = TagKey.of(RegistryKeys.ITEM, CopperInferno.id("emberite_repair"));
	public static final TagKey<Item> REPAIRS_ASHSTEEL = TagKey.of(RegistryKeys.ITEM, CopperInferno.id("ashsteel_repair"));
	public static final TagKey<Item> REPAIRS_VOIDSTEEL = TagKey.of(RegistryKeys.ITEM, CopperInferno.id("voidsteel_repair"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed, attackDamageBonus,
	 * enchantmentValue, repairItems) — verified via javap (same as InferniumFeature).
	 */
	public static final ToolMaterial PYRIUM_TOOL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_IRON_TOOL, 455, 6.8F, 2.2F, 22, REPAIRS_PYRIUM);
	public static final ToolMaterial EMBERITE_TOOL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_IRON_TOOL, 780, 7.2F, 2.8F, 14, REPAIRS_EMBERITE);
	public static final ToolMaterial ASHSTEEL_TOOL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_DIAMOND_TOOL, 1180, 7.6F, 2.4F, 12, REPAIRS_ASHSTEEL);
	public static final ToolMaterial VOIDSTEEL_TOOL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_DIAMOND_TOOL, 1650, 8.2F, 3.2F, 16, REPAIRS_VOIDSTEEL);

	// ----- worn-armor equipment assets (assets/copper_inferno/equipment/<tier>.json)
	public static final RegistryKey<EquipmentAsset> PYRIUM_ASSET =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("pyrium"));
	public static final RegistryKey<EquipmentAsset> EMBERITE_ASSET =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("emberite"));
	public static final RegistryKey<EquipmentAsset> ASHSTEEL_ASSET =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("ashsteel"));
	public static final RegistryKey<EquipmentAsset> VOIDSTEEL_ASSET =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("voidsteel"));

	/**
	 * ArmorMaterial is a record: (durability, defense map, enchantmentValue, equipSound,
	 * toughness, knockbackResistance, repairIngredient, assetId) — verified via javap.
	 * Durability multipliers sit between iron (15) and netherite (37).
	 */
	public static final ArmorMaterial PYRIUM_ARMOR = new ArmorMaterial(
			17, defenseMap(2, 5, 6, 2, 5), 22, SoundEvents.ITEM_ARMOR_EQUIP_GOLD,
			0.5F, 0.0F, REPAIRS_PYRIUM, PYRIUM_ASSET);
	public static final ArmorMaterial EMBERITE_ARMOR = new ArmorMaterial(
			21, defenseMap(2, 6, 7, 3, 6), 14, SoundEvents.ITEM_ARMOR_EQUIP_IRON,
			1.0F, 0.0F, REPAIRS_EMBERITE, EMBERITE_ASSET);
	public static final ArmorMaterial ASHSTEEL_ARMOR = new ArmorMaterial(
			27, defenseMap(3, 6, 7, 2, 6), 12, SoundEvents.ITEM_ARMOR_EQUIP_IRON,
			1.5F, 0.0F, REPAIRS_ASHSTEEL, ASHSTEEL_ASSET);
	public static final ArmorMaterial VOIDSTEEL_ARMOR = new ArmorMaterial(
			33, defenseMap(3, 6, 8, 3, 7), 16, SoundEvents.ITEM_ARMOR_EQUIP_NETHERITE,
			2.5F, 0.05F, REPAIRS_VOIDSTEEL, VOIDSTEEL_ASSET);

	// ----- tier gear (4 x 9)
	public static Item PYRIUM_SWORD;
	public static Item PYRIUM_PICKAXE;
	public static Item PYRIUM_AXE;
	public static Item PYRIUM_SHOVEL;
	public static Item PYRIUM_HOE;
	public static Item PYRIUM_HELMET;
	public static Item PYRIUM_CHESTPLATE;
	public static Item PYRIUM_LEGGINGS;
	public static Item PYRIUM_BOOTS;

	public static Item EMBERITE_SWORD;
	public static Item EMBERITE_PICKAXE;
	public static Item EMBERITE_AXE;
	public static Item EMBERITE_SHOVEL;
	public static Item EMBERITE_HOE;
	public static Item EMBERITE_HELMET;
	public static Item EMBERITE_CHESTPLATE;
	public static Item EMBERITE_LEGGINGS;
	public static Item EMBERITE_BOOTS;

	public static Item ASHSTEEL_SWORD;
	public static Item ASHSTEEL_PICKAXE;
	public static Item ASHSTEEL_AXE;
	public static Item ASHSTEEL_SHOVEL;
	public static Item ASHSTEEL_HOE;
	public static Item ASHSTEEL_HELMET;
	public static Item ASHSTEEL_CHESTPLATE;
	public static Item ASHSTEEL_LEGGINGS;
	public static Item ASHSTEEL_BOOTS;

	public static Item VOIDSTEEL_SWORD;
	public static Item VOIDSTEEL_PICKAXE;
	public static Item VOIDSTEEL_AXE;
	public static Item VOIDSTEEL_SHOVEL;
	public static Item VOIDSTEEL_HOE;
	public static Item VOIDSTEEL_HELMET;
	public static Item VOIDSTEEL_CHESTPLATE;
	public static Item VOIDSTEEL_LEGGINGS;
	public static Item VOIDSTEEL_BOOTS;

	// ----- throwing weapons (6)
	public static Item EMBER_JAVELIN;
	public static Item SLAG_HAMMER;
	public static Item ASH_GRENADE;
	public static Item CINDER_DART;
	public static Item COPPER_BOLAS;
	public static Item VOIDSTEEL_CHAKRAM;

	// ----- charms & talismans (12)
	public static Item MAGNET_CHARM;
	public static Item EMBER_WARD_TALISMAN;
	public static Item HASTE_CHARM;
	public static Item LEAPING_CHARM;
	public static Item VOID_WARD_TALISMAN;
	public static Item TIDE_TALISMAN;
	public static Item STORM_TALISMAN;
	public static Item MINER_TALISMAN;
	public static Item HEARTH_TALISMAN;
	public static Item SHADOW_CHARM;
	public static Item GILDED_CHARM;
	public static Item PEPPER_CHARM;

	// ----- utility gadgets (12)
	public static Item COPPER_GRAPNEL;
	public static Item PROSPECTOR_LENS;
	public static Item SIGNAL_HORN;
	public static Item PORTABLE_ANVIL;
	public static Item POCKET_FURNACE;
	public static Item COPPER_TROWEL;
	public static Item SLAG_SCRAPER;
	public static Item EMBER_LIGHTER;
	public static Item TUNING_HAMMER;
	public static Item ARSENAL_WHETSTONE;
	public static Item FIELD_KIT;
	public static Item COPPER_PLUMB_LINE;

	// ----- crafting catalysts & parts (24)
	public static Item ARSENAL_CATALYST;
	public static Item CATALYST_DUST;
	public static Item TEMPERED_PLATE;
	public static Item DOOM_ALLOY_SHARD;
	public static Item PYRIUM_CORE;
	public static Item EMBERITE_CORE;
	public static Item ASHSTEEL_CORE;
	public static Item VOIDSTEEL_CORE;
	public static Item GILDED_RIVET;
	public static Item FORGE_BINDING;
	public static Item WEAPON_GRIP;
	public static Item BLAST_POWDER;
	public static Item MOLTEN_SOLDER;
	public static Item ARC_FILAMENT;
	public static Item HARDENED_STRAP;
	public static Item LENS_BLANK;
	public static Item ALLOY_MESH;
	public static Item TOOL_MATRIX;
	public static Item JAVELIN_SHAFT;
	public static Item CHARM_LOCKET;
	public static Item TALISMAN_CORD;
	public static Item GRAPNEL_HOOK;
	public static Item WHETSTONE_GRIT;
	public static Item HORN_VALVE;

	private static Map<EquipmentType, Integer> defenseMap(int boots, int leggings, int chestplate, int helmet, int body) {
		Map<EquipmentType, Integer> map = new EnumMap<>(EquipmentType.class);
		map.put(EquipmentType.BOOTS, boots);
		map.put(EquipmentType.LEGGINGS, leggings);
		map.put(EquipmentType.CHESTPLATE, chestplate);
		map.put(EquipmentType.HELMET, helmet);
		map.put(EquipmentType.BODY, body);
		return map;
	}

	public static void init() {
		// ----- pyrium tier (sword/pickaxe are component-driven via the Settings profile;
		// axe/shovel/hoe keep their vanilla strip/path/till behavior, exactly like
		// InferniumFeature; every registration uses a FRESH Settings and a LITERAL id).
		PYRIUM_SWORD = ModItems.register("pyrium_sword", Item::new,
				new Item.Settings().sword(PYRIUM_TOOL, 3.0F, -2.4F));
		PYRIUM_PICKAXE = ModItems.register("pyrium_pickaxe", Item::new,
				new Item.Settings().pickaxe(PYRIUM_TOOL, 1.0F, -2.8F));
		PYRIUM_AXE = ModItems.register("pyrium_axe",
				s -> new AxeItem(PYRIUM_TOOL, 6.0F, -3.1F, s), new Item.Settings());
		PYRIUM_SHOVEL = ModItems.register("pyrium_shovel",
				s -> new ShovelItem(PYRIUM_TOOL, 1.5F, -3.0F, s), new Item.Settings());
		PYRIUM_HOE = ModItems.register("pyrium_hoe",
				s -> new HoeItem(PYRIUM_TOOL, -2.0F, -1.0F, s), new Item.Settings());
		PYRIUM_HELMET = ModItems.register("pyrium_helmet", Item::new,
				new Item.Settings().armor(PYRIUM_ARMOR, EquipmentType.HELMET));
		PYRIUM_CHESTPLATE = ModItems.register("pyrium_chestplate", Item::new,
				new Item.Settings().armor(PYRIUM_ARMOR, EquipmentType.CHESTPLATE));
		PYRIUM_LEGGINGS = ModItems.register("pyrium_leggings", Item::new,
				new Item.Settings().armor(PYRIUM_ARMOR, EquipmentType.LEGGINGS));
		PYRIUM_BOOTS = ModItems.register("pyrium_boots", Item::new,
				new Item.Settings().armor(PYRIUM_ARMOR, EquipmentType.BOOTS));

		// ----- emberite tier
		EMBERITE_SWORD = ModItems.register("emberite_sword", Item::new,
				new Item.Settings().sword(EMBERITE_TOOL, 3.0F, -2.4F));
		EMBERITE_PICKAXE = ModItems.register("emberite_pickaxe", Item::new,
				new Item.Settings().pickaxe(EMBERITE_TOOL, 1.0F, -2.8F));
		EMBERITE_AXE = ModItems.register("emberite_axe",
				s -> new AxeItem(EMBERITE_TOOL, 6.0F, -3.1F, s), new Item.Settings());
		EMBERITE_SHOVEL = ModItems.register("emberite_shovel",
				s -> new ShovelItem(EMBERITE_TOOL, 1.5F, -3.0F, s), new Item.Settings());
		EMBERITE_HOE = ModItems.register("emberite_hoe",
				s -> new HoeItem(EMBERITE_TOOL, -2.0F, -1.0F, s), new Item.Settings());
		EMBERITE_HELMET = ModItems.register("emberite_helmet", Item::new,
				new Item.Settings().armor(EMBERITE_ARMOR, EquipmentType.HELMET));
		EMBERITE_CHESTPLATE = ModItems.register("emberite_chestplate", Item::new,
				new Item.Settings().armor(EMBERITE_ARMOR, EquipmentType.CHESTPLATE));
		EMBERITE_LEGGINGS = ModItems.register("emberite_leggings", Item::new,
				new Item.Settings().armor(EMBERITE_ARMOR, EquipmentType.LEGGINGS));
		EMBERITE_BOOTS = ModItems.register("emberite_boots", Item::new,
				new Item.Settings().armor(EMBERITE_ARMOR, EquipmentType.BOOTS));

		// ----- ashsteel tier
		ASHSTEEL_SWORD = ModItems.register("ashsteel_sword", Item::new,
				new Item.Settings().sword(ASHSTEEL_TOOL, 3.0F, -2.4F));
		ASHSTEEL_PICKAXE = ModItems.register("ashsteel_pickaxe", Item::new,
				new Item.Settings().pickaxe(ASHSTEEL_TOOL, 1.0F, -2.8F));
		ASHSTEEL_AXE = ModItems.register("ashsteel_axe",
				s -> new AxeItem(ASHSTEEL_TOOL, 5.0F, -3.0F, s), new Item.Settings());
		ASHSTEEL_SHOVEL = ModItems.register("ashsteel_shovel",
				s -> new ShovelItem(ASHSTEEL_TOOL, 1.5F, -3.0F, s), new Item.Settings());
		ASHSTEEL_HOE = ModItems.register("ashsteel_hoe",
				s -> new HoeItem(ASHSTEEL_TOOL, -3.0F, 0.0F, s), new Item.Settings());
		ASHSTEEL_HELMET = ModItems.register("ashsteel_helmet", Item::new,
				new Item.Settings().armor(ASHSTEEL_ARMOR, EquipmentType.HELMET));
		ASHSTEEL_CHESTPLATE = ModItems.register("ashsteel_chestplate", Item::new,
				new Item.Settings().armor(ASHSTEEL_ARMOR, EquipmentType.CHESTPLATE));
		ASHSTEEL_LEGGINGS = ModItems.register("ashsteel_leggings", Item::new,
				new Item.Settings().armor(ASHSTEEL_ARMOR, EquipmentType.LEGGINGS));
		ASHSTEEL_BOOTS = ModItems.register("ashsteel_boots", Item::new,
				new Item.Settings().armor(ASHSTEEL_ARMOR, EquipmentType.BOOTS));

		// ----- voidsteel tier
		VOIDSTEEL_SWORD = ModItems.register("voidsteel_sword", Item::new,
				new Item.Settings().sword(VOIDSTEEL_TOOL, 3.0F, -2.4F));
		VOIDSTEEL_PICKAXE = ModItems.register("voidsteel_pickaxe", Item::new,
				new Item.Settings().pickaxe(VOIDSTEEL_TOOL, 1.0F, -2.8F));
		VOIDSTEEL_AXE = ModItems.register("voidsteel_axe",
				s -> new AxeItem(VOIDSTEEL_TOOL, 5.0F, -3.0F, s), new Item.Settings());
		VOIDSTEEL_SHOVEL = ModItems.register("voidsteel_shovel",
				s -> new ShovelItem(VOIDSTEEL_TOOL, 1.5F, -3.0F, s), new Item.Settings());
		VOIDSTEEL_HOE = ModItems.register("voidsteel_hoe",
				s -> new HoeItem(VOIDSTEEL_TOOL, -3.0F, 0.0F, s), new Item.Settings());
		VOIDSTEEL_HELMET = ModItems.register("voidsteel_helmet", Item::new,
				new Item.Settings().armor(VOIDSTEEL_ARMOR, EquipmentType.HELMET));
		VOIDSTEEL_CHESTPLATE = ModItems.register("voidsteel_chestplate", Item::new,
				new Item.Settings().armor(VOIDSTEEL_ARMOR, EquipmentType.CHESTPLATE));
		VOIDSTEEL_LEGGINGS = ModItems.register("voidsteel_leggings", Item::new,
				new Item.Settings().armor(VOIDSTEEL_ARMOR, EquipmentType.LEGGINGS));
		VOIDSTEEL_BOOTS = ModItems.register("voidsteel_boots", Item::new,
				new Item.Settings().armor(VOIDSTEEL_ARMOR, EquipmentType.BOOTS));

		// ----- throwing weapons
		EMBER_JAVELIN = ModItems.register("ember_javelin", EmberJavelinItem::new,
				new Item.Settings().maxCount(16));
		SLAG_HAMMER = ModItems.register("slag_hammer", SlagHammerItem::new,
				new Item.Settings().maxDamage(250));
		ASH_GRENADE = ModItems.register("ash_grenade", AshGrenadeItem::new,
				new Item.Settings().maxCount(16));
		CINDER_DART = ModItems.register("cinder_dart", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16));
		COPPER_BOLAS = ModItems.register("copper_bolas", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16));
		VOIDSTEEL_CHAKRAM = ModItems.register("voidsteel_chakram", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16).rarity(Rarity.UNCOMMON));

		// ----- charms & talismans (behavior charms use ArsenalCharmItem; fresh Settings each)
		MAGNET_CHARM = ModItems.register("magnet_charm", MagnetCharmItem::new,
				new Item.Settings().maxCount(1));
		EMBER_WARD_TALISMAN = ModItems.register("ember_ward_talisman",
				s -> new ArsenalCharmItem(s, 5 * 20, true,
						new ArsenalCharmItem.EffectSpec(StatusEffects.FIRE_RESISTANCE, 60 * 20, 0)),
				new Item.Settings().maxCount(16));
		HASTE_CHARM = ModItems.register("haste_charm",
				s -> new ArsenalCharmItem(s, 60 * 20, false,
						new ArsenalCharmItem.EffectSpec(StatusEffects.HASTE, 30 * 20, 1)),
				new Item.Settings().maxCount(1));
		LEAPING_CHARM = ModItems.register("leaping_charm",
				s -> new ArsenalCharmItem(s, 60 * 20, false,
						new ArsenalCharmItem.EffectSpec(StatusEffects.JUMP_BOOST, 30 * 20, 1),
						new ArsenalCharmItem.EffectSpec(StatusEffects.SLOW_FALLING, 30 * 20, 0)),
				new Item.Settings().maxCount(1));
		VOID_WARD_TALISMAN = ModItems.register("void_ward_talisman", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16));
		TIDE_TALISMAN = ModItems.register("tide_talisman", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16));
		STORM_TALISMAN = ModItems.register("storm_talisman", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16));
		MINER_TALISMAN = ModItems.register("miner_talisman", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16));
		HEARTH_TALISMAN = ModItems.register("hearth_talisman", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16));
		SHADOW_CHARM = ModItems.register("shadow_charm", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		GILDED_CHARM = ModItems.register("gilded_charm", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		PEPPER_CHARM = ModItems.register("pepper_charm", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));

		// ----- utility gadgets
		COPPER_GRAPNEL = ModItems.register("copper_grapnel", CopperGrapnelItem::new,
				new Item.Settings().maxDamage(128));
		PROSPECTOR_LENS = ModItems.register("prospector_lens", ProspectorLensItem::new,
				new Item.Settings().maxCount(1));
		SIGNAL_HORN = ModItems.register("signal_horn", SignalHornItem::new,
				new Item.Settings().maxCount(1));
		PORTABLE_ANVIL = ModItems.register("portable_anvil", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		POCKET_FURNACE = ModItems.register("pocket_furnace", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		COPPER_TROWEL = ModItems.register("copper_trowel", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		SLAG_SCRAPER = ModItems.register("slag_scraper", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		EMBER_LIGHTER = ModItems.register("ember_lighter", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		TUNING_HAMMER = ModItems.register("tuning_hammer", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		ARSENAL_WHETSTONE = ModItems.register("arsenal_whetstone", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(16));
		FIELD_KIT = ModItems.register("field_kit", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));
		COPPER_PLUMB_LINE = ModItems.register("copper_plumb_line", ArsenalMaterialItem::new,
				new Item.Settings().maxCount(1));

		// ----- crafting catalysts & parts
		ARSENAL_CATALYST = ModItems.register("arsenal_catalyst", ArsenalMaterialItem::new,
				new Item.Settings().rarity(Rarity.UNCOMMON));
		CATALYST_DUST = ModItems.register("catalyst_dust", ArsenalMaterialItem::new,
				new Item.Settings());
		TEMPERED_PLATE = ModItems.register("tempered_plate", ArsenalMaterialItem::new,
				new Item.Settings());
		DOOM_ALLOY_SHARD = ModItems.register("doom_alloy_shard", ArsenalMaterialItem::new,
				new Item.Settings().rarity(Rarity.UNCOMMON));
		PYRIUM_CORE = ModItems.register("pyrium_core", ArsenalMaterialItem::new,
				new Item.Settings());
		EMBERITE_CORE = ModItems.register("emberite_core", ArsenalMaterialItem::new,
				new Item.Settings());
		ASHSTEEL_CORE = ModItems.register("ashsteel_core", ArsenalMaterialItem::new,
				new Item.Settings());
		VOIDSTEEL_CORE = ModItems.register("voidsteel_core", ArsenalMaterialItem::new,
				new Item.Settings());
		GILDED_RIVET = ModItems.register("gilded_rivet", ArsenalMaterialItem::new,
				new Item.Settings());
		FORGE_BINDING = ModItems.register("forge_binding", ArsenalMaterialItem::new,
				new Item.Settings());
		WEAPON_GRIP = ModItems.register("weapon_grip", ArsenalMaterialItem::new,
				new Item.Settings());
		BLAST_POWDER = ModItems.register("blast_powder", ArsenalMaterialItem::new,
				new Item.Settings());
		MOLTEN_SOLDER = ModItems.register("molten_solder", ArsenalMaterialItem::new,
				new Item.Settings());
		ARC_FILAMENT = ModItems.register("arc_filament", ArsenalMaterialItem::new,
				new Item.Settings());
		HARDENED_STRAP = ModItems.register("hardened_strap", ArsenalMaterialItem::new,
				new Item.Settings());
		LENS_BLANK = ModItems.register("lens_blank", ArsenalMaterialItem::new,
				new Item.Settings());
		ALLOY_MESH = ModItems.register("alloy_mesh", ArsenalMaterialItem::new,
				new Item.Settings());
		TOOL_MATRIX = ModItems.register("tool_matrix", ArsenalMaterialItem::new,
				new Item.Settings());
		JAVELIN_SHAFT = ModItems.register("javelin_shaft", ArsenalMaterialItem::new,
				new Item.Settings());
		CHARM_LOCKET = ModItems.register("charm_locket", ArsenalMaterialItem::new,
				new Item.Settings());
		TALISMAN_CORD = ModItems.register("talisman_cord", ArsenalMaterialItem::new,
				new Item.Settings());
		GRAPNEL_HOOK = ModItems.register("grapnel_hook", ArsenalMaterialItem::new,
				new Item.Settings());
		WHETSTONE_GRIT = ModItems.register("whetstone_grit", ArsenalMaterialItem::new,
				new Item.Settings());
		HORN_VALVE = ModItems.register("horn_valve", ArsenalMaterialItem::new,
				new Item.Settings());

		// ----- creative tab: gear tiers, then throwables, charms, gadgets, catalysts (MAIN)
		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			entries.add(PYRIUM_SWORD);
			entries.add(PYRIUM_PICKAXE);
			entries.add(PYRIUM_AXE);
			entries.add(PYRIUM_SHOVEL);
			entries.add(PYRIUM_HOE);
			entries.add(PYRIUM_HELMET);
			entries.add(PYRIUM_CHESTPLATE);
			entries.add(PYRIUM_LEGGINGS);
			entries.add(PYRIUM_BOOTS);
			entries.add(EMBERITE_SWORD);
			entries.add(EMBERITE_PICKAXE);
			entries.add(EMBERITE_AXE);
			entries.add(EMBERITE_SHOVEL);
			entries.add(EMBERITE_HOE);
			entries.add(EMBERITE_HELMET);
			entries.add(EMBERITE_CHESTPLATE);
			entries.add(EMBERITE_LEGGINGS);
			entries.add(EMBERITE_BOOTS);
			entries.add(ASHSTEEL_SWORD);
			entries.add(ASHSTEEL_PICKAXE);
			entries.add(ASHSTEEL_AXE);
			entries.add(ASHSTEEL_SHOVEL);
			entries.add(ASHSTEEL_HOE);
			entries.add(ASHSTEEL_HELMET);
			entries.add(ASHSTEEL_CHESTPLATE);
			entries.add(ASHSTEEL_LEGGINGS);
			entries.add(ASHSTEEL_BOOTS);
			entries.add(VOIDSTEEL_SWORD);
			entries.add(VOIDSTEEL_PICKAXE);
			entries.add(VOIDSTEEL_AXE);
			entries.add(VOIDSTEEL_SHOVEL);
			entries.add(VOIDSTEEL_HOE);
			entries.add(VOIDSTEEL_HELMET);
			entries.add(VOIDSTEEL_CHESTPLATE);
			entries.add(VOIDSTEEL_LEGGINGS);
			entries.add(VOIDSTEEL_BOOTS);
			entries.add(EMBER_JAVELIN);
			entries.add(SLAG_HAMMER);
			entries.add(ASH_GRENADE);
			entries.add(CINDER_DART);
			entries.add(COPPER_BOLAS);
			entries.add(VOIDSTEEL_CHAKRAM);
			entries.add(MAGNET_CHARM);
			entries.add(EMBER_WARD_TALISMAN);
			entries.add(HASTE_CHARM);
			entries.add(LEAPING_CHARM);
			entries.add(VOID_WARD_TALISMAN);
			entries.add(TIDE_TALISMAN);
			entries.add(STORM_TALISMAN);
			entries.add(MINER_TALISMAN);
			entries.add(HEARTH_TALISMAN);
			entries.add(SHADOW_CHARM);
			entries.add(GILDED_CHARM);
			entries.add(PEPPER_CHARM);
			entries.add(COPPER_GRAPNEL);
			entries.add(PROSPECTOR_LENS);
			entries.add(SIGNAL_HORN);
			entries.add(PORTABLE_ANVIL);
			entries.add(POCKET_FURNACE);
			entries.add(COPPER_TROWEL);
			entries.add(SLAG_SCRAPER);
			entries.add(EMBER_LIGHTER);
			entries.add(TUNING_HAMMER);
			entries.add(ARSENAL_WHETSTONE);
			entries.add(FIELD_KIT);
			entries.add(COPPER_PLUMB_LINE);
			entries.add(ARSENAL_CATALYST);
			entries.add(CATALYST_DUST);
			entries.add(TEMPERED_PLATE);
			entries.add(DOOM_ALLOY_SHARD);
			entries.add(PYRIUM_CORE);
			entries.add(EMBERITE_CORE);
			entries.add(ASHSTEEL_CORE);
			entries.add(VOIDSTEEL_CORE);
			entries.add(GILDED_RIVET);
			entries.add(FORGE_BINDING);
			entries.add(WEAPON_GRIP);
			entries.add(BLAST_POWDER);
			entries.add(MOLTEN_SOLDER);
			entries.add(ARC_FILAMENT);
			entries.add(HARDENED_STRAP);
			entries.add(LENS_BLANK);
			entries.add(ALLOY_MESH);
			entries.add(TOOL_MATRIX);
			entries.add(JAVELIN_SHAFT);
			entries.add(CHARM_LOCKET);
			entries.add(TALISMAN_CORD);
			entries.add(GRAPNEL_HOOK);
			entries.add(WHETSTONE_GRIT);
			entries.add(HORN_VALVE);
		});

		registerHandbookEntries();
	}

	private static void registerHandbookEntries() {
		final String PY = "copper_inferno:pyrium_ingot";
		final String EM = "copper_inferno:emberite_ingot";
		final String AS = "copper_inferno:ashsteel_ingot";
		final String VS = "copper_inferno:voidsteel_ingot";
		final String CAT = "copper_inferno:arsenal_catalyst";
		final String DUS = "copper_inferno:catalyst_dust";
		final String STK = "minecraft:stick";

		// ~12 curated entries, all category "gear" (ids prefixed arsenal_ to stay unique).
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_catalyst",
				CAT, "arsenal/arsenal_catalyst",
				new String[]{"", PY, "", EM, "minecraft:blaze_powder", VS, "", AS, ""}, CAT, 2,
				"The Arsenal Catalyst: all four gem-alloy ingots fused around blaze powder. Every arsenal recipe runs through it (or through a part made from it).",
				"Der Arsenal-Katalysator: alle vier Edelmetall-Barren um Lohenstaub verschmolzen. Jedes Arsenal-Rezept l\u00e4uft \u00fcber ihn (oder \u00fcber ein daraus gefertigtes Bauteil)."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_tempered_plate",
				"copper_inferno:tempered_plate", "arsenal/tempered_plate",
				new String[]{DUS, "minecraft:iron_ingot", "minecraft:iron_ingot", "", "", "", "", "", ""},
				"copper_inferno:tempered_plate", 1,
				"Catalyst Dust hardens two iron ingots into a Tempered Plate, the arsenal's structural part.",
				"Katalysatorstaub h\u00e4rtet zwei Eisenbarren zu einer Geh\u00e4rteten Platte, dem Strukturbauteil des Arsenals."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_pyrium_sword",
				"copper_inferno:pyrium_sword", "arsenal/pyrium_sword",
				new String[]{PY, "", "", PY, CAT, "", STK, "", ""}, "copper_inferno:pyrium_sword", 1,
				"Pyrium gear is light and hungry for enchantments (enchantability 22); the sword swings for 5.2 damage.",
				"Pyrium-Ausr\u00fcstung ist leicht und giert nach Verzauberungen (Verzauberbarkeit 22); das Schwert schl\u00e4gt mit 5,2 Schaden zu."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_emberite_pickaxe",
				"copper_inferno:emberite_pickaxe", "arsenal/emberite_pickaxe",
				new String[]{EM, EM, EM, "", CAT, "", "", STK, ""}, "copper_inferno:emberite_pickaxe", 1,
				"Emberite is the aggressive tier: +2.8 attack bonus and 7.2 mining speed at iron-level harvest.",
				"Emberite ist die aggressive Stufe: +2,8 Angriffsbonus und 7,2 Abbaugeschwindigkeit auf Eisen-Abbaustufe."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_ashsteel_chestplate",
				"copper_inferno:ashsteel_chestplate", "arsenal/ashsteel_chestplate",
				new String[]{AS, CAT, AS, AS, AS, AS, AS, AS, AS}, "copper_inferno:ashsteel_chestplate", 1,
				"Ashsteel is the durable workhorse tier: diamond-level tools with 1180 durability, armor with 1.5 toughness.",
				"Ashsteel ist die robuste Arbeitsstufe: Werkzeuge auf Diamant-Niveau mit 1180 Haltbarkeit, R\u00fcstung mit 1,5 Z\u00e4higkeit."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_voidsteel_sword",
				"copper_inferno:voidsteel_sword", "arsenal/voidsteel_sword",
				new String[]{VS, "", "", VS, CAT, "", STK, "", ""}, "copper_inferno:voidsteel_sword", 1,
				"Voidsteel sits just under netherite: 1650 durability, +3.2 damage, armor with 2.5 toughness and knockback resistance.",
				"Voidsteel liegt knapp unter Netherit: 1650 Haltbarkeit, +3,2 Schaden, R\u00fcstung mit 2,5 Z\u00e4higkeit und R\u00fccksto\u00dfresistenz."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_ember_javelin",
				"copper_inferno:ember_javelin", "arsenal/ember_javelin",
				new String[]{EM, "", "", "copper_inferno:javelin_shaft", "", "", "copper_inferno:javelin_shaft", "", ""},
				"copper_inferno:ember_javelin", 2,
				"The Ember Javelin: right-click to hurl it up to 16 blocks; the first creature hit takes 7 damage and catches fire.",
				"Der Glutspeer: Rechtsklick schleudert ihn bis zu 16 Bl\u00f6cke weit; das erste getroffene Wesen erleidet 7 Schaden und f\u00e4ngt Feuer."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_slag_hammer",
				"copper_inferno:slag_hammer", "arsenal/slag_hammer",
				new String[]{"copper_inferno:tempered_plate", "copper_inferno:tempered_plate", "copper_inferno:tempered_plate",
						"copper_inferno:tempered_plate", "copper_inferno:weapon_grip", "copper_inferno:tempered_plate",
						"", "copper_inferno:weapon_grip", ""},
				"copper_inferno:slag_hammer", 1,
				"The Slag Hammer slams the ground on use: everything within 3 blocks takes 5 damage and is hurled away. 5s cooldown.",
				"Der Schlackehammer schl\u00e4gt bei Benutzung auf den Boden: alles im Umkreis von 3 Bl\u00f6cken erleidet 5 Schaden und wird weggeschleudert. 5s Abklingzeit."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_ash_grenade",
				"copper_inferno:ash_grenade", "arsenal/ash_grenade",
				new String[]{"copper_inferno:blast_powder", "copper_inferno:ash_pile", "", "", "", "", "", "", ""},
				"copper_inferno:ash_grenade", 2,
				"The Ash Grenade bursts into a choking cloud that blinds and slows everything inside it.",
				"Die Aschegranate zerplatzt zu einer erstickenden Wolke, die alles darin blendet und verlangsamt."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_magnet_charm",
				"copper_inferno:magnet_charm", "arsenal/magnet_charm",
				new String[]{"", "minecraft:iron_ingot", "", "minecraft:iron_ingot", "minecraft:redstone", "minecraft:iron_ingot",
						"", "copper_inferno:charm_locket", ""},
				"copper_inferno:magnet_charm", 1,
				"The Magnet Charm yanks every dropped item within 12 blocks toward you - the unbreakable big sibling of the Copper Magnet.",
				"Das Magnetamulett zieht jeden fallengelassenen Gegenstand im Umkreis von 12 Bl\u00f6cken zu dir - der unzerst\u00f6rbare gro\u00dfe Bruder des Kupfermagneten."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_copper_grapnel",
				"copper_inferno:copper_grapnel", "arsenal/copper_grapnel",
				new String[]{"copper_inferno:grapnel_hook", "", "", "minecraft:string", "", "", "minecraft:copper_ingot", "", ""},
				"copper_inferno:copper_grapnel", 1,
				"The Copper Grapnel launches you along your line of sight - a spring-loaded escape (or entrance).",
				"Der Kupfer-Enterhaken schleudert dich entlang deiner Blickrichtung - ein federgetriebener Ausweg (oder Auftritt)."));
		HandbookEntries.add(new HandbookEntry("gear", "arsenal_prospector_lens",
				"copper_inferno:prospector_lens", "arsenal/prospector_lens",
				new String[]{"", "minecraft:copper_ingot", "", "minecraft:copper_ingot", "copper_inferno:lens_blank",
						"minecraft:copper_ingot", "", DUS, ""},
				"copper_inferno:prospector_lens", 1,
				"Peer through the Prospector Lens to count every ore within 8 blocks - vanilla, infernium and all twelve gem alloys.",
				"Ein Blick durch die Sch\u00fcrferlinse z\u00e4hlt jedes Erz im Umkreis von 8 Bl\u00f6cken - Vanilla, Infernium und alle zw\u00f6lf Edelmetalle."));
	}
}
