package net.sonic0810.copperinferno.feature.legacyhandbook;

/**
 * Handbook coverage for the 12 legacy (pre-v3) recipe dirs plus lore pages for the
 * recipe-less flagship features (Dr.Pepper brewing/DOOM, Dr.Pepper golems, copper
 * armor/tool oxidation). Registers handbook entries ONLY - no blocks, items or
 * recipes; the documented content is owned by the original legacy features.
 *
 * <p>Generated by {@code devtools/gen/legacyhandbook_gen.py}; must be initialized
 * immediately before {@code HandbookFeature.init()} (which stays last).
 */
public final class LegacyHandbookFeature {
	private LegacyHandbookFeature() {
	}

	public static void init() {
		LegacyMasonryHandbook.register();
		LegacySodablocksHandbook.register();
		LegacyMaterialsHandbook.register();
		LegacyDecostoneHandbook.register();
		LegacyFoodsHandbook.register();
		LegacyInfernoHandbook.register();
		LegacyMusicHandbook.register();
		LegacyUtilityblocksHandbook.register();
		LegacyGlasslightHandbook.register();
		LegacyGearHandbook.register();
		LegacyExtrasHandbook.register();
		LegacyStatueHandbook.register();
		LegacyLoreHandbook.register();
	}
}
