package net.sonic0810.copperinferno.feature.legacyhandbook;

import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * Lore pages (no recipeId/grid) for the flagship recipe-less legacy features:
 * Dr.Pepper brewing + the DOOM kick, Dr.Pepper golems, and copper armor/tool
 * oxidation. Generated by {@code devtools/gen/legacyhandbook_gen.py}.
 */
final class LegacyLoreHandbook {
	private LegacyLoreHandbook() {
	}

	static void register() {
		HandbookEntries.add(new HandbookEntry("items", "legacyhandbook/dr_pepper_brewing", "copper_inferno:dr_pepper", null,
				null,
				null, 0, "Dr.Pepper is brewed at a brewing stand: a Water Bottle plus Black Dye makes the Dark Soda Base, Sugar turns it into Sweet Dark Brew, and Gunpowder finishes the can. Drinking it grants Speed V plus the Dr.Pepper kick, which unleashes the DOOM soundtrack and motion blur on the client.", "Dr.Pepper wird am Braustand gebraut: Eine Wasserflasche plus Schwarzer Farbstoff ergibt die Dunkle Limonadenbasis, Zucker macht daraus S\u00fc\u00dfes Dunkles Gebr\u00e4u und Schwarzpulver vollendet die Dose. Beim Trinken gibt es Schnelligkeit V und den Dr.Pepper-Kick, der clientseitig den DOOM-Soundtrack und die Bewegungsunsch\u00e4rfe entfesselt."));

		HandbookEntries.add(new HandbookEntry("mobs", "legacyhandbook/dr_pepper_golem", "copper_inferno:dr_pepper_golem", null,
				null,
				null, 0, "Right-click a vanilla Copper Golem with a Dr.Pepper to convert it into a Dr.Pepper Golem; health, name, equipment and effects carry over. Players standing close to the golem hear its DOOM proximity aura. The Dr.Pepper Golem Spawn Can places one directly.", "Rechtsklickt einen Kupfergolem mit einem Dr.Pepper, um ihn in einen Dr.Pepper-Golem zu verwandeln; Leben, Name, Ausr\u00fcstung und Effekte bleiben erhalten. Wer nahe beim Golem steht, h\u00f6rt seine DOOM-N\u00e4he-Aura. Die Dr.Pepper-Golem-Spawn-Dose setzt direkt einen Golem in die Welt."));

		HandbookEntries.add(new HandbookEntry("gear", "legacyhandbook/copper_armor_oxidation", "copper_inferno:exposed_copper_helmet", null,
				null,
				null, 0, "Copper armor oxidizes over time: each vanilla copper piece weathers through the exposed, weathered and oxidized stages, keeping enchantments, damage and name. Scrape a piece with an axe to remove one stage, or wax it with a honeycomb to freeze its patina.", "Kupferr\u00fcstung oxidiert mit der Zeit: Jedes Kupfer-R\u00fcstungsteil durchl\u00e4uft die Stufen angelaufen, verwittert und oxidiert und beh\u00e4lt dabei Verzauberungen, Haltbarkeit und Namen. Mit einer Axt kratzt ihr eine Stufe wieder ab, mit einer Honigwabe wachst ihr das Teil und friert die Patina ein."));

		HandbookEntries.add(new HandbookEntry("gear", "legacyhandbook/copper_tool_oxidation", "copper_inferno:exposed_copper_pickaxe", null,
				null,
				null, 0, "Copper tools oxidize just like the armor: sword, pickaxe, axe, shovel and hoe pass through the exposed, weathered and oxidized stages. An axe scrapes a stage off again, and a honeycomb waxes the tool to stop further oxidation.", "Kupferwerkzeuge oxidieren wie die R\u00fcstung: Schwert, Spitzhacke, Axt, Schaufel und Hacke durchlaufen die Stufen angelaufen, verwittert und oxidiert. Eine Axt kratzt eine Stufe wieder ab, und eine Honigwabe wachst das Werkzeug, sodass es nicht weiter oxidiert."));
	}
}
