package net.sonic0810.copperinferno.feature.infernofauna;

import java.util.function.Predicate;

import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.SpawnLocationTypes;
import net.minecraft.entity.SpawnRestriction;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.mob.CaveSpiderEntity;
import net.minecraft.entity.mob.EndermiteEntity;
import net.minecraft.entity.mob.GhastEntity;
import net.minecraft.entity.mob.GuardianEntity;
import net.minecraft.entity.mob.HoglinEntity;
import net.minecraft.entity.mob.HostileEntity;
import net.minecraft.entity.mob.MagmaCubeEntity;
import net.minecraft.entity.mob.MobEntity;
import net.minecraft.entity.mob.SilverfishEntity;
import net.minecraft.entity.mob.SpiderEntity;
import net.minecraft.entity.mob.VexEntity;
import net.minecraft.entity.mob.ZombieEntity;
import net.minecraft.entity.passive.BatEntity;
import net.minecraft.entity.passive.FrogEntity;
import net.minecraft.entity.passive.GoatEntity;
import net.minecraft.entity.passive.IronGolemEntity;
import net.minecraft.entity.passive.ParrotEntity;
import net.minecraft.entity.passive.PigEntity;
import net.minecraft.entity.passive.SheepEntity;
import net.minecraft.entity.passive.StriderEntity;
import net.minecraft.entity.passive.TurtleEntity;
import net.minecraft.entity.passive.WolfEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.math.Vec3d;
import net.minecraft.world.Difficulty;
import net.minecraft.world.Heightmap;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Inferno Wildlife": 24 mobs native to the Inferno dimension, each extending a vanilla
 * entity with exactly one headline behavioral tweak (see the individual entity classes; some
 * breeders additionally get a covariant {@code createChild} type-consistency fix, the pattern
 * proven by the infernomobs Cinder Strider). EntityType dimensions/eye heights/attachments are
 * copied 1:1 from the vanilla {@code EntityType} registrations (bytecode-verified via javap).
 * Registers spawn eggs + 12 mob-drop items into the FAUNA creative tab, natural spawns in the
 * three Inferno biomes, spawn restrictions, and one handbook entry per mob. Assets (item
 * defs/models/textures, entity textures, loot tables, recipes, lang fragments) are generated by
 * {@code devtools/gen/infernofauna_gen.py}.
 */
public final class InfernoFaunaFeature {
	private InfernoFaunaFeature() {
	}

	public static EntityType<MagmaHopperEntity> MAGMA_HOPPER;
	public static EntityType<CinderHoundEntity> CINDER_HOUND;
	public static EntityType<EmberMothEntity> EMBER_MOTH;
	public static EntityType<SlagSnailEntity> SLAG_SNAIL;
	public static EntityType<PyreRavenEntity> PYRE_RAVEN;
	public static EntityType<AshStalkerEntity> ASH_STALKER;
	public static EntityType<FumaroleFrogEntity> FUMAROLE_FROG;
	public static EntityType<SootPigletEntity> SOOT_PIGLET;
	public static EntityType<ScorchGoatEntity> SCORCH_GOAT;
	public static EntityType<LavaEelEntity> LAVA_EEL;
	public static EntityType<EmberOwlEntity> EMBER_OWL;
	public static EntityType<CinderToadEntity> CINDER_TOAD;
	public static EntityType<FlareWispEntity> FLARE_WISP;
	public static EntityType<SmolderTortoiseEntity> SMOLDER_TORTOISE;
	public static EntityType<BrimstoneBullEntity> BRIMSTONE_BULL;
	public static EntityType<AshWandererEntity> ASH_WANDERER;
	public static EntityType<PyroclastGolemEntity> PYROCLAST_GOLEM;
	public static EntityType<EmberSerpentEntity> EMBER_SERPENT;
	public static EntityType<SootSheepEntity> SOOT_SHEEP;
	public static EntityType<GlowStriderEntity> GLOW_STRIDER;
	public static EntityType<KilnSpiderEntity> KILN_SPIDER;
	public static EntityType<CharPhantomEntity> CHAR_PHANTOM;
	public static EntityType<MoltenMiteEntity> MOLTEN_MITE;
	public static EntityType<InfernoGhastlingEntity> INFERNO_GHASTLING;

	public static Item MAGMA_HOPPER_SPAWN_EGG;
	public static Item CINDER_HOUND_SPAWN_EGG;
	public static Item EMBER_MOTH_SPAWN_EGG;
	public static Item SLAG_SNAIL_SPAWN_EGG;
	public static Item PYRE_RAVEN_SPAWN_EGG;
	public static Item ASH_STALKER_SPAWN_EGG;
	public static Item FUMAROLE_FROG_SPAWN_EGG;
	public static Item SOOT_PIGLET_SPAWN_EGG;
	public static Item SCORCH_GOAT_SPAWN_EGG;
	public static Item LAVA_EEL_SPAWN_EGG;
	public static Item EMBER_OWL_SPAWN_EGG;
	public static Item CINDER_TOAD_SPAWN_EGG;
	public static Item FLARE_WISP_SPAWN_EGG;
	public static Item SMOLDER_TORTOISE_SPAWN_EGG;
	public static Item BRIMSTONE_BULL_SPAWN_EGG;
	public static Item ASH_WANDERER_SPAWN_EGG;
	public static Item PYROCLAST_GOLEM_SPAWN_EGG;
	public static Item EMBER_SERPENT_SPAWN_EGG;
	public static Item SOOT_SHEEP_SPAWN_EGG;
	public static Item GLOW_STRIDER_SPAWN_EGG;
	public static Item KILN_SPIDER_SPAWN_EGG;
	public static Item CHAR_PHANTOM_SPAWN_EGG;
	public static Item MOLTEN_MITE_SPAWN_EGG;
	public static Item INFERNO_GHASTLING_SPAWN_EGG;

	public static Item HOPPER_SLAG;
	public static Item SINGED_FANG;
	public static Item EMBER_WING;
	public static Item SLAG_SHELL;
	public static Item PYRE_FEATHER;
	public static Item FUMAROLE_GLAND;
	public static Item SCORCHED_HORN;
	public static Item LAVA_EEL_FILLET;
	public static Item FLARE_ESSENCE;
	public static Item SMOLDER_SCUTE;
	public static Item BRIMSTONE_HIDE;
	public static Item PYROCLAST_CORE;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		registerSpawning();
		registerHandbookEntries();
	}

	private static void registerEntityTypes() {
		// All builder chains are copied 1:1 from the vanilla EntityType registrations
		// (bytecode-verified via javap -c on EntityType's <clinit>); each comment quotes the
		// vanilla source entry. Builders are created FRESH per registration.
		// magma_cube = makeFireImmune().dimensions(0.52f, 0.52f).eyeHeight(0.325f)
		// .spawnBoxScale(4.0f).maxTrackingRange(8).notAllowedInPeaceful()
		MAGMA_HOPPER = ModEntities.register("magma_hopper",
				EntityType.Builder.create(MagmaHopperEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.52f, 0.52f)
						.eyeHeight(0.325f)
						.spawnBoxScale(4.0f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// wolf = dimensions(0.6f, 0.85f).eyeHeight(0.68f)
		// .passengerAttachments(new Vec3d(0.0, 0.81875, -0.0625)).maxTrackingRange(10)
		CINDER_HOUND = ModEntities.register("cinder_hound",
				EntityType.Builder.create(CinderHoundEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.6f, 0.85f)
						.eyeHeight(0.68f)
						.passengerAttachments(new Vec3d(0.0, 0.81875, -0.0625))
						.maxTrackingRange(10));
		// bat = dimensions(0.5f, 0.9f).eyeHeight(0.45f).maxTrackingRange(5)
		EMBER_MOTH = ModEntities.register("ember_moth",
				EntityType.Builder.create(EmberMothEntity::new, SpawnGroup.AMBIENT)
						.dimensions(0.5f, 0.9f)
						.eyeHeight(0.45f)
						.maxTrackingRange(5));
		// silverfish = dimensions(0.4f, 0.3f).eyeHeight(0.13f).passengerAttachments(0.2375f)
		// .maxTrackingRange(8).notAllowedInPeaceful()
		SLAG_SNAIL = ModEntities.register("slag_snail",
				EntityType.Builder.create(SlagSnailEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// parrot = dimensions(0.5f, 0.9f).eyeHeight(0.54f).passengerAttachments(0.4625f)
		// .maxTrackingRange(8)
		PYRE_RAVEN = ModEntities.register("pyre_raven",
				EntityType.Builder.create(PyreRavenEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.5f, 0.9f)
						.eyeHeight(0.54f)
						.passengerAttachments(0.4625f)
						.maxTrackingRange(8));
		// spider = dimensions(1.4f, 0.9f).eyeHeight(0.65f).passengerAttachments(0.765f)
		// .maxTrackingRange(8).notAllowedInPeaceful()
		ASH_STALKER = ModEntities.register("ash_stalker",
				EntityType.Builder.create(AshStalkerEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.4f, 0.9f)
						.eyeHeight(0.65f)
						.passengerAttachments(0.765f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// frog = dimensions(0.5f, 0.5f).passengerAttachments(new Vec3d(0.0, 0.375, -0.25))
		// .maxTrackingRange(10)
		FUMAROLE_FROG = ModEntities.register("fumarole_frog",
				EntityType.Builder.create(FumaroleFrogEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.5f, 0.5f)
						.passengerAttachments(new Vec3d(0.0, 0.375, -0.25))
						.maxTrackingRange(10));
		// pig = dimensions(0.9f, 0.9f).passengerAttachments(0.86875f).maxTrackingRange(10)
		SOOT_PIGLET = ModEntities.register("soot_piglet",
				EntityType.Builder.create(SootPigletEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 0.9f)
						.passengerAttachments(0.86875f)
						.maxTrackingRange(10));
		// goat = dimensions(0.9f, 1.3f).passengerAttachments(1.1125f).maxTrackingRange(10)
		SCORCH_GOAT = ModEntities.register("scorch_goat",
				EntityType.Builder.create(ScorchGoatEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.3f)
						.passengerAttachments(1.1125f)
						.maxTrackingRange(10));
		// guardian = dimensions(0.85f, 0.85f).eyeHeight(0.425f).passengerAttachments(0.975f)
		// .maxTrackingRange(8).notAllowedInPeaceful(); made fire-immune ON TOP of vanilla so
		// the lava it lives in cannot kill it.
		LAVA_EEL = ModEntities.register("lava_eel",
				EntityType.Builder.create(LavaEelEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.85f, 0.85f)
						.eyeHeight(0.425f)
						.passengerAttachments(0.975f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// parrot dimensions again (fresh builder).
		EMBER_OWL = ModEntities.register("ember_owl",
				EntityType.Builder.create(EmberOwlEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.5f, 0.9f)
						.eyeHeight(0.54f)
						.passengerAttachments(0.4625f)
						.maxTrackingRange(8));
		// frog dimensions again (fresh builder).
		CINDER_TOAD = ModEntities.register("cinder_toad",
				EntityType.Builder.create(CinderToadEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.5f, 0.5f)
						.passengerAttachments(new Vec3d(0.0, 0.375, -0.25))
						.maxTrackingRange(10));
		// vex = makeFireImmune().dimensions(0.4f, 0.8f).eyeHeight(0.51875f)
		// .passengerAttachments(0.7375f).vehicleAttachment(0.04f).maxTrackingRange(8)
		// .notAllowedInPeaceful()
		FLARE_WISP = ModEntities.register("flare_wisp",
				EntityType.Builder.create(FlareWispEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.4f, 0.8f)
						.eyeHeight(0.51875f)
						.passengerAttachments(0.7375f)
						.vehicleAttachment(0.04f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// turtle = dimensions(1.2f, 0.4f).passengerAttachments(new Vec3d(0.0, 0.55625, -0.25))
		// .maxTrackingRange(10)
		SMOLDER_TORTOISE = ModEntities.register("smolder_tortoise",
				EntityType.Builder.create(SmolderTortoiseEntity::new, SpawnGroup.CREATURE)
						.dimensions(1.2f, 0.4f)
						.passengerAttachments(new Vec3d(0.0, 0.55625, -0.25))
						.maxTrackingRange(10));
		// hoglin = dimensions(1.3964844f, 1.4f).passengerAttachments(1.49375f)
		// .maxTrackingRange(8)
		BRIMSTONE_BULL = ModEntities.register("brimstone_bull",
				EntityType.Builder.create(BrimstoneBullEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.3964844f, 1.4f)
						.passengerAttachments(1.49375f)
						.maxTrackingRange(8));
		// husk = dimensions(0.6f, 1.95f).eyeHeight(1.74f).passengerAttachments(2.075f)
		// .vehicleAttachment(-0.7f).maxTrackingRange(8).notAllowedInPeaceful()
		ASH_WANDERER = ModEntities.register("ash_wanderer",
				EntityType.Builder.create(AshWandererEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.075f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// iron_golem = dimensions(1.4f, 2.7f).maxTrackingRange(10). Vanilla registers it in
		// SpawnGroup.MISC (village-summoned only); the wild pyroclast golem uses CREATURE so
		// BiomeModifications natural spawning works against a real mob cap.
		PYROCLAST_GOLEM = ModEntities.register("pyroclast_golem",
				EntityType.Builder.create(PyroclastGolemEntity::new, SpawnGroup.CREATURE)
						.dimensions(1.4f, 2.7f)
						.maxTrackingRange(10));
		// cave_spider = dimensions(0.7f, 0.5f).eyeHeight(0.45f).maxTrackingRange(8)
		// .notAllowedInPeaceful()
		EMBER_SERPENT = ModEntities.register("ember_serpent",
				EntityType.Builder.create(EmberSerpentEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.7f, 0.5f)
						.eyeHeight(0.45f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// sheep = dimensions(0.9f, 1.3f).eyeHeight(1.235f).passengerAttachments(1.2375f)
		// .maxTrackingRange(10)
		SOOT_SHEEP = ModEntities.register("soot_sheep",
				EntityType.Builder.create(SootSheepEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.3f)
						.eyeHeight(1.235f)
						.passengerAttachments(1.2375f)
						.maxTrackingRange(10));
		// strider = makeFireImmune().dimensions(0.9f, 1.7f).maxTrackingRange(10)
		GLOW_STRIDER = ModEntities.register("glow_strider",
				EntityType.Builder.create(GlowStriderEntity::new, SpawnGroup.CREATURE)
						.makeFireImmune()
						.dimensions(0.9f, 1.7f)
						.maxTrackingRange(10));
		// spider dimensions again (fresh builder).
		KILN_SPIDER = ModEntities.register("kiln_spider",
				EntityType.Builder.create(KilnSpiderEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.4f, 0.9f)
						.eyeHeight(0.65f)
						.passengerAttachments(0.765f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// phantom = dimensions(0.9f, 0.5f).eyeHeight(0.175f).passengerAttachments(0.3375f)
		// .vehicleAttachment(-0.125f).maxTrackingRange(8).notAllowedInPeaceful()
		CHAR_PHANTOM = ModEntities.register("char_phantom",
				EntityType.Builder.create(CharPhantomEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.9f, 0.5f)
						.eyeHeight(0.175f)
						.passengerAttachments(0.3375f)
						.vehicleAttachment(-0.125f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// endermite = dimensions(0.4f, 0.3f).eyeHeight(0.13f).passengerAttachments(0.2375f)
		// .maxTrackingRange(8).notAllowedInPeaceful()
		MOLTEN_MITE = ModEntities.register("molten_mite",
				EntityType.Builder.create(MoltenMiteEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// ghast = makeFireImmune().dimensions(4.0f, 4.0f).eyeHeight(2.6f)
		// .passengerAttachments(4.0625f).vehicleAttachment(0.5f).maxTrackingRange(10)
		// .notAllowedInPeaceful(); the runt SCALE lives in the attributes, not here.
		INFERNO_GHASTLING = ModEntities.register("inferno_ghastling",
				EntityType.Builder.create(InfernoGhastlingEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(4.0f, 4.0f)
						.eyeHeight(2.6f)
						.passengerAttachments(4.0625f)
						.vehicleAttachment(0.5f)
						.maxTrackingRange(10)
						.notAllowedInPeaceful());
	}

	private static void registerAttributes() {
		// FabricDefaultAttributeRegistry.register is MANDATORY for every custom mob (the
		// vanilla DefaultAttributeRegistry only knows vanilla types). Base builders are the
		// vanilla createXAttributes() factories (verified via javap); phantom has no factory of
		// its own — vanilla maps EntityType.PHANTOM to HostileEntity.createHostileAttributes()
		// (DefaultAttributeRegistry bytecode-verified). Husks likewise reuse
		// ZombieEntity.createZombieAttributes() (which carries the mandatory
		// ZOMBIE_SPAWN_REINFORCEMENTS attribute ZombieEntity.initialize reads).
		FabricDefaultAttributeRegistry.register(MAGMA_HOPPER, MagmaCubeEntity.createMagmaCubeAttributes());
		FabricDefaultAttributeRegistry.register(CINDER_HOUND, WolfEntity.createWolfAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_MOTH, BatEntity.createBatAttributes());
		FabricDefaultAttributeRegistry.register(SLAG_SNAIL, SilverfishEntity.createSilverfishAttributes());
		FabricDefaultAttributeRegistry.register(PYRE_RAVEN, ParrotEntity.createParrotAttributes());
		FabricDefaultAttributeRegistry.register(ASH_STALKER, SpiderEntity.createSpiderAttributes());
		FabricDefaultAttributeRegistry.register(FUMAROLE_FROG, FrogEntity.createFrogAttributes());
		FabricDefaultAttributeRegistry.register(SOOT_PIGLET, PigEntity.createPigAttributes());
		FabricDefaultAttributeRegistry.register(SCORCH_GOAT, GoatEntity.createGoatAttributes());
		FabricDefaultAttributeRegistry.register(LAVA_EEL, GuardianEntity.createGuardianAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_OWL, ParrotEntity.createParrotAttributes());
		FabricDefaultAttributeRegistry.register(CINDER_TOAD, FrogEntity.createFrogAttributes());
		FabricDefaultAttributeRegistry.register(FLARE_WISP, VexEntity.createVexAttributes());
		// Smolder Tortoise headline tweak: immovable (KNOCKBACK_RESISTANCE 1.0).
		FabricDefaultAttributeRegistry.register(SMOLDER_TORTOISE, TurtleEntity.createTurtleAttributes()
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 1.0));
		FabricDefaultAttributeRegistry.register(BRIMSTONE_BULL, HoglinEntity.createHoglinAttributes());
		FabricDefaultAttributeRegistry.register(ASH_WANDERER, ZombieEntity.createZombieAttributes());
		FabricDefaultAttributeRegistry.register(PYROCLAST_GOLEM, IronGolemEntity.createIronGolemAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_SERPENT, CaveSpiderEntity.createCaveSpiderAttributes());
		FabricDefaultAttributeRegistry.register(SOOT_SHEEP, SheepEntity.createSheepAttributes());
		FabricDefaultAttributeRegistry.register(GLOW_STRIDER, StriderEntity.createStriderAttributes());
		FabricDefaultAttributeRegistry.register(KILN_SPIDER, SpiderEntity.createSpiderAttributes());
		FabricDefaultAttributeRegistry.register(CHAR_PHANTOM, HostileEntity.createHostileAttributes());
		FabricDefaultAttributeRegistry.register(MOLTEN_MITE, EndermiteEntity.createEndermiteAttributes());
		// Inferno Ghastling headline tweak: a runt — cat-sized (SCALE 0.35) and two-hit
		// (MAX_HEALTH 6, vanilla ghast has 10).
		FabricDefaultAttributeRegistry.register(INFERNO_GHASTLING, GhastEntity.createGhastAttributes()
				.add(EntityAttributes.SCALE, 0.35)
				.add(EntityAttributes.MAX_HEALTH, 6.0));
	}

	private static void registerItems() {
		// Item.Settings.spawnEgg(type) stores the ENTITY_DATA component the vanilla
		// SpawnEggItem reads its entity type from in 1.21.9 (same proven pattern as the
		// infernomobs eggs). Settings are FRESH per registration.
		MAGMA_HOPPER_SPAWN_EGG = ModItems.register("magma_hopper_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MAGMA_HOPPER));
		CINDER_HOUND_SPAWN_EGG = ModItems.register("cinder_hound_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_HOUND));
		EMBER_MOTH_SPAWN_EGG = ModItems.register("ember_moth_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_MOTH));
		SLAG_SNAIL_SPAWN_EGG = ModItems.register("slag_snail_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_SNAIL));
		PYRE_RAVEN_SPAWN_EGG = ModItems.register("pyre_raven_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(PYRE_RAVEN));
		ASH_STALKER_SPAWN_EGG = ModItems.register("ash_stalker_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_STALKER));
		FUMAROLE_FROG_SPAWN_EGG = ModItems.register("fumarole_frog_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(FUMAROLE_FROG));
		SOOT_PIGLET_SPAWN_EGG = ModItems.register("soot_piglet_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_PIGLET));
		SCORCH_GOAT_SPAWN_EGG = ModItems.register("scorch_goat_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SCORCH_GOAT));
		LAVA_EEL_SPAWN_EGG = ModItems.register("lava_eel_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(LAVA_EEL));
		EMBER_OWL_SPAWN_EGG = ModItems.register("ember_owl_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_OWL));
		CINDER_TOAD_SPAWN_EGG = ModItems.register("cinder_toad_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_TOAD));
		FLARE_WISP_SPAWN_EGG = ModItems.register("flare_wisp_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(FLARE_WISP));
		SMOLDER_TORTOISE_SPAWN_EGG = ModItems.register("smolder_tortoise_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SMOLDER_TORTOISE));
		BRIMSTONE_BULL_SPAWN_EGG = ModItems.register("brimstone_bull_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(BRIMSTONE_BULL));
		ASH_WANDERER_SPAWN_EGG = ModItems.register("ash_wanderer_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_WANDERER));
		PYROCLAST_GOLEM_SPAWN_EGG = ModItems.register("pyroclast_golem_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(PYROCLAST_GOLEM));
		EMBER_SERPENT_SPAWN_EGG = ModItems.register("ember_serpent_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_SERPENT));
		SOOT_SHEEP_SPAWN_EGG = ModItems.register("soot_sheep_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_SHEEP));
		GLOW_STRIDER_SPAWN_EGG = ModItems.register("glow_strider_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(GLOW_STRIDER));
		KILN_SPIDER_SPAWN_EGG = ModItems.register("kiln_spider_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(KILN_SPIDER));
		CHAR_PHANTOM_SPAWN_EGG = ModItems.register("char_phantom_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CHAR_PHANTOM));
		MOLTEN_MITE_SPAWN_EGG = ModItems.register("molten_mite_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MOLTEN_MITE));
		INFERNO_GHASTLING_SPAWN_EGG = ModItems.register("inferno_ghastling_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(INFERNO_GHASTLING));

		HOPPER_SLAG = ModItems.register("hopper_slag", Item::new, new Item.Settings());
		SINGED_FANG = ModItems.register("singed_fang", Item::new, new Item.Settings());
		EMBER_WING = ModItems.register("ember_wing", Item::new, new Item.Settings());
		SLAG_SHELL = ModItems.register("slag_shell", Item::new, new Item.Settings());
		PYRE_FEATHER = ModItems.register("pyre_feather", Item::new, new Item.Settings());
		FUMAROLE_GLAND = ModItems.register("fumarole_gland", Item::new, new Item.Settings());
		SCORCHED_HORN = ModItems.register("scorched_horn", Item::new, new Item.Settings());
		LAVA_EEL_FILLET = ModItems.register("lava_eel_fillet", Item::new, new Item.Settings());
		FLARE_ESSENCE = ModItems.register("flare_essence", Item::new, new Item.Settings());
		SMOLDER_SCUTE = ModItems.register("smolder_scute", Item::new, new Item.Settings());
		BRIMSTONE_HIDE = ModItems.register("brimstone_hide", Item::new, new Item.Settings());
		PYROCLAST_CORE = ModItems.register("pyroclast_core", Item::new, new Item.Settings());

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.FAUNA_KEY).register(entries -> {
			// Spawn eggs in roster order, then the twelve mob drops.
			entries.add(MAGMA_HOPPER_SPAWN_EGG);
			entries.add(CINDER_HOUND_SPAWN_EGG);
			entries.add(EMBER_MOTH_SPAWN_EGG);
			entries.add(SLAG_SNAIL_SPAWN_EGG);
			entries.add(PYRE_RAVEN_SPAWN_EGG);
			entries.add(ASH_STALKER_SPAWN_EGG);
			entries.add(FUMAROLE_FROG_SPAWN_EGG);
			entries.add(SOOT_PIGLET_SPAWN_EGG);
			entries.add(SCORCH_GOAT_SPAWN_EGG);
			entries.add(LAVA_EEL_SPAWN_EGG);
			entries.add(EMBER_OWL_SPAWN_EGG);
			entries.add(CINDER_TOAD_SPAWN_EGG);
			entries.add(FLARE_WISP_SPAWN_EGG);
			entries.add(SMOLDER_TORTOISE_SPAWN_EGG);
			entries.add(BRIMSTONE_BULL_SPAWN_EGG);
			entries.add(ASH_WANDERER_SPAWN_EGG);
			entries.add(PYROCLAST_GOLEM_SPAWN_EGG);
			entries.add(EMBER_SERPENT_SPAWN_EGG);
			entries.add(SOOT_SHEEP_SPAWN_EGG);
			entries.add(GLOW_STRIDER_SPAWN_EGG);
			entries.add(KILN_SPIDER_SPAWN_EGG);
			entries.add(CHAR_PHANTOM_SPAWN_EGG);
			entries.add(MOLTEN_MITE_SPAWN_EGG);
			entries.add(INFERNO_GHASTLING_SPAWN_EGG);
			entries.add(HOPPER_SLAG);
			entries.add(SINGED_FANG);
			entries.add(EMBER_WING);
			entries.add(SLAG_SHELL);
			entries.add(PYRE_FEATHER);
			entries.add(FUMAROLE_GLAND);
			entries.add(SCORCHED_HORN);
			entries.add(LAVA_EEL_FILLET);
			entries.add(FLARE_ESSENCE);
			entries.add(SMOLDER_SCUTE);
			entries.add(BRIMSTONE_HIDE);
			entries.add(PYROCLAST_CORE);
		});
	}

	private static void registerSpawning() {
		// SpawnRestriction.register is private in vanilla but access-widened by Fabric's
		// transitive access wideners (proven by the infernomobs feature). Predicate choice per
		// the infernomobs precedent: HostileEntity::canSpawnIgnoreLightLevel for monsters whose
		// base extends HostileEntity (nether-style hostiles ignore light); a plain
		// difficulty != PEACEFUL lambda for monsters outside the HostileEntity hierarchy
		// (magma cube/slime, hoglin/animal, phantom+ghast/mob) — mirroring vanilla
		// canMagmaCubeSpawn, whose vanilla method is typed to the vanilla EntityType; and
		// MobEntity::canMobSpawn for creatures/ambients, because the vanilla animal predicate
		// (isValidNaturalSpawn) gates on grass + light and would starve every spawn in the
		// Inferno (same reasoning as the infernomobs Ash Bat inferno branch).
		SpawnRestriction.register(MAGMA_HOPPER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(CINDER_HOUND, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(EMBER_MOTH, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(SLAG_SNAIL, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(PYRE_RAVEN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(ASH_STALKER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(FUMAROLE_FROG, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(SOOT_PIGLET, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(SCORCH_GOAT, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		// The eel spawns inside the Slag Sea's lava columns, like a vanilla strider.
		SpawnRestriction.register(LAVA_EEL, SpawnLocationTypes.IN_LAVA,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(EMBER_OWL, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(CINDER_TOAD, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(FLARE_WISP, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(SMOLDER_TORTOISE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(BRIMSTONE_BULL, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(ASH_WANDERER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(PYROCLAST_GOLEM, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(EMBER_SERPENT, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(SOOT_SHEEP, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		// Glow striders wade the lava like their vanilla cousins (IN_LAVA, strider precedent).
		SpawnRestriction.register(GLOW_STRIDER, SpawnLocationTypes.IN_LAVA,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, MobEntity::canMobSpawn);
		SpawnRestriction.register(KILN_SPIDER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(CHAR_PHANTOM, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(MOLTEN_MITE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(INFERNO_GHASTLING, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);

		// Natural spawns in the three Inferno biomes only (biome JSONs are owned by the
		// infernodim feature; includeByKey matches nothing until they are loaded). addSpawn
		// signature verified via javap: (Predicate<BiomeSelectionContext>, SpawnGroup,
		// EntityType, weight, minGroup, maxGroup).
		Predicate<BiomeSelectionContext> infernoBiomes = BiomeSelectors.includeByKey(
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("cinder_wastes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("ember_grove")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("slag_sea")));
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, MAGMA_HOPPER, 20, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAG_SNAIL, 20, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASH_STALKER, 15, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, LAVA_EEL, 10, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, FLARE_WISP, 10, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, BRIMSTONE_BULL, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASH_WANDERER, 15, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBER_SERPENT, 10, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, KILN_SPIDER, 15, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CHAR_PHANTOM, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, MOLTEN_MITE, 15, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, INFERNO_GHASTLING, 5, 1, 1);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, CINDER_HOUND, 8, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, PYRE_RAVEN, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, FUMAROLE_FROG, 8, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SOOT_PIGLET, 8, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SCORCH_GOAT, 6, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, EMBER_OWL, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, CINDER_TOAD, 8, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SMOLDER_TORTOISE, 5, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, PYROCLAST_GOLEM, 2, 1, 1);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SOOT_SHEEP, 8, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, GLOW_STRIDER, 10, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.AMBIENT, EMBER_MOTH, 10, 2, 4);
	}

	private static void registerHandbookEntries() {
		HandbookEntries.add(new HandbookEntry("mobs", "magma_hopper",
				"copper_inferno:magma_hopper_spawn_egg", null, null, null, 0,
				"Magma Hopper - a restless slag cube that hops many times faster than a magma cube and splits when slain. Drops Hopper Slag.",
				"Magmahüpfer - ein rastloser Schlackenwürfel, der viel schneller hüpft als ein Magmawürfel und sich beim Tod teilt. Lässt Hüpferschlacke fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "cinder_hound",
				"copper_inferno:cinder_hound_spawn_egg", null, null, null, 0,
				"Cinder Hound - a wolf of the Cinder Wastes whose smoldering bite sets prey on fire. Tameable like any wolf. Drops Singed Fangs.",
				"Zunderhund - ein Wolf der Aschenöde, dessen glimmender Biss die Beute in Brand setzt. Zähmbar wie jeder Wolf. Lässt Versengte Fangzähne fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "ember_moth",
				"copper_inferno:ember_moth_spawn_egg", null, null, null, 0,
				"Ember Moth - a moth-like bat with wings of living ember that glows permanently in the gloom. Harmless. Drops Ember Wings.",
				"Glutfalter - eine mottengleiche Fledermaus mit Schwingen aus lebender Glut, die dauerhaft im Dunkel leuchtet. Harmlos. Lässt Glutflügel fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "slag_snail",
				"copper_inferno:slag_snail_spawn_egg", null, null, null, 0,
				"Slag Snail - a slag-shelled crawler that idles in place like a true snail and never infests blocks. Drops Slag Shells.",
				"Schlackenschnecke - ein Kriecher mit Schlackengehäuse, der wie eine echte Schnecke auf der Stelle verharrt und niemals Blöcke befällt. Lässt Schlackengehäuse fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "pyre_raven",
				"copper_inferno:pyre_raven_spawn_egg", null, null, null, 0,
				"Pyre Raven - a raven-dark parrot with fireproof feathers; flames and lava cannot harm it. Drops Pyre Feathers.",
				"Feuerrabe - ein rabenschwarzer Papagei mit feuerfestem Gefieder; Flammen und Lava können ihm nichts anhaben. Lässt Feuerfedern fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "ash_stalker",
				"copper_inferno:ash_stalker_spawn_egg", null, null, null, 0,
				"Ash Stalker - a spider whose bite whips up a blinding ash cloud. Drops string.",
				"Aschenschleicher - eine Spinne, deren Biss eine blendende Aschewolke aufwirbelt. Lässt Fäden fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "fumarole_frog",
				"copper_inferno:fumarole_frog_spawn_egg", null, null, null, 0,
				"Fumarole Frog - a frog that squats on fumaroles and vents little plumes of smoke. Drops Fumarole Glands.",
				"Fumarolenfrosch - ein Frosch, der auf Fumarolen hockt und kleine Rauchfahnen ausstößt. Lässt Fumarolendrüsen fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "soot_piglet",
				"copper_inferno:soot_piglet_spawn_egg", null, null, null, 0,
				"Soot Piglet - a soot-black pig that lives pre-roasted: it drops cooked porkchops. Breeds true.",
				"Rußferkel - ein rußschwarzes Schwein, das schon vorgegart lebt: Es lässt gebratene Koteletts fallen. Vererbt sich rein."));
		HandbookEntries.add(new HandbookEntry("mobs", "scorch_goat",
				"copper_inferno:scorch_goat_spawn_egg", null, null, null, 0,
				"Scorch Goat - a goat with scorch-marked flanks that rams like its Overworld kin and breeds true. Drops Scorched Horns.",
				"Sengziege - eine Ziege mit versengten Flanken, die wie ihre Oberwelt-Verwandtschaft rammt und sich rein vererbt. Lässt Versengte Hörner fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "lava_eel",
				"copper_inferno:lava_eel_spawn_egg", null, null, null, 0,
				"Lava Eel - an eel-like guardian that swims the Slag Sea's lava and regenerates while submerged in it. Drops Lava Eel Fillets.",
				"Lava-Aal - ein aalartiger Wächter, der durch die Lava des Schlackenmeers schwimmt und sich darin regeneriert. Lässt Lava-Aal-Filets fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "ember_owl",
				"copper_inferno:ember_owl_spawn_egg", null, null, null, 0,
				"Ember Owl - an owl-faced parrot whose banked-coal plumage glows at night and fades by day. Drops feathers.",
				"Gluteule - ein eulengesichtiger Papagei, dessen kohlglühendes Gefieder nachts leuchtet und tagsüber verblasst. Lässt Federn fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "cinder_toad",
				"copper_inferno:cinder_toad_spawn_egg", null, null, null, 0,
				"Cinder Toad - a squat toad crusted in cinders; stray sparks flicker off its back. Drops slime balls.",
				"Zunderkröte - eine gedrungene, zunderverkrustete Kröte; von ihrem Rücken stieben Funken. Lässt Schleimbälle fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "flare_wisp",
				"copper_inferno:flare_wisp_spawn_egg", null, null, null, 0,
				"Flare Wisp - a free-roaming wisp of living flame that burns whoever strikes it. Drops Flare Essence.",
				"Flammenirrlicht - ein frei umherziehender Fetzen lebendigen Feuers, der jeden verbrennt, der es schlägt. Lässt Flackeressenz fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "smolder_tortoise",
				"copper_inferno:smolder_tortoise_spawn_egg", null, null, null, 0,
				"Smolder Tortoise - a tortoise with a hearth-warm shell that no blow can shove off its spot. Drops Smolder Scutes.",
				"Schwelschildkröte - eine Schildkröte mit herdwarmem Panzer, die kein Schlag von ihrem Platz stößt. Lässt Schwelhornschilde fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "brimstone_bull",
				"copper_inferno:brimstone_bull_spawn_egg", null, null, null, 0,
				"Brimstone Bull - a sulfur-crusted hoglin that never zombifies, no matter the dimension. Drops Brimstone Hide.",
				"Schwefelbulle - ein schwefelverkrusteter Hoglin, der niemals verzombiet, egal in welcher Dimension. Lässt Schwefelhaut fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "ash_wanderer",
				"copper_inferno:ash_wanderer_spawn_egg", null, null, null, 0,
				"Ash Wanderer - a desiccated husk that never burns in daylight, under any sky. Drops rotten flesh.",
				"Aschenwanderer - ein ausgedörrter Wüstenzombie, der unter keinem Himmel im Tageslicht brennt. Lässt verrottetes Fleisch fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "pyroclast_golem",
				"copper_inferno:pyroclast_golem_spawn_egg", null, null, null, 0,
				"Pyroclast Golem - a wild golem of pyroclastic rock whose furnace-hot fists set victims ablaze. Drops Pyroclast Cores.",
				"Pyroklast-Golem - ein wilder Golem aus pyroklastischem Gestein, dessen ofenheiße Fäuste die Opfer entzünden. Lässt Pyroklast-Kerne fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "ember_serpent",
				"copper_inferno:ember_serpent_spawn_egg", null, null, null, 0,
				"Ember Serpent - a serpentine cave spider whose bite poisons AND ignites. The Inferno's nastiest small predator. Drops spider eyes.",
				"Glutnatter - eine schlangengleiche Höhlenspinne, deren Biss vergiftet UND entzündet. Der fieseste kleine Jäger des Infernos. Lässt Spinnenaugen fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "soot_sheep",
				"copper_inferno:soot_sheep_spawn_egg", null, null, null, 0,
				"Soot Sheep - a sheep whose fleece is stained soot-black from birth; shearing yields black wool. Drops black wool.",
				"Rußschaf - ein Schaf, dessen Vlies von Geburt an rußschwarz gefärbt ist; das Scheren liefert schwarze Wolle. Lässt schwarze Wolle fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "glow_strider",
				"copper_inferno:glow_strider_spawn_egg", null, null, null, 0,
				"Glow Strider - a strider with a phosphorescent hide, permanently aglow and visible far across the Slag Sea. Saddleable. Drops glowstone dust.",
				"Glimmschreiter - ein Schreiter mit phosphoreszierender Haut, dauerhaft leuchtend und weit über das Schlackenmeer sichtbar. Sattelbar. Lässt Glowstonestaub fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "kiln_spider",
				"copper_inferno:kiln_spider_spawn_egg", null, null, null, 0,
				"Kiln Spider - a brick-red spider with kiln-hardened chitin; fire and lava cannot touch it. Drops string.",
				"Brennofenspinne - eine ziegelrote Spinne mit ofengehärtetem Chitin; Feuer und Lava können ihr nichts anhaben. Lässt Fäden fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "char_phantom",
				"copper_inferno:char_phantom_spawn_egg", null, null, null, 0,
				"Char Phantom - a phantom already burned black; daylight cannot ignite it, so it circles under any sky. Drops phantom membranes.",
				"Kohlenphantom - ein bereits schwarzgebranntes Phantom; Tageslicht kann es nicht entzünden, es kreist unter jedem Himmel. Lässt Phantomhäute fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "molten_mite",
				"copper_inferno:molten_mite_spawn_egg", null, null, null, 0,
				"Molten Mite - a mite of half-molten rock that splashes liquid stone on whoever squashes it. Drops blaze powder.",
				"Schmelzmilbe - eine Milbe aus halbgeschmolzenem Gestein, die jeden mit flüssigem Stein bespritzt, der sie zerquetscht. Lässt Lohenstaub fallen."));
		HandbookEntries.add(new HandbookEntry("mobs", "inferno_ghastling",
				"copper_inferno:inferno_ghastling_spawn_egg", null, null, null, 0,
				"Inferno Ghastling - a cat-sized ghast runt; frail, but its little fireballs still sting. Drops ghast tears.",
				"Inferno-Ghastling - ein katzengroßer Ghast-Wicht; zerbrechlich, doch seine kleinen Feuerbälle brennen trotzdem. Lässt Ghast-Tränen fallen."));
	}
}
