package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.WitherSkeletonEntity;
import net.minecraft.world.World;

/**
 * Ashbone Knight - an armored skeletal knight of ash-bleached bone, native to the Inferno dimension. Behavior is pure
 * vanilla WitherSkeletonEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Ashbone Chip ({@code loot_table/entities/ashbone_knight.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class AshboneKnightEntity extends WitherSkeletonEntity {
	public AshboneKnightEntity(EntityType<? extends WitherSkeletonEntity> type, World world) {
		super(type, world);
	}
}
