package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.ZombifiedPiglinEntity;
import net.minecraft.world.World;

/**
 * Ashen Zombie Piglin - a zombified piglin bleached grey by falling ash, native to the Inferno dimension. Behavior is pure
 * vanilla ZombifiedPiglinEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Charred Flesh ({@code loot_table/entities/ashen_zombie_piglin.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class AshenZombiePiglinEntity extends ZombifiedPiglinEntity {
	public AshenZombiePiglinEntity(EntityType<? extends ZombifiedPiglinEntity> type, World world) {
		super(type, world);
	}
}
