package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.EndermanEntity;
import net.minecraft.world.World;

/**
 * Ashgaze Warper - a warper whose ash-grey gaze bends space, native to the Inferno dimension. Behavior is pure
 * vanilla EndermanEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Warper Iris ({@code loot_table/entities/ashgaze_warper.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class AshgazeWarperEntity extends EndermanEntity {
	public AshgazeWarperEntity(EntityType<? extends EndermanEntity> type, World world) {
		super(type, world);
	}
}
