package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnReason;
import net.minecraft.entity.mob.HoglinEntity;
import net.minecraft.entity.passive.PassiveEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.world.World;

/**
 * Cinderhide Boar - a fast, cinder-pelted boar, native to the Inferno dimension. Behavior is pure
 * vanilla HoglinEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Cinderhide Scrap ({@code loot_table/entities/cinderhide_boar.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class CinderhideBoarEntity extends HoglinEntity {
	public CinderhideBoarEntity(EntityType<? extends HoglinEntity> type, World world) {
		super(type, world);
	}

	/**
	 * Vanilla {@code HoglinEntity.canConvert()} (public, javap-verified) gates the zoglin
	 * conversion on {@code !world.getDimension().piglinSafe()}; slag-fiend hoglins never
	 * convert, in the Inferno or anywhere else.
	 */
	@Override
	public boolean canConvert() {
		return false;
	}

	/**
	 * Vanilla {@code HoglinEntity.createChild} hard-codes {@code EntityType.HOGLIN}
	 * (bytecode-verified: create -> setPersistent -> return), so bred Cinderhide Boars
	 * would produce vanilla hoglins. Covariant override, same create/setPersistent flow.
	 */
	@Override
	public CinderhideBoarEntity createChild(ServerWorld world, PassiveEntity entity) {
		CinderhideBoarEntity child = SlagFiendsFeature.CINDERHIDE_BOAR.create(world, SpawnReason.BREEDING);
		if (child != null) {
			child.setPersistent();
		}
		return child;
	}
}
