package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.EndermanEntity;
import net.minecraft.world.World;

/**
 * Cinder Shade - a flickering shade of cinder and smoke, native to the Inferno dimension. Behavior is pure
 * vanilla EndermanEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Shade Essence ({@code loot_table/entities/cinder_shade.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class CinderShadeEntity extends EndermanEntity {
	public CinderShadeEntity(EntityType<? extends EndermanEntity> type, World world) {
		super(type, world);
	}
}
