package net.sonic0810.copperinferno.feature.slagfiends;

import java.util.function.Predicate;
import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.block.Blocks;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.SpawnLocationTypes;
import net.minecraft.entity.SpawnRestriction;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.mob.AbstractSkeletonEntity;
import net.minecraft.entity.mob.EndermanEntity;
import net.minecraft.entity.mob.HoglinEntity;
import net.minecraft.entity.mob.HostileEntity;
import net.minecraft.entity.mob.PiglinEntity;
import net.minecraft.entity.mob.ZombifiedPiglinEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.world.Difficulty;
import net.minecraft.world.Heightmap;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * Slag Fiends: 25 hostile mobs native to the Inferno dimension, five thin subclasses per
 * vanilla base (wither skeleton, hoglin, piglin, enderman, zombified piglin), each reusing
 * the vanilla renderer (see {@code SlagFiendsFeatureClient}). EntityType builder chains,
 * default attribute suppliers and spawn predicates are copied from the vanilla
 * registrations (javap/bytecode-verified; see the comments below). Spawn eggs, mob-drop
 * items, natural spawns in the three Inferno biomes, drop recipes and handbook pages are
 * all registered here.
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public final class SlagFiendsFeature {
	private SlagFiendsFeature() {
	}

	public static EntityType<SlagWraithEntity> SLAG_WRAITH;
	public static EntityType<CinderReaperEntity> CINDER_REAPER;
	public static EntityType<AshboneKnightEntity> ASHBONE_KNIGHT;
	public static EntityType<EmberRevenantEntity> EMBER_REVENANT;
	public static EntityType<SootboneHarrowerEntity> SOOTBONE_HARROWER;
	public static EntityType<MoltenHoglinEntity> MOLTEN_HOGLIN;
	public static EntityType<CinderhideBoarEntity> CINDERHIDE_BOAR;
	public static EntityType<SlagtuskBruteEntity> SLAGTUSK_BRUTE;
	public static EntityType<EmberbackHogEntity> EMBERBACK_HOG;
	public static EntityType<AshsnoutGorerEntity> ASHSNOUT_GORER;
	public static EntityType<CinderPiglinEntity> CINDER_PIGLIN;
	public static EntityType<SlagforgedPiglinEntity> SLAGFORGED_PIGLIN;
	public static EntityType<EmbercladPiglinEntity> EMBERCLAD_PIGLIN;
	public static EntityType<AshenPiglinMarauderEntity> ASHEN_PIGLIN_MARAUDER;
	public static EntityType<SootPiglinPlundererEntity> SOOT_PIGLIN_PLUNDERER;
	public static EntityType<EmberStalkerEntity> EMBER_STALKER;
	public static EntityType<CinderShadeEntity> CINDER_SHADE;
	public static EntityType<SlagveilLurkerEntity> SLAGVEIL_LURKER;
	public static EntityType<AshgazeWarperEntity> ASHGAZE_WARPER;
	public static EntityType<SootflareHauntEntity> SOOTFLARE_HAUNT;
	public static EntityType<AshenZombiePiglinEntity> ASHEN_ZOMBIE_PIGLIN;
	public static EntityType<SlagrotPiglinEntity> SLAGROT_PIGLIN;
	public static EntityType<EmberfleshPiglinEntity> EMBERFLESH_PIGLIN;
	public static EntityType<CinderboundPiglinEntity> CINDERBOUND_PIGLIN;
	public static EntityType<SootrotMarauderEntity> SOOTROT_MARAUDER;

	public static Item SLAG_WRAITH_SPAWN_EGG;
	public static Item CINDER_REAPER_SPAWN_EGG;
	public static Item ASHBONE_KNIGHT_SPAWN_EGG;
	public static Item EMBER_REVENANT_SPAWN_EGG;
	public static Item SOOTBONE_HARROWER_SPAWN_EGG;
	public static Item MOLTEN_HOGLIN_SPAWN_EGG;
	public static Item CINDERHIDE_BOAR_SPAWN_EGG;
	public static Item SLAGTUSK_BRUTE_SPAWN_EGG;
	public static Item EMBERBACK_HOG_SPAWN_EGG;
	public static Item ASHSNOUT_GORER_SPAWN_EGG;
	public static Item CINDER_PIGLIN_SPAWN_EGG;
	public static Item SLAGFORGED_PIGLIN_SPAWN_EGG;
	public static Item EMBERCLAD_PIGLIN_SPAWN_EGG;
	public static Item ASHEN_PIGLIN_MARAUDER_SPAWN_EGG;
	public static Item SOOT_PIGLIN_PLUNDERER_SPAWN_EGG;
	public static Item EMBER_STALKER_SPAWN_EGG;
	public static Item CINDER_SHADE_SPAWN_EGG;
	public static Item SLAGVEIL_LURKER_SPAWN_EGG;
	public static Item ASHGAZE_WARPER_SPAWN_EGG;
	public static Item SOOTFLARE_HAUNT_SPAWN_EGG;
	public static Item ASHEN_ZOMBIE_PIGLIN_SPAWN_EGG;
	public static Item SLAGROT_PIGLIN_SPAWN_EGG;
	public static Item EMBERFLESH_PIGLIN_SPAWN_EGG;
	public static Item CINDERBOUND_PIGLIN_SPAWN_EGG;
	public static Item SOOTROT_MARAUDER_SPAWN_EGG;

	public static Item SLAGBONE_SHARD;
	public static Item REAPER_CINDER;
	public static Item ASHBONE_CHIP;
	public static Item REVENANT_EMBER;
	public static Item HARROWER_SOOT;
	public static Item MOLTEN_HOGLIN_TUSK;
	public static Item CINDERHIDE_SCRAP;
	public static Item SLAGTUSK_FRAGMENT;
	public static Item EMBERBACK_BRISTLE;
	public static Item ASHSNOUT_HIDE;
	public static Item CINDER_TOOTH;
	public static Item SLAGFORGED_PLATE;
	public static Item EMBERCLAD_SCRAP;
	public static Item MARAUDER_TUSK;
	public static Item PLUNDERER_SOOT;
	public static Item STALKER_PEARL;
	public static Item SHADE_ESSENCE;
	public static Item LURKER_VEIL;
	public static Item WARPER_IRIS;
	public static Item HAUNT_FLARE;
	public static Item CHARRED_FLESH;
	public static Item SLAGROT_CHUNK;
	public static Item EMBERFLESH_STRIP;
	public static Item CINDERBOUND_SHACKLE;
	public static Item SOOTROT_HIDE;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		registerSpawning();
		SlagFiendsHandbook.register();
	}

	private static void registerEntityTypes() {
		// Builder chains copied 1:1 from the vanilla EntityType registrations
		// (1.21.9 bytecode):
		// wither_skeleton = makeFireImmune().allowSpawningInside(Blocks.WITHER_ROSE).dimensions(0.7f, 2.4f).eyeHeight(2.1f).vehicleAttachment(-0.875f).maxTrackingRange(8).notAllowedInPeaceful()
		SLAG_WRAITH = ModEntities.register("slag_wraith",
				EntityType.Builder.create(SlagWraithEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.allowSpawningInside(Blocks.WITHER_ROSE)
						.dimensions(0.7f, 2.4f)
						.eyeHeight(2.1f)
						.vehicleAttachment(-0.875f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		CINDER_REAPER = ModEntities.register("cinder_reaper",
				EntityType.Builder.create(CinderReaperEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.allowSpawningInside(Blocks.WITHER_ROSE)
						.dimensions(0.7f, 2.4f)
						.eyeHeight(2.1f)
						.vehicleAttachment(-0.875f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		ASHBONE_KNIGHT = ModEntities.register("ashbone_knight",
				EntityType.Builder.create(AshboneKnightEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.allowSpawningInside(Blocks.WITHER_ROSE)
						.dimensions(0.7f, 2.4f)
						.eyeHeight(2.1f)
						.vehicleAttachment(-0.875f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		EMBER_REVENANT = ModEntities.register("ember_revenant",
				EntityType.Builder.create(EmberRevenantEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.allowSpawningInside(Blocks.WITHER_ROSE)
						.dimensions(0.7f, 2.4f)
						.eyeHeight(2.1f)
						.vehicleAttachment(-0.875f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SOOTBONE_HARROWER = ModEntities.register("sootbone_harrower",
				EntityType.Builder.create(SootboneHarrowerEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.allowSpawningInside(Blocks.WITHER_ROSE)
						.dimensions(0.7f, 2.4f)
						.eyeHeight(2.1f)
						.vehicleAttachment(-0.875f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		// hoglin = dimensions(1.3964844f, 1.4f).passengerAttachments(1.49375f).maxTrackingRange(8)
		MOLTEN_HOGLIN = ModEntities.register("molten_hoglin",
				EntityType.Builder.create(MoltenHoglinEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.3964844f, 1.4f)
						.passengerAttachments(1.49375f)
						.maxTrackingRange(8));

		CINDERHIDE_BOAR = ModEntities.register("cinderhide_boar",
				EntityType.Builder.create(CinderhideBoarEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.3964844f, 1.4f)
						.passengerAttachments(1.49375f)
						.maxTrackingRange(8));

		SLAGTUSK_BRUTE = ModEntities.register("slagtusk_brute",
				EntityType.Builder.create(SlagtuskBruteEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.3964844f, 1.4f)
						.passengerAttachments(1.49375f)
						.maxTrackingRange(8));

		EMBERBACK_HOG = ModEntities.register("emberback_hog",
				EntityType.Builder.create(EmberbackHogEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.3964844f, 1.4f)
						.passengerAttachments(1.49375f)
						.maxTrackingRange(8));

		ASHSNOUT_GORER = ModEntities.register("ashsnout_gorer",
				EntityType.Builder.create(AshsnoutGorerEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.3964844f, 1.4f)
						.passengerAttachments(1.49375f)
						.maxTrackingRange(8));

		// piglin = dimensions(0.6f, 1.95f).eyeHeight(1.79f).passengerAttachments(2.0125f).vehicleAttachment(-0.7f).maxTrackingRange(8)
		CINDER_PIGLIN = ModEntities.register("cinder_piglin",
				EntityType.Builder.create(CinderPiglinEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8));

		SLAGFORGED_PIGLIN = ModEntities.register("slagforged_piglin",
				EntityType.Builder.create(SlagforgedPiglinEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8));

		EMBERCLAD_PIGLIN = ModEntities.register("emberclad_piglin",
				EntityType.Builder.create(EmbercladPiglinEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8));

		ASHEN_PIGLIN_MARAUDER = ModEntities.register("ashen_piglin_marauder",
				EntityType.Builder.create(AshenPiglinMarauderEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8));

		SOOT_PIGLIN_PLUNDERER = ModEntities.register("soot_piglin_plunderer",
				EntityType.Builder.create(SootPiglinPlundererEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8));

		// enderman = dimensions(0.6f, 2.9f).eyeHeight(2.55f).passengerAttachments(2.80625f).maxTrackingRange(8).notAllowedInPeaceful()
		EMBER_STALKER = ModEntities.register("ember_stalker",
				EntityType.Builder.create(EmberStalkerEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 2.9f)
						.eyeHeight(2.55f)
						.passengerAttachments(2.80625f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		CINDER_SHADE = ModEntities.register("cinder_shade",
				EntityType.Builder.create(CinderShadeEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 2.9f)
						.eyeHeight(2.55f)
						.passengerAttachments(2.80625f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SLAGVEIL_LURKER = ModEntities.register("slagveil_lurker",
				EntityType.Builder.create(SlagveilLurkerEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 2.9f)
						.eyeHeight(2.55f)
						.passengerAttachments(2.80625f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		ASHGAZE_WARPER = ModEntities.register("ashgaze_warper",
				EntityType.Builder.create(AshgazeWarperEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 2.9f)
						.eyeHeight(2.55f)
						.passengerAttachments(2.80625f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SOOTFLARE_HAUNT = ModEntities.register("sootflare_haunt",
				EntityType.Builder.create(SootflareHauntEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 2.9f)
						.eyeHeight(2.55f)
						.passengerAttachments(2.80625f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		// zombified_piglin = makeFireImmune().dimensions(0.6f, 1.95f).eyeHeight(1.79f).passengerAttachments(2.0f).vehicleAttachment(-0.7f).maxTrackingRange(8).notAllowedInPeaceful()
		ASHEN_ZOMBIE_PIGLIN = ModEntities.register("ashen_zombie_piglin",
				EntityType.Builder.create(AshenZombiePiglinEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SLAGROT_PIGLIN = ModEntities.register("slagrot_piglin",
				EntityType.Builder.create(SlagrotPiglinEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		EMBERFLESH_PIGLIN = ModEntities.register("emberflesh_piglin",
				EntityType.Builder.create(EmberfleshPiglinEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		CINDERBOUND_PIGLIN = ModEntities.register("cinderbound_piglin",
				EntityType.Builder.create(CinderboundPiglinEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SOOTROT_MARAUDER = ModEntities.register("sootrot_marauder",
				EntityType.Builder.create(SootrotMarauderEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.passengerAttachments(2.0f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
	}

	private static void registerAttributes() {
		// Base suppliers mirror DefaultAttributeRegistry (bytecode-verified);
		// DefaultAttributeContainer.Builder.add(...) overrides any base value.
		FabricDefaultAttributeRegistry.register(SLAG_WRAITH, AbstractSkeletonEntity.createAbstractSkeletonAttributes()
				.add(EntityAttributes.MAX_HEALTH, 24.0)
				.add(EntityAttributes.SCALE, 1.1));
		FabricDefaultAttributeRegistry.register(CINDER_REAPER, AbstractSkeletonEntity.createAbstractSkeletonAttributes()
				.add(EntityAttributes.MAX_HEALTH, 22.0)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.3));
		FabricDefaultAttributeRegistry.register(ASHBONE_KNIGHT, AbstractSkeletonEntity.createAbstractSkeletonAttributes()
				.add(EntityAttributes.MAX_HEALTH, 30.0)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 0.5));
		FabricDefaultAttributeRegistry.register(EMBER_REVENANT, AbstractSkeletonEntity.createAbstractSkeletonAttributes()
				.add(EntityAttributes.MAX_HEALTH, 26.0)
				.add(EntityAttributes.SCALE, 1.05));
		FabricDefaultAttributeRegistry.register(SOOTBONE_HARROWER, AbstractSkeletonEntity.createAbstractSkeletonAttributes()
				.add(EntityAttributes.MOVEMENT_SPEED, 0.28)
				.add(EntityAttributes.SCALE, 0.95));
		FabricDefaultAttributeRegistry.register(MOLTEN_HOGLIN, HoglinEntity.createHoglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 48.0)
				.add(EntityAttributes.SCALE, 1.1));
		FabricDefaultAttributeRegistry.register(CINDERHIDE_BOAR, HoglinEntity.createHoglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 36.0)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.34));
		FabricDefaultAttributeRegistry.register(SLAGTUSK_BRUTE, HoglinEntity.createHoglinAttributes()
				.add(EntityAttributes.ATTACK_DAMAGE, 8.0)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 0.75));
		FabricDefaultAttributeRegistry.register(EMBERBACK_HOG, HoglinEntity.createHoglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 44.0)
				.add(EntityAttributes.SCALE, 1.05));
		FabricDefaultAttributeRegistry.register(ASHSNOUT_GORER, HoglinEntity.createHoglinAttributes()
				.add(EntityAttributes.ATTACK_DAMAGE, 7.0)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.32));
		FabricDefaultAttributeRegistry.register(CINDER_PIGLIN, PiglinEntity.createPiglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 20.0));
		FabricDefaultAttributeRegistry.register(SLAGFORGED_PIGLIN, PiglinEntity.createPiglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 24.0)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 0.3));
		FabricDefaultAttributeRegistry.register(EMBERCLAD_PIGLIN, PiglinEntity.createPiglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 22.0)
				.add(EntityAttributes.SCALE, 1.05));
		FabricDefaultAttributeRegistry.register(ASHEN_PIGLIN_MARAUDER, PiglinEntity.createPiglinAttributes()
				.add(EntityAttributes.ATTACK_DAMAGE, 6.0));
		FabricDefaultAttributeRegistry.register(SOOT_PIGLIN_PLUNDERER, PiglinEntity.createPiglinAttributes()
				.add(EntityAttributes.MOVEMENT_SPEED, 0.38));
		FabricDefaultAttributeRegistry.register(EMBER_STALKER, EndermanEntity.createEndermanAttributes()
				.add(EntityAttributes.MAX_HEALTH, 44.0)
				.add(EntityAttributes.SCALE, 1.05));
		FabricDefaultAttributeRegistry.register(CINDER_SHADE, EndermanEntity.createEndermanAttributes()
				.add(EntityAttributes.MOVEMENT_SPEED, 0.33));
		FabricDefaultAttributeRegistry.register(SLAGVEIL_LURKER, EndermanEntity.createEndermanAttributes()
				.add(EntityAttributes.MAX_HEALTH, 42.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 8.0));
		FabricDefaultAttributeRegistry.register(ASHGAZE_WARPER, EndermanEntity.createEndermanAttributes()
				.add(EntityAttributes.SCALE, 0.95)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.32));
		FabricDefaultAttributeRegistry.register(SOOTFLARE_HAUNT, EndermanEntity.createEndermanAttributes()
				.add(EntityAttributes.MAX_HEALTH, 38.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 7.5));
		FabricDefaultAttributeRegistry.register(ASHEN_ZOMBIE_PIGLIN, ZombifiedPiglinEntity.createZombifiedPiglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 22.0));
		FabricDefaultAttributeRegistry.register(SLAGROT_PIGLIN, ZombifiedPiglinEntity.createZombifiedPiglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 24.0)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.25));
		FabricDefaultAttributeRegistry.register(EMBERFLESH_PIGLIN, ZombifiedPiglinEntity.createZombifiedPiglinAttributes()
				.add(EntityAttributes.ATTACK_DAMAGE, 6.0));
		FabricDefaultAttributeRegistry.register(CINDERBOUND_PIGLIN, ZombifiedPiglinEntity.createZombifiedPiglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 26.0)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 0.4));
		FabricDefaultAttributeRegistry.register(SOOTROT_MARAUDER, ZombifiedPiglinEntity.createZombifiedPiglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 24.0)
				.add(EntityAttributes.SCALE, 1.1));
	}

	private static void registerItems() {
		SLAG_WRAITH_SPAWN_EGG = ModItems.register("slag_wraith_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_WRAITH));
		CINDER_REAPER_SPAWN_EGG = ModItems.register("cinder_reaper_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_REAPER));
		ASHBONE_KNIGHT_SPAWN_EGG = ModItems.register("ashbone_knight_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASHBONE_KNIGHT));
		EMBER_REVENANT_SPAWN_EGG = ModItems.register("ember_revenant_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_REVENANT));
		SOOTBONE_HARROWER_SPAWN_EGG = ModItems.register("sootbone_harrower_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOTBONE_HARROWER));
		MOLTEN_HOGLIN_SPAWN_EGG = ModItems.register("molten_hoglin_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MOLTEN_HOGLIN));
		CINDERHIDE_BOAR_SPAWN_EGG = ModItems.register("cinderhide_boar_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDERHIDE_BOAR));
		SLAGTUSK_BRUTE_SPAWN_EGG = ModItems.register("slagtusk_brute_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAGTUSK_BRUTE));
		EMBERBACK_HOG_SPAWN_EGG = ModItems.register("emberback_hog_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBERBACK_HOG));
		ASHSNOUT_GORER_SPAWN_EGG = ModItems.register("ashsnout_gorer_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASHSNOUT_GORER));
		CINDER_PIGLIN_SPAWN_EGG = ModItems.register("cinder_piglin_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_PIGLIN));
		SLAGFORGED_PIGLIN_SPAWN_EGG = ModItems.register("slagforged_piglin_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAGFORGED_PIGLIN));
		EMBERCLAD_PIGLIN_SPAWN_EGG = ModItems.register("emberclad_piglin_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBERCLAD_PIGLIN));
		ASHEN_PIGLIN_MARAUDER_SPAWN_EGG = ModItems.register("ashen_piglin_marauder_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASHEN_PIGLIN_MARAUDER));
		SOOT_PIGLIN_PLUNDERER_SPAWN_EGG = ModItems.register("soot_piglin_plunderer_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_PIGLIN_PLUNDERER));
		EMBER_STALKER_SPAWN_EGG = ModItems.register("ember_stalker_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_STALKER));
		CINDER_SHADE_SPAWN_EGG = ModItems.register("cinder_shade_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_SHADE));
		SLAGVEIL_LURKER_SPAWN_EGG = ModItems.register("slagveil_lurker_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAGVEIL_LURKER));
		ASHGAZE_WARPER_SPAWN_EGG = ModItems.register("ashgaze_warper_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASHGAZE_WARPER));
		SOOTFLARE_HAUNT_SPAWN_EGG = ModItems.register("sootflare_haunt_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOTFLARE_HAUNT));
		ASHEN_ZOMBIE_PIGLIN_SPAWN_EGG = ModItems.register("ashen_zombie_piglin_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASHEN_ZOMBIE_PIGLIN));
		SLAGROT_PIGLIN_SPAWN_EGG = ModItems.register("slagrot_piglin_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAGROT_PIGLIN));
		EMBERFLESH_PIGLIN_SPAWN_EGG = ModItems.register("emberflesh_piglin_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBERFLESH_PIGLIN));
		CINDERBOUND_PIGLIN_SPAWN_EGG = ModItems.register("cinderbound_piglin_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDERBOUND_PIGLIN));
		SOOTROT_MARAUDER_SPAWN_EGG = ModItems.register("sootrot_marauder_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOTROT_MARAUDER));

		SLAGBONE_SHARD = ModItems.register("slagbone_shard", Item::new, new Item.Settings());
		REAPER_CINDER = ModItems.register("reaper_cinder", Item::new, new Item.Settings());
		ASHBONE_CHIP = ModItems.register("ashbone_chip", Item::new, new Item.Settings());
		REVENANT_EMBER = ModItems.register("revenant_ember", Item::new, new Item.Settings());
		HARROWER_SOOT = ModItems.register("harrower_soot", Item::new, new Item.Settings());
		MOLTEN_HOGLIN_TUSK = ModItems.register("molten_hoglin_tusk", Item::new, new Item.Settings());
		CINDERHIDE_SCRAP = ModItems.register("cinderhide_scrap", Item::new, new Item.Settings());
		SLAGTUSK_FRAGMENT = ModItems.register("slagtusk_fragment", Item::new, new Item.Settings());
		EMBERBACK_BRISTLE = ModItems.register("emberback_bristle", Item::new, new Item.Settings());
		ASHSNOUT_HIDE = ModItems.register("ashsnout_hide", Item::new, new Item.Settings());
		CINDER_TOOTH = ModItems.register("cinder_tooth", Item::new, new Item.Settings());
		SLAGFORGED_PLATE = ModItems.register("slagforged_plate", Item::new, new Item.Settings());
		EMBERCLAD_SCRAP = ModItems.register("emberclad_scrap", Item::new, new Item.Settings());
		MARAUDER_TUSK = ModItems.register("marauder_tusk", Item::new, new Item.Settings());
		PLUNDERER_SOOT = ModItems.register("plunderer_soot", Item::new, new Item.Settings());
		STALKER_PEARL = ModItems.register("stalker_pearl", Item::new, new Item.Settings());
		SHADE_ESSENCE = ModItems.register("shade_essence", Item::new, new Item.Settings());
		LURKER_VEIL = ModItems.register("lurker_veil", Item::new, new Item.Settings());
		WARPER_IRIS = ModItems.register("warper_iris", Item::new, new Item.Settings());
		HAUNT_FLARE = ModItems.register("haunt_flare", Item::new, new Item.Settings());
		CHARRED_FLESH = ModItems.register("charred_flesh", Item::new, new Item.Settings());
		SLAGROT_CHUNK = ModItems.register("slagrot_chunk", Item::new, new Item.Settings());
		EMBERFLESH_STRIP = ModItems.register("emberflesh_strip", Item::new, new Item.Settings());
		CINDERBOUND_SHACKLE = ModItems.register("cinderbound_shackle", Item::new, new Item.Settings());
		SOOTROT_HIDE = ModItems.register("sootrot_hide", Item::new, new Item.Settings());

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			// Spawn eggs together, then the mob drops.
			entries.add(SLAG_WRAITH_SPAWN_EGG);
			entries.add(CINDER_REAPER_SPAWN_EGG);
			entries.add(ASHBONE_KNIGHT_SPAWN_EGG);
			entries.add(EMBER_REVENANT_SPAWN_EGG);
			entries.add(SOOTBONE_HARROWER_SPAWN_EGG);
			entries.add(MOLTEN_HOGLIN_SPAWN_EGG);
			entries.add(CINDERHIDE_BOAR_SPAWN_EGG);
			entries.add(SLAGTUSK_BRUTE_SPAWN_EGG);
			entries.add(EMBERBACK_HOG_SPAWN_EGG);
			entries.add(ASHSNOUT_GORER_SPAWN_EGG);
			entries.add(CINDER_PIGLIN_SPAWN_EGG);
			entries.add(SLAGFORGED_PIGLIN_SPAWN_EGG);
			entries.add(EMBERCLAD_PIGLIN_SPAWN_EGG);
			entries.add(ASHEN_PIGLIN_MARAUDER_SPAWN_EGG);
			entries.add(SOOT_PIGLIN_PLUNDERER_SPAWN_EGG);
			entries.add(EMBER_STALKER_SPAWN_EGG);
			entries.add(CINDER_SHADE_SPAWN_EGG);
			entries.add(SLAGVEIL_LURKER_SPAWN_EGG);
			entries.add(ASHGAZE_WARPER_SPAWN_EGG);
			entries.add(SOOTFLARE_HAUNT_SPAWN_EGG);
			entries.add(ASHEN_ZOMBIE_PIGLIN_SPAWN_EGG);
			entries.add(SLAGROT_PIGLIN_SPAWN_EGG);
			entries.add(EMBERFLESH_PIGLIN_SPAWN_EGG);
			entries.add(CINDERBOUND_PIGLIN_SPAWN_EGG);
			entries.add(SOOTROT_MARAUDER_SPAWN_EGG);
			entries.add(SLAGBONE_SHARD);
			entries.add(REAPER_CINDER);
			entries.add(ASHBONE_CHIP);
			entries.add(REVENANT_EMBER);
			entries.add(HARROWER_SOOT);
			entries.add(MOLTEN_HOGLIN_TUSK);
			entries.add(CINDERHIDE_SCRAP);
			entries.add(SLAGTUSK_FRAGMENT);
			entries.add(EMBERBACK_BRISTLE);
			entries.add(ASHSNOUT_HIDE);
			entries.add(CINDER_TOOTH);
			entries.add(SLAGFORGED_PLATE);
			entries.add(EMBERCLAD_SCRAP);
			entries.add(MARAUDER_TUSK);
			entries.add(PLUNDERER_SOOT);
			entries.add(STALKER_PEARL);
			entries.add(SHADE_ESSENCE);
			entries.add(LURKER_VEIL);
			entries.add(WARPER_IRIS);
			entries.add(HAUNT_FLARE);
			entries.add(CHARRED_FLESH);
			entries.add(SLAGROT_CHUNK);
			entries.add(EMBERFLESH_STRIP);
			entries.add(CINDERBOUND_SHACKLE);
			entries.add(SOOTROT_HIDE);
		});
	}

	private static void registerSpawning() {
		// SpawnRestriction.register is access-widened by Fabric's transitive access
		// wideners. Per-base predicates mirror the vanilla SpawnRestriction entries
		// (bytecode): wither skeleton + enderman use HostileEntity::canSpawnInDark
		// (typed to `? extends HostileEntity`, so reusable for subclasses); hoglin/
		// piglin/zombified piglin canSpawn are typed to the vanilla EntityTypes and
		// are reimplemented 1:1 inline (no-nether-wart-below, plus the zombified
		// piglin difficulty gate). All spawn ON_GROUND + MOTION_BLOCKING_NO_LEAVES.
		SpawnRestriction.register(SLAG_WRAITH, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(CINDER_REAPER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(ASHBONE_KNIGHT, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(EMBER_REVENANT, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SOOTBONE_HARROWER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(MOLTEN_HOGLIN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(CINDERHIDE_BOAR, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(SLAGTUSK_BRUTE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(EMBERBACK_HOG, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(ASHSNOUT_GORER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(CINDER_PIGLIN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(SLAGFORGED_PIGLIN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(EMBERCLAD_PIGLIN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(ASHEN_PIGLIN_MARAUDER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(SOOT_PIGLIN_PLUNDERER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(EMBER_STALKER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(CINDER_SHADE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SLAGVEIL_LURKER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(ASHGAZE_WARPER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SOOTFLARE_HAUNT, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(ASHEN_ZOMBIE_PIGLIN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL
						&& !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(SLAGROT_PIGLIN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL
						&& !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(EMBERFLESH_PIGLIN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL
						&& !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(CINDERBOUND_PIGLIN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL
						&& !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));
		SpawnRestriction.register(SOOTROT_MARAUDER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL
						&& !world.getBlockState(pos.down()).isOf(Blocks.NETHER_WART_BLOCK));

		// Natural spawns in the three Inferno biomes (biome JSONs are owned by the
		// infernodim feature; includeByKey simply matches nothing until loaded).
		Predicate<BiomeSelectionContext> infernoBiomes = BiomeSelectors.includeByKey(
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("cinder_wastes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("ember_grove")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("slag_sea")));
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAG_WRAITH, 10, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDER_REAPER, 9, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASHBONE_KNIGHT, 7, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBER_REVENANT, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SOOTBONE_HARROWER, 9, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, MOLTEN_HOGLIN, 8, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDERHIDE_BOAR, 9, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAGTUSK_BRUTE, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBERBACK_HOG, 8, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASHSNOUT_GORER, 7, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDER_PIGLIN, 10, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAGFORGED_PIGLIN, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBERCLAD_PIGLIN, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASHEN_PIGLIN_MARAUDER, 7, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SOOT_PIGLIN_PLUNDERER, 8, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBER_STALKER, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDER_SHADE, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAGVEIL_LURKER, 5, 1, 1);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASHGAZE_WARPER, 5, 1, 1);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SOOTFLARE_HAUNT, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASHEN_ZOMBIE_PIGLIN, 10, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAGROT_PIGLIN, 9, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBERFLESH_PIGLIN, 9, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDERBOUND_PIGLIN, 7, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SOOTROT_MARAUDER, 8, 1, 2);
	}
}
