package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.ZombifiedPiglinEntity;
import net.minecraft.world.World;

/**
 * Slagrot Piglin - a rotting piglin fused with cooling slag, native to the Inferno dimension. Behavior is pure
 * vanilla ZombifiedPiglinEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Slagrot Chunk ({@code loot_table/entities/slagrot_piglin.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class SlagrotPiglinEntity extends ZombifiedPiglinEntity {
	public SlagrotPiglinEntity(EntityType<? extends ZombifiedPiglinEntity> type, World world) {
		super(type, world);
	}
}
