package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.AbstractPiglinEntity;
import net.minecraft.entity.mob.PiglinEntity;
import net.minecraft.world.World;

/**
 * Soot Piglin Plunderer - a quick soot-smeared plunderer, native to the Inferno dimension. Behavior is pure
 * vanilla PiglinEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Plunderer Soot ({@code loot_table/entities/soot_piglin_plunderer.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class SootPiglinPlundererEntity extends PiglinEntity {
	public SootPiglinPlundererEntity(EntityType<? extends AbstractPiglinEntity> type, World world) {
		super(type, world);
	}

	/**
	 * Vanilla {@code AbstractPiglinEntity.mobTick} counts up {@code timeInOverworld} while
	 * {@code shouldZombify()} (public, javap-verified) is true and converts to a vanilla
	 * zombified piglin after 300 ticks; slag-fiend piglins never zombify.
	 */
	@Override
	public boolean shouldZombify() {
		return false;
	}
}
