package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.EndermanEntity;
import net.minecraft.world.World;

/**
 * Sootflare Haunt - a haunt trailing sparks of burning soot, native to the Inferno dimension. Behavior is pure
 * vanilla EndermanEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Haunt Flare ({@code loot_table/entities/sootflare_haunt.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class SootflareHauntEntity extends EndermanEntity {
	public SootflareHauntEntity(EntityType<? extends EndermanEntity> type, World world) {
		super(type, world);
	}
}
