package net.sonic0810.copperinferno.feature.slagfiends;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.WitherSkeletonEntity;
import net.minecraft.world.World;

/**
 * Sootbone Harrower - a stooped, soot-black harrower of the ashfields, native to the Inferno dimension. Behavior is pure
 * vanilla WitherSkeletonEntity; the stat distinction comes from the tuned default
 * attributes registered in {@link SlagFiendsFeature}. Drops
 * Harrower Soot ({@code loot_table/entities/sootbone_harrower.json}).
 *
 * <p>Generated by {@code devtools/gen/slagfiends_gen.py}; do not edit by hand.
 */
public class SootboneHarrowerEntity extends WitherSkeletonEntity {
	public SootboneHarrowerEntity(EntityType<? extends WitherSkeletonEntity> type, World world) {
		super(type, world);
	}
}
