package net.sonic0810.copperinferno.feature.pyrestone;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlockFamilies.BlockFamily;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Pyrestone block set: 224 building blocks across 14 volcanic stone materials
 * (pyrestone, emberstone, sootstone, charflint, kindlerock, cindershale, coalspar,
 * tindergrit, flarebasalt, magmite, fumarole rock, pyroclast stone, vitrified ash,
 * blazewrought stone). Each material ships three full cube families (base, polished,
 * bricks; each base/slab/stairs/wall) plus tiles, cracked bricks, chiseled bricks and
 * a pillar.
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes,
 * EN+DE lang fragments) are generated by {@code devtools/gen/pyrestone_gen.py}; the tag
 * fragment lives at {@code devtools/tagfrag/pyrestone.json}; handbook pages are
 * registered by {@link PyrestoneHandbook}.
 */
public final class PyrestoneFeature {
	private PyrestoneFeature() {
	}

	// Full cube families (base + slab + stairs + wall).
	public static BlockFamily PYRESTONE;
	public static BlockFamily POLISHED_PYRESTONE;
	public static BlockFamily PYRESTONE_BRICKS;
	public static BlockFamily EMBERSTONE;
	public static BlockFamily POLISHED_EMBERSTONE;
	public static BlockFamily EMBERSTONE_BRICKS;
	public static BlockFamily SOOTSTONE;
	public static BlockFamily POLISHED_SOOTSTONE;
	public static BlockFamily SOOTSTONE_BRICKS;
	public static BlockFamily CHARFLINT;
	public static BlockFamily POLISHED_CHARFLINT;
	public static BlockFamily CHARFLINT_BRICKS;
	public static BlockFamily KINDLEROCK;
	public static BlockFamily POLISHED_KINDLEROCK;
	public static BlockFamily KINDLEROCK_BRICKS;
	public static BlockFamily CINDERSHALE;
	public static BlockFamily POLISHED_CINDERSHALE;
	public static BlockFamily CINDERSHALE_BRICKS;
	public static BlockFamily COALSPAR;
	public static BlockFamily POLISHED_COALSPAR;
	public static BlockFamily COALSPAR_BRICKS;
	public static BlockFamily TINDERGRIT;
	public static BlockFamily POLISHED_TINDERGRIT;
	public static BlockFamily TINDERGRIT_BRICKS;
	public static BlockFamily FLAREBASALT;
	public static BlockFamily POLISHED_FLAREBASALT;
	public static BlockFamily FLAREBASALT_BRICKS;
	public static BlockFamily MAGMITE;
	public static BlockFamily POLISHED_MAGMITE;
	public static BlockFamily MAGMITE_BRICKS;
	public static BlockFamily FUMAROLE_ROCK;
	public static BlockFamily POLISHED_FUMAROLE_ROCK;
	public static BlockFamily FUMAROLE_ROCK_BRICKS;
	public static BlockFamily PYROCLAST_STONE;
	public static BlockFamily POLISHED_PYROCLAST_STONE;
	public static BlockFamily PYROCLAST_STONE_BRICKS;
	public static BlockFamily VITRIFIED_ASH;
	public static BlockFamily POLISHED_VITRIFIED_ASH;
	public static BlockFamily VITRIFIED_ASH_BRICKS;
	public static BlockFamily BLAZEWROUGHT_STONE;
	public static BlockFamily POLISHED_BLAZEWROUGHT_STONE;
	public static BlockFamily BLAZEWROUGHT_STONE_BRICKS;

	// Single blocks.
	public static Block PYRESTONE_TILES;
	public static Block CRACKED_PYRESTONE_BRICKS;
	public static Block CHISELED_PYRESTONE_BRICKS;
	public static Block PYRESTONE_PILLAR;
	public static Block EMBERSTONE_TILES;
	public static Block CRACKED_EMBERSTONE_BRICKS;
	public static Block CHISELED_EMBERSTONE_BRICKS;
	public static Block EMBERSTONE_PILLAR;
	public static Block SOOTSTONE_TILES;
	public static Block CRACKED_SOOTSTONE_BRICKS;
	public static Block CHISELED_SOOTSTONE_BRICKS;
	public static Block SOOTSTONE_PILLAR;
	public static Block CHARFLINT_TILES;
	public static Block CRACKED_CHARFLINT_BRICKS;
	public static Block CHISELED_CHARFLINT_BRICKS;
	public static Block CHARFLINT_PILLAR;
	public static Block KINDLEROCK_TILES;
	public static Block CRACKED_KINDLEROCK_BRICKS;
	public static Block CHISELED_KINDLEROCK_BRICKS;
	public static Block KINDLEROCK_PILLAR;
	public static Block CINDERSHALE_TILES;
	public static Block CRACKED_CINDERSHALE_BRICKS;
	public static Block CHISELED_CINDERSHALE_BRICKS;
	public static Block CINDERSHALE_PILLAR;
	public static Block COALSPAR_TILES;
	public static Block CRACKED_COALSPAR_BRICKS;
	public static Block CHISELED_COALSPAR_BRICKS;
	public static Block COALSPAR_PILLAR;
	public static Block TINDERGRIT_TILES;
	public static Block CRACKED_TINDERGRIT_BRICKS;
	public static Block CHISELED_TINDERGRIT_BRICKS;
	public static Block TINDERGRIT_PILLAR;
	public static Block FLAREBASALT_TILES;
	public static Block CRACKED_FLAREBASALT_BRICKS;
	public static Block CHISELED_FLAREBASALT_BRICKS;
	public static Block FLAREBASALT_PILLAR;
	public static Block MAGMITE_TILES;
	public static Block CRACKED_MAGMITE_BRICKS;
	public static Block CHISELED_MAGMITE_BRICKS;
	public static Block MAGMITE_PILLAR;
	public static Block FUMAROLE_ROCK_TILES;
	public static Block CRACKED_FUMAROLE_ROCK_BRICKS;
	public static Block CHISELED_FUMAROLE_ROCK_BRICKS;
	public static Block FUMAROLE_ROCK_PILLAR;
	public static Block PYROCLAST_STONE_TILES;
	public static Block CRACKED_PYROCLAST_STONE_BRICKS;
	public static Block CHISELED_PYROCLAST_STONE_BRICKS;
	public static Block PYROCLAST_STONE_PILLAR;
	public static Block VITRIFIED_ASH_TILES;
	public static Block CRACKED_VITRIFIED_ASH_BRICKS;
	public static Block CHISELED_VITRIFIED_ASH_BRICKS;
	public static Block VITRIFIED_ASH_PILLAR;
	public static Block BLAZEWROUGHT_STONE_TILES;
	public static Block CRACKED_BLAZEWROUGHT_STONE_BRICKS;
	public static Block CHISELED_BLAZEWROUGHT_STONE_BRICKS;
	public static Block BLAZEWROUGHT_STONE_PILLAR;

	/**
	 * Fresh settings per block ({@link ModBlocks#register} writes a registry key into the
	 * instance, so settings must never be shared). Standard requires-tool stone profile
	 * (same numbers as the cinderstone feature).
	 */
	private static AbstractBlock.Settings stoneSettings(MapColor color, BlockSoundGroup sounds) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.5F, 8.0F)
				.requiresTool()
				.sounds(sounds);
	}

	private static AbstractBlock.Settings pyrestoneSettings() {
		return stoneSettings(MapColor.TERRACOTTA_ORANGE, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings emberstoneSettings() {
		return stoneSettings(MapColor.ORANGE, BlockSoundGroup.NETHERRACK);
	}

	private static AbstractBlock.Settings sootstoneSettings() {
		return stoneSettings(MapColor.GRAY, BlockSoundGroup.TUFF);
	}

	private static AbstractBlock.Settings charflintSettings() {
		return stoneSettings(MapColor.BLACK, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings kindlerockSettings() {
		return stoneSettings(MapColor.BROWN, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings cindershaleSettings() {
		return stoneSettings(MapColor.LIGHT_BLUE_GRAY, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings coalsparSettings() {
		return stoneSettings(MapColor.TERRACOTTA_BLACK, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings tindergritSettings() {
		return stoneSettings(MapColor.PALE_YELLOW, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings flarebasaltSettings() {
		return stoneSettings(MapColor.DEEPSLATE_GRAY, BlockSoundGroup.BASALT);
	}

	private static AbstractBlock.Settings magmiteSettings() {
		return stoneSettings(MapColor.DARK_RED, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings fumaroleRockSettings() {
		return stoneSettings(MapColor.TERRACOTTA_YELLOW, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings pyroclastStoneSettings() {
		return stoneSettings(MapColor.STONE_GRAY, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings vitrifiedAshSettings() {
		return stoneSettings(MapColor.LIGHT_GRAY, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings blazewroughtStoneSettings() {
		return stoneSettings(MapColor.GOLD, BlockSoundGroup.NETHER_BRICKS);
	}

	public static void init() {
		PYRESTONE = ModBlockFamilies.registerCubeFamily(
				"pyrestone", "pyrestone", PyrestoneFeature::pyrestoneSettings, true);
		POLISHED_PYRESTONE = ModBlockFamilies.registerCubeFamily(
				"polished_pyrestone", "polished_pyrestone", PyrestoneFeature::pyrestoneSettings, true);
		PYRESTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"pyrestone_bricks", "pyrestone_brick", PyrestoneFeature::pyrestoneSettings, true);
		EMBERSTONE = ModBlockFamilies.registerCubeFamily(
				"emberstone", "emberstone", PyrestoneFeature::emberstoneSettings, true);
		POLISHED_EMBERSTONE = ModBlockFamilies.registerCubeFamily(
				"polished_emberstone", "polished_emberstone", PyrestoneFeature::emberstoneSettings, true);
		EMBERSTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"emberstone_bricks", "emberstone_brick", PyrestoneFeature::emberstoneSettings, true);
		SOOTSTONE = ModBlockFamilies.registerCubeFamily(
				"sootstone", "sootstone", PyrestoneFeature::sootstoneSettings, true);
		POLISHED_SOOTSTONE = ModBlockFamilies.registerCubeFamily(
				"polished_sootstone", "polished_sootstone", PyrestoneFeature::sootstoneSettings, true);
		SOOTSTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"sootstone_bricks", "sootstone_brick", PyrestoneFeature::sootstoneSettings, true);
		CHARFLINT = ModBlockFamilies.registerCubeFamily(
				"charflint", "charflint", PyrestoneFeature::charflintSettings, true);
		POLISHED_CHARFLINT = ModBlockFamilies.registerCubeFamily(
				"polished_charflint", "polished_charflint", PyrestoneFeature::charflintSettings, true);
		CHARFLINT_BRICKS = ModBlockFamilies.registerCubeFamily(
				"charflint_bricks", "charflint_brick", PyrestoneFeature::charflintSettings, true);
		KINDLEROCK = ModBlockFamilies.registerCubeFamily(
				"kindlerock", "kindlerock", PyrestoneFeature::kindlerockSettings, true);
		POLISHED_KINDLEROCK = ModBlockFamilies.registerCubeFamily(
				"polished_kindlerock", "polished_kindlerock", PyrestoneFeature::kindlerockSettings, true);
		KINDLEROCK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"kindlerock_bricks", "kindlerock_brick", PyrestoneFeature::kindlerockSettings, true);
		CINDERSHALE = ModBlockFamilies.registerCubeFamily(
				"cindershale", "cindershale", PyrestoneFeature::cindershaleSettings, true);
		POLISHED_CINDERSHALE = ModBlockFamilies.registerCubeFamily(
				"polished_cindershale", "polished_cindershale", PyrestoneFeature::cindershaleSettings, true);
		CINDERSHALE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"cindershale_bricks", "cindershale_brick", PyrestoneFeature::cindershaleSettings, true);
		COALSPAR = ModBlockFamilies.registerCubeFamily(
				"coalspar", "coalspar", PyrestoneFeature::coalsparSettings, true);
		POLISHED_COALSPAR = ModBlockFamilies.registerCubeFamily(
				"polished_coalspar", "polished_coalspar", PyrestoneFeature::coalsparSettings, true);
		COALSPAR_BRICKS = ModBlockFamilies.registerCubeFamily(
				"coalspar_bricks", "coalspar_brick", PyrestoneFeature::coalsparSettings, true);
		TINDERGRIT = ModBlockFamilies.registerCubeFamily(
				"tindergrit", "tindergrit", PyrestoneFeature::tindergritSettings, true);
		POLISHED_TINDERGRIT = ModBlockFamilies.registerCubeFamily(
				"polished_tindergrit", "polished_tindergrit", PyrestoneFeature::tindergritSettings, true);
		TINDERGRIT_BRICKS = ModBlockFamilies.registerCubeFamily(
				"tindergrit_bricks", "tindergrit_brick", PyrestoneFeature::tindergritSettings, true);
		FLAREBASALT = ModBlockFamilies.registerCubeFamily(
				"flarebasalt", "flarebasalt", PyrestoneFeature::flarebasaltSettings, true);
		POLISHED_FLAREBASALT = ModBlockFamilies.registerCubeFamily(
				"polished_flarebasalt", "polished_flarebasalt", PyrestoneFeature::flarebasaltSettings, true);
		FLAREBASALT_BRICKS = ModBlockFamilies.registerCubeFamily(
				"flarebasalt_bricks", "flarebasalt_brick", PyrestoneFeature::flarebasaltSettings, true);
		MAGMITE = ModBlockFamilies.registerCubeFamily(
				"magmite", "magmite", PyrestoneFeature::magmiteSettings, true);
		POLISHED_MAGMITE = ModBlockFamilies.registerCubeFamily(
				"polished_magmite", "polished_magmite", PyrestoneFeature::magmiteSettings, true);
		MAGMITE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"magmite_bricks", "magmite_brick", PyrestoneFeature::magmiteSettings, true);
		FUMAROLE_ROCK = ModBlockFamilies.registerCubeFamily(
				"fumarole_rock", "fumarole_rock", PyrestoneFeature::fumaroleRockSettings, true);
		POLISHED_FUMAROLE_ROCK = ModBlockFamilies.registerCubeFamily(
				"polished_fumarole_rock", "polished_fumarole_rock", PyrestoneFeature::fumaroleRockSettings, true);
		FUMAROLE_ROCK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"fumarole_rock_bricks", "fumarole_rock_brick", PyrestoneFeature::fumaroleRockSettings, true);
		PYROCLAST_STONE = ModBlockFamilies.registerCubeFamily(
				"pyroclast_stone", "pyroclast_stone", PyrestoneFeature::pyroclastStoneSettings, true);
		POLISHED_PYROCLAST_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_pyroclast_stone", "polished_pyroclast_stone", PyrestoneFeature::pyroclastStoneSettings, true);
		PYROCLAST_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"pyroclast_stone_bricks", "pyroclast_stone_brick", PyrestoneFeature::pyroclastStoneSettings, true);
		VITRIFIED_ASH = ModBlockFamilies.registerCubeFamily(
				"vitrified_ash", "vitrified_ash", PyrestoneFeature::vitrifiedAshSettings, true);
		POLISHED_VITRIFIED_ASH = ModBlockFamilies.registerCubeFamily(
				"polished_vitrified_ash", "polished_vitrified_ash", PyrestoneFeature::vitrifiedAshSettings, true);
		VITRIFIED_ASH_BRICKS = ModBlockFamilies.registerCubeFamily(
				"vitrified_ash_bricks", "vitrified_ash_brick", PyrestoneFeature::vitrifiedAshSettings, true);
		BLAZEWROUGHT_STONE = ModBlockFamilies.registerCubeFamily(
				"blazewrought_stone", "blazewrought_stone", PyrestoneFeature::blazewroughtStoneSettings, true);
		POLISHED_BLAZEWROUGHT_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_blazewrought_stone", "polished_blazewrought_stone", PyrestoneFeature::blazewroughtStoneSettings, true);
		BLAZEWROUGHT_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"blazewrought_stone_bricks", "blazewrought_stone_brick", PyrestoneFeature::blazewroughtStoneSettings, true);

		PYRESTONE_TILES = ModBlocks.register("pyrestone_tiles", Block::new, pyrestoneSettings(), true);
		CRACKED_PYRESTONE_BRICKS = ModBlocks.register("cracked_pyrestone_bricks", Block::new, pyrestoneSettings(), true);
		CHISELED_PYRESTONE_BRICKS = ModBlocks.register("chiseled_pyrestone_bricks", Block::new, pyrestoneSettings(), true);
		PYRESTONE_PILLAR = ModBlocks.register("pyrestone_pillar", PillarBlock::new, pyrestoneSettings(), true);
		EMBERSTONE_TILES = ModBlocks.register("emberstone_tiles", Block::new, emberstoneSettings(), true);
		CRACKED_EMBERSTONE_BRICKS = ModBlocks.register("cracked_emberstone_bricks", Block::new, emberstoneSettings(), true);
		CHISELED_EMBERSTONE_BRICKS = ModBlocks.register("chiseled_emberstone_bricks", Block::new, emberstoneSettings(), true);
		EMBERSTONE_PILLAR = ModBlocks.register("emberstone_pillar", PillarBlock::new, emberstoneSettings(), true);
		SOOTSTONE_TILES = ModBlocks.register("sootstone_tiles", Block::new, sootstoneSettings(), true);
		CRACKED_SOOTSTONE_BRICKS = ModBlocks.register("cracked_sootstone_bricks", Block::new, sootstoneSettings(), true);
		CHISELED_SOOTSTONE_BRICKS = ModBlocks.register("chiseled_sootstone_bricks", Block::new, sootstoneSettings(), true);
		SOOTSTONE_PILLAR = ModBlocks.register("sootstone_pillar", PillarBlock::new, sootstoneSettings(), true);
		CHARFLINT_TILES = ModBlocks.register("charflint_tiles", Block::new, charflintSettings(), true);
		CRACKED_CHARFLINT_BRICKS = ModBlocks.register("cracked_charflint_bricks", Block::new, charflintSettings(), true);
		CHISELED_CHARFLINT_BRICKS = ModBlocks.register("chiseled_charflint_bricks", Block::new, charflintSettings(), true);
		CHARFLINT_PILLAR = ModBlocks.register("charflint_pillar", PillarBlock::new, charflintSettings(), true);
		KINDLEROCK_TILES = ModBlocks.register("kindlerock_tiles", Block::new, kindlerockSettings(), true);
		CRACKED_KINDLEROCK_BRICKS = ModBlocks.register("cracked_kindlerock_bricks", Block::new, kindlerockSettings(), true);
		CHISELED_KINDLEROCK_BRICKS = ModBlocks.register("chiseled_kindlerock_bricks", Block::new, kindlerockSettings(), true);
		KINDLEROCK_PILLAR = ModBlocks.register("kindlerock_pillar", PillarBlock::new, kindlerockSettings(), true);
		CINDERSHALE_TILES = ModBlocks.register("cindershale_tiles", Block::new, cindershaleSettings(), true);
		CRACKED_CINDERSHALE_BRICKS = ModBlocks.register("cracked_cindershale_bricks", Block::new, cindershaleSettings(), true);
		CHISELED_CINDERSHALE_BRICKS = ModBlocks.register("chiseled_cindershale_bricks", Block::new, cindershaleSettings(), true);
		CINDERSHALE_PILLAR = ModBlocks.register("cindershale_pillar", PillarBlock::new, cindershaleSettings(), true);
		COALSPAR_TILES = ModBlocks.register("coalspar_tiles", Block::new, coalsparSettings(), true);
		CRACKED_COALSPAR_BRICKS = ModBlocks.register("cracked_coalspar_bricks", Block::new, coalsparSettings(), true);
		CHISELED_COALSPAR_BRICKS = ModBlocks.register("chiseled_coalspar_bricks", Block::new, coalsparSettings(), true);
		COALSPAR_PILLAR = ModBlocks.register("coalspar_pillar", PillarBlock::new, coalsparSettings(), true);
		TINDERGRIT_TILES = ModBlocks.register("tindergrit_tiles", Block::new, tindergritSettings(), true);
		CRACKED_TINDERGRIT_BRICKS = ModBlocks.register("cracked_tindergrit_bricks", Block::new, tindergritSettings(), true);
		CHISELED_TINDERGRIT_BRICKS = ModBlocks.register("chiseled_tindergrit_bricks", Block::new, tindergritSettings(), true);
		TINDERGRIT_PILLAR = ModBlocks.register("tindergrit_pillar", PillarBlock::new, tindergritSettings(), true);
		FLAREBASALT_TILES = ModBlocks.register("flarebasalt_tiles", Block::new, flarebasaltSettings(), true);
		CRACKED_FLAREBASALT_BRICKS = ModBlocks.register("cracked_flarebasalt_bricks", Block::new, flarebasaltSettings(), true);
		CHISELED_FLAREBASALT_BRICKS = ModBlocks.register("chiseled_flarebasalt_bricks", Block::new, flarebasaltSettings(), true);
		FLAREBASALT_PILLAR = ModBlocks.register("flarebasalt_pillar", PillarBlock::new, flarebasaltSettings(), true);
		MAGMITE_TILES = ModBlocks.register("magmite_tiles", Block::new, magmiteSettings(), true);
		CRACKED_MAGMITE_BRICKS = ModBlocks.register("cracked_magmite_bricks", Block::new, magmiteSettings(), true);
		CHISELED_MAGMITE_BRICKS = ModBlocks.register("chiseled_magmite_bricks", Block::new, magmiteSettings(), true);
		MAGMITE_PILLAR = ModBlocks.register("magmite_pillar", PillarBlock::new, magmiteSettings(), true);
		FUMAROLE_ROCK_TILES = ModBlocks.register("fumarole_rock_tiles", Block::new, fumaroleRockSettings(), true);
		CRACKED_FUMAROLE_ROCK_BRICKS = ModBlocks.register("cracked_fumarole_rock_bricks", Block::new, fumaroleRockSettings(), true);
		CHISELED_FUMAROLE_ROCK_BRICKS = ModBlocks.register("chiseled_fumarole_rock_bricks", Block::new, fumaroleRockSettings(), true);
		FUMAROLE_ROCK_PILLAR = ModBlocks.register("fumarole_rock_pillar", PillarBlock::new, fumaroleRockSettings(), true);
		PYROCLAST_STONE_TILES = ModBlocks.register("pyroclast_stone_tiles", Block::new, pyroclastStoneSettings(), true);
		CRACKED_PYROCLAST_STONE_BRICKS = ModBlocks.register("cracked_pyroclast_stone_bricks", Block::new, pyroclastStoneSettings(), true);
		CHISELED_PYROCLAST_STONE_BRICKS = ModBlocks.register("chiseled_pyroclast_stone_bricks", Block::new, pyroclastStoneSettings(), true);
		PYROCLAST_STONE_PILLAR = ModBlocks.register("pyroclast_stone_pillar", PillarBlock::new, pyroclastStoneSettings(), true);
		VITRIFIED_ASH_TILES = ModBlocks.register("vitrified_ash_tiles", Block::new, vitrifiedAshSettings(), true);
		CRACKED_VITRIFIED_ASH_BRICKS = ModBlocks.register("cracked_vitrified_ash_bricks", Block::new, vitrifiedAshSettings(), true);
		CHISELED_VITRIFIED_ASH_BRICKS = ModBlocks.register("chiseled_vitrified_ash_bricks", Block::new, vitrifiedAshSettings(), true);
		VITRIFIED_ASH_PILLAR = ModBlocks.register("vitrified_ash_pillar", PillarBlock::new, vitrifiedAshSettings(), true);
		BLAZEWROUGHT_STONE_TILES = ModBlocks.register("blazewrought_stone_tiles", Block::new, blazewroughtStoneSettings(), true);
		CRACKED_BLAZEWROUGHT_STONE_BRICKS = ModBlocks.register("cracked_blazewrought_stone_bricks", Block::new, blazewroughtStoneSettings(), true);
		CHISELED_BLAZEWROUGHT_STONE_BRICKS = ModBlocks.register("chiseled_blazewrought_stone_bricks", Block::new, blazewroughtStoneSettings(), true);
		BLAZEWROUGHT_STONE_PILLAR = ModBlocks.register("blazewrought_stone_pillar", PillarBlock::new, blazewroughtStoneSettings(), true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			entries.add(PYRESTONE.block());
			entries.add(PYRESTONE.stairs());
			entries.add(PYRESTONE.slab());
			entries.add(PYRESTONE.wall());
			entries.add(POLISHED_PYRESTONE.block());
			entries.add(POLISHED_PYRESTONE.stairs());
			entries.add(POLISHED_PYRESTONE.slab());
			entries.add(POLISHED_PYRESTONE.wall());
			entries.add(PYRESTONE_BRICKS.block());
			entries.add(PYRESTONE_BRICKS.stairs());
			entries.add(PYRESTONE_BRICKS.slab());
			entries.add(PYRESTONE_BRICKS.wall());
			entries.add(PYRESTONE_TILES);
			entries.add(CRACKED_PYRESTONE_BRICKS);
			entries.add(CHISELED_PYRESTONE_BRICKS);
			entries.add(PYRESTONE_PILLAR);
			entries.add(EMBERSTONE.block());
			entries.add(EMBERSTONE.stairs());
			entries.add(EMBERSTONE.slab());
			entries.add(EMBERSTONE.wall());
			entries.add(POLISHED_EMBERSTONE.block());
			entries.add(POLISHED_EMBERSTONE.stairs());
			entries.add(POLISHED_EMBERSTONE.slab());
			entries.add(POLISHED_EMBERSTONE.wall());
			entries.add(EMBERSTONE_BRICKS.block());
			entries.add(EMBERSTONE_BRICKS.stairs());
			entries.add(EMBERSTONE_BRICKS.slab());
			entries.add(EMBERSTONE_BRICKS.wall());
			entries.add(EMBERSTONE_TILES);
			entries.add(CRACKED_EMBERSTONE_BRICKS);
			entries.add(CHISELED_EMBERSTONE_BRICKS);
			entries.add(EMBERSTONE_PILLAR);
			entries.add(SOOTSTONE.block());
			entries.add(SOOTSTONE.stairs());
			entries.add(SOOTSTONE.slab());
			entries.add(SOOTSTONE.wall());
			entries.add(POLISHED_SOOTSTONE.block());
			entries.add(POLISHED_SOOTSTONE.stairs());
			entries.add(POLISHED_SOOTSTONE.slab());
			entries.add(POLISHED_SOOTSTONE.wall());
			entries.add(SOOTSTONE_BRICKS.block());
			entries.add(SOOTSTONE_BRICKS.stairs());
			entries.add(SOOTSTONE_BRICKS.slab());
			entries.add(SOOTSTONE_BRICKS.wall());
			entries.add(SOOTSTONE_TILES);
			entries.add(CRACKED_SOOTSTONE_BRICKS);
			entries.add(CHISELED_SOOTSTONE_BRICKS);
			entries.add(SOOTSTONE_PILLAR);
			entries.add(CHARFLINT.block());
			entries.add(CHARFLINT.stairs());
			entries.add(CHARFLINT.slab());
			entries.add(CHARFLINT.wall());
			entries.add(POLISHED_CHARFLINT.block());
			entries.add(POLISHED_CHARFLINT.stairs());
			entries.add(POLISHED_CHARFLINT.slab());
			entries.add(POLISHED_CHARFLINT.wall());
			entries.add(CHARFLINT_BRICKS.block());
			entries.add(CHARFLINT_BRICKS.stairs());
			entries.add(CHARFLINT_BRICKS.slab());
			entries.add(CHARFLINT_BRICKS.wall());
			entries.add(CHARFLINT_TILES);
			entries.add(CRACKED_CHARFLINT_BRICKS);
			entries.add(CHISELED_CHARFLINT_BRICKS);
			entries.add(CHARFLINT_PILLAR);
			entries.add(KINDLEROCK.block());
			entries.add(KINDLEROCK.stairs());
			entries.add(KINDLEROCK.slab());
			entries.add(KINDLEROCK.wall());
			entries.add(POLISHED_KINDLEROCK.block());
			entries.add(POLISHED_KINDLEROCK.stairs());
			entries.add(POLISHED_KINDLEROCK.slab());
			entries.add(POLISHED_KINDLEROCK.wall());
			entries.add(KINDLEROCK_BRICKS.block());
			entries.add(KINDLEROCK_BRICKS.stairs());
			entries.add(KINDLEROCK_BRICKS.slab());
			entries.add(KINDLEROCK_BRICKS.wall());
			entries.add(KINDLEROCK_TILES);
			entries.add(CRACKED_KINDLEROCK_BRICKS);
			entries.add(CHISELED_KINDLEROCK_BRICKS);
			entries.add(KINDLEROCK_PILLAR);
			entries.add(CINDERSHALE.block());
			entries.add(CINDERSHALE.stairs());
			entries.add(CINDERSHALE.slab());
			entries.add(CINDERSHALE.wall());
			entries.add(POLISHED_CINDERSHALE.block());
			entries.add(POLISHED_CINDERSHALE.stairs());
			entries.add(POLISHED_CINDERSHALE.slab());
			entries.add(POLISHED_CINDERSHALE.wall());
			entries.add(CINDERSHALE_BRICKS.block());
			entries.add(CINDERSHALE_BRICKS.stairs());
			entries.add(CINDERSHALE_BRICKS.slab());
			entries.add(CINDERSHALE_BRICKS.wall());
			entries.add(CINDERSHALE_TILES);
			entries.add(CRACKED_CINDERSHALE_BRICKS);
			entries.add(CHISELED_CINDERSHALE_BRICKS);
			entries.add(CINDERSHALE_PILLAR);
			entries.add(COALSPAR.block());
			entries.add(COALSPAR.stairs());
			entries.add(COALSPAR.slab());
			entries.add(COALSPAR.wall());
			entries.add(POLISHED_COALSPAR.block());
			entries.add(POLISHED_COALSPAR.stairs());
			entries.add(POLISHED_COALSPAR.slab());
			entries.add(POLISHED_COALSPAR.wall());
			entries.add(COALSPAR_BRICKS.block());
			entries.add(COALSPAR_BRICKS.stairs());
			entries.add(COALSPAR_BRICKS.slab());
			entries.add(COALSPAR_BRICKS.wall());
			entries.add(COALSPAR_TILES);
			entries.add(CRACKED_COALSPAR_BRICKS);
			entries.add(CHISELED_COALSPAR_BRICKS);
			entries.add(COALSPAR_PILLAR);
			entries.add(TINDERGRIT.block());
			entries.add(TINDERGRIT.stairs());
			entries.add(TINDERGRIT.slab());
			entries.add(TINDERGRIT.wall());
			entries.add(POLISHED_TINDERGRIT.block());
			entries.add(POLISHED_TINDERGRIT.stairs());
			entries.add(POLISHED_TINDERGRIT.slab());
			entries.add(POLISHED_TINDERGRIT.wall());
			entries.add(TINDERGRIT_BRICKS.block());
			entries.add(TINDERGRIT_BRICKS.stairs());
			entries.add(TINDERGRIT_BRICKS.slab());
			entries.add(TINDERGRIT_BRICKS.wall());
			entries.add(TINDERGRIT_TILES);
			entries.add(CRACKED_TINDERGRIT_BRICKS);
			entries.add(CHISELED_TINDERGRIT_BRICKS);
			entries.add(TINDERGRIT_PILLAR);
			entries.add(FLAREBASALT.block());
			entries.add(FLAREBASALT.stairs());
			entries.add(FLAREBASALT.slab());
			entries.add(FLAREBASALT.wall());
			entries.add(POLISHED_FLAREBASALT.block());
			entries.add(POLISHED_FLAREBASALT.stairs());
			entries.add(POLISHED_FLAREBASALT.slab());
			entries.add(POLISHED_FLAREBASALT.wall());
			entries.add(FLAREBASALT_BRICKS.block());
			entries.add(FLAREBASALT_BRICKS.stairs());
			entries.add(FLAREBASALT_BRICKS.slab());
			entries.add(FLAREBASALT_BRICKS.wall());
			entries.add(FLAREBASALT_TILES);
			entries.add(CRACKED_FLAREBASALT_BRICKS);
			entries.add(CHISELED_FLAREBASALT_BRICKS);
			entries.add(FLAREBASALT_PILLAR);
			entries.add(MAGMITE.block());
			entries.add(MAGMITE.stairs());
			entries.add(MAGMITE.slab());
			entries.add(MAGMITE.wall());
			entries.add(POLISHED_MAGMITE.block());
			entries.add(POLISHED_MAGMITE.stairs());
			entries.add(POLISHED_MAGMITE.slab());
			entries.add(POLISHED_MAGMITE.wall());
			entries.add(MAGMITE_BRICKS.block());
			entries.add(MAGMITE_BRICKS.stairs());
			entries.add(MAGMITE_BRICKS.slab());
			entries.add(MAGMITE_BRICKS.wall());
			entries.add(MAGMITE_TILES);
			entries.add(CRACKED_MAGMITE_BRICKS);
			entries.add(CHISELED_MAGMITE_BRICKS);
			entries.add(MAGMITE_PILLAR);
			entries.add(FUMAROLE_ROCK.block());
			entries.add(FUMAROLE_ROCK.stairs());
			entries.add(FUMAROLE_ROCK.slab());
			entries.add(FUMAROLE_ROCK.wall());
			entries.add(POLISHED_FUMAROLE_ROCK.block());
			entries.add(POLISHED_FUMAROLE_ROCK.stairs());
			entries.add(POLISHED_FUMAROLE_ROCK.slab());
			entries.add(POLISHED_FUMAROLE_ROCK.wall());
			entries.add(FUMAROLE_ROCK_BRICKS.block());
			entries.add(FUMAROLE_ROCK_BRICKS.stairs());
			entries.add(FUMAROLE_ROCK_BRICKS.slab());
			entries.add(FUMAROLE_ROCK_BRICKS.wall());
			entries.add(FUMAROLE_ROCK_TILES);
			entries.add(CRACKED_FUMAROLE_ROCK_BRICKS);
			entries.add(CHISELED_FUMAROLE_ROCK_BRICKS);
			entries.add(FUMAROLE_ROCK_PILLAR);
			entries.add(PYROCLAST_STONE.block());
			entries.add(PYROCLAST_STONE.stairs());
			entries.add(PYROCLAST_STONE.slab());
			entries.add(PYROCLAST_STONE.wall());
			entries.add(POLISHED_PYROCLAST_STONE.block());
			entries.add(POLISHED_PYROCLAST_STONE.stairs());
			entries.add(POLISHED_PYROCLAST_STONE.slab());
			entries.add(POLISHED_PYROCLAST_STONE.wall());
			entries.add(PYROCLAST_STONE_BRICKS.block());
			entries.add(PYROCLAST_STONE_BRICKS.stairs());
			entries.add(PYROCLAST_STONE_BRICKS.slab());
			entries.add(PYROCLAST_STONE_BRICKS.wall());
			entries.add(PYROCLAST_STONE_TILES);
			entries.add(CRACKED_PYROCLAST_STONE_BRICKS);
			entries.add(CHISELED_PYROCLAST_STONE_BRICKS);
			entries.add(PYROCLAST_STONE_PILLAR);
			entries.add(VITRIFIED_ASH.block());
			entries.add(VITRIFIED_ASH.stairs());
			entries.add(VITRIFIED_ASH.slab());
			entries.add(VITRIFIED_ASH.wall());
			entries.add(POLISHED_VITRIFIED_ASH.block());
			entries.add(POLISHED_VITRIFIED_ASH.stairs());
			entries.add(POLISHED_VITRIFIED_ASH.slab());
			entries.add(POLISHED_VITRIFIED_ASH.wall());
			entries.add(VITRIFIED_ASH_BRICKS.block());
			entries.add(VITRIFIED_ASH_BRICKS.stairs());
			entries.add(VITRIFIED_ASH_BRICKS.slab());
			entries.add(VITRIFIED_ASH_BRICKS.wall());
			entries.add(VITRIFIED_ASH_TILES);
			entries.add(CRACKED_VITRIFIED_ASH_BRICKS);
			entries.add(CHISELED_VITRIFIED_ASH_BRICKS);
			entries.add(VITRIFIED_ASH_PILLAR);
			entries.add(BLAZEWROUGHT_STONE.block());
			entries.add(BLAZEWROUGHT_STONE.stairs());
			entries.add(BLAZEWROUGHT_STONE.slab());
			entries.add(BLAZEWROUGHT_STONE.wall());
			entries.add(POLISHED_BLAZEWROUGHT_STONE.block());
			entries.add(POLISHED_BLAZEWROUGHT_STONE.stairs());
			entries.add(POLISHED_BLAZEWROUGHT_STONE.slab());
			entries.add(POLISHED_BLAZEWROUGHT_STONE.wall());
			entries.add(BLAZEWROUGHT_STONE_BRICKS.block());
			entries.add(BLAZEWROUGHT_STONE_BRICKS.stairs());
			entries.add(BLAZEWROUGHT_STONE_BRICKS.slab());
			entries.add(BLAZEWROUGHT_STONE_BRICKS.wall());
			entries.add(BLAZEWROUGHT_STONE_TILES);
			entries.add(CRACKED_BLAZEWROUGHT_STONE_BRICKS);
			entries.add(CHISELED_BLAZEWROUGHT_STONE_BRICKS);
			entries.add(BLAZEWROUGHT_STONE_PILLAR);
		});

		PyrestoneHandbook.register();
	}
}
