package net.sonic0810.copperinferno.feature.archfiends;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.mob.AbstractSkeletonEntity;
import net.minecraft.entity.mob.EvokerEntity;
import net.minecraft.entity.mob.GhastEntity;
import net.minecraft.entity.mob.HoglinEntity;
import net.minecraft.entity.mob.PiglinBruteEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * The ten archfiend bosses (boss bars via core.boss.BossBarHolder), all
 * summoned-only: each is called with its own sigil (shared
 * {@link ArchfiendSummonItem}, ring recipes in
 * {@code data/copper_inferno/recipe/archfiends/}) and never spawns naturally
 * (SpawnGroup.MISC, no spawn restrictions registered). All ten keep their
 * vanilla models but wear their own recolored textures via renderer
 * subclasses (see {@code ArchfiendsFeatureClient}); EntityType dimensions are
 * copied from the vanilla registrations (verified via bytecode) and inflated
 * via the SCALE attribute. Summon sigils, boss drops, EPIC trophies, spawn
 * eggs and handbook entries are all registered here. Generated by
 * {@code devtools/gen/archfiends_gen.py}; keep ids as plain literals so the
 * audit scripts can parse them.
 */
public final class ArchfiendsFeature {
	private ArchfiendsFeature() {
	}

	public static EntityType<DreadGhastSovereignEntity> DREAD_GHAST_SOVEREIGN;
	public static EntityType<CinderGhastMatriarchEntity> CINDER_GHAST_MATRIARCH;
	public static EntityType<MoltenHoglinTyrantEntity> MOLTEN_HOGLIN_TYRANT;
	public static EntityType<AshenHoglinGorefiendEntity> ASHEN_HOGLIN_GOREFIEND;
	public static EntityType<AshEvokerArchonEntity> ASH_EVOKER_ARCHON;
	public static EntityType<SootEvokerHighlordEntity> SOOT_EVOKER_HIGHLORD;
	public static EntityType<CinderBruteWarlordEntity> CINDER_BRUTE_WARLORD;
	public static EntityType<GildedBruteExecutionerEntity> GILDED_BRUTE_EXECUTIONER;
	public static EntityType<SlagWitherMonarchEntity> SLAG_WITHER_MONARCH;
	public static EntityType<BlightWitherEmperorEntity> BLIGHT_WITHER_EMPEROR;

	public static Item DREAD_SOVEREIGN_SIGIL;
	public static Item DREAD_GHAST_TEAR;
	public static Item SOVEREIGN_VEIL_SHARD;
	public static Item DREAD_SOVEREIGN_CROWN;
	public static Item DREAD_GHAST_SOVEREIGN_SPAWN_EGG;
	public static Item CINDER_MATRIARCH_SIGIL;
	public static Item CINDER_TEARSTONE;
	public static Item MATRIARCH_EMBER_SAC;
	public static Item MATRIARCH_CINDER_DIADEM;
	public static Item CINDER_GHAST_MATRIARCH_SPAWN_EGG;
	public static Item MOLTEN_TYRANT_SIGIL;
	public static Item MOLTEN_TUSK;
	public static Item TYRANT_SEARED_HIDE;
	public static Item MOLTEN_TYRANT_IDOL;
	public static Item MOLTEN_HOGLIN_TYRANT_SPAWN_EGG;
	public static Item ASHEN_GOREFIEND_SIGIL;
	public static Item GOREFIEND_BRISTLE;
	public static Item ASHEN_GORE_HEART;
	public static Item GOREFIEND_ASH_TOTEM;
	public static Item ASHEN_HOGLIN_GOREFIEND_SPAWN_EGG;
	public static Item ASH_ARCHON_SIGIL;
	public static Item ARCHON_ASH_TOME;
	public static Item ASH_RUNE_SHARD;
	public static Item ARCHON_CINDER_MITRE;
	public static Item ASH_EVOKER_ARCHON_SPAWN_EGG;
	public static Item SOOT_HIGHLORD_SIGIL;
	public static Item HIGHLORD_SOOT_PEARL;
	public static Item SOOT_GRIMOIRE_PAGE;
	public static Item HIGHLORD_SOOT_SCEPTRE;
	public static Item SOOT_EVOKER_HIGHLORD_SPAWN_EGG;
	public static Item CINDER_WARLORD_SIGIL;
	public static Item WARLORD_CINDER_AXEHEAD;
	public static Item WARLORD_GILDED_TUSK;
	public static Item WARLORD_WAR_CROWN;
	public static Item CINDER_BRUTE_WARLORD_SPAWN_EGG;
	public static Item GILDED_EXECUTIONER_SIGIL;
	public static Item EXECUTIONER_GILDED_PLATE;
	public static Item EXECUTIONER_CHAIN_LINK;
	public static Item EXECUTIONER_GOLD_VISAGE;
	public static Item GILDED_BRUTE_EXECUTIONER_SPAWN_EGG;
	public static Item SLAG_MONARCH_SIGIL;
	public static Item MONARCH_SLAG_RIB;
	public static Item WITHERED_SLAG_CHUNK;
	public static Item MONARCH_WITHER_CROWN;
	public static Item SLAG_WITHER_MONARCH_SPAWN_EGG;
	public static Item BLIGHT_EMPEROR_SIGIL;
	public static Item BLIGHT_BONE_SHARD;
	public static Item EMPEROR_BLIGHT_MARROW;
	public static Item EMPEROR_BLIGHT_DIADEM;
	public static Item BLIGHT_WITHER_EMPEROR_SPAWN_EGG;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		ArchfiendsHandbook.register();
	}

	/**
	 * Base dimensions copied from the vanilla EntityType registrations (bytecode);
	 * the bosses' bulk comes from the SCALE attribute, and all get an extended
	 * tracking range so the boss bar/model appear well before the fight. Summoned
	 * bosses call setPersistent, so MISC (no natural despawn logic) fits them all.
	 */
	private static void registerEntityTypes() {
		DREAD_GHAST_SOVEREIGN = ModEntities.register("dread_ghast_sovereign",
				EntityType.Builder.create(DreadGhastSovereignEntity::new, SpawnGroup.MISC)
						.makeFireImmune()
						.dimensions(4.0f, 4.0f)
						.eyeHeight(2.6f)
						.maxTrackingRange(10));
		CINDER_GHAST_MATRIARCH = ModEntities.register("cinder_ghast_matriarch",
				EntityType.Builder.create(CinderGhastMatriarchEntity::new, SpawnGroup.MISC)
						.makeFireImmune()
						.dimensions(4.0f, 4.0f)
						.eyeHeight(2.6f)
						.maxTrackingRange(10));
		MOLTEN_HOGLIN_TYRANT = ModEntities.register("molten_hoglin_tyrant",
				EntityType.Builder.create(MoltenHoglinTyrantEntity::new, SpawnGroup.MISC)
						.dimensions(1.3964844f, 1.4f)
						.maxTrackingRange(10));
		ASHEN_HOGLIN_GOREFIEND = ModEntities.register("ashen_hoglin_gorefiend",
				EntityType.Builder.create(AshenHoglinGorefiendEntity::new, SpawnGroup.MISC)
						.dimensions(1.3964844f, 1.4f)
						.maxTrackingRange(10));
		ASH_EVOKER_ARCHON = ModEntities.register("ash_evoker_archon",
				EntityType.Builder.create(AshEvokerArchonEntity::new, SpawnGroup.MISC)
						.dimensions(0.6f, 1.95f)
						.maxTrackingRange(10));
		SOOT_EVOKER_HIGHLORD = ModEntities.register("soot_evoker_highlord",
				EntityType.Builder.create(SootEvokerHighlordEntity::new, SpawnGroup.MISC)
						.dimensions(0.6f, 1.95f)
						.maxTrackingRange(10));
		CINDER_BRUTE_WARLORD = ModEntities.register("cinder_brute_warlord",
				EntityType.Builder.create(CinderBruteWarlordEntity::new, SpawnGroup.MISC)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.maxTrackingRange(10));
		GILDED_BRUTE_EXECUTIONER = ModEntities.register("gilded_brute_executioner",
				EntityType.Builder.create(GildedBruteExecutionerEntity::new, SpawnGroup.MISC)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.79f)
						.maxTrackingRange(10));
		SLAG_WITHER_MONARCH = ModEntities.register("slag_wither_monarch",
				EntityType.Builder.create(SlagWitherMonarchEntity::new, SpawnGroup.MISC)
						.makeFireImmune()
						.dimensions(0.7f, 2.4f)
						.eyeHeight(2.1f)
						.maxTrackingRange(10));
		BLIGHT_WITHER_EMPEROR = ModEntities.register("blight_wither_emperor",
				EntityType.Builder.create(BlightWitherEmperorEntity::new, SpawnGroup.MISC)
						.makeFireImmune()
						.dimensions(0.7f, 2.4f)
						.eyeHeight(2.1f)
						.maxTrackingRange(10));
	}

	/**
	 * EntityAttributes fields have no GENERIC_ prefix in 1.21.9 (verified via
	 * javap); DefaultAttributeContainer.Builder.add(...) overrides the base values
	 * from each vanilla create*Attributes() builder.
	 */
	private static void registerAttributes() {
		FabricDefaultAttributeRegistry.register(DREAD_GHAST_SOVEREIGN, GhastEntity.createGhastAttributes()
				.add(EntityAttributes.MAX_HEALTH, 320.0)
				.add(EntityAttributes.SCALE, 1.6)
				.add(EntityAttributes.FOLLOW_RANGE, 100.0));
		FabricDefaultAttributeRegistry.register(CINDER_GHAST_MATRIARCH, GhastEntity.createGhastAttributes()
				.add(EntityAttributes.MAX_HEALTH, 300.0)
				.add(EntityAttributes.SCALE, 1.8)
				.add(EntityAttributes.FOLLOW_RANGE, 100.0));
		FabricDefaultAttributeRegistry.register(MOLTEN_HOGLIN_TYRANT, HoglinEntity.createHoglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 320.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 16.0)
				.add(EntityAttributes.SCALE, 2.2)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 1.0)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(ASHEN_HOGLIN_GOREFIEND, HoglinEntity.createHoglinAttributes()
				.add(EntityAttributes.MAX_HEALTH, 340.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 14.0)
				.add(EntityAttributes.SCALE, 2.4)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 1.0)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(ASH_EVOKER_ARCHON, EvokerEntity.createEvokerAttributes()
				.add(EntityAttributes.MAX_HEALTH, 240.0)
				.add(EntityAttributes.SCALE, 1.8)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(SOOT_EVOKER_HIGHLORD, EvokerEntity.createEvokerAttributes()
				.add(EntityAttributes.MAX_HEALTH, 260.0)
				.add(EntityAttributes.SCALE, 2.0)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(CINDER_BRUTE_WARLORD, PiglinBruteEntity.createPiglinBruteAttributes()
				.add(EntityAttributes.MAX_HEALTH, 300.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 18.0)
				.add(EntityAttributes.SCALE, 2.0)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 0.8)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(GILDED_BRUTE_EXECUTIONER, PiglinBruteEntity.createPiglinBruteAttributes()
				.add(EntityAttributes.MAX_HEALTH, 320.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 16.0)
				.add(EntityAttributes.SCALE, 2.2)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 0.8)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(SLAG_WITHER_MONARCH, AbstractSkeletonEntity.createAbstractSkeletonAttributes()
				.add(EntityAttributes.MAX_HEALTH, 280.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 12.0)
				.add(EntityAttributes.SCALE, 2.2)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 0.6)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(BLIGHT_WITHER_EMPEROR, AbstractSkeletonEntity.createAbstractSkeletonAttributes()
				.add(EntityAttributes.MAX_HEALTH, 300.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 14.0)
				.add(EntityAttributes.SCALE, 2.4)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 0.6)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
	}

	private static void registerItems() {
		// Summon sigils (shared ArchfiendSummonItem; boss type resolved from the
		// already-registered EntityType fields).
		DREAD_SOVEREIGN_SIGIL = ModItems.register("dread_sovereign_sigil",
				s -> new ArchfiendSummonItem(DREAD_GHAST_SOVEREIGN, s), new Item.Settings());
		CINDER_MATRIARCH_SIGIL = ModItems.register("cinder_matriarch_sigil",
				s -> new ArchfiendSummonItem(CINDER_GHAST_MATRIARCH, s), new Item.Settings());
		MOLTEN_TYRANT_SIGIL = ModItems.register("molten_tyrant_sigil",
				s -> new ArchfiendSummonItem(MOLTEN_HOGLIN_TYRANT, s), new Item.Settings());
		ASHEN_GOREFIEND_SIGIL = ModItems.register("ashen_gorefiend_sigil",
				s -> new ArchfiendSummonItem(ASHEN_HOGLIN_GOREFIEND, s), new Item.Settings());
		ASH_ARCHON_SIGIL = ModItems.register("ash_archon_sigil",
				s -> new ArchfiendSummonItem(ASH_EVOKER_ARCHON, s), new Item.Settings());
		SOOT_HIGHLORD_SIGIL = ModItems.register("soot_highlord_sigil",
				s -> new ArchfiendSummonItem(SOOT_EVOKER_HIGHLORD, s), new Item.Settings());
		CINDER_WARLORD_SIGIL = ModItems.register("cinder_warlord_sigil",
				s -> new ArchfiendSummonItem(CINDER_BRUTE_WARLORD, s), new Item.Settings());
		GILDED_EXECUTIONER_SIGIL = ModItems.register("gilded_executioner_sigil",
				s -> new ArchfiendSummonItem(GILDED_BRUTE_EXECUTIONER, s), new Item.Settings());
		SLAG_MONARCH_SIGIL = ModItems.register("slag_monarch_sigil",
				s -> new ArchfiendSummonItem(SLAG_WITHER_MONARCH, s), new Item.Settings());
		BLIGHT_EMPEROR_SIGIL = ModItems.register("blight_emperor_sigil",
				s -> new ArchfiendSummonItem(BLIGHT_WITHER_EMPEROR, s), new Item.Settings());

		// Boss drops and EPIC trophies (Item.Settings.rarity verified via javap).
		DREAD_GHAST_TEAR = ModItems.register("dread_ghast_tear", Item::new, new Item.Settings());
		SOVEREIGN_VEIL_SHARD = ModItems.register("sovereign_veil_shard", Item::new, new Item.Settings());
		DREAD_SOVEREIGN_CROWN = ModItems.register("dread_sovereign_crown", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		CINDER_TEARSTONE = ModItems.register("cinder_tearstone", Item::new, new Item.Settings());
		MATRIARCH_EMBER_SAC = ModItems.register("matriarch_ember_sac", Item::new, new Item.Settings());
		MATRIARCH_CINDER_DIADEM = ModItems.register("matriarch_cinder_diadem", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		MOLTEN_TUSK = ModItems.register("molten_tusk", Item::new, new Item.Settings());
		TYRANT_SEARED_HIDE = ModItems.register("tyrant_seared_hide", Item::new, new Item.Settings());
		MOLTEN_TYRANT_IDOL = ModItems.register("molten_tyrant_idol", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		GOREFIEND_BRISTLE = ModItems.register("gorefiend_bristle", Item::new, new Item.Settings());
		ASHEN_GORE_HEART = ModItems.register("ashen_gore_heart", Item::new, new Item.Settings());
		GOREFIEND_ASH_TOTEM = ModItems.register("gorefiend_ash_totem", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		ARCHON_ASH_TOME = ModItems.register("archon_ash_tome", Item::new, new Item.Settings());
		ASH_RUNE_SHARD = ModItems.register("ash_rune_shard", Item::new, new Item.Settings());
		ARCHON_CINDER_MITRE = ModItems.register("archon_cinder_mitre", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		HIGHLORD_SOOT_PEARL = ModItems.register("highlord_soot_pearl", Item::new, new Item.Settings());
		SOOT_GRIMOIRE_PAGE = ModItems.register("soot_grimoire_page", Item::new, new Item.Settings());
		HIGHLORD_SOOT_SCEPTRE = ModItems.register("highlord_soot_sceptre", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		WARLORD_CINDER_AXEHEAD = ModItems.register("warlord_cinder_axehead", Item::new, new Item.Settings());
		WARLORD_GILDED_TUSK = ModItems.register("warlord_gilded_tusk", Item::new, new Item.Settings());
		WARLORD_WAR_CROWN = ModItems.register("warlord_war_crown", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		EXECUTIONER_GILDED_PLATE = ModItems.register("executioner_gilded_plate", Item::new, new Item.Settings());
		EXECUTIONER_CHAIN_LINK = ModItems.register("executioner_chain_link", Item::new, new Item.Settings());
		EXECUTIONER_GOLD_VISAGE = ModItems.register("executioner_gold_visage", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		MONARCH_SLAG_RIB = ModItems.register("monarch_slag_rib", Item::new, new Item.Settings());
		WITHERED_SLAG_CHUNK = ModItems.register("withered_slag_chunk", Item::new, new Item.Settings());
		MONARCH_WITHER_CROWN = ModItems.register("monarch_wither_crown", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		BLIGHT_BONE_SHARD = ModItems.register("blight_bone_shard", Item::new, new Item.Settings());
		EMPEROR_BLIGHT_MARROW = ModItems.register("emperor_blight_marrow", Item::new, new Item.Settings());
		EMPEROR_BLIGHT_DIADEM = ModItems.register("emperor_blight_diadem", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));

		// Item.Settings.spawnEgg(type) stores the ENTITY_DATA component the
		// vanilla SpawnEggItem reads its entity type from in 1.21.9
		// (infernoboss pattern).
		DREAD_GHAST_SOVEREIGN_SPAWN_EGG = ModItems.register("dread_ghast_sovereign_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(DREAD_GHAST_SOVEREIGN));
		CINDER_GHAST_MATRIARCH_SPAWN_EGG = ModItems.register("cinder_ghast_matriarch_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_GHAST_MATRIARCH));
		MOLTEN_HOGLIN_TYRANT_SPAWN_EGG = ModItems.register("molten_hoglin_tyrant_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MOLTEN_HOGLIN_TYRANT));
		ASHEN_HOGLIN_GOREFIEND_SPAWN_EGG = ModItems.register("ashen_hoglin_gorefiend_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASHEN_HOGLIN_GOREFIEND));
		ASH_EVOKER_ARCHON_SPAWN_EGG = ModItems.register("ash_evoker_archon_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_EVOKER_ARCHON));
		SOOT_EVOKER_HIGHLORD_SPAWN_EGG = ModItems.register("soot_evoker_highlord_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_EVOKER_HIGHLORD));
		CINDER_BRUTE_WARLORD_SPAWN_EGG = ModItems.register("cinder_brute_warlord_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_BRUTE_WARLORD));
		GILDED_BRUTE_EXECUTIONER_SPAWN_EGG = ModItems.register("gilded_brute_executioner_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(GILDED_BRUTE_EXECUTIONER));
		SLAG_WITHER_MONARCH_SPAWN_EGG = ModItems.register("slag_wither_monarch_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_WITHER_MONARCH));
		BLIGHT_WITHER_EMPEROR_SPAWN_EGG = ModItems.register("blight_wither_emperor_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(BLIGHT_WITHER_EMPEROR));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MOBS_KEY).register(entries -> {
			// Summon sigils, then per-boss drops/trophies, then the spawn eggs.
			entries.add(DREAD_SOVEREIGN_SIGIL);
			entries.add(CINDER_MATRIARCH_SIGIL);
			entries.add(MOLTEN_TYRANT_SIGIL);
			entries.add(ASHEN_GOREFIEND_SIGIL);
			entries.add(ASH_ARCHON_SIGIL);
			entries.add(SOOT_HIGHLORD_SIGIL);
			entries.add(CINDER_WARLORD_SIGIL);
			entries.add(GILDED_EXECUTIONER_SIGIL);
			entries.add(SLAG_MONARCH_SIGIL);
			entries.add(BLIGHT_EMPEROR_SIGIL);
			entries.add(DREAD_GHAST_TEAR);
			entries.add(SOVEREIGN_VEIL_SHARD);
			entries.add(DREAD_SOVEREIGN_CROWN);
			entries.add(CINDER_TEARSTONE);
			entries.add(MATRIARCH_EMBER_SAC);
			entries.add(MATRIARCH_CINDER_DIADEM);
			entries.add(MOLTEN_TUSK);
			entries.add(TYRANT_SEARED_HIDE);
			entries.add(MOLTEN_TYRANT_IDOL);
			entries.add(GOREFIEND_BRISTLE);
			entries.add(ASHEN_GORE_HEART);
			entries.add(GOREFIEND_ASH_TOTEM);
			entries.add(ARCHON_ASH_TOME);
			entries.add(ASH_RUNE_SHARD);
			entries.add(ARCHON_CINDER_MITRE);
			entries.add(HIGHLORD_SOOT_PEARL);
			entries.add(SOOT_GRIMOIRE_PAGE);
			entries.add(HIGHLORD_SOOT_SCEPTRE);
			entries.add(WARLORD_CINDER_AXEHEAD);
			entries.add(WARLORD_GILDED_TUSK);
			entries.add(WARLORD_WAR_CROWN);
			entries.add(EXECUTIONER_GILDED_PLATE);
			entries.add(EXECUTIONER_CHAIN_LINK);
			entries.add(EXECUTIONER_GOLD_VISAGE);
			entries.add(MONARCH_SLAG_RIB);
			entries.add(WITHERED_SLAG_CHUNK);
			entries.add(MONARCH_WITHER_CROWN);
			entries.add(BLIGHT_BONE_SHARD);
			entries.add(EMPEROR_BLIGHT_MARROW);
			entries.add(EMPEROR_BLIGHT_DIADEM);
			entries.add(DREAD_GHAST_SOVEREIGN_SPAWN_EGG);
			entries.add(CINDER_GHAST_MATRIARCH_SPAWN_EGG);
			entries.add(MOLTEN_HOGLIN_TYRANT_SPAWN_EGG);
			entries.add(ASHEN_HOGLIN_GOREFIEND_SPAWN_EGG);
			entries.add(ASH_EVOKER_ARCHON_SPAWN_EGG);
			entries.add(SOOT_EVOKER_HIGHLORD_SPAWN_EGG);
			entries.add(CINDER_BRUTE_WARLORD_SPAWN_EGG);
			entries.add(GILDED_BRUTE_EXECUTIONER_SPAWN_EGG);
			entries.add(SLAG_WITHER_MONARCH_SPAWN_EGG);
			entries.add(BLIGHT_WITHER_EMPEROR_SPAWN_EGG);
		});
	}
}
