package net.sonic0810.copperinferno.feature.moltenfauna;

import java.util.function.Predicate;

import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.SpawnLocationTypes;
import net.minecraft.entity.SpawnReason;
import net.minecraft.entity.SpawnRestriction;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.mob.MobEntity;
import net.minecraft.entity.passive.AbstractCowEntity;
import net.minecraft.entity.passive.AnimalEntity;
import net.minecraft.entity.passive.ChickenEntity;
import net.minecraft.entity.passive.PigEntity;
import net.minecraft.entity.passive.SheepEntity;
import net.minecraft.entity.passive.StriderEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.FluidTags;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Direction;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.random.Random;
import net.minecraft.world.Heightmap;
import net.minecraft.world.ServerWorldAccess;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModDimensions;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * Molten Fauna: 25 passive/neutral mobs (all SpawnGroup.CREATURE) native to the Inferno
 * dimension - 5 lava-wading strider variants, 5 cow variants, 5 chicken variants, 5 pig
 * variants and 5 sheep variants. Each is a thin subclass of the vanilla base reusing the
 * vanilla renderer (see {@code MoltenFaunaFeatureClient}). EntityType dimensions/eye
 * heights are copied from the vanilla EntityType registrations (verified via bytecode);
 * attributes start from the vanilla create*Attributes() builders with per-mob tweaks.
 * Spawn eggs + drop items, natural spawns in the three Inferno biomes, and drop recipes
 * are all registered here. Generated by {@code devtools/gen/moltenfauna_gen.py}.
 */
public final class MoltenFaunaFeature {
	private MoltenFaunaFeature() {
	}

	public static EntityType<MagmaStriderEntity> MAGMA_STRIDER;
	public static EntityType<SootStriderEntity> SOOT_STRIDER;
	public static EntityType<BasaltStriderEntity> BASALT_STRIDER;
	public static EntityType<SlagStriderEntity> SLAG_STRIDER;
	public static EntityType<ObsidianStriderEntity> OBSIDIAN_STRIDER;
	public static EntityType<EmberGrazerEntity> EMBER_GRAZER;
	public static EntityType<AshYakEntity> ASH_YAK;
	public static EntityType<MagmaOxEntity> MAGMA_OX;
	public static EntityType<SlagBuffaloEntity> SLAG_BUFFALO;
	public static EntityType<CinderAurochsEntity> CINDER_AUROCHS;
	public static EntityType<SootHenEntity> SOOT_HEN;
	public static EntityType<CinderRoosterEntity> CINDER_ROOSTER;
	public static EntityType<EmberPulletEntity> EMBER_PULLET;
	public static EntityType<AshFowlEntity> ASH_FOWL;
	public static EntityType<MagmaBantamEntity> MAGMA_BANTAM;
	public static EntityType<MagmaHogEntity> MAGMA_HOG;
	public static EntityType<SootSwineEntity> SOOT_SWINE;
	public static EntityType<CinderBoarEntity> CINDER_BOAR;
	public static EntityType<SlagSowEntity> SLAG_SOW;
	public static EntityType<EmberPorkerEntity> EMBER_PORKER;
	public static EntityType<AshEweEntity> ASH_EWE;
	public static EntityType<CinderRamEntity> CINDER_RAM;
	public static EntityType<EmberLambEntity> EMBER_LAMB;
	public static EntityType<SootWetherEntity> SOOT_WETHER;
	public static EntityType<SmolderSheepEntity> SMOLDER_SHEEP;

	public static Item MAGMA_STRIDER_SPAWN_EGG;
	public static Item SOOT_STRIDER_SPAWN_EGG;
	public static Item BASALT_STRIDER_SPAWN_EGG;
	public static Item SLAG_STRIDER_SPAWN_EGG;
	public static Item OBSIDIAN_STRIDER_SPAWN_EGG;
	public static Item EMBER_GRAZER_SPAWN_EGG;
	public static Item ASH_YAK_SPAWN_EGG;
	public static Item MAGMA_OX_SPAWN_EGG;
	public static Item SLAG_BUFFALO_SPAWN_EGG;
	public static Item CINDER_AUROCHS_SPAWN_EGG;
	public static Item SOOT_HEN_SPAWN_EGG;
	public static Item CINDER_ROOSTER_SPAWN_EGG;
	public static Item EMBER_PULLET_SPAWN_EGG;
	public static Item ASH_FOWL_SPAWN_EGG;
	public static Item MAGMA_BANTAM_SPAWN_EGG;
	public static Item MAGMA_HOG_SPAWN_EGG;
	public static Item SOOT_SWINE_SPAWN_EGG;
	public static Item CINDER_BOAR_SPAWN_EGG;
	public static Item SLAG_SOW_SPAWN_EGG;
	public static Item EMBER_PORKER_SPAWN_EGG;
	public static Item ASH_EWE_SPAWN_EGG;
	public static Item CINDER_RAM_SPAWN_EGG;
	public static Item EMBER_LAMB_SPAWN_EGG;
	public static Item SOOT_WETHER_SPAWN_EGG;
	public static Item SMOLDER_SHEEP_SPAWN_EGG;

	public static Item MAGMA_CARAPACE;
	public static Item SOOT_BRISTLES;
	public static Item BASALT_SCALE;
	public static Item SLAG_HUSK;
	public static Item OBSIDIAN_PLATING;
	public static Item GRAZER_BRISKET;
	public static Item YAK_HAUNCH;
	public static Item OX_LOIN;
	public static Item BUFFALO_HUMP;
	public static Item AUROCHS_SHANK;
	public static Item HEN_DRUMSTICK;
	public static Item ROOSTER_WING;
	public static Item PULLET_BREAST;
	public static Item FOWL_GIBLETS;
	public static Item BANTAM_THIGH;
	public static Item HOG_BELLY;
	public static Item SWINE_HOCK;
	public static Item BOAR_SHOULDER;
	public static Item SOW_JOWL;
	public static Item PORKER_HAM;
	public static Item EWE_SHANK;
	public static Item RAM_RACK;
	public static Item LAMB_CUTLET;
	public static Item WETHER_RIBS;
	public static Item SMOLDER_FLEECE;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		registerSpawning();
		MoltenFaunaHandbook.register();
	}

	private static void registerEntityTypes() {
		// Dimensions/eye heights/attachments/tracking ranges copied 1:1 from the vanilla
		// EntityType registrations (1.21.9 bytecode):
		// strider = makeFireImmune().dimensions(0.9f, 1.7f).maxTrackingRange(10).
		// cow = dimensions(0.9f, 1.4f).eyeHeight(1.3f).passengerAttachments(1.36875f).maxTrackingRange(10).
		// chicken = dimensions(0.4f, 0.7f).eyeHeight(0.644f).passengerAttachments(new Vec3d(0.0, 0.7, -0.1)).maxTrackingRange(10).
		// pig = dimensions(0.9f, 0.9f).passengerAttachments(0.86875f).maxTrackingRange(10).
		// sheep = dimensions(0.9f, 1.3f).eyeHeight(1.235f).passengerAttachments(1.2375f).maxTrackingRange(10).
		MAGMA_STRIDER = ModEntities.register("magma_strider",
				EntityType.Builder.create(MagmaStriderEntity::new, SpawnGroup.CREATURE)
						.makeFireImmune()
						.dimensions(0.9f, 1.7f)
						.maxTrackingRange(10));

		SOOT_STRIDER = ModEntities.register("soot_strider",
				EntityType.Builder.create(SootStriderEntity::new, SpawnGroup.CREATURE)
						.makeFireImmune()
						.dimensions(0.9f, 1.7f)
						.maxTrackingRange(10));

		BASALT_STRIDER = ModEntities.register("basalt_strider",
				EntityType.Builder.create(BasaltStriderEntity::new, SpawnGroup.CREATURE)
						.makeFireImmune()
						.dimensions(0.9f, 1.7f)
						.maxTrackingRange(10));

		SLAG_STRIDER = ModEntities.register("slag_strider",
				EntityType.Builder.create(SlagStriderEntity::new, SpawnGroup.CREATURE)
						.makeFireImmune()
						.dimensions(0.9f, 1.7f)
						.maxTrackingRange(10));

		OBSIDIAN_STRIDER = ModEntities.register("obsidian_strider",
				EntityType.Builder.create(ObsidianStriderEntity::new, SpawnGroup.CREATURE)
						.makeFireImmune()
						.dimensions(0.9f, 1.7f)
						.maxTrackingRange(10));

		EMBER_GRAZER = ModEntities.register("ember_grazer",
				EntityType.Builder.create(EmberGrazerEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.4f)
						.eyeHeight(1.3f)
						.passengerAttachments(1.36875f)
						.maxTrackingRange(10));

		ASH_YAK = ModEntities.register("ash_yak",
				EntityType.Builder.create(AshYakEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.4f)
						.eyeHeight(1.3f)
						.passengerAttachments(1.36875f)
						.maxTrackingRange(10));

		MAGMA_OX = ModEntities.register("magma_ox",
				EntityType.Builder.create(MagmaOxEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.4f)
						.eyeHeight(1.3f)
						.passengerAttachments(1.36875f)
						.maxTrackingRange(10));

		SLAG_BUFFALO = ModEntities.register("slag_buffalo",
				EntityType.Builder.create(SlagBuffaloEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.4f)
						.eyeHeight(1.3f)
						.passengerAttachments(1.36875f)
						.maxTrackingRange(10));

		CINDER_AUROCHS = ModEntities.register("cinder_aurochs",
				EntityType.Builder.create(CinderAurochsEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.4f)
						.eyeHeight(1.3f)
						.passengerAttachments(1.36875f)
						.maxTrackingRange(10));

		SOOT_HEN = ModEntities.register("soot_hen",
				EntityType.Builder.create(SootHenEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.4f, 0.7f)
						.eyeHeight(0.644f)
						.passengerAttachments(new Vec3d(0.0, 0.7, -0.1))
						.maxTrackingRange(10));

		CINDER_ROOSTER = ModEntities.register("cinder_rooster",
				EntityType.Builder.create(CinderRoosterEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.4f, 0.7f)
						.eyeHeight(0.644f)
						.passengerAttachments(new Vec3d(0.0, 0.7, -0.1))
						.maxTrackingRange(10));

		EMBER_PULLET = ModEntities.register("ember_pullet",
				EntityType.Builder.create(EmberPulletEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.4f, 0.7f)
						.eyeHeight(0.644f)
						.passengerAttachments(new Vec3d(0.0, 0.7, -0.1))
						.maxTrackingRange(10));

		ASH_FOWL = ModEntities.register("ash_fowl",
				EntityType.Builder.create(AshFowlEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.4f, 0.7f)
						.eyeHeight(0.644f)
						.passengerAttachments(new Vec3d(0.0, 0.7, -0.1))
						.maxTrackingRange(10));

		MAGMA_BANTAM = ModEntities.register("magma_bantam",
				EntityType.Builder.create(MagmaBantamEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.4f, 0.7f)
						.eyeHeight(0.644f)
						.passengerAttachments(new Vec3d(0.0, 0.7, -0.1))
						.maxTrackingRange(10));

		MAGMA_HOG = ModEntities.register("magma_hog",
				EntityType.Builder.create(MagmaHogEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 0.9f)
						.passengerAttachments(0.86875f)
						.maxTrackingRange(10));

		SOOT_SWINE = ModEntities.register("soot_swine",
				EntityType.Builder.create(SootSwineEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 0.9f)
						.passengerAttachments(0.86875f)
						.maxTrackingRange(10));

		CINDER_BOAR = ModEntities.register("cinder_boar",
				EntityType.Builder.create(CinderBoarEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 0.9f)
						.passengerAttachments(0.86875f)
						.maxTrackingRange(10));

		SLAG_SOW = ModEntities.register("slag_sow",
				EntityType.Builder.create(SlagSowEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 0.9f)
						.passengerAttachments(0.86875f)
						.maxTrackingRange(10));

		EMBER_PORKER = ModEntities.register("ember_porker",
				EntityType.Builder.create(EmberPorkerEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 0.9f)
						.passengerAttachments(0.86875f)
						.maxTrackingRange(10));

		ASH_EWE = ModEntities.register("ash_ewe",
				EntityType.Builder.create(AshEweEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.3f)
						.eyeHeight(1.235f)
						.passengerAttachments(1.2375f)
						.maxTrackingRange(10));

		CINDER_RAM = ModEntities.register("cinder_ram",
				EntityType.Builder.create(CinderRamEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.3f)
						.eyeHeight(1.235f)
						.passengerAttachments(1.2375f)
						.maxTrackingRange(10));

		EMBER_LAMB = ModEntities.register("ember_lamb",
				EntityType.Builder.create(EmberLambEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.3f)
						.eyeHeight(1.235f)
						.passengerAttachments(1.2375f)
						.maxTrackingRange(10));

		SOOT_WETHER = ModEntities.register("soot_wether",
				EntityType.Builder.create(SootWetherEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.3f)
						.eyeHeight(1.235f)
						.passengerAttachments(1.2375f)
						.maxTrackingRange(10));

		SMOLDER_SHEEP = ModEntities.register("smolder_sheep",
				EntityType.Builder.create(SmolderSheepEntity::new, SpawnGroup.CREATURE)
						.dimensions(0.9f, 1.3f)
						.eyeHeight(1.235f)
						.passengerAttachments(1.2375f)
						.maxTrackingRange(10));
	}

	private static void registerAttributes() {
		// Vanilla create*Attributes() builders (verified via javap; createCowAttributes
		// lives on AbstractCowEntity in 1.21.9) plus per-mob tweaks; EntityAttributes
		// fields have no GENERIC_ prefix in 1.21.9 and Builder.add(...) overrides the
		// base value (same proven pattern as InfernoMobsFeature).
		FabricDefaultAttributeRegistry.register(MAGMA_STRIDER, StriderEntity.createStriderAttributes()
				.add(EntityAttributes.MAX_HEALTH, 24.0));
		FabricDefaultAttributeRegistry.register(SOOT_STRIDER, StriderEntity.createStriderAttributes()
				.add(EntityAttributes.MOVEMENT_SPEED, 0.2));
		FabricDefaultAttributeRegistry.register(BASALT_STRIDER, StriderEntity.createStriderAttributes()
				.add(EntityAttributes.MAX_HEALTH, 28.0)
				.add(EntityAttributes.SCALE, 1.1));
		FabricDefaultAttributeRegistry.register(SLAG_STRIDER, StriderEntity.createStriderAttributes()
				.add(EntityAttributes.MAX_HEALTH, 22.0));
		FabricDefaultAttributeRegistry.register(OBSIDIAN_STRIDER, StriderEntity.createStriderAttributes()
				.add(EntityAttributes.MAX_HEALTH, 30.0)
				.add(EntityAttributes.SCALE, 1.15));
		FabricDefaultAttributeRegistry.register(EMBER_GRAZER, AbstractCowEntity.createCowAttributes()
				.add(EntityAttributes.MAX_HEALTH, 12.0));
		FabricDefaultAttributeRegistry.register(ASH_YAK, AbstractCowEntity.createCowAttributes()
				.add(EntityAttributes.MAX_HEALTH, 16.0)
				.add(EntityAttributes.SCALE, 1.1));
		FabricDefaultAttributeRegistry.register(MAGMA_OX, AbstractCowEntity.createCowAttributes()
				.add(EntityAttributes.MAX_HEALTH, 20.0)
				.add(EntityAttributes.SCALE, 1.2));
		FabricDefaultAttributeRegistry.register(SLAG_BUFFALO, AbstractCowEntity.createCowAttributes()
				.add(EntityAttributes.MAX_HEALTH, 18.0)
				.add(EntityAttributes.SCALE, 1.15));
		FabricDefaultAttributeRegistry.register(CINDER_AUROCHS, AbstractCowEntity.createCowAttributes()
				.add(EntityAttributes.MAX_HEALTH, 22.0)
				.add(EntityAttributes.SCALE, 1.25));
		FabricDefaultAttributeRegistry.register(SOOT_HEN, ChickenEntity.createChickenAttributes()
				.add(EntityAttributes.MAX_HEALTH, 5.0));
		FabricDefaultAttributeRegistry.register(CINDER_ROOSTER, ChickenEntity.createChickenAttributes()
				.add(EntityAttributes.MAX_HEALTH, 6.0)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.3));
		FabricDefaultAttributeRegistry.register(EMBER_PULLET, ChickenEntity.createChickenAttributes()
				.add(EntityAttributes.SCALE, 0.9));
		FabricDefaultAttributeRegistry.register(ASH_FOWL, ChickenEntity.createChickenAttributes()
				.add(EntityAttributes.MAX_HEALTH, 5.0));
		FabricDefaultAttributeRegistry.register(MAGMA_BANTAM, ChickenEntity.createChickenAttributes()
				.add(EntityAttributes.SCALE, 0.8)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.3));
		FabricDefaultAttributeRegistry.register(MAGMA_HOG, PigEntity.createPigAttributes()
				.add(EntityAttributes.MAX_HEALTH, 14.0)
				.add(EntityAttributes.SCALE, 1.1));
		FabricDefaultAttributeRegistry.register(SOOT_SWINE, PigEntity.createPigAttributes()
				.add(EntityAttributes.MAX_HEALTH, 12.0));
		FabricDefaultAttributeRegistry.register(CINDER_BOAR, PigEntity.createPigAttributes()
				.add(EntityAttributes.MAX_HEALTH, 16.0)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.28));
		FabricDefaultAttributeRegistry.register(SLAG_SOW, PigEntity.createPigAttributes()
				.add(EntityAttributes.MAX_HEALTH, 14.0)
				.add(EntityAttributes.SCALE, 1.05));
		FabricDefaultAttributeRegistry.register(EMBER_PORKER, PigEntity.createPigAttributes()
				.add(EntityAttributes.MAX_HEALTH, 12.0)
				.add(EntityAttributes.SCALE, 1.15));
		FabricDefaultAttributeRegistry.register(ASH_EWE, SheepEntity.createSheepAttributes()
				.add(EntityAttributes.MAX_HEALTH, 10.0));
		FabricDefaultAttributeRegistry.register(CINDER_RAM, SheepEntity.createSheepAttributes()
				.add(EntityAttributes.MAX_HEALTH, 12.0)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.25));
		FabricDefaultAttributeRegistry.register(EMBER_LAMB, SheepEntity.createSheepAttributes()
				.add(EntityAttributes.SCALE, 0.85)
				.add(EntityAttributes.MOVEMENT_SPEED, 0.25));
		FabricDefaultAttributeRegistry.register(SOOT_WETHER, SheepEntity.createSheepAttributes()
				.add(EntityAttributes.MAX_HEALTH, 12.0)
				.add(EntityAttributes.SCALE, 1.1));
		FabricDefaultAttributeRegistry.register(SMOLDER_SHEEP, SheepEntity.createSheepAttributes()
				.add(EntityAttributes.MAX_HEALTH, 10.0));
	}

	private static void registerItems() {
		// Item.Settings.spawnEgg(type) stores the ENTITY_DATA component the vanilla
		// SpawnEggItem reads its entity type from in 1.21.9 (same proven pattern as
		// the infernomobs eggs).
		MAGMA_STRIDER_SPAWN_EGG = ModItems.register("magma_strider_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MAGMA_STRIDER));
		SOOT_STRIDER_SPAWN_EGG = ModItems.register("soot_strider_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_STRIDER));
		BASALT_STRIDER_SPAWN_EGG = ModItems.register("basalt_strider_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(BASALT_STRIDER));
		SLAG_STRIDER_SPAWN_EGG = ModItems.register("slag_strider_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_STRIDER));
		OBSIDIAN_STRIDER_SPAWN_EGG = ModItems.register("obsidian_strider_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(OBSIDIAN_STRIDER));
		EMBER_GRAZER_SPAWN_EGG = ModItems.register("ember_grazer_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_GRAZER));
		ASH_YAK_SPAWN_EGG = ModItems.register("ash_yak_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_YAK));
		MAGMA_OX_SPAWN_EGG = ModItems.register("magma_ox_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MAGMA_OX));
		SLAG_BUFFALO_SPAWN_EGG = ModItems.register("slag_buffalo_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_BUFFALO));
		CINDER_AUROCHS_SPAWN_EGG = ModItems.register("cinder_aurochs_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_AUROCHS));
		SOOT_HEN_SPAWN_EGG = ModItems.register("soot_hen_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_HEN));
		CINDER_ROOSTER_SPAWN_EGG = ModItems.register("cinder_rooster_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_ROOSTER));
		EMBER_PULLET_SPAWN_EGG = ModItems.register("ember_pullet_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_PULLET));
		ASH_FOWL_SPAWN_EGG = ModItems.register("ash_fowl_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_FOWL));
		MAGMA_BANTAM_SPAWN_EGG = ModItems.register("magma_bantam_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MAGMA_BANTAM));
		MAGMA_HOG_SPAWN_EGG = ModItems.register("magma_hog_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MAGMA_HOG));
		SOOT_SWINE_SPAWN_EGG = ModItems.register("soot_swine_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_SWINE));
		CINDER_BOAR_SPAWN_EGG = ModItems.register("cinder_boar_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_BOAR));
		SLAG_SOW_SPAWN_EGG = ModItems.register("slag_sow_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_SOW));
		EMBER_PORKER_SPAWN_EGG = ModItems.register("ember_porker_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_PORKER));
		ASH_EWE_SPAWN_EGG = ModItems.register("ash_ewe_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_EWE));
		CINDER_RAM_SPAWN_EGG = ModItems.register("cinder_ram_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_RAM));
		EMBER_LAMB_SPAWN_EGG = ModItems.register("ember_lamb_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_LAMB));
		SOOT_WETHER_SPAWN_EGG = ModItems.register("soot_wether_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_WETHER));
		SMOLDER_SHEEP_SPAWN_EGG = ModItems.register("smolder_sheep_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SMOLDER_SHEEP));

		MAGMA_CARAPACE = ModItems.register("magma_carapace", Item::new, new Item.Settings());
		SOOT_BRISTLES = ModItems.register("soot_bristles", Item::new, new Item.Settings());
		BASALT_SCALE = ModItems.register("basalt_scale", Item::new, new Item.Settings());
		SLAG_HUSK = ModItems.register("slag_husk", Item::new, new Item.Settings());
		OBSIDIAN_PLATING = ModItems.register("obsidian_plating", Item::new, new Item.Settings());
		GRAZER_BRISKET = ModItems.register("grazer_brisket", Item::new, new Item.Settings());
		YAK_HAUNCH = ModItems.register("yak_haunch", Item::new, new Item.Settings());
		OX_LOIN = ModItems.register("ox_loin", Item::new, new Item.Settings());
		BUFFALO_HUMP = ModItems.register("buffalo_hump", Item::new, new Item.Settings());
		AUROCHS_SHANK = ModItems.register("aurochs_shank", Item::new, new Item.Settings());
		HEN_DRUMSTICK = ModItems.register("hen_drumstick", Item::new, new Item.Settings());
		ROOSTER_WING = ModItems.register("rooster_wing", Item::new, new Item.Settings());
		PULLET_BREAST = ModItems.register("pullet_breast", Item::new, new Item.Settings());
		FOWL_GIBLETS = ModItems.register("fowl_giblets", Item::new, new Item.Settings());
		BANTAM_THIGH = ModItems.register("bantam_thigh", Item::new, new Item.Settings());
		HOG_BELLY = ModItems.register("hog_belly", Item::new, new Item.Settings());
		SWINE_HOCK = ModItems.register("swine_hock", Item::new, new Item.Settings());
		BOAR_SHOULDER = ModItems.register("boar_shoulder", Item::new, new Item.Settings());
		SOW_JOWL = ModItems.register("sow_jowl", Item::new, new Item.Settings());
		PORKER_HAM = ModItems.register("porker_ham", Item::new, new Item.Settings());
		EWE_SHANK = ModItems.register("ewe_shank", Item::new, new Item.Settings());
		RAM_RACK = ModItems.register("ram_rack", Item::new, new Item.Settings());
		LAMB_CUTLET = ModItems.register("lamb_cutlet", Item::new, new Item.Settings());
		WETHER_RIBS = ModItems.register("wether_ribs", Item::new, new Item.Settings());
		SMOLDER_FLEECE = ModItems.register("smolder_fleece", Item::new, new Item.Settings());

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			// Spawn eggs together, then the mob drops.
			entries.add(MAGMA_STRIDER_SPAWN_EGG);
			entries.add(SOOT_STRIDER_SPAWN_EGG);
			entries.add(BASALT_STRIDER_SPAWN_EGG);
			entries.add(SLAG_STRIDER_SPAWN_EGG);
			entries.add(OBSIDIAN_STRIDER_SPAWN_EGG);
			entries.add(EMBER_GRAZER_SPAWN_EGG);
			entries.add(ASH_YAK_SPAWN_EGG);
			entries.add(MAGMA_OX_SPAWN_EGG);
			entries.add(SLAG_BUFFALO_SPAWN_EGG);
			entries.add(CINDER_AUROCHS_SPAWN_EGG);
			entries.add(SOOT_HEN_SPAWN_EGG);
			entries.add(CINDER_ROOSTER_SPAWN_EGG);
			entries.add(EMBER_PULLET_SPAWN_EGG);
			entries.add(ASH_FOWL_SPAWN_EGG);
			entries.add(MAGMA_BANTAM_SPAWN_EGG);
			entries.add(MAGMA_HOG_SPAWN_EGG);
			entries.add(SOOT_SWINE_SPAWN_EGG);
			entries.add(CINDER_BOAR_SPAWN_EGG);
			entries.add(SLAG_SOW_SPAWN_EGG);
			entries.add(EMBER_PORKER_SPAWN_EGG);
			entries.add(ASH_EWE_SPAWN_EGG);
			entries.add(CINDER_RAM_SPAWN_EGG);
			entries.add(EMBER_LAMB_SPAWN_EGG);
			entries.add(SOOT_WETHER_SPAWN_EGG);
			entries.add(SMOLDER_SHEEP_SPAWN_EGG);
			entries.add(MAGMA_CARAPACE);
			entries.add(SOOT_BRISTLES);
			entries.add(BASALT_SCALE);
			entries.add(SLAG_HUSK);
			entries.add(OBSIDIAN_PLATING);
			entries.add(GRAZER_BRISKET);
			entries.add(YAK_HAUNCH);
			entries.add(OX_LOIN);
			entries.add(BUFFALO_HUMP);
			entries.add(AUROCHS_SHANK);
			entries.add(HEN_DRUMSTICK);
			entries.add(ROOSTER_WING);
			entries.add(PULLET_BREAST);
			entries.add(FOWL_GIBLETS);
			entries.add(BANTAM_THIGH);
			entries.add(HOG_BELLY);
			entries.add(SWINE_HOCK);
			entries.add(BOAR_SHOULDER);
			entries.add(SOW_JOWL);
			entries.add(PORKER_HAM);
			entries.add(EWE_SHANK);
			entries.add(RAM_RACK);
			entries.add(LAMB_CUTLET);
			entries.add(WETHER_RIBS);
			entries.add(SMOLDER_FLEECE);
		});
	}

	private static void registerSpawning() {
		// SpawnRestriction.register is private in vanilla but access-widened by Fabric's
		// transitive access wideners (same proven pattern as InfernoMobsFeature).
		// Locations/heightmaps mirror the vanilla entries (SpawnRestriction bytecode):
		// chicken/cow/pig/sheep use ON_GROUND + MOTION_BLOCKING_NO_LEAVES +
		// AnimalEntity::isValidNaturalSpawn, strider uses IN_LAVA +
		// MOTION_BLOCKING_NO_LEAVES + StriderEntity::canSpawn. Both vanilla predicates
		// are typed to the vanilla EntityTypes (and take WorldAccess), so they are
		// reimplemented 1:1 below (canInfernoAnimalSpawn / canInfernoStriderSpawn).
		SpawnRestriction.register(MAGMA_STRIDER, SpawnLocationTypes.IN_LAVA,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoStriderSpawn);
		SpawnRestriction.register(SOOT_STRIDER, SpawnLocationTypes.IN_LAVA,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoStriderSpawn);
		SpawnRestriction.register(BASALT_STRIDER, SpawnLocationTypes.IN_LAVA,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoStriderSpawn);
		SpawnRestriction.register(SLAG_STRIDER, SpawnLocationTypes.IN_LAVA,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoStriderSpawn);
		SpawnRestriction.register(OBSIDIAN_STRIDER, SpawnLocationTypes.IN_LAVA,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoStriderSpawn);
		SpawnRestriction.register(EMBER_GRAZER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(ASH_YAK, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(MAGMA_OX, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(SLAG_BUFFALO, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(CINDER_AUROCHS, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(SOOT_HEN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(CINDER_ROOSTER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(EMBER_PULLET, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(ASH_FOWL, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(MAGMA_BANTAM, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(MAGMA_HOG, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(SOOT_SWINE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(CINDER_BOAR, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(SLAG_SOW, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(EMBER_PORKER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(ASH_EWE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(CINDER_RAM, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(EMBER_LAMB, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(SOOT_WETHER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);
		SpawnRestriction.register(SMOLDER_SHEEP, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				MoltenFaunaFeature::canInfernoAnimalSpawn);

		// Natural spawns in the three Inferno biomes (biome JSONs are owned by the
		// infernodim feature; includeByKey simply matches nothing until they are loaded).
		Predicate<BiomeSelectionContext> infernoBiomes = BiomeSelectors.includeByKey(
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("cinder_wastes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("ember_grove")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("slag_sea")));
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, MAGMA_STRIDER, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SOOT_STRIDER, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, BASALT_STRIDER, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SLAG_STRIDER, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, OBSIDIAN_STRIDER, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, EMBER_GRAZER, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, ASH_YAK, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, MAGMA_OX, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SLAG_BUFFALO, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, CINDER_AUROCHS, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SOOT_HEN, 12, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, CINDER_ROOSTER, 12, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, EMBER_PULLET, 12, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, ASH_FOWL, 12, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, MAGMA_BANTAM, 12, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, MAGMA_HOG, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SOOT_SWINE, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, CINDER_BOAR, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SLAG_SOW, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, EMBER_PORKER, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, ASH_EWE, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, CINDER_RAM, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, EMBER_LAMB, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SOOT_WETHER, 10, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.CREATURE, SMOLDER_SHEEP, 10, 2, 4);
	}

	/**
	 * Mirrors vanilla {@code AnimalEntity.isValidNaturalSpawn} (verified against the 1.21.9
	 * bytecode; the vanilla method takes {@code WorldAccess} and cannot be used as a
	 * {@code SpawnRestriction.SpawnPredicate} method reference here without reimplementing
	 * the Inferno branch anyway): spawnable when the block below is ANIMALS_SPAWNABLE_ON and
	 * the light gate passes ({@code getBaseLightLevel(pos, 0) > 8}, skipped for trial-spawner
	 * spawns - {@code AnimalEntity.isLightLevelValidForNaturalSpawn} is protected, so its
	 * one-line body is inlined).
	 *
	 * <p>In the Inferno the ANIMALS_SPAWNABLE_ON gate would starve spawns entirely - the
	 * ground there is cinderstone/ash/ember soil/basalt/blackstone, none of which are in the
	 * tag (it only contains {@code minecraft:grass_block}) - so the Inferno branch keeps just
	 * the base {@code MobEntity.canMobSpawn} checks (same proven pattern as the ash bat).
	 */
	private static boolean canInfernoAnimalSpawn(EntityType<? extends AnimalEntity> type,
			ServerWorldAccess world, SpawnReason reason, BlockPos pos, Random random) {
		if (world.toServerWorld().getRegistryKey() == ModDimensions.INFERNO_WORLD) {
			return MobEntity.canMobSpawn(type, world, reason, pos, random);
		}
		boolean lightOk = SpawnReason.isTrialSpawner(reason) || world.getBaseLightLevel(pos, 0) > 8;
		return world.getBlockState(pos.down()).isIn(BlockTags.ANIMALS_SPAWNABLE_ON) && lightOk;
	}

	/**
	 * Mirrors vanilla {@code StriderEntity.canSpawn} (verified against the 1.21.9 bytecode;
	 * the vanilla method is typed to {@code EntityType<StriderEntity>} so it cannot be reused
	 * directly - same reimplementation as the cinder strider): walk upward through the lava
	 * column above the spawn pos, then require the first non-lava block to be air.
	 */
	private static boolean canInfernoStriderSpawn(EntityType<? extends StriderEntity> type,
			ServerWorldAccess world, SpawnReason reason, BlockPos pos, Random random) {
		BlockPos.Mutable mutable = pos.mutableCopy();
		do {
			mutable.move(Direction.UP);
		} while (world.getFluidState(mutable).isIn(FluidTags.LAVA));
		return world.getBlockState(mutable).isAir();
	}
}
