package net.sonic0810.copperinferno.feature.infernofoods;

import java.util.List;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.component.type.ConsumableComponent;
import net.minecraft.component.type.ConsumableComponents;
import net.minecraft.component.type.FoodComponent;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.item.consume.ApplyEffectsConsumeEffect;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * Foods and consumables sourced from the Inferno dimension: 9 items.
 *
 * <p>Follows the verified 1.21.9 consumable pattern from {@code feature/foods/FoodsFeature}:
 * {@link FoodComponent.Builder} for hunger/saturation, {@link ConsumableComponents#food()} /
 * {@link ConsumableComponents#drink()} builders carrying an {@link ApplyEffectsConsumeEffect},
 * and {@code Item.Settings.useRemainder(...)} for container-returning foods. The bowl food
 * mirrors the vanilla mushroom-stew registration verified from {@code net.minecraft.item.Items}
 * bytecode: {@code maxCount(1).food(...).useRemainder(Items.BOWL)}.
 *
 * <p>Assets (items/*.json + models/item/*.json + 16x16 textures), recipes
 * ({@code data/copper_inferno/recipe/infernofoods/}) and the lang fragments
 * ({@code lang/fragments/infernofoods.json} + {@code lang/fragments_de/infernofoods.json})
 * are generated by {@code devtools/gen/infernofoods_gen.py}.
 */
public final class InfernoFoodsFeature {
	private InfernoFoodsFeature() {
	}

	public static Item EMBER_BERRIES;
	public static Item ROASTED_EMBER_FUNGUS;
	public static Item ASH_BREAD;
	public static Item SMOLDER_STEW;
	public static Item CINDER_CANDY;
	public static Item STRIDER_ESCARGOT;
	public static Item INFERNIUM_APPLE;
	public static Item EMBER_JAM;
	public static Item BOTTLED_SMOKE;

	public static void init() {
		// ---- Plain foods ----
		EMBER_BERRIES = ModItems.register("ember_berries", Item::new, new Item.Settings()
				.food(food(2, 0.3f))); // raw dimension berries (sweet-berries-like)
		ROASTED_EMBER_FUNGUS = ModItems.register("roasted_ember_fungus", Item::new, new Item.Settings()
				.food(food(5, 0.6f)));
		ASH_BREAD = ModItems.register("ash_bread", Item::new, new Item.Settings()
				.food(food(5, 0.6f))); // bread-like
		CINDER_CANDY = ModItems.register("cinder_candy", Item::new, new Item.Settings()
				.food(alwaysEdibleFood(2, 0.2f))); // candy: nibble any time
		STRIDER_ESCARGOT = ModItems.register("strider_escargot", Item::new, new Item.Settings()
				.food(food(8, 0.8f))); // hearty delicacy

		// ---- Bowl food (vanilla mushroom-stew pattern: single stack, bowl handed back) ----
		SMOLDER_STEW = ModItems.register("smolder_stew", Item::new, new Item.Settings()
				.maxCount(1)
				.useRemainder(Items.BOWL)
				.food(food(6, 0.6f)));

		// ---- Golden-apple-like (always edible, effects via ApplyEffectsConsumeEffect) ----
		INFERNIUM_APPLE = ModItems.register("infernium_apple", Item::new, new Item.Settings()
				.rarity(Rarity.RARE)
				.food(alwaysEdibleFood(4, 1.2f), effectFood(
						new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 1200, 0), // Fire Resistance 60s
						new StatusEffectInstance(StatusEffects.ABSORPTION, 2400, 0)))); // Absorption I 120s

		// ---- Bottled foods (glass bottle handed back, honey-bottle-like stack of 16) ----
		EMBER_JAM = ModItems.register("ember_jam", Item::new, new Item.Settings()
				.maxCount(16)
				.useRemainder(Items.GLASS_BOTTLE)
				.food(food(4, 0.5f)));
		// Simplification: bottled smoke is a plain always-drinkable curio (1 nutrition, no
		// status effect, no custom smoke particles/fx - those would need client-side work).
		BOTTLED_SMOKE = ModItems.register("bottled_smoke", Item::new, new Item.Settings()
				.maxCount(16)
				.useRemainder(Items.GLASS_BOTTLE)
				.food(alwaysEdibleFood(1, 0.1f), ConsumableComponents.drink().build()));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.FOODS_KEY).register(entries -> {
			entries.add(EMBER_BERRIES);
			entries.add(ROASTED_EMBER_FUNGUS);
			entries.add(ASH_BREAD);
			entries.add(SMOLDER_STEW);
			entries.add(CINDER_CANDY);
			entries.add(STRIDER_ESCARGOT);
			entries.add(INFERNIUM_APPLE);
			entries.add(EMBER_JAM);
			entries.add(BOTTLED_SMOKE);
		});

		registerHandbookEntries();
	}

	private static FoodComponent food(int nutrition, float saturation) {
		return new FoodComponent.Builder().nutrition(nutrition).saturationModifier(saturation).build();
	}

	private static FoodComponent alwaysEdibleFood(int nutrition, float saturation) {
		return new FoodComponent.Builder().nutrition(nutrition).saturationModifier(saturation).alwaysEdible().build();
	}

	/** Standard eat consumable (vanilla golden-apple pattern) carrying the given effects. */
	private static ConsumableComponent effectFood(StatusEffectInstance... effects) {
		return ConsumableComponents.food()
				.consumeEffect(new ApplyEffectsConsumeEffect(List.of(effects)))
				.build();
	}

	private static void registerHandbookEntries() {
		final String BER = "copper_inferno:ember_berries";
		final String RST = "copper_inferno:roasted_ember_fungus";
		final String BRD = "copper_inferno:ash_bread";
		final String STW = "copper_inferno:smolder_stew";
		final String CND = "copper_inferno:cinder_candy";
		final String ESC = "copper_inferno:strider_escargot";
		final String APL = "copper_inferno:infernium_apple";
		final String JAM = "copper_inferno:ember_jam";
		final String SMK = "copper_inferno:bottled_smoke";
		final String FUN = "copper_inferno:ember_fungus";
		final String ASH = "copper_inferno:ash_pile";
		final String DUS = "copper_inferno:ember_dust";
		final String ING = "copper_inferno:infernium_ingot";

		// Overview page for all 9 Inferno foods.
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_overview",
				APL, null, null, null, 0,
				"The Inferno dimension feeds the brave: Ember Berries (break a Cinder Nest in the Inferno to harvest 2-4) eaten raw or roasted into Roasted Ember Fungus, Ash Bread, warming Smolder Stew (bowl comes back), Cinder Candy, hearty Strider Escargot, Ember Jam and Bottled Smoke in returnable bottles - and the Infernium Apple, which grants Fire Resistance and Absorption like a golden apple of the deep.",
				"Die Inferno-Dimension ern\u00e4hrt die Mutigen: Glutbeeren (ein Schlackennest im Inferno abbauen ergibt 2-4) roh oder als Ger\u00f6steter Glutpilz, Aschebrot, w\u00e4rmender Schweleintopf (die Sch\u00fcssel kommt zur\u00fcck), Zinderbonbons, deftiges Schreiter-Escargot, Glutmarmelade und Rauchflaschen in Pfandflaschen - und der Infernium-Apfel, der wie ein goldener Apfel der Tiefe Feuerschutz und Absorption verleiht."));

		// ----- cooking
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_roasted_ember_fungus",
				RST, "infernofoods/roasted_ember_fungus",
				new String[]{"", "", "", "", BER, "", "", "", ""}, RST, 1,
				"Smelt Ember Berries (or an Ember Fungus) in a furnace into Roasted Ember Fungus.",
				"Glutbeeren (oder einen Glutpilz) im Ofen zu Ger\u00f6stetem Glutpilz r\u00f6sten."));
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_roasted_ember_fungus_from_smoking",
				RST, "infernofoods/roasted_ember_fungus_from_smoking",
				new String[]{"", "", "", "", FUN, "", "", "", ""}, RST, 1,
				"A smoker roasts Ember Berries and Ember Fungus twice as fast.",
				"Ein R\u00e4ucherofen r\u00f6stet Glutbeeren und Glutpilze doppelt so schnell."));

		// ----- crafting
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_ash_bread",
				BRD, "infernofoods/ash_bread",
				new String[]{"", "", "", "minecraft:wheat", ASH, "minecraft:wheat", "", "", ""}, BRD, 1,
				"Wheat kneaded around an Ash Pile bakes into smoky Ash Bread.",
				"Weizen um einen Aschehaufen geknetet ergibt rauchiges Aschebrot."));
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_smolder_stew",
				STW, "infernofoods/smolder_stew",
				new String[]{RST, BER, "", "minecraft:bowl", "", "", "", "", ""}, STW, 1,
				"Roasted Ember Fungus and Ember Berries in a bowl make Smolder Stew; the bowl is returned when eaten.",
				"Ger\u00f6steter Glutpilz und Glutbeeren in einer Sch\u00fcssel ergeben Schweleintopf; die Sch\u00fcssel gibt es beim Essen zur\u00fcck."));
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_cinder_candy",
				CND, "infernofoods/cinder_candy",
				new String[]{"minecraft:sugar", "minecraft:sugar", "", DUS, "", "", "", "", ""}, CND, 3,
				"Sugar rolled in Ember Dust hardens into three Cinder Candies - a snack you can nibble any time.",
				"Zucker in Glutstaub gerollt wird zu drei Zinderbonbons - ein Snack f\u00fcr zwischendurch."));
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_strider_escargot",
				ESC, "infernofoods/strider_escargot",
				new String[]{"minecraft:string", "minecraft:string", "", RST, "", "", "", "", ""}, ESC, 1,
				"Strider strings wrapped around Roasted Ember Fungus: the Inferno delicacy Strider Escargot.",
				"Schreiterf\u00e4den um Ger\u00f6steten Glutpilz gewickelt: die Inferno-Delikatesse Schreiter-Escargot."));
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_infernium_apple",
				APL, "infernofoods/infernium_apple",
				new String[]{ING, ING, ING, ING, "minecraft:apple", ING, ING, ING, ING}, APL, 1,
				"An apple in a ring of Infernium Ingots becomes the Infernium Apple: 60s Fire Resistance and 2min Absorption, edible any time.",
				"Ein Apfel im Ring aus Infernium-Barren wird zum Infernium-Apfel: 60s Feuerschutz und 2min Absorption, jederzeit essbar."));
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_ember_jam",
				JAM, "infernofoods/ember_jam",
				new String[]{BER, BER, "", "minecraft:sugar", "minecraft:glass_bottle", "", "", "", ""}, JAM, 1,
				"Two Ember Berries and sugar cooked into a bottle: Ember Jam. The bottle is returned when eaten.",
				"Zwei Glutbeeren und Zucker in eine Flasche eingekocht: Glutmarmelade. Die Flasche gibt es beim Essen zur\u00fcck."));
		HandbookEntries.add(new HandbookEntry("items", "infernofoods_bottled_smoke",
				SMK, "infernofoods/bottled_smoke",
				new String[]{"minecraft:glass_bottle", ASH, "minecraft:charcoal", "", "", "", "", "", ""}, SMK, 1,
				"Ash and charcoal fumes caught in a bottle: Bottled Smoke, a barely nourishing curio you can sip any time.",
				"Asche- und Holzkohlenschwaden in einer Flasche gefangen: die Rauchflasche, ein kaum nahrhaftes Kuriosum f\u00fcr zwischendurch."));
	}
}
