package net.sonic0810.copperinferno.feature.fishing;

import java.util.List;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.loot.v3.LootTableEvents;
import net.minecraft.component.type.ConsumableComponents;
import net.minecraft.component.type.FoodComponent;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.Item;
import net.minecraft.item.consume.ApplyEffectsConsumeEffect;
import net.minecraft.loot.LootTables;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4.1 "Fishing": four fishing finds injected into the VANILLA fishing loot tables via
 * {@link LootTableEvents#MODIFY} (fabric-loot-api-v3) — never by editing vanilla JSON.
 * Junk hauls ({@code minecraft:gameplay/fishing/junk}) can reel in a Rusted Copper Ring or
 * edible Fizzy Kelp (weight 10 each, competing with the vanilla junk weights inside the
 * table's single pool via {@code LootTable.Builder.modifyPools}); treasure catches
 * ({@code minecraft:gameplay/fishing/treasure}) add the Verdigris Pearl and the Ancient
 * Copper Coin (weight 5 each).
 *
 * <p>AUDIT CONTRACT: all four {@code ModItems.register} call sites below pass the id as a
 * string LITERAL so {@code devtools/audit_assets.py} check (f) can see them. Assets
 * (items/*.json + models/item/*.json + 16x16 textures) and the lang fragments
 * ({@code lang/fragments{,_de}/fishing.json}) are generated by
 * {@code devtools/gen/fishing_gen.py}.
 *
 * <p>The {@link FoodComponent} setup for Fizzy Kelp copies the verified 1.21.9 consumable
 * pattern from {@code feature/foods/FoodsFeature} (FoodComponent.Builder +
 * ConsumableComponents.food() carrying an ApplyEffectsConsumeEffect).
 */
public final class FishingFeature {
	private FishingFeature() {
	}

	public static Item VERDIGRIS_PEARL;
	public static Item RUSTED_COPPER_RING;
	public static Item ANCIENT_COPPER_COIN;
	public static Item FIZZY_KELP;

	public static void init() {
		VERDIGRIS_PEARL = ModItems.register("verdigris_pearl", Item::new, new Item.Settings()
				.maxCount(16)
				.rarity(Rarity.UNCOMMON));
		RUSTED_COPPER_RING = ModItems.register("rusted_copper_ring", Item::new, new Item.Settings());
		ANCIENT_COPPER_COIN = ModItems.register("ancient_copper_coin", Item::new, new Item.Settings());
		FIZZY_KELP = ModItems.register("fizzy_kelp", Item::new, new Item.Settings()
				.food(
						new FoodComponent.Builder().nutrition(2).saturationModifier(0.3f).build(),
						ConsumableComponents.food()
								.consumeEffect(new ApplyEffectsConsumeEffect(List.of(
										new StatusEffectInstance(StatusEffects.SPEED, 100, 0)))) // Speed I 5s
								.build()));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			entries.add(VERDIGRIS_PEARL);
			entries.add(RUSTED_COPPER_RING);
			entries.add(ANCIENT_COPPER_COIN);
			entries.add(FIZZY_KELP);
		});

		// Signature verified via javap against fabric-loot-api-v3 2.0.11 (LootTableEvents$Modify.
		// modifyLootTable(RegistryKey<LootTable>, LootTable$Builder, LootTableSource,
		// RegistryWrapper$WrapperLookup)); modifyPools comes from FabricLootTableBuilder
		// (interface-injected into LootTable.Builder) and appends our weighted entries to the
		// table's existing pool so they compete with the vanilla entry weights.
		LootTableEvents.MODIFY.register((key, tableBuilder, source, registries) -> {
			if (LootTables.FISHING_JUNK_GAMEPLAY.equals(key)) {
				tableBuilder.modifyPools(pool -> pool
						.with(ItemEntry.builder(RUSTED_COPPER_RING).weight(10))
						.with(ItemEntry.builder(FIZZY_KELP).weight(10)));
			} else if (LootTables.FISHING_TREASURE_GAMEPLAY.equals(key)) {
				tableBuilder.modifyPools(pool -> pool
						.with(ItemEntry.builder(VERDIGRIS_PEARL).weight(5))
						.with(ItemEntry.builder(ANCIENT_COPPER_COIN).weight(5)));
			}
		});

		HandbookEntries.add(new HandbookEntry("items", "fishing_finds",
				"copper_inferno:verdigris_pearl", null, null, null, 0,
				"Cast a line: the waters hide four fishing finds. Junk hauls can reel in a Rusted Copper Ring or a snackable Fizzy Kelp (a quick bite with a short speed fizz), while treasure catches gleam with Verdigris Pearls and Ancient Copper Coins.",
				"Wirf die Angel aus: In den Gew\u00e4ssern verbergen sich vier Angelfunde. Tr\u00f6delf\u00e4nge bringen einen Rostigen Kupferring oder essbaren Sprudel-Seetang (ein schneller Happen mit kurzem Tempo-Prickeln), w\u00e4hrend Schatzf\u00e4nge mit Gr\u00fcnspanperlen und Alten Kupferm\u00fcnzen gl\u00e4nzen."));
	}
}
