package net.sonic0810.copperinferno.feature.bosslords.client;

import net.minecraft.client.render.entity.BlazeEntityRenderer;
import net.minecraft.client.render.entity.EntityRendererFactories;
import net.minecraft.client.render.entity.EntityRendererFactory;
import net.minecraft.client.render.entity.GhastEntityRenderer;
import net.minecraft.client.render.entity.IronGolemEntityRenderer;
import net.minecraft.client.render.entity.RavagerEntityRenderer;
import net.minecraft.client.render.entity.SkeletonEntityRenderer;
import net.minecraft.client.render.entity.state.GhastEntityRenderState;
import net.minecraft.client.render.entity.state.IronGolemEntityRenderState;
import net.minecraft.client.render.entity.state.LivingEntityRenderState;
import net.minecraft.client.render.entity.state.RavagerEntityRenderState;
import net.minecraft.client.render.entity.state.SkeletonEntityRenderState;
import net.minecraft.util.Identifier;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.feature.bosslords.BossLordsFeature;

/**
 * Client-side setup for the six Inferno Lords: every boss reuses its vanilla renderer
 * subclassed ONLY to swap the texture - each subclass overrides the renderer's
 * {@code getTexture(<state>)} (exact state parameter type verified via javap per renderer:
 * IronGolemEntityRenderState for the golem bosses, LivingEntityRenderState for the blaze,
 * GhastEntityRenderState / SkeletonEntityRenderState / RavagerEntityRenderState for the
 * rest) to return a recolored copy of the vanilla entity texture generated by
 * {@code devtools/gen/bosslords_gen.py} into
 * {@code assets/copper_inferno/textures/entity/bosslords/}. All vanilla renderer ctors used
 * here are Context-only (javap-verified); the bosses extend the matching vanilla entities,
 * so the factories fit the {@code register(EntityType<? extends T>, EntityRendererFactory<T>)}
 * bound (the infernofauna-proven pattern).
 */
public final class BossLordsFeatureClient {
	private BossLordsFeatureClient() {
	}

	private static Identifier tex(String boss) {
		return CopperInferno.id("textures/entity/bosslords/" + boss + ".png");
	}

	public static void initClient() {
		EntityRendererFactories.register(BossLordsFeature.THE_SLAG_KING,
				ctx -> new BossGolemRenderer(ctx, tex("the_slag_king")));
		EntityRendererFactories.register(BossLordsFeature.EMBER_MATRIARCH, EmberMatriarchRenderer::new);
		EntityRendererFactories.register(BossLordsFeature.ASH_COLOSSUS,
				ctx -> new BossGolemRenderer(ctx, tex("ash_colossus")));
		EntityRendererFactories.register(BossLordsFeature.MAGMA_LEVIATHAN, MagmaLeviathanRenderer::new);
		EntityRendererFactories.register(BossLordsFeature.CINDER_REAPER, CinderReaperRenderer::new);
		EntityRendererFactories.register(BossLordsFeature.FORGE_TYRANT, ForgeTyrantRenderer::new);
	}

	/** Shared by The Slag King and the Ash Colossus (both iron-golem based). */
	private static final class BossGolemRenderer extends IronGolemEntityRenderer {
		private final Identifier texture;

		BossGolemRenderer(EntityRendererFactory.Context context, Identifier texture) {
			super(context);
			this.texture = texture;
		}

		@Override
		public Identifier getTexture(IronGolemEntityRenderState state) {
			return texture;
		}
	}

	private static final class EmberMatriarchRenderer extends BlazeEntityRenderer {
		private static final Identifier TEXTURE = tex("ember_matriarch");

		EmberMatriarchRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(LivingEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class MagmaLeviathanRenderer extends GhastEntityRenderer {
		private static final Identifier TEXTURE = tex("magma_leviathan");

		MagmaLeviathanRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(GhastEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class CinderReaperRenderer extends SkeletonEntityRenderer {
		private static final Identifier TEXTURE = tex("cinder_reaper");

		CinderReaperRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(SkeletonEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class ForgeTyrantRenderer extends RavagerEntityRenderer {
		private static final Identifier TEXTURE = tex("forge_tyrant");

		ForgeTyrantRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(RavagerEntityRenderState state) {
			return TEXTURE;
		}
	}
}
