package net.sonic0810.copperinferno.feature.emberswarm;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.SilverfishEntity;
import net.minecraft.world.World;

/**
 * A swarm silverfish. Behavior is vanilla silverfish minus the block
 * infestation AI (see {@link #initGoals()}); stats come from
 * {@link EmberSwarmFeature}. Drops are in
 * {@code loot_table/entities/ash_silverfish.json}.
 * Generated by {@code devtools/gen/emberswarm_gen.py}.
 */
public class AshSilverfishEntity extends SilverfishEntity {
	public AshSilverfishEntity(EntityType<? extends SilverfishEntity> type, World world) {
		super(type, world);
	}

	@Override
	protected void initGoals() {
		super.initGoals();
		// Swarm silverfish do not infest blocks: drop the two inherited infestation
		// goals vanilla SilverfishEntity.initGoals adds (CallForHelpGoal +
		// WanderAndInfestGoal, both PRIVATE inner classes of SilverfishEntity),
		// matched via their declaring class exactly like the proven
		// SlagCrawlerEntity (infernomobs).
		this.goalSelector.clear(goal -> goal.getClass().getDeclaringClass() == SilverfishEntity.class);
	}
}
