package net.sonic0810.copperinferno.feature.emberswarm;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.BlazeEntity;
import net.minecraft.world.World;

/**
 * A swarm blaze of the Inferno dimension. Behavior is pure vanilla blaze; the
 * stat distinction comes from the default attributes registered in
 * {@link EmberSwarmFeature}. Drops are in
 * {@code loot_table/entities/cinder_blaze.json}.
 * Generated by {@code devtools/gen/emberswarm_gen.py}.
 */
public class CinderBlazeEntity extends BlazeEntity {
	public CinderBlazeEntity(EntityType<? extends BlazeEntity> type, World world) {
		super(type, world);
	}
}
