package net.sonic0810.copperinferno.feature.emberswarm;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.EndermiteEntity;
import net.minecraft.world.World;

/**
 * A swarm endermite. Behavior is pure vanilla endermite; stats come from
 * {@link EmberSwarmFeature}. Drops are in
 * {@code loot_table/entities/ember_mite.json}.
 * Generated by {@code devtools/gen/emberswarm_gen.py}.
 */
public class EmberMiteEntity extends EndermiteEntity {
	public EmberMiteEntity(EntityType<? extends EndermiteEntity> type, World world) {
		super(type, world);
	}
}
