package net.sonic0810.copperinferno.feature.emberswarm;

import java.util.function.Predicate;

import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.SpawnLocationTypes;
import net.minecraft.entity.SpawnReason;
import net.minecraft.entity.SpawnRestriction;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.mob.BlazeEntity;
import net.minecraft.entity.mob.EndermiteEntity;
import net.minecraft.entity.mob.HostileEntity;
import net.minecraft.entity.mob.MagmaCubeEntity;
import net.minecraft.entity.mob.SilverfishEntity;
import net.minecraft.entity.mob.VexEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.random.Random;
import net.minecraft.world.Difficulty;
import net.minecraft.world.Heightmap;
import net.minecraft.world.ServerWorldAccess;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * The Ember Swarm: 25 swarm-sized hostile mobs native to the Inferno dimension, five
 * each on the vanilla Blaze / MagmaCube / Silverfish / Vex / Endermite bases. Every mob
 * is a thin subclass reusing the vanilla renderer (see {@code EmberSwarmFeatureClient});
 * EntityType dimensions/eye heights/attachments are copied from the vanilla
 * {@code EntityType} registrations (verified via bytecode). Spawn eggs, mob-drop items,
 * natural spawns in the three Inferno biomes and drop recipes are registered here;
 * handbook pages live in {@link EmberSwarmHandbook}. Generated by
 * {@code devtools/gen/emberswarm_gen.py} - do not edit by hand.
 */
public final class EmberSwarmFeature {
	private EmberSwarmFeature() {
	}

	public static EntityType<EmberBlazeEntity> EMBER_BLAZE;
	public static EntityType<SootBlazeEntity> SOOT_BLAZE;
	public static EntityType<PyreBlazeEntity> PYRE_BLAZE;
	public static EntityType<CinderBlazeEntity> CINDER_BLAZE;
	public static EntityType<SlagfireBlazeEntity> SLAGFIRE_BLAZE;
	public static EntityType<MoltenCubeEntity> MOLTEN_CUBE;
	public static EntityType<EmberCubeEntity> EMBER_CUBE;
	public static EntityType<SootCubeEntity> SOOT_CUBE;
	public static EntityType<ScoriaCubeEntity> SCORIA_CUBE;
	public static EntityType<PyroclastCubeEntity> PYROCLAST_CUBE;
	public static EntityType<CinderSilverfishEntity> CINDER_SILVERFISH;
	public static EntityType<AshSilverfishEntity> ASH_SILVERFISH;
	public static EntityType<EmberSilverfishEntity> EMBER_SILVERFISH;
	public static EntityType<SootSilverfishEntity> SOOT_SILVERFISH;
	public static EntityType<SlagSilverfishEntity> SLAG_SILVERFISH;
	public static EntityType<FlameVexEntity> FLAME_VEX;
	public static EntityType<EmberVexEntity> EMBER_VEX;
	public static EntityType<CinderVexEntity> CINDER_VEX;
	public static EntityType<SmokeVexEntity> SMOKE_VEX;
	public static EntityType<SparkVexEntity> SPARK_VEX;
	public static EntityType<AshMiteEntity> ASH_MITE;
	public static EntityType<EmberMiteEntity> EMBER_MITE;
	public static EntityType<CinderMiteEntity> CINDER_MITE;
	public static EntityType<SootMiteEntity> SOOT_MITE;
	public static EntityType<SlagMiteEntity> SLAG_MITE;

	public static Item EMBER_BLAZE_SPAWN_EGG;
	public static Item SOOT_BLAZE_SPAWN_EGG;
	public static Item PYRE_BLAZE_SPAWN_EGG;
	public static Item CINDER_BLAZE_SPAWN_EGG;
	public static Item SLAGFIRE_BLAZE_SPAWN_EGG;
	public static Item MOLTEN_CUBE_SPAWN_EGG;
	public static Item EMBER_CUBE_SPAWN_EGG;
	public static Item SOOT_CUBE_SPAWN_EGG;
	public static Item SCORIA_CUBE_SPAWN_EGG;
	public static Item PYROCLAST_CUBE_SPAWN_EGG;
	public static Item CINDER_SILVERFISH_SPAWN_EGG;
	public static Item ASH_SILVERFISH_SPAWN_EGG;
	public static Item EMBER_SILVERFISH_SPAWN_EGG;
	public static Item SOOT_SILVERFISH_SPAWN_EGG;
	public static Item SLAG_SILVERFISH_SPAWN_EGG;
	public static Item FLAME_VEX_SPAWN_EGG;
	public static Item EMBER_VEX_SPAWN_EGG;
	public static Item CINDER_VEX_SPAWN_EGG;
	public static Item SMOKE_VEX_SPAWN_EGG;
	public static Item SPARK_VEX_SPAWN_EGG;
	public static Item ASH_MITE_SPAWN_EGG;
	public static Item EMBER_MITE_SPAWN_EGG;
	public static Item CINDER_MITE_SPAWN_EGG;
	public static Item SOOT_MITE_SPAWN_EGG;
	public static Item SLAG_MITE_SPAWN_EGG;

	public static Item EMBER_BLAZE_ROD;
	public static Item SOOT_PLUME;
	public static Item PYRE_ASH;
	public static Item CINDER_SPARK;
	public static Item SLAGFIRE_DROPLET;
	public static Item MOLTEN_GLOBULE;
	public static Item EMBER_GLOBULE;
	public static Item SOOT_GLOBULE;
	public static Item SCORIA_CHUNK;
	public static Item PYROCLAST_SHARD;
	public static Item CINDER_CHITIN;
	public static Item ASH_CHITIN;
	public static Item EMBER_CHITIN;
	public static Item SOOT_CHITIN;
	public static Item SLAG_CHITIN;
	public static Item FLAME_ESSENCE;
	public static Item EMBER_ESSENCE;
	public static Item CINDER_ESSENCE;
	public static Item SMOKE_ESSENCE;
	public static Item SPARK_ESSENCE;
	public static Item ASH_MITE_HUSK;
	public static Item EMBER_MITE_HUSK;
	public static Item CINDER_MITE_HUSK;
	public static Item SOOT_MITE_HUSK;
	public static Item SLAG_MITE_HUSK;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		registerSpawning();
		EmberSwarmHandbook.register();
	}

	private static void registerEntityTypes() {
		// Dimensions/eye heights/attachments/tracking ranges copied from the vanilla
		// EntityType registrations (bytecode-verified, same method as infernomobs).
		// blaze = makeFireImmune().dimensions(0.6f, 1.8f).maxTrackingRange(8).notAllowedInPeaceful().
		EMBER_BLAZE = ModEntities.register("ember_blaze",
				EntityType.Builder.create(EmberBlazeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.8f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SOOT_BLAZE = ModEntities.register("soot_blaze",
				EntityType.Builder.create(SootBlazeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.8f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		PYRE_BLAZE = ModEntities.register("pyre_blaze",
				EntityType.Builder.create(PyreBlazeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.8f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		CINDER_BLAZE = ModEntities.register("cinder_blaze",
				EntityType.Builder.create(CinderBlazeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.8f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SLAGFIRE_BLAZE = ModEntities.register("slagfire_blaze",
				EntityType.Builder.create(SlagfireBlazeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.6f, 1.8f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// magma_cube = makeFireImmune().dimensions(0.52f, 0.52f).eyeHeight(0.325f).spawnBoxScale(4.0f)
		// .maxTrackingRange(8).notAllowedInPeaceful(); size handling is inherited from SlimeEntity.
		MOLTEN_CUBE = ModEntities.register("molten_cube",
				EntityType.Builder.create(MoltenCubeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.52f, 0.52f)
						.eyeHeight(0.325f)
						.spawnBoxScale(4.0f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		EMBER_CUBE = ModEntities.register("ember_cube",
				EntityType.Builder.create(EmberCubeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.52f, 0.52f)
						.eyeHeight(0.325f)
						.spawnBoxScale(4.0f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SOOT_CUBE = ModEntities.register("soot_cube",
				EntityType.Builder.create(SootCubeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.52f, 0.52f)
						.eyeHeight(0.325f)
						.spawnBoxScale(4.0f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SCORIA_CUBE = ModEntities.register("scoria_cube",
				EntityType.Builder.create(ScoriaCubeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.52f, 0.52f)
						.eyeHeight(0.325f)
						.spawnBoxScale(4.0f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		PYROCLAST_CUBE = ModEntities.register("pyroclast_cube",
				EntityType.Builder.create(PyroclastCubeEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.52f, 0.52f)
						.eyeHeight(0.325f)
						.spawnBoxScale(4.0f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// silverfish = dimensions(0.4f, 0.3f).eyeHeight(0.13f).passengerAttachments(0.2375f)
		// .maxTrackingRange(8).notAllowedInPeaceful().
		CINDER_SILVERFISH = ModEntities.register("cinder_silverfish",
				EntityType.Builder.create(CinderSilverfishEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		ASH_SILVERFISH = ModEntities.register("ash_silverfish",
				EntityType.Builder.create(AshSilverfishEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		EMBER_SILVERFISH = ModEntities.register("ember_silverfish",
				EntityType.Builder.create(EmberSilverfishEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SOOT_SILVERFISH = ModEntities.register("soot_silverfish",
				EntityType.Builder.create(SootSilverfishEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SLAG_SILVERFISH = ModEntities.register("slag_silverfish",
				EntityType.Builder.create(SlagSilverfishEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// vex = makeFireImmune().dimensions(0.4f, 0.8f).eyeHeight(0.51875f).passengerAttachments(0.7375f)
		// .vehicleAttachment(0.04f).maxTrackingRange(8).notAllowedInPeaceful().
		FLAME_VEX = ModEntities.register("flame_vex",
				EntityType.Builder.create(FlameVexEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.4f, 0.8f)
						.eyeHeight(0.51875f)
						.passengerAttachments(0.7375f)
						.vehicleAttachment(0.04f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		EMBER_VEX = ModEntities.register("ember_vex",
				EntityType.Builder.create(EmberVexEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.4f, 0.8f)
						.eyeHeight(0.51875f)
						.passengerAttachments(0.7375f)
						.vehicleAttachment(0.04f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		CINDER_VEX = ModEntities.register("cinder_vex",
				EntityType.Builder.create(CinderVexEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.4f, 0.8f)
						.eyeHeight(0.51875f)
						.passengerAttachments(0.7375f)
						.vehicleAttachment(0.04f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SMOKE_VEX = ModEntities.register("smoke_vex",
				EntityType.Builder.create(SmokeVexEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.4f, 0.8f)
						.eyeHeight(0.51875f)
						.passengerAttachments(0.7375f)
						.vehicleAttachment(0.04f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SPARK_VEX = ModEntities.register("spark_vex",
				EntityType.Builder.create(SparkVexEntity::new, SpawnGroup.MONSTER)
						.makeFireImmune()
						.dimensions(0.4f, 0.8f)
						.eyeHeight(0.51875f)
						.passengerAttachments(0.7375f)
						.vehicleAttachment(0.04f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		// endermite = dimensions(0.4f, 0.3f).eyeHeight(0.13f).passengerAttachments(0.2375f)
		// .maxTrackingRange(8).notAllowedInPeaceful().
		ASH_MITE = ModEntities.register("ash_mite",
				EntityType.Builder.create(AshMiteEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		EMBER_MITE = ModEntities.register("ember_mite",
				EntityType.Builder.create(EmberMiteEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		CINDER_MITE = ModEntities.register("cinder_mite",
				EntityType.Builder.create(CinderMiteEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SOOT_MITE = ModEntities.register("soot_mite",
				EntityType.Builder.create(SootMiteEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
		SLAG_MITE = ModEntities.register("slag_mite",
				EntityType.Builder.create(SlagMiteEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.4f, 0.3f)
						.eyeHeight(0.13f)
						.passengerAttachments(0.2375f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
	}

	private static void registerAttributes() {
		// EntityAttributes fields have no GENERIC_ prefix in 1.21.9 (verified via
		// javap); DefaultAttributeContainer.Builder.add(...) overrides base values.
		// The magma-cube types stay on the plain vanilla builder because
		// SlimeEntity.setSize overrides health/speed/damage per size (like
		// infernomobs' molten_slagling).
		FabricDefaultAttributeRegistry.register(EMBER_BLAZE, BlazeEntity.createBlazeAttributes()
				.add(EntityAttributes.SCALE, 0.9)
				.add(EntityAttributes.MAX_HEALTH, 16.0));
		FabricDefaultAttributeRegistry.register(SOOT_BLAZE, BlazeEntity.createBlazeAttributes()
				.add(EntityAttributes.SCALE, 0.95)
				.add(EntityAttributes.MAX_HEALTH, 18.0));
		FabricDefaultAttributeRegistry.register(PYRE_BLAZE, BlazeEntity.createBlazeAttributes()
				.add(EntityAttributes.SCALE, 1.05)
				.add(EntityAttributes.MAX_HEALTH, 22.0));
		FabricDefaultAttributeRegistry.register(CINDER_BLAZE, BlazeEntity.createBlazeAttributes()
				.add(EntityAttributes.SCALE, 1.0)
				.add(EntityAttributes.MAX_HEALTH, 20.0));
		FabricDefaultAttributeRegistry.register(SLAGFIRE_BLAZE, BlazeEntity.createBlazeAttributes()
				.add(EntityAttributes.SCALE, 1.1)
				.add(EntityAttributes.MAX_HEALTH, 24.0));
		FabricDefaultAttributeRegistry.register(MOLTEN_CUBE, MagmaCubeEntity.createMagmaCubeAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_CUBE, MagmaCubeEntity.createMagmaCubeAttributes());
		FabricDefaultAttributeRegistry.register(SOOT_CUBE, MagmaCubeEntity.createMagmaCubeAttributes());
		FabricDefaultAttributeRegistry.register(SCORIA_CUBE, MagmaCubeEntity.createMagmaCubeAttributes());
		FabricDefaultAttributeRegistry.register(PYROCLAST_CUBE, MagmaCubeEntity.createMagmaCubeAttributes());
		FabricDefaultAttributeRegistry.register(CINDER_SILVERFISH, SilverfishEntity.createSilverfishAttributes()
				.add(EntityAttributes.SCALE, 1.1)
				.add(EntityAttributes.MAX_HEALTH, 10.0));
		FabricDefaultAttributeRegistry.register(ASH_SILVERFISH, SilverfishEntity.createSilverfishAttributes()
				.add(EntityAttributes.SCALE, 0.9)
				.add(EntityAttributes.MAX_HEALTH, 8.0));
		FabricDefaultAttributeRegistry.register(EMBER_SILVERFISH, SilverfishEntity.createSilverfishAttributes()
				.add(EntityAttributes.SCALE, 1.2)
				.add(EntityAttributes.MAX_HEALTH, 12.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 2.0));
		FabricDefaultAttributeRegistry.register(SOOT_SILVERFISH, SilverfishEntity.createSilverfishAttributes()
				.add(EntityAttributes.SCALE, 1.0)
				.add(EntityAttributes.MAX_HEALTH, 10.0));
		FabricDefaultAttributeRegistry.register(SLAG_SILVERFISH, SilverfishEntity.createSilverfishAttributes()
				.add(EntityAttributes.SCALE, 1.3)
				.add(EntityAttributes.MAX_HEALTH, 14.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 3.0));
		FabricDefaultAttributeRegistry.register(FLAME_VEX, VexEntity.createVexAttributes()
				.add(EntityAttributes.SCALE, 1.0)
				.add(EntityAttributes.MAX_HEALTH, 14.0));
		FabricDefaultAttributeRegistry.register(EMBER_VEX, VexEntity.createVexAttributes()
				.add(EntityAttributes.SCALE, 0.9)
				.add(EntityAttributes.MAX_HEALTH, 12.0));
		FabricDefaultAttributeRegistry.register(CINDER_VEX, VexEntity.createVexAttributes()
				.add(EntityAttributes.SCALE, 1.1)
				.add(EntityAttributes.MAX_HEALTH, 16.0));
		FabricDefaultAttributeRegistry.register(SMOKE_VEX, VexEntity.createVexAttributes()
				.add(EntityAttributes.SCALE, 0.95)
				.add(EntityAttributes.MAX_HEALTH, 12.0));
		FabricDefaultAttributeRegistry.register(SPARK_VEX, VexEntity.createVexAttributes()
				.add(EntityAttributes.SCALE, 0.85)
				.add(EntityAttributes.MAX_HEALTH, 10.0));
		FabricDefaultAttributeRegistry.register(ASH_MITE, EndermiteEntity.createEndermiteAttributes()
				.add(EntityAttributes.SCALE, 1.0)
				.add(EntityAttributes.MAX_HEALTH, 8.0));
		FabricDefaultAttributeRegistry.register(EMBER_MITE, EndermiteEntity.createEndermiteAttributes()
				.add(EntityAttributes.SCALE, 1.1)
				.add(EntityAttributes.MAX_HEALTH, 10.0));
		FabricDefaultAttributeRegistry.register(CINDER_MITE, EndermiteEntity.createEndermiteAttributes()
				.add(EntityAttributes.SCALE, 1.2)
				.add(EntityAttributes.MAX_HEALTH, 12.0));
		FabricDefaultAttributeRegistry.register(SOOT_MITE, EndermiteEntity.createEndermiteAttributes()
				.add(EntityAttributes.SCALE, 0.9)
				.add(EntityAttributes.MAX_HEALTH, 8.0));
		FabricDefaultAttributeRegistry.register(SLAG_MITE, EndermiteEntity.createEndermiteAttributes()
				.add(EntityAttributes.SCALE, 1.3)
				.add(EntityAttributes.MAX_HEALTH, 14.0));
	}

	private static void registerItems() {
		// Item.Settings.spawnEgg(type) stores the ENTITY_DATA component the vanilla
		// SpawnEggItem reads its entity type from in 1.21.9 (proven pattern from
		// infernomobs / dr_pepper_golem).
		EMBER_BLAZE_SPAWN_EGG = ModItems.register("ember_blaze_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_BLAZE));
		SOOT_BLAZE_SPAWN_EGG = ModItems.register("soot_blaze_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_BLAZE));
		PYRE_BLAZE_SPAWN_EGG = ModItems.register("pyre_blaze_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(PYRE_BLAZE));
		CINDER_BLAZE_SPAWN_EGG = ModItems.register("cinder_blaze_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_BLAZE));
		SLAGFIRE_BLAZE_SPAWN_EGG = ModItems.register("slagfire_blaze_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAGFIRE_BLAZE));
		MOLTEN_CUBE_SPAWN_EGG = ModItems.register("molten_cube_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MOLTEN_CUBE));
		EMBER_CUBE_SPAWN_EGG = ModItems.register("ember_cube_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_CUBE));
		SOOT_CUBE_SPAWN_EGG = ModItems.register("soot_cube_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_CUBE));
		SCORIA_CUBE_SPAWN_EGG = ModItems.register("scoria_cube_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SCORIA_CUBE));
		PYROCLAST_CUBE_SPAWN_EGG = ModItems.register("pyroclast_cube_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(PYROCLAST_CUBE));
		CINDER_SILVERFISH_SPAWN_EGG = ModItems.register("cinder_silverfish_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_SILVERFISH));
		ASH_SILVERFISH_SPAWN_EGG = ModItems.register("ash_silverfish_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_SILVERFISH));
		EMBER_SILVERFISH_SPAWN_EGG = ModItems.register("ember_silverfish_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_SILVERFISH));
		SOOT_SILVERFISH_SPAWN_EGG = ModItems.register("soot_silverfish_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_SILVERFISH));
		SLAG_SILVERFISH_SPAWN_EGG = ModItems.register("slag_silverfish_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_SILVERFISH));
		FLAME_VEX_SPAWN_EGG = ModItems.register("flame_vex_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(FLAME_VEX));
		EMBER_VEX_SPAWN_EGG = ModItems.register("ember_vex_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_VEX));
		CINDER_VEX_SPAWN_EGG = ModItems.register("cinder_vex_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_VEX));
		SMOKE_VEX_SPAWN_EGG = ModItems.register("smoke_vex_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SMOKE_VEX));
		SPARK_VEX_SPAWN_EGG = ModItems.register("spark_vex_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SPARK_VEX));
		ASH_MITE_SPAWN_EGG = ModItems.register("ash_mite_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_MITE));
		EMBER_MITE_SPAWN_EGG = ModItems.register("ember_mite_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_MITE));
		CINDER_MITE_SPAWN_EGG = ModItems.register("cinder_mite_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_MITE));
		SOOT_MITE_SPAWN_EGG = ModItems.register("soot_mite_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_MITE));
		SLAG_MITE_SPAWN_EGG = ModItems.register("slag_mite_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_MITE));

		EMBER_BLAZE_ROD = ModItems.register("ember_blaze_rod", Item::new, new Item.Settings());
		SOOT_PLUME = ModItems.register("soot_plume", Item::new, new Item.Settings());
		PYRE_ASH = ModItems.register("pyre_ash", Item::new, new Item.Settings());
		CINDER_SPARK = ModItems.register("cinder_spark", Item::new, new Item.Settings());
		SLAGFIRE_DROPLET = ModItems.register("slagfire_droplet", Item::new, new Item.Settings());
		MOLTEN_GLOBULE = ModItems.register("molten_globule", Item::new, new Item.Settings());
		EMBER_GLOBULE = ModItems.register("ember_globule", Item::new, new Item.Settings());
		SOOT_GLOBULE = ModItems.register("soot_globule", Item::new, new Item.Settings());
		SCORIA_CHUNK = ModItems.register("scoria_chunk", Item::new, new Item.Settings());
		PYROCLAST_SHARD = ModItems.register("pyroclast_shard", Item::new, new Item.Settings());
		CINDER_CHITIN = ModItems.register("cinder_chitin", Item::new, new Item.Settings());
		ASH_CHITIN = ModItems.register("ash_chitin", Item::new, new Item.Settings());
		EMBER_CHITIN = ModItems.register("ember_chitin", Item::new, new Item.Settings());
		SOOT_CHITIN = ModItems.register("soot_chitin", Item::new, new Item.Settings());
		SLAG_CHITIN = ModItems.register("slag_chitin", Item::new, new Item.Settings());
		FLAME_ESSENCE = ModItems.register("flame_essence", Item::new, new Item.Settings());
		EMBER_ESSENCE = ModItems.register("ember_essence", Item::new, new Item.Settings());
		CINDER_ESSENCE = ModItems.register("cinder_essence", Item::new, new Item.Settings());
		SMOKE_ESSENCE = ModItems.register("smoke_essence", Item::new, new Item.Settings());
		SPARK_ESSENCE = ModItems.register("spark_essence", Item::new, new Item.Settings());
		ASH_MITE_HUSK = ModItems.register("ash_mite_husk", Item::new, new Item.Settings());
		EMBER_MITE_HUSK = ModItems.register("ember_mite_husk", Item::new, new Item.Settings());
		CINDER_MITE_HUSK = ModItems.register("cinder_mite_husk", Item::new, new Item.Settings());
		SOOT_MITE_HUSK = ModItems.register("soot_mite_husk", Item::new, new Item.Settings());
		SLAG_MITE_HUSK = ModItems.register("slag_mite_husk", Item::new, new Item.Settings());

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			// Spawn eggs together, then the mob drops.
			entries.add(EMBER_BLAZE_SPAWN_EGG);
			entries.add(SOOT_BLAZE_SPAWN_EGG);
			entries.add(PYRE_BLAZE_SPAWN_EGG);
			entries.add(CINDER_BLAZE_SPAWN_EGG);
			entries.add(SLAGFIRE_BLAZE_SPAWN_EGG);
			entries.add(MOLTEN_CUBE_SPAWN_EGG);
			entries.add(EMBER_CUBE_SPAWN_EGG);
			entries.add(SOOT_CUBE_SPAWN_EGG);
			entries.add(SCORIA_CUBE_SPAWN_EGG);
			entries.add(PYROCLAST_CUBE_SPAWN_EGG);
			entries.add(CINDER_SILVERFISH_SPAWN_EGG);
			entries.add(ASH_SILVERFISH_SPAWN_EGG);
			entries.add(EMBER_SILVERFISH_SPAWN_EGG);
			entries.add(SOOT_SILVERFISH_SPAWN_EGG);
			entries.add(SLAG_SILVERFISH_SPAWN_EGG);
			entries.add(FLAME_VEX_SPAWN_EGG);
			entries.add(EMBER_VEX_SPAWN_EGG);
			entries.add(CINDER_VEX_SPAWN_EGG);
			entries.add(SMOKE_VEX_SPAWN_EGG);
			entries.add(SPARK_VEX_SPAWN_EGG);
			entries.add(ASH_MITE_SPAWN_EGG);
			entries.add(EMBER_MITE_SPAWN_EGG);
			entries.add(CINDER_MITE_SPAWN_EGG);
			entries.add(SOOT_MITE_SPAWN_EGG);
			entries.add(SLAG_MITE_SPAWN_EGG);
			entries.add(EMBER_BLAZE_ROD);
			entries.add(SOOT_PLUME);
			entries.add(PYRE_ASH);
			entries.add(CINDER_SPARK);
			entries.add(SLAGFIRE_DROPLET);
			entries.add(MOLTEN_GLOBULE);
			entries.add(EMBER_GLOBULE);
			entries.add(SOOT_GLOBULE);
			entries.add(SCORIA_CHUNK);
			entries.add(PYROCLAST_SHARD);
			entries.add(CINDER_CHITIN);
			entries.add(ASH_CHITIN);
			entries.add(EMBER_CHITIN);
			entries.add(SOOT_CHITIN);
			entries.add(SLAG_CHITIN);
			entries.add(FLAME_ESSENCE);
			entries.add(EMBER_ESSENCE);
			entries.add(CINDER_ESSENCE);
			entries.add(SMOKE_ESSENCE);
			entries.add(SPARK_ESSENCE);
			entries.add(ASH_MITE_HUSK);
			entries.add(EMBER_MITE_HUSK);
			entries.add(CINDER_MITE_HUSK);
			entries.add(SOOT_MITE_HUSK);
			entries.add(SLAG_MITE_HUSK);
		});
	}

	private static void registerSpawning() {
		// SpawnRestriction.register is private in vanilla but access-widened by
		// Fabric's transitive access wideners (proven by infernomobs). Locations/
		// heightmaps/predicates mirror the vanilla entries (SpawnRestriction
		// bytecode): blaze uses ON_GROUND + HostileEntity::canSpawnIgnoreLightLevel,
		// magma_cube's canMagmaCubeSpawn is only a difficulty != PEACEFUL check
		// (inlined; the vanilla method is typed to EntityType<MagmaCubeEntity>),
		// silverfish/endermite use their canSpawn (reimplemented 1:1 in
		// canSwarmBugSpawn below, the vanilla methods are likewise typed), and vex
		// uses UNRESTRICTED + HostileEntity::canSpawnInDark (it flies).
		SpawnRestriction.register(EMBER_BLAZE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(SOOT_BLAZE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(PYRE_BLAZE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(CINDER_BLAZE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(SLAGFIRE_BLAZE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnIgnoreLightLevel);
		SpawnRestriction.register(MOLTEN_CUBE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(EMBER_CUBE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(SOOT_CUBE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(SCORIA_CUBE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(PYROCLAST_CUBE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES,
				(type, world, reason, pos, random) -> world.getDifficulty() != Difficulty.PEACEFUL);
		SpawnRestriction.register(CINDER_SILVERFISH, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(ASH_SILVERFISH, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(EMBER_SILVERFISH, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(SOOT_SILVERFISH, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(SLAG_SILVERFISH, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(FLAME_VEX, SpawnLocationTypes.UNRESTRICTED,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(EMBER_VEX, SpawnLocationTypes.UNRESTRICTED,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(CINDER_VEX, SpawnLocationTypes.UNRESTRICTED,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SMOKE_VEX, SpawnLocationTypes.UNRESTRICTED,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SPARK_VEX, SpawnLocationTypes.UNRESTRICTED,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(ASH_MITE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(EMBER_MITE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(CINDER_MITE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(SOOT_MITE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);
		SpawnRestriction.register(SLAG_MITE, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, EmberSwarmFeature::canSwarmBugSpawn);

		// Natural spawns in the three Inferno biomes (biome JSONs are owned by the
		// infernodim feature; includeByKey matches nothing until they are loaded).
		Predicate<BiomeSelectionContext> infernoBiomes = BiomeSelectors.includeByKey(
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("cinder_wastes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("ember_grove")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("slag_sea")));
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBER_BLAZE, 10, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SOOT_BLAZE, 10, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, PYRE_BLAZE, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDER_BLAZE, 10, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAGFIRE_BLAZE, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, MOLTEN_CUBE, 18, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBER_CUBE, 16, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SOOT_CUBE, 16, 2, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SCORIA_CUBE, 14, 2, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, PYROCLAST_CUBE, 12, 2, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDER_SILVERFISH, 22, 1, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASH_SILVERFISH, 22, 1, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBER_SILVERFISH, 18, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SOOT_SILVERFISH, 20, 1, 4);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAG_SILVERFISH, 16, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, FLAME_VEX, 8, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBER_VEX, 7, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDER_VEX, 7, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SMOKE_VEX, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SPARK_VEX, 6, 1, 2);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, ASH_MITE, 18, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, EMBER_MITE, 16, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, CINDER_MITE, 14, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SOOT_MITE, 16, 1, 3);
		BiomeModifications.addSpawn(infernoBiomes, SpawnGroup.MONSTER, SLAG_MITE, 12, 1, 2);
	}

	/**
	 * Mirrors vanilla {@code SilverfishEntity.canSpawn} / {@code EndermiteEntity.canSpawn}
	 * (verified against the 1.21.9 bytecode - the two vanilla methods are identical but
	 * typed to the vanilla EntityTypes, so they cannot be reused directly): hostile
	 * ignore-light-level checks, spawners bypass the player-distance gate, otherwise no
	 * player may be within 5 blocks of the spawn position.
	 */
	private static <T extends HostileEntity> boolean canSwarmBugSpawn(EntityType<T> type,
			ServerWorldAccess world, SpawnReason reason, BlockPos pos, Random random) {
		if (!HostileEntity.canSpawnIgnoreLightLevel(type, world, reason, pos, random)) {
			return false;
		}
		if (SpawnReason.isAnySpawner(reason)) {
			return true;
		}
		PlayerEntity player = world.getClosestPlayer(pos.getX() + 0.5, pos.getY() + 0.5,
				pos.getZ() + 0.5, 5.0, true);
		return player == null;
	}
}
