package net.sonic0810.copperinferno.feature.emberswarm;

import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.VexEntity;
import net.minecraft.world.World;

/**
 * A swarm vex. Behavior is pure vanilla vex: it flies via the vex move control
 * installed by the base constructor, phases through blocks and only decays when
 * {@code setLifeTicks} is called (evoker summons; natural spawns live forever).
 * Stats come from {@link EmberSwarmFeature}. Drops are in
 * {@code loot_table/entities/spark_vex.json}.
 * Generated by {@code devtools/gen/emberswarm_gen.py}.
 */
public class SparkVexEntity extends VexEntity {
	public SparkVexEntity(EntityType<? extends VexEntity> type, World world) {
		super(type, world);
	}
}
