package net.sonic0810.copperinferno.feature.driftwood;

import java.util.function.Supplier;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.registry.FlammableBlockRegistry;
import net.fabricmc.fabric.api.registry.StrippableBlockRegistry;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.UntintedParticleLeavesBlock;
import net.minecraft.particle.ParticleTypes;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.content.WoodSets;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v5 "Grünspanflut" driftwood and coastal flora: three full 13-block wood sets with matching
 * leaves plus six decorative shore plants/clusters. Assets, recipes, tags and language fragments
 * are generated by {@code devtools/gen/driftwood_gen.py}.
 *
 * <p>The flora blocks deliberately use the lightweight Inferno-flora pattern: plain blocks with
 * instant breaking and no support checks. The five sprite-shaped decorations render cutout on the
 * client; Foam Moss is an ordinary moss-like cube.
 */
public final class DriftwoodFeature {
	private DriftwoodFeature() {
	}

	public static WoodSets.WoodSet DRIFTWOOD;
	public static WoodSets.WoodSet TIDEWILLOW;
	public static WoodSets.WoodSet BRINEPINE;

	public static Block DRIFTWOOD_LEAVES;
	public static Block TIDEWILLOW_LEAVES;
	public static Block BRINEPINE_LEAVES;

	public static Block VERDIGRIS_KELP;
	public static Block SALT_SPROUT;
	public static Block TIDE_LILY;
	public static Block BARNACLE_CLUSTER;
	public static Block PEARL_CLUSTER;
	public static Block FOAM_MOSS;

	private static Supplier<AbstractBlock.Settings> woodSettings(MapColor color) {
		return () -> AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(2.0F)
				.sounds(BlockSoundGroup.WOOD);
	}

	private static AbstractBlock.Settings plantSettings(BlockSoundGroup sounds, MapColor color) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.noCollision()
				.breakInstantly()
				.sounds(sounds);
	}

	private static AbstractBlock.Settings leavesSettings(MapColor color) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(0.2F)
				.ticksRandomly()
				.nonOpaque()
				.sounds(BlockSoundGroup.GRASS);
	}

	public static void init() {
		// String literals are required by audit_assets.py's WoodSets expansion.
		DRIFTWOOD = WoodSets.registerWoodSet("driftwood",
				woodSettings(MapColor.SPRUCE_BROWN), ModCreativeTab.TIDES_KEY);
		TIDEWILLOW = WoodSets.registerWoodSet("tidewillow",
				woodSettings(MapColor.TEAL), ModCreativeTab.TIDES_KEY);
		BRINEPINE = WoodSets.registerWoodSet("brinepine",
				woodSettings(MapColor.DARK_AQUA), ModCreativeTab.TIDES_KEY);

		DRIFTWOOD_LEAVES = ModBlocks.register("driftwood_leaves",
				s -> new UntintedParticleLeavesBlock(0.01F, ParticleTypes.PALE_OAK_LEAVES, s),
				leavesSettings(MapColor.PALE_GREEN), true);
		TIDEWILLOW_LEAVES = ModBlocks.register("tidewillow_leaves",
				s -> new UntintedParticleLeavesBlock(0.01F, ParticleTypes.PALE_OAK_LEAVES, s),
				leavesSettings(MapColor.TEAL), true);
		BRINEPINE_LEAVES = ModBlocks.register("brinepine_leaves",
				s -> new UntintedParticleLeavesBlock(0.01F, ParticleTypes.PALE_OAK_LEAVES, s),
				leavesSettings(MapColor.DARK_AQUA), true);

		registerWoodBehavior(DRIFTWOOD, DRIFTWOOD_LEAVES);
		registerWoodBehavior(TIDEWILLOW, TIDEWILLOW_LEAVES);
		registerWoodBehavior(BRINEPINE, BRINEPINE_LEAVES);

		VERDIGRIS_KELP = ModBlocks.register("verdigris_kelp", Block::new,
				plantSettings(BlockSoundGroup.WET_GRASS, MapColor.TEAL), true);
		SALT_SPROUT = ModBlocks.register("salt_sprout", Block::new,
				plantSettings(BlockSoundGroup.ROOTS, MapColor.OFF_WHITE), true);
		TIDE_LILY = ModBlocks.register("tide_lily", Block::new,
				plantSettings(BlockSoundGroup.GRASS, MapColor.LIGHT_BLUE), true);
		BARNACLE_CLUSTER = ModBlocks.register("barnacle_cluster", Block::new,
				plantSettings(BlockSoundGroup.CORAL, MapColor.LIGHT_GRAY), true);
		PEARL_CLUSTER = ModBlocks.register("pearl_cluster", Block::new,
				plantSettings(BlockSoundGroup.AMETHYST_CLUSTER, MapColor.OFF_WHITE)
						.luminance(state -> 7),
				true);
		FOAM_MOSS = ModBlocks.register("foam_moss", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.PALE_GREEN)
						.strength(0.1F)
						.sounds(BlockSoundGroup.MOSS_BLOCK),
				true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.TIDES_KEY).register(entries -> {
			entries.add(DRIFTWOOD_LEAVES);
			entries.add(TIDEWILLOW_LEAVES);
			entries.add(BRINEPINE_LEAVES);
			entries.add(VERDIGRIS_KELP);
			entries.add(SALT_SPROUT);
			entries.add(TIDE_LILY);
			entries.add(BARNACLE_CLUSTER);
			entries.add(PEARL_CLUSTER);
			entries.add(FOAM_MOSS);
		});

		DriftwoodTreesFeature.init();
		registerHandbookEntries();
	}

	private static void registerWoodBehavior(WoodSets.WoodSet set, Block leaves) {
		// Vanilla axe stripping preserves the PillarBlock AXIS property.
		StrippableBlockRegistry.register(set.log(), set.strippedLog());
		StrippableBlockRegistry.register(set.wood(), set.strippedWood());

		FlammableBlockRegistry flammable = FlammableBlockRegistry.getDefaultInstance();
		flammable.add(set.log(), 5, 5);
		flammable.add(set.strippedLog(), 5, 5);
		flammable.add(set.wood(), 5, 5);
		flammable.add(set.strippedWood(), 5, 5);
		flammable.add(set.planks(), 5, 20);
		flammable.add(set.plankSlab(), 5, 20);
		flammable.add(set.plankStairs(), 5, 20);
		flammable.add(set.fence(), 5, 20);
		flammable.add(set.fenceGate(), 5, 20);
		flammable.add(set.mosaic(), 5, 20);
		flammable.add(set.pillar(), 5, 20);
		flammable.add(leaves, 30, 60);
	}

	/** Three wood introductions plus one coastal-flora overview. */
	private static void registerHandbookEntries() {
		HandbookEntries.add(new HandbookEntry("blocks", "driftwood_planks",
				"copper_inferno:driftwood_planks", "driftwood/driftwood_planks",
				new String[] {"copper_inferno:driftwood_log", "", "", "", "", "", "", "", ""},
				"copper_inferno:driftwood_planks", 4,
				"Any Driftwood log or wood block crafts into 4 Driftwood Planks. Use an axe on logs and wood to strip away their salt-worn bark.",
				"Jeder Treibholzstamm oder -holzblock ergibt 4 Treibholzbretter. Mit einer Axt lässt sich die salzgegerbte Rinde entfernen."));
		HandbookEntries.add(new HandbookEntry("blocks", "tidewillow_planks",
				"copper_inferno:tidewillow_planks", "driftwood/tidewillow_planks",
				new String[] {"copper_inferno:tidewillow_log", "", "", "", "", "", "", "", ""},
				"copper_inferno:tidewillow_planks", 4,
				"Tidewillows grow along rivers. Their teal timber forms a complete 13-piece building set and can be stripped with an axe.",
				"Gezeitenweiden wachsen an Flüssen. Ihr türkisfarbenes Holz bildet ein vollständiges 13-teiliges Bauset und lässt sich mit einer Axt entrinden."));
		HandbookEntries.add(new HandbookEntry("blocks", "brinepine_planks",
				"copper_inferno:brinepine_planks", "driftwood/brinepine_planks",
				new String[] {"copper_inferno:brinepine_log", "", "", "", "", "", "", "", ""},
				"copper_inferno:brinepine_planks", 4,
				"Brinepines weather ocean spray into sturdy blue-green timber. One log or wood block crafts into 4 planks.",
				"Salzkiefern trotzen der Meeresgischt mit robustem blaugrünem Holz. Ein Stamm oder Holzblock ergibt 4 Bretter."));
		HandbookEntries.add(new HandbookEntry("blocks", "driftwood_coastal_flora",
				"copper_inferno:pearl_cluster", null, null,
				"copper_inferno:pearl_cluster", 1,
				"Coastal flora includes Verdigris Kelp, Salt Sprouts, Tide Lilies, Barnacle and glowing Pearl Clusters, plus soft Foam Moss. Pearl Clusters emit light level 7.",
				"Zur Küstenflora gehören Grünspankelp, Salzsprossen, Gezeitenlilien, Seepocken- und leuchtende Perlenkolonien sowie weiches Schaummoos. Perlenkolonien leuchten mit Lichtstufe 7."));
	}
}
