package net.sonic0810.copperinferno.feature.scorchwood;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;

import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.registry.FlammableBlockRegistry;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.SaplingGenerator;
import net.minecraft.block.UntintedParticleLeavesBlock;
import net.minecraft.particle.ParticleTypes;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.world.gen.GenerationStep;
import net.minecraft.world.gen.feature.ConfiguredFeature;
import net.minecraft.world.gen.feature.PlacedFeature;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.content.WoodSets;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Scorched Woods" (WP4): eight full wood sets — the 13 building blocks (planks, plank
 * slab/stairs, fence, fence gate, button, pressure plate, log, stripped log, wood, stripped
 * wood, mosaic, pillar) registered through {@link WoodSets#registerWoodSet} plus a
 * {@link ScorchSaplingBlock sapling} and {@link UntintedParticleLeavesBlock leaves} per wood
 * (15 x 8 = 120 blocks), all in the Depths creative tab.
 *
 * <p>Survival obtainability: each wood grows as a real tree. The sapling's
 * {@link SaplingGenerator} references the datapack configured feature
 * {@code copper_inferno:<wood>_tree}, and {@code <wood>_trees} placed features are injected
 * into the Inferno biomes via {@link BiomeModifications} (4 woods in ember_grove, 4 in
 * verdigris_jungle). Logs/planks/leaves get vanilla flammability so logs smelt to charcoal
 * and burn (the log families join {@code #minecraft:logs}/{@code logs_that_burn} through
 * devtools/tagfrag/scorchwood.json).
 *
 * <p>AUDIT CONTRACT: every {@code registerWoodSet}/{@code registerTreeContent} call below
 * passes the wood name (and biome id) as string LITERALS (see devtools/audit_assets.py check
 * (f)). Assets/recipes/tags/lang are generated by devtools/gen/scorchwood_gen.py. Stripped
 * variants come from the stonecutter (recipe-based, no axe-stripping), so no
 * {@code StrippableBlockRegistry} wiring is needed.
 */
public final class ScorchWoodFeature {
	private ScorchWoodFeature() {
	}

	/** The 8 registered saplings, in canonical wood order (client render layers walk this). */
	public static final List<Block> SAPLINGS = new ArrayList<>();

	/** The 8 registered leaves, in canonical wood order (client render layers walk this). */
	public static final List<Block> LEAVES = new ArrayList<>();

	/** Fresh wood settings per registration (WoodSets invokes the supplier per block). */
	private static Supplier<AbstractBlock.Settings> woodSettings() {
		return () -> AbstractBlock.Settings.create()
				.strength(2.0F)
				.sounds(BlockSoundGroup.WOOD);
	}

	public static void init() {
		// 4 woods at home in ember_grove, 4 in verdigris_jungle (tree worldgen injection).
		registerTreeContent("emberwood", "ember_grove",
				WoodSets.registerWoodSet("emberwood", woodSettings(), ModCreativeTab.DEPTHS_KEY));
		registerTreeContent("ashwillow", "verdigris_jungle",
				WoodSets.registerWoodSet("ashwillow", woodSettings(), ModCreativeTab.DEPTHS_KEY));
		registerTreeContent("cinderpine", "ember_grove",
				WoodSets.registerWoodSet("cinderpine", woodSettings(), ModCreativeTab.DEPTHS_KEY));
		registerTreeContent("charoak", "ember_grove",
				WoodSets.registerWoodSet("charoak", woodSettings(), ModCreativeTab.DEPTHS_KEY));
		registerTreeContent("glowbirch", "verdigris_jungle",
				WoodSets.registerWoodSet("glowbirch", woodSettings(), ModCreativeTab.DEPTHS_KEY));
		registerTreeContent("sootmaple", "verdigris_jungle",
				WoodSets.registerWoodSet("sootmaple", woodSettings(), ModCreativeTab.DEPTHS_KEY));
		registerTreeContent("duskthorn", "verdigris_jungle",
				WoodSets.registerWoodSet("duskthorn", woodSettings(), ModCreativeTab.DEPTHS_KEY));
		registerTreeContent("pyrewood", "ember_grove",
				WoodSets.registerWoodSet("pyrewood", woodSettings(), ModCreativeTab.DEPTHS_KEY));

		registerHandbookEntries();
	}

	/**
	 * Registers one wood's survival-progression content: the {@code <wood>_sapling}
	 * (growing into the {@code copper_inferno:<wood>_tree} configured feature) and
	 * {@code <wood>_leaves} blocks (appended to the Depths tab after the 13-block set),
	 * vanilla flammability for the whole set, and the {@code <wood>_trees} placed-feature
	 * injection into the wood's home Inferno biome.
	 *
	 * <p>AUDIT CONTRACT: call sites pass {@code wood} and {@code biome} as string literals.
	 */
	private static void registerTreeContent(String wood, String biome, WoodSets.WoodSet set) {
		RegistryKey<ConfiguredFeature<?, ?>> treeFeature =
				RegistryKey.of(RegistryKeys.CONFIGURED_FEATURE, CopperInferno.id(wood + "_tree"));
		// 4-arg SaplingGenerator ctor: (id, megaVariant, regularVariant, beesVariant).
		SaplingGenerator generator = new SaplingGenerator(CopperInferno.MOD_ID + ":" + wood,
				Optional.empty(), Optional.of(treeFeature), Optional.empty());

		Block sapling = ModBlocks.register(wood + "_sapling",
				s -> new ScorchSaplingBlock(generator, s),
				AbstractBlock.Settings.create()
						.noCollision()
						.ticksRandomly()
						.strength(0.0F)
						.sounds(BlockSoundGroup.GRASS),
				true);
		Block leaves = ModBlocks.register(wood + "_leaves",
				s -> new UntintedParticleLeavesBlock(0.01F, ParticleTypes.PALE_OAK_LEAVES, s),
				AbstractBlock.Settings.create()
						.strength(0.2F)
						.ticksRandomly()
						.nonOpaque()
						.sounds(BlockSoundGroup.GRASS),
				true);
		SAPLINGS.add(sapling);
		LEAVES.add(leaves);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.DEPTHS_KEY).register(entries -> {
			entries.add(sapling);
			entries.add(leaves);
		});

		// Vanilla flammability (FireBlock.registerDefaultFlammables values): logs 5/5,
		// plank-family 5/20, leaves 30/60. Buttons/pressure plates are not flammable in
		// vanilla either.
		FlammableBlockRegistry flammable = FlammableBlockRegistry.getDefaultInstance();
		flammable.add(set.log(), 5, 5);
		flammable.add(set.strippedLog(), 5, 5);
		flammable.add(set.wood(), 5, 5);
		flammable.add(set.strippedWood(), 5, 5);
		flammable.add(set.planks(), 5, 20);
		flammable.add(set.plankSlab(), 5, 20);
		flammable.add(set.plankStairs(), 5, 20);
		flammable.add(set.fence(), 5, 20);
		flammable.add(set.fenceGate(), 5, 20);
		flammable.add(set.mosaic(), 5, 20);
		flammable.add(set.pillar(), 5, 20);
		flammable.add(leaves, 30, 60);

		// Registration-order-safe datapack-key injection, exactly like GemAlloyFeature's
		// injectAlloyOres (the key resolves against worldgen JSON at world load).
		RegistryKey<PlacedFeature> trees =
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id(wood + "_trees"));
		BiomeModifications.addFeature(
				BiomeSelectors.includeByKey(RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id(biome))),
				GenerationStep.Feature.VEGETAL_DECORATION, trees);
	}

	/** One curated entry per wood: the log-to-planks recipe that opens up the whole set. */
	private static void registerHandbookEntries() {
		addWoodEntry("emberwood", "Emberwood",
				"Any Emberwood log or wood block crafts into 4 Emberwood Planks - the warm, ember-flecked entry point to the full 13-piece Emberwood set.",
				"Jeder Glutholzstamm oder Glutholzblock ergibt 4 Glutholzbretter - der glutgesprenkelte Einstieg in das komplette 13-teilige Glutholz-Sortiment.");
		addWoodEntry("ashwillow", "Ashwillow",
				"Any Ashwillow log or wood block crafts into 4 Ashwillow Planks - pale ashen timber for the full 13-piece Ashwillow set.",
				"Jeder Aschenweidenstamm oder Aschenweidenholzblock ergibt 4 Aschenweidenholzbretter - blasses Aschenholz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("cinderpine", "Cinderpine",
				"Any Cinderpine log or wood block crafts into 4 Cinderpine Planks - deep auburn timber for the full 13-piece Cinderpine set.",
				"Jeder Schlackenkiefernstamm oder Schlackenkiefernholzblock ergibt 4 Schlackenkiefernholzbretter - tiefrotbraunes Holz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("charoak", "Charoak",
				"Any Charoak log or wood block crafts into 4 Charoak Planks - charcoal-black timber for the full 13-piece Charoak set.",
				"Jeder Kohleneichenstamm oder Kohleneichenholzblock ergibt 4 Kohleneichenholzbretter - kohlschwarzes Holz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("glowbirch", "Glowbirch",
				"Any Glowbirch log or wood block crafts into 4 Glowbirch Planks - pale cream timber with teal glints for the full 13-piece Glowbirch set.",
				"Jeder Leuchtbirkenstamm oder Leuchtbirkenholzblock ergibt 4 Leuchtbirkenholzbretter - cremehelles Holz mit t\u00fcrkisen Glanzpunkten f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("sootmaple", "Sootmaple",
				"Any Sootmaple log or wood block crafts into 4 Sootmaple Planks - smoky gray-brown timber for the full 13-piece Sootmaple set.",
				"Jeder Ru\u00dfahornstamm oder Ru\u00dfahornholzblock ergibt 4 Ru\u00dfahornholzbretter - rauchig graubraunes Holz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("duskthorn", "Duskthorn",
				"Any Duskthorn log or wood block crafts into 4 Duskthorn Planks - dusky violet timber for the full 13-piece Duskthorn set.",
				"Jeder D\u00e4mmerdornstamm oder D\u00e4mmerdornholzblock ergibt 4 D\u00e4mmerdornholzbretter - d\u00e4mmrig violettes Holz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("pyrewood", "Pyrewood",
				"Any Pyrewood log or wood block crafts into 4 Pyrewood Planks - bright amber timber for the full 13-piece Pyrewood set.",
				"Jeder Scheiterholzstamm oder Scheiterholzblock ergibt 4 Scheiterholzbretter - leuchtend bernsteinfarbenes Holz f\u00fcr das komplette 13-teilige Sortiment.");
	}

	private static void addWoodEntry(String wood, String woodEn, String textEn, String textDe) {
		String planks = "copper_inferno:" + wood + "_planks";
		HandbookEntries.add(new HandbookEntry("blocks", "scorchwood_" + wood + "_planks",
				planks, "scorchwood/" + wood + "_planks",
				new String[] {"copper_inferno:" + wood + "_log", "", "", "", "", "", "", "", ""},
				planks, 4, textEn, textDe));
	}
}
