package net.sonic0810.copperinferno.feature.scorchwood;

import java.util.function.Supplier;

import net.minecraft.block.AbstractBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.content.WoodSets;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Scorched Woods" (WP4): eight full 13-block wood sets (planks, plank slab/stairs, fence,
 * fence gate, button, pressure plate, log, stripped log, wood, stripped wood, mosaic, pillar)
 * registered through {@link WoodSets#registerWoodSet} into the Depths creative tab — 104 blocks.
 *
 * <p>AUDIT CONTRACT: every {@code registerWoodSet} call below passes the wood name as a string
 * LITERAL (see devtools/audit_assets.py check (f)). Assets/recipes/tags/lang are generated by
 * devtools/gen/scorchwood_gen.py. Stripped variants come from the stonecutter (recipe-based, no
 * axe-stripping), so no {@code StrippableBlockRegistry} wiring is needed.
 */
public final class ScorchWoodFeature {
	private ScorchWoodFeature() {
	}

	/** Fresh wood settings per registration (WoodSets invokes the supplier per block). */
	private static Supplier<AbstractBlock.Settings> woodSettings() {
		return () -> AbstractBlock.Settings.create()
				.strength(2.0F)
				.sounds(BlockSoundGroup.WOOD);
	}

	public static void init() {
		WoodSets.registerWoodSet("emberwood", woodSettings(), ModCreativeTab.DEPTHS_KEY);
		WoodSets.registerWoodSet("ashwillow", woodSettings(), ModCreativeTab.DEPTHS_KEY);
		WoodSets.registerWoodSet("cinderpine", woodSettings(), ModCreativeTab.DEPTHS_KEY);
		WoodSets.registerWoodSet("charoak", woodSettings(), ModCreativeTab.DEPTHS_KEY);
		WoodSets.registerWoodSet("glowbirch", woodSettings(), ModCreativeTab.DEPTHS_KEY);
		WoodSets.registerWoodSet("sootmaple", woodSettings(), ModCreativeTab.DEPTHS_KEY);
		WoodSets.registerWoodSet("duskthorn", woodSettings(), ModCreativeTab.DEPTHS_KEY);
		WoodSets.registerWoodSet("pyrewood", woodSettings(), ModCreativeTab.DEPTHS_KEY);

		registerHandbookEntries();
	}

	/** One curated entry per wood: the log-to-planks recipe that opens up the whole set. */
	private static void registerHandbookEntries() {
		addWoodEntry("emberwood", "Emberwood",
				"Any Emberwood log or wood block crafts into 4 Emberwood Planks - the warm, ember-flecked entry point to the full 13-piece Emberwood set.",
				"Jeder Glutholzstamm oder Glutholzblock ergibt 4 Glutholzbretter - der glutgesprenkelte Einstieg in das komplette 13-teilige Glutholz-Sortiment.");
		addWoodEntry("ashwillow", "Ashwillow",
				"Any Ashwillow log or wood block crafts into 4 Ashwillow Planks - pale ashen timber for the full 13-piece Ashwillow set.",
				"Jeder Aschenweidenstamm oder Aschenweidenholzblock ergibt 4 Aschenweidenholzbretter - blasses Aschenholz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("cinderpine", "Cinderpine",
				"Any Cinderpine log or wood block crafts into 4 Cinderpine Planks - deep auburn timber for the full 13-piece Cinderpine set.",
				"Jeder Schlackenkiefernstamm oder Schlackenkiefernholzblock ergibt 4 Schlackenkiefernholzbretter - tiefrotbraunes Holz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("charoak", "Charoak",
				"Any Charoak log or wood block crafts into 4 Charoak Planks - charcoal-black timber for the full 13-piece Charoak set.",
				"Jeder Kohleneichenstamm oder Kohleneichenholzblock ergibt 4 Kohleneichenholzbretter - kohlschwarzes Holz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("glowbirch", "Glowbirch",
				"Any Glowbirch log or wood block crafts into 4 Glowbirch Planks - pale cream timber with teal glints for the full 13-piece Glowbirch set.",
				"Jeder Leuchtbirkenstamm oder Leuchtbirkenholzblock ergibt 4 Leuchtbirkenholzbretter - cremehelles Holz mit t\u00fcrkisen Glanzpunkten f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("sootmaple", "Sootmaple",
				"Any Sootmaple log or wood block crafts into 4 Sootmaple Planks - smoky gray-brown timber for the full 13-piece Sootmaple set.",
				"Jeder Ru\u00dfahornstamm oder Ru\u00dfahornholzblock ergibt 4 Ru\u00dfahornholzbretter - rauchig graubraunes Holz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("duskthorn", "Duskthorn",
				"Any Duskthorn log or wood block crafts into 4 Duskthorn Planks - dusky violet timber for the full 13-piece Duskthorn set.",
				"Jeder D\u00e4mmerdornstamm oder D\u00e4mmerdornholzblock ergibt 4 D\u00e4mmerdornholzbretter - d\u00e4mmrig violettes Holz f\u00fcr das komplette 13-teilige Sortiment.");
		addWoodEntry("pyrewood", "Pyrewood",
				"Any Pyrewood log or wood block crafts into 4 Pyrewood Planks - bright amber timber for the full 13-piece Pyrewood set.",
				"Jeder Scheiterholzstamm oder Scheiterholzblock ergibt 4 Scheiterholzbretter - leuchtend bernsteinfarbenes Holz f\u00fcr das komplette 13-teilige Sortiment.");
	}

	private static void addWoodEntry(String wood, String woodEn, String textEn, String textDe) {
		String planks = "copper_inferno:" + wood + "_planks";
		HandbookEntries.add(new HandbookEntry("blocks", "scorchwood_" + wood + "_planks",
				planks, "scorchwood/" + wood + "_planks",
				new String[] {"copper_inferno:" + wood + "_log", "", "", "", "", "", "", "", ""},
				planks, 4, textEn, textDe));
	}
}
