package net.sonic0810.copperinferno.feature.wildworld;

/**
 * v4 "Wild World" feature (WP16): 8 named worldgen features, each in its own class —
 * <ol>
 *   <li>{@link VerdigrisJungleBiome} — new Inferno biome (data-driven)</li>
 *   <li>{@link DoomBasinBiome} — new Inferno biome (data-driven)</li>
 *   <li>{@link EmberGeyserFeature} — geyser block that launches entities + Doom Basin patch</li>
 *   <li>{@link CopperMeteoriteFeature} — rare Overworld impact site + meteoric_iron block</li>
 *   <li>{@link FumaroleVentFeature} — smoking vent block + Doom Basin patch</li>
 *   <li>{@link SmolderCrystalCaveFeature} — huge smolder_crystal_ore clusters</li>
 *   <li>{@link AshfallFeature} — dimension-wide client ash particles (see client class)</li>
 *   <li>{@link RuinedForgesFeature} — custom {@code Feature<DefaultFeatureConfig>} ruin</li>
 * </ol>
 * Assets/worldgen JSON are generated by {@code devtools/gen/wildworld_gen.py}; client hooks
 * live in {@code feature.wildworld.client.WildWorldFeatureClient}.
 */
public final class WildWorldFeature {
	private WildWorldFeature() {
	}

	public static void init() {
		VerdigrisJungleBiome.init();
		DoomBasinBiome.init();
		EmberGeyserFeature.init();
		CopperMeteoriteFeature.init();
		FumaroleVentFeature.init();
		SmolderCrystalCaveFeature.init();
		AshfallFeature.init();
		RuinedForgesFeature.init();
	}
}
