package net.sonic0810.copperinferno.feature.advancements;

import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4.1 "Advancements" feature: the 20-node bilingual COPPER INFERNO advancement tree.
 *
 * <p>The tree itself is pure data — datapack JSON under
 * {@code data/copper_inferno/advancement/copper_inferno/} generated by
 * devtools/gen/advancements_gen.py (root -> copper -> armor/statue/gemalloys, the Dr.Pepper
 * branch with its DOOM kick, the infernium -> Inferno -> boss branch and the scorchwood
 * branch), with every title/description translated in the EN + DE lang fragments
 * ({@code lang/fragments{,_de}/advancements.json}). This initializer only contributes the
 * handbook entry pointing players at the tree.
 */
public final class AdvancementsFeature {
	private AdvancementsFeature() {
	}

	public static void init() {
		HandbookEntries.add(new HandbookEntry("items", "advancements_tree",
				"copper_inferno:dr_pepper", null, null, null, 0,
				"The COPPER INFERNO advancement tree (press L) charts your journey: from the"
						+ " first copper ingot through oxidizing armor, all twelve gemalloys and"
						+ " the Dr.Pepper DOOM kick, down into the Inferno to fell its bosses"
						+ " and grow the scorched woods.",
				"Der COPPER-INFERNO-Fortschrittsbaum (Taste L) kartiert deine Reise: vom ersten"
						+ " Kupferbarren \u00fcber oxidierende R\u00fcstung, alle zw\u00f6lf Edellegierungen und"
						+ " den Dr.Pepper-DOOM-Kick hinab ins Inferno, um seine Bosse zu f\u00e4llen"
						+ " und die versengten W\u00e4lder anzubauen."));
	}
}
