package net.sonic0810.copperinferno.feature.materials;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.Item;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * Crafting materials: copper machining parts (dust, rod, gear, sheet, wire, spring, mesh,
 * rivet, screw, coil), alloy/charred/inferno ingots, inferno shard & powder, bottle cap and
 * soda essence. Assets + recipes are generated by devtools/gen/materials_gen.py.
 */
public final class MaterialsFeature {
	private MaterialsFeature() {
	}

	public static Item COPPER_DUST;
	public static Item OXIDIZED_COPPER_DUST;
	public static Item COPPER_ROD;
	public static Item COPPER_GEAR;
	public static Item COPPER_SHEET;
	public static Item COPPER_WIRE;
	public static Item COPPER_SPRING;
	public static Item COPPER_MESH;
	public static Item COPPER_RIVET;
	public static Item COPPER_SCREW;
	public static Item COPPER_COIL;
	public static Item COPPER_ALLOY_INGOT;
	public static Item CHARRED_COPPER_INGOT;
	public static Item INFERNO_SHARD;
	public static Item INFERNO_POWDER;
	public static Item INFERNO_ALLOY_INGOT;
	public static Item BOTTLE_CAP;
	public static Item SODA_ESSENCE;

	public static void init() {
		COPPER_DUST = ModItems.register("copper_dust", Item::new, new Item.Settings());
		OXIDIZED_COPPER_DUST = ModItems.register("oxidized_copper_dust", Item::new, new Item.Settings());
		COPPER_ROD = ModItems.register("copper_rod", Item::new, new Item.Settings());
		COPPER_GEAR = ModItems.register("copper_gear", Item::new, new Item.Settings());
		COPPER_SHEET = ModItems.register("copper_sheet", Item::new, new Item.Settings());
		COPPER_WIRE = ModItems.register("copper_wire", Item::new, new Item.Settings());
		COPPER_SPRING = ModItems.register("copper_spring", Item::new, new Item.Settings());
		COPPER_MESH = ModItems.register("copper_mesh", Item::new, new Item.Settings());
		COPPER_RIVET = ModItems.register("copper_rivet", Item::new, new Item.Settings());
		COPPER_SCREW = ModItems.register("copper_screw", Item::new, new Item.Settings());
		COPPER_COIL = ModItems.register("copper_coil", Item::new, new Item.Settings());
		COPPER_ALLOY_INGOT = ModItems.register("copper_alloy_ingot", Item::new, new Item.Settings());
		CHARRED_COPPER_INGOT = ModItems.register("charred_copper_ingot", Item::new, new Item.Settings());
		INFERNO_SHARD = ModItems.register("inferno_shard", Item::new, new Item.Settings());
		INFERNO_POWDER = ModItems.register("inferno_powder", Item::new, new Item.Settings());
		INFERNO_ALLOY_INGOT = ModItems.register("inferno_alloy_ingot", Item::new,
				new Item.Settings().rarity(Rarity.UNCOMMON).fireproof());
		BOTTLE_CAP = ModItems.register("bottle_cap", Item::new, new Item.Settings());
		SODA_ESSENCE = ModItems.register("soda_essence", Item::new, new Item.Settings());

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			entries.add(COPPER_DUST);
			entries.add(OXIDIZED_COPPER_DUST);
			entries.add(COPPER_ROD);
			entries.add(COPPER_GEAR);
			entries.add(COPPER_SHEET);
			entries.add(COPPER_WIRE);
			entries.add(COPPER_SPRING);
			entries.add(COPPER_MESH);
			entries.add(COPPER_RIVET);
			entries.add(COPPER_SCREW);
			entries.add(COPPER_COIL);
			entries.add(COPPER_ALLOY_INGOT);
			entries.add(CHARRED_COPPER_INGOT);
			entries.add(INFERNO_SHARD);
			entries.add(INFERNO_POWDER);
			entries.add(INFERNO_ALLOY_INGOT);
			entries.add(BOTTLE_CAP);
			entries.add(SODA_ESSENCE);
		});
	}
}
