package net.sonic0810.copperinferno.feature.infernoflora;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.block.type.WoodTypeBuilder;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.BlockSetType;
import net.minecraft.block.CarpetBlock;
import net.minecraft.block.FenceBlock;
import net.minecraft.block.FenceGateBlock;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.block.SlabBlock;
import net.minecraft.block.WoodType;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * Inferno flora: 22 plant/fungus/wood blocks for the Inferno dimension — the "scorched" wood
 * set (stem/hyphae + stripped variants, planks, slab, stairs, fence, fence gate), two wart
 * blocks, six small cross-model plants, ember moss (block + carpet) and three fungal utility
 * blocks. Assets (blockstates, models, textures, item definitions, loot tables, recipes, lang
 * fragments) are generated by {@code devtools/gen/infernoflora_gen.py}.
 *
 * <p>DOCUMENTED SIMPLIFICATIONS:
 * <ul>
 *   <li>The six small plants (ember_fungus, ash_sprouts, cinder_roots, smolder_bloom,
 *       ashen_grass, spore_cluster) are plain {@link Block}s with
 *       {@code noCollision().breakInstantly()}: they are placeable on ANY surface — there is no
 *       floor/support-block check like vanilla {@code PlantBlock} performs.</li>
 *   <li>Stripped stem/hyphae are obtained via crafting recipes; there is NO axe-strip
 *       right-click interaction on the unstripped logs.</li>
 *   <li>All 22 blocks (including the small plants) drop themselves unconditionally — no
 *       shears/silk-touch requirement.</li>
 * </ul>
 *
 * <p>The scorched wood set does NOT use {@code requiresTool()}: it is breakable by hand (axe
 * only speeds it up via the mineable/axe tag fragment; the set is deliberately NOT in the
 * pickaxe tag — see {@code devtools/tagfrag/infernoflora.json}).
 */
public final class InfernoFloraFeature {
	private InfernoFloraFeature() {
	}

	/**
	 * Scorched wood type for the fence gate. Copies {@link WoodType#CRIMSON} (nether-wood
	 * sounds + crimson fence-gate open/close sounds) via Fabric's {@link WoodTypeBuilder},
	 * which also registers the type in {@code WoodType.VALUES} so the
	 * {@link FenceGateBlock} codec stays functional (same pattern as the utilityblocks
	 * feature's copper wood type).
	 */
	public static final WoodType SCORCHED_WOOD_TYPE = WoodTypeBuilder.copyOf(WoodType.CRIMSON)
			.register(CopperInferno.id("scorched"), BlockSetType.CRIMSON);

	// Scorched wood set (9).
	public static Block SCORCHED_STEM;
	public static Block STRIPPED_SCORCHED_STEM;
	public static Block SCORCHED_HYPHAE;
	public static Block STRIPPED_SCORCHED_HYPHAE;
	public static Block SCORCHED_PLANKS;
	public static Block SCORCHED_SLAB;
	public static Block SCORCHED_STAIRS;
	public static Block SCORCHED_FENCE;
	public static Block SCORCHED_FENCE_GATE;

	// Wart blocks (2).
	public static Block SCORCHED_WART_BLOCK;
	public static Block EMBER_WART_BLOCK;

	// Small plants (6, cross model, CUTOUT — see InfernoFloraFeatureClient).
	public static Block EMBER_FUNGUS;
	public static Block ASH_SPROUTS;
	public static Block CINDER_ROOTS;
	public static Block SMOLDER_BLOOM;
	public static Block ASHEN_GRASS;
	public static Block SPORE_CLUSTER;

	// Moss + fungal utility blocks (5).
	public static Block EMBER_MOSS_BLOCK;
	public static Block EMBER_MOSS_CARPET;
	public static Block GLOWING_SPORE_BLOCK;
	public static Block FUNGAL_LIGHT;
	public static Block CINDER_NEST;

	/**
	 * Scorched wood settings — fresh instance per registration (ModBlocks.register writes the
	 * registry key into the instance). Vanilla nether-wood strength (2.0/3.0), nether-wood
	 * sounds, NO requiresTool (axe-breakable by hand).
	 */
	private static AbstractBlock.Settings woodSettings() {
		return AbstractBlock.Settings.create()
				.mapColor(MapColor.TERRACOTTA_GRAY)
				.strength(2.0F, 3.0F)
				.sounds(BlockSoundGroup.NETHER_WOOD);
	}

	/** Small-plant settings: no collision, instant break, given sound group + map color. */
	private static AbstractBlock.Settings plantSettings(BlockSoundGroup sounds, MapColor mapColor) {
		return AbstractBlock.Settings.create()
				.mapColor(mapColor)
				.noCollision()
				.breakInstantly()
				.sounds(sounds);
	}

	/** Wart-block settings (vanilla nether_wart_block-like: strength 1.0, wart sounds). */
	private static AbstractBlock.Settings wartSettings(MapColor mapColor) {
		return AbstractBlock.Settings.create()
				.mapColor(mapColor)
				.strength(1.0F)
				.sounds(BlockSoundGroup.NETHER_WART);
	}

	public static void init() {
		SCORCHED_STEM = ModBlocks.register("scorched_stem", PillarBlock::new, woodSettings(), true);
		STRIPPED_SCORCHED_STEM = ModBlocks.register("stripped_scorched_stem", PillarBlock::new, woodSettings(), true);
		SCORCHED_HYPHAE = ModBlocks.register("scorched_hyphae", PillarBlock::new, woodSettings(), true);
		STRIPPED_SCORCHED_HYPHAE = ModBlocks.register("stripped_scorched_hyphae", PillarBlock::new, woodSettings(), true);
		SCORCHED_PLANKS = ModBlocks.register("scorched_planks", Block::new, woodSettings(), true);
		SCORCHED_SLAB = ModBlocks.register("scorched_slab", SlabBlock::new, woodSettings(), true);
		SCORCHED_STAIRS = ModBlocks.register("scorched_stairs",
				s -> new ModBlockFamilies.PublicStairsBlock(SCORCHED_PLANKS.getDefaultState(), s), woodSettings(), true);
		SCORCHED_FENCE = ModBlocks.register("scorched_fence", FenceBlock::new, woodSettings(), true);
		SCORCHED_FENCE_GATE = ModBlocks.register("scorched_fence_gate",
				s -> new FenceGateBlock(SCORCHED_WOOD_TYPE, s), woodSettings(), true);

		SCORCHED_WART_BLOCK = ModBlocks.register("scorched_wart_block", Block::new,
				wartSettings(MapColor.TEAL), true);
		EMBER_WART_BLOCK = ModBlocks.register("ember_wart_block", Block::new,
				wartSettings(MapColor.DARK_RED), true);

		EMBER_FUNGUS = ModBlocks.register("ember_fungus", Block::new,
				plantSettings(BlockSoundGroup.NETHER_WART, MapColor.TEAL), true);
		ASH_SPROUTS = ModBlocks.register("ash_sprouts", Block::new,
				plantSettings(BlockSoundGroup.ROOTS, MapColor.LIGHT_GRAY), true);
		CINDER_ROOTS = ModBlocks.register("cinder_roots", Block::new,
				plantSettings(BlockSoundGroup.ROOTS, MapColor.DARK_RED), true);
		SMOLDER_BLOOM = ModBlocks.register("smolder_bloom", Block::new,
				plantSettings(BlockSoundGroup.NETHER_WART, MapColor.ORANGE).luminance(state -> 7), true);
		ASHEN_GRASS = ModBlocks.register("ashen_grass", Block::new,
				plantSettings(BlockSoundGroup.ROOTS, MapColor.GRAY), true);
		SPORE_CLUSTER = ModBlocks.register("spore_cluster", Block::new,
				plantSettings(BlockSoundGroup.NETHER_WART, MapColor.TEAL), true);

		EMBER_MOSS_BLOCK = ModBlocks.register("ember_moss_block", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.TEAL)
						.strength(0.1F)
						.sounds(BlockSoundGroup.MOSS_BLOCK),
				true);
		EMBER_MOSS_CARPET = ModBlocks.register("ember_moss_carpet", CarpetBlock::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.TEAL)
						.strength(0.1F)
						.sounds(BlockSoundGroup.MOSS_CARPET),
				true);
		GLOWING_SPORE_BLOCK = ModBlocks.register("glowing_spore_block", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.TEAL)
						.strength(1.0F)
						.sounds(BlockSoundGroup.SHROOMLIGHT)
						.luminance(state -> 8),
				true);
		// nonOpaque: the fungal_light texture has fully-transparent vent holes (CUTOUT render
		// layer, registered client-side); an opaque cube would x-ray through them.
		FUNGAL_LIGHT = ModBlocks.register("fungal_light", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.ORANGE)
						.strength(1.0F)
						.sounds(BlockSoundGroup.SHROOMLIGHT)
						.luminance(state -> 13)
						.nonOpaque(),
				true);
		CINDER_NEST = ModBlocks.register("cinder_nest", Block::new,
				AbstractBlock.Settings.create()
						.mapColor(MapColor.SPRUCE_BROWN)
						.strength(0.5F)
						.sounds(BlockSoundGroup.NETHER_WART),
				true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			entries.add(SCORCHED_STEM);
			entries.add(STRIPPED_SCORCHED_STEM);
			entries.add(SCORCHED_HYPHAE);
			entries.add(STRIPPED_SCORCHED_HYPHAE);
			entries.add(SCORCHED_PLANKS);
			entries.add(SCORCHED_STAIRS);
			entries.add(SCORCHED_SLAB);
			entries.add(SCORCHED_FENCE);
			entries.add(SCORCHED_FENCE_GATE);
			entries.add(SCORCHED_WART_BLOCK);
			entries.add(EMBER_WART_BLOCK);
			entries.add(EMBER_FUNGUS);
			entries.add(ASH_SPROUTS);
			entries.add(CINDER_ROOTS);
			entries.add(SMOLDER_BLOOM);
			entries.add(ASHEN_GRASS);
			entries.add(SPORE_CLUSTER);
			entries.add(EMBER_MOSS_BLOCK);
			entries.add(EMBER_MOSS_CARPET);
			entries.add(GLOWING_SPORE_BLOCK);
			entries.add(FUNGAL_LIGHT);
			entries.add(CINDER_NEST);
		});

		registerHandbookEntries();
	}

	/** One handbook entry per infernoflora recipe + the Inferno-flora dimension overview. */
	private static void registerHandbookEntries() {
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_scorched_planks",
				"copper_inferno:scorched_planks", "infernoflora/scorched_planks",
				new String[] {"copper_inferno:scorched_stem", "", "", "", "", "", "", "", ""},
				"copper_inferno:scorched_planks", 4,
				"Any scorched stem or hyphae block (stripped or not) crafts into 4 Scorched Planks.",
				"Jeder versengte Stiel- oder Hyphenblock (auch entrindet) ergibt 4 versengte Bretter."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_scorched_slab",
				"copper_inferno:scorched_slab", "infernoflora/scorched_slab",
				new String[] {"copper_inferno:scorched_planks", "copper_inferno:scorched_planks", "copper_inferno:scorched_planks",
						"", "", "", "", "", ""},
				"copper_inferno:scorched_slab", 6,
				"Three Scorched Planks in a row craft 6 Scorched Slabs.",
				"Drei versengte Bretter in einer Reihe ergeben 6 versengte Stufen."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_scorched_stairs",
				"copper_inferno:scorched_stairs", "infernoflora/scorched_stairs",
				new String[] {"copper_inferno:scorched_planks", "", "",
						"copper_inferno:scorched_planks", "copper_inferno:scorched_planks", "",
						"copper_inferno:scorched_planks", "copper_inferno:scorched_planks", "copper_inferno:scorched_planks"},
				"copper_inferno:scorched_stairs", 4,
				"The vanilla stair pattern of Scorched Planks crafts 4 Scorched Stairs.",
				"Das bekannte Treppenmuster aus versengten Brettern ergibt 4 versengte Treppen."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_scorched_fence",
				"copper_inferno:scorched_fence", "infernoflora/scorched_fence",
				new String[] {"copper_inferno:scorched_planks", "minecraft:stick", "copper_inferno:scorched_planks",
						"copper_inferno:scorched_planks", "minecraft:stick", "copper_inferno:scorched_planks",
						"", "", ""},
				"copper_inferno:scorched_fence", 3,
				"Scorched Planks and sticks craft 3 Scorched Fences.",
				"Versengte Bretter und Stoecke ergeben 3 versengte Zaeune."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_scorched_fence_gate",
				"copper_inferno:scorched_fence_gate", "infernoflora/scorched_fence_gate",
				new String[] {"minecraft:stick", "copper_inferno:scorched_planks", "minecraft:stick",
						"minecraft:stick", "copper_inferno:scorched_planks", "minecraft:stick",
						"", "", ""},
				"copper_inferno:scorched_fence_gate", 1,
				"Sticks and Scorched Planks craft a Scorched Fence Gate.",
				"Stoecke und versengte Bretter ergeben ein versengtes Zauntor."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_scorched_hyphae",
				"copper_inferno:scorched_hyphae", "infernoflora/scorched_hyphae",
				new String[] {"copper_inferno:scorched_stem", "copper_inferno:scorched_stem", "",
						"copper_inferno:scorched_stem", "copper_inferno:scorched_stem", "",
						"", "", ""},
				"copper_inferno:scorched_hyphae", 3,
				"Four Scorched Stems craft 3 Scorched Hyphae (bark on all six sides).",
				"Vier versengte Stiele ergeben 3 versengte Hyphen (Rinde auf allen sechs Seiten)."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_stripped_scorched_stem",
				"copper_inferno:stripped_scorched_stem", "infernoflora/stripped_scorched_stem",
				new String[] {"copper_inferno:scorched_stem", "", "", "", "", "", "", "", ""},
				"copper_inferno:stripped_scorched_stem", 1,
				"A Scorched Stem crafts directly into its stripped variant (no axe-stripping interaction).",
				"Ein versengter Stiel wird direkt zur entrindeten Variante verarbeitet (kein Entrinden per Axt)."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_stripped_scorched_hyphae",
				"copper_inferno:stripped_scorched_hyphae", "infernoflora/stripped_scorched_hyphae",
				new String[] {"copper_inferno:scorched_hyphae", "", "", "", "", "", "", "", ""},
				"copper_inferno:stripped_scorched_hyphae", 1,
				"Scorched Hyphae craft directly into their stripped variant (no axe-stripping interaction).",
				"Versengte Hyphen werden direkt zur entrindeten Variante verarbeitet (kein Entrinden per Axt)."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_ember_wart_block",
				"copper_inferno:ember_wart_block", "infernoflora/ember_wart_block",
				new String[] {"copper_inferno:ember_fungus", "copper_inferno:ember_fungus", "copper_inferno:ember_fungus",
						"copper_inferno:ember_fungus", "copper_inferno:ember_fungus", "copper_inferno:ember_fungus",
						"copper_inferno:ember_fungus", "copper_inferno:ember_fungus", "copper_inferno:ember_fungus"},
				"copper_inferno:ember_wart_block", 1,
				"Nine Ember Fungi compress into an Ember Wart Block.",
				"Neun Glutpilze ergeben einen Glutwarzenblock."));
		HandbookEntries.add(new HandbookEntry("blocks", "infernoflora_ember_moss_carpet",
				"copper_inferno:ember_moss_carpet", "infernoflora/ember_moss_carpet",
				new String[] {"copper_inferno:ember_moss_block", "copper_inferno:ember_moss_block", "",
						"", "", "", "", "", ""},
				"copper_inferno:ember_moss_carpet", 3,
				"Two Ember Moss Blocks craft 3 Ember Moss Carpets.",
				"Zwei Glutmoosbloecke ergeben 3 Glutmoosteppiche."));
		HandbookEntries.add(new HandbookEntry("dimension", "infernoflora_overview",
				"copper_inferno:ember_fungus", null, null, null, 0,
				"Flora of the Inferno: scorched fungus trees (stem, hyphae, full plank set), teal ember fungi "
						+ "and spore growths, glowing smolder blooms (light 7), ember moss, glowing spore blocks "
						+ "(light 8) and fungal lights (light 13). The small plants are hardy — they can be "
						+ "placed on any surface.",
				"Flora des Infernos: versengte Pilzbaeume (Stiel, Hyphen, komplettes Bretter-Set), tuerkise "
						+ "Glutpilze und Sporengewaechse, leuchtende Schwelblueten (Licht 7), Glutmoos, "
						+ "Leuchtsporenbloecke (Licht 8) und Pilzlichter (Licht 13). Die kleinen Pflanzen sind "
						+ "robust — sie koennen auf jeder Oberflaeche platziert werden."));
	}
}
