package net.sonic0810.copperinferno.feature.artifacts;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ToolMaterial;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModBlockEntities;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Artifacts" feature (WP17) — 8 named gadget/artifact features, each its own class:
 * <ol>
 * <li>{@link GrapplingCoilItem} — raycast pull toward the hit block.</li>
 * <li>{@link EmberShieldItem} — parry window: fire resistance + ignites nearby hostiles.</li>
 * <li>{@link FizzJetpackItem} — chest trinket, crouch-jump launch with fizz particles.</li>
 * <li>{@link DoomHornItem} — AoE fear (Slowness + Darkness) + the DOOM_KICK sample.</li>
 * <li>{@link CopperDrillItem} — a pickaxe that mines a 3x1 line.</li>
 * <li>{@link HeatSuitBonus} — full WP6 arsenal armor tier = fire immunity (tick check,
 *     detects the arsenal pieces by item id only).</li>
 * <li>{@link BrewKegBlock} — stores up to 16 drinks, right-click dispenses (block entity).</li>
 * <li>{@link TrophyPedestalBlock} — displays any item (block entity + client renderer,
 *     statue-renderer pattern).</li>
 * </ol>
 *
 * <p>Assets (textures, item defs/models, blockstates, loot tables, recipes under
 * {@code recipe/artifacts/}, the drill repair tag, lang fragments EN + DE, the vanilla-tag
 * fragment) are generated by {@code devtools/gen/artifacts_gen.py}. Every crafting recipe
 * includes at least one arsenal/gemalloy/soda item unique to this mod, so no vanilla/mod
 * input collisions are possible (checked by devtools/check_recipe_collisions.py).
 */
public final class ArtifactsFeature {
	private ArtifactsFeature() {
	}

	/** Repair tag, backed by data/copper_inferno/tags/item/copper_drill_repair.json. */
	public static final TagKey<Item> REPAIRS_COPPER_DRILL =
			TagKey.of(RegistryKeys.ITEM, CopperInferno.id("copper_drill_repair"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed, attackDamageBonus,
	 * enchantmentValue, repairItems) — verified via javap (same as ArsenalFeature). The drill
	 * sits between iron and diamond, repairing from copper ingots.
	 */
	public static final ToolMaterial COPPER_DRILL_TOOL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_IRON_TOOL, 600, 6.5F, 1.0F, 14, REPAIRS_COPPER_DRILL);

	public static Item GRAPPLING_COIL;
	public static Item EMBER_SHIELD;
	public static Item FIZZ_JETPACK;
	public static Item DOOM_HORN;
	public static Item COPPER_DRILL;

	public static Block BREW_KEG;
	public static Block TROPHY_PEDESTAL;

	public static BlockEntityType<BrewKegBlockEntity> BREW_KEG_BLOCK_ENTITY;
	public static BlockEntityType<TrophyPedestalBlockEntity> TROPHY_PEDESTAL_BLOCK_ENTITY;

	public static void init() {
		// ----- items (every registration uses a FRESH Settings and a LITERAL id)
		GRAPPLING_COIL = ModItems.register("grappling_coil", GrapplingCoilItem::new,
				new Item.Settings().maxDamage(250));
		EMBER_SHIELD = ModItems.register("ember_shield", EmberShieldItem::new,
				new Item.Settings().maxDamage(228));
		FIZZ_JETPACK = ModItems.register("fizz_jetpack", FizzJetpackItem::new,
				new Item.Settings().maxDamage(256).equippable(EquipmentSlot.CHEST));
		DOOM_HORN = ModItems.register("doom_horn", DoomHornItem::new,
				new Item.Settings().maxCount(1).rarity(Rarity.UNCOMMON));
		COPPER_DRILL = ModItems.register("copper_drill", CopperDrillItem::new,
				new Item.Settings().pickaxe(COPPER_DRILL_TOOL, 1.0F, -2.8F));

		// ----- blocks (no requiresTool: like the statue they always drop, tool tags are
		// only a mining-speed nicety via devtools/tagfrag/artifacts.json)
		BREW_KEG = ModBlocks.register("brew_keg", BrewKegBlock::new,
				AbstractBlock.Settings.create()
						.strength(2.5f)
						.sounds(BlockSoundGroup.WOOD),
				true);
		TROPHY_PEDESTAL = ModBlocks.register("trophy_pedestal", TrophyPedestalBlock::new,
				AbstractBlock.Settings.create()
						.strength(2.0f, 6.0f)
						.sounds(BlockSoundGroup.COPPER)
						.nonOpaque(),
				true);

		BREW_KEG_BLOCK_ENTITY = ModBlockEntities.register("brew_keg",
				BrewKegBlockEntity::new, BREW_KEG);
		TROPHY_PEDESTAL_BLOCK_ENTITY = ModBlockEntities.register("trophy_pedestal",
				TrophyPedestalBlockEntity::new, TROPHY_PEDESTAL);

		// ----- the itemless feature: the arsenal-armor set bonus tick check
		HeatSuitBonus.init();

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			entries.add(GRAPPLING_COIL);
			entries.add(EMBER_SHIELD);
			entries.add(FIZZ_JETPACK);
			entries.add(DOOM_HORN);
			entries.add(COPPER_DRILL);
		});
		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			entries.add(BREW_KEG);
			entries.add(TROPHY_PEDESTAL);
		});

		registerHandbookEntries();
	}

	private static void registerHandbookEntries() {
		final String CU = "minecraft:copper_ingot";

		HandbookEntries.add(new HandbookEntry("gear", "artifact_grappling_coil",
				"copper_inferno:grappling_coil", "artifacts/grappling_coil",
				new String[]{"copper_inferno:grapnel_hook", "", "", "copper_inferno:talisman_cord", "", "", CU, "", ""},
				"copper_inferno:grappling_coil", 1,
				"The Grappling Coil reels you IN: aim at a block within 24 blocks and use - the barbed anchor bites and the coil yanks you toward it. A miss costs nothing.",
				"Die Greifhaken-Spule zieht dich HERAN: ziele auf einen Block in bis zu 24 Bl\u00f6cken Entfernung und benutze sie - der Widerhaken bei\u00dft sich fest und die Spule rei\u00dft dich hinzu. Ein Fehlschuss kostet nichts."));
		HandbookEntries.add(new HandbookEntry("gear", "artifact_ember_shield",
				"copper_inferno:ember_shield", "artifacts/ember_shield",
				new String[]{"", "copper_inferno:tempered_plate", "", "copper_inferno:tempered_plate", "minecraft:magma_cream", "copper_inferno:tempered_plate", "", CU, ""},
				"copper_inferno:ember_shield", 1,
				"Raise the Ember Shield for a 5-second parry window of Fire Resistance while its molten core flash-ignites every hostile within 4 blocks. 8s cooldown.",
				"Hebe den Glutschild f\u00fcr ein 5-Sekunden-Parierfenster mit Feuerresistenz, w\u00e4hrend sein geschmolzener Kern jeden Feind im Umkreis von 4 Bl\u00f6cken entz\u00fcndet. 8s Abklingzeit."));
		HandbookEntries.add(new HandbookEntry("gear", "artifact_fizz_jetpack",
				"copper_inferno:fizz_jetpack", "artifacts/fizz_jetpack",
				new String[]{"copper_inferno:tempered_plate", "copper_inferno:dr_pepper", "copper_inferno:tempered_plate",
						"copper_inferno:tempered_plate", "copper_inferno:dr_pepper", "copper_inferno:tempered_plate",
						"", "minecraft:feather", ""},
				"copper_inferno:fizz_jetpack", 1,
				"Strap the Fizz Jetpack into your chest slot, then CROUCH-JUMP: two shaken Dr.Pepper kegs blast you skyward in a plume of foam. 3s cooldown per launch.",
				"Schnalle das Brause-Jetpack in den Brustslot und mache einen HOCK-SPRUNG: zwei gesch\u00fcttelte Dr.Pepper-F\u00e4sser schie\u00dfen dich in einer Schaumfont\u00e4ne himmelw\u00e4rts. 3s Abklingzeit pro Start."));
		HandbookEntries.add(new HandbookEntry("gear", "artifact_doom_horn",
				"copper_inferno:doom_horn", "artifacts/doom_horn",
				new String[]{"copper_inferno:doom_alloy_shard", "copper_inferno:horn_valve", CU, "", "", "", "", "", ""},
				"copper_inferno:doom_horn", 1,
				"The Doom Horn blasts the DOOM kick itself: every creature within 8 blocks is gripped by fear - Slowness II and Darkness for 8 seconds. 15s cooldown.",
				"Das Doom-Horn schmettert den DOOM-Kick h\u00f6chstpers\u00f6nlich: jedes Wesen im Umkreis von 8 Bl\u00f6cken packt die Angst - Langsamkeit II und Dunkelheit f\u00fcr 8 Sekunden. 15s Abklingzeit."));
		HandbookEntries.add(new HandbookEntry("gear", "artifact_copper_drill",
				"copper_inferno:copper_drill", "artifacts/copper_drill",
				new String[]{CU, CU, CU, CU, "copper_inferno:tool_matrix", CU, "", "minecraft:stick", ""},
				"copper_inferno:copper_drill", 1,
				"The Copper Drill is a pickaxe that bores a 3x1 LINE: each broken block also drills the next two along your line of sight, drops and durability included.",
				"Der Kupferbohrer ist eine Spitzhacke, die eine 3x1-LINIE bohrt: jeder abgebaute Block bohrt auch die n\u00e4chsten zwei entlang deiner Blickrichtung mit - Drops und Haltbarkeit inklusive."));
		HandbookEntries.add(new HandbookEntry("gear", "artifact_heat_suit_bonus",
				"copper_inferno:pyrium_chestplate", null,
				null, null, 0,
				"Heat Suit Bonus: wear all FOUR pieces of one arsenal tier (pyrium, emberite, ashsteel or voidsteel) and the suit seals itself - total fire immunity while the set is complete.",
				"Hitzeanzug-Bonus: trage alle VIER Teile einer Arsenal-Stufe (Pyrium, Emberite, Ashsteel oder Voidsteel) und der Anzug versiegelt sich - v\u00f6llige Feuerimmunit\u00e4t, solange das Set komplett ist."));
		HandbookEntries.add(new HandbookEntry("gear", "artifact_brew_keg",
				"copper_inferno:brew_keg", "artifacts/brew_keg",
				new String[]{"minecraft:oak_planks", CU, "minecraft:oak_planks",
						"minecraft:oak_planks", "copper_inferno:dr_pepper", "minecraft:oak_planks",
						"minecraft:oak_planks", "minecraft:oak_planks", "minecraft:oak_planks"},
				"copper_inferno:brew_keg", 1,
				"The Brew Keg stores up to 16 drinks - Dr.Pepper, potions, anything drinkable. Right-click with a drink to pour it in, right-click empty-handed to tap one back out.",
				"Das Braufass lagert bis zu 16 Getr\u00e4nke - Dr.Pepper, Tr\u00e4nke, alles Trinkbare. Rechtsklick mit einem Getr\u00e4nk f\u00fcllt es ein, Rechtsklick mit leerer Hand zapft eines wieder aus."));
		HandbookEntries.add(new HandbookEntry("gear", "artifact_trophy_pedestal",
				"copper_inferno:trophy_pedestal", "artifacts/trophy_pedestal",
				new String[]{"minecraft:smooth_stone_slab", "minecraft:smooth_stone_slab", "minecraft:smooth_stone_slab",
						"", "copper_inferno:gilded_rivet", "",
						"minecraft:smooth_stone_slab", "minecraft:smooth_stone_slab", "minecraft:smooth_stone_slab"},
				"copper_inferno:trophy_pedestal", 1,
				"The Trophy Pedestal displays any item floating above its gilded column. Right-click with an item to enshrine it, right-click empty-handed to take it down.",
				"Der Troph\u00e4ensockel pr\u00e4sentiert jeden Gegenstand schwebend \u00fcber seiner vergoldeten S\u00e4ule. Rechtsklick mit einem Gegenstand stellt ihn aus, Rechtsklick mit leerer Hand nimmt ihn herunter."));
	}
}
