package net.sonic0810.copperinferno.feature.chromacopper;

import java.util.List;
import java.util.function.Supplier;

import net.minecraft.block.AbstractBlock;
import net.minecraft.block.LanternBlock;
import net.minecraft.block.MapColor;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.content.PaletteSets;
import net.sonic0810.copperinferno.core.content.PaletteSets.PaletteSet;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Chromatic Copper" feature: 16 tinted-copper palettes x the 20-block palette template
 * (320 blocks) registered via {@link PaletteSets#registerPaletteSet} into the CHROMATIC
 * creative tab.
 *
 * <p>AUDIT CONTRACT (devtools/audit_assets.py check (f)): every {@code registerPaletteSet}
 * call below passes a STRING LITERAL as the leading palette argument — never a variable or
 * loop value. 16 literal call sites = 16 x 20 audited ids.
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes, EN+DE
 * lang fragments, tag fragment) are generated by {@code devtools/gen/chromacopper_gen.py};
 * the tag fragment lives at {@code devtools/tagfrag/chromacopper.json}.
 *
 * <p>Note: the "gilded" palette is registered as {@code tinted_gilded_copper} because plain
 * {@code gilded_copper_bricks}/{@code _brick_slab}/{@code _brick_stairs}/{@code _brick_wall}
 * already exist (copperdeco feature).
 */
public final class ChromaCopperFeature {
	private ChromaCopperFeature() {
	}

	public static PaletteSet AZURE;
	public static PaletteSet CRIMSON;
	public static PaletteSet TINTED_GILDED;
	public static PaletteSet COBALT;
	public static PaletteSet EMERALD;
	public static PaletteSet AMETHYST;
	public static PaletteSet OBSIDIAN;
	public static PaletteSet IVORY;
	public static PaletteSet JADE;
	public static PaletteSet UMBER;
	public static PaletteSet SCARLET;
	public static PaletteSet INDIGO;
	public static PaletteSet VIRIDIAN;
	public static PaletteSet ONYX;
	public static PaletteSet PEARL;
	public static PaletteSet SAFFRON;

	private static List<PaletteSet> all;

	/** All 16 palette sets in registration order (for the client render-layer hookup). */
	public static List<PaletteSet> all() {
		return all;
	}

	/**
	 * Copper-like stone profile. Returned SUPPLIER is invoked fresh per registration
	 * ({@code ModBlocks.register} writes a registry key into every settings instance).
	 */
	private static Supplier<AbstractBlock.Settings> chromaStone(MapColor color) {
		return () -> AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.0F, 6.0F)
				.requiresTool()
				.sounds(BlockSoundGroup.COPPER);
	}

	/** Fragile tinted glass: glass sounds, nonOpaque, NO requiresTool. */
	private static Supplier<AbstractBlock.Settings> chromaGlass(MapColor color) {
		return () -> AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(0.4F)
				.sounds(BlockSoundGroup.GLASS)
				.nonOpaque();
	}

	/**
	 * Light-source profile shared by {@code <palette>_lamp} and {@code <palette>_lantern}
	 * (PaletteSets feeds BOTH from this one supplier): the lamp glows at 15, the lantern at
	 * 14 — resolved per block state, since only the lantern is a {@link LanternBlock}.
	 */
	private static Supplier<AbstractBlock.Settings> chromaLamp(MapColor color) {
		return () -> AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.0F, 6.0F)
				.requiresTool()
				.sounds(BlockSoundGroup.COPPER)
				.luminance(state -> state.getBlock() instanceof LanternBlock ? 14 : 15);
	}

	public static void init() {
		AZURE = PaletteSets.registerPaletteSet("azure_copper",
				chromaStone(MapColor.LIGHT_BLUE), chromaGlass(MapColor.LIGHT_BLUE),
				chromaLamp(MapColor.LIGHT_BLUE), ModCreativeTab.CHROMATIC_KEY);
		CRIMSON = PaletteSets.registerPaletteSet("crimson_copper",
				chromaStone(MapColor.RED), chromaGlass(MapColor.RED),
				chromaLamp(MapColor.RED), ModCreativeTab.CHROMATIC_KEY);
		TINTED_GILDED = PaletteSets.registerPaletteSet("tinted_gilded_copper",
				chromaStone(MapColor.GOLD), chromaGlass(MapColor.GOLD),
				chromaLamp(MapColor.GOLD), ModCreativeTab.CHROMATIC_KEY);
		COBALT = PaletteSets.registerPaletteSet("cobalt_copper",
				chromaStone(MapColor.LAPIS_BLUE), chromaGlass(MapColor.LAPIS_BLUE),
				chromaLamp(MapColor.LAPIS_BLUE), ModCreativeTab.CHROMATIC_KEY);
		EMERALD = PaletteSets.registerPaletteSet("emerald_copper",
				chromaStone(MapColor.EMERALD_GREEN), chromaGlass(MapColor.EMERALD_GREEN),
				chromaLamp(MapColor.EMERALD_GREEN), ModCreativeTab.CHROMATIC_KEY);
		AMETHYST = PaletteSets.registerPaletteSet("amethyst_copper",
				chromaStone(MapColor.PURPLE), chromaGlass(MapColor.PURPLE),
				chromaLamp(MapColor.PURPLE), ModCreativeTab.CHROMATIC_KEY);
		OBSIDIAN = PaletteSets.registerPaletteSet("obsidian_copper",
				chromaStone(MapColor.BLACK), chromaGlass(MapColor.BLACK),
				chromaLamp(MapColor.BLACK), ModCreativeTab.CHROMATIC_KEY);
		IVORY = PaletteSets.registerPaletteSet("ivory_copper",
				chromaStone(MapColor.OFF_WHITE), chromaGlass(MapColor.OFF_WHITE),
				chromaLamp(MapColor.OFF_WHITE), ModCreativeTab.CHROMATIC_KEY);
		JADE = PaletteSets.registerPaletteSet("jade_copper",
				chromaStone(MapColor.LIME), chromaGlass(MapColor.LIME),
				chromaLamp(MapColor.LIME), ModCreativeTab.CHROMATIC_KEY);
		UMBER = PaletteSets.registerPaletteSet("umber_copper",
				chromaStone(MapColor.BROWN), chromaGlass(MapColor.BROWN),
				chromaLamp(MapColor.BROWN), ModCreativeTab.CHROMATIC_KEY);
		SCARLET = PaletteSets.registerPaletteSet("scarlet_copper",
				chromaStone(MapColor.BRIGHT_RED), chromaGlass(MapColor.BRIGHT_RED),
				chromaLamp(MapColor.BRIGHT_RED), ModCreativeTab.CHROMATIC_KEY);
		INDIGO = PaletteSets.registerPaletteSet("indigo_copper",
				chromaStone(MapColor.MAGENTA), chromaGlass(MapColor.MAGENTA),
				chromaLamp(MapColor.MAGENTA), ModCreativeTab.CHROMATIC_KEY);
		VIRIDIAN = PaletteSets.registerPaletteSet("viridian_copper",
				chromaStone(MapColor.CYAN), chromaGlass(MapColor.CYAN),
				chromaLamp(MapColor.CYAN), ModCreativeTab.CHROMATIC_KEY);
		ONYX = PaletteSets.registerPaletteSet("onyx_copper",
				chromaStone(MapColor.DEEPSLATE_GRAY), chromaGlass(MapColor.DEEPSLATE_GRAY),
				chromaLamp(MapColor.DEEPSLATE_GRAY), ModCreativeTab.CHROMATIC_KEY);
		PEARL = PaletteSets.registerPaletteSet("pearl_copper",
				chromaStone(MapColor.LIGHT_GRAY), chromaGlass(MapColor.LIGHT_GRAY),
				chromaLamp(MapColor.LIGHT_GRAY), ModCreativeTab.CHROMATIC_KEY);
		SAFFRON = PaletteSets.registerPaletteSet("saffron_copper",
				chromaStone(MapColor.ORANGE), chromaGlass(MapColor.ORANGE),
				chromaLamp(MapColor.ORANGE), ModCreativeTab.CHROMATIC_KEY);

		all = List.of(AZURE, CRIMSON, TINTED_GILDED, COBALT, EMERALD, AMETHYST, OBSIDIAN,
				IVORY, JADE, UMBER, SCARLET, INDIGO, VIRIDIAN, ONYX, PEARL, SAFFRON);

		registerHandbookEntries();
	}

	// ------------------------------------------------------------------
	// Handbook: one curated page per palette, documenting the base-block dye recipe
	// (recipe id chromacopper/<palette>, 8 copper blocks ringed around one dye -> 8 blocks).
	// ------------------------------------------------------------------

	private static void addPaletteEntry(String palette, String dyeId, String nameEn, String nameDe,
			String dyeEn, String dyeDe) {
		String block = "copper_inferno:" + palette;
		String c = "minecraft:copper_block";
		HandbookEntries.add(new HandbookEntry("blocks", "chromacopper_" + palette,
				block, "chromacopper/" + palette,
				new String[]{c, c, c, c, dyeId, c, c, c, c}, block, 8,
				"Eight Copper Blocks ringed around " + dyeEn + " tint into eight blocks of "
						+ nameEn + ". The stonecutter turns the block into every other shape of the "
						+ "palette (bricks, tiles, slabs, stairs, walls, chiseled, carved, pillar, "
						+ "cut, lamp, lantern); smelting it yields " + nameEn + " Glass.",
				"Acht Kupferbl\u00f6cke, in der Mitte " + dyeDe + " \u2014 das ergibt acht Bl\u00f6cke "
						+ nameDe + ". Die Steins\u00e4ge macht daraus jede weitere Form der Palette "
						+ "(Ziegel, Fliesen, Stufen, Treppen, Mauern, gemei\u00dfelt, verziert, S\u00e4ule, "
						+ "geschnitten, Lampe, Laterne); im Ofen geschmolzen entsteht " + nameDe + "glas."));
	}

	private static void registerHandbookEntries() {
		addPaletteEntry("azure_copper", "minecraft:light_blue_dye",
				"Azure Copper", "Azurkupfer", "Light Blue Dye", "Hellblauer Farbstoff");
		addPaletteEntry("crimson_copper", "minecraft:red_dye",
				"Crimson Copper", "Karmesinkupfer", "Red Dye", "Roter Farbstoff");
		addPaletteEntry("tinted_gilded_copper", "minecraft:yellow_dye",
				"Tinted Gilded Copper", "Goldtonkupfer", "Yellow Dye", "Gelber Farbstoff");
		addPaletteEntry("cobalt_copper", "minecraft:blue_dye",
				"Cobalt Copper", "Kobaltkupfer", "Blue Dye", "Blauer Farbstoff");
		addPaletteEntry("emerald_copper", "minecraft:green_dye",
				"Emerald Copper", "Smaragdkupfer", "Green Dye", "Gr\u00fcner Farbstoff");
		addPaletteEntry("amethyst_copper", "minecraft:purple_dye",
				"Amethyst Copper", "Amethystkupfer", "Purple Dye", "Violetter Farbstoff");
		addPaletteEntry("obsidian_copper", "minecraft:black_dye",
				"Obsidian Copper", "Obsidiankupfer", "Black Dye", "Schwarzer Farbstoff");
		addPaletteEntry("ivory_copper", "minecraft:white_dye",
				"Ivory Copper", "Elfenbeinkupfer", "White Dye", "Wei\u00dfer Farbstoff");
		addPaletteEntry("jade_copper", "minecraft:lime_dye",
				"Jade Copper", "Jadekupfer", "Lime Dye", "Hellgr\u00fcner Farbstoff");
		addPaletteEntry("umber_copper", "minecraft:brown_dye",
				"Umber Copper", "Umbrakupfer", "Brown Dye", "Brauner Farbstoff");
		addPaletteEntry("scarlet_copper", "minecraft:pink_dye",
				"Scarlet Copper", "Scharlachkupfer", "Pink Dye", "Rosa Farbstoff");
		addPaletteEntry("indigo_copper", "minecraft:magenta_dye",
				"Indigo Copper", "Indigokupfer", "Magenta Dye", "Magenta Farbstoff");
		addPaletteEntry("viridian_copper", "minecraft:cyan_dye",
				"Viridian Copper", "Viridiankupfer", "Cyan Dye", "T\u00fcrkiser Farbstoff");
		addPaletteEntry("onyx_copper", "minecraft:gray_dye",
				"Onyx Copper", "Onyxkupfer", "Gray Dye", "Grauer Farbstoff");
		addPaletteEntry("pearl_copper", "minecraft:light_gray_dye",
				"Pearl Copper", "Perlkupfer", "Light Gray Dye", "Hellgrauer Farbstoff");
		addPaletteEntry("saffron_copper", "minecraft:orange_dye",
				"Saffron Copper", "Safrankupfer", "Orange Dye", "Oranger Farbstoff");
	}
}
