package net.sonic0810.copperinferno.feature.bosslords;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.mob.AbstractSkeletonEntity;
import net.minecraft.entity.mob.BlazeEntity;
import net.minecraft.entity.mob.GhastEntity;
import net.minecraft.entity.mob.RavagerEntity;
import net.minecraft.entity.passive.IronGolemEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.util.Rarity;
import net.minecraft.util.math.Vec3d;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Inferno Lords": six multi-phase boss fights, each replicating the proven infernoboss
 * architecture (vanilla base entity + {@code core.boss.BossBarHolder} + SpawnGroup.MISC +
 * setPersistent + FabricDefaultAttributeRegistry attributes + summon item + loot table +
 * spawn egg + handbook entries). Every boss has two health phases (ability shift at 50%),
 * a timed special ability and an enrage/defensive stance - see the individual entity
 * classes. Assets (item defs/models/textures, entity textures, loot tables, recipes, lang
 * fragments) are generated by {@code devtools/gen/bosslords_gen.py}.
 */
public final class BossLordsFeature {
	private BossLordsFeature() {
	}

	public static EntityType<TheSlagKingEntity> THE_SLAG_KING;
	public static EntityType<EmberMatriarchEntity> EMBER_MATRIARCH;
	public static EntityType<AshColossusEntity> ASH_COLOSSUS;
	public static EntityType<MagmaLeviathanEntity> MAGMA_LEVIATHAN;
	public static EntityType<CinderReaperEntity> CINDER_REAPER;
	public static EntityType<ForgeTyrantEntity> FORGE_TYRANT;

	public static Item SLAG_KING_CORE;
	public static Item EMBER_MATRIARCH_SIGIL;
	public static Item ASH_COLOSSUS_CORE;
	public static Item MAGMA_LEVIATHAN_SIGIL;
	public static Item CINDER_REAPER_SIGIL;
	public static Item FORGE_TYRANT_CORE;

	public static Item ROYAL_SLAG;
	public static Item FISSURE_SHARD;
	public static Item SLAG_CROWN;
	public static Item MATRIARCH_PLUME;
	public static Item LIVING_FLAME;
	public static Item MATRIARCH_DIADEM;
	public static Item COLOSSAL_ASH;
	public static Item BLINDING_GRIT;
	public static Item ASH_COLOSSUS_IDOL;
	public static Item LEVIATHAN_SCALE;
	public static Item MAGMA_BOMB_SHELL;
	public static Item LEVIATHAN_MAW;
	public static Item REAPER_CINDER;
	public static Item WITHERED_CLOTH;
	public static Item CINDER_SCYTHE;
	public static Item FORGE_SCRAP;
	public static Item TYRANT_HIDE;
	public static Item TYRANTS_ANVIL;

	public static Item THE_SLAG_KING_SPAWN_EGG;
	public static Item EMBER_MATRIARCH_SPAWN_EGG;
	public static Item ASH_COLOSSUS_SPAWN_EGG;
	public static Item MAGMA_LEVIATHAN_SPAWN_EGG;
	public static Item CINDER_REAPER_SPAWN_EGG;
	public static Item FORGE_TYRANT_SPAWN_EGG;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		registerHandbookEntries();
	}

	private static void registerEntityTypes() {
		// Base dimensions copied 1:1 from the vanilla EntityType registrations (bytecode
		// verified via javap -c on EntityType's <clinit>: iron_golem =
		// dimensions(1.4f, 2.7f); blaze = makeFireImmune().dimensions(0.6f, 1.8f); ghast =
		// makeFireImmune().dimensions(4.0f, 4.0f).eyeHeight(2.6f)
		// .passengerAttachments(4.0625f).vehicleAttachment(0.5f); skeleton =
		// dimensions(0.6f, 1.99f).eyeHeight(1.74f).vehicleAttachment(-0.7f); ravager =
		// dimensions(1.95f, 2.2f).passengerAttachments(new Vec3d(0.0, 2.2625, -0.0625))).
		// The bosses' bulk comes from the SCALE attribute; all get the extended tracking
		// range 10 so the boss bar/model appear well before the fight (infernoboss
		// precedent). Summoned bosses call setPersistent, so MISC (no natural despawn
		// logic) fits all six. Builders are created FRESH per registration.
		THE_SLAG_KING = ModEntities.register("the_slag_king",
				EntityType.Builder.create(TheSlagKingEntity::new, SpawnGroup.MISC)
						.dimensions(1.4f, 2.7f)
						.maxTrackingRange(10));
		EMBER_MATRIARCH = ModEntities.register("ember_matriarch",
				EntityType.Builder.create(EmberMatriarchEntity::new, SpawnGroup.MISC)
						.makeFireImmune()
						.dimensions(0.6f, 1.8f)
						.maxTrackingRange(10));
		ASH_COLOSSUS = ModEntities.register("ash_colossus",
				EntityType.Builder.create(AshColossusEntity::new, SpawnGroup.MISC)
						.dimensions(1.4f, 2.7f)
						.maxTrackingRange(10));
		MAGMA_LEVIATHAN = ModEntities.register("magma_leviathan",
				EntityType.Builder.create(MagmaLeviathanEntity::new, SpawnGroup.MISC)
						.makeFireImmune()
						.dimensions(4.0f, 4.0f)
						.eyeHeight(2.6f)
						.passengerAttachments(4.0625f)
						.vehicleAttachment(0.5f)
						.maxTrackingRange(10));
		CINDER_REAPER = ModEntities.register("cinder_reaper",
				EntityType.Builder.create(CinderReaperEntity::new, SpawnGroup.MISC)
						.dimensions(0.6f, 1.99f)
						.eyeHeight(1.74f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(10));
		FORGE_TYRANT = ModEntities.register("forge_tyrant",
				EntityType.Builder.create(ForgeTyrantEntity::new, SpawnGroup.MISC)
						.dimensions(1.95f, 2.2f)
						.passengerAttachments(new Vec3d(0.0, 2.2625, -0.0625))
						.maxTrackingRange(10));
	}

	private static void registerAttributes() {
		// EntityAttributes fields have no GENERIC_ prefix in 1.21.9 (infernoboss precedent,
		// javap-verified); DefaultAttributeContainer.Builder.add(...) overrides base values.
		// MAX_HEALTH spans 240-600, SCALE 1.8-3.5, FOLLOW_RANGE 48-64 across the roster.
		FabricDefaultAttributeRegistry.register(THE_SLAG_KING, IronGolemEntity.createIronGolemAttributes()
				.add(EntityAttributes.MAX_HEALTH, 500.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 20.0)
				.add(EntityAttributes.SCALE, 3.0)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 1.0)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(EMBER_MATRIARCH, BlazeEntity.createBlazeAttributes()
				.add(EntityAttributes.MAX_HEALTH, 300.0)
				.add(EntityAttributes.SCALE, 2.2)
				.add(EntityAttributes.FOLLOW_RANGE, 64.0));
		FabricDefaultAttributeRegistry.register(ASH_COLOSSUS, IronGolemEntity.createIronGolemAttributes()
				.add(EntityAttributes.MAX_HEALTH, 550.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 22.0)
				.add(EntityAttributes.SCALE, 3.5)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 1.0)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(MAGMA_LEVIATHAN, GhastEntity.createGhastAttributes()
				.add(EntityAttributes.MAX_HEALTH, 400.0)
				.add(EntityAttributes.SCALE, 1.8)
				.add(EntityAttributes.FOLLOW_RANGE, 64.0));
		// Abstract-skeleton attributes carry no ATTACK_DAMAGE base (vanilla skeleton damage
		// comes from the bow), so the melee reaper adds it explicitly for its scythe.
		FabricDefaultAttributeRegistry.register(CINDER_REAPER, AbstractSkeletonEntity.createAbstractSkeletonAttributes()
				.add(EntityAttributes.MAX_HEALTH, 240.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 8.0)
				.add(EntityAttributes.SCALE, 1.8)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(FORGE_TYRANT, RavagerEntity.createRavagerAttributes()
				.add(EntityAttributes.MAX_HEALTH, 600.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 18.0)
				.add(EntityAttributes.SCALE, 2.0)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 1.0)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
	}

	private static void registerItems() {
		// Summon items (TitanSigilItem behavior, generalized): the sigils/cores for the
		// Ember Matriarch, Magma Leviathan and Forge Tyrant only answer inside the Inferno
		// dimension; the other three work anywhere. Settings are FRESH per registration.
		SLAG_KING_CORE = ModItems.register("slag_king_core",
				s -> new BossLordSummonItem(s, w -> new TheSlagKingEntity(THE_SLAG_KING, w), false),
				new Item.Settings());
		EMBER_MATRIARCH_SIGIL = ModItems.register("ember_matriarch_sigil",
				s -> new BossLordSummonItem(s, w -> new EmberMatriarchEntity(EMBER_MATRIARCH, w), true),
				new Item.Settings());
		ASH_COLOSSUS_CORE = ModItems.register("ash_colossus_core",
				s -> new BossLordSummonItem(s, w -> new AshColossusEntity(ASH_COLOSSUS, w), false),
				new Item.Settings());
		MAGMA_LEVIATHAN_SIGIL = ModItems.register("magma_leviathan_sigil",
				s -> new BossLordSummonItem(s, w -> new MagmaLeviathanEntity(MAGMA_LEVIATHAN, w), true),
				new Item.Settings());
		CINDER_REAPER_SIGIL = ModItems.register("cinder_reaper_sigil",
				s -> new BossLordSummonItem(s, w -> new CinderReaperEntity(CINDER_REAPER, w), false),
				new Item.Settings());
		FORGE_TYRANT_CORE = ModItems.register("forge_tyrant_core",
				s -> new BossLordSummonItem(s, w -> new ForgeTyrantEntity(FORGE_TYRANT, w), true),
				new Item.Settings());

		// 2 drops + 1 EPIC trophy per boss (Item.Settings.rarity verified by infernoboss).
		ROYAL_SLAG = ModItems.register("royal_slag", Item::new, new Item.Settings());
		FISSURE_SHARD = ModItems.register("fissure_shard", Item::new, new Item.Settings());
		SLAG_CROWN = ModItems.register("slag_crown", Item::new, new Item.Settings().rarity(Rarity.EPIC));
		MATRIARCH_PLUME = ModItems.register("matriarch_plume", Item::new, new Item.Settings());
		LIVING_FLAME = ModItems.register("living_flame", Item::new, new Item.Settings());
		MATRIARCH_DIADEM = ModItems.register("matriarch_diadem", Item::new, new Item.Settings().rarity(Rarity.EPIC));
		COLOSSAL_ASH = ModItems.register("colossal_ash", Item::new, new Item.Settings());
		BLINDING_GRIT = ModItems.register("blinding_grit", Item::new, new Item.Settings());
		ASH_COLOSSUS_IDOL = ModItems.register("ash_colossus_idol", Item::new, new Item.Settings().rarity(Rarity.EPIC));
		LEVIATHAN_SCALE = ModItems.register("leviathan_scale", Item::new, new Item.Settings());
		MAGMA_BOMB_SHELL = ModItems.register("magma_bomb_shell", Item::new, new Item.Settings());
		LEVIATHAN_MAW = ModItems.register("leviathan_maw", Item::new, new Item.Settings().rarity(Rarity.EPIC));
		REAPER_CINDER = ModItems.register("reaper_cinder", Item::new, new Item.Settings());
		WITHERED_CLOTH = ModItems.register("withered_cloth", Item::new, new Item.Settings());
		CINDER_SCYTHE = ModItems.register("cinder_scythe", Item::new, new Item.Settings().rarity(Rarity.EPIC));
		FORGE_SCRAP = ModItems.register("forge_scrap", Item::new, new Item.Settings());
		TYRANT_HIDE = ModItems.register("tyrant_hide", Item::new, new Item.Settings());
		TYRANTS_ANVIL = ModItems.register("tyrants_anvil", Item::new, new Item.Settings().rarity(Rarity.EPIC));

		// Item.Settings.spawnEgg(type) stores the ENTITY_DATA component the vanilla
		// SpawnEggItem reads its entity type from in 1.21.9 (infernoboss precedent).
		THE_SLAG_KING_SPAWN_EGG = ModItems.register("the_slag_king_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(THE_SLAG_KING));
		EMBER_MATRIARCH_SPAWN_EGG = ModItems.register("ember_matriarch_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_MATRIARCH));
		ASH_COLOSSUS_SPAWN_EGG = ModItems.register("ash_colossus_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_COLOSSUS));
		MAGMA_LEVIATHAN_SPAWN_EGG = ModItems.register("magma_leviathan_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(MAGMA_LEVIATHAN));
		CINDER_REAPER_SPAWN_EGG = ModItems.register("cinder_reaper_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_REAPER));
		FORGE_TYRANT_SPAWN_EGG = ModItems.register("forge_tyrant_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(FORGE_TYRANT));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.FAUNA_KEY).register(entries -> {
			// Spawn eggs in roster order, then per-boss summon item / drops / trophy.
			entries.add(THE_SLAG_KING_SPAWN_EGG);
			entries.add(EMBER_MATRIARCH_SPAWN_EGG);
			entries.add(ASH_COLOSSUS_SPAWN_EGG);
			entries.add(MAGMA_LEVIATHAN_SPAWN_EGG);
			entries.add(CINDER_REAPER_SPAWN_EGG);
			entries.add(FORGE_TYRANT_SPAWN_EGG);
			entries.add(SLAG_KING_CORE);
			entries.add(ROYAL_SLAG);
			entries.add(FISSURE_SHARD);
			entries.add(SLAG_CROWN);
			entries.add(EMBER_MATRIARCH_SIGIL);
			entries.add(MATRIARCH_PLUME);
			entries.add(LIVING_FLAME);
			entries.add(MATRIARCH_DIADEM);
			entries.add(ASH_COLOSSUS_CORE);
			entries.add(COLOSSAL_ASH);
			entries.add(BLINDING_GRIT);
			entries.add(ASH_COLOSSUS_IDOL);
			entries.add(MAGMA_LEVIATHAN_SIGIL);
			entries.add(LEVIATHAN_SCALE);
			entries.add(MAGMA_BOMB_SHELL);
			entries.add(LEVIATHAN_MAW);
			entries.add(CINDER_REAPER_SIGIL);
			entries.add(REAPER_CINDER);
			entries.add(WITHERED_CLOTH);
			entries.add(CINDER_SCYTHE);
			entries.add(FORGE_TYRANT_CORE);
			entries.add(FORGE_SCRAP);
			entries.add(TYRANT_HIDE);
			entries.add(TYRANTS_ANVIL);
		});
	}

	private static void registerHandbookEntries() {
		HandbookEntries.add(new HandbookEntry("bosses", "the_slag_king",
				"copper_inferno:the_slag_king_spawn_egg", null, null, null, 0,
				"The Slag King - a molten iron-golem monarch. Summon: use a Slag King Core anywhere. Every few seconds he slams the ground, tearing open a molten fissure that burns, wounds and hurls back everyone nearby. Below half health he calls slag minions from the fissures and slams faster; below a quarter he enrages. Drops Royal Slag, Fissure Shards and the Slag Crown trophy.",
				"Der Schlackenkönig - ein geschmolzener Eisengolem-Monarch. Beschwörung: einen Schlackenkönig-Kern beliebig benutzen. Alle paar Sekunden rammt er den Boden und reißt eine geschmolzene Spalte auf, die jeden in der Nähe verbrennt, verwundet und zurückschleudert. Unter halber Gesundheit ruft er Schlacken-Diener aus den Spalten und rammt schneller; unter einem Viertel wird er rasend. Lässt Königsschlacke, Spaltsplitter und die Trophäe Schlackenkrone fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "ember_matriarch",
				"copper_inferno:ember_matriarch_spawn_egg", null, null, null, 0,
				"Ember Matriarch - the blaze mother of fire tornadoes. Summon: use an Ember Matriarch Sigil, only inside the Inferno dimension. She whirls rings of fireballs outward and drinks strength from everything that burns around her, healing herself. Below half health the tornado doubles and two blaze daughters answer her call; below a quarter she enrages. Drops Matriarch Plumes, Living Flames and the Matriarch Diadem trophy.",
				"Glutmatriarchin - die Lohenmutter der Feuertornados. Beschwörung: ein Glutmatriarchin-Siegel benutzen, nur in der Inferno-Dimension. Sie wirbelt Feuerballringe nach außen und zieht Kraft aus allem, was um sie herum brennt, und heilt sich damit. Unter halber Gesundheit verdoppelt sich der Tornado und zwei Lohen-Töchter folgen ihrem Ruf; unter einem Viertel wird sie rasend. Lässt Matriarchinnen-Federn, Lebende Flammen und die Trophäe Matriarchinnen-Diadem fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "ash_colossus",
				"copper_inferno:ash_colossus_spawn_egg", null, null, null, 0,
				"Ash Colossus - a towering golem wrapped in ash storms. Summon: use an Ash Colossus Core anywhere. It periodically whips up a blinding ash storm - Blindness and Slowness for everyone it can see. Below half health the storm also saps strength and the colossus hardens into a defensive stance; below a quarter it enrages. Drops Colossal Ash, Blinding Grit and the Ash Colossus Idol trophy.",
				"Aschenkoloss - ein turmhoher Golem in Aschestürmen. Beschwörung: einen Aschenkoloss-Kern beliebig benutzen. Er peitscht regelmäßig einen blendenden Aschesturm auf - Blindheit und Langsamkeit für jeden, den er sehen kann. Unter halber Gesundheit raubt der Sturm zusätzlich Kraft und der Koloss verhärtet sich in eine Verteidigungshaltung; unter einem Viertel wird er rasend. Lässt Kolossale Asche, Blendgrus und die Trophäe Aschenkoloss-Götzenbild fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "magma_leviathan",
				"copper_inferno:magma_leviathan_spawn_egg", null, null, null, 0,
				"Magma Leviathan - a colossal ghast that rains lava bombs. Summon: use a Magma Leviathan Sigil, only inside the Inferno dimension. Its mortar hurls spreads of explosive lava bombs at its prey. Below half health it enters its armor phase, hardening its hide with Resistance and firing denser volleys; below a quarter the bombs grow stronger still. Drops Leviathan Scales, Magma Bomb Shells and the Leviathan Maw trophy.",
				"Magma-Leviathan - ein kolossaler Ghast, der Lavabomben regnen lässt. Beschwörung: ein Magma-Leviathan-Siegel benutzen, nur in der Inferno-Dimension. Sein Mörser schleudert Streuungen explosiver Lavabomben auf seine Beute. Unter halber Gesundheit beginnt seine Panzerphase - die Haut härtet mit Resistenz und die Salven werden dichter; unter einem Viertel werden die Bomben noch stärker. Lässt Leviathan-Schuppen, Magmabomben-Hüllen und die Trophäe Leviathan-Schlund fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "cinder_reaper",
				"copper_inferno:cinder_reaper_spawn_egg", null, null, null, 0,
				"Cinder Reaper - a scythe-wielding skeleton lord that steps through shadow. Summon: use a Cinder Reaper Sigil anywhere. It blinks straight to its victim for withering scythe strikes and constantly bleeds a wither aura onto everyone close by. Below half health it gains ghostly speed and blinks faster; below a quarter its scythe arm enrages. Sunlight cannot burn it. Drops Reaper Cinders, Withered Cloth and the Cinder Scythe trophy.",
				"Zunderschnitter - ein sensenschwingender Skelettfürst, der durch Schatten schreitet. Beschwörung: ein Zunderschnitter-Siegel beliebig benutzen. Er blinzelt direkt zu seinem Opfer für zehrende Sensenhiebe und verströmt ständig eine Wither-Aura auf alle in seiner Nähe. Unter halber Gesundheit erhält er geisterhafte Geschwindigkeit und blinzelt schneller; unter einem Viertel gerät sein Sensenarm in Raserei. Sonnenlicht kann ihn nicht verbrennen. Lässt Schnitterzunder, Verdorrtes Tuch und die Trophäe Zundersense fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "forge_tyrant",
				"copper_inferno:forge_tyrant_spawn_egg", null, null, null, 0,
				"Forge Tyrant - a ravager cast from forge steel. Summon: use a Forge Tyrant Core, only inside the Inferno dimension. Its anvil quake hammers the ground, crushing and hurling everyone standing nearby. Below half health it bellows for two forge-hand adds; below a quarter it enrages with speed and fury. Drops Forge Scrap, Tyrant Hide and the Tyrant's Anvil trophy.",
				"Schmiedetyrann - ein aus Schmiedestahl gegossener Verwüster. Beschwörung: einen Schmiedetyrann-Kern benutzen, nur in der Inferno-Dimension. Sein Ambossbeben hämmert auf den Boden und zermalmt und schleudert jeden, der in der Nähe steht. Unter halber Gesundheit brüllt er nach zwei Schmiedeknecht-Verstärkungen; unter einem Viertel gerät er mit Tempo und Wut in Raserei. Lässt Schmiedeschrott, Tyrannenhaut und die Trophäe Tyrannenamboss fallen."));

		HandbookEntries.add(new HandbookEntry("bosses", "slag_king_core_recipe",
				"copper_inferno:slag_king_core", "bosslords/slag_king_core",
				new String[] {
						"minecraft:magma_block", "minecraft:iron_ingot", "minecraft:magma_block",
						"minecraft:iron_ingot", "copper_inferno:royal_slag", "minecraft:iron_ingot",
						"minecraft:magma_block", "minecraft:iron_ingot", "minecraft:magma_block"},
				"copper_inferno:slag_king_core", 1,
				"Slag King Core - ring Royal Slag with 4 Magma Blocks and 4 Iron Ingots. Use it anywhere to summon The Slag King.",
				"Schlackenkönig-Kern - Königsschlacke mit 4 Magmablöcken und 4 Eisenbarren umringen. Beliebig benutzen, um den Schlackenkönig zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "ember_matriarch_sigil_recipe",
				"copper_inferno:ember_matriarch_sigil", "bosslords/ember_matriarch_sigil",
				new String[] {
						"minecraft:blaze_powder", "minecraft:fire_charge", "minecraft:blaze_powder",
						"minecraft:fire_charge", "copper_inferno:matriarch_plume", "minecraft:fire_charge",
						"minecraft:blaze_powder", "minecraft:fire_charge", "minecraft:blaze_powder"},
				"copper_inferno:ember_matriarch_sigil", 1,
				"Ember Matriarch Sigil - ring a Matriarch Plume with 4 Blaze Powder and 4 Fire Charges. Use it inside the Inferno dimension to summon the Ember Matriarch.",
				"Glutmatriarchin-Siegel - eine Matriarchinnen-Feder mit 4 Lohenstaub und 4 Feuerkugeln umringen. In der Inferno-Dimension benutzen, um die Glutmatriarchin zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "ash_colossus_core_recipe",
				"copper_inferno:ash_colossus_core", "bosslords/ash_colossus_core",
				new String[] {
						"minecraft:tuff", "minecraft:bone_meal", "minecraft:tuff",
						"minecraft:bone_meal", "copper_inferno:colossal_ash", "minecraft:bone_meal",
						"minecraft:tuff", "minecraft:bone_meal", "minecraft:tuff"},
				"copper_inferno:ash_colossus_core", 1,
				"Ash Colossus Core - ring Colossal Ash with 4 Tuff and 4 Bone Meal. Use it anywhere to summon the Ash Colossus.",
				"Aschenkoloss-Kern - Kolossale Asche mit 4 Tuffstein und 4 Knochenmehl umringen. Beliebig benutzen, um den Aschenkoloss zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "magma_leviathan_sigil_recipe",
				"copper_inferno:magma_leviathan_sigil", "bosslords/magma_leviathan_sigil",
				new String[] {
						"minecraft:obsidian", "minecraft:magma_cream", "minecraft:obsidian",
						"minecraft:magma_cream", "copper_inferno:leviathan_scale", "minecraft:magma_cream",
						"minecraft:obsidian", "minecraft:magma_cream", "minecraft:obsidian"},
				"copper_inferno:magma_leviathan_sigil", 1,
				"Magma Leviathan Sigil - ring a Leviathan Scale with 4 Obsidian and 4 Magma Cream. Use it inside the Inferno dimension to summon the Magma Leviathan.",
				"Magma-Leviathan-Siegel - eine Leviathan-Schuppe mit 4 Obsidian und 4 Magmacreme umringen. In der Inferno-Dimension benutzen, um den Magma-Leviathan zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "cinder_reaper_sigil_recipe",
				"copper_inferno:cinder_reaper_sigil", "bosslords/cinder_reaper_sigil",
				new String[] {
						"minecraft:bone", "minecraft:soul_sand", "minecraft:bone",
						"minecraft:soul_sand", "copper_inferno:reaper_cinder", "minecraft:soul_sand",
						"minecraft:bone", "minecraft:soul_sand", "minecraft:bone"},
				"copper_inferno:cinder_reaper_sigil", 1,
				"Cinder Reaper Sigil - ring a Reaper Cinder with 4 Bones and 4 Soul Sand. Use it anywhere to summon the Cinder Reaper.",
				"Zunderschnitter-Siegel - Schnitterzunder mit 4 Knochen und 4 Seelensand umringen. Beliebig benutzen, um den Zunderschnitter zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "forge_tyrant_core_recipe",
				"copper_inferno:forge_tyrant_core", "bosslords/forge_tyrant_core",
				new String[] {
						"minecraft:iron_block", "minecraft:coal", "minecraft:iron_block",
						"minecraft:coal", "copper_inferno:forge_scrap", "minecraft:coal",
						"minecraft:iron_block", "minecraft:coal", "minecraft:iron_block"},
				"copper_inferno:forge_tyrant_core", 1,
				"Forge Tyrant Core - ring Forge Scrap with 4 Iron Blocks and 4 Coal. Use it inside the Inferno dimension to summon the Forge Tyrant.",
				"Schmiedetyrann-Kern - Schmiedeschrott mit 4 Eisenblöcken und 4 Kohle umringen. In der Inferno-Dimension benutzen, um den Schmiedetyrann zu beschwören."));
	}
}
