package net.sonic0810.copperinferno.feature.infernofx;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.minecraft.entity.attribute.EntityAttributeModifier;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.effect.StatusEffect;
import net.minecraft.item.Item;
import net.minecraft.particle.SimpleParticleType;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.entry.RegistryEntry;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEffects;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * Inferno ambience: 2 status effects (Heat Ward, Oxidized), 2 particles (ember_spark,
 * ash_fall) and 4 gadget items (heat_ward_charm, slag_bomb, cinder_compass, ash_talisman).
 * Assets are generated by {@code devtools/gen/infernofx_gen.py}; recipes live in
 * {@code data/copper_inferno/recipe/infernofx/}. Particle factories are registered in
 * {@code feature.infernofx.client.InfernoFxFeatureClient}.
 */
public final class InfernoFxFeature {
	private InfernoFxFeature() {
	}

	// Particle types (same FabricParticleTypes.simple() pattern as core.ModParticles;
	// registered here because this feature owns them).
	public static final SimpleParticleType EMBER_SPARK = Registry.register(
			Registries.PARTICLE_TYPE,
			CopperInferno.id("ember_spark"),
			FabricParticleTypes.simple());

	public static final SimpleParticleType ASH_FALL = Registry.register(
			Registries.PARTICLE_TYPE,
			CopperInferno.id("ash_fall"),
			FabricParticleTypes.simple());

	// Status effects
	public static RegistryEntry<StatusEffect> HEAT_WARD;
	public static RegistryEntry<StatusEffect> OXIDIZED;

	// Items
	public static Item HEAT_WARD_CHARM;
	public static Item SLAG_BOMB;
	public static Item CINDER_COMPASS;
	public static Item ASH_TALISMAN;

	public static void init() {
		HEAT_WARD = ModEffects.register("heat_ward", new HeatWardEffect());

		// -30% movement speed while oxidized. Signature verified via javap:
		// addAttributeModifier(RegistryEntry<EntityAttribute>, Identifier, double,
		// EntityAttributeModifier$Operation); ADD_MULTIPLIED_TOTAL is the 1.21.9 name.
		OXIDIZED = ModEffects.register("oxidized", new OxidizedEffect()
				.addAttributeModifier(EntityAttributes.MOVEMENT_SPEED,
						CopperInferno.id("effect.oxidized"), -0.30,
						EntityAttributeModifier.Operation.ADD_MULTIPLIED_TOTAL));

		HEAT_WARD_CHARM = ModItems.register("heat_ward_charm", HeatWardCharmItem::new,
				new Item.Settings().maxCount(1));
		SLAG_BOMB = ModItems.register("slag_bomb", SlagBombItem::new,
				new Item.Settings().maxCount(16));
		CINDER_COMPASS = ModItems.register("cinder_compass", CinderCompassItem::new,
				new Item.Settings().maxCount(1));
		ASH_TALISMAN = ModItems.register("ash_talisman", AshTalismanItem::new,
				new Item.Settings().maxCount(16));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			entries.add(HEAT_WARD_CHARM);
			entries.add(SLAG_BOMB);
			entries.add(CINDER_COMPASS);
			entries.add(ASH_TALISMAN);
		});

		registerHandbookEntries();
	}

	private static void registerHandbookEntries() {
		// ----- effect explainers (no recipe)
		HandbookEntries.add(new HandbookEntry("gear", "infernofx_heat_ward_effect",
				"copper_inferno:heat_ward_charm", null, null, null, 0,
				"Heat Ward is a status effect that keeps you from burning: while it is active any fire on you is snuffed out every tick, and warm ember sparks shimmer around you. Get it from the Heat Ward Charm (120s) or by crushing an Ash Talisman (30s).",
				"Hitzeschutz ist ein Statuseffekt, der dich vor dem Verbrennen bewahrt: Solange er aktiv ist, wird Feuer an dir in jedem Tick gel\u00f6scht, und warme Glutfunken flimmern um dich herum. Du erh\u00e4ltst ihn vom Hitzeschutz-Amulett (120s) oder durch das Zerbr\u00f6seln eines Asche-Talismans (30s)."));
		HandbookEntries.add(new HandbookEntry("gear", "infernofx_oxidized_effect",
				"minecraft:oxidized_copper", null, null, null, 0,
				"Oxidized is a harmful status effect: a verdigris crust stiffens your joints and slows your movement speed by 30% for as long as it lasts. Nothing in the Inferno applies it yet - consider it a hazard for future perils.",
				"Oxidiert ist ein sch\u00e4dlicher Statuseffekt: Eine Gr\u00fcnspankruste versteift deine Gelenke und verlangsamt deine Bewegungsgeschwindigkeit um 30%, solange er anh\u00e4lt. Noch verursacht ihn nichts im Inferno - betrachte ihn als Gefahr f\u00fcr kommende Abenteuer."));

		// ----- item recipes (one entry per recipe json in data/copper_inferno/recipe/infernofx/)
		HandbookEntries.add(new HandbookEntry("gear", "infernofx_heat_ward_charm",
				"copper_inferno:heat_ward_charm", "infernofx/heat_ward_charm",
				new String[]{
						"", "minecraft:copper_ingot", "",
						"minecraft:copper_ingot", "minecraft:magma_cream", "minecraft:copper_ingot",
						"", "minecraft:copper_ingot", ""},
				"copper_inferno:heat_ward_charm", 1,
				"A magma-cream core in a copper setting. Use it to gain 120 seconds of Heat Ward; the charm is kept but needs 60 seconds to recharge.",
				"Ein Magmacreme-Kern in Kupferfassung. Bei Benutzung erh\u00e4ltst du 120 Sekunden Hitzeschutz; das Amulett bleibt erhalten, braucht aber 60 Sekunden zum Aufladen."));
		HandbookEntries.add(new HandbookEntry("gear", "infernofx_slag_bomb",
				"copper_inferno:slag_bomb", "infernofx/slag_bomb",
				new String[]{
						"", "copper_inferno:slag_chunk", "",
						"", "minecraft:gunpowder", "",
						"", "", ""},
				"copper_inferno:slag_bomb", 2,
				"A molten slag lump packed with gunpowder. Throw it (use) to pop it where you are looking: a burst of ember sparks briefly ignites nearby creatures for 3 seconds. It places no fire blocks and damages no blocks.",
				"Ein gl\u00fchender Schlackeklumpen voller Schwarzpulver. Wirf sie (benutzen), um sie dort platzen zu lassen, wohin du schaust: Ein Glutfunkenregen entz\u00fcndet Kreaturen in der N\u00e4he f\u00fcr 3 Sekunden. Sie setzt keine Feuerbl\u00f6cke und besch\u00e4digt keine Bl\u00f6cke."));
		HandbookEntries.add(new HandbookEntry("gear", "infernofx_cinder_compass",
				"copper_inferno:cinder_compass", "infernofx/cinder_compass",
				new String[]{
						"", "minecraft:copper_ingot", "",
						"minecraft:copper_ingot", "copper_inferno:ember_dust", "minecraft:copper_ingot",
						"", "minecraft:copper_ingot", ""},
				"copper_inferno:cinder_compass", 1,
				"An ember-dust needle in a copper housing. Pure flavor: the needle only ever points toward the nearest warmth and does nothing when used - a souvenir of the Inferno.",
				"Eine Glutstaubnadel in einem Kupfergeh\u00e4use. Reine Zierde: Die Nadel zeigt stets nur zur n\u00e4chsten W\u00e4rmequelle und tut bei Benutzung nichts - ein Andenken an das Inferno."));
		HandbookEntries.add(new HandbookEntry("gear", "infernofx_ash_talisman",
				"copper_inferno:ash_talisman", "infernofx/ash_talisman",
				new String[]{
						"", "minecraft:string", "",
						"copper_inferno:ash_pile", "minecraft:gold_nugget", "copper_inferno:ash_pile",
						"", "copper_inferno:ash_pile", ""},
				"copper_inferno:ash_talisman", 1,
				"Pressed ash on a golden clasp. Crush it (use) for 30 seconds of Heat Ward - the talisman crumbles away. It grants the same Heat Ward effect as the charm, just shorter.",
				"Gepresste Asche an einer goldenen Spange. Zerbr\u00f6sle ihn (benutzen) f\u00fcr 30 Sekunden Hitzeschutz - der Talisman zerf\u00e4llt dabei. Er gew\u00e4hrt denselben Hitzeschutz-Effekt wie das Amulett, nur k\u00fcrzer."));
	}
}
