package net.sonic0810.copperinferno.feature.ashhorde;

import java.util.function.Predicate;
import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.SpawnLocationTypes;
import net.minecraft.entity.SpawnReason;
import net.minecraft.entity.SpawnRestriction;
import net.minecraft.entity.mob.HostileEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.random.Random;
import net.minecraft.world.Heightmap;
import net.minecraft.world.ServerWorldAccess;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModDimensions;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * The Ash Horde: 25 hostile mobs native to the Inferno biomes, each a thin subclass of a
 * vanilla base reusing the vanilla renderer (see {@code AshHordeFeatureClient}) — 5 each on
 * ZombieEntity, SkeletonEntity, SpiderEntity, CreeperEntity and HuskEntity. EntityType
 * dimensions/eye heights/attachments/tracking ranges are copied from the vanilla EntityType
 * registrations (verified via bytecode). Every mob ships a spawn egg, a unique drop item
 * (loot tables under {@code loot_table/entities/}), natural spawns in the harsh Inferno
 * biomes (cinder_wastes, ember_grove, slag_sea, soot_dunes, molten_delta), and a
 * drop-conversion recipe under {@code recipe/ashhorde/}.
 *
 * <p>Assets and this class are generated by {@code devtools/gen/ashhorde_gen.py}; handbook
 * pages are registered by {@link AshHordeHandbook}.
 */
public final class AshHordeFeature {
	private AshHordeFeature() {
	}

	public static EntityType<CinderShamblerEntity> CINDER_SHAMBLER;
	public static EntityType<AshGhoulEntity> ASH_GHOUL;
	public static EntityType<SlagRotterEntity> SLAG_ROTTER;
	public static EntityType<EmberThrallEntity> EMBER_THRALL;
	public static EntityType<SootWalkerEntity> SOOT_WALKER;
	public static EntityType<AshArcherEntity> ASH_ARCHER;
	public static EntityType<CinderBowmanEntity> CINDER_BOWMAN;
	public static EntityType<SlagMarksmanEntity> SLAG_MARKSMAN;
	public static EntityType<EmberRattlerEntity> EMBER_RATTLER;
	public static EntityType<SootSkirmisherEntity> SOOT_SKIRMISHER;
	public static EntityType<EmberLurkerEntity> EMBER_LURKER;
	public static EntityType<AshWeaverEntity> ASH_WEAVER;
	public static EntityType<SlagSpinnerEntity> SLAG_SPINNER;
	public static EntityType<SootStalkerEntity> SOOT_STALKER;
	public static EntityType<CinderBroodlingEntity> CINDER_BROODLING;
	public static EntityType<SlagCreeperEntity> SLAG_CREEPER;
	public static EntityType<AshBomberEntity> ASH_BOMBER;
	public static EntityType<EmberBursterEntity> EMBER_BURSTER;
	public static EntityType<SootDetonatorEntity> SOOT_DETONATOR;
	public static EntityType<CinderCrackerEntity> CINDER_CRACKER;
	public static EntityType<CharHuskEntity> CHAR_HUSK;
	public static EntityType<AshMummyEntity> ASH_MUMMY;
	public static EntityType<SlagHuskEntity> SLAG_HUSK;
	public static EntityType<EmberScorchlingEntity> EMBER_SCORCHLING;
	public static EntityType<SootWandererEntity> SOOT_WANDERER;

	public static Item CINDER_SHAMBLER_SPAWN_EGG;
	public static Item ASH_GHOUL_SPAWN_EGG;
	public static Item SLAG_ROTTER_SPAWN_EGG;
	public static Item EMBER_THRALL_SPAWN_EGG;
	public static Item SOOT_WALKER_SPAWN_EGG;
	public static Item ASH_ARCHER_SPAWN_EGG;
	public static Item CINDER_BOWMAN_SPAWN_EGG;
	public static Item SLAG_MARKSMAN_SPAWN_EGG;
	public static Item EMBER_RATTLER_SPAWN_EGG;
	public static Item SOOT_SKIRMISHER_SPAWN_EGG;
	public static Item EMBER_LURKER_SPAWN_EGG;
	public static Item ASH_WEAVER_SPAWN_EGG;
	public static Item SLAG_SPINNER_SPAWN_EGG;
	public static Item SOOT_STALKER_SPAWN_EGG;
	public static Item CINDER_BROODLING_SPAWN_EGG;
	public static Item SLAG_CREEPER_SPAWN_EGG;
	public static Item ASH_BOMBER_SPAWN_EGG;
	public static Item EMBER_BURSTER_SPAWN_EGG;
	public static Item SOOT_DETONATOR_SPAWN_EGG;
	public static Item CINDER_CRACKER_SPAWN_EGG;
	public static Item CHAR_HUSK_SPAWN_EGG;
	public static Item ASH_MUMMY_SPAWN_EGG;
	public static Item SLAG_HUSK_SPAWN_EGG;
	public static Item EMBER_SCORCHLING_SPAWN_EGG;
	public static Item SOOT_WANDERER_SPAWN_EGG;

	public static Item SHAMBLER_RAG;
	public static Item GHOUL_TATTER;
	public static Item ROTTER_SLUDGE;
	public static Item THRALL_SHACKLE;
	public static Item WALKER_GRIME;
	public static Item ARCHER_ARROWHEAD;
	public static Item BOWMAN_STRING;
	public static Item MARKSMAN_BONE;
	public static Item RATTLER_RIB;
	public static Item SKIRMISHER_QUIVER;
	public static Item LURKER_EYE;
	public static Item WEAVER_SILK;
	public static Item SPINNER_THREAD;
	public static Item STALKER_CLAW;
	public static Item BROODLING_FANG;
	public static Item CREEPER_SLAG;
	public static Item BOMBER_FUSE;
	public static Item BURSTER_POWDER;
	public static Item DETONATOR_CHARGE;
	public static Item CRACKER_SHARD;
	public static Item CHAR_HIDE;
	public static Item MUMMY_WRAP;
	public static Item HUSK_CRUST;
	public static Item SCORCHLING_CHAR;
	public static Item WANDERER_SHROUD;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		registerSpawning();
		AshHordeHandbook.register();
	}

	private static void registerEntityTypes() {
		// Builder chains copied 1:1 from the vanilla EntityType registrations (bytecode:
		// zombie/husk = dimensions(0.6f, 1.95f).eyeHeight(1.74f).passengerAttachments(2.0125f
		// resp. 2.075f).vehicleAttachment(-0.7f); skeleton = dimensions(0.6f, 1.99f)
		// .eyeHeight(1.74f).vehicleAttachment(-0.7f); spider = dimensions(1.4f, 0.9f)
		// .eyeHeight(0.65f).passengerAttachments(0.765f); creeper = dimensions(0.6f, 1.7f);
		// all .maxTrackingRange(8).notAllowedInPeaceful()).
		CINDER_SHAMBLER = ModEntities.register("cinder_shambler",
				EntityType.Builder.create(CinderShamblerEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		ASH_GHOUL = ModEntities.register("ash_ghoul",
				EntityType.Builder.create(AshGhoulEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SLAG_ROTTER = ModEntities.register("slag_rotter",
				EntityType.Builder.create(SlagRotterEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		EMBER_THRALL = ModEntities.register("ember_thrall",
				EntityType.Builder.create(EmberThrallEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SOOT_WALKER = ModEntities.register("soot_walker",
				EntityType.Builder.create(SootWalkerEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.0125f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		ASH_ARCHER = ModEntities.register("ash_archer",
				EntityType.Builder.create(AshArcherEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.99f)
						.eyeHeight(1.74f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		CINDER_BOWMAN = ModEntities.register("cinder_bowman",
				EntityType.Builder.create(CinderBowmanEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.99f)
						.eyeHeight(1.74f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SLAG_MARKSMAN = ModEntities.register("slag_marksman",
				EntityType.Builder.create(SlagMarksmanEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.99f)
						.eyeHeight(1.74f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		EMBER_RATTLER = ModEntities.register("ember_rattler",
				EntityType.Builder.create(EmberRattlerEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.99f)
						.eyeHeight(1.74f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SOOT_SKIRMISHER = ModEntities.register("soot_skirmisher",
				EntityType.Builder.create(SootSkirmisherEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.99f)
						.eyeHeight(1.74f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		EMBER_LURKER = ModEntities.register("ember_lurker",
				EntityType.Builder.create(EmberLurkerEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.4f, 0.9f)
						.eyeHeight(0.65f)
						.passengerAttachments(0.765f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		ASH_WEAVER = ModEntities.register("ash_weaver",
				EntityType.Builder.create(AshWeaverEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.4f, 0.9f)
						.eyeHeight(0.65f)
						.passengerAttachments(0.765f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SLAG_SPINNER = ModEntities.register("slag_spinner",
				EntityType.Builder.create(SlagSpinnerEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.4f, 0.9f)
						.eyeHeight(0.65f)
						.passengerAttachments(0.765f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SOOT_STALKER = ModEntities.register("soot_stalker",
				EntityType.Builder.create(SootStalkerEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.4f, 0.9f)
						.eyeHeight(0.65f)
						.passengerAttachments(0.765f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		CINDER_BROODLING = ModEntities.register("cinder_broodling",
				EntityType.Builder.create(CinderBroodlingEntity::new, SpawnGroup.MONSTER)
						.dimensions(1.4f, 0.9f)
						.eyeHeight(0.65f)
						.passengerAttachments(0.765f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SLAG_CREEPER = ModEntities.register("slag_creeper",
				EntityType.Builder.create(SlagCreeperEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		ASH_BOMBER = ModEntities.register("ash_bomber",
				EntityType.Builder.create(AshBomberEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		EMBER_BURSTER = ModEntities.register("ember_burster",
				EntityType.Builder.create(EmberBursterEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SOOT_DETONATOR = ModEntities.register("soot_detonator",
				EntityType.Builder.create(SootDetonatorEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		CINDER_CRACKER = ModEntities.register("cinder_cracker",
				EntityType.Builder.create(CinderCrackerEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		CHAR_HUSK = ModEntities.register("char_husk",
				EntityType.Builder.create(CharHuskEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.075f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		ASH_MUMMY = ModEntities.register("ash_mummy",
				EntityType.Builder.create(AshMummyEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.075f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SLAG_HUSK = ModEntities.register("slag_husk",
				EntityType.Builder.create(SlagHuskEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.075f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		EMBER_SCORCHLING = ModEntities.register("ember_scorchling",
				EntityType.Builder.create(EmberScorchlingEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.075f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());

		SOOT_WANDERER = ModEntities.register("soot_wanderer",
				EntityType.Builder.create(SootWandererEntity::new, SpawnGroup.MONSTER)
						.dimensions(0.6f, 1.95f)
						.eyeHeight(1.74f)
						.passengerAttachments(2.075f)
						.vehicleAttachment(-0.7f)
						.maxTrackingRange(8)
						.notAllowedInPeaceful());
	}

	private static void registerAttributes() {
		// Each createAttributes() delegates to the vanilla base create*Attributes() with
		// tuned MAX_HEALTH/ATTACK_DAMAGE/SCALE (javap-verified; add() overrides base values).
		FabricDefaultAttributeRegistry.register(CINDER_SHAMBLER, CinderShamblerEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(ASH_GHOUL, AshGhoulEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SLAG_ROTTER, SlagRotterEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_THRALL, EmberThrallEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SOOT_WALKER, SootWalkerEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(ASH_ARCHER, AshArcherEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(CINDER_BOWMAN, CinderBowmanEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SLAG_MARKSMAN, SlagMarksmanEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_RATTLER, EmberRattlerEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SOOT_SKIRMISHER, SootSkirmisherEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_LURKER, EmberLurkerEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(ASH_WEAVER, AshWeaverEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SLAG_SPINNER, SlagSpinnerEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SOOT_STALKER, SootStalkerEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(CINDER_BROODLING, CinderBroodlingEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SLAG_CREEPER, SlagCreeperEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(ASH_BOMBER, AshBomberEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_BURSTER, EmberBursterEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SOOT_DETONATOR, SootDetonatorEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(CINDER_CRACKER, CinderCrackerEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(CHAR_HUSK, CharHuskEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(ASH_MUMMY, AshMummyEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SLAG_HUSK, SlagHuskEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(EMBER_SCORCHLING, EmberScorchlingEntity.createAttributes());
		FabricDefaultAttributeRegistry.register(SOOT_WANDERER, SootWandererEntity.createAttributes());
	}

	private static void registerItems() {
		// Item.Settings.spawnEgg(type) stores the entity type the vanilla SpawnEggItem
		// reads in 1.21.9 (same proven pattern as InfernoMobsFeature/dr_pepper_golem).
		CINDER_SHAMBLER_SPAWN_EGG = ModItems.register("cinder_shambler_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_SHAMBLER));
		ASH_GHOUL_SPAWN_EGG = ModItems.register("ash_ghoul_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_GHOUL));
		SLAG_ROTTER_SPAWN_EGG = ModItems.register("slag_rotter_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_ROTTER));
		EMBER_THRALL_SPAWN_EGG = ModItems.register("ember_thrall_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_THRALL));
		SOOT_WALKER_SPAWN_EGG = ModItems.register("soot_walker_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_WALKER));
		ASH_ARCHER_SPAWN_EGG = ModItems.register("ash_archer_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_ARCHER));
		CINDER_BOWMAN_SPAWN_EGG = ModItems.register("cinder_bowman_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_BOWMAN));
		SLAG_MARKSMAN_SPAWN_EGG = ModItems.register("slag_marksman_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_MARKSMAN));
		EMBER_RATTLER_SPAWN_EGG = ModItems.register("ember_rattler_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_RATTLER));
		SOOT_SKIRMISHER_SPAWN_EGG = ModItems.register("soot_skirmisher_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_SKIRMISHER));
		EMBER_LURKER_SPAWN_EGG = ModItems.register("ember_lurker_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_LURKER));
		ASH_WEAVER_SPAWN_EGG = ModItems.register("ash_weaver_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_WEAVER));
		SLAG_SPINNER_SPAWN_EGG = ModItems.register("slag_spinner_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_SPINNER));
		SOOT_STALKER_SPAWN_EGG = ModItems.register("soot_stalker_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_STALKER));
		CINDER_BROODLING_SPAWN_EGG = ModItems.register("cinder_broodling_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_BROODLING));
		SLAG_CREEPER_SPAWN_EGG = ModItems.register("slag_creeper_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_CREEPER));
		ASH_BOMBER_SPAWN_EGG = ModItems.register("ash_bomber_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_BOMBER));
		EMBER_BURSTER_SPAWN_EGG = ModItems.register("ember_burster_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_BURSTER));
		SOOT_DETONATOR_SPAWN_EGG = ModItems.register("soot_detonator_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_DETONATOR));
		CINDER_CRACKER_SPAWN_EGG = ModItems.register("cinder_cracker_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CINDER_CRACKER));
		CHAR_HUSK_SPAWN_EGG = ModItems.register("char_husk_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(CHAR_HUSK));
		ASH_MUMMY_SPAWN_EGG = ModItems.register("ash_mummy_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(ASH_MUMMY));
		SLAG_HUSK_SPAWN_EGG = ModItems.register("slag_husk_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SLAG_HUSK));
		EMBER_SCORCHLING_SPAWN_EGG = ModItems.register("ember_scorchling_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(EMBER_SCORCHLING));
		SOOT_WANDERER_SPAWN_EGG = ModItems.register("soot_wanderer_spawn_egg", SpawnEggItem::new,
				new Item.Settings().spawnEgg(SOOT_WANDERER));

		SHAMBLER_RAG = ModItems.register("shambler_rag", Item::new, new Item.Settings());
		GHOUL_TATTER = ModItems.register("ghoul_tatter", Item::new, new Item.Settings());
		ROTTER_SLUDGE = ModItems.register("rotter_sludge", Item::new, new Item.Settings());
		THRALL_SHACKLE = ModItems.register("thrall_shackle", Item::new, new Item.Settings());
		WALKER_GRIME = ModItems.register("walker_grime", Item::new, new Item.Settings());
		ARCHER_ARROWHEAD = ModItems.register("archer_arrowhead", Item::new, new Item.Settings());
		BOWMAN_STRING = ModItems.register("bowman_string", Item::new, new Item.Settings());
		MARKSMAN_BONE = ModItems.register("marksman_bone", Item::new, new Item.Settings());
		RATTLER_RIB = ModItems.register("rattler_rib", Item::new, new Item.Settings());
		SKIRMISHER_QUIVER = ModItems.register("skirmisher_quiver", Item::new, new Item.Settings());
		LURKER_EYE = ModItems.register("lurker_eye", Item::new, new Item.Settings());
		WEAVER_SILK = ModItems.register("weaver_silk", Item::new, new Item.Settings());
		SPINNER_THREAD = ModItems.register("spinner_thread", Item::new, new Item.Settings());
		STALKER_CLAW = ModItems.register("stalker_claw", Item::new, new Item.Settings());
		BROODLING_FANG = ModItems.register("broodling_fang", Item::new, new Item.Settings());
		CREEPER_SLAG = ModItems.register("creeper_slag", Item::new, new Item.Settings());
		BOMBER_FUSE = ModItems.register("bomber_fuse", Item::new, new Item.Settings());
		BURSTER_POWDER = ModItems.register("burster_powder", Item::new, new Item.Settings());
		DETONATOR_CHARGE = ModItems.register("detonator_charge", Item::new, new Item.Settings());
		CRACKER_SHARD = ModItems.register("cracker_shard", Item::new, new Item.Settings());
		CHAR_HIDE = ModItems.register("char_hide", Item::new, new Item.Settings());
		MUMMY_WRAP = ModItems.register("mummy_wrap", Item::new, new Item.Settings());
		HUSK_CRUST = ModItems.register("husk_crust", Item::new, new Item.Settings());
		SCORCHLING_CHAR = ModItems.register("scorchling_char", Item::new, new Item.Settings());
		WANDERER_SHROUD = ModItems.register("wanderer_shroud", Item::new, new Item.Settings());

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MOBS_KEY).register(entries -> {
			// Spawn eggs together, then the mob drops.
			entries.add(CINDER_SHAMBLER_SPAWN_EGG);
			entries.add(ASH_GHOUL_SPAWN_EGG);
			entries.add(SLAG_ROTTER_SPAWN_EGG);
			entries.add(EMBER_THRALL_SPAWN_EGG);
			entries.add(SOOT_WALKER_SPAWN_EGG);
			entries.add(ASH_ARCHER_SPAWN_EGG);
			entries.add(CINDER_BOWMAN_SPAWN_EGG);
			entries.add(SLAG_MARKSMAN_SPAWN_EGG);
			entries.add(EMBER_RATTLER_SPAWN_EGG);
			entries.add(SOOT_SKIRMISHER_SPAWN_EGG);
			entries.add(EMBER_LURKER_SPAWN_EGG);
			entries.add(ASH_WEAVER_SPAWN_EGG);
			entries.add(SLAG_SPINNER_SPAWN_EGG);
			entries.add(SOOT_STALKER_SPAWN_EGG);
			entries.add(CINDER_BROODLING_SPAWN_EGG);
			entries.add(SLAG_CREEPER_SPAWN_EGG);
			entries.add(ASH_BOMBER_SPAWN_EGG);
			entries.add(EMBER_BURSTER_SPAWN_EGG);
			entries.add(SOOT_DETONATOR_SPAWN_EGG);
			entries.add(CINDER_CRACKER_SPAWN_EGG);
			entries.add(CHAR_HUSK_SPAWN_EGG);
			entries.add(ASH_MUMMY_SPAWN_EGG);
			entries.add(SLAG_HUSK_SPAWN_EGG);
			entries.add(EMBER_SCORCHLING_SPAWN_EGG);
			entries.add(SOOT_WANDERER_SPAWN_EGG);
			entries.add(SHAMBLER_RAG);
			entries.add(GHOUL_TATTER);
			entries.add(ROTTER_SLUDGE);
			entries.add(THRALL_SHACKLE);
			entries.add(WALKER_GRIME);
			entries.add(ARCHER_ARROWHEAD);
			entries.add(BOWMAN_STRING);
			entries.add(MARKSMAN_BONE);
			entries.add(RATTLER_RIB);
			entries.add(SKIRMISHER_QUIVER);
			entries.add(LURKER_EYE);
			entries.add(WEAVER_SILK);
			entries.add(SPINNER_THREAD);
			entries.add(STALKER_CLAW);
			entries.add(BROODLING_FANG);
			entries.add(CREEPER_SLAG);
			entries.add(BOMBER_FUSE);
			entries.add(BURSTER_POWDER);
			entries.add(DETONATOR_CHARGE);
			entries.add(CRACKER_SHARD);
			entries.add(CHAR_HIDE);
			entries.add(MUMMY_WRAP);
			entries.add(HUSK_CRUST);
			entries.add(SCORCHLING_CHAR);
			entries.add(WANDERER_SHROUD);
		});
	}

	private static void registerSpawning() {
		// SpawnRestriction.register is access-widened by Fabric's transitive access
		// wideners (same as InfernoMobsFeature). Locations/heightmaps/predicates mirror
		// the vanilla SpawnRestriction entries (bytecode): zombie/skeleton/spider/creeper
		// use ON_GROUND + MOTION_BLOCKING_NO_LEAVES + HostileEntity::canSpawnInDark; husk
		// uses HuskEntity.canSpawn, which is typed to EntityType<HuskEntity> and therefore
		// reimplemented 1:1 in canAshHuskSpawn below.
		SpawnRestriction.register(CINDER_SHAMBLER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(ASH_GHOUL, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SLAG_ROTTER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(EMBER_THRALL, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SOOT_WALKER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(ASH_ARCHER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(CINDER_BOWMAN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SLAG_MARKSMAN, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(EMBER_RATTLER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SOOT_SKIRMISHER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(EMBER_LURKER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(ASH_WEAVER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SLAG_SPINNER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SOOT_STALKER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(CINDER_BROODLING, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SLAG_CREEPER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(ASH_BOMBER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(EMBER_BURSTER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(SOOT_DETONATOR, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(CINDER_CRACKER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, HostileEntity::canSpawnInDark);
		SpawnRestriction.register(CHAR_HUSK, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, AshHordeFeature::canAshHuskSpawn);
		SpawnRestriction.register(ASH_MUMMY, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, AshHordeFeature::canAshHuskSpawn);
		SpawnRestriction.register(SLAG_HUSK, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, AshHordeFeature::canAshHuskSpawn);
		SpawnRestriction.register(EMBER_SCORCHLING, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, AshHordeFeature::canAshHuskSpawn);
		SpawnRestriction.register(SOOT_WANDERER, SpawnLocationTypes.ON_GROUND,
				Heightmap.Type.MOTION_BLOCKING_NO_LEAVES, AshHordeFeature::canAshHuskSpawn);

		// Natural spawns in the harsh Inferno biomes (SPAWN_BIOMES in the generator;
		// biome JSONs are owned by infernodim/infernodim2 and includeByKey simply
		// matches nothing until they are loaded). addSpawn signature verified via
		// javap: (Predicate<BiomeSelectionContext>, SpawnGroup, EntityType, weight,
		// minGroup, maxGroup).
		Predicate<BiomeSelectionContext> hordeBiomes = BiomeSelectors.includeByKey(
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("cinder_wastes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("ember_grove")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("slag_sea")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("soot_dunes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("molten_delta")));
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, CINDER_SHAMBLER, 12, 2, 4);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, ASH_GHOUL, 10, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SLAG_ROTTER, 8, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, EMBER_THRALL, 9, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SOOT_WALKER, 11, 2, 4);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, ASH_ARCHER, 12, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, CINDER_BOWMAN, 10, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SLAG_MARKSMAN, 8, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, EMBER_RATTLER, 9, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SOOT_SKIRMISHER, 11, 2, 4);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, EMBER_LURKER, 9, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, ASH_WEAVER, 8, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SLAG_SPINNER, 8, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SOOT_STALKER, 9, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, CINDER_BROODLING, 7, 2, 4);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SLAG_CREEPER, 8, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, ASH_BOMBER, 7, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, EMBER_BURSTER, 7, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SOOT_DETONATOR, 6, 1, 1);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, CINDER_CRACKER, 8, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, CHAR_HUSK, 10, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, ASH_MUMMY, 8, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SLAG_HUSK, 9, 1, 3);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, EMBER_SCORCHLING, 7, 1, 2);
		BiomeModifications.addSpawn(hordeBiomes, SpawnGroup.MONSTER, SOOT_WANDERER, 10, 2, 4);
	}

	/**
	 * Mirrors vanilla {@code HuskEntity.canSpawn} (verified against the 1.21.9 bytecode:
	 * {@code canSpawnInDark && (SpawnReason.isAnySpawner(reason) || world.isSkyVisible(pos))});
	 * the vanilla method is typed to {@code EntityType<HuskEntity>} so it cannot be reused
	 * directly. In the Inferno the sky-visibility gate would starve natural spawns entirely
	 * (the dimension has a ceiling, like the vanilla Nether), so — exactly like the ash
	 * bat's Inferno branch in {@code InfernoMobsFeature} — only the dark-spawn rules are
	 * kept there.
	 */
	private static <T extends HostileEntity> boolean canAshHuskSpawn(EntityType<T> type,
			ServerWorldAccess world, SpawnReason reason, BlockPos pos, Random random) {
		if (world.toServerWorld().getRegistryKey() == ModDimensions.INFERNO_WORLD) {
			return HostileEntity.canSpawnInDark(type, world, reason, pos, random);
		}
		return HostileEntity.canSpawnInDark(type, world, reason, pos, random)
				&& (SpawnReason.isAnySpawner(reason) || world.isSkyVisible(pos));
	}
}
