package net.sonic0810.copperinferno.feature.moltenmetal;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlockFamilies.BlockFamily;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Molten Metal block set: 224 building blocks across 14 molten-metal/alloy materials
 * (ember brass, slag bronze, molten brass, patina steel, cinder iron, forgeworn metal,
 * blistered bronze, scalding steel, smelter's alloy, furnace steel, quench iron,
 * emberchrome, molten cobalt, ashiron). Each material ships three full cube families
 * (base, polished, bricks; each base/slab/stairs/wall) plus tiles, cracked bricks,
 * chiseled bricks and a pillar.
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes,
 * EN+DE lang fragments) are generated by {@code devtools/gen/moltenmetal_gen.py}; the
 * tag fragment lives at {@code devtools/tagfrag/moltenmetal.json}; handbook pages are
 * registered by {@link MoltenMetalHandbook}.
 */
public final class MoltenMetalFeature {
	private MoltenMetalFeature() {
	}

	// Full cube families (base + slab + stairs + wall).
	public static BlockFamily EMBER_BRASS;
	public static BlockFamily POLISHED_EMBER_BRASS;
	public static BlockFamily EMBER_BRASS_BRICKS;
	public static BlockFamily SLAG_BRONZE;
	public static BlockFamily POLISHED_SLAG_BRONZE;
	public static BlockFamily SLAG_BRONZE_BRICKS;
	public static BlockFamily MOLTEN_BRASS;
	public static BlockFamily POLISHED_MOLTEN_BRASS;
	public static BlockFamily MOLTEN_BRASS_BRICKS;
	public static BlockFamily PATINA_STEEL;
	public static BlockFamily POLISHED_PATINA_STEEL;
	public static BlockFamily PATINA_STEEL_BRICKS;
	public static BlockFamily CINDER_IRON;
	public static BlockFamily POLISHED_CINDER_IRON;
	public static BlockFamily CINDER_IRON_BRICKS;
	public static BlockFamily FORGEWORN_METAL;
	public static BlockFamily POLISHED_FORGEWORN_METAL;
	public static BlockFamily FORGEWORN_METAL_BRICKS;
	public static BlockFamily BLISTERED_BRONZE;
	public static BlockFamily POLISHED_BLISTERED_BRONZE;
	public static BlockFamily BLISTERED_BRONZE_BRICKS;
	public static BlockFamily SCALDING_STEEL;
	public static BlockFamily POLISHED_SCALDING_STEEL;
	public static BlockFamily SCALDING_STEEL_BRICKS;
	public static BlockFamily SMELTERS_ALLOY;
	public static BlockFamily POLISHED_SMELTERS_ALLOY;
	public static BlockFamily SMELTERS_ALLOY_BRICKS;
	public static BlockFamily FURNACE_STEEL;
	public static BlockFamily POLISHED_FURNACE_STEEL;
	public static BlockFamily FURNACE_STEEL_BRICKS;
	public static BlockFamily QUENCH_IRON;
	public static BlockFamily POLISHED_QUENCH_IRON;
	public static BlockFamily QUENCH_IRON_BRICKS;
	public static BlockFamily EMBERCHROME;
	public static BlockFamily POLISHED_EMBERCHROME;
	public static BlockFamily EMBERCHROME_BRICKS;
	public static BlockFamily MOLTEN_COBALT;
	public static BlockFamily POLISHED_MOLTEN_COBALT;
	public static BlockFamily MOLTEN_COBALT_BRICKS;
	public static BlockFamily ASHIRON;
	public static BlockFamily POLISHED_ASHIRON;
	public static BlockFamily ASHIRON_BRICKS;

	// Single blocks.
	public static Block EMBER_BRASS_TILES;
	public static Block CRACKED_EMBER_BRASS_BRICKS;
	public static Block CHISELED_EMBER_BRASS_BRICKS;
	public static Block EMBER_BRASS_PILLAR;
	public static Block SLAG_BRONZE_TILES;
	public static Block CRACKED_SLAG_BRONZE_BRICKS;
	public static Block CHISELED_SLAG_BRONZE_BRICKS;
	public static Block SLAG_BRONZE_PILLAR;
	public static Block MOLTEN_BRASS_TILES;
	public static Block CRACKED_MOLTEN_BRASS_BRICKS;
	public static Block CHISELED_MOLTEN_BRASS_BRICKS;
	public static Block MOLTEN_BRASS_PILLAR;
	public static Block PATINA_STEEL_TILES;
	public static Block CRACKED_PATINA_STEEL_BRICKS;
	public static Block CHISELED_PATINA_STEEL_BRICKS;
	public static Block PATINA_STEEL_PILLAR;
	public static Block CINDER_IRON_TILES;
	public static Block CRACKED_CINDER_IRON_BRICKS;
	public static Block CHISELED_CINDER_IRON_BRICKS;
	public static Block CINDER_IRON_PILLAR;
	public static Block FORGEWORN_METAL_TILES;
	public static Block CRACKED_FORGEWORN_METAL_BRICKS;
	public static Block CHISELED_FORGEWORN_METAL_BRICKS;
	public static Block FORGEWORN_METAL_PILLAR;
	public static Block BLISTERED_BRONZE_TILES;
	public static Block CRACKED_BLISTERED_BRONZE_BRICKS;
	public static Block CHISELED_BLISTERED_BRONZE_BRICKS;
	public static Block BLISTERED_BRONZE_PILLAR;
	public static Block SCALDING_STEEL_TILES;
	public static Block CRACKED_SCALDING_STEEL_BRICKS;
	public static Block CHISELED_SCALDING_STEEL_BRICKS;
	public static Block SCALDING_STEEL_PILLAR;
	public static Block SMELTERS_ALLOY_TILES;
	public static Block CRACKED_SMELTERS_ALLOY_BRICKS;
	public static Block CHISELED_SMELTERS_ALLOY_BRICKS;
	public static Block SMELTERS_ALLOY_PILLAR;
	public static Block FURNACE_STEEL_TILES;
	public static Block CRACKED_FURNACE_STEEL_BRICKS;
	public static Block CHISELED_FURNACE_STEEL_BRICKS;
	public static Block FURNACE_STEEL_PILLAR;
	public static Block QUENCH_IRON_TILES;
	public static Block CRACKED_QUENCH_IRON_BRICKS;
	public static Block CHISELED_QUENCH_IRON_BRICKS;
	public static Block QUENCH_IRON_PILLAR;
	public static Block EMBERCHROME_TILES;
	public static Block CRACKED_EMBERCHROME_BRICKS;
	public static Block CHISELED_EMBERCHROME_BRICKS;
	public static Block EMBERCHROME_PILLAR;
	public static Block MOLTEN_COBALT_TILES;
	public static Block CRACKED_MOLTEN_COBALT_BRICKS;
	public static Block CHISELED_MOLTEN_COBALT_BRICKS;
	public static Block MOLTEN_COBALT_PILLAR;
	public static Block ASHIRON_TILES;
	public static Block CRACKED_ASHIRON_BRICKS;
	public static Block CHISELED_ASHIRON_BRICKS;
	public static Block ASHIRON_PILLAR;

	/**
	 * Fresh settings per block ({@link ModBlocks#register} writes a registry key into the
	 * instance, so settings must never be shared). Requires-tool metal profile adapted
	 * from the cinderstone stone profile (slightly harder, metal sounds).
	 */
	private static AbstractBlock.Settings metalSettings(MapColor color, BlockSoundGroup sounds) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(4.0F, 8.0F)
				.requiresTool()
				.sounds(sounds);
	}

	private static AbstractBlock.Settings emberBrassSettings() {
		return metalSettings(MapColor.GOLD, BlockSoundGroup.COPPER);
	}

	private static AbstractBlock.Settings slagBronzeSettings() {
		return metalSettings(MapColor.TERRACOTTA_BROWN, BlockSoundGroup.COPPER);
	}

	private static AbstractBlock.Settings moltenBrassSettings() {
		return metalSettings(MapColor.ORANGE, BlockSoundGroup.COPPER);
	}

	private static AbstractBlock.Settings patinaSteelSettings() {
		return metalSettings(MapColor.TEAL, BlockSoundGroup.METAL);
	}

	private static AbstractBlock.Settings cinderIronSettings() {
		return metalSettings(MapColor.IRON_GRAY, BlockSoundGroup.IRON);
	}

	private static AbstractBlock.Settings forgewornMetalSettings() {
		return metalSettings(MapColor.DEEPSLATE_GRAY, BlockSoundGroup.NETHERITE);
	}

	private static AbstractBlock.Settings blisteredBronzeSettings() {
		return metalSettings(MapColor.TERRACOTTA_ORANGE, BlockSoundGroup.COPPER);
	}

	private static AbstractBlock.Settings scaldingSteelSettings() {
		return metalSettings(MapColor.DULL_RED, BlockSoundGroup.METAL);
	}

	private static AbstractBlock.Settings smeltersAlloySettings() {
		return metalSettings(MapColor.RAW_IRON_PINK, BlockSoundGroup.METAL);
	}

	private static AbstractBlock.Settings furnaceSteelSettings() {
		return metalSettings(MapColor.GRAY, BlockSoundGroup.METAL);
	}

	private static AbstractBlock.Settings quenchIronSettings() {
		return metalSettings(MapColor.LIGHT_BLUE_GRAY, BlockSoundGroup.IRON);
	}

	private static AbstractBlock.Settings emberchromeSettings() {
		return metalSettings(MapColor.LIGHT_GRAY, BlockSoundGroup.METAL);
	}

	private static AbstractBlock.Settings moltenCobaltSettings() {
		return metalSettings(MapColor.LAPIS_BLUE, BlockSoundGroup.METAL);
	}

	private static AbstractBlock.Settings ashironSettings() {
		return metalSettings(MapColor.TERRACOTTA_GRAY, BlockSoundGroup.IRON);
	}

	public static void init() {
		EMBER_BRASS = ModBlockFamilies.registerCubeFamily(
				"ember_brass", "ember_brass", MoltenMetalFeature::emberBrassSettings, true);
		POLISHED_EMBER_BRASS = ModBlockFamilies.registerCubeFamily(
				"polished_ember_brass", "polished_ember_brass", MoltenMetalFeature::emberBrassSettings, true);
		EMBER_BRASS_BRICKS = ModBlockFamilies.registerCubeFamily(
				"ember_brass_bricks", "ember_brass_brick", MoltenMetalFeature::emberBrassSettings, true);
		SLAG_BRONZE = ModBlockFamilies.registerCubeFamily(
				"slag_bronze", "slag_bronze", MoltenMetalFeature::slagBronzeSettings, true);
		POLISHED_SLAG_BRONZE = ModBlockFamilies.registerCubeFamily(
				"polished_slag_bronze", "polished_slag_bronze", MoltenMetalFeature::slagBronzeSettings, true);
		SLAG_BRONZE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"slag_bronze_bricks", "slag_bronze_brick", MoltenMetalFeature::slagBronzeSettings, true);
		MOLTEN_BRASS = ModBlockFamilies.registerCubeFamily(
				"molten_brass", "molten_brass", MoltenMetalFeature::moltenBrassSettings, true);
		POLISHED_MOLTEN_BRASS = ModBlockFamilies.registerCubeFamily(
				"polished_molten_brass", "polished_molten_brass", MoltenMetalFeature::moltenBrassSettings, true);
		MOLTEN_BRASS_BRICKS = ModBlockFamilies.registerCubeFamily(
				"molten_brass_bricks", "molten_brass_brick", MoltenMetalFeature::moltenBrassSettings, true);
		PATINA_STEEL = ModBlockFamilies.registerCubeFamily(
				"patina_steel", "patina_steel", MoltenMetalFeature::patinaSteelSettings, true);
		POLISHED_PATINA_STEEL = ModBlockFamilies.registerCubeFamily(
				"polished_patina_steel", "polished_patina_steel", MoltenMetalFeature::patinaSteelSettings, true);
		PATINA_STEEL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"patina_steel_bricks", "patina_steel_brick", MoltenMetalFeature::patinaSteelSettings, true);
		CINDER_IRON = ModBlockFamilies.registerCubeFamily(
				"cinder_iron", "cinder_iron", MoltenMetalFeature::cinderIronSettings, true);
		POLISHED_CINDER_IRON = ModBlockFamilies.registerCubeFamily(
				"polished_cinder_iron", "polished_cinder_iron", MoltenMetalFeature::cinderIronSettings, true);
		CINDER_IRON_BRICKS = ModBlockFamilies.registerCubeFamily(
				"cinder_iron_bricks", "cinder_iron_brick", MoltenMetalFeature::cinderIronSettings, true);
		FORGEWORN_METAL = ModBlockFamilies.registerCubeFamily(
				"forgeworn_metal", "forgeworn_metal", MoltenMetalFeature::forgewornMetalSettings, true);
		POLISHED_FORGEWORN_METAL = ModBlockFamilies.registerCubeFamily(
				"polished_forgeworn_metal", "polished_forgeworn_metal", MoltenMetalFeature::forgewornMetalSettings, true);
		FORGEWORN_METAL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"forgeworn_metal_bricks", "forgeworn_metal_brick", MoltenMetalFeature::forgewornMetalSettings, true);
		BLISTERED_BRONZE = ModBlockFamilies.registerCubeFamily(
				"blistered_bronze", "blistered_bronze", MoltenMetalFeature::blisteredBronzeSettings, true);
		POLISHED_BLISTERED_BRONZE = ModBlockFamilies.registerCubeFamily(
				"polished_blistered_bronze", "polished_blistered_bronze", MoltenMetalFeature::blisteredBronzeSettings, true);
		BLISTERED_BRONZE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"blistered_bronze_bricks", "blistered_bronze_brick", MoltenMetalFeature::blisteredBronzeSettings, true);
		SCALDING_STEEL = ModBlockFamilies.registerCubeFamily(
				"scalding_steel", "scalding_steel", MoltenMetalFeature::scaldingSteelSettings, true);
		POLISHED_SCALDING_STEEL = ModBlockFamilies.registerCubeFamily(
				"polished_scalding_steel", "polished_scalding_steel", MoltenMetalFeature::scaldingSteelSettings, true);
		SCALDING_STEEL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"scalding_steel_bricks", "scalding_steel_brick", MoltenMetalFeature::scaldingSteelSettings, true);
		SMELTERS_ALLOY = ModBlockFamilies.registerCubeFamily(
				"smelters_alloy", "smelters_alloy", MoltenMetalFeature::smeltersAlloySettings, true);
		POLISHED_SMELTERS_ALLOY = ModBlockFamilies.registerCubeFamily(
				"polished_smelters_alloy", "polished_smelters_alloy", MoltenMetalFeature::smeltersAlloySettings, true);
		SMELTERS_ALLOY_BRICKS = ModBlockFamilies.registerCubeFamily(
				"smelters_alloy_bricks", "smelters_alloy_brick", MoltenMetalFeature::smeltersAlloySettings, true);
		FURNACE_STEEL = ModBlockFamilies.registerCubeFamily(
				"furnace_steel", "furnace_steel", MoltenMetalFeature::furnaceSteelSettings, true);
		POLISHED_FURNACE_STEEL = ModBlockFamilies.registerCubeFamily(
				"polished_furnace_steel", "polished_furnace_steel", MoltenMetalFeature::furnaceSteelSettings, true);
		FURNACE_STEEL_BRICKS = ModBlockFamilies.registerCubeFamily(
				"furnace_steel_bricks", "furnace_steel_brick", MoltenMetalFeature::furnaceSteelSettings, true);
		QUENCH_IRON = ModBlockFamilies.registerCubeFamily(
				"quench_iron", "quench_iron", MoltenMetalFeature::quenchIronSettings, true);
		POLISHED_QUENCH_IRON = ModBlockFamilies.registerCubeFamily(
				"polished_quench_iron", "polished_quench_iron", MoltenMetalFeature::quenchIronSettings, true);
		QUENCH_IRON_BRICKS = ModBlockFamilies.registerCubeFamily(
				"quench_iron_bricks", "quench_iron_brick", MoltenMetalFeature::quenchIronSettings, true);
		EMBERCHROME = ModBlockFamilies.registerCubeFamily(
				"emberchrome", "emberchrome", MoltenMetalFeature::emberchromeSettings, true);
		POLISHED_EMBERCHROME = ModBlockFamilies.registerCubeFamily(
				"polished_emberchrome", "polished_emberchrome", MoltenMetalFeature::emberchromeSettings, true);
		EMBERCHROME_BRICKS = ModBlockFamilies.registerCubeFamily(
				"emberchrome_bricks", "emberchrome_brick", MoltenMetalFeature::emberchromeSettings, true);
		MOLTEN_COBALT = ModBlockFamilies.registerCubeFamily(
				"molten_cobalt", "molten_cobalt", MoltenMetalFeature::moltenCobaltSettings, true);
		POLISHED_MOLTEN_COBALT = ModBlockFamilies.registerCubeFamily(
				"polished_molten_cobalt", "polished_molten_cobalt", MoltenMetalFeature::moltenCobaltSettings, true);
		MOLTEN_COBALT_BRICKS = ModBlockFamilies.registerCubeFamily(
				"molten_cobalt_bricks", "molten_cobalt_brick", MoltenMetalFeature::moltenCobaltSettings, true);
		ASHIRON = ModBlockFamilies.registerCubeFamily(
				"ashiron", "ashiron", MoltenMetalFeature::ashironSettings, true);
		POLISHED_ASHIRON = ModBlockFamilies.registerCubeFamily(
				"polished_ashiron", "polished_ashiron", MoltenMetalFeature::ashironSettings, true);
		ASHIRON_BRICKS = ModBlockFamilies.registerCubeFamily(
				"ashiron_bricks", "ashiron_brick", MoltenMetalFeature::ashironSettings, true);

		EMBER_BRASS_TILES = ModBlocks.register("ember_brass_tiles", Block::new, emberBrassSettings(), true);
		CRACKED_EMBER_BRASS_BRICKS = ModBlocks.register("cracked_ember_brass_bricks", Block::new, emberBrassSettings(), true);
		CHISELED_EMBER_BRASS_BRICKS = ModBlocks.register("chiseled_ember_brass_bricks", Block::new, emberBrassSettings(), true);
		EMBER_BRASS_PILLAR = ModBlocks.register("ember_brass_pillar", PillarBlock::new, emberBrassSettings(), true);
		SLAG_BRONZE_TILES = ModBlocks.register("slag_bronze_tiles", Block::new, slagBronzeSettings(), true);
		CRACKED_SLAG_BRONZE_BRICKS = ModBlocks.register("cracked_slag_bronze_bricks", Block::new, slagBronzeSettings(), true);
		CHISELED_SLAG_BRONZE_BRICKS = ModBlocks.register("chiseled_slag_bronze_bricks", Block::new, slagBronzeSettings(), true);
		SLAG_BRONZE_PILLAR = ModBlocks.register("slag_bronze_pillar", PillarBlock::new, slagBronzeSettings(), true);
		MOLTEN_BRASS_TILES = ModBlocks.register("molten_brass_tiles", Block::new, moltenBrassSettings(), true);
		CRACKED_MOLTEN_BRASS_BRICKS = ModBlocks.register("cracked_molten_brass_bricks", Block::new, moltenBrassSettings(), true);
		CHISELED_MOLTEN_BRASS_BRICKS = ModBlocks.register("chiseled_molten_brass_bricks", Block::new, moltenBrassSettings(), true);
		MOLTEN_BRASS_PILLAR = ModBlocks.register("molten_brass_pillar", PillarBlock::new, moltenBrassSettings(), true);
		PATINA_STEEL_TILES = ModBlocks.register("patina_steel_tiles", Block::new, patinaSteelSettings(), true);
		CRACKED_PATINA_STEEL_BRICKS = ModBlocks.register("cracked_patina_steel_bricks", Block::new, patinaSteelSettings(), true);
		CHISELED_PATINA_STEEL_BRICKS = ModBlocks.register("chiseled_patina_steel_bricks", Block::new, patinaSteelSettings(), true);
		PATINA_STEEL_PILLAR = ModBlocks.register("patina_steel_pillar", PillarBlock::new, patinaSteelSettings(), true);
		CINDER_IRON_TILES = ModBlocks.register("cinder_iron_tiles", Block::new, cinderIronSettings(), true);
		CRACKED_CINDER_IRON_BRICKS = ModBlocks.register("cracked_cinder_iron_bricks", Block::new, cinderIronSettings(), true);
		CHISELED_CINDER_IRON_BRICKS = ModBlocks.register("chiseled_cinder_iron_bricks", Block::new, cinderIronSettings(), true);
		CINDER_IRON_PILLAR = ModBlocks.register("cinder_iron_pillar", PillarBlock::new, cinderIronSettings(), true);
		FORGEWORN_METAL_TILES = ModBlocks.register("forgeworn_metal_tiles", Block::new, forgewornMetalSettings(), true);
		CRACKED_FORGEWORN_METAL_BRICKS = ModBlocks.register("cracked_forgeworn_metal_bricks", Block::new, forgewornMetalSettings(), true);
		CHISELED_FORGEWORN_METAL_BRICKS = ModBlocks.register("chiseled_forgeworn_metal_bricks", Block::new, forgewornMetalSettings(), true);
		FORGEWORN_METAL_PILLAR = ModBlocks.register("forgeworn_metal_pillar", PillarBlock::new, forgewornMetalSettings(), true);
		BLISTERED_BRONZE_TILES = ModBlocks.register("blistered_bronze_tiles", Block::new, blisteredBronzeSettings(), true);
		CRACKED_BLISTERED_BRONZE_BRICKS = ModBlocks.register("cracked_blistered_bronze_bricks", Block::new, blisteredBronzeSettings(), true);
		CHISELED_BLISTERED_BRONZE_BRICKS = ModBlocks.register("chiseled_blistered_bronze_bricks", Block::new, blisteredBronzeSettings(), true);
		BLISTERED_BRONZE_PILLAR = ModBlocks.register("blistered_bronze_pillar", PillarBlock::new, blisteredBronzeSettings(), true);
		SCALDING_STEEL_TILES = ModBlocks.register("scalding_steel_tiles", Block::new, scaldingSteelSettings(), true);
		CRACKED_SCALDING_STEEL_BRICKS = ModBlocks.register("cracked_scalding_steel_bricks", Block::new, scaldingSteelSettings(), true);
		CHISELED_SCALDING_STEEL_BRICKS = ModBlocks.register("chiseled_scalding_steel_bricks", Block::new, scaldingSteelSettings(), true);
		SCALDING_STEEL_PILLAR = ModBlocks.register("scalding_steel_pillar", PillarBlock::new, scaldingSteelSettings(), true);
		SMELTERS_ALLOY_TILES = ModBlocks.register("smelters_alloy_tiles", Block::new, smeltersAlloySettings(), true);
		CRACKED_SMELTERS_ALLOY_BRICKS = ModBlocks.register("cracked_smelters_alloy_bricks", Block::new, smeltersAlloySettings(), true);
		CHISELED_SMELTERS_ALLOY_BRICKS = ModBlocks.register("chiseled_smelters_alloy_bricks", Block::new, smeltersAlloySettings(), true);
		SMELTERS_ALLOY_PILLAR = ModBlocks.register("smelters_alloy_pillar", PillarBlock::new, smeltersAlloySettings(), true);
		FURNACE_STEEL_TILES = ModBlocks.register("furnace_steel_tiles", Block::new, furnaceSteelSettings(), true);
		CRACKED_FURNACE_STEEL_BRICKS = ModBlocks.register("cracked_furnace_steel_bricks", Block::new, furnaceSteelSettings(), true);
		CHISELED_FURNACE_STEEL_BRICKS = ModBlocks.register("chiseled_furnace_steel_bricks", Block::new, furnaceSteelSettings(), true);
		FURNACE_STEEL_PILLAR = ModBlocks.register("furnace_steel_pillar", PillarBlock::new, furnaceSteelSettings(), true);
		QUENCH_IRON_TILES = ModBlocks.register("quench_iron_tiles", Block::new, quenchIronSettings(), true);
		CRACKED_QUENCH_IRON_BRICKS = ModBlocks.register("cracked_quench_iron_bricks", Block::new, quenchIronSettings(), true);
		CHISELED_QUENCH_IRON_BRICKS = ModBlocks.register("chiseled_quench_iron_bricks", Block::new, quenchIronSettings(), true);
		QUENCH_IRON_PILLAR = ModBlocks.register("quench_iron_pillar", PillarBlock::new, quenchIronSettings(), true);
		EMBERCHROME_TILES = ModBlocks.register("emberchrome_tiles", Block::new, emberchromeSettings(), true);
		CRACKED_EMBERCHROME_BRICKS = ModBlocks.register("cracked_emberchrome_bricks", Block::new, emberchromeSettings(), true);
		CHISELED_EMBERCHROME_BRICKS = ModBlocks.register("chiseled_emberchrome_bricks", Block::new, emberchromeSettings(), true);
		EMBERCHROME_PILLAR = ModBlocks.register("emberchrome_pillar", PillarBlock::new, emberchromeSettings(), true);
		MOLTEN_COBALT_TILES = ModBlocks.register("molten_cobalt_tiles", Block::new, moltenCobaltSettings(), true);
		CRACKED_MOLTEN_COBALT_BRICKS = ModBlocks.register("cracked_molten_cobalt_bricks", Block::new, moltenCobaltSettings(), true);
		CHISELED_MOLTEN_COBALT_BRICKS = ModBlocks.register("chiseled_molten_cobalt_bricks", Block::new, moltenCobaltSettings(), true);
		MOLTEN_COBALT_PILLAR = ModBlocks.register("molten_cobalt_pillar", PillarBlock::new, moltenCobaltSettings(), true);
		ASHIRON_TILES = ModBlocks.register("ashiron_tiles", Block::new, ashironSettings(), true);
		CRACKED_ASHIRON_BRICKS = ModBlocks.register("cracked_ashiron_bricks", Block::new, ashironSettings(), true);
		CHISELED_ASHIRON_BRICKS = ModBlocks.register("chiseled_ashiron_bricks", Block::new, ashironSettings(), true);
		ASHIRON_PILLAR = ModBlocks.register("ashiron_pillar", PillarBlock::new, ashironSettings(), true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.SETS_KEY).register(entries -> {
			entries.add(EMBER_BRASS.block());
			entries.add(EMBER_BRASS.stairs());
			entries.add(EMBER_BRASS.slab());
			entries.add(EMBER_BRASS.wall());
			entries.add(POLISHED_EMBER_BRASS.block());
			entries.add(POLISHED_EMBER_BRASS.stairs());
			entries.add(POLISHED_EMBER_BRASS.slab());
			entries.add(POLISHED_EMBER_BRASS.wall());
			entries.add(EMBER_BRASS_BRICKS.block());
			entries.add(EMBER_BRASS_BRICKS.stairs());
			entries.add(EMBER_BRASS_BRICKS.slab());
			entries.add(EMBER_BRASS_BRICKS.wall());
			entries.add(EMBER_BRASS_TILES);
			entries.add(CRACKED_EMBER_BRASS_BRICKS);
			entries.add(CHISELED_EMBER_BRASS_BRICKS);
			entries.add(EMBER_BRASS_PILLAR);
			entries.add(SLAG_BRONZE.block());
			entries.add(SLAG_BRONZE.stairs());
			entries.add(SLAG_BRONZE.slab());
			entries.add(SLAG_BRONZE.wall());
			entries.add(POLISHED_SLAG_BRONZE.block());
			entries.add(POLISHED_SLAG_BRONZE.stairs());
			entries.add(POLISHED_SLAG_BRONZE.slab());
			entries.add(POLISHED_SLAG_BRONZE.wall());
			entries.add(SLAG_BRONZE_BRICKS.block());
			entries.add(SLAG_BRONZE_BRICKS.stairs());
			entries.add(SLAG_BRONZE_BRICKS.slab());
			entries.add(SLAG_BRONZE_BRICKS.wall());
			entries.add(SLAG_BRONZE_TILES);
			entries.add(CRACKED_SLAG_BRONZE_BRICKS);
			entries.add(CHISELED_SLAG_BRONZE_BRICKS);
			entries.add(SLAG_BRONZE_PILLAR);
			entries.add(MOLTEN_BRASS.block());
			entries.add(MOLTEN_BRASS.stairs());
			entries.add(MOLTEN_BRASS.slab());
			entries.add(MOLTEN_BRASS.wall());
			entries.add(POLISHED_MOLTEN_BRASS.block());
			entries.add(POLISHED_MOLTEN_BRASS.stairs());
			entries.add(POLISHED_MOLTEN_BRASS.slab());
			entries.add(POLISHED_MOLTEN_BRASS.wall());
			entries.add(MOLTEN_BRASS_BRICKS.block());
			entries.add(MOLTEN_BRASS_BRICKS.stairs());
			entries.add(MOLTEN_BRASS_BRICKS.slab());
			entries.add(MOLTEN_BRASS_BRICKS.wall());
			entries.add(MOLTEN_BRASS_TILES);
			entries.add(CRACKED_MOLTEN_BRASS_BRICKS);
			entries.add(CHISELED_MOLTEN_BRASS_BRICKS);
			entries.add(MOLTEN_BRASS_PILLAR);
			entries.add(PATINA_STEEL.block());
			entries.add(PATINA_STEEL.stairs());
			entries.add(PATINA_STEEL.slab());
			entries.add(PATINA_STEEL.wall());
			entries.add(POLISHED_PATINA_STEEL.block());
			entries.add(POLISHED_PATINA_STEEL.stairs());
			entries.add(POLISHED_PATINA_STEEL.slab());
			entries.add(POLISHED_PATINA_STEEL.wall());
			entries.add(PATINA_STEEL_BRICKS.block());
			entries.add(PATINA_STEEL_BRICKS.stairs());
			entries.add(PATINA_STEEL_BRICKS.slab());
			entries.add(PATINA_STEEL_BRICKS.wall());
			entries.add(PATINA_STEEL_TILES);
			entries.add(CRACKED_PATINA_STEEL_BRICKS);
			entries.add(CHISELED_PATINA_STEEL_BRICKS);
			entries.add(PATINA_STEEL_PILLAR);
			entries.add(CINDER_IRON.block());
			entries.add(CINDER_IRON.stairs());
			entries.add(CINDER_IRON.slab());
			entries.add(CINDER_IRON.wall());
			entries.add(POLISHED_CINDER_IRON.block());
			entries.add(POLISHED_CINDER_IRON.stairs());
			entries.add(POLISHED_CINDER_IRON.slab());
			entries.add(POLISHED_CINDER_IRON.wall());
			entries.add(CINDER_IRON_BRICKS.block());
			entries.add(CINDER_IRON_BRICKS.stairs());
			entries.add(CINDER_IRON_BRICKS.slab());
			entries.add(CINDER_IRON_BRICKS.wall());
			entries.add(CINDER_IRON_TILES);
			entries.add(CRACKED_CINDER_IRON_BRICKS);
			entries.add(CHISELED_CINDER_IRON_BRICKS);
			entries.add(CINDER_IRON_PILLAR);
			entries.add(FORGEWORN_METAL.block());
			entries.add(FORGEWORN_METAL.stairs());
			entries.add(FORGEWORN_METAL.slab());
			entries.add(FORGEWORN_METAL.wall());
			entries.add(POLISHED_FORGEWORN_METAL.block());
			entries.add(POLISHED_FORGEWORN_METAL.stairs());
			entries.add(POLISHED_FORGEWORN_METAL.slab());
			entries.add(POLISHED_FORGEWORN_METAL.wall());
			entries.add(FORGEWORN_METAL_BRICKS.block());
			entries.add(FORGEWORN_METAL_BRICKS.stairs());
			entries.add(FORGEWORN_METAL_BRICKS.slab());
			entries.add(FORGEWORN_METAL_BRICKS.wall());
			entries.add(FORGEWORN_METAL_TILES);
			entries.add(CRACKED_FORGEWORN_METAL_BRICKS);
			entries.add(CHISELED_FORGEWORN_METAL_BRICKS);
			entries.add(FORGEWORN_METAL_PILLAR);
			entries.add(BLISTERED_BRONZE.block());
			entries.add(BLISTERED_BRONZE.stairs());
			entries.add(BLISTERED_BRONZE.slab());
			entries.add(BLISTERED_BRONZE.wall());
			entries.add(POLISHED_BLISTERED_BRONZE.block());
			entries.add(POLISHED_BLISTERED_BRONZE.stairs());
			entries.add(POLISHED_BLISTERED_BRONZE.slab());
			entries.add(POLISHED_BLISTERED_BRONZE.wall());
			entries.add(BLISTERED_BRONZE_BRICKS.block());
			entries.add(BLISTERED_BRONZE_BRICKS.stairs());
			entries.add(BLISTERED_BRONZE_BRICKS.slab());
			entries.add(BLISTERED_BRONZE_BRICKS.wall());
			entries.add(BLISTERED_BRONZE_TILES);
			entries.add(CRACKED_BLISTERED_BRONZE_BRICKS);
			entries.add(CHISELED_BLISTERED_BRONZE_BRICKS);
			entries.add(BLISTERED_BRONZE_PILLAR);
			entries.add(SCALDING_STEEL.block());
			entries.add(SCALDING_STEEL.stairs());
			entries.add(SCALDING_STEEL.slab());
			entries.add(SCALDING_STEEL.wall());
			entries.add(POLISHED_SCALDING_STEEL.block());
			entries.add(POLISHED_SCALDING_STEEL.stairs());
			entries.add(POLISHED_SCALDING_STEEL.slab());
			entries.add(POLISHED_SCALDING_STEEL.wall());
			entries.add(SCALDING_STEEL_BRICKS.block());
			entries.add(SCALDING_STEEL_BRICKS.stairs());
			entries.add(SCALDING_STEEL_BRICKS.slab());
			entries.add(SCALDING_STEEL_BRICKS.wall());
			entries.add(SCALDING_STEEL_TILES);
			entries.add(CRACKED_SCALDING_STEEL_BRICKS);
			entries.add(CHISELED_SCALDING_STEEL_BRICKS);
			entries.add(SCALDING_STEEL_PILLAR);
			entries.add(SMELTERS_ALLOY.block());
			entries.add(SMELTERS_ALLOY.stairs());
			entries.add(SMELTERS_ALLOY.slab());
			entries.add(SMELTERS_ALLOY.wall());
			entries.add(POLISHED_SMELTERS_ALLOY.block());
			entries.add(POLISHED_SMELTERS_ALLOY.stairs());
			entries.add(POLISHED_SMELTERS_ALLOY.slab());
			entries.add(POLISHED_SMELTERS_ALLOY.wall());
			entries.add(SMELTERS_ALLOY_BRICKS.block());
			entries.add(SMELTERS_ALLOY_BRICKS.stairs());
			entries.add(SMELTERS_ALLOY_BRICKS.slab());
			entries.add(SMELTERS_ALLOY_BRICKS.wall());
			entries.add(SMELTERS_ALLOY_TILES);
			entries.add(CRACKED_SMELTERS_ALLOY_BRICKS);
			entries.add(CHISELED_SMELTERS_ALLOY_BRICKS);
			entries.add(SMELTERS_ALLOY_PILLAR);
			entries.add(FURNACE_STEEL.block());
			entries.add(FURNACE_STEEL.stairs());
			entries.add(FURNACE_STEEL.slab());
			entries.add(FURNACE_STEEL.wall());
			entries.add(POLISHED_FURNACE_STEEL.block());
			entries.add(POLISHED_FURNACE_STEEL.stairs());
			entries.add(POLISHED_FURNACE_STEEL.slab());
			entries.add(POLISHED_FURNACE_STEEL.wall());
			entries.add(FURNACE_STEEL_BRICKS.block());
			entries.add(FURNACE_STEEL_BRICKS.stairs());
			entries.add(FURNACE_STEEL_BRICKS.slab());
			entries.add(FURNACE_STEEL_BRICKS.wall());
			entries.add(FURNACE_STEEL_TILES);
			entries.add(CRACKED_FURNACE_STEEL_BRICKS);
			entries.add(CHISELED_FURNACE_STEEL_BRICKS);
			entries.add(FURNACE_STEEL_PILLAR);
			entries.add(QUENCH_IRON.block());
			entries.add(QUENCH_IRON.stairs());
			entries.add(QUENCH_IRON.slab());
			entries.add(QUENCH_IRON.wall());
			entries.add(POLISHED_QUENCH_IRON.block());
			entries.add(POLISHED_QUENCH_IRON.stairs());
			entries.add(POLISHED_QUENCH_IRON.slab());
			entries.add(POLISHED_QUENCH_IRON.wall());
			entries.add(QUENCH_IRON_BRICKS.block());
			entries.add(QUENCH_IRON_BRICKS.stairs());
			entries.add(QUENCH_IRON_BRICKS.slab());
			entries.add(QUENCH_IRON_BRICKS.wall());
			entries.add(QUENCH_IRON_TILES);
			entries.add(CRACKED_QUENCH_IRON_BRICKS);
			entries.add(CHISELED_QUENCH_IRON_BRICKS);
			entries.add(QUENCH_IRON_PILLAR);
			entries.add(EMBERCHROME.block());
			entries.add(EMBERCHROME.stairs());
			entries.add(EMBERCHROME.slab());
			entries.add(EMBERCHROME.wall());
			entries.add(POLISHED_EMBERCHROME.block());
			entries.add(POLISHED_EMBERCHROME.stairs());
			entries.add(POLISHED_EMBERCHROME.slab());
			entries.add(POLISHED_EMBERCHROME.wall());
			entries.add(EMBERCHROME_BRICKS.block());
			entries.add(EMBERCHROME_BRICKS.stairs());
			entries.add(EMBERCHROME_BRICKS.slab());
			entries.add(EMBERCHROME_BRICKS.wall());
			entries.add(EMBERCHROME_TILES);
			entries.add(CRACKED_EMBERCHROME_BRICKS);
			entries.add(CHISELED_EMBERCHROME_BRICKS);
			entries.add(EMBERCHROME_PILLAR);
			entries.add(MOLTEN_COBALT.block());
			entries.add(MOLTEN_COBALT.stairs());
			entries.add(MOLTEN_COBALT.slab());
			entries.add(MOLTEN_COBALT.wall());
			entries.add(POLISHED_MOLTEN_COBALT.block());
			entries.add(POLISHED_MOLTEN_COBALT.stairs());
			entries.add(POLISHED_MOLTEN_COBALT.slab());
			entries.add(POLISHED_MOLTEN_COBALT.wall());
			entries.add(MOLTEN_COBALT_BRICKS.block());
			entries.add(MOLTEN_COBALT_BRICKS.stairs());
			entries.add(MOLTEN_COBALT_BRICKS.slab());
			entries.add(MOLTEN_COBALT_BRICKS.wall());
			entries.add(MOLTEN_COBALT_TILES);
			entries.add(CRACKED_MOLTEN_COBALT_BRICKS);
			entries.add(CHISELED_MOLTEN_COBALT_BRICKS);
			entries.add(MOLTEN_COBALT_PILLAR);
			entries.add(ASHIRON.block());
			entries.add(ASHIRON.stairs());
			entries.add(ASHIRON.slab());
			entries.add(ASHIRON.wall());
			entries.add(POLISHED_ASHIRON.block());
			entries.add(POLISHED_ASHIRON.stairs());
			entries.add(POLISHED_ASHIRON.slab());
			entries.add(POLISHED_ASHIRON.wall());
			entries.add(ASHIRON_BRICKS.block());
			entries.add(ASHIRON_BRICKS.stairs());
			entries.add(ASHIRON_BRICKS.slab());
			entries.add(ASHIRON_BRICKS.wall());
			entries.add(ASHIRON_TILES);
			entries.add(CRACKED_ASHIRON_BRICKS);
			entries.add(CHISELED_ASHIRON_BRICKS);
			entries.add(ASHIRON_PILLAR);
		});

		MoltenMetalHandbook.register();
	}
}
