package net.sonic0810.copperinferno.feature.cinderstone;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.registry.FuelRegistryEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.LanternBlock;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlockFamilies.BlockFamily;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Cinder Stone block set: 56 building blocks for the Inferno-dimension aesthetic — eight full
 * cube families (base/slab/stairs/wall) plus 24 singles (cracked/chiseled/carved variants,
 * pillars, lanterns, lamps, glass, panes, ember coal and the glowing forge heart).
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes, EN+DE lang
 * fragments) are generated by {@code devtools/gen/cinderstone_gen.py}; the tag fragment lives at
 * {@code devtools/tagfrag/cinderstone.json}; handbook pages are registered by
 * {@link CinderStoneHandbook}.
 */
public final class CinderStoneFeature {
	private CinderStoneFeature() {
	}

	// Full cube families (base + slab + stairs + wall).
	public static BlockFamily CINDERSTONE_BRICKS;
	public static BlockFamily CINDERSTONE_TILES;
	public static BlockFamily POLISHED_CINDERSTONE;
	public static BlockFamily SLAGSTONE_BRICKS;
	public static BlockFamily ASHEN_BRICKS;
	public static BlockFamily SMOLDERING_BRICKS;
	public static BlockFamily FORGE_BRICKS;
	public static BlockFamily QUENCHED_SLAG;

	// Cinderstone singles.
	public static Block CRACKED_CINDERSTONE_BRICKS;
	public static Block CHISELED_CINDERSTONE_BRICKS;
	public static Block CINDERSTONE_PILLAR;
	public static Block CARVED_CINDERSTONE;

	// Slagstone singles.
	public static Block CRACKED_SLAGSTONE_BRICKS;
	public static Block CHISELED_SLAGSTONE_BRICKS;
	public static Block SLAGSTONE_PILLAR;
	public static Block QUENCHED_SLAG_PILLAR;

	// Forge singles.
	public static Block CRACKED_FORGE_BRICKS;
	public static Block CHISELED_FORGE_BRICKS;
	public static Block FORGE_PILLAR;
	public static Block FORGE_HEART;

	// Ashen singles.
	public static Block ASHEN_PILLAR;
	public static Block CHISELED_ASHEN_BRICKS;
	public static Block ASHEN_MOSAIC;

	// Light sources.
	public static Block EMBER_LANTERN;
	public static Block ASHEN_LANTERN;
	public static Block SMOLDER_LAMP;
	public static Block ASHEN_LAMP;

	// Glass (no requiresTool, like the glasslight feature's glass).
	public static Block CINDER_GLASS;
	public static Block CINDER_GLASS_PANE;
	public static Block SMOLDER_GLASS;
	public static Block SMOLDER_GLASS_PANE;

	// Misc.
	public static Block EMBER_COAL_BLOCK;

	/**
	 * Fresh settings per block ({@link ModBlocks#register} writes a registry key into the
	 * instance, so settings must never be shared). Standard cinderstone stone profile.
	 */
	private static AbstractBlock.Settings stoneSettings(MapColor color, BlockSoundGroup sounds) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.5F, 8.0F)
				.requiresTool()
				.sounds(sounds);
	}

	private static AbstractBlock.Settings cinderstoneSettings() {
		return stoneSettings(MapColor.BLACK, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings slagstoneSettings() {
		return stoneSettings(MapColor.TEAL, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings ashenSettings() {
		return stoneSettings(MapColor.LIGHT_GRAY, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings smolderingSettings() {
		return stoneSettings(MapColor.DARK_RED, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings forgeSettings() {
		return stoneSettings(MapColor.TERRACOTTA_RED, BlockSoundGroup.NETHER_BRICKS);
	}

	/** Copies the glasslight glass profile: fragile, glass sounds, nonOpaque, NO requiresTool. */
	private static AbstractBlock.Settings glassSettings() {
		return AbstractBlock.Settings.create()
				.strength(0.4F)
				.sounds(BlockSoundGroup.GLASS)
				.nonOpaque();
	}

	/** Vanilla-lantern-like profile with a per-block constant light level. */
	private static AbstractBlock.Settings lanternSettings(int light) {
		return AbstractBlock.Settings.create()
				.mapColor(MapColor.IRON_GRAY)
				.strength(3.5F)
				.requiresTool()
				.luminance(state -> light)
				.nonOpaque()
				.sounds(BlockSoundGroup.LANTERN);
	}

	public static void init() {
		CINDERSTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"cinderstone_bricks", "cinderstone_brick", CinderStoneFeature::cinderstoneSettings, true);
		CINDERSTONE_TILES = ModBlockFamilies.registerCubeFamily(
				"cinderstone_tiles", "cinderstone_tile", CinderStoneFeature::cinderstoneSettings, true);
		POLISHED_CINDERSTONE = ModBlockFamilies.registerCubeFamily(
				"polished_cinderstone", "polished_cinderstone", CinderStoneFeature::cinderstoneSettings, true);
		SLAGSTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"slagstone_bricks", "slagstone_brick", CinderStoneFeature::slagstoneSettings, true);
		ASHEN_BRICKS = ModBlockFamilies.registerCubeFamily(
				"ashen_bricks", "ashen_brick", CinderStoneFeature::ashenSettings, true);
		SMOLDERING_BRICKS = ModBlockFamilies.registerCubeFamily(
				"smoldering_bricks", "smoldering_brick", CinderStoneFeature::smolderingSettings, true);
		FORGE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"forge_bricks", "forge_brick", CinderStoneFeature::forgeSettings, true);
		QUENCHED_SLAG = ModBlockFamilies.registerCubeFamily(
				"quenched_slag", "quenched_slag", CinderStoneFeature::slagstoneSettings, true);

		CRACKED_CINDERSTONE_BRICKS = ModBlocks.register("cracked_cinderstone_bricks", Block::new, cinderstoneSettings(), true);
		CHISELED_CINDERSTONE_BRICKS = ModBlocks.register("chiseled_cinderstone_bricks", Block::new, cinderstoneSettings(), true);
		CINDERSTONE_PILLAR = ModBlocks.register("cinderstone_pillar", PillarBlock::new, cinderstoneSettings(), true);
		CARVED_CINDERSTONE = ModBlocks.register("carved_cinderstone", Block::new, cinderstoneSettings(), true);

		CRACKED_SLAGSTONE_BRICKS = ModBlocks.register("cracked_slagstone_bricks", Block::new, slagstoneSettings(), true);
		CHISELED_SLAGSTONE_BRICKS = ModBlocks.register("chiseled_slagstone_bricks", Block::new, slagstoneSettings(), true);
		SLAGSTONE_PILLAR = ModBlocks.register("slagstone_pillar", PillarBlock::new, slagstoneSettings(), true);
		QUENCHED_SLAG_PILLAR = ModBlocks.register("quenched_slag_pillar", PillarBlock::new, slagstoneSettings(), true);

		CRACKED_FORGE_BRICKS = ModBlocks.register("cracked_forge_bricks", Block::new, forgeSettings(), true);
		CHISELED_FORGE_BRICKS = ModBlocks.register("chiseled_forge_bricks", Block::new, forgeSettings(), true);
		FORGE_PILLAR = ModBlocks.register("forge_pillar", PillarBlock::new, forgeSettings(), true);
		FORGE_HEART = ModBlocks.register("forge_heart", Block::new, forgeSettings().luminance(state -> 13), true);

		ASHEN_PILLAR = ModBlocks.register("ashen_pillar", PillarBlock::new, ashenSettings(), true);
		CHISELED_ASHEN_BRICKS = ModBlocks.register("chiseled_ashen_bricks", Block::new, ashenSettings(), true);
		ASHEN_MOSAIC = ModBlocks.register("ashen_mosaic", Block::new, ashenSettings(), true);

		EMBER_LANTERN = ModBlocks.register("ember_lantern", LanternBlock::new, lanternSettings(14), true);
		ASHEN_LANTERN = ModBlocks.register("ashen_lantern", LanternBlock::new, lanternSettings(12), true);
		SMOLDER_LAMP = ModBlocks.register("smolder_lamp", Block::new, smolderingSettings().luminance(state -> 15), true);
		ASHEN_LAMP = ModBlocks.register("ashen_lamp", Block::new, ashenSettings().luminance(state -> 13), true);

		CINDER_GLASS = ModBlocks.register("cinder_glass", CinderGlassBlock::new, glassSettings(), true);
		CINDER_GLASS_PANE = ModBlocks.register("cinder_glass_pane", CinderGlassPaneBlock::new, glassSettings(), true);
		SMOLDER_GLASS = ModBlocks.register("smolder_glass", CinderGlassBlock::new, glassSettings().luminance(state -> 9), true);
		SMOLDER_GLASS_PANE = ModBlocks.register("smolder_glass_pane", CinderGlassPaneBlock::new,
				glassSettings().luminance(state -> 9), true);

		EMBER_COAL_BLOCK = ModBlocks.register("ember_coal_block", Block::new, cinderstoneSettings(), true);

		// Ember coal block burns like a vanilla coal block (16000 ticks = 80 smelts).
		FuelRegistryEvents.BUILD.register((builder, context) -> builder.add(EMBER_COAL_BLOCK, 16000));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			// Vanilla family shape order: block -> stairs -> slab -> wall.
			for (BlockFamily family : new BlockFamily[] {
					CINDERSTONE_BRICKS, CINDERSTONE_TILES, POLISHED_CINDERSTONE, SLAGSTONE_BRICKS,
					ASHEN_BRICKS, SMOLDERING_BRICKS, FORGE_BRICKS, QUENCHED_SLAG}) {
				entries.add(family.block());
				entries.add(family.stairs());
				entries.add(family.slab());
				entries.add(family.wall());
			}
			entries.add(CRACKED_CINDERSTONE_BRICKS);
			entries.add(CHISELED_CINDERSTONE_BRICKS);
			entries.add(CINDERSTONE_PILLAR);
			entries.add(CARVED_CINDERSTONE);
			entries.add(CRACKED_SLAGSTONE_BRICKS);
			entries.add(CHISELED_SLAGSTONE_BRICKS);
			entries.add(SLAGSTONE_PILLAR);
			entries.add(QUENCHED_SLAG_PILLAR);
			entries.add(CRACKED_FORGE_BRICKS);
			entries.add(CHISELED_FORGE_BRICKS);
			entries.add(FORGE_PILLAR);
			entries.add(FORGE_HEART);
			entries.add(ASHEN_PILLAR);
			entries.add(CHISELED_ASHEN_BRICKS);
			entries.add(ASHEN_MOSAIC);
			entries.add(EMBER_LANTERN);
			entries.add(ASHEN_LANTERN);
			entries.add(SMOLDER_LAMP);
			entries.add(ASHEN_LAMP);
			entries.add(CINDER_GLASS);
			entries.add(CINDER_GLASS_PANE);
			entries.add(SMOLDER_GLASS);
			entries.add(SMOLDER_GLASS_PANE);
			entries.add(EMBER_COAL_BLOCK);
		});

		CinderStoneHandbook.register();
	}
}
