package net.sonic0810.copperinferno.feature.infernogeology;

import java.util.function.Predicate;
import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.item.Item;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.world.gen.GenerationStep;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * Inferno geology: 25 data-driven worldgen features (10 ore veins, 2 scattered
 * scorched-debris veins, 4 replace-blobs, 3 sediment disks, 3 lava springs, 3
 * geyser basins) for the Inferno dimension, plus the 18 ore/deco blocks they
 * place and the brimstone item (dropped by brimstone_ore; consumed by the
 * recipes under {@code data/copper_inferno/recipe/infernogeology/}). The
 * configured/placed feature JSON under
 * {@code data/copper_inferno/worldgen/} is derived from the real vanilla 1.21.9
 * schemas; generation is wired here via Fabric BiomeModifications with two
 * literal predicates: veins + blobs into all seven copper_inferno biomes,
 * disks/springs/basins into the five lava-shore biomes (biome JSONs owned by
 * the infernodim/infernodim2 features).
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, EN+DE
 * lang fragments), the recipes and the worldgen JSON are generated by
 * {@code devtools/gen/infernogeology_gen.py}; the 8 real ores drop their
 * refined product under Fortune and the ore block under Silk Touch (loot derived
 * from the real vanilla tables); the tag fragment lives at
 * {@code devtools/tagfrag/infernogeology.json}; handbook pages are registered by
 * {@link InfernoGeologyHandbook}.
 */
public final class InfernoGeologyFeature {
	private InfernoGeologyFeature() {
	}

	// Single blocks.
	public static Block EMBER_IRON_ORE;
	public static Block ASH_GOLD_ORE;
	public static Block SLAG_COPPER_ORE;
	public static Block CINDER_QUARTZ_ORE;
	public static Block BRIMSTONE_ORE;
	public static Block CINDER_LAPIS_ORE;
	public static Block SMOLDER_REDSTONE_ORE;
	public static Block DEEP_INFERNIUM_ORE;
	public static Block SCORCHED_DEBRIS;
	public static Block ASHFALL_TUFF;
	public static Block EMBER_PUMICE;
	public static Block SCORIA;
	public static Block GEYSERITE;
	public static Block HARDENED_SLAG;
	public static Block SULFUR_BLOCK;
	public static Block SULFUR_SAND;
	public static Block EMBER_GRIT;
	public static Block CINDER_SILT;

	// Items.
	public static Item BRIMSTONE;

	/**
	 * Fresh settings per block ({@link ModBlocks#register} writes a registry key into the
	 * instance, so settings must never be shared). Requires-tool stone/ore profile, same
	 * shape as the infernodim terrain blocks.
	 */
	private static AbstractBlock.Settings stoneSettings(MapColor color, BlockSoundGroup sounds,
			float hardness, float resistance) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.requiresTool()
				.strength(hardness, resistance)
				.sounds(sounds);
	}

	/** Soft sediments: no requiresTool (shovel-mineable by hand, like scorched_sand). */
	private static AbstractBlock.Settings softSettings(MapColor color, BlockSoundGroup sounds,
			float strength) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(strength)
				.sounds(sounds);
	}

	public static void init() {
		EMBER_IRON_ORE = ModBlocks.register("ember_iron_ore", Block::new, stoneSettings(MapColor.IRON_GRAY, BlockSoundGroup.NETHER_ORE, 3.0F, 3.0F), true);
		ASH_GOLD_ORE = ModBlocks.register("ash_gold_ore", Block::new, stoneSettings(MapColor.GOLD, BlockSoundGroup.NETHER_ORE, 3.0F, 3.0F), true);
		SLAG_COPPER_ORE = ModBlocks.register("slag_copper_ore", Block::new, stoneSettings(MapColor.TERRACOTTA_ORANGE, BlockSoundGroup.NETHER_ORE, 3.0F, 3.0F), true);
		CINDER_QUARTZ_ORE = ModBlocks.register("cinder_quartz_ore", Block::new, stoneSettings(MapColor.OFF_WHITE, BlockSoundGroup.NETHER_ORE, 3.0F, 3.0F), true);
		BRIMSTONE_ORE = ModBlocks.register("brimstone_ore", Block::new, stoneSettings(MapColor.YELLOW, BlockSoundGroup.NETHER_ORE, 3.0F, 3.0F), true);
		CINDER_LAPIS_ORE = ModBlocks.register("cinder_lapis_ore", Block::new, stoneSettings(MapColor.LAPIS_BLUE, BlockSoundGroup.NETHER_ORE, 3.0F, 3.0F), true);
		SMOLDER_REDSTONE_ORE = ModBlocks.register("smolder_redstone_ore", Block::new, stoneSettings(MapColor.BRIGHT_RED, BlockSoundGroup.NETHER_ORE, 3.0F, 3.0F), true);
		DEEP_INFERNIUM_ORE = ModBlocks.register("deep_infernium_ore", Block::new, stoneSettings(MapColor.ORANGE, BlockSoundGroup.NETHER_ORE, 4.5F, 4.5F), true);
		SCORCHED_DEBRIS = ModBlocks.register("scorched_debris", Block::new, stoneSettings(MapColor.BLACK, BlockSoundGroup.ANCIENT_DEBRIS, 30.0F, 1200.0F), true);
		ASHFALL_TUFF = ModBlocks.register("ashfall_tuff", Block::new, stoneSettings(MapColor.TERRACOTTA_GRAY, BlockSoundGroup.TUFF, 1.5F, 6.0F), true);
		EMBER_PUMICE = ModBlocks.register("ember_pumice", Block::new, stoneSettings(MapColor.TERRACOTTA_ORANGE, BlockSoundGroup.BASALT, 1.25F, 4.2F), true);
		SCORIA = ModBlocks.register("scoria", Block::new, stoneSettings(MapColor.DARK_RED, BlockSoundGroup.BASALT, 1.25F, 4.2F), true);
		GEYSERITE = ModBlocks.register("geyserite", Block::new, stoneSettings(MapColor.PALE_YELLOW, BlockSoundGroup.CALCITE, 0.75F, 0.75F), true);
		HARDENED_SLAG = ModBlocks.register("hardened_slag", Block::new, stoneSettings(MapColor.GRAY, BlockSoundGroup.NETHER_BRICKS, 2.0F, 6.0F), true);
		SULFUR_BLOCK = ModBlocks.register("sulfur_block", Block::new, stoneSettings(MapColor.YELLOW, BlockSoundGroup.CALCITE, 1.5F, 2.0F), true);
		SULFUR_SAND = ModBlocks.register("sulfur_sand", Block::new, softSettings(MapColor.PALE_YELLOW, BlockSoundGroup.SAND, 0.5F), true);
		EMBER_GRIT = ModBlocks.register("ember_grit", Block::new, softSettings(MapColor.ORANGE, BlockSoundGroup.GRAVEL, 0.6F), true);
		CINDER_SILT = ModBlocks.register("cinder_silt", Block::new, softSettings(MapColor.GRAY, BlockSoundGroup.SOUL_SAND, 0.5F), true);

		BRIMSTONE = ModItems.register("brimstone", Item::new, new Item.Settings());

		// Worldgen wiring (biome JSONs owned by infernodim/infernodim2; includeByKey
		// matches nothing until they load). Veins and replace-blobs run in all seven
		// Inferno biomes; disks, springs and geyser basins only in the five lava-shore
		// biomes (crystal_hollows stays clean, verdigris_jungle keeps its jungle floor).
		// Every feature keeps its position in the single master order below and
		// lavaShoreBiomes is a strict subset of allInfernoBiomes, so every biome sees
		// its features in the same relative order and the placed-feature ordering
		// stays cycle-free (FeatureSorter single-master-order rule).
		Predicate<BiomeSelectionContext> allInfernoBiomes = BiomeSelectors.includeByKey(
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("cinder_wastes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("ember_grove")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("slag_sea")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("verdigris_jungle")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("molten_delta")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("soot_dunes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("crystal_hollows")));
		Predicate<BiomeSelectionContext> lavaShoreBiomes = BiomeSelectors.includeByKey(
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("cinder_wastes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("ember_grove")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("slag_sea")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("molten_delta")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("soot_dunes")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_ember_iron")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_ash_gold")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_slag_copper")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_cinder_quartz")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_brimstone")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_cinder_lapis")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_smolder_redstone")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_deep_infernium")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_ashfall_tuff")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_ember_pumice")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_scorched_debris_large")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_ORES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ore_scorched_debris_small")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("scoria_blobs")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("geyserite_blobs")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("hardened_slag_blobs")));
		BiomeModifications.addFeature(allInfernoBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("sulfur_blobs")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("disk_sulfur_sand")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("disk_ember_grit")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("disk_cinder_silt")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.FLUID_SPRINGS,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("spring_sulfur")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.FLUID_SPRINGS,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("spring_geyserite")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.FLUID_SPRINGS,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("spring_scoria")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.SURFACE_STRUCTURES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("geyser_basin")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.SURFACE_STRUCTURES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("sulfur_basin")));
		BiomeModifications.addFeature(lavaShoreBiomes, GenerationStep.Feature.SURFACE_STRUCTURES,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("slag_basin")));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			entries.add(EMBER_IRON_ORE);
			entries.add(ASH_GOLD_ORE);
			entries.add(SLAG_COPPER_ORE);
			entries.add(CINDER_QUARTZ_ORE);
			entries.add(BRIMSTONE_ORE);
			entries.add(CINDER_LAPIS_ORE);
			entries.add(SMOLDER_REDSTONE_ORE);
			entries.add(DEEP_INFERNIUM_ORE);
			entries.add(SCORCHED_DEBRIS);
			entries.add(ASHFALL_TUFF);
			entries.add(EMBER_PUMICE);
			entries.add(SCORIA);
			entries.add(GEYSERITE);
			entries.add(HARDENED_SLAG);
			entries.add(SULFUR_BLOCK);
			entries.add(SULFUR_SAND);
			entries.add(EMBER_GRIT);
			entries.add(CINDER_SILT);
		});

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			entries.add(BRIMSTONE);
		});

		InfernoGeologyHandbook.register();
	}
}
