package net.sonic0810.copperinferno.feature.titanforge;

import java.util.EnumMap;
import java.util.Map;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.AxeItem;
import net.minecraft.item.HoeItem;
import net.minecraft.item.Item;
import net.minecraft.item.ShovelItem;
import net.minecraft.item.ToolMaterial;
import net.minecraft.item.equipment.ArmorMaterial;
import net.minecraft.item.equipment.EquipmentAsset;
import net.minecraft.item.equipment.EquipmentAssetKeys;
import net.minecraft.item.equipment.EquipmentType;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.sound.SoundEvents;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * TitanForge gear: 96 items across six new tool &amp; armor tiers in progression order
 * (ember_steel, pyrite, slagsteel, cinderforge, molten_titan, infernal_alloy). Each tier
 * ships sword/pickaxe/axe/shovel/hoe + helmet/chestplate/leggings/boots, one alloy ingot
 * and six charm trinkets (charm, totem, ring, amulet, talisman, medallion).
 *
 * <p>Tool and armor materials mirror {@code InferniumFeature}: ToolMaterial /
 * ArmorMaterial record constructors verified via javap; each tier repairs from its own
 * {@code copper_inferno:&lt;tier&gt;_repair} item tag and renders worn armor through its
 * own equipment asset {@code assets/copper_inferno/equipment/&lt;tier&gt;.json}. Molten
 * Titan and Infernal Alloy gear is fireproof.
 *
 * <p>Recipes live in {@code data/copper_inferno/recipe/titanforge/}: vanilla tool/armor
 * shapes from tier ingots + sticks, shapeless alloy chains (each tier's ingot consumes
 * the previous tier's), charm shapes, and smithing_transform upgrade chains between
 * consecutive tiers using the shipped infernium upgrade smithing template (data-side
 * dependency only). Assets are generated by {@code devtools/gen/titanforge_gen.py};
 * handbook pages are registered by {@link TitanForgeHandbook}.
 */
public final class TitanForgeFeature {
	private TitanForgeFeature() {
	}

	// Items.
	public static Item EMBER_STEEL_INGOT;
	public static Item EMBER_STEEL_SWORD;
	public static Item EMBER_STEEL_PICKAXE;
	public static Item EMBER_STEEL_AXE;
	public static Item EMBER_STEEL_SHOVEL;
	public static Item EMBER_STEEL_HOE;
	public static Item EMBER_STEEL_HELMET;
	public static Item EMBER_STEEL_CHESTPLATE;
	public static Item EMBER_STEEL_LEGGINGS;
	public static Item EMBER_STEEL_BOOTS;
	public static Item EMBER_STEEL_CHARM;
	public static Item EMBER_STEEL_TOTEM;
	public static Item EMBER_STEEL_RING;
	public static Item EMBER_STEEL_AMULET;
	public static Item EMBER_STEEL_TALISMAN;
	public static Item EMBER_STEEL_MEDALLION;
	public static Item PYRITE_INGOT;
	public static Item PYRITE_SWORD;
	public static Item PYRITE_PICKAXE;
	public static Item PYRITE_AXE;
	public static Item PYRITE_SHOVEL;
	public static Item PYRITE_HOE;
	public static Item PYRITE_HELMET;
	public static Item PYRITE_CHESTPLATE;
	public static Item PYRITE_LEGGINGS;
	public static Item PYRITE_BOOTS;
	public static Item PYRITE_CHARM;
	public static Item PYRITE_TOTEM;
	public static Item PYRITE_RING;
	public static Item PYRITE_AMULET;
	public static Item PYRITE_TALISMAN;
	public static Item PYRITE_MEDALLION;
	public static Item SLAGSTEEL_INGOT;
	public static Item SLAGSTEEL_SWORD;
	public static Item SLAGSTEEL_PICKAXE;
	public static Item SLAGSTEEL_AXE;
	public static Item SLAGSTEEL_SHOVEL;
	public static Item SLAGSTEEL_HOE;
	public static Item SLAGSTEEL_HELMET;
	public static Item SLAGSTEEL_CHESTPLATE;
	public static Item SLAGSTEEL_LEGGINGS;
	public static Item SLAGSTEEL_BOOTS;
	public static Item SLAGSTEEL_CHARM;
	public static Item SLAGSTEEL_TOTEM;
	public static Item SLAGSTEEL_RING;
	public static Item SLAGSTEEL_AMULET;
	public static Item SLAGSTEEL_TALISMAN;
	public static Item SLAGSTEEL_MEDALLION;
	public static Item CINDERFORGE_INGOT;
	public static Item CINDERFORGE_SWORD;
	public static Item CINDERFORGE_PICKAXE;
	public static Item CINDERFORGE_AXE;
	public static Item CINDERFORGE_SHOVEL;
	public static Item CINDERFORGE_HOE;
	public static Item CINDERFORGE_HELMET;
	public static Item CINDERFORGE_CHESTPLATE;
	public static Item CINDERFORGE_LEGGINGS;
	public static Item CINDERFORGE_BOOTS;
	public static Item CINDERFORGE_CHARM;
	public static Item CINDERFORGE_TOTEM;
	public static Item CINDERFORGE_RING;
	public static Item CINDERFORGE_AMULET;
	public static Item CINDERFORGE_TALISMAN;
	public static Item CINDERFORGE_MEDALLION;
	public static Item MOLTEN_TITAN_INGOT;
	public static Item MOLTEN_TITAN_SWORD;
	public static Item MOLTEN_TITAN_PICKAXE;
	public static Item MOLTEN_TITAN_AXE;
	public static Item MOLTEN_TITAN_SHOVEL;
	public static Item MOLTEN_TITAN_HOE;
	public static Item MOLTEN_TITAN_HELMET;
	public static Item MOLTEN_TITAN_CHESTPLATE;
	public static Item MOLTEN_TITAN_LEGGINGS;
	public static Item MOLTEN_TITAN_BOOTS;
	public static Item MOLTEN_TITAN_CHARM;
	public static Item MOLTEN_TITAN_TOTEM;
	public static Item MOLTEN_TITAN_RING;
	public static Item MOLTEN_TITAN_AMULET;
	public static Item MOLTEN_TITAN_TALISMAN;
	public static Item MOLTEN_TITAN_MEDALLION;
	public static Item INFERNAL_ALLOY_INGOT;
	public static Item INFERNAL_ALLOY_SWORD;
	public static Item INFERNAL_ALLOY_PICKAXE;
	public static Item INFERNAL_ALLOY_AXE;
	public static Item INFERNAL_ALLOY_SHOVEL;
	public static Item INFERNAL_ALLOY_HOE;
	public static Item INFERNAL_ALLOY_HELMET;
	public static Item INFERNAL_ALLOY_CHESTPLATE;
	public static Item INFERNAL_ALLOY_LEGGINGS;
	public static Item INFERNAL_ALLOY_BOOTS;
	public static Item INFERNAL_ALLOY_CHARM;
	public static Item INFERNAL_ALLOY_TOTEM;
	public static Item INFERNAL_ALLOY_RING;
	public static Item INFERNAL_ALLOY_AMULET;
	public static Item INFERNAL_ALLOY_TALISMAN;
	public static Item INFERNAL_ALLOY_MEDALLION;

	/** Repair tag, backed by data/copper_inferno/tags/item/ember_steel_repair.json. */
	public static final TagKey<Item> REPAIRS_EMBER_STEEL =
			TagKey.of(RegistryKeys.ITEM, CopperInferno.id("ember_steel_repair"));

	/** Custom worn-armor asset: assets/copper_inferno/equipment/ember_steel.json. */
	public static final RegistryKey<EquipmentAsset> EMBER_STEEL_EQUIPMENT_ASSET_ID =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("ember_steel"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed,
	 * attackDamageBonus, enchantmentValue, repairItems) — verified via javap,
	 * mirroring InferniumFeature.
	 */
	public static final ToolMaterial EMBER_STEEL_TOOL_MATERIAL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_IRON_TOOL, 320, 6.5F, 2.0F, 16, REPAIRS_EMBER_STEEL);

	/**
	 * ArmorMaterial is a record: (durability, defense map, enchantmentValue, equipSound,
	 * toughness, knockbackResistance, repairIngredient, assetId) — verified via javap,
	 * mirroring InferniumFeature (defenseMap order: boots, leggings, chestplate,
	 * helmet, body).
	 */
	public static final ArmorMaterial EMBER_STEEL_ARMOR_MATERIAL = new ArmorMaterial(
			16, defenseMap(2, 5, 6, 2, 5), 16,
			SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.5F, 0.0F, REPAIRS_EMBER_STEEL, EMBER_STEEL_EQUIPMENT_ASSET_ID);

	/** Repair tag, backed by data/copper_inferno/tags/item/pyrite_repair.json. */
	public static final TagKey<Item> REPAIRS_PYRITE =
			TagKey.of(RegistryKeys.ITEM, CopperInferno.id("pyrite_repair"));

	/** Custom worn-armor asset: assets/copper_inferno/equipment/pyrite.json. */
	public static final RegistryKey<EquipmentAsset> PYRITE_EQUIPMENT_ASSET_ID =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("pyrite"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed,
	 * attackDamageBonus, enchantmentValue, repairItems) — verified via javap,
	 * mirroring InferniumFeature.
	 */
	public static final ToolMaterial PYRITE_TOOL_MATERIAL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_IRON_TOOL, 500, 7.0F, 2.0F, 22, REPAIRS_PYRITE);

	/**
	 * ArmorMaterial is a record: (durability, defense map, enchantmentValue, equipSound,
	 * toughness, knockbackResistance, repairIngredient, assetId) — verified via javap,
	 * mirroring InferniumFeature (defenseMap order: boots, leggings, chestplate,
	 * helmet, body).
	 */
	public static final ArmorMaterial PYRITE_ARMOR_MATERIAL = new ArmorMaterial(
			12, defenseMap(2, 4, 6, 2, 4), 22,
			SoundEvents.ITEM_ARMOR_EQUIP_GOLD, 0.0F, 0.0F, REPAIRS_PYRITE, PYRITE_EQUIPMENT_ASSET_ID);

	/** Repair tag, backed by data/copper_inferno/tags/item/slagsteel_repair.json. */
	public static final TagKey<Item> REPAIRS_SLAGSTEEL =
			TagKey.of(RegistryKeys.ITEM, CopperInferno.id("slagsteel_repair"));

	/** Custom worn-armor asset: assets/copper_inferno/equipment/slagsteel.json. */
	public static final RegistryKey<EquipmentAsset> SLAGSTEEL_EQUIPMENT_ASSET_ID =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("slagsteel"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed,
	 * attackDamageBonus, enchantmentValue, repairItems) — verified via javap,
	 * mirroring InferniumFeature.
	 */
	public static final ToolMaterial SLAGSTEEL_TOOL_MATERIAL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_IRON_TOOL, 900, 6.0F, 3.0F, 10, REPAIRS_SLAGSTEEL);

	/**
	 * ArmorMaterial is a record: (durability, defense map, enchantmentValue, equipSound,
	 * toughness, knockbackResistance, repairIngredient, assetId) — verified via javap,
	 * mirroring InferniumFeature (defenseMap order: boots, leggings, chestplate,
	 * helmet, body).
	 */
	public static final ArmorMaterial SLAGSTEEL_ARMOR_MATERIAL = new ArmorMaterial(
			24, defenseMap(3, 5, 7, 3, 6), 10,
			SoundEvents.ITEM_ARMOR_EQUIP_IRON, 1.0F, 0.05F, REPAIRS_SLAGSTEEL, SLAGSTEEL_EQUIPMENT_ASSET_ID);

	/** Repair tag, backed by data/copper_inferno/tags/item/cinderforge_repair.json. */
	public static final TagKey<Item> REPAIRS_CINDERFORGE =
			TagKey.of(RegistryKeys.ITEM, CopperInferno.id("cinderforge_repair"));

	/** Custom worn-armor asset: assets/copper_inferno/equipment/cinderforge.json. */
	public static final RegistryKey<EquipmentAsset> CINDERFORGE_EQUIPMENT_ASSET_ID =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("cinderforge"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed,
	 * attackDamageBonus, enchantmentValue, repairItems) — verified via javap,
	 * mirroring InferniumFeature.
	 */
	public static final ToolMaterial CINDERFORGE_TOOL_MATERIAL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_DIAMOND_TOOL, 1400, 8.0F, 3.0F, 12, REPAIRS_CINDERFORGE);

	/**
	 * ArmorMaterial is a record: (durability, defense map, enchantmentValue, equipSound,
	 * toughness, knockbackResistance, repairIngredient, assetId) — verified via javap,
	 * mirroring InferniumFeature (defenseMap order: boots, leggings, chestplate,
	 * helmet, body).
	 */
	public static final ArmorMaterial CINDERFORGE_ARMOR_MATERIAL = new ArmorMaterial(
			33, defenseMap(3, 6, 8, 3, 7), 12,
			SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.0F, 0.0F, REPAIRS_CINDERFORGE, CINDERFORGE_EQUIPMENT_ASSET_ID);

	/** Repair tag, backed by data/copper_inferno/tags/item/molten_titan_repair.json. */
	public static final TagKey<Item> REPAIRS_MOLTEN_TITAN =
			TagKey.of(RegistryKeys.ITEM, CopperInferno.id("molten_titan_repair"));

	/** Custom worn-armor asset: assets/copper_inferno/equipment/molten_titan.json. */
	public static final RegistryKey<EquipmentAsset> MOLTEN_TITAN_EQUIPMENT_ASSET_ID =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("molten_titan"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed,
	 * attackDamageBonus, enchantmentValue, repairItems) — verified via javap,
	 * mirroring InferniumFeature.
	 */
	public static final ToolMaterial MOLTEN_TITAN_TOOL_MATERIAL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_DIAMOND_TOOL, 1800, 8.5F, 3.5F, 14, REPAIRS_MOLTEN_TITAN);

	/**
	 * ArmorMaterial is a record: (durability, defense map, enchantmentValue, equipSound,
	 * toughness, knockbackResistance, repairIngredient, assetId) — verified via javap,
	 * mirroring InferniumFeature (defenseMap order: boots, leggings, chestplate,
	 * helmet, body).
	 */
	public static final ArmorMaterial MOLTEN_TITAN_ARMOR_MATERIAL = new ArmorMaterial(
			36, defenseMap(3, 6, 8, 3, 8), 14,
			SoundEvents.ITEM_ARMOR_EQUIP_NETHERITE, 2.5F, 0.05F, REPAIRS_MOLTEN_TITAN, MOLTEN_TITAN_EQUIPMENT_ASSET_ID);

	/** Repair tag, backed by data/copper_inferno/tags/item/infernal_alloy_repair.json. */
	public static final TagKey<Item> REPAIRS_INFERNAL_ALLOY =
			TagKey.of(RegistryKeys.ITEM, CopperInferno.id("infernal_alloy_repair"));

	/** Custom worn-armor asset: assets/copper_inferno/equipment/infernal_alloy.json. */
	public static final RegistryKey<EquipmentAsset> INFERNAL_ALLOY_EQUIPMENT_ASSET_ID =
			RegistryKey.of(EquipmentAssetKeys.REGISTRY_KEY, CopperInferno.id("infernal_alloy"));

	/**
	 * ToolMaterial is a record: (incorrectBlocksForDrops, durability, speed,
	 * attackDamageBonus, enchantmentValue, repairItems) — verified via javap,
	 * mirroring InferniumFeature.
	 */
	public static final ToolMaterial INFERNAL_ALLOY_TOOL_MATERIAL = new ToolMaterial(
			BlockTags.INCORRECT_FOR_NETHERITE_TOOL, 2400, 9.5F, 4.5F, 18, REPAIRS_INFERNAL_ALLOY);

	/**
	 * ArmorMaterial is a record: (durability, defense map, enchantmentValue, equipSound,
	 * toughness, knockbackResistance, repairIngredient, assetId) — verified via javap,
	 * mirroring InferniumFeature (defenseMap order: boots, leggings, chestplate,
	 * helmet, body).
	 */
	public static final ArmorMaterial INFERNAL_ALLOY_ARMOR_MATERIAL = new ArmorMaterial(
			40, defenseMap(4, 7, 9, 4, 9), 18,
			SoundEvents.ITEM_ARMOR_EQUIP_NETHERITE, 3.5F, 0.1F, REPAIRS_INFERNAL_ALLOY, INFERNAL_ALLOY_EQUIPMENT_ASSET_ID);

	private static Map<EquipmentType, Integer> defenseMap(int boots, int leggings, int chestplate, int helmet, int body) {
		Map<EquipmentType, Integer> map = new EnumMap<>(EquipmentType.class);
		map.put(EquipmentType.BOOTS, boots);
		map.put(EquipmentType.LEGGINGS, leggings);
		map.put(EquipmentType.CHESTPLATE, chestplate);
		map.put(EquipmentType.HELMET, helmet);
		map.put(EquipmentType.BODY, body);
		return map;
	}

	public static void init() {
		EMBER_STEEL_INGOT = ModItems.register("ember_steel_ingot", Item::new, new Item.Settings().maxCount(64));
		EMBER_STEEL_SWORD = ModItems.register("ember_steel_sword", Item::new, new Item.Settings().sword(EMBER_STEEL_TOOL_MATERIAL, 3.0F, -2.4F));
		EMBER_STEEL_PICKAXE = ModItems.register("ember_steel_pickaxe", Item::new, new Item.Settings().pickaxe(EMBER_STEEL_TOOL_MATERIAL, 1.0F, -2.8F));
		EMBER_STEEL_AXE = ModItems.register("ember_steel_axe", s -> new AxeItem(EMBER_STEEL_TOOL_MATERIAL, 5.0F, -3.0F, s), new Item.Settings());
		EMBER_STEEL_SHOVEL = ModItems.register("ember_steel_shovel", s -> new ShovelItem(EMBER_STEEL_TOOL_MATERIAL, 1.5F, -3.0F, s), new Item.Settings());
		EMBER_STEEL_HOE = ModItems.register("ember_steel_hoe", s -> new HoeItem(EMBER_STEEL_TOOL_MATERIAL, -3.0F, 0.0F, s), new Item.Settings());
		EMBER_STEEL_HELMET = ModItems.register("ember_steel_helmet", Item::new, new Item.Settings().armor(EMBER_STEEL_ARMOR_MATERIAL, EquipmentType.HELMET));
		EMBER_STEEL_CHESTPLATE = ModItems.register("ember_steel_chestplate", Item::new, new Item.Settings().armor(EMBER_STEEL_ARMOR_MATERIAL, EquipmentType.CHESTPLATE));
		EMBER_STEEL_LEGGINGS = ModItems.register("ember_steel_leggings", Item::new, new Item.Settings().armor(EMBER_STEEL_ARMOR_MATERIAL, EquipmentType.LEGGINGS));
		EMBER_STEEL_BOOTS = ModItems.register("ember_steel_boots", Item::new, new Item.Settings().armor(EMBER_STEEL_ARMOR_MATERIAL, EquipmentType.BOOTS));
		EMBER_STEEL_CHARM = ModItems.register("ember_steel_charm", Item::new, new Item.Settings().maxCount(16));
		EMBER_STEEL_TOTEM = ModItems.register("ember_steel_totem", Item::new, new Item.Settings().maxCount(16));
		EMBER_STEEL_RING = ModItems.register("ember_steel_ring", Item::new, new Item.Settings().maxCount(16));
		EMBER_STEEL_AMULET = ModItems.register("ember_steel_amulet", Item::new, new Item.Settings().maxCount(16));
		EMBER_STEEL_TALISMAN = ModItems.register("ember_steel_talisman", Item::new, new Item.Settings().maxCount(16));
		EMBER_STEEL_MEDALLION = ModItems.register("ember_steel_medallion", Item::new, new Item.Settings().maxCount(16));
		PYRITE_INGOT = ModItems.register("pyrite_ingot", Item::new, new Item.Settings().maxCount(64));
		PYRITE_SWORD = ModItems.register("pyrite_sword", Item::new, new Item.Settings().sword(PYRITE_TOOL_MATERIAL, 3.0F, -2.4F));
		PYRITE_PICKAXE = ModItems.register("pyrite_pickaxe", Item::new, new Item.Settings().pickaxe(PYRITE_TOOL_MATERIAL, 1.0F, -2.8F));
		PYRITE_AXE = ModItems.register("pyrite_axe", s -> new AxeItem(PYRITE_TOOL_MATERIAL, 5.0F, -3.0F, s), new Item.Settings());
		PYRITE_SHOVEL = ModItems.register("pyrite_shovel", s -> new ShovelItem(PYRITE_TOOL_MATERIAL, 1.5F, -3.0F, s), new Item.Settings());
		PYRITE_HOE = ModItems.register("pyrite_hoe", s -> new HoeItem(PYRITE_TOOL_MATERIAL, -3.0F, 0.0F, s), new Item.Settings());
		PYRITE_HELMET = ModItems.register("pyrite_helmet", Item::new, new Item.Settings().armor(PYRITE_ARMOR_MATERIAL, EquipmentType.HELMET));
		PYRITE_CHESTPLATE = ModItems.register("pyrite_chestplate", Item::new, new Item.Settings().armor(PYRITE_ARMOR_MATERIAL, EquipmentType.CHESTPLATE));
		PYRITE_LEGGINGS = ModItems.register("pyrite_leggings", Item::new, new Item.Settings().armor(PYRITE_ARMOR_MATERIAL, EquipmentType.LEGGINGS));
		PYRITE_BOOTS = ModItems.register("pyrite_boots", Item::new, new Item.Settings().armor(PYRITE_ARMOR_MATERIAL, EquipmentType.BOOTS));
		PYRITE_CHARM = ModItems.register("pyrite_charm", Item::new, new Item.Settings().maxCount(16));
		PYRITE_TOTEM = ModItems.register("pyrite_totem", Item::new, new Item.Settings().maxCount(16));
		PYRITE_RING = ModItems.register("pyrite_ring", Item::new, new Item.Settings().maxCount(16));
		PYRITE_AMULET = ModItems.register("pyrite_amulet", Item::new, new Item.Settings().maxCount(16));
		PYRITE_TALISMAN = ModItems.register("pyrite_talisman", Item::new, new Item.Settings().maxCount(16));
		PYRITE_MEDALLION = ModItems.register("pyrite_medallion", Item::new, new Item.Settings().maxCount(16));
		SLAGSTEEL_INGOT = ModItems.register("slagsteel_ingot", Item::new, new Item.Settings().maxCount(64));
		SLAGSTEEL_SWORD = ModItems.register("slagsteel_sword", Item::new, new Item.Settings().sword(SLAGSTEEL_TOOL_MATERIAL, 3.0F, -2.4F));
		SLAGSTEEL_PICKAXE = ModItems.register("slagsteel_pickaxe", Item::new, new Item.Settings().pickaxe(SLAGSTEEL_TOOL_MATERIAL, 1.0F, -2.8F));
		SLAGSTEEL_AXE = ModItems.register("slagsteel_axe", s -> new AxeItem(SLAGSTEEL_TOOL_MATERIAL, 5.0F, -3.0F, s), new Item.Settings());
		SLAGSTEEL_SHOVEL = ModItems.register("slagsteel_shovel", s -> new ShovelItem(SLAGSTEEL_TOOL_MATERIAL, 1.5F, -3.0F, s), new Item.Settings());
		SLAGSTEEL_HOE = ModItems.register("slagsteel_hoe", s -> new HoeItem(SLAGSTEEL_TOOL_MATERIAL, -3.0F, 0.0F, s), new Item.Settings());
		SLAGSTEEL_HELMET = ModItems.register("slagsteel_helmet", Item::new, new Item.Settings().armor(SLAGSTEEL_ARMOR_MATERIAL, EquipmentType.HELMET));
		SLAGSTEEL_CHESTPLATE = ModItems.register("slagsteel_chestplate", Item::new, new Item.Settings().armor(SLAGSTEEL_ARMOR_MATERIAL, EquipmentType.CHESTPLATE));
		SLAGSTEEL_LEGGINGS = ModItems.register("slagsteel_leggings", Item::new, new Item.Settings().armor(SLAGSTEEL_ARMOR_MATERIAL, EquipmentType.LEGGINGS));
		SLAGSTEEL_BOOTS = ModItems.register("slagsteel_boots", Item::new, new Item.Settings().armor(SLAGSTEEL_ARMOR_MATERIAL, EquipmentType.BOOTS));
		SLAGSTEEL_CHARM = ModItems.register("slagsteel_charm", Item::new, new Item.Settings().maxCount(16));
		SLAGSTEEL_TOTEM = ModItems.register("slagsteel_totem", Item::new, new Item.Settings().maxCount(16));
		SLAGSTEEL_RING = ModItems.register("slagsteel_ring", Item::new, new Item.Settings().maxCount(16));
		SLAGSTEEL_AMULET = ModItems.register("slagsteel_amulet", Item::new, new Item.Settings().maxCount(16));
		SLAGSTEEL_TALISMAN = ModItems.register("slagsteel_talisman", Item::new, new Item.Settings().maxCount(16));
		SLAGSTEEL_MEDALLION = ModItems.register("slagsteel_medallion", Item::new, new Item.Settings().maxCount(16));
		CINDERFORGE_INGOT = ModItems.register("cinderforge_ingot", Item::new, new Item.Settings().maxCount(64));
		CINDERFORGE_SWORD = ModItems.register("cinderforge_sword", Item::new, new Item.Settings().sword(CINDERFORGE_TOOL_MATERIAL, 3.0F, -2.4F));
		CINDERFORGE_PICKAXE = ModItems.register("cinderforge_pickaxe", Item::new, new Item.Settings().pickaxe(CINDERFORGE_TOOL_MATERIAL, 1.0F, -2.8F));
		CINDERFORGE_AXE = ModItems.register("cinderforge_axe", s -> new AxeItem(CINDERFORGE_TOOL_MATERIAL, 5.0F, -3.0F, s), new Item.Settings());
		CINDERFORGE_SHOVEL = ModItems.register("cinderforge_shovel", s -> new ShovelItem(CINDERFORGE_TOOL_MATERIAL, 1.5F, -3.0F, s), new Item.Settings());
		CINDERFORGE_HOE = ModItems.register("cinderforge_hoe", s -> new HoeItem(CINDERFORGE_TOOL_MATERIAL, -3.0F, 0.0F, s), new Item.Settings());
		CINDERFORGE_HELMET = ModItems.register("cinderforge_helmet", Item::new, new Item.Settings().armor(CINDERFORGE_ARMOR_MATERIAL, EquipmentType.HELMET));
		CINDERFORGE_CHESTPLATE = ModItems.register("cinderforge_chestplate", Item::new, new Item.Settings().armor(CINDERFORGE_ARMOR_MATERIAL, EquipmentType.CHESTPLATE));
		CINDERFORGE_LEGGINGS = ModItems.register("cinderforge_leggings", Item::new, new Item.Settings().armor(CINDERFORGE_ARMOR_MATERIAL, EquipmentType.LEGGINGS));
		CINDERFORGE_BOOTS = ModItems.register("cinderforge_boots", Item::new, new Item.Settings().armor(CINDERFORGE_ARMOR_MATERIAL, EquipmentType.BOOTS));
		CINDERFORGE_CHARM = ModItems.register("cinderforge_charm", Item::new, new Item.Settings().maxCount(16));
		CINDERFORGE_TOTEM = ModItems.register("cinderforge_totem", Item::new, new Item.Settings().maxCount(16));
		CINDERFORGE_RING = ModItems.register("cinderforge_ring", Item::new, new Item.Settings().maxCount(16));
		CINDERFORGE_AMULET = ModItems.register("cinderforge_amulet", Item::new, new Item.Settings().maxCount(16));
		CINDERFORGE_TALISMAN = ModItems.register("cinderforge_talisman", Item::new, new Item.Settings().maxCount(16));
		CINDERFORGE_MEDALLION = ModItems.register("cinderforge_medallion", Item::new, new Item.Settings().maxCount(16));
		MOLTEN_TITAN_INGOT = ModItems.register("molten_titan_ingot", Item::new, new Item.Settings().maxCount(64).fireproof());
		MOLTEN_TITAN_SWORD = ModItems.register("molten_titan_sword", Item::new, new Item.Settings().sword(MOLTEN_TITAN_TOOL_MATERIAL, 3.0F, -2.4F).fireproof());
		MOLTEN_TITAN_PICKAXE = ModItems.register("molten_titan_pickaxe", Item::new, new Item.Settings().pickaxe(MOLTEN_TITAN_TOOL_MATERIAL, 1.0F, -2.8F).fireproof());
		MOLTEN_TITAN_AXE = ModItems.register("molten_titan_axe", s -> new AxeItem(MOLTEN_TITAN_TOOL_MATERIAL, 5.0F, -3.0F, s), new Item.Settings().fireproof());
		MOLTEN_TITAN_SHOVEL = ModItems.register("molten_titan_shovel", s -> new ShovelItem(MOLTEN_TITAN_TOOL_MATERIAL, 1.5F, -3.0F, s), new Item.Settings().fireproof());
		MOLTEN_TITAN_HOE = ModItems.register("molten_titan_hoe", s -> new HoeItem(MOLTEN_TITAN_TOOL_MATERIAL, -3.0F, 0.0F, s), new Item.Settings().fireproof());
		MOLTEN_TITAN_HELMET = ModItems.register("molten_titan_helmet", Item::new, new Item.Settings().armor(MOLTEN_TITAN_ARMOR_MATERIAL, EquipmentType.HELMET).fireproof());
		MOLTEN_TITAN_CHESTPLATE = ModItems.register("molten_titan_chestplate", Item::new, new Item.Settings().armor(MOLTEN_TITAN_ARMOR_MATERIAL, EquipmentType.CHESTPLATE).fireproof());
		MOLTEN_TITAN_LEGGINGS = ModItems.register("molten_titan_leggings", Item::new, new Item.Settings().armor(MOLTEN_TITAN_ARMOR_MATERIAL, EquipmentType.LEGGINGS).fireproof());
		MOLTEN_TITAN_BOOTS = ModItems.register("molten_titan_boots", Item::new, new Item.Settings().armor(MOLTEN_TITAN_ARMOR_MATERIAL, EquipmentType.BOOTS).fireproof());
		MOLTEN_TITAN_CHARM = ModItems.register("molten_titan_charm", Item::new, new Item.Settings().maxCount(16).fireproof());
		MOLTEN_TITAN_TOTEM = ModItems.register("molten_titan_totem", Item::new, new Item.Settings().maxCount(16).fireproof());
		MOLTEN_TITAN_RING = ModItems.register("molten_titan_ring", Item::new, new Item.Settings().maxCount(16).fireproof());
		MOLTEN_TITAN_AMULET = ModItems.register("molten_titan_amulet", Item::new, new Item.Settings().maxCount(16).fireproof());
		MOLTEN_TITAN_TALISMAN = ModItems.register("molten_titan_talisman", Item::new, new Item.Settings().maxCount(16).fireproof());
		MOLTEN_TITAN_MEDALLION = ModItems.register("molten_titan_medallion", Item::new, new Item.Settings().maxCount(16).fireproof());
		INFERNAL_ALLOY_INGOT = ModItems.register("infernal_alloy_ingot", Item::new, new Item.Settings().maxCount(64).fireproof());
		INFERNAL_ALLOY_SWORD = ModItems.register("infernal_alloy_sword", Item::new, new Item.Settings().sword(INFERNAL_ALLOY_TOOL_MATERIAL, 3.0F, -2.4F).fireproof());
		INFERNAL_ALLOY_PICKAXE = ModItems.register("infernal_alloy_pickaxe", Item::new, new Item.Settings().pickaxe(INFERNAL_ALLOY_TOOL_MATERIAL, 1.0F, -2.8F).fireproof());
		INFERNAL_ALLOY_AXE = ModItems.register("infernal_alloy_axe", s -> new AxeItem(INFERNAL_ALLOY_TOOL_MATERIAL, 5.0F, -3.0F, s), new Item.Settings().fireproof());
		INFERNAL_ALLOY_SHOVEL = ModItems.register("infernal_alloy_shovel", s -> new ShovelItem(INFERNAL_ALLOY_TOOL_MATERIAL, 1.5F, -3.0F, s), new Item.Settings().fireproof());
		INFERNAL_ALLOY_HOE = ModItems.register("infernal_alloy_hoe", s -> new HoeItem(INFERNAL_ALLOY_TOOL_MATERIAL, -3.0F, 0.0F, s), new Item.Settings().fireproof());
		INFERNAL_ALLOY_HELMET = ModItems.register("infernal_alloy_helmet", Item::new, new Item.Settings().armor(INFERNAL_ALLOY_ARMOR_MATERIAL, EquipmentType.HELMET).fireproof());
		INFERNAL_ALLOY_CHESTPLATE = ModItems.register("infernal_alloy_chestplate", Item::new, new Item.Settings().armor(INFERNAL_ALLOY_ARMOR_MATERIAL, EquipmentType.CHESTPLATE).fireproof());
		INFERNAL_ALLOY_LEGGINGS = ModItems.register("infernal_alloy_leggings", Item::new, new Item.Settings().armor(INFERNAL_ALLOY_ARMOR_MATERIAL, EquipmentType.LEGGINGS).fireproof());
		INFERNAL_ALLOY_BOOTS = ModItems.register("infernal_alloy_boots", Item::new, new Item.Settings().armor(INFERNAL_ALLOY_ARMOR_MATERIAL, EquipmentType.BOOTS).fireproof());
		INFERNAL_ALLOY_CHARM = ModItems.register("infernal_alloy_charm", Item::new, new Item.Settings().maxCount(16).fireproof());
		INFERNAL_ALLOY_TOTEM = ModItems.register("infernal_alloy_totem", Item::new, new Item.Settings().maxCount(16).fireproof());
		INFERNAL_ALLOY_RING = ModItems.register("infernal_alloy_ring", Item::new, new Item.Settings().maxCount(16).fireproof());
		INFERNAL_ALLOY_AMULET = ModItems.register("infernal_alloy_amulet", Item::new, new Item.Settings().maxCount(16).fireproof());
		INFERNAL_ALLOY_TALISMAN = ModItems.register("infernal_alloy_talisman", Item::new, new Item.Settings().maxCount(16).fireproof());
		INFERNAL_ALLOY_MEDALLION = ModItems.register("infernal_alloy_medallion", Item::new, new Item.Settings().maxCount(16).fireproof());

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.EQUIPMENT_KEY).register(entries -> {
			entries.add(EMBER_STEEL_INGOT);
			entries.add(EMBER_STEEL_SWORD);
			entries.add(EMBER_STEEL_PICKAXE);
			entries.add(EMBER_STEEL_AXE);
			entries.add(EMBER_STEEL_SHOVEL);
			entries.add(EMBER_STEEL_HOE);
			entries.add(EMBER_STEEL_HELMET);
			entries.add(EMBER_STEEL_CHESTPLATE);
			entries.add(EMBER_STEEL_LEGGINGS);
			entries.add(EMBER_STEEL_BOOTS);
			entries.add(EMBER_STEEL_CHARM);
			entries.add(EMBER_STEEL_TOTEM);
			entries.add(EMBER_STEEL_RING);
			entries.add(EMBER_STEEL_AMULET);
			entries.add(EMBER_STEEL_TALISMAN);
			entries.add(EMBER_STEEL_MEDALLION);
			entries.add(PYRITE_INGOT);
			entries.add(PYRITE_SWORD);
			entries.add(PYRITE_PICKAXE);
			entries.add(PYRITE_AXE);
			entries.add(PYRITE_SHOVEL);
			entries.add(PYRITE_HOE);
			entries.add(PYRITE_HELMET);
			entries.add(PYRITE_CHESTPLATE);
			entries.add(PYRITE_LEGGINGS);
			entries.add(PYRITE_BOOTS);
			entries.add(PYRITE_CHARM);
			entries.add(PYRITE_TOTEM);
			entries.add(PYRITE_RING);
			entries.add(PYRITE_AMULET);
			entries.add(PYRITE_TALISMAN);
			entries.add(PYRITE_MEDALLION);
			entries.add(SLAGSTEEL_INGOT);
			entries.add(SLAGSTEEL_SWORD);
			entries.add(SLAGSTEEL_PICKAXE);
			entries.add(SLAGSTEEL_AXE);
			entries.add(SLAGSTEEL_SHOVEL);
			entries.add(SLAGSTEEL_HOE);
			entries.add(SLAGSTEEL_HELMET);
			entries.add(SLAGSTEEL_CHESTPLATE);
			entries.add(SLAGSTEEL_LEGGINGS);
			entries.add(SLAGSTEEL_BOOTS);
			entries.add(SLAGSTEEL_CHARM);
			entries.add(SLAGSTEEL_TOTEM);
			entries.add(SLAGSTEEL_RING);
			entries.add(SLAGSTEEL_AMULET);
			entries.add(SLAGSTEEL_TALISMAN);
			entries.add(SLAGSTEEL_MEDALLION);
			entries.add(CINDERFORGE_INGOT);
			entries.add(CINDERFORGE_SWORD);
			entries.add(CINDERFORGE_PICKAXE);
			entries.add(CINDERFORGE_AXE);
			entries.add(CINDERFORGE_SHOVEL);
			entries.add(CINDERFORGE_HOE);
			entries.add(CINDERFORGE_HELMET);
			entries.add(CINDERFORGE_CHESTPLATE);
			entries.add(CINDERFORGE_LEGGINGS);
			entries.add(CINDERFORGE_BOOTS);
			entries.add(CINDERFORGE_CHARM);
			entries.add(CINDERFORGE_TOTEM);
			entries.add(CINDERFORGE_RING);
			entries.add(CINDERFORGE_AMULET);
			entries.add(CINDERFORGE_TALISMAN);
			entries.add(CINDERFORGE_MEDALLION);
			entries.add(MOLTEN_TITAN_INGOT);
			entries.add(MOLTEN_TITAN_SWORD);
			entries.add(MOLTEN_TITAN_PICKAXE);
			entries.add(MOLTEN_TITAN_AXE);
			entries.add(MOLTEN_TITAN_SHOVEL);
			entries.add(MOLTEN_TITAN_HOE);
			entries.add(MOLTEN_TITAN_HELMET);
			entries.add(MOLTEN_TITAN_CHESTPLATE);
			entries.add(MOLTEN_TITAN_LEGGINGS);
			entries.add(MOLTEN_TITAN_BOOTS);
			entries.add(MOLTEN_TITAN_CHARM);
			entries.add(MOLTEN_TITAN_TOTEM);
			entries.add(MOLTEN_TITAN_RING);
			entries.add(MOLTEN_TITAN_AMULET);
			entries.add(MOLTEN_TITAN_TALISMAN);
			entries.add(MOLTEN_TITAN_MEDALLION);
			entries.add(INFERNAL_ALLOY_INGOT);
			entries.add(INFERNAL_ALLOY_SWORD);
			entries.add(INFERNAL_ALLOY_PICKAXE);
			entries.add(INFERNAL_ALLOY_AXE);
			entries.add(INFERNAL_ALLOY_SHOVEL);
			entries.add(INFERNAL_ALLOY_HOE);
			entries.add(INFERNAL_ALLOY_HELMET);
			entries.add(INFERNAL_ALLOY_CHESTPLATE);
			entries.add(INFERNAL_ALLOY_LEGGINGS);
			entries.add(INFERNAL_ALLOY_BOOTS);
			entries.add(INFERNAL_ALLOY_CHARM);
			entries.add(INFERNAL_ALLOY_TOTEM);
			entries.add(INFERNAL_ALLOY_RING);
			entries.add(INFERNAL_ALLOY_AMULET);
			entries.add(INFERNAL_ALLOY_TALISMAN);
			entries.add(INFERNAL_ALLOY_MEDALLION);
		});

		TitanForgeHandbook.register();
	}
}
