package net.sonic0810.copperinferno.feature.shrines;

import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.world.gen.GenerationStep;
import net.minecraft.world.gen.feature.DefaultFeatureConfig;
import net.minecraft.world.gen.feature.Feature;
import net.minecraft.world.gen.feature.PlacedFeature;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4.1 "Shrines" feature: small copper shrines scattered across the Overworld. The shrine
 * itself is built in code by {@link CopperShrineWorldgenFeature}, a custom
 * {@code Feature<DefaultFeatureConfig>} registered here in {@code Registries.FEATURE}
 * (signature verified via javap) and referenced from
 * {@code data/copper_inferno/worldgen/configured_feature/copper_shrine.json}; the placement
 * is data-driven ({@code placed_feature/copper_shrine.json}, rarity 40 + surface heightmap)
 * and injected via {@code BiomeModifications.addFeature} at SURFACE_STRUCTURES. Same
 * pattern as {@code feature.wildworld.RuinedForgesFeature}; assets/data are generated by
 * {@code devtools/gen/shrines_gen.py}.
 */
public final class ShrinesFeature {
	private ShrinesFeature() {
	}

	public static Feature<DefaultFeatureConfig> COPPER_SHRINE;

	public static void init() {
		COPPER_SHRINE = Registry.register(Registries.FEATURE,
				CopperInferno.id("copper_shrine"),
				new CopperShrineWorldgenFeature(DefaultFeatureConfig.CODEC));

		RegistryKey<PlacedFeature> shrine =
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("copper_shrine"));
		BiomeModifications.addFeature(BiomeSelectors.foundInOverworld(),
				GenerationStep.Feature.SURFACE_STRUCTURES, shrine);

		HandbookEntries.add(new HandbookEntry("dimension", "shrines_copper_shrine",
				"copper_inferno:copper_pillar", null, null, null, 0,
				"Copper Shrines: small daises of stone brick and copper raised across the"
						+ " Overworld by early copper cultists. Four pillars carry ember lanterns"
						+ " that never go out, and the chest between them still holds their"
						+ " offerings — copper, gemalloy nuggets and the odd Dr.Pepper.",
				"Kupferschreine: kleine Podeste aus Steinziegeln und Kupfer, die frühe"
						+ " Kupferkultisten überall in der Oberwelt errichteten. Vier Säulen tragen"
						+ " Glutlaternen, die niemals erlöschen, und die Truhe dazwischen birgt noch"
						+ " immer ihre Opfergaben — Kupfer, Gemallo-Nuggets und ab und zu ein"
						+ " Dr.Pepper."));
	}
}
