package net.sonic0810.copperinferno.feature.sodafauna.client;

import net.minecraft.client.render.entity.BatEntityRenderer;
import net.minecraft.client.render.entity.BeeEntityRenderer;
import net.minecraft.client.render.entity.CatEntityRenderer;
import net.minecraft.client.render.entity.ChickenEntityRenderer;
import net.minecraft.client.render.entity.CreeperEntityRenderer;
import net.minecraft.client.render.entity.EntityRendererFactories;
import net.minecraft.client.render.entity.FoxEntityRenderer;
import net.minecraft.client.render.entity.FrogEntityRenderer;
import net.minecraft.client.render.entity.HoglinEntityRenderer;
import net.minecraft.client.render.entity.MagmaCubeEntityRenderer;
import net.minecraft.client.render.entity.ParrotEntityRenderer;
import net.minecraft.client.render.entity.PhantomEntityRenderer;
import net.minecraft.client.render.entity.RabbitEntityRenderer;
import net.minecraft.client.render.entity.SheepEntityRenderer;
import net.minecraft.client.render.entity.SilverfishEntityRenderer;
import net.minecraft.client.render.entity.SkeletonEntityRenderer;
import net.minecraft.client.render.entity.SlimeEntityRenderer;
import net.minecraft.client.render.entity.SnowGolemEntityRenderer;
import net.minecraft.client.render.entity.SpiderEntityRenderer;
import net.minecraft.client.render.entity.StrayEntityRenderer;
import net.minecraft.client.render.entity.VexEntityRenderer;
import net.minecraft.client.render.entity.WitchEntityRenderer;
import net.minecraft.client.render.entity.WolfEntityRenderer;
import net.minecraft.client.render.entity.ZombieEntityRenderer;
import net.minecraft.client.render.entity.state.BatEntityRenderState;
import net.minecraft.client.render.entity.state.BeeEntityRenderState;
import net.minecraft.client.render.entity.state.CatEntityRenderState;
import net.minecraft.client.render.entity.state.ChickenEntityRenderState;
import net.minecraft.client.render.entity.state.CreeperEntityRenderState;
import net.minecraft.client.render.entity.state.FoxEntityRenderState;
import net.minecraft.client.render.entity.state.FrogEntityRenderState;
import net.minecraft.client.render.entity.state.HoglinEntityRenderState;
import net.minecraft.client.render.entity.state.LivingEntityRenderState;
import net.minecraft.client.render.entity.state.ParrotEntityRenderState;
import net.minecraft.client.render.entity.state.PhantomEntityRenderState;
import net.minecraft.client.render.entity.state.RabbitEntityRenderState;
import net.minecraft.client.render.entity.state.SheepEntityRenderState;
import net.minecraft.client.render.entity.state.SkeletonEntityRenderState;
import net.minecraft.client.render.entity.state.SlimeEntityRenderState;
import net.minecraft.client.render.entity.state.SnowGolemEntityRenderState;
import net.minecraft.client.render.entity.state.VexEntityRenderState;
import net.minecraft.client.render.entity.state.WitchEntityRenderState;
import net.minecraft.client.render.entity.state.WolfEntityRenderState;
import net.minecraft.client.render.entity.state.ZombieEntityRenderState;
import net.minecraft.util.Identifier;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.feature.sodafauna.SodaFaunaFeature;
import net.sonic0810.copperinferno.feature.sodafauna.SyrupSpiderEntity;

/**
 * Client-side setup for the Soda &amp; Candy Fauna: every mob reuses its vanilla renderer as an
 * anonymous subclass whose {@code getTexture(<state>)} override points at the recolored
 * soda/candy skin under {@code textures/entity/sodafauna/} (generated by
 * {@code devtools/gen/sodafauna_gen.py} from the vanilla textures). Every override signature was
 * verified via javap against the 1.21.9 loom jars; all 24 renderers expose an overridable
 * {@code getTexture}, so no mob had to fall back to the untextured vanilla renderer. Layer/
 * feature textures that vanilla renders on top (sheep wool, stray overlay, cat collar, phantom
 * eyes, creeper charge) intentionally stay vanilla. All 24 vanilla renderer constructors are
 * Context-only (SpiderEntityRenderer is generic over the entity, bound to SyrupSpiderEntity);
 * the register method is access-widened by Fabric's transitive access wideners (same proven
 * pattern as infernomobs).
 */
public final class SodaFaunaFeatureClient {
	private SodaFaunaFeatureClient() {
	}

	private static Identifier tex(String id) {
		return CopperInferno.id("textures/entity/sodafauna/" + id + ".png");
	}

	public static void initClient() {
		Identifier fizzSlime = tex("fizz_slime");
		EntityRendererFactories.register(SodaFaunaFeature.FIZZ_SLIME, ctx -> new SlimeEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(SlimeEntityRenderState state) {
				return fizzSlime;
			}
		});
		Identifier colaCube = tex("cola_cube");
		EntityRendererFactories.register(SodaFaunaFeature.COLA_CUBE, ctx -> new MagmaCubeEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(SlimeEntityRenderState state) {
				return colaCube;
			}
		});
		Identifier sodaSprite = tex("soda_sprite");
		EntityRendererFactories.register(SodaFaunaFeature.SODA_SPRITE, ctx -> new VexEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(VexEntityRenderState state) {
				return sodaSprite;
			}
		});
		Identifier gummyHopper = tex("gummy_hopper");
		EntityRendererFactories.register(SodaFaunaFeature.GUMMY_HOPPER, ctx -> new RabbitEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(RabbitEntityRenderState state) {
				return gummyHopper;
			}
		});
		Identifier caramelGolem = tex("caramel_golem");
		EntityRendererFactories.register(SodaFaunaFeature.CARAMEL_GOLEM, ctx -> new SnowGolemEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(SnowGolemEntityRenderState state) {
				return caramelGolem;
			}
		});
		Identifier syrupSpider = tex("syrup_spider");
		EntityRendererFactories.register(SodaFaunaFeature.SYRUP_SPIDER,
				ctx -> new SpiderEntityRenderer<SyrupSpiderEntity>(ctx) {
					@Override
					public Identifier getTexture(LivingEntityRenderState state) {
						return syrupSpider;
					}
				});
		Identifier bottlecapBeetle = tex("bottlecap_beetle");
		EntityRendererFactories.register(SodaFaunaFeature.BOTTLECAP_BEETLE, ctx -> new SilverfishEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(LivingEntityRenderState state) {
				return bottlecapBeetle;
			}
		});
		Identifier sugarRushFox = tex("sugar_rush_fox");
		EntityRendererFactories.register(SodaFaunaFeature.SUGAR_RUSH_FOX, ctx -> new FoxEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(FoxEntityRenderState state) {
				return sugarRushFox;
			}
		});
		Identifier rootBeerBoar = tex("root_beer_boar");
		EntityRendererFactories.register(SodaFaunaFeature.ROOT_BEER_BOAR, ctx -> new HoglinEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(HoglinEntityRenderState state) {
				return rootBeerBoar;
			}
		});
		Identifier creamCat = tex("cream_cat");
		EntityRendererFactories.register(SodaFaunaFeature.CREAM_CAT, ctx -> new CatEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(CatEntityRenderState state) {
				return creamCat;
			}
		});
		Identifier pepperPup = tex("pepper_pup");
		EntityRendererFactories.register(SodaFaunaFeature.PEPPER_PUP, ctx -> new WolfEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(WolfEntityRenderState state) {
				return pepperPup;
			}
		});
		Identifier cherryBee = tex("cherry_bee");
		EntityRendererFactories.register(SodaFaunaFeature.CHERRY_BEE, ctx -> new BeeEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(BeeEntityRenderState state) {
				return cherryBee;
			}
		});
		Identifier grapeBat = tex("grape_bat");
		EntityRendererFactories.register(SodaFaunaFeature.GRAPE_BAT, ctx -> new BatEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(BatEntityRenderState state) {
				return grapeBat;
			}
		});
		Identifier limeFrog = tex("lime_frog");
		EntityRendererFactories.register(SodaFaunaFeature.LIME_FROG, ctx -> new FrogEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(FrogEntityRenderState state) {
				return limeFrog;
			}
		});
		Identifier vanillaSheep = tex("vanilla_sheep");
		EntityRendererFactories.register(SodaFaunaFeature.VANILLA_SHEEP, ctx -> new SheepEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(SheepEntityRenderState state) {
				return vanillaSheep;
			}
		});
		Identifier cannedCreeper = tex("canned_creeper");
		EntityRendererFactories.register(SodaFaunaFeature.CANNED_CREEPER, ctx -> new CreeperEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(CreeperEntityRenderState state) {
				return cannedCreeper;
			}
		});
		Identifier sodaWitch = tex("soda_witch");
		EntityRendererFactories.register(SodaFaunaFeature.SODA_WITCH, ctx -> new WitchEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(WitchEntityRenderState state) {
				return sodaWitch;
			}
		});
		Identifier floatPhantom = tex("float_phantom");
		EntityRendererFactories.register(SodaFaunaFeature.FLOAT_PHANTOM, ctx -> new PhantomEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(PhantomEntityRenderState state) {
				return floatPhantom;
			}
		});
		Identifier fizzyChicken = tex("fizzy_chicken");
		EntityRendererFactories.register(SodaFaunaFeature.FIZZY_CHICKEN, ctx -> new ChickenEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(ChickenEntityRenderState state) {
				return fizzyChicken;
			}
		});
		Identifier dietZombie = tex("diet_zombie");
		EntityRendererFactories.register(SodaFaunaFeature.DIET_ZOMBIE, ctx -> new ZombieEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(ZombieEntityRenderState state) {
				return dietZombie;
			}
		});
		Identifier sugarSkeleton = tex("sugar_skeleton");
		EntityRendererFactories.register(SodaFaunaFeature.SUGAR_SKELETON, ctx -> new SkeletonEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(SkeletonEntityRenderState state) {
				return sugarSkeleton;
			}
		});
		Identifier carbonatedCube = tex("carbonated_cube");
		EntityRendererFactories.register(SodaFaunaFeature.CARBONATED_CUBE, ctx -> new MagmaCubeEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(SlimeEntityRenderState state) {
				return carbonatedCube;
			}
		});
		Identifier strawStray = tex("straw_stray");
		EntityRendererFactories.register(SodaFaunaFeature.STRAW_STRAY, ctx -> new StrayEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(SkeletonEntityRenderState state) {
				return strawStray;
			}
		});
		Identifier popParrot = tex("pop_parrot");
		EntityRendererFactories.register(SodaFaunaFeature.POP_PARROT, ctx -> new ParrotEntityRenderer(ctx) {
			@Override
			public Identifier getTexture(ParrotEntityRenderState state) {
				return popParrot;
			}
		});
	}
}
