package net.sonic0810.copperinferno.feature.bosspantheon.client;

import net.minecraft.client.render.entity.BlazeEntityRenderer;
import net.minecraft.client.render.entity.EntityRendererFactories;
import net.minecraft.client.render.entity.EntityRendererFactory;
import net.minecraft.client.render.entity.EvokerEntityRenderer;
import net.minecraft.client.render.entity.GhastEntityRenderer;
import net.minecraft.client.render.entity.IronGolemEntityRenderer;
import net.minecraft.client.render.entity.SlimeEntityRenderer;
import net.minecraft.client.render.entity.VindicatorEntityRenderer;
import net.minecraft.client.render.entity.state.EvokerEntityRenderState;
import net.minecraft.client.render.entity.state.GhastEntityRenderState;
import net.minecraft.client.render.entity.state.IllagerEntityRenderState;
import net.minecraft.client.render.entity.state.IronGolemEntityRenderState;
import net.minecraft.client.render.entity.state.LivingEntityRenderState;
import net.minecraft.client.render.entity.state.SlimeEntityRenderState;
import net.minecraft.util.Identifier;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.feature.bosspantheon.BossPantheonFeature;
import net.sonic0810.copperinferno.feature.bosspantheon.TheVerdigrisProphetEntity;

/**
 * Client-side setup for the Copper Pantheon bosses: every boss reuses its vanilla renderer
 * subclassed ONLY to swap the texture - each subclass overrides the renderer's
 * {@code getTexture(<state>)} (exact state parameter type verified via javap per renderer:
 * EvokerEntityRenderState for the prophet, IronGolemEntityRenderState for the warden,
 * GhastEntityRenderState for the hydra, LivingEntityRenderState for the blaze-based
 * conductor, SlimeEntityRenderState for the king and IllagerEntityRenderState for the
 * executioner) to return the recolored vanilla entity texture generated by
 * {@code devtools/gen/bosspantheon_gen.py} into
 * {@code assets/copper_inferno/textures/entity/bosspantheon/}. All six vanilla renderer
 * ctors are Context-only (javap-verified); the bosses extend the matching vanilla
 * entities, so the factories fit the
 * {@code register(EntityType<? extends T>, EntityRendererFactory<T>)} bound (vanilla
 * register is access-widened by Fabric's transitive access wideners - the proven
 * infernofauna/constructs pattern). No renderer fallback was needed.
 *
 * <p>Texture-override caveats (accepted, same as infernofauna): the ghast's shooting
 * texture swap and the slime's translucent outer layer both reuse the single recolored
 * texture.
 */
public final class BossPantheonFeatureClient {
	private BossPantheonFeatureClient() {
	}

	private static Identifier tex(String boss) {
		return CopperInferno.id("textures/entity/bosspantheon/" + boss + ".png");
	}

	public static void initClient() {
		EntityRendererFactories.register(BossPantheonFeature.THE_VERDIGRIS_PROPHET,
				VerdigrisProphetRenderer::new);
		EntityRendererFactories.register(BossPantheonFeature.PATINA_WARDEN, PatinaWardenRenderer::new);
		EntityRendererFactories.register(BossPantheonFeature.COIL_HYDRA, CoilHydraRenderer::new);
		EntityRendererFactories.register(BossPantheonFeature.THUNDER_CONDUCTOR,
				ThunderConductorRenderer::new);
		EntityRendererFactories.register(BossPantheonFeature.THE_MINT_KING, MintKingRenderer::new);
		EntityRendererFactories.register(BossPantheonFeature.GILDED_EXECUTIONER,
				GildedExecutionerRenderer::new);
	}

	/** EvokerEntityRenderer&lt;T extends SpellcastingIllagerEntity&gt; is generic (javap). */
	private static final class VerdigrisProphetRenderer extends EvokerEntityRenderer<TheVerdigrisProphetEntity> {
		private static final Identifier TEXTURE = tex("the_verdigris_prophet");

		VerdigrisProphetRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(EvokerEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class PatinaWardenRenderer extends IronGolemEntityRenderer {
		private static final Identifier TEXTURE = tex("patina_warden");

		PatinaWardenRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(IronGolemEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class CoilHydraRenderer extends GhastEntityRenderer {
		private static final Identifier TEXTURE = tex("coil_hydra");

		CoilHydraRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(GhastEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class ThunderConductorRenderer extends BlazeEntityRenderer {
		private static final Identifier TEXTURE = tex("thunder_conductor");

		ThunderConductorRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(LivingEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class MintKingRenderer extends SlimeEntityRenderer {
		private static final Identifier TEXTURE = tex("the_mint_king");

		MintKingRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(SlimeEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class GildedExecutionerRenderer extends VindicatorEntityRenderer {
		private static final Identifier TEXTURE = tex("gilded_executioner");

		GildedExecutionerRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(IllagerEntityRenderState state) {
			return TEXTURE;
		}
	}
}
