package net.sonic0810.copperinferno.feature.kilnstone;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlockFamilies.BlockFamily;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Kilnstone block set: 224 building blocks across 14 kiln/ceramic/fired-clay materials
 * (kilnstone, firebrick stone, glazed cinder, terracotta slag, kiln ceramic, emberware,
 * sootware, glazed ember, baked ash block, foundry brick, crucible stone, slagware,
 * ash ceramic, pyroceramic). Each material ships three full cube families (base,
 * polished, bricks; each base/slab/stairs/wall) plus tiles, cracked bricks, chiseled
 * bricks and a pillar.
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes,
 * EN+DE lang fragments) are generated by {@code devtools/gen/kilnstone_gen.py}; the tag
 * fragment lives at {@code devtools/tagfrag/kilnstone.json}; handbook pages are
 * registered by {@link KilnstoneHandbook}.
 */
public final class KilnstoneFeature {
	private KilnstoneFeature() {
	}

	// Full cube families (base + slab + stairs + wall).
	public static BlockFamily KILNSTONE;
	public static BlockFamily POLISHED_KILNSTONE;
	public static BlockFamily KILNSTONE_BRICKS;
	public static BlockFamily FIREBRICK_STONE;
	public static BlockFamily POLISHED_FIREBRICK_STONE;
	public static BlockFamily FIREBRICK_STONE_BRICKS;
	public static BlockFamily GLAZED_CINDER;
	public static BlockFamily POLISHED_GLAZED_CINDER;
	public static BlockFamily GLAZED_CINDER_BRICKS;
	public static BlockFamily TERRACOTTA_SLAG;
	public static BlockFamily POLISHED_TERRACOTTA_SLAG;
	public static BlockFamily TERRACOTTA_SLAG_BRICKS;
	public static BlockFamily KILN_CERAMIC;
	public static BlockFamily POLISHED_KILN_CERAMIC;
	public static BlockFamily KILN_CERAMIC_BRICKS;
	public static BlockFamily EMBERWARE;
	public static BlockFamily POLISHED_EMBERWARE;
	public static BlockFamily EMBERWARE_BRICKS;
	public static BlockFamily SOOTWARE;
	public static BlockFamily POLISHED_SOOTWARE;
	public static BlockFamily SOOTWARE_BRICKS;
	public static BlockFamily GLAZED_EMBER;
	public static BlockFamily POLISHED_GLAZED_EMBER;
	public static BlockFamily GLAZED_EMBER_BRICKS;
	public static BlockFamily BAKED_ASH_BLOCK;
	public static BlockFamily POLISHED_BAKED_ASH_BLOCK;
	public static BlockFamily BAKED_ASH_BLOCK_BRICKS;
	public static BlockFamily FOUNDRY_BRICK;
	public static BlockFamily POLISHED_FOUNDRY_BRICK;
	public static BlockFamily FOUNDRY_BRICK_BRICKS;
	public static BlockFamily CRUCIBLE_STONE;
	public static BlockFamily POLISHED_CRUCIBLE_STONE;
	public static BlockFamily CRUCIBLE_STONE_BRICKS;
	public static BlockFamily SLAGWARE;
	public static BlockFamily POLISHED_SLAGWARE;
	public static BlockFamily SLAGWARE_BRICKS;
	public static BlockFamily ASH_CERAMIC;
	public static BlockFamily POLISHED_ASH_CERAMIC;
	public static BlockFamily ASH_CERAMIC_BRICKS;
	public static BlockFamily PYROCERAMIC;
	public static BlockFamily POLISHED_PYROCERAMIC;
	public static BlockFamily PYROCERAMIC_BRICKS;

	// Single blocks.
	public static Block KILNSTONE_TILES;
	public static Block CRACKED_KILNSTONE_BRICKS;
	public static Block CHISELED_KILNSTONE_BRICKS;
	public static Block KILNSTONE_PILLAR;
	public static Block FIREBRICK_STONE_TILES;
	public static Block CRACKED_FIREBRICK_STONE_BRICKS;
	public static Block CHISELED_FIREBRICK_STONE_BRICKS;
	public static Block FIREBRICK_STONE_PILLAR;
	public static Block GLAZED_CINDER_TILES;
	public static Block CRACKED_GLAZED_CINDER_BRICKS;
	public static Block CHISELED_GLAZED_CINDER_BRICKS;
	public static Block GLAZED_CINDER_PILLAR;
	public static Block TERRACOTTA_SLAG_TILES;
	public static Block CRACKED_TERRACOTTA_SLAG_BRICKS;
	public static Block CHISELED_TERRACOTTA_SLAG_BRICKS;
	public static Block TERRACOTTA_SLAG_PILLAR;
	public static Block KILN_CERAMIC_TILES;
	public static Block CRACKED_KILN_CERAMIC_BRICKS;
	public static Block CHISELED_KILN_CERAMIC_BRICKS;
	public static Block KILN_CERAMIC_PILLAR;
	public static Block EMBERWARE_TILES;
	public static Block CRACKED_EMBERWARE_BRICKS;
	public static Block CHISELED_EMBERWARE_BRICKS;
	public static Block EMBERWARE_PILLAR;
	public static Block SOOTWARE_TILES;
	public static Block CRACKED_SOOTWARE_BRICKS;
	public static Block CHISELED_SOOTWARE_BRICKS;
	public static Block SOOTWARE_PILLAR;
	public static Block GLAZED_EMBER_TILES;
	public static Block CRACKED_GLAZED_EMBER_BRICKS;
	public static Block CHISELED_GLAZED_EMBER_BRICKS;
	public static Block GLAZED_EMBER_PILLAR;
	public static Block BAKED_ASH_BLOCK_TILES;
	public static Block CRACKED_BAKED_ASH_BLOCK_BRICKS;
	public static Block CHISELED_BAKED_ASH_BLOCK_BRICKS;
	public static Block BAKED_ASH_BLOCK_PILLAR;
	public static Block FOUNDRY_BRICK_TILES;
	public static Block CRACKED_FOUNDRY_BRICK_BRICKS;
	public static Block CHISELED_FOUNDRY_BRICK_BRICKS;
	public static Block FOUNDRY_BRICK_PILLAR;
	public static Block CRUCIBLE_STONE_TILES;
	public static Block CRACKED_CRUCIBLE_STONE_BRICKS;
	public static Block CHISELED_CRUCIBLE_STONE_BRICKS;
	public static Block CRUCIBLE_STONE_PILLAR;
	public static Block SLAGWARE_TILES;
	public static Block CRACKED_SLAGWARE_BRICKS;
	public static Block CHISELED_SLAGWARE_BRICKS;
	public static Block SLAGWARE_PILLAR;
	public static Block ASH_CERAMIC_TILES;
	public static Block CRACKED_ASH_CERAMIC_BRICKS;
	public static Block CHISELED_ASH_CERAMIC_BRICKS;
	public static Block ASH_CERAMIC_PILLAR;
	public static Block PYROCERAMIC_TILES;
	public static Block CRACKED_PYROCERAMIC_BRICKS;
	public static Block CHISELED_PYROCERAMIC_BRICKS;
	public static Block PYROCERAMIC_PILLAR;

	/**
	 * Fresh settings per block ({@link ModBlocks#register} writes a registry key into the
	 * instance, so settings must never be shared). Standard requires-tool stone profile
	 * (same numbers as the cinderstone feature), ceramic-like map colors.
	 */
	private static AbstractBlock.Settings stoneSettings(MapColor color, BlockSoundGroup sounds) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.5F, 8.0F)
				.requiresTool()
				.sounds(sounds);
	}

	private static AbstractBlock.Settings kilnstoneSettings() {
		return stoneSettings(MapColor.TERRACOTTA_ORANGE, BlockSoundGroup.MUD_BRICKS);
	}

	private static AbstractBlock.Settings firebrickStoneSettings() {
		return stoneSettings(MapColor.TERRACOTTA_RED, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings glazedCinderSettings() {
		return stoneSettings(MapColor.TERRACOTTA_GRAY, BlockSoundGroup.DEEPSLATE_TILES);
	}

	private static AbstractBlock.Settings terracottaSlagSettings() {
		return stoneSettings(MapColor.TERRACOTTA_BROWN, BlockSoundGroup.MUD_BRICKS);
	}

	private static AbstractBlock.Settings kilnCeramicSettings() {
		return stoneSettings(MapColor.TERRACOTTA_WHITE, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings emberwareSettings() {
		return stoneSettings(MapColor.ORANGE, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings sootwareSettings() {
		return stoneSettings(MapColor.TERRACOTTA_BLACK, BlockSoundGroup.TUFF_BRICKS);
	}

	private static AbstractBlock.Settings glazedEmberSettings() {
		return stoneSettings(MapColor.TERRACOTTA_YELLOW, BlockSoundGroup.RESIN_BRICKS);
	}

	private static AbstractBlock.Settings bakedAshBlockSettings() {
		return stoneSettings(MapColor.TERRACOTTA_LIGHT_GRAY, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings foundryBrickSettings() {
		return stoneSettings(MapColor.DULL_RED, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings crucibleStoneSettings() {
		return stoneSettings(MapColor.STONE_GRAY, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings slagwareSettings() {
		return stoneSettings(MapColor.TERRACOTTA_CYAN, BlockSoundGroup.POLISHED_TUFF);
	}

	private static AbstractBlock.Settings ashCeramicSettings() {
		return stoneSettings(MapColor.LIGHT_GRAY, BlockSoundGroup.CALCITE);
	}

	private static AbstractBlock.Settings pyroceramicSettings() {
		return stoneSettings(MapColor.DARK_RED, BlockSoundGroup.DRIPSTONE_BLOCK);
	}

	public static void init() {
		KILNSTONE = ModBlockFamilies.registerCubeFamily(
				"kilnstone", "kilnstone", KilnstoneFeature::kilnstoneSettings, true);
		POLISHED_KILNSTONE = ModBlockFamilies.registerCubeFamily(
				"polished_kilnstone", "polished_kilnstone", KilnstoneFeature::kilnstoneSettings, true);
		KILNSTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"kilnstone_bricks", "kilnstone_brick", KilnstoneFeature::kilnstoneSettings, true);
		FIREBRICK_STONE = ModBlockFamilies.registerCubeFamily(
				"firebrick_stone", "firebrick_stone", KilnstoneFeature::firebrickStoneSettings, true);
		POLISHED_FIREBRICK_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_firebrick_stone", "polished_firebrick_stone", KilnstoneFeature::firebrickStoneSettings, true);
		FIREBRICK_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"firebrick_stone_bricks", "firebrick_stone_brick", KilnstoneFeature::firebrickStoneSettings, true);
		GLAZED_CINDER = ModBlockFamilies.registerCubeFamily(
				"glazed_cinder", "glazed_cinder", KilnstoneFeature::glazedCinderSettings, true);
		POLISHED_GLAZED_CINDER = ModBlockFamilies.registerCubeFamily(
				"polished_glazed_cinder", "polished_glazed_cinder", KilnstoneFeature::glazedCinderSettings, true);
		GLAZED_CINDER_BRICKS = ModBlockFamilies.registerCubeFamily(
				"glazed_cinder_bricks", "glazed_cinder_brick", KilnstoneFeature::glazedCinderSettings, true);
		TERRACOTTA_SLAG = ModBlockFamilies.registerCubeFamily(
				"terracotta_slag", "terracotta_slag", KilnstoneFeature::terracottaSlagSettings, true);
		POLISHED_TERRACOTTA_SLAG = ModBlockFamilies.registerCubeFamily(
				"polished_terracotta_slag", "polished_terracotta_slag", KilnstoneFeature::terracottaSlagSettings, true);
		TERRACOTTA_SLAG_BRICKS = ModBlockFamilies.registerCubeFamily(
				"terracotta_slag_bricks", "terracotta_slag_brick", KilnstoneFeature::terracottaSlagSettings, true);
		KILN_CERAMIC = ModBlockFamilies.registerCubeFamily(
				"kiln_ceramic", "kiln_ceramic", KilnstoneFeature::kilnCeramicSettings, true);
		POLISHED_KILN_CERAMIC = ModBlockFamilies.registerCubeFamily(
				"polished_kiln_ceramic", "polished_kiln_ceramic", KilnstoneFeature::kilnCeramicSettings, true);
		KILN_CERAMIC_BRICKS = ModBlockFamilies.registerCubeFamily(
				"kiln_ceramic_bricks", "kiln_ceramic_brick", KilnstoneFeature::kilnCeramicSettings, true);
		EMBERWARE = ModBlockFamilies.registerCubeFamily(
				"emberware", "emberware", KilnstoneFeature::emberwareSettings, true);
		POLISHED_EMBERWARE = ModBlockFamilies.registerCubeFamily(
				"polished_emberware", "polished_emberware", KilnstoneFeature::emberwareSettings, true);
		EMBERWARE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"emberware_bricks", "emberware_brick", KilnstoneFeature::emberwareSettings, true);
		SOOTWARE = ModBlockFamilies.registerCubeFamily(
				"sootware", "sootware", KilnstoneFeature::sootwareSettings, true);
		POLISHED_SOOTWARE = ModBlockFamilies.registerCubeFamily(
				"polished_sootware", "polished_sootware", KilnstoneFeature::sootwareSettings, true);
		SOOTWARE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"sootware_bricks", "sootware_brick", KilnstoneFeature::sootwareSettings, true);
		GLAZED_EMBER = ModBlockFamilies.registerCubeFamily(
				"glazed_ember", "glazed_ember", KilnstoneFeature::glazedEmberSettings, true);
		POLISHED_GLAZED_EMBER = ModBlockFamilies.registerCubeFamily(
				"polished_glazed_ember", "polished_glazed_ember", KilnstoneFeature::glazedEmberSettings, true);
		GLAZED_EMBER_BRICKS = ModBlockFamilies.registerCubeFamily(
				"glazed_ember_bricks", "glazed_ember_brick", KilnstoneFeature::glazedEmberSettings, true);
		BAKED_ASH_BLOCK = ModBlockFamilies.registerCubeFamily(
				"baked_ash_block", "baked_ash_block", KilnstoneFeature::bakedAshBlockSettings, true);
		POLISHED_BAKED_ASH_BLOCK = ModBlockFamilies.registerCubeFamily(
				"polished_baked_ash_block", "polished_baked_ash_block", KilnstoneFeature::bakedAshBlockSettings, true);
		BAKED_ASH_BLOCK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"baked_ash_block_bricks", "baked_ash_block_brick", KilnstoneFeature::bakedAshBlockSettings, true);
		FOUNDRY_BRICK = ModBlockFamilies.registerCubeFamily(
				"foundry_brick", "foundry_brick", KilnstoneFeature::foundryBrickSettings, true);
		POLISHED_FOUNDRY_BRICK = ModBlockFamilies.registerCubeFamily(
				"polished_foundry_brick", "polished_foundry_brick", KilnstoneFeature::foundryBrickSettings, true);
		FOUNDRY_BRICK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"foundry_brick_bricks", "foundry_brick_brick", KilnstoneFeature::foundryBrickSettings, true);
		CRUCIBLE_STONE = ModBlockFamilies.registerCubeFamily(
				"crucible_stone", "crucible_stone", KilnstoneFeature::crucibleStoneSettings, true);
		POLISHED_CRUCIBLE_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_crucible_stone", "polished_crucible_stone", KilnstoneFeature::crucibleStoneSettings, true);
		CRUCIBLE_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"crucible_stone_bricks", "crucible_stone_brick", KilnstoneFeature::crucibleStoneSettings, true);
		SLAGWARE = ModBlockFamilies.registerCubeFamily(
				"slagware", "slagware", KilnstoneFeature::slagwareSettings, true);
		POLISHED_SLAGWARE = ModBlockFamilies.registerCubeFamily(
				"polished_slagware", "polished_slagware", KilnstoneFeature::slagwareSettings, true);
		SLAGWARE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"slagware_bricks", "slagware_brick", KilnstoneFeature::slagwareSettings, true);
		ASH_CERAMIC = ModBlockFamilies.registerCubeFamily(
				"ash_ceramic", "ash_ceramic", KilnstoneFeature::ashCeramicSettings, true);
		POLISHED_ASH_CERAMIC = ModBlockFamilies.registerCubeFamily(
				"polished_ash_ceramic", "polished_ash_ceramic", KilnstoneFeature::ashCeramicSettings, true);
		ASH_CERAMIC_BRICKS = ModBlockFamilies.registerCubeFamily(
				"ash_ceramic_bricks", "ash_ceramic_brick", KilnstoneFeature::ashCeramicSettings, true);
		PYROCERAMIC = ModBlockFamilies.registerCubeFamily(
				"pyroceramic", "pyroceramic", KilnstoneFeature::pyroceramicSettings, true);
		POLISHED_PYROCERAMIC = ModBlockFamilies.registerCubeFamily(
				"polished_pyroceramic", "polished_pyroceramic", KilnstoneFeature::pyroceramicSettings, true);
		PYROCERAMIC_BRICKS = ModBlockFamilies.registerCubeFamily(
				"pyroceramic_bricks", "pyroceramic_brick", KilnstoneFeature::pyroceramicSettings, true);

		KILNSTONE_TILES = ModBlocks.register("kilnstone_tiles", Block::new, kilnstoneSettings(), true);
		CRACKED_KILNSTONE_BRICKS = ModBlocks.register("cracked_kilnstone_bricks", Block::new, kilnstoneSettings(), true);
		CHISELED_KILNSTONE_BRICKS = ModBlocks.register("chiseled_kilnstone_bricks", Block::new, kilnstoneSettings(), true);
		KILNSTONE_PILLAR = ModBlocks.register("kilnstone_pillar", PillarBlock::new, kilnstoneSettings(), true);
		FIREBRICK_STONE_TILES = ModBlocks.register("firebrick_stone_tiles", Block::new, firebrickStoneSettings(), true);
		CRACKED_FIREBRICK_STONE_BRICKS = ModBlocks.register("cracked_firebrick_stone_bricks", Block::new, firebrickStoneSettings(), true);
		CHISELED_FIREBRICK_STONE_BRICKS = ModBlocks.register("chiseled_firebrick_stone_bricks", Block::new, firebrickStoneSettings(), true);
		FIREBRICK_STONE_PILLAR = ModBlocks.register("firebrick_stone_pillar", PillarBlock::new, firebrickStoneSettings(), true);
		GLAZED_CINDER_TILES = ModBlocks.register("glazed_cinder_tiles", Block::new, glazedCinderSettings(), true);
		CRACKED_GLAZED_CINDER_BRICKS = ModBlocks.register("cracked_glazed_cinder_bricks", Block::new, glazedCinderSettings(), true);
		CHISELED_GLAZED_CINDER_BRICKS = ModBlocks.register("chiseled_glazed_cinder_bricks", Block::new, glazedCinderSettings(), true);
		GLAZED_CINDER_PILLAR = ModBlocks.register("glazed_cinder_pillar", PillarBlock::new, glazedCinderSettings(), true);
		TERRACOTTA_SLAG_TILES = ModBlocks.register("terracotta_slag_tiles", Block::new, terracottaSlagSettings(), true);
		CRACKED_TERRACOTTA_SLAG_BRICKS = ModBlocks.register("cracked_terracotta_slag_bricks", Block::new, terracottaSlagSettings(), true);
		CHISELED_TERRACOTTA_SLAG_BRICKS = ModBlocks.register("chiseled_terracotta_slag_bricks", Block::new, terracottaSlagSettings(), true);
		TERRACOTTA_SLAG_PILLAR = ModBlocks.register("terracotta_slag_pillar", PillarBlock::new, terracottaSlagSettings(), true);
		KILN_CERAMIC_TILES = ModBlocks.register("kiln_ceramic_tiles", Block::new, kilnCeramicSettings(), true);
		CRACKED_KILN_CERAMIC_BRICKS = ModBlocks.register("cracked_kiln_ceramic_bricks", Block::new, kilnCeramicSettings(), true);
		CHISELED_KILN_CERAMIC_BRICKS = ModBlocks.register("chiseled_kiln_ceramic_bricks", Block::new, kilnCeramicSettings(), true);
		KILN_CERAMIC_PILLAR = ModBlocks.register("kiln_ceramic_pillar", PillarBlock::new, kilnCeramicSettings(), true);
		EMBERWARE_TILES = ModBlocks.register("emberware_tiles", Block::new, emberwareSettings(), true);
		CRACKED_EMBERWARE_BRICKS = ModBlocks.register("cracked_emberware_bricks", Block::new, emberwareSettings(), true);
		CHISELED_EMBERWARE_BRICKS = ModBlocks.register("chiseled_emberware_bricks", Block::new, emberwareSettings(), true);
		EMBERWARE_PILLAR = ModBlocks.register("emberware_pillar", PillarBlock::new, emberwareSettings(), true);
		SOOTWARE_TILES = ModBlocks.register("sootware_tiles", Block::new, sootwareSettings(), true);
		CRACKED_SOOTWARE_BRICKS = ModBlocks.register("cracked_sootware_bricks", Block::new, sootwareSettings(), true);
		CHISELED_SOOTWARE_BRICKS = ModBlocks.register("chiseled_sootware_bricks", Block::new, sootwareSettings(), true);
		SOOTWARE_PILLAR = ModBlocks.register("sootware_pillar", PillarBlock::new, sootwareSettings(), true);
		GLAZED_EMBER_TILES = ModBlocks.register("glazed_ember_tiles", Block::new, glazedEmberSettings(), true);
		CRACKED_GLAZED_EMBER_BRICKS = ModBlocks.register("cracked_glazed_ember_bricks", Block::new, glazedEmberSettings(), true);
		CHISELED_GLAZED_EMBER_BRICKS = ModBlocks.register("chiseled_glazed_ember_bricks", Block::new, glazedEmberSettings(), true);
		GLAZED_EMBER_PILLAR = ModBlocks.register("glazed_ember_pillar", PillarBlock::new, glazedEmberSettings(), true);
		BAKED_ASH_BLOCK_TILES = ModBlocks.register("baked_ash_block_tiles", Block::new, bakedAshBlockSettings(), true);
		CRACKED_BAKED_ASH_BLOCK_BRICKS = ModBlocks.register("cracked_baked_ash_block_bricks", Block::new, bakedAshBlockSettings(), true);
		CHISELED_BAKED_ASH_BLOCK_BRICKS = ModBlocks.register("chiseled_baked_ash_block_bricks", Block::new, bakedAshBlockSettings(), true);
		BAKED_ASH_BLOCK_PILLAR = ModBlocks.register("baked_ash_block_pillar", PillarBlock::new, bakedAshBlockSettings(), true);
		FOUNDRY_BRICK_TILES = ModBlocks.register("foundry_brick_tiles", Block::new, foundryBrickSettings(), true);
		CRACKED_FOUNDRY_BRICK_BRICKS = ModBlocks.register("cracked_foundry_brick_bricks", Block::new, foundryBrickSettings(), true);
		CHISELED_FOUNDRY_BRICK_BRICKS = ModBlocks.register("chiseled_foundry_brick_bricks", Block::new, foundryBrickSettings(), true);
		FOUNDRY_BRICK_PILLAR = ModBlocks.register("foundry_brick_pillar", PillarBlock::new, foundryBrickSettings(), true);
		CRUCIBLE_STONE_TILES = ModBlocks.register("crucible_stone_tiles", Block::new, crucibleStoneSettings(), true);
		CRACKED_CRUCIBLE_STONE_BRICKS = ModBlocks.register("cracked_crucible_stone_bricks", Block::new, crucibleStoneSettings(), true);
		CHISELED_CRUCIBLE_STONE_BRICKS = ModBlocks.register("chiseled_crucible_stone_bricks", Block::new, crucibleStoneSettings(), true);
		CRUCIBLE_STONE_PILLAR = ModBlocks.register("crucible_stone_pillar", PillarBlock::new, crucibleStoneSettings(), true);
		SLAGWARE_TILES = ModBlocks.register("slagware_tiles", Block::new, slagwareSettings(), true);
		CRACKED_SLAGWARE_BRICKS = ModBlocks.register("cracked_slagware_bricks", Block::new, slagwareSettings(), true);
		CHISELED_SLAGWARE_BRICKS = ModBlocks.register("chiseled_slagware_bricks", Block::new, slagwareSettings(), true);
		SLAGWARE_PILLAR = ModBlocks.register("slagware_pillar", PillarBlock::new, slagwareSettings(), true);
		ASH_CERAMIC_TILES = ModBlocks.register("ash_ceramic_tiles", Block::new, ashCeramicSettings(), true);
		CRACKED_ASH_CERAMIC_BRICKS = ModBlocks.register("cracked_ash_ceramic_bricks", Block::new, ashCeramicSettings(), true);
		CHISELED_ASH_CERAMIC_BRICKS = ModBlocks.register("chiseled_ash_ceramic_bricks", Block::new, ashCeramicSettings(), true);
		ASH_CERAMIC_PILLAR = ModBlocks.register("ash_ceramic_pillar", PillarBlock::new, ashCeramicSettings(), true);
		PYROCERAMIC_TILES = ModBlocks.register("pyroceramic_tiles", Block::new, pyroceramicSettings(), true);
		CRACKED_PYROCERAMIC_BRICKS = ModBlocks.register("cracked_pyroceramic_bricks", Block::new, pyroceramicSettings(), true);
		CHISELED_PYROCERAMIC_BRICKS = ModBlocks.register("chiseled_pyroceramic_bricks", Block::new, pyroceramicSettings(), true);
		PYROCERAMIC_PILLAR = ModBlocks.register("pyroceramic_pillar", PillarBlock::new, pyroceramicSettings(), true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.SETS_KEY).register(entries -> {
			entries.add(KILNSTONE.block());
			entries.add(KILNSTONE.stairs());
			entries.add(KILNSTONE.slab());
			entries.add(KILNSTONE.wall());
			entries.add(POLISHED_KILNSTONE.block());
			entries.add(POLISHED_KILNSTONE.stairs());
			entries.add(POLISHED_KILNSTONE.slab());
			entries.add(POLISHED_KILNSTONE.wall());
			entries.add(KILNSTONE_BRICKS.block());
			entries.add(KILNSTONE_BRICKS.stairs());
			entries.add(KILNSTONE_BRICKS.slab());
			entries.add(KILNSTONE_BRICKS.wall());
			entries.add(KILNSTONE_TILES);
			entries.add(CRACKED_KILNSTONE_BRICKS);
			entries.add(CHISELED_KILNSTONE_BRICKS);
			entries.add(KILNSTONE_PILLAR);
			entries.add(FIREBRICK_STONE.block());
			entries.add(FIREBRICK_STONE.stairs());
			entries.add(FIREBRICK_STONE.slab());
			entries.add(FIREBRICK_STONE.wall());
			entries.add(POLISHED_FIREBRICK_STONE.block());
			entries.add(POLISHED_FIREBRICK_STONE.stairs());
			entries.add(POLISHED_FIREBRICK_STONE.slab());
			entries.add(POLISHED_FIREBRICK_STONE.wall());
			entries.add(FIREBRICK_STONE_BRICKS.block());
			entries.add(FIREBRICK_STONE_BRICKS.stairs());
			entries.add(FIREBRICK_STONE_BRICKS.slab());
			entries.add(FIREBRICK_STONE_BRICKS.wall());
			entries.add(FIREBRICK_STONE_TILES);
			entries.add(CRACKED_FIREBRICK_STONE_BRICKS);
			entries.add(CHISELED_FIREBRICK_STONE_BRICKS);
			entries.add(FIREBRICK_STONE_PILLAR);
			entries.add(GLAZED_CINDER.block());
			entries.add(GLAZED_CINDER.stairs());
			entries.add(GLAZED_CINDER.slab());
			entries.add(GLAZED_CINDER.wall());
			entries.add(POLISHED_GLAZED_CINDER.block());
			entries.add(POLISHED_GLAZED_CINDER.stairs());
			entries.add(POLISHED_GLAZED_CINDER.slab());
			entries.add(POLISHED_GLAZED_CINDER.wall());
			entries.add(GLAZED_CINDER_BRICKS.block());
			entries.add(GLAZED_CINDER_BRICKS.stairs());
			entries.add(GLAZED_CINDER_BRICKS.slab());
			entries.add(GLAZED_CINDER_BRICKS.wall());
			entries.add(GLAZED_CINDER_TILES);
			entries.add(CRACKED_GLAZED_CINDER_BRICKS);
			entries.add(CHISELED_GLAZED_CINDER_BRICKS);
			entries.add(GLAZED_CINDER_PILLAR);
			entries.add(TERRACOTTA_SLAG.block());
			entries.add(TERRACOTTA_SLAG.stairs());
			entries.add(TERRACOTTA_SLAG.slab());
			entries.add(TERRACOTTA_SLAG.wall());
			entries.add(POLISHED_TERRACOTTA_SLAG.block());
			entries.add(POLISHED_TERRACOTTA_SLAG.stairs());
			entries.add(POLISHED_TERRACOTTA_SLAG.slab());
			entries.add(POLISHED_TERRACOTTA_SLAG.wall());
			entries.add(TERRACOTTA_SLAG_BRICKS.block());
			entries.add(TERRACOTTA_SLAG_BRICKS.stairs());
			entries.add(TERRACOTTA_SLAG_BRICKS.slab());
			entries.add(TERRACOTTA_SLAG_BRICKS.wall());
			entries.add(TERRACOTTA_SLAG_TILES);
			entries.add(CRACKED_TERRACOTTA_SLAG_BRICKS);
			entries.add(CHISELED_TERRACOTTA_SLAG_BRICKS);
			entries.add(TERRACOTTA_SLAG_PILLAR);
			entries.add(KILN_CERAMIC.block());
			entries.add(KILN_CERAMIC.stairs());
			entries.add(KILN_CERAMIC.slab());
			entries.add(KILN_CERAMIC.wall());
			entries.add(POLISHED_KILN_CERAMIC.block());
			entries.add(POLISHED_KILN_CERAMIC.stairs());
			entries.add(POLISHED_KILN_CERAMIC.slab());
			entries.add(POLISHED_KILN_CERAMIC.wall());
			entries.add(KILN_CERAMIC_BRICKS.block());
			entries.add(KILN_CERAMIC_BRICKS.stairs());
			entries.add(KILN_CERAMIC_BRICKS.slab());
			entries.add(KILN_CERAMIC_BRICKS.wall());
			entries.add(KILN_CERAMIC_TILES);
			entries.add(CRACKED_KILN_CERAMIC_BRICKS);
			entries.add(CHISELED_KILN_CERAMIC_BRICKS);
			entries.add(KILN_CERAMIC_PILLAR);
			entries.add(EMBERWARE.block());
			entries.add(EMBERWARE.stairs());
			entries.add(EMBERWARE.slab());
			entries.add(EMBERWARE.wall());
			entries.add(POLISHED_EMBERWARE.block());
			entries.add(POLISHED_EMBERWARE.stairs());
			entries.add(POLISHED_EMBERWARE.slab());
			entries.add(POLISHED_EMBERWARE.wall());
			entries.add(EMBERWARE_BRICKS.block());
			entries.add(EMBERWARE_BRICKS.stairs());
			entries.add(EMBERWARE_BRICKS.slab());
			entries.add(EMBERWARE_BRICKS.wall());
			entries.add(EMBERWARE_TILES);
			entries.add(CRACKED_EMBERWARE_BRICKS);
			entries.add(CHISELED_EMBERWARE_BRICKS);
			entries.add(EMBERWARE_PILLAR);
			entries.add(SOOTWARE.block());
			entries.add(SOOTWARE.stairs());
			entries.add(SOOTWARE.slab());
			entries.add(SOOTWARE.wall());
			entries.add(POLISHED_SOOTWARE.block());
			entries.add(POLISHED_SOOTWARE.stairs());
			entries.add(POLISHED_SOOTWARE.slab());
			entries.add(POLISHED_SOOTWARE.wall());
			entries.add(SOOTWARE_BRICKS.block());
			entries.add(SOOTWARE_BRICKS.stairs());
			entries.add(SOOTWARE_BRICKS.slab());
			entries.add(SOOTWARE_BRICKS.wall());
			entries.add(SOOTWARE_TILES);
			entries.add(CRACKED_SOOTWARE_BRICKS);
			entries.add(CHISELED_SOOTWARE_BRICKS);
			entries.add(SOOTWARE_PILLAR);
			entries.add(GLAZED_EMBER.block());
			entries.add(GLAZED_EMBER.stairs());
			entries.add(GLAZED_EMBER.slab());
			entries.add(GLAZED_EMBER.wall());
			entries.add(POLISHED_GLAZED_EMBER.block());
			entries.add(POLISHED_GLAZED_EMBER.stairs());
			entries.add(POLISHED_GLAZED_EMBER.slab());
			entries.add(POLISHED_GLAZED_EMBER.wall());
			entries.add(GLAZED_EMBER_BRICKS.block());
			entries.add(GLAZED_EMBER_BRICKS.stairs());
			entries.add(GLAZED_EMBER_BRICKS.slab());
			entries.add(GLAZED_EMBER_BRICKS.wall());
			entries.add(GLAZED_EMBER_TILES);
			entries.add(CRACKED_GLAZED_EMBER_BRICKS);
			entries.add(CHISELED_GLAZED_EMBER_BRICKS);
			entries.add(GLAZED_EMBER_PILLAR);
			entries.add(BAKED_ASH_BLOCK.block());
			entries.add(BAKED_ASH_BLOCK.stairs());
			entries.add(BAKED_ASH_BLOCK.slab());
			entries.add(BAKED_ASH_BLOCK.wall());
			entries.add(POLISHED_BAKED_ASH_BLOCK.block());
			entries.add(POLISHED_BAKED_ASH_BLOCK.stairs());
			entries.add(POLISHED_BAKED_ASH_BLOCK.slab());
			entries.add(POLISHED_BAKED_ASH_BLOCK.wall());
			entries.add(BAKED_ASH_BLOCK_BRICKS.block());
			entries.add(BAKED_ASH_BLOCK_BRICKS.stairs());
			entries.add(BAKED_ASH_BLOCK_BRICKS.slab());
			entries.add(BAKED_ASH_BLOCK_BRICKS.wall());
			entries.add(BAKED_ASH_BLOCK_TILES);
			entries.add(CRACKED_BAKED_ASH_BLOCK_BRICKS);
			entries.add(CHISELED_BAKED_ASH_BLOCK_BRICKS);
			entries.add(BAKED_ASH_BLOCK_PILLAR);
			entries.add(FOUNDRY_BRICK.block());
			entries.add(FOUNDRY_BRICK.stairs());
			entries.add(FOUNDRY_BRICK.slab());
			entries.add(FOUNDRY_BRICK.wall());
			entries.add(POLISHED_FOUNDRY_BRICK.block());
			entries.add(POLISHED_FOUNDRY_BRICK.stairs());
			entries.add(POLISHED_FOUNDRY_BRICK.slab());
			entries.add(POLISHED_FOUNDRY_BRICK.wall());
			entries.add(FOUNDRY_BRICK_BRICKS.block());
			entries.add(FOUNDRY_BRICK_BRICKS.stairs());
			entries.add(FOUNDRY_BRICK_BRICKS.slab());
			entries.add(FOUNDRY_BRICK_BRICKS.wall());
			entries.add(FOUNDRY_BRICK_TILES);
			entries.add(CRACKED_FOUNDRY_BRICK_BRICKS);
			entries.add(CHISELED_FOUNDRY_BRICK_BRICKS);
			entries.add(FOUNDRY_BRICK_PILLAR);
			entries.add(CRUCIBLE_STONE.block());
			entries.add(CRUCIBLE_STONE.stairs());
			entries.add(CRUCIBLE_STONE.slab());
			entries.add(CRUCIBLE_STONE.wall());
			entries.add(POLISHED_CRUCIBLE_STONE.block());
			entries.add(POLISHED_CRUCIBLE_STONE.stairs());
			entries.add(POLISHED_CRUCIBLE_STONE.slab());
			entries.add(POLISHED_CRUCIBLE_STONE.wall());
			entries.add(CRUCIBLE_STONE_BRICKS.block());
			entries.add(CRUCIBLE_STONE_BRICKS.stairs());
			entries.add(CRUCIBLE_STONE_BRICKS.slab());
			entries.add(CRUCIBLE_STONE_BRICKS.wall());
			entries.add(CRUCIBLE_STONE_TILES);
			entries.add(CRACKED_CRUCIBLE_STONE_BRICKS);
			entries.add(CHISELED_CRUCIBLE_STONE_BRICKS);
			entries.add(CRUCIBLE_STONE_PILLAR);
			entries.add(SLAGWARE.block());
			entries.add(SLAGWARE.stairs());
			entries.add(SLAGWARE.slab());
			entries.add(SLAGWARE.wall());
			entries.add(POLISHED_SLAGWARE.block());
			entries.add(POLISHED_SLAGWARE.stairs());
			entries.add(POLISHED_SLAGWARE.slab());
			entries.add(POLISHED_SLAGWARE.wall());
			entries.add(SLAGWARE_BRICKS.block());
			entries.add(SLAGWARE_BRICKS.stairs());
			entries.add(SLAGWARE_BRICKS.slab());
			entries.add(SLAGWARE_BRICKS.wall());
			entries.add(SLAGWARE_TILES);
			entries.add(CRACKED_SLAGWARE_BRICKS);
			entries.add(CHISELED_SLAGWARE_BRICKS);
			entries.add(SLAGWARE_PILLAR);
			entries.add(ASH_CERAMIC.block());
			entries.add(ASH_CERAMIC.stairs());
			entries.add(ASH_CERAMIC.slab());
			entries.add(ASH_CERAMIC.wall());
			entries.add(POLISHED_ASH_CERAMIC.block());
			entries.add(POLISHED_ASH_CERAMIC.stairs());
			entries.add(POLISHED_ASH_CERAMIC.slab());
			entries.add(POLISHED_ASH_CERAMIC.wall());
			entries.add(ASH_CERAMIC_BRICKS.block());
			entries.add(ASH_CERAMIC_BRICKS.stairs());
			entries.add(ASH_CERAMIC_BRICKS.slab());
			entries.add(ASH_CERAMIC_BRICKS.wall());
			entries.add(ASH_CERAMIC_TILES);
			entries.add(CRACKED_ASH_CERAMIC_BRICKS);
			entries.add(CHISELED_ASH_CERAMIC_BRICKS);
			entries.add(ASH_CERAMIC_PILLAR);
			entries.add(PYROCERAMIC.block());
			entries.add(PYROCERAMIC.stairs());
			entries.add(PYROCERAMIC.slab());
			entries.add(PYROCERAMIC.wall());
			entries.add(POLISHED_PYROCERAMIC.block());
			entries.add(POLISHED_PYROCERAMIC.stairs());
			entries.add(POLISHED_PYROCERAMIC.slab());
			entries.add(POLISHED_PYROCERAMIC.wall());
			entries.add(PYROCERAMIC_BRICKS.block());
			entries.add(PYROCERAMIC_BRICKS.stairs());
			entries.add(PYROCERAMIC_BRICKS.slab());
			entries.add(PYROCERAMIC_BRICKS.wall());
			entries.add(PYROCERAMIC_TILES);
			entries.add(CRACKED_PYROCERAMIC_BRICKS);
			entries.add(CHISELED_PYROCERAMIC_BRICKS);
			entries.add(PYROCERAMIC_PILLAR);
		});

		KilnstoneHandbook.register();
	}
}
