package net.sonic0810.copperinferno.feature.cuisine;

import java.util.ArrayList;
import java.util.List;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.component.type.ConsumableComponent;
import net.minecraft.component.type.ConsumableComponents;
import net.minecraft.component.type.FoodComponent;
import net.minecraft.entity.attribute.EntityAttributeModifier;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.effect.StatusEffect;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.item.consume.ApplyEffectsConsumeEffect;
import net.minecraft.registry.entry.RegistryEntry;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEffects;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Inferno Cuisine &amp; Brews" (WP7): 70 standalone consumables — 10 kitchen
 * ingredients (led by the Cuisine Spice, the unique-to-this-feature recipe input), 40 foods
 * and 20 bottled fizz brews — plus 3 new status effects (Sugar Rush, Ember Belly,
 * Cinder Skin).
 *
 * <p>Follows the verified 1.21.9 consumable pattern from {@code feature/foods/FoodsFeature}
 * / {@code feature/drpepper/DrPepperFeature}: {@link FoodComponent.Builder} for
 * hunger/saturation, {@link ConsumableComponents#food()} / {@link ConsumableComponents#drink()}
 * builders carrying an {@link ApplyEffectsConsumeEffect}, and
 * {@code Item.Settings.useRemainder(...)} for container-returning foods (bowls hand back the
 * bowl, fizz brews hand back the glass bottle). Effects register through
 * {@code core.ModEffects.register} exactly like {@code feature/infernofx}; the attribute
 * payloads chain {@code StatusEffect.addAttributeModifier} (signature verified via javap).
 *
 * <p>Assets (items/*.json + models/item/*.json + 16x16 textures), recipes
 * ({@code data/copper_inferno/recipe/cuisine/}) and the lang fragments
 * ({@code lang/fragments/cuisine.json} + {@code lang/fragments_de/cuisine.json})
 * are generated by {@code devtools/gen/cuisine_gen.py}.
 */
public final class CuisineFeature {
	private CuisineFeature() {
	}

	// ---- status effects ----
	public static RegistryEntry<StatusEffect> SUGAR_RUSH;
	public static RegistryEntry<StatusEffect> EMBER_BELLY;
	public static RegistryEntry<StatusEffect> CINDER_SKIN;

	/** Creative-tab entries in registration order (ingredients, foods, drinks). */
	private static final List<Item> TAB_ORDER = new ArrayList<>();

	public static void init() {
		// ---- effects (registered before any consumable references them) ----
		SUGAR_RUSH = ModEffects.register("sugar_rush", new SugarRushEffect()
				.addAttributeModifier(EntityAttributes.MOVEMENT_SPEED,
						CopperInferno.id("effect.sugar_rush_speed"), 0.20,
						EntityAttributeModifier.Operation.ADD_MULTIPLIED_TOTAL)
				.addAttributeModifier(EntityAttributes.BLOCK_BREAK_SPEED,
						CopperInferno.id("effect.sugar_rush_haste"), 0.25,
						EntityAttributeModifier.Operation.ADD_MULTIPLIED_TOTAL));
		EMBER_BELLY = ModEffects.register("ember_belly", new EmberBellyEffect());
		CINDER_SKIN = ModEffects.register("cinder_skin", new CinderSkinEffect()
				.addAttributeModifier(EntityAttributes.ARMOR,
						CopperInferno.id("effect.cinder_skin_armor"), 4.0,
						EntityAttributeModifier.Operation.ADD_VALUE));

		// ---- ingredients (10; cuisine_spice is the unique recipe input of this feature) ----
		regIngredient("cuisine_spice");
		regIngredient("ember_flour");
		regIngredient("soda_sugar");
		regIngredient("cinder_salt");
		regIngredient("magma_butter");
		regIngredient("ash_yeast");
		regIngredient("fizz_crystal");
		regIngredient("ember_oil");
		regIngredient("smoke_extract");
		regIngredient("cinder_cocoa");

		// ---- foods (40) ----
		regFood("ash_pastry", 4, 0.4f);
		regFood("ember_jerky", 5, 0.7f);
		// Golden-apple-like candied gem: always edible, absorption on eating.
		TAB_ORDER.add(ModItems.register("candied_pyrium", Item::new, new Item.Settings()
				.rarity(Rarity.UNCOMMON)
				.food(alwaysEdibleFood(4, 1.0f), effectFood(
						new StatusEffectInstance(StatusEffects.ABSORPTION, 600, 0))))); // Absorption I 30s
		regBowlFood("magma_stew", 8, 0.7f);
		regFood("soda_glazed_ham", 9, 0.9f);
		regFood("cinder_toast", 5, 0.6f);
		regFood("fizz_tart", 4, 0.4f);
		regFood("ember_dumpling", 4, 0.5f);
		regFood("charred_skewer", 6, 0.7f);
		regFood("soda_bread", 5, 0.6f);
		regFood("magma_cake_slice", 3, 0.3f);
		regFood("pepper_pretzel", 3, 0.4f);
		regFood("smoke_sausage", 5, 0.7f);
		regBowlFood("ember_noodles", 7, 0.7f);
		regCandy("cinder_cookie", 2, 0.1f);
		regFood("fizz_pudding", 4, 0.4f);
		regFood("soda_waffle", 5, 0.5f);
		regFood("ember_pie_slice", 4, 0.4f);
		regFood("ash_biscuit", 3, 0.4f);
		// Bowl food with a fiery kick: Fire Resistance for 30s.
		TAB_ORDER.add(ModItems.register("magma_chili", Item::new, new Item.Settings()
				.maxCount(1)
				.useRemainder(Items.BOWL)
				.food(food(8, 0.8f), effectFood(
						new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 600, 0))))); // Fire Res 30s
		regFood("cinder_wrap", 6, 0.6f);
		regCandy("soda_donut", 3, 0.3f);
		regFood("ember_omelette", 5, 0.6f);
		regFood("charred_corn", 4, 0.5f);
		// Nibble-any-time candy with a short speed burst.
		TAB_ORDER.add(ModItems.register("fizz_candy_cane", Item::new, new Item.Settings()
				.food(alwaysEdibleFood(2, 0.2f), effectFood(
						new StatusEffectInstance(StatusEffects.SPEED, 200, 0))))); // Speed I 10s
		regFood("smoke_cheese", 4, 0.5f);
		regFood("ember_taco", 6, 0.6f);
		regCandy("cinder_brownie", 3, 0.3f);
		regFood("soda_pancakes", 5, 0.5f);
		regFood("magma_meatballs", 6, 0.7f);
		regFood("ash_cracker", 2, 0.2f);
		regFood("ember_croissant", 4, 0.5f);
		regCandy("fizz_gelato", 3, 0.3f);
		regFood("charred_potato", 5, 0.6f);
		regFood("soda_muffin", 3, 0.4f);
		regFood("ember_burger", 9, 0.8f);
		regFood("cinder_pizza_slice", 5, 0.6f);
		regFood("smoke_ribs", 8, 0.8f);
		regCandy("fizz_marshmallow", 2, 0.2f);
		regBowlFood("ember_chowder", 7, 0.7f);

		// ---- fizz brews (20 bottled drinks, themed effect(s), glass bottle back) ----
		regFizz("sugar_rush_fizz",
				new StatusEffectInstance(SUGAR_RUSH, 1200, 0)); // Sugar Rush 60s
		regFizz("ember_belly_fizz",
				new StatusEffectInstance(EMBER_BELLY, 1200, 0)); // Ember Belly 60s
		regFizz("cinder_skin_fizz",
				new StatusEffectInstance(CINDER_SKIN, 1200, 0)); // Cinder Skin 60s
		regFizz("ember_fizz",
				new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 600, 0)); // Fire Res 30s
		regFizz("cinder_fizz",
				new StatusEffectInstance(StatusEffects.RESISTANCE, 400, 0)); // Resistance I 20s
		regFizz("ash_fizz",
				new StatusEffectInstance(StatusEffects.NIGHT_VISION, 600, 0)); // Night Vision 30s
		regFizz("magma_fizz",
				new StatusEffectInstance(StatusEffects.STRENGTH, 400, 0)); // Strength I 20s
		regFizz("soda_fizz",
				new StatusEffectInstance(StatusEffects.SPEED, 600, 0)); // Speed I 30s
		regFizz("smoke_fizz",
				new StatusEffectInstance(StatusEffects.INVISIBILITY, 400, 0)); // Invisibility 20s
		regFizz("spice_fizz",
				new StatusEffectInstance(StatusEffects.HASTE, 600, 0)); // Haste I 30s
		regFizz("leaping_fizz",
				new StatusEffectInstance(StatusEffects.JUMP_BOOST, 600, 0)); // Jump Boost I 30s
		regFizz("mending_fizz",
				new StatusEffectInstance(StatusEffects.REGENERATION, 200, 0)); // Regeneration I 10s
		regFizz("hearty_fizz",
				new StatusEffectInstance(StatusEffects.ABSORPTION, 600, 0)); // Absorption I 30s
		regFizz("lucky_fizz",
				new StatusEffectInstance(StatusEffects.LUCK, 1200, 0)); // Luck 60s
		regFizz("tidal_fizz",
				new StatusEffectInstance(StatusEffects.WATER_BREATHING, 1200, 0)); // Water Breathing 60s
		regFizz("feather_fizz",
				new StatusEffectInstance(StatusEffects.SLOW_FALLING, 600, 0)); // Slow Falling 30s
		regFizz("dolphin_fizz",
				new StatusEffectInstance(StatusEffects.DOLPHINS_GRACE, 600, 0)); // Dolphin's Grace 30s
		regFizz("iced_ember_tea",
				new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 400, 0),
				new StatusEffectInstance(StatusEffects.SPEED, 400, 0)); // Fire Res + Speed 20s
		regFizz("molten_mocha",
				new StatusEffectInstance(StatusEffects.STRENGTH, 400, 0),
				new StatusEffectInstance(StatusEffects.HASTE, 400, 0)); // Strength + Haste 20s
		regFizz("cindercream_shake",
				new StatusEffectInstance(StatusEffects.ABSORPTION, 600, 0),
				new StatusEffectInstance(StatusEffects.REGENERATION, 100, 0)); // Absorption 30s + Regen 5s

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			for (Item item : TAB_ORDER) {
				entries.add(item);
			}
		});

		registerHandbookEntries();
	}

	// ------------------------------------------------------------------
	// Registration helpers (fresh Item.Settings per call; ids stay literal at
	// every call site so devtools/audit_assets.py can resolve them).
	// ------------------------------------------------------------------

	/** Plain crafting ingredient (no food component). */
	private static Item regIngredient(String path) {
		Item item = ModItems.register(path, Item::new, new Item.Settings());
		TAB_ORDER.add(item);
		return item;
	}

	/** Standard food (edible when hungry). */
	private static Item regFood(String path, int nutrition, float saturation) {
		Item item = ModItems.register(path, Item::new, new Item.Settings()
				.food(food(nutrition, saturation)));
		TAB_ORDER.add(item);
		return item;
	}

	/** Snack/candy: nibble any time (alwaysEdible). */
	private static Item regCandy(String path, int nutrition, float saturation) {
		Item item = ModItems.register(path, Item::new, new Item.Settings()
				.food(alwaysEdibleFood(nutrition, saturation)));
		TAB_ORDER.add(item);
		return item;
	}

	/** Bowl food (vanilla mushroom-stew pattern: single stack, bowl handed back). */
	private static Item regBowlFood(String path, int nutrition, float saturation) {
		Item item = ModItems.register(path, Item::new, new Item.Settings()
				.maxCount(1)
				.useRemainder(Items.BOWL)
				.food(food(nutrition, saturation)));
		TAB_ORDER.add(item);
		return item;
	}

	/**
	 * Bottled fizz brew: stack of 16, always drinkable, themed effect(s), returns the glass
	 * bottle when finished (the verified drpepper/foods drink pattern).
	 */
	private static Item regFizz(String path, StatusEffectInstance... effects) {
		Item item = ModItems.register(path, Item::new, new Item.Settings()
				.maxCount(16)
				.useRemainder(Items.GLASS_BOTTLE)
				.food(
						alwaysEdibleFood(2, 0.3f),
						ConsumableComponents.drink()
								.consumeEffect(new ApplyEffectsConsumeEffect(List.of(effects)))
								.build()));
		TAB_ORDER.add(item);
		return item;
	}

	private static FoodComponent food(int nutrition, float saturation) {
		return new FoodComponent.Builder().nutrition(nutrition).saturationModifier(saturation).build();
	}

	private static FoodComponent alwaysEdibleFood(int nutrition, float saturation) {
		return new FoodComponent.Builder().nutrition(nutrition).saturationModifier(saturation).alwaysEdible().build();
	}

	/** Standard eat consumable (vanilla golden-apple pattern) carrying the given effects. */
	private static ConsumableComponent effectFood(StatusEffectInstance... effects) {
		return ConsumableComponents.food()
				.consumeEffect(new ApplyEffectsConsumeEffect(List.of(effects)))
				.build();
	}

	// ------------------------------------------------------------------
	// Handbook (10 curated entries, category "items")
	// ------------------------------------------------------------------

	private static void registerHandbookEntries() {
		final String SPI = "copper_inferno:cuisine_spice";
		final String FLR = "copper_inferno:ember_flour";
		final String SSU = "copper_inferno:soda_sugar";
		final String SLT = "copper_inferno:cinder_salt";
		final String BUT = "copper_inferno:magma_butter";
		final String FIZ = "copper_inferno:fizz_crystal";
		final String OIL = "copper_inferno:ember_oil";
		final String DUS = "copper_inferno:ember_dust";
		final String NUG = "copper_inferno:pyrium_nugget";

		HandbookEntries.add(new HandbookEntry("items", "cuisine_overview",
				SPI, null, null, null, 0,
				"The Inferno kitchen runs on Cuisine Spice: blaze powder, sugar and ember dust ground into the pantry staple behind 10 ingredients, 40 dishes and 20 fizz brews. Cook stews and chowders (bowls come back), bake with Ember Flour and Magma Butter, candy a Pyrium Nugget - and bottle Fizz Crystals into brews that grant everything from Luck to the new Sugar Rush, Ember Belly and Cinder Skin effects.",
				"Die Inferno-K\u00fcche l\u00e4uft auf Gew\u00fcrzmischung: Lohenstaub, Zucker und Glutstaub gemahlen zur Vorratsbasis hinter 10 Zutaten, 40 Gerichten und 20 Brausetr\u00e4nken. Koche Eint\u00f6pfe und Suppen (die Sch\u00fcssel kommt zur\u00fcck), backe mit Glutmehl und Magmabutter, kandiere einen Pyrium-Klumpen - und f\u00fclle Brausekristalle in Tr\u00e4nke ab, die von Gl\u00fcck bis zu den neuen Effekten Zuckerrausch, Glutbauch und Zinderhaut alles verleihen."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_spice",
				SPI, "cuisine/cuisine_spice",
				new String[]{"minecraft:blaze_powder", "minecraft:sugar", DUS, "", "", "", "", "", ""}, SPI, 4,
				"Blaze powder, sugar and Ember Dust grind into four Cuisine Spice - the unique ingredient every Inferno Cuisine recipe builds on.",
				"Lohenstaub, Zucker und Glutstaub ergeben vier Gew\u00fcrzmischung - die einzigartige Zutat, auf der jedes Inferno-K\u00fcchenrezept aufbaut."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_ash_pastry",
				"copper_inferno:ash_pastry", "cuisine/ash_pastry",
				new String[]{FLR, BUT, SSU, "", "", "", "", "", ""}, "copper_inferno:ash_pastry", 2,
				"Ember Flour, Magma Butter and Soda Sugar fold into two flaky Ash Pastries.",
				"Glutmehl, Magmabutter und Brausezucker ergeben zwei bl\u00e4ttrige Aschegeb\u00e4cke."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_magma_stew",
				"copper_inferno:magma_stew", "cuisine/magma_stew",
				new String[]{"minecraft:bowl", OIL, "minecraft:baked_potato", SPI, "", "", "", "", ""},
				"copper_inferno:magma_stew", 1,
				"Ember Oil, a baked potato and Cuisine Spice simmered in a bowl: Magma Stew, 8 hunger. The bowl is returned when eaten.",
				"Glut\u00f6l, eine Ofenkartoffel und Gew\u00fcrzmischung in einer Sch\u00fcssel gek\u00f6chelt: Magmaeintopf, 8 Hunger. Die Sch\u00fcssel gibt es beim Essen zur\u00fcck."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_soda_glazed_ham",
				"copper_inferno:soda_glazed_ham", "cuisine/soda_glazed_ham",
				new String[]{"minecraft:cooked_porkchop", SSU, OIL, "", "", "", "", "", ""},
				"copper_inferno:soda_glazed_ham", 1,
				"Cooked porkchop lacquered with Soda Sugar and Ember Oil: the 9-hunger Soda-Glazed Ham, the feast dish of the Inferno kitchen.",
				"Gebratenes Schweinefleisch mit Brausezucker und Glut\u00f6l glasiert: der Brause-Glasurschinken mit 9 Hunger, das Festessen der Inferno-K\u00fcche."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_candied_pyrium",
				"copper_inferno:candied_pyrium", "cuisine/candied_pyrium",
				new String[]{NUG, SSU, SSU, "", "", "", "", "", ""}, "copper_inferno:candied_pyrium", 1,
				"A Pyrium Nugget rolled in double Soda Sugar becomes Candied Pyrium: edible any time and wrapping you in 30s of Absorption.",
				"Ein Pyrium-Klumpen in doppeltem Brausezucker gerollt wird zu Kandiertem Pyrium: jederzeit essbar und mit 30s Absorption."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_cinder_toast",
				"copper_inferno:cinder_toast", "cuisine/cinder_toast",
				new String[]{"", "", "", "", "copper_inferno:soda_bread", "", "", "", ""},
				"copper_inferno:cinder_toast", 1,
				"Soda Bread toasted in a furnace (or twice as fast in a smoker) turns into crisp Cinder Toast.",
				"Brausebrot im Ofen ger\u00f6stet (im R\u00e4ucherofen doppelt so schnell) wird zu knusprigem Zindertoast."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_sugar_rush_fizz",
				"copper_inferno:sugar_rush_fizz", "cuisine/sugar_rush_fizz",
				new String[]{"minecraft:glass_bottle", FIZ, SSU, "", "", "", "", "", ""},
				"copper_inferno:sugar_rush_fizz", 1,
				"A Fizz Crystal and Soda Sugar in a bottle: Sugar Rush Fizz. One minute of the new Sugar Rush effect - +20% speed and +25% mining pace. The bottle comes back.",
				"Ein Brausekristall und Brausezucker in der Flasche: Zuckerrausch-Brause. Eine Minute des neuen Zuckerrausch-Effekts - +20% Tempo und +25% Abbaugeschwindigkeit. Die Flasche kommt zur\u00fcck."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_ember_belly_fizz",
				"copper_inferno:ember_belly_fizz", "cuisine/ember_belly_fizz",
				new String[]{"minecraft:glass_bottle", FIZ, OIL, "", "", "", "", "", ""},
				"copper_inferno:ember_belly_fizz", 1,
				"Fizz Crystal and Ember Oil bottled into Ember Belly Fizz: for a minute a warm ember smothers any fire on you and slowly refills your hunger.",
				"Brausekristall und Glut\u00f6l abgef\u00fcllt zur Glutbauch-Brause: eine Minute lang erstickt eine warme Glut jedes Feuer an dir und f\u00fcllt langsam den Hunger auf."));

		HandbookEntries.add(new HandbookEntry("items", "cuisine_cinder_skin_fizz",
				"copper_inferno:cinder_skin_fizz", "cuisine/cinder_skin_fizz",
				new String[]{"minecraft:glass_bottle", FIZ, SLT, "", "", "", "", "", ""},
				"copper_inferno:cinder_skin_fizz", 1,
				"Fizz Crystal and Cinder Salt make Cinder Skin Fizz: a minute of the new Cinder Skin effect, hardening your hide with +4 armor.",
				"Brausekristall und Zindersalz ergeben die Zinderhaut-Brause: eine Minute des neuen Zinderhaut-Effekts, der die Haut mit +4 R\u00fcstung h\u00e4rtet."));
	}
}
