package net.sonic0810.copperinferno.feature.charwood;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlockFamilies.BlockFamily;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Charwood block set: 224 building blocks across 14 scorched-organic charred-wood
 * materials (charwood, emberbark, sootbark, cinderlog, blazewood, magmawood,
 * kindlewood, pyrewood, smolderwood, glowbark, coalwood, tarwood, brimwood,
 * flarewood). Each material ships three full cube families (base, polished, bricks;
 * each base/slab/stairs/wall) plus tiles, cracked bricks, chiseled bricks and a
 * pillar. The charred-wood look is texture theme only: plain opaque
 * Block/PillarBlock registrations, requiresTool + pickaxe-mineable, with NO
 * burnable/strippable log mechanics.
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes,
 * EN+DE lang fragments) are generated by {@code devtools/gen/charwood_gen.py}; the tag
 * fragment lives at {@code devtools/tagfrag/charwood.json}; handbook pages are
 * registered by {@link CharwoodHandbook}.
 */
public final class CharwoodFeature {
	private CharwoodFeature() {
	}

	// Full cube families (base + slab + stairs + wall).
	public static BlockFamily CHARWOOD;
	public static BlockFamily POLISHED_CHARWOOD;
	public static BlockFamily CHARWOOD_BRICKS;
	public static BlockFamily EMBERBARK;
	public static BlockFamily POLISHED_EMBERBARK;
	public static BlockFamily EMBERBARK_BRICKS;
	public static BlockFamily SOOTBARK;
	public static BlockFamily POLISHED_SOOTBARK;
	public static BlockFamily SOOTBARK_BRICKS;
	public static BlockFamily CINDERLOG_BLOCK;
	public static BlockFamily POLISHED_CINDERLOG_BLOCK;
	public static BlockFamily CINDERLOG_BLOCK_BRICKS;
	public static BlockFamily BLAZEWOOD;
	public static BlockFamily POLISHED_BLAZEWOOD;
	public static BlockFamily BLAZEWOOD_BRICKS;
	public static BlockFamily MAGMAWOOD;
	public static BlockFamily POLISHED_MAGMAWOOD;
	public static BlockFamily MAGMAWOOD_BRICKS;
	public static BlockFamily KINDLEWOOD;
	public static BlockFamily POLISHED_KINDLEWOOD;
	public static BlockFamily KINDLEWOOD_BRICKS;
	public static BlockFamily PYREWOOD;
	public static BlockFamily POLISHED_PYREWOOD;
	public static BlockFamily PYREWOOD_BRICKS;
	public static BlockFamily SMOLDERWOOD;
	public static BlockFamily POLISHED_SMOLDERWOOD;
	public static BlockFamily SMOLDERWOOD_BRICKS;
	public static BlockFamily GLOWBARK;
	public static BlockFamily POLISHED_GLOWBARK;
	public static BlockFamily GLOWBARK_BRICKS;
	public static BlockFamily COALWOOD;
	public static BlockFamily POLISHED_COALWOOD;
	public static BlockFamily COALWOOD_BRICKS;
	public static BlockFamily TARWOOD;
	public static BlockFamily POLISHED_TARWOOD;
	public static BlockFamily TARWOOD_BRICKS;
	public static BlockFamily BRIMWOOD;
	public static BlockFamily POLISHED_BRIMWOOD;
	public static BlockFamily BRIMWOOD_BRICKS;
	public static BlockFamily FLAREWOOD;
	public static BlockFamily POLISHED_FLAREWOOD;
	public static BlockFamily FLAREWOOD_BRICKS;

	// Single blocks.
	public static Block CHARWOOD_TILES;
	public static Block CRACKED_CHARWOOD_BRICKS;
	public static Block CHISELED_CHARWOOD_BRICKS;
	public static Block CHARWOOD_PILLAR;
	public static Block EMBERBARK_TILES;
	public static Block CRACKED_EMBERBARK_BRICKS;
	public static Block CHISELED_EMBERBARK_BRICKS;
	public static Block EMBERBARK_PILLAR;
	public static Block SOOTBARK_TILES;
	public static Block CRACKED_SOOTBARK_BRICKS;
	public static Block CHISELED_SOOTBARK_BRICKS;
	public static Block SOOTBARK_PILLAR;
	public static Block CINDERLOG_BLOCK_TILES;
	public static Block CRACKED_CINDERLOG_BLOCK_BRICKS;
	public static Block CHISELED_CINDERLOG_BLOCK_BRICKS;
	public static Block CINDERLOG_BLOCK_PILLAR;
	public static Block BLAZEWOOD_TILES;
	public static Block CRACKED_BLAZEWOOD_BRICKS;
	public static Block CHISELED_BLAZEWOOD_BRICKS;
	public static Block BLAZEWOOD_PILLAR;
	public static Block MAGMAWOOD_TILES;
	public static Block CRACKED_MAGMAWOOD_BRICKS;
	public static Block CHISELED_MAGMAWOOD_BRICKS;
	public static Block MAGMAWOOD_PILLAR;
	public static Block KINDLEWOOD_TILES;
	public static Block CRACKED_KINDLEWOOD_BRICKS;
	public static Block CHISELED_KINDLEWOOD_BRICKS;
	public static Block KINDLEWOOD_PILLAR;
	public static Block PYREWOOD_TILES;
	public static Block CRACKED_PYREWOOD_BRICKS;
	public static Block CHISELED_PYREWOOD_BRICKS;
	public static Block PYREWOOD_PILLAR;
	public static Block SMOLDERWOOD_TILES;
	public static Block CRACKED_SMOLDERWOOD_BRICKS;
	public static Block CHISELED_SMOLDERWOOD_BRICKS;
	public static Block SMOLDERWOOD_PILLAR;
	public static Block GLOWBARK_TILES;
	public static Block CRACKED_GLOWBARK_BRICKS;
	public static Block CHISELED_GLOWBARK_BRICKS;
	public static Block GLOWBARK_PILLAR;
	public static Block COALWOOD_TILES;
	public static Block CRACKED_COALWOOD_BRICKS;
	public static Block CHISELED_COALWOOD_BRICKS;
	public static Block COALWOOD_PILLAR;
	public static Block TARWOOD_TILES;
	public static Block CRACKED_TARWOOD_BRICKS;
	public static Block CHISELED_TARWOOD_BRICKS;
	public static Block TARWOOD_PILLAR;
	public static Block BRIMWOOD_TILES;
	public static Block CRACKED_BRIMWOOD_BRICKS;
	public static Block CHISELED_BRIMWOOD_BRICKS;
	public static Block BRIMWOOD_PILLAR;
	public static Block FLAREWOOD_TILES;
	public static Block CRACKED_FLAREWOOD_BRICKS;
	public static Block CHISELED_FLAREWOOD_BRICKS;
	public static Block FLAREWOOD_PILLAR;

	/**
	 * Fresh settings per block ({@link ModBlocks#register} writes a registry key into the
	 * instance, so settings must never be shared). Charred-hardwood profile: wood-ish
	 * sounds/strength but requiresTool + pickaxe-mineable (all charwood ids ship in
	 * block/mineable/pickaxe via devtools/tagfrag/charwood.json).
	 */
	private static AbstractBlock.Settings charredWoodSettings(MapColor color, BlockSoundGroup sounds) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(2.5F, 6.0F)
				.requiresTool()
				.sounds(sounds);
	}

	private static AbstractBlock.Settings charwoodSettings() {
		return charredWoodSettings(MapColor.TERRACOTTA_BLACK, BlockSoundGroup.WOOD);
	}

	private static AbstractBlock.Settings emberbarkSettings() {
		return charredWoodSettings(MapColor.TERRACOTTA_ORANGE, BlockSoundGroup.NETHER_WOOD);
	}

	private static AbstractBlock.Settings sootbarkSettings() {
		return charredWoodSettings(MapColor.TERRACOTTA_GRAY, BlockSoundGroup.WOOD);
	}

	private static AbstractBlock.Settings cinderlogBlockSettings() {
		return charredWoodSettings(MapColor.SPRUCE_BROWN, BlockSoundGroup.WOOD);
	}

	private static AbstractBlock.Settings blazewoodSettings() {
		return charredWoodSettings(MapColor.ORANGE, BlockSoundGroup.NETHER_WOOD);
	}

	private static AbstractBlock.Settings magmawoodSettings() {
		return charredWoodSettings(MapColor.DARK_RED, BlockSoundGroup.NETHER_WOOD);
	}

	private static AbstractBlock.Settings kindlewoodSettings() {
		return charredWoodSettings(MapColor.OAK_TAN, BlockSoundGroup.BAMBOO_WOOD);
	}

	private static AbstractBlock.Settings pyrewoodSettings() {
		return charredWoodSettings(MapColor.TERRACOTTA_RED, BlockSoundGroup.WOOD);
	}

	private static AbstractBlock.Settings smolderwoodSettings() {
		return charredWoodSettings(MapColor.DULL_RED, BlockSoundGroup.NETHER_WOOD);
	}

	private static AbstractBlock.Settings glowbarkSettings() {
		return charredWoodSettings(MapColor.GOLD, BlockSoundGroup.CHERRY_WOOD);
	}

	private static AbstractBlock.Settings coalwoodSettings() {
		return charredWoodSettings(MapColor.BLACK, BlockSoundGroup.WOOD);
	}

	private static AbstractBlock.Settings tarwoodSettings() {
		return charredWoodSettings(MapColor.TERRACOTTA_BROWN, BlockSoundGroup.BAMBOO_WOOD);
	}

	private static AbstractBlock.Settings brimwoodSettings() {
		return charredWoodSettings(MapColor.TERRACOTTA_YELLOW, BlockSoundGroup.NETHER_STEM);
	}

	private static AbstractBlock.Settings flarewoodSettings() {
		return charredWoodSettings(MapColor.BRIGHT_RED, BlockSoundGroup.CHERRY_WOOD);
	}

	public static void init() {
		CHARWOOD = ModBlockFamilies.registerCubeFamily(
				"charwood", "charwood", CharwoodFeature::charwoodSettings, true);
		POLISHED_CHARWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_charwood", "polished_charwood", CharwoodFeature::charwoodSettings, true);
		CHARWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"charwood_bricks", "charwood_brick", CharwoodFeature::charwoodSettings, true);
		EMBERBARK = ModBlockFamilies.registerCubeFamily(
				"emberbark", "emberbark", CharwoodFeature::emberbarkSettings, true);
		POLISHED_EMBERBARK = ModBlockFamilies.registerCubeFamily(
				"polished_emberbark", "polished_emberbark", CharwoodFeature::emberbarkSettings, true);
		EMBERBARK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"emberbark_bricks", "emberbark_brick", CharwoodFeature::emberbarkSettings, true);
		SOOTBARK = ModBlockFamilies.registerCubeFamily(
				"sootbark", "sootbark", CharwoodFeature::sootbarkSettings, true);
		POLISHED_SOOTBARK = ModBlockFamilies.registerCubeFamily(
				"polished_sootbark", "polished_sootbark", CharwoodFeature::sootbarkSettings, true);
		SOOTBARK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"sootbark_bricks", "sootbark_brick", CharwoodFeature::sootbarkSettings, true);
		CINDERLOG_BLOCK = ModBlockFamilies.registerCubeFamily(
				"cinderlog_block", "cinderlog_block", CharwoodFeature::cinderlogBlockSettings, true);
		POLISHED_CINDERLOG_BLOCK = ModBlockFamilies.registerCubeFamily(
				"polished_cinderlog_block", "polished_cinderlog_block", CharwoodFeature::cinderlogBlockSettings, true);
		CINDERLOG_BLOCK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"cinderlog_block_bricks", "cinderlog_block_brick", CharwoodFeature::cinderlogBlockSettings, true);
		BLAZEWOOD = ModBlockFamilies.registerCubeFamily(
				"blazewood", "blazewood", CharwoodFeature::blazewoodSettings, true);
		POLISHED_BLAZEWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_blazewood", "polished_blazewood", CharwoodFeature::blazewoodSettings, true);
		BLAZEWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"blazewood_bricks", "blazewood_brick", CharwoodFeature::blazewoodSettings, true);
		MAGMAWOOD = ModBlockFamilies.registerCubeFamily(
				"magmawood", "magmawood", CharwoodFeature::magmawoodSettings, true);
		POLISHED_MAGMAWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_magmawood", "polished_magmawood", CharwoodFeature::magmawoodSettings, true);
		MAGMAWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"magmawood_bricks", "magmawood_brick", CharwoodFeature::magmawoodSettings, true);
		KINDLEWOOD = ModBlockFamilies.registerCubeFamily(
				"kindlewood", "kindlewood", CharwoodFeature::kindlewoodSettings, true);
		POLISHED_KINDLEWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_kindlewood", "polished_kindlewood", CharwoodFeature::kindlewoodSettings, true);
		KINDLEWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"kindlewood_bricks", "kindlewood_brick", CharwoodFeature::kindlewoodSettings, true);
		PYREWOOD = ModBlockFamilies.registerCubeFamily(
				"pyrewood", "pyrewood", CharwoodFeature::pyrewoodSettings, true);
		POLISHED_PYREWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_pyrewood", "polished_pyrewood", CharwoodFeature::pyrewoodSettings, true);
		PYREWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"pyrewood_bricks", "pyrewood_brick", CharwoodFeature::pyrewoodSettings, true);
		SMOLDERWOOD = ModBlockFamilies.registerCubeFamily(
				"smolderwood", "smolderwood", CharwoodFeature::smolderwoodSettings, true);
		POLISHED_SMOLDERWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_smolderwood", "polished_smolderwood", CharwoodFeature::smolderwoodSettings, true);
		SMOLDERWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"smolderwood_bricks", "smolderwood_brick", CharwoodFeature::smolderwoodSettings, true);
		GLOWBARK = ModBlockFamilies.registerCubeFamily(
				"glowbark", "glowbark", CharwoodFeature::glowbarkSettings, true);
		POLISHED_GLOWBARK = ModBlockFamilies.registerCubeFamily(
				"polished_glowbark", "polished_glowbark", CharwoodFeature::glowbarkSettings, true);
		GLOWBARK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"glowbark_bricks", "glowbark_brick", CharwoodFeature::glowbarkSettings, true);
		COALWOOD = ModBlockFamilies.registerCubeFamily(
				"coalwood", "coalwood", CharwoodFeature::coalwoodSettings, true);
		POLISHED_COALWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_coalwood", "polished_coalwood", CharwoodFeature::coalwoodSettings, true);
		COALWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"coalwood_bricks", "coalwood_brick", CharwoodFeature::coalwoodSettings, true);
		TARWOOD = ModBlockFamilies.registerCubeFamily(
				"tarwood", "tarwood", CharwoodFeature::tarwoodSettings, true);
		POLISHED_TARWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_tarwood", "polished_tarwood", CharwoodFeature::tarwoodSettings, true);
		TARWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"tarwood_bricks", "tarwood_brick", CharwoodFeature::tarwoodSettings, true);
		BRIMWOOD = ModBlockFamilies.registerCubeFamily(
				"brimwood", "brimwood", CharwoodFeature::brimwoodSettings, true);
		POLISHED_BRIMWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_brimwood", "polished_brimwood", CharwoodFeature::brimwoodSettings, true);
		BRIMWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"brimwood_bricks", "brimwood_brick", CharwoodFeature::brimwoodSettings, true);
		FLAREWOOD = ModBlockFamilies.registerCubeFamily(
				"flarewood", "flarewood", CharwoodFeature::flarewoodSettings, true);
		POLISHED_FLAREWOOD = ModBlockFamilies.registerCubeFamily(
				"polished_flarewood", "polished_flarewood", CharwoodFeature::flarewoodSettings, true);
		FLAREWOOD_BRICKS = ModBlockFamilies.registerCubeFamily(
				"flarewood_bricks", "flarewood_brick", CharwoodFeature::flarewoodSettings, true);

		CHARWOOD_TILES = ModBlocks.register("charwood_tiles", Block::new, charwoodSettings(), true);
		CRACKED_CHARWOOD_BRICKS = ModBlocks.register("cracked_charwood_bricks", Block::new, charwoodSettings(), true);
		CHISELED_CHARWOOD_BRICKS = ModBlocks.register("chiseled_charwood_bricks", Block::new, charwoodSettings(), true);
		CHARWOOD_PILLAR = ModBlocks.register("charwood_pillar", PillarBlock::new, charwoodSettings(), true);
		EMBERBARK_TILES = ModBlocks.register("emberbark_tiles", Block::new, emberbarkSettings(), true);
		CRACKED_EMBERBARK_BRICKS = ModBlocks.register("cracked_emberbark_bricks", Block::new, emberbarkSettings(), true);
		CHISELED_EMBERBARK_BRICKS = ModBlocks.register("chiseled_emberbark_bricks", Block::new, emberbarkSettings(), true);
		EMBERBARK_PILLAR = ModBlocks.register("emberbark_pillar", PillarBlock::new, emberbarkSettings(), true);
		SOOTBARK_TILES = ModBlocks.register("sootbark_tiles", Block::new, sootbarkSettings(), true);
		CRACKED_SOOTBARK_BRICKS = ModBlocks.register("cracked_sootbark_bricks", Block::new, sootbarkSettings(), true);
		CHISELED_SOOTBARK_BRICKS = ModBlocks.register("chiseled_sootbark_bricks", Block::new, sootbarkSettings(), true);
		SOOTBARK_PILLAR = ModBlocks.register("sootbark_pillar", PillarBlock::new, sootbarkSettings(), true);
		CINDERLOG_BLOCK_TILES = ModBlocks.register("cinderlog_block_tiles", Block::new, cinderlogBlockSettings(), true);
		CRACKED_CINDERLOG_BLOCK_BRICKS = ModBlocks.register("cracked_cinderlog_block_bricks", Block::new, cinderlogBlockSettings(), true);
		CHISELED_CINDERLOG_BLOCK_BRICKS = ModBlocks.register("chiseled_cinderlog_block_bricks", Block::new, cinderlogBlockSettings(), true);
		CINDERLOG_BLOCK_PILLAR = ModBlocks.register("cinderlog_block_pillar", PillarBlock::new, cinderlogBlockSettings(), true);
		BLAZEWOOD_TILES = ModBlocks.register("blazewood_tiles", Block::new, blazewoodSettings(), true);
		CRACKED_BLAZEWOOD_BRICKS = ModBlocks.register("cracked_blazewood_bricks", Block::new, blazewoodSettings(), true);
		CHISELED_BLAZEWOOD_BRICKS = ModBlocks.register("chiseled_blazewood_bricks", Block::new, blazewoodSettings(), true);
		BLAZEWOOD_PILLAR = ModBlocks.register("blazewood_pillar", PillarBlock::new, blazewoodSettings(), true);
		MAGMAWOOD_TILES = ModBlocks.register("magmawood_tiles", Block::new, magmawoodSettings(), true);
		CRACKED_MAGMAWOOD_BRICKS = ModBlocks.register("cracked_magmawood_bricks", Block::new, magmawoodSettings(), true);
		CHISELED_MAGMAWOOD_BRICKS = ModBlocks.register("chiseled_magmawood_bricks", Block::new, magmawoodSettings(), true);
		MAGMAWOOD_PILLAR = ModBlocks.register("magmawood_pillar", PillarBlock::new, magmawoodSettings(), true);
		KINDLEWOOD_TILES = ModBlocks.register("kindlewood_tiles", Block::new, kindlewoodSettings(), true);
		CRACKED_KINDLEWOOD_BRICKS = ModBlocks.register("cracked_kindlewood_bricks", Block::new, kindlewoodSettings(), true);
		CHISELED_KINDLEWOOD_BRICKS = ModBlocks.register("chiseled_kindlewood_bricks", Block::new, kindlewoodSettings(), true);
		KINDLEWOOD_PILLAR = ModBlocks.register("kindlewood_pillar", PillarBlock::new, kindlewoodSettings(), true);
		PYREWOOD_TILES = ModBlocks.register("pyrewood_tiles", Block::new, pyrewoodSettings(), true);
		CRACKED_PYREWOOD_BRICKS = ModBlocks.register("cracked_pyrewood_bricks", Block::new, pyrewoodSettings(), true);
		CHISELED_PYREWOOD_BRICKS = ModBlocks.register("chiseled_pyrewood_bricks", Block::new, pyrewoodSettings(), true);
		PYREWOOD_PILLAR = ModBlocks.register("pyrewood_pillar", PillarBlock::new, pyrewoodSettings(), true);
		SMOLDERWOOD_TILES = ModBlocks.register("smolderwood_tiles", Block::new, smolderwoodSettings(), true);
		CRACKED_SMOLDERWOOD_BRICKS = ModBlocks.register("cracked_smolderwood_bricks", Block::new, smolderwoodSettings(), true);
		CHISELED_SMOLDERWOOD_BRICKS = ModBlocks.register("chiseled_smolderwood_bricks", Block::new, smolderwoodSettings(), true);
		SMOLDERWOOD_PILLAR = ModBlocks.register("smolderwood_pillar", PillarBlock::new, smolderwoodSettings(), true);
		GLOWBARK_TILES = ModBlocks.register("glowbark_tiles", Block::new, glowbarkSettings(), true);
		CRACKED_GLOWBARK_BRICKS = ModBlocks.register("cracked_glowbark_bricks", Block::new, glowbarkSettings(), true);
		CHISELED_GLOWBARK_BRICKS = ModBlocks.register("chiseled_glowbark_bricks", Block::new, glowbarkSettings(), true);
		GLOWBARK_PILLAR = ModBlocks.register("glowbark_pillar", PillarBlock::new, glowbarkSettings(), true);
		COALWOOD_TILES = ModBlocks.register("coalwood_tiles", Block::new, coalwoodSettings(), true);
		CRACKED_COALWOOD_BRICKS = ModBlocks.register("cracked_coalwood_bricks", Block::new, coalwoodSettings(), true);
		CHISELED_COALWOOD_BRICKS = ModBlocks.register("chiseled_coalwood_bricks", Block::new, coalwoodSettings(), true);
		COALWOOD_PILLAR = ModBlocks.register("coalwood_pillar", PillarBlock::new, coalwoodSettings(), true);
		TARWOOD_TILES = ModBlocks.register("tarwood_tiles", Block::new, tarwoodSettings(), true);
		CRACKED_TARWOOD_BRICKS = ModBlocks.register("cracked_tarwood_bricks", Block::new, tarwoodSettings(), true);
		CHISELED_TARWOOD_BRICKS = ModBlocks.register("chiseled_tarwood_bricks", Block::new, tarwoodSettings(), true);
		TARWOOD_PILLAR = ModBlocks.register("tarwood_pillar", PillarBlock::new, tarwoodSettings(), true);
		BRIMWOOD_TILES = ModBlocks.register("brimwood_tiles", Block::new, brimwoodSettings(), true);
		CRACKED_BRIMWOOD_BRICKS = ModBlocks.register("cracked_brimwood_bricks", Block::new, brimwoodSettings(), true);
		CHISELED_BRIMWOOD_BRICKS = ModBlocks.register("chiseled_brimwood_bricks", Block::new, brimwoodSettings(), true);
		BRIMWOOD_PILLAR = ModBlocks.register("brimwood_pillar", PillarBlock::new, brimwoodSettings(), true);
		FLAREWOOD_TILES = ModBlocks.register("flarewood_tiles", Block::new, flarewoodSettings(), true);
		CRACKED_FLAREWOOD_BRICKS = ModBlocks.register("cracked_flarewood_bricks", Block::new, flarewoodSettings(), true);
		CHISELED_FLAREWOOD_BRICKS = ModBlocks.register("chiseled_flarewood_bricks", Block::new, flarewoodSettings(), true);
		FLAREWOOD_PILLAR = ModBlocks.register("flarewood_pillar", PillarBlock::new, flarewoodSettings(), true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			entries.add(CHARWOOD.block());
			entries.add(CHARWOOD.stairs());
			entries.add(CHARWOOD.slab());
			entries.add(CHARWOOD.wall());
			entries.add(POLISHED_CHARWOOD.block());
			entries.add(POLISHED_CHARWOOD.stairs());
			entries.add(POLISHED_CHARWOOD.slab());
			entries.add(POLISHED_CHARWOOD.wall());
			entries.add(CHARWOOD_BRICKS.block());
			entries.add(CHARWOOD_BRICKS.stairs());
			entries.add(CHARWOOD_BRICKS.slab());
			entries.add(CHARWOOD_BRICKS.wall());
			entries.add(CHARWOOD_TILES);
			entries.add(CRACKED_CHARWOOD_BRICKS);
			entries.add(CHISELED_CHARWOOD_BRICKS);
			entries.add(CHARWOOD_PILLAR);
			entries.add(EMBERBARK.block());
			entries.add(EMBERBARK.stairs());
			entries.add(EMBERBARK.slab());
			entries.add(EMBERBARK.wall());
			entries.add(POLISHED_EMBERBARK.block());
			entries.add(POLISHED_EMBERBARK.stairs());
			entries.add(POLISHED_EMBERBARK.slab());
			entries.add(POLISHED_EMBERBARK.wall());
			entries.add(EMBERBARK_BRICKS.block());
			entries.add(EMBERBARK_BRICKS.stairs());
			entries.add(EMBERBARK_BRICKS.slab());
			entries.add(EMBERBARK_BRICKS.wall());
			entries.add(EMBERBARK_TILES);
			entries.add(CRACKED_EMBERBARK_BRICKS);
			entries.add(CHISELED_EMBERBARK_BRICKS);
			entries.add(EMBERBARK_PILLAR);
			entries.add(SOOTBARK.block());
			entries.add(SOOTBARK.stairs());
			entries.add(SOOTBARK.slab());
			entries.add(SOOTBARK.wall());
			entries.add(POLISHED_SOOTBARK.block());
			entries.add(POLISHED_SOOTBARK.stairs());
			entries.add(POLISHED_SOOTBARK.slab());
			entries.add(POLISHED_SOOTBARK.wall());
			entries.add(SOOTBARK_BRICKS.block());
			entries.add(SOOTBARK_BRICKS.stairs());
			entries.add(SOOTBARK_BRICKS.slab());
			entries.add(SOOTBARK_BRICKS.wall());
			entries.add(SOOTBARK_TILES);
			entries.add(CRACKED_SOOTBARK_BRICKS);
			entries.add(CHISELED_SOOTBARK_BRICKS);
			entries.add(SOOTBARK_PILLAR);
			entries.add(CINDERLOG_BLOCK.block());
			entries.add(CINDERLOG_BLOCK.stairs());
			entries.add(CINDERLOG_BLOCK.slab());
			entries.add(CINDERLOG_BLOCK.wall());
			entries.add(POLISHED_CINDERLOG_BLOCK.block());
			entries.add(POLISHED_CINDERLOG_BLOCK.stairs());
			entries.add(POLISHED_CINDERLOG_BLOCK.slab());
			entries.add(POLISHED_CINDERLOG_BLOCK.wall());
			entries.add(CINDERLOG_BLOCK_BRICKS.block());
			entries.add(CINDERLOG_BLOCK_BRICKS.stairs());
			entries.add(CINDERLOG_BLOCK_BRICKS.slab());
			entries.add(CINDERLOG_BLOCK_BRICKS.wall());
			entries.add(CINDERLOG_BLOCK_TILES);
			entries.add(CRACKED_CINDERLOG_BLOCK_BRICKS);
			entries.add(CHISELED_CINDERLOG_BLOCK_BRICKS);
			entries.add(CINDERLOG_BLOCK_PILLAR);
			entries.add(BLAZEWOOD.block());
			entries.add(BLAZEWOOD.stairs());
			entries.add(BLAZEWOOD.slab());
			entries.add(BLAZEWOOD.wall());
			entries.add(POLISHED_BLAZEWOOD.block());
			entries.add(POLISHED_BLAZEWOOD.stairs());
			entries.add(POLISHED_BLAZEWOOD.slab());
			entries.add(POLISHED_BLAZEWOOD.wall());
			entries.add(BLAZEWOOD_BRICKS.block());
			entries.add(BLAZEWOOD_BRICKS.stairs());
			entries.add(BLAZEWOOD_BRICKS.slab());
			entries.add(BLAZEWOOD_BRICKS.wall());
			entries.add(BLAZEWOOD_TILES);
			entries.add(CRACKED_BLAZEWOOD_BRICKS);
			entries.add(CHISELED_BLAZEWOOD_BRICKS);
			entries.add(BLAZEWOOD_PILLAR);
			entries.add(MAGMAWOOD.block());
			entries.add(MAGMAWOOD.stairs());
			entries.add(MAGMAWOOD.slab());
			entries.add(MAGMAWOOD.wall());
			entries.add(POLISHED_MAGMAWOOD.block());
			entries.add(POLISHED_MAGMAWOOD.stairs());
			entries.add(POLISHED_MAGMAWOOD.slab());
			entries.add(POLISHED_MAGMAWOOD.wall());
			entries.add(MAGMAWOOD_BRICKS.block());
			entries.add(MAGMAWOOD_BRICKS.stairs());
			entries.add(MAGMAWOOD_BRICKS.slab());
			entries.add(MAGMAWOOD_BRICKS.wall());
			entries.add(MAGMAWOOD_TILES);
			entries.add(CRACKED_MAGMAWOOD_BRICKS);
			entries.add(CHISELED_MAGMAWOOD_BRICKS);
			entries.add(MAGMAWOOD_PILLAR);
			entries.add(KINDLEWOOD.block());
			entries.add(KINDLEWOOD.stairs());
			entries.add(KINDLEWOOD.slab());
			entries.add(KINDLEWOOD.wall());
			entries.add(POLISHED_KINDLEWOOD.block());
			entries.add(POLISHED_KINDLEWOOD.stairs());
			entries.add(POLISHED_KINDLEWOOD.slab());
			entries.add(POLISHED_KINDLEWOOD.wall());
			entries.add(KINDLEWOOD_BRICKS.block());
			entries.add(KINDLEWOOD_BRICKS.stairs());
			entries.add(KINDLEWOOD_BRICKS.slab());
			entries.add(KINDLEWOOD_BRICKS.wall());
			entries.add(KINDLEWOOD_TILES);
			entries.add(CRACKED_KINDLEWOOD_BRICKS);
			entries.add(CHISELED_KINDLEWOOD_BRICKS);
			entries.add(KINDLEWOOD_PILLAR);
			entries.add(PYREWOOD.block());
			entries.add(PYREWOOD.stairs());
			entries.add(PYREWOOD.slab());
			entries.add(PYREWOOD.wall());
			entries.add(POLISHED_PYREWOOD.block());
			entries.add(POLISHED_PYREWOOD.stairs());
			entries.add(POLISHED_PYREWOOD.slab());
			entries.add(POLISHED_PYREWOOD.wall());
			entries.add(PYREWOOD_BRICKS.block());
			entries.add(PYREWOOD_BRICKS.stairs());
			entries.add(PYREWOOD_BRICKS.slab());
			entries.add(PYREWOOD_BRICKS.wall());
			entries.add(PYREWOOD_TILES);
			entries.add(CRACKED_PYREWOOD_BRICKS);
			entries.add(CHISELED_PYREWOOD_BRICKS);
			entries.add(PYREWOOD_PILLAR);
			entries.add(SMOLDERWOOD.block());
			entries.add(SMOLDERWOOD.stairs());
			entries.add(SMOLDERWOOD.slab());
			entries.add(SMOLDERWOOD.wall());
			entries.add(POLISHED_SMOLDERWOOD.block());
			entries.add(POLISHED_SMOLDERWOOD.stairs());
			entries.add(POLISHED_SMOLDERWOOD.slab());
			entries.add(POLISHED_SMOLDERWOOD.wall());
			entries.add(SMOLDERWOOD_BRICKS.block());
			entries.add(SMOLDERWOOD_BRICKS.stairs());
			entries.add(SMOLDERWOOD_BRICKS.slab());
			entries.add(SMOLDERWOOD_BRICKS.wall());
			entries.add(SMOLDERWOOD_TILES);
			entries.add(CRACKED_SMOLDERWOOD_BRICKS);
			entries.add(CHISELED_SMOLDERWOOD_BRICKS);
			entries.add(SMOLDERWOOD_PILLAR);
			entries.add(GLOWBARK.block());
			entries.add(GLOWBARK.stairs());
			entries.add(GLOWBARK.slab());
			entries.add(GLOWBARK.wall());
			entries.add(POLISHED_GLOWBARK.block());
			entries.add(POLISHED_GLOWBARK.stairs());
			entries.add(POLISHED_GLOWBARK.slab());
			entries.add(POLISHED_GLOWBARK.wall());
			entries.add(GLOWBARK_BRICKS.block());
			entries.add(GLOWBARK_BRICKS.stairs());
			entries.add(GLOWBARK_BRICKS.slab());
			entries.add(GLOWBARK_BRICKS.wall());
			entries.add(GLOWBARK_TILES);
			entries.add(CRACKED_GLOWBARK_BRICKS);
			entries.add(CHISELED_GLOWBARK_BRICKS);
			entries.add(GLOWBARK_PILLAR);
			entries.add(COALWOOD.block());
			entries.add(COALWOOD.stairs());
			entries.add(COALWOOD.slab());
			entries.add(COALWOOD.wall());
			entries.add(POLISHED_COALWOOD.block());
			entries.add(POLISHED_COALWOOD.stairs());
			entries.add(POLISHED_COALWOOD.slab());
			entries.add(POLISHED_COALWOOD.wall());
			entries.add(COALWOOD_BRICKS.block());
			entries.add(COALWOOD_BRICKS.stairs());
			entries.add(COALWOOD_BRICKS.slab());
			entries.add(COALWOOD_BRICKS.wall());
			entries.add(COALWOOD_TILES);
			entries.add(CRACKED_COALWOOD_BRICKS);
			entries.add(CHISELED_COALWOOD_BRICKS);
			entries.add(COALWOOD_PILLAR);
			entries.add(TARWOOD.block());
			entries.add(TARWOOD.stairs());
			entries.add(TARWOOD.slab());
			entries.add(TARWOOD.wall());
			entries.add(POLISHED_TARWOOD.block());
			entries.add(POLISHED_TARWOOD.stairs());
			entries.add(POLISHED_TARWOOD.slab());
			entries.add(POLISHED_TARWOOD.wall());
			entries.add(TARWOOD_BRICKS.block());
			entries.add(TARWOOD_BRICKS.stairs());
			entries.add(TARWOOD_BRICKS.slab());
			entries.add(TARWOOD_BRICKS.wall());
			entries.add(TARWOOD_TILES);
			entries.add(CRACKED_TARWOOD_BRICKS);
			entries.add(CHISELED_TARWOOD_BRICKS);
			entries.add(TARWOOD_PILLAR);
			entries.add(BRIMWOOD.block());
			entries.add(BRIMWOOD.stairs());
			entries.add(BRIMWOOD.slab());
			entries.add(BRIMWOOD.wall());
			entries.add(POLISHED_BRIMWOOD.block());
			entries.add(POLISHED_BRIMWOOD.stairs());
			entries.add(POLISHED_BRIMWOOD.slab());
			entries.add(POLISHED_BRIMWOOD.wall());
			entries.add(BRIMWOOD_BRICKS.block());
			entries.add(BRIMWOOD_BRICKS.stairs());
			entries.add(BRIMWOOD_BRICKS.slab());
			entries.add(BRIMWOOD_BRICKS.wall());
			entries.add(BRIMWOOD_TILES);
			entries.add(CRACKED_BRIMWOOD_BRICKS);
			entries.add(CHISELED_BRIMWOOD_BRICKS);
			entries.add(BRIMWOOD_PILLAR);
			entries.add(FLAREWOOD.block());
			entries.add(FLAREWOOD.stairs());
			entries.add(FLAREWOOD.slab());
			entries.add(FLAREWOOD.wall());
			entries.add(POLISHED_FLAREWOOD.block());
			entries.add(POLISHED_FLAREWOOD.stairs());
			entries.add(POLISHED_FLAREWOOD.slab());
			entries.add(POLISHED_FLAREWOOD.wall());
			entries.add(FLAREWOOD_BRICKS.block());
			entries.add(FLAREWOOD_BRICKS.stairs());
			entries.add(FLAREWOOD_BRICKS.slab());
			entries.add(FLAREWOOD_BRICKS.wall());
			entries.add(FLAREWOOD_TILES);
			entries.add(CRACKED_FLAREWOOD_BRICKS);
			entries.add(CHISELED_FLAREWOOD_BRICKS);
			entries.add(FLAREWOOD_PILLAR);
		});

		CharwoodHandbook.register();
	}
}
