package net.sonic0810.copperinferno.feature.infernogardens;

import java.util.function.Predicate;
import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.GlowLichenBlock;
import net.minecraft.block.MapColor;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.world.gen.GenerationStep;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Inferno gardens: 25 data-driven worldgen features (flora patches, weighted garden
 * mixes, ceiling/wall growth, crystal clusters, giant fungi, moss shelves) for the
 * three Inferno biomes, plus the 20 new plant/deco blocks they place. The
 * configured/placed feature JSONs live under
 * {@code data/copper_inferno/worldgen/} and are generated by
 * {@code devtools/gen/infernogardens_gen.py} from extracted vanilla 1.21.9 schemas;
 * the biome JSONs are NOT touched — placement is wired here via Fabric's
 * {@code BiomeModifications.addFeature} (signature verified via javap).
 *
 * <p>DOCUMENTED SIMPLIFICATIONS (mirroring infernoflora):
 * <ul>
 *   <li>The 15 cross-model plants are plain {@link Block}s with
 *       {@code noCollision().breakInstantly()} — no floor/support check; the worldgen
 *       patch predicates are the only ground filter.</li>
 *   <li>All blocks except verdigris_lichen drop themselves unconditionally;
 *       verdigris_lichen uses the vanilla glow-lichen shears table.</li>
 * </ul>
 *
 * <p>CUTOUT render layers are registered client-side by
 * {@code InfernoGardensFeatureClient}; handbook pages by
 * {@link InfernoGardensHandbook}.
 */
public final class InfernoGardensFeature {
	private InfernoGardensFeature() {
	}

	// Single blocks.
	public static Block EMBER_LILY;
	public static Block CINDER_FERN;
	public static Block SEAR_SPRIGS;
	public static Block MOLTEN_BUD;
	public static Block ASH_BRAMBLE;
	public static Block GLOW_TENDRILS;
	public static Block SOOT_PUFF;
	public static Block SLAG_THISTLE;
	public static Block PYRE_REED;
	public static Block COPPER_ROSE;
	public static Block INFERNO_ORCHID;
	public static Block CHARRED_SHRUB;
	public static Block GILDED_CLOVER;
	public static Block HANGING_EMBER_ROOTS;
	public static Block ASH_VEIL;
	public static Block EMBERCAP_BLOCK;
	public static Block GLOOMCAP_BLOCK;
	public static Block CINDER_CRYSTAL_BLOCK;
	public static Block VERDIGRIS_CRYSTAL_BLOCK;
	public static Block VERDIGRIS_LICHEN;

	/**
	 * Fresh settings per registration ({@link ModBlocks#register} writes a registry key
	 * into the instance). Cross-model garden plants: no collision, instant break — same
	 * documented simplification as the infernoflora plants (placeable on any surface, no
	 * floor check; the worldgen patch predicates are the only ground filter).
	 */
	private static AbstractBlock.Settings plantSettings(BlockSoundGroup sounds, MapColor mapColor) {
		return AbstractBlock.Settings.create()
				.mapColor(mapColor)
				.noCollision()
				.breakInstantly()
				.sounds(sounds);
	}

	/** Giant-fungus cap cubes (vanilla wart-block profile: strength 1.0, wart sounds). */
	private static AbstractBlock.Settings capSettings(MapColor mapColor, int light) {
		return AbstractBlock.Settings.create()
				.mapColor(mapColor)
				.strength(1.0F)
				.sounds(BlockSoundGroup.NETHER_WART)
				.luminance(state -> light);
	}

	/** Glowing crystal cubes (amethyst-block sounds; hand-breakable, no requiresTool). */
	private static AbstractBlock.Settings crystalSettings(MapColor mapColor, int light) {
		return AbstractBlock.Settings.create()
				.mapColor(mapColor)
				.strength(1.5F)
				.sounds(BlockSoundGroup.AMETHYST_BLOCK)
				.luminance(state -> light);
	}

	public static void init() {
		EMBER_LILY = ModBlocks.register("ember_lily", Block::new, plantSettings(BlockSoundGroup.SPORE_BLOSSOM, MapColor.ORANGE).luminance(state -> 5), true);
		CINDER_FERN = ModBlocks.register("cinder_fern", Block::new, plantSettings(BlockSoundGroup.ROOTS, MapColor.GRAY), true);
		SEAR_SPRIGS = ModBlocks.register("sear_sprigs", Block::new, plantSettings(BlockSoundGroup.ROOTS, MapColor.SPRUCE_BROWN), true);
		MOLTEN_BUD = ModBlocks.register("molten_bud", Block::new, plantSettings(BlockSoundGroup.NETHER_WART, MapColor.ORANGE).luminance(state -> 6), true);
		ASH_BRAMBLE = ModBlocks.register("ash_bramble", Block::new, plantSettings(BlockSoundGroup.ROOTS, MapColor.LIGHT_GRAY), true);
		GLOW_TENDRILS = ModBlocks.register("glow_tendrils", Block::new, plantSettings(BlockSoundGroup.CAVE_VINES, MapColor.TEAL).luminance(state -> 7), true);
		SOOT_PUFF = ModBlocks.register("soot_puff", Block::new, plantSettings(BlockSoundGroup.FUNGUS, MapColor.GRAY), true);
		SLAG_THISTLE = ModBlocks.register("slag_thistle", Block::new, plantSettings(BlockSoundGroup.ROOTS, MapColor.GRAY), true);
		PYRE_REED = ModBlocks.register("pyre_reed", Block::new, plantSettings(BlockSoundGroup.ROOTS, MapColor.ORANGE), true);
		COPPER_ROSE = ModBlocks.register("copper_rose", Block::new, plantSettings(BlockSoundGroup.SPORE_BLOSSOM, MapColor.ORANGE), true);
		INFERNO_ORCHID = ModBlocks.register("inferno_orchid", Block::new, plantSettings(BlockSoundGroup.SPORE_BLOSSOM, MapColor.MAGENTA).luminance(state -> 4), true);
		CHARRED_SHRUB = ModBlocks.register("charred_shrub", Block::new, plantSettings(BlockSoundGroup.ROOTS, MapColor.SPRUCE_BROWN), true);
		GILDED_CLOVER = ModBlocks.register("gilded_clover", Block::new, plantSettings(BlockSoundGroup.ROOTS, MapColor.YELLOW), true);
		HANGING_EMBER_ROOTS = ModBlocks.register("hanging_ember_roots", Block::new, plantSettings(BlockSoundGroup.HANGING_ROOTS, MapColor.DARK_RED).luminance(state -> 3), true);
		ASH_VEIL = ModBlocks.register("ash_veil", Block::new, plantSettings(BlockSoundGroup.HANGING_ROOTS, MapColor.LIGHT_GRAY), true);
		EMBERCAP_BLOCK = ModBlocks.register("embercap_block", Block::new, capSettings(MapColor.ORANGE, 4), true);
		GLOOMCAP_BLOCK = ModBlocks.register("gloomcap_block", Block::new, capSettings(MapColor.TEAL, 6), true);
		CINDER_CRYSTAL_BLOCK = ModBlocks.register("cinder_crystal_block", Block::new, crystalSettings(MapColor.ORANGE, 9), true);
		VERDIGRIS_CRYSTAL_BLOCK = ModBlocks.register("verdigris_crystal_block", Block::new, crystalSettings(MapColor.EMERALD_GREEN, 7), true);
		VERDIGRIS_LICHEN = ModBlocks.register("verdigris_lichen", GlowLichenBlock::new, AbstractBlock.Settings.create().mapColor(MapColor.TEAL).replaceable().noCollision().strength(0.2F).sounds(BlockSoundGroup.GLOW_LICHEN).luminance(GlowLichenBlock.getLuminanceSupplier(7)), true);

		// Worldgen wiring: the 25 garden placed features are appended to the three
		// Inferno biomes in ONE fixed order with ONE shared selector, so every biome
		// sees the identical appended subsequence and the FeatureSorter ordering stays
		// cycle-free (per-biome flavor comes from the ground-block predicates inside
		// the features, which are cheap no-ops on foreign terrain). Signatures verified
		// via javap: addFeature(Predicate<BiomeSelectionContext>,
		// GenerationStep.Feature, RegistryKey<PlacedFeature>).
		Predicate<BiomeSelectionContext> infernoBiomes = BiomeSelectors.includeByKey(
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("cinder_wastes")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("ember_grove")),
				RegistryKey.of(RegistryKeys.BIOME, CopperInferno.id("slag_sea")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_ember_lily")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_cinder_fern")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_sear_sprigs")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_molten_bud")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_ash_bramble")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_glow_tendrils")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_soot_puff")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_slag_thistle")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_pyre_reed")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_copper_rose")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_inferno_orchid")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_charred_shrub")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_gilded_clover")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("garden_wastes_mix")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("garden_grove_mix")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("garden_slag_mix")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ceiling_hanging_ember_roots")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("ceiling_ash_veils")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("wall_verdigris_lichen")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("cinder_crystal_cluster")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("verdigris_crystal_cluster")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.UNDERGROUND_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("buried_verdigris_crystal")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("giant_embercap")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("giant_gloomcap")));
		BiomeModifications.addFeature(infernoBiomes, GenerationStep.Feature.VEGETAL_DECORATION,
				RegistryKey.of(RegistryKeys.PLACED_FEATURE, CopperInferno.id("patch_ember_moss_carpet")));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.BLOCKS_KEY).register(entries -> {
			entries.add(EMBER_LILY);
			entries.add(CINDER_FERN);
			entries.add(SEAR_SPRIGS);
			entries.add(MOLTEN_BUD);
			entries.add(ASH_BRAMBLE);
			entries.add(GLOW_TENDRILS);
			entries.add(SOOT_PUFF);
			entries.add(SLAG_THISTLE);
			entries.add(PYRE_REED);
			entries.add(COPPER_ROSE);
			entries.add(INFERNO_ORCHID);
			entries.add(CHARRED_SHRUB);
			entries.add(GILDED_CLOVER);
			entries.add(HANGING_EMBER_ROOTS);
			entries.add(ASH_VEIL);
			entries.add(EMBERCAP_BLOCK);
			entries.add(GLOOMCAP_BLOCK);
			entries.add(CINDER_CRYSTAL_BLOCK);
			entries.add(VERDIGRIS_CRYSTAL_BLOCK);
			entries.add(VERDIGRIS_LICHEN);
		});

		InfernoGardensHandbook.register();
	}
}
