package net.sonic0810.copperinferno.feature.bosspantheon;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricDefaultAttributeRegistry;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.mob.BlazeEntity;
import net.minecraft.entity.mob.EvokerEntity;
import net.minecraft.entity.mob.GhastEntity;
import net.minecraft.entity.mob.HostileEntity;
import net.minecraft.entity.mob.VindicatorEntity;
import net.minecraft.entity.passive.IronGolemEntity;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModEntities;
import net.sonic0810.copperinferno.core.ModItems;
import net.sonic0810.copperinferno.core.handbook.HandbookEntries;
import net.sonic0810.copperinferno.core.handbook.HandbookEntry;

/**
 * v4 "Copper Pantheon" (WP13): six summonable ultra-bosses, each extending a vanilla mob
 * and carrying a boss bar (core.boss.BossBarHolder), two phases, a timed special and an
 * enrage/defensive stance - see the individual entity classes. Every boss has a crafted
 * summon item (shared {@link PantheonSummonItem}; recipes ring the Pantheon Relic
 * catalyst), two drops + one EPIC trophy (loot_table/entities/&lt;boss&gt;.json), a spawn
 * egg in the FAUNA tab and handbook lore + recipe entries. EntityType
 * dimensions/attachments are copied 1:1 from the vanilla registrations (bytecode-verified
 * via javap, chains quoted inline). Assets (item defs/models/textures, entity textures,
 * loot tables, recipes, lang fragments) are generated by
 * {@code devtools/gen/bosspantheon_gen.py}.
 */
public final class BossPantheonFeature {
	private BossPantheonFeature() {
	}

	public static EntityType<TheVerdigrisProphetEntity> THE_VERDIGRIS_PROPHET;
	public static EntityType<PatinaWardenEntity> PATINA_WARDEN;
	public static EntityType<CoilHydraEntity> COIL_HYDRA;
	public static EntityType<ThunderConductorEntity> THUNDER_CONDUCTOR;
	public static EntityType<TheMintKingEntity> THE_MINT_KING;
	public static EntityType<GildedExecutionerEntity> GILDED_EXECUTIONER;

	public static Item PANTHEON_RELIC;

	public static Item PROPHET_SIGIL;
	public static Item PATINA_CORE;
	public static Item HYDRA_SIGIL;
	public static Item CONDUCTOR_CORE;
	public static Item MINT_KING_CORE;
	public static Item EXECUTIONER_CORE;

	public static Item VERDIGRIS_TOME;
	public static Item CORRODED_FANG;
	public static Item PROPHETS_CIRCLET;
	public static Item PATINA_PLATE;
	public static Item WARDEN_RIVET;
	public static Item PATINA_AEGIS;
	public static Item COIL_SCALE;
	public static Item HYDRA_TEAR;
	public static Item HYDRA_DIADEM;
	public static Item STORM_ROD;
	public static Item CHARGED_FILAMENT;
	public static Item THUNDER_SCEPTER;
	public static Item ROYAL_JELLY;
	public static Item MINT_CRYSTAL;
	public static Item MINT_CROWN;
	public static Item GILDED_SCRAP;
	public static Item EXECUTIONER_PENDANT;
	public static Item GILDED_GREATAXE;

	public static Item THE_VERDIGRIS_PROPHET_SPAWN_EGG;
	public static Item PATINA_WARDEN_SPAWN_EGG;
	public static Item COIL_HYDRA_SPAWN_EGG;
	public static Item THUNDER_CONDUCTOR_SPAWN_EGG;
	public static Item THE_MINT_KING_SPAWN_EGG;
	public static Item GILDED_EXECUTIONER_SPAWN_EGG;

	public static void init() {
		registerEntityTypes();
		registerAttributes();
		registerItems();
		registerHandbookEntries();
	}

	private static void registerEntityTypes() {
		// Base dimension chains copied 1:1 from the vanilla EntityType registrations
		// (bytecode-verified via javap -c on EntityType's <clinit>); the bosses' bulk comes
		// from the SCALE attribute, and all six get maxTrackingRange(10) so the model/boss
		// bar appear well before the fight. Summoned bosses call setPersistent, so MISC
		// (no natural despawn logic) fits all of them - the proven infernoboss pattern.
		// evoker = dimensions(0.6f, 1.95f).passengerAttachments(2.0f).vehicleAttachment(-0.6f)
		// .maxTrackingRange(8).notAllowedInPeaceful()
		THE_VERDIGRIS_PROPHET = ModEntities.register("the_verdigris_prophet",
				EntityType.Builder.create(TheVerdigrisProphetEntity::new, SpawnGroup.MISC)
						.dimensions(0.6f, 1.95f)
						.passengerAttachments(2.0f)
						.vehicleAttachment(-0.6f)
						.maxTrackingRange(10));
		// iron_golem = dimensions(1.4f, 2.7f).maxTrackingRange(10)
		PATINA_WARDEN = ModEntities.register("patina_warden",
				EntityType.Builder.create(PatinaWardenEntity::new, SpawnGroup.MISC)
						.dimensions(1.4f, 2.7f)
						.maxTrackingRange(10));
		// ghast = makeFireImmune().dimensions(4.0f, 4.0f).eyeHeight(2.6f)
		// .passengerAttachments(4.0625f).vehicleAttachment(0.5f).maxTrackingRange(10)
		// .notAllowedInPeaceful()
		COIL_HYDRA = ModEntities.register("coil_hydra",
				EntityType.Builder.create(CoilHydraEntity::new, SpawnGroup.MISC)
						.makeFireImmune()
						.dimensions(4.0f, 4.0f)
						.eyeHeight(2.6f)
						.passengerAttachments(4.0625f)
						.vehicleAttachment(0.5f)
						.maxTrackingRange(10));
		// blaze = makeFireImmune().dimensions(0.6f, 1.8f).maxTrackingRange(8)
		// .notAllowedInPeaceful()
		THUNDER_CONDUCTOR = ModEntities.register("thunder_conductor",
				EntityType.Builder.create(ThunderConductorEntity::new, SpawnGroup.MISC)
						.makeFireImmune()
						.dimensions(0.6f, 1.8f)
						.maxTrackingRange(10));
		// slime = dimensions(0.52f, 0.52f).eyeHeight(0.325f).spawnBoxScale(4.0f)
		// .maxTrackingRange(10).notAllowedInPeaceful(); the royal bulk comes from the
		// forced slime SIZE 6 plus the SCALE attribute.
		THE_MINT_KING = ModEntities.register("the_mint_king",
				EntityType.Builder.create(TheMintKingEntity::new, SpawnGroup.MISC)
						.dimensions(0.52f, 0.52f)
						.eyeHeight(0.325f)
						.spawnBoxScale(4.0f)
						.maxTrackingRange(10));
		// vindicator = dimensions(0.6f, 1.95f).passengerAttachments(2.0f)
		// .vehicleAttachment(-0.6f).maxTrackingRange(8).notAllowedInPeaceful()
		GILDED_EXECUTIONER = ModEntities.register("gilded_executioner",
				EntityType.Builder.create(GildedExecutionerEntity::new, SpawnGroup.MISC)
						.dimensions(0.6f, 1.95f)
						.passengerAttachments(2.0f)
						.vehicleAttachment(-0.6f)
						.maxTrackingRange(10));
	}

	private static void registerAttributes() {
		// Every base creator verified via javap; EntityAttributes fields have no GENERIC_
		// prefix in 1.21.9 and DefaultAttributeContainer.Builder.add(...) overrides the base
		// values. MAX_HEALTH 280-500, SCALE 1.8-2.4, FOLLOW_RANGE 48-64 across the roster.
		FabricDefaultAttributeRegistry.register(THE_VERDIGRIS_PROPHET, EvokerEntity.createEvokerAttributes()
				.add(EntityAttributes.MAX_HEALTH, 300.0)
				.add(EntityAttributes.SCALE, 1.8)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(PATINA_WARDEN, IronGolemEntity.createIronGolemAttributes()
				.add(EntityAttributes.MAX_HEALTH, 450.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 17.0)
				.add(EntityAttributes.SCALE, 2.2)
				.add(EntityAttributes.KNOCKBACK_RESISTANCE, 1.0)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(COIL_HYDRA, GhastEntity.createGhastAttributes()
				.add(EntityAttributes.MAX_HEALTH, 320.0)
				.add(EntityAttributes.SCALE, 1.8)
				.add(EntityAttributes.FOLLOW_RANGE, 64.0));
		FabricDefaultAttributeRegistry.register(THUNDER_CONDUCTOR, BlazeEntity.createBlazeAttributes()
				.add(EntityAttributes.MAX_HEALTH, 280.0)
				.add(EntityAttributes.SCALE, 2.4)
				.add(EntityAttributes.FOLLOW_RANGE, 64.0));
		// Slimes have no dedicated creator (vanilla registers HostileEntity attributes and
		// derives stats from the size); TheMintKingEntity.setSize re-asserts the royal
		// statline on top of these bases.
		FabricDefaultAttributeRegistry.register(THE_MINT_KING, HostileEntity.createHostileAttributes()
				.add(EntityAttributes.MAX_HEALTH, 500.0)
				.add(EntityAttributes.SCALE, 1.8)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
		FabricDefaultAttributeRegistry.register(GILDED_EXECUTIONER, VindicatorEntity.createVindicatorAttributes()
				.add(EntityAttributes.MAX_HEALTH, 300.0)
				.add(EntityAttributes.ATTACK_DAMAGE, 14.0)
				.add(EntityAttributes.SCALE, 2.0)
				.add(EntityAttributes.FOLLOW_RANGE, 48.0));
	}

	private static void registerItems() {
		// Catalyst ringed by every summon recipe (unique-input rule by construction).
		PANTHEON_RELIC = ModItems.register("pantheon_relic", Item::new,
				new Item.Settings().rarity(Rarity.RARE));

		// Summon items: entity types are registered above, so direct references are safe.
		PROPHET_SIGIL = ModItems.register("prophet_sigil",
				settings -> new PantheonSummonItem(THE_VERDIGRIS_PROPHET, settings), new Item.Settings());
		PATINA_CORE = ModItems.register("patina_core",
				settings -> new PantheonSummonItem(PATINA_WARDEN, settings), new Item.Settings());
		HYDRA_SIGIL = ModItems.register("hydra_sigil",
				settings -> new PantheonSummonItem(COIL_HYDRA, settings), new Item.Settings());
		CONDUCTOR_CORE = ModItems.register("conductor_core",
				settings -> new PantheonSummonItem(THUNDER_CONDUCTOR, settings), new Item.Settings());
		MINT_KING_CORE = ModItems.register("mint_king_core",
				settings -> new PantheonSummonItem(THE_MINT_KING, settings), new Item.Settings());
		EXECUTIONER_CORE = ModItems.register("executioner_core",
				settings -> new PantheonSummonItem(GILDED_EXECUTIONER, settings), new Item.Settings());

		// Boss drops (2 per boss) + one EPIC trophy each (Item.Settings.rarity via javap).
		VERDIGRIS_TOME = ModItems.register("verdigris_tome", Item::new, new Item.Settings());
		CORRODED_FANG = ModItems.register("corroded_fang", Item::new, new Item.Settings());
		PROPHETS_CIRCLET = ModItems.register("prophets_circlet", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		PATINA_PLATE = ModItems.register("patina_plate", Item::new, new Item.Settings());
		WARDEN_RIVET = ModItems.register("warden_rivet", Item::new, new Item.Settings());
		PATINA_AEGIS = ModItems.register("patina_aegis", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		COIL_SCALE = ModItems.register("coil_scale", Item::new, new Item.Settings());
		HYDRA_TEAR = ModItems.register("hydra_tear", Item::new, new Item.Settings());
		HYDRA_DIADEM = ModItems.register("hydra_diadem", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		STORM_ROD = ModItems.register("storm_rod", Item::new, new Item.Settings());
		CHARGED_FILAMENT = ModItems.register("charged_filament", Item::new, new Item.Settings());
		THUNDER_SCEPTER = ModItems.register("thunder_scepter", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		ROYAL_JELLY = ModItems.register("royal_jelly", Item::new, new Item.Settings());
		MINT_CRYSTAL = ModItems.register("mint_crystal", Item::new, new Item.Settings());
		MINT_CROWN = ModItems.register("mint_crown", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));
		GILDED_SCRAP = ModItems.register("gilded_scrap", Item::new, new Item.Settings());
		EXECUTIONER_PENDANT = ModItems.register("executioner_pendant", Item::new, new Item.Settings());
		GILDED_GREATAXE = ModItems.register("gilded_greataxe", Item::new,
				new Item.Settings().rarity(Rarity.EPIC));

		// Item.Settings.spawnEgg(type) stores the ENTITY_DATA component the vanilla
		// SpawnEggItem reads its entity type from in 1.21.9 (dr_pepper_golem pattern).
		THE_VERDIGRIS_PROPHET_SPAWN_EGG = ModItems.register("the_verdigris_prophet_spawn_egg",
				SpawnEggItem::new, new Item.Settings().spawnEgg(THE_VERDIGRIS_PROPHET));
		PATINA_WARDEN_SPAWN_EGG = ModItems.register("patina_warden_spawn_egg",
				SpawnEggItem::new, new Item.Settings().spawnEgg(PATINA_WARDEN));
		COIL_HYDRA_SPAWN_EGG = ModItems.register("coil_hydra_spawn_egg",
				SpawnEggItem::new, new Item.Settings().spawnEgg(COIL_HYDRA));
		THUNDER_CONDUCTOR_SPAWN_EGG = ModItems.register("thunder_conductor_spawn_egg",
				SpawnEggItem::new, new Item.Settings().spawnEgg(THUNDER_CONDUCTOR));
		THE_MINT_KING_SPAWN_EGG = ModItems.register("the_mint_king_spawn_egg",
				SpawnEggItem::new, new Item.Settings().spawnEgg(THE_MINT_KING));
		GILDED_EXECUTIONER_SPAWN_EGG = ModItems.register("gilded_executioner_spawn_egg",
				SpawnEggItem::new, new Item.Settings().spawnEgg(GILDED_EXECUTIONER));

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.MAIN_KEY).register(entries -> {
			// Catalyst, then per boss: summon item, drops, trophy.
			entries.add(PANTHEON_RELIC);
			entries.add(PROPHET_SIGIL);
			entries.add(VERDIGRIS_TOME);
			entries.add(CORRODED_FANG);
			entries.add(PROPHETS_CIRCLET);
			entries.add(PATINA_CORE);
			entries.add(PATINA_PLATE);
			entries.add(WARDEN_RIVET);
			entries.add(PATINA_AEGIS);
			entries.add(HYDRA_SIGIL);
			entries.add(COIL_SCALE);
			entries.add(HYDRA_TEAR);
			entries.add(HYDRA_DIADEM);
			entries.add(CONDUCTOR_CORE);
			entries.add(STORM_ROD);
			entries.add(CHARGED_FILAMENT);
			entries.add(THUNDER_SCEPTER);
			entries.add(MINT_KING_CORE);
			entries.add(ROYAL_JELLY);
			entries.add(MINT_CRYSTAL);
			entries.add(MINT_CROWN);
			entries.add(EXECUTIONER_CORE);
			entries.add(GILDED_SCRAP);
			entries.add(EXECUTIONER_PENDANT);
			entries.add(GILDED_GREATAXE);
		});
		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.FAUNA_KEY).register(entries -> {
			// Spawn eggs in roster order.
			entries.add(THE_VERDIGRIS_PROPHET_SPAWN_EGG);
			entries.add(PATINA_WARDEN_SPAWN_EGG);
			entries.add(COIL_HYDRA_SPAWN_EGG);
			entries.add(THUNDER_CONDUCTOR_SPAWN_EGG);
			entries.add(THE_MINT_KING_SPAWN_EGG);
			entries.add(GILDED_EXECUTIONER_SPAWN_EGG);
		});
	}

	private static void registerHandbookEntries() {
		// Lore entry per boss (icon = spawn egg), then the catalyst + summon-item recipes.
		HandbookEntries.add(new HandbookEntry("bosses", "the_verdigris_prophet",
				"copper_inferno:the_verdigris_prophet_spawn_egg", null, null, null, 0,
				"The Verdigris Prophet - a corrosion-preaching evoker. Summon: use a Prophet Sigil. He curses everyone he can see within 8 blocks (Slowness, Weakness, Mining Fatigue), conjures double rings of fangs around his prey, and below half health his sermon quickens - both abilities twice as fast, plus a retaliatory fang ring. Drops Verdigris Tomes, Corroded Fangs and the Prophet's Circlet.",
				"Der Grünspan-Prophet - ein korrosionspredigender Magier. Beschwörung: ein Prophetensiegel benutzen. Er verflucht jeden, den er im Umkreis von 8 Blöcken sieht (Langsamkeit, Schwäche, Abbaulähmung), beschwört doppelte Fangzahnringe um seine Beute, und unter halber Gesundheit beschleunigt sich seine Predigt - beide Fähigkeiten doppelt so schnell, plus ein Vergeltungsring. Lässt Grünspanfolianten, Korrodierte Fangzähne und das Diadem des Propheten fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "patina_warden",
				"copper_inferno:patina_warden_spawn_egg", null, null, null, 0,
				"Patina Warden - a colossal oxidized golem. Summon: use a Patina Core. Every 15 seconds it raises a patina shield for 5 seconds: incoming damage drops to a quarter and half of it is reflected back at the attacker. Below half health it enrages and raises the shield more often. Never try to heal it with iron. Drops Patina Plates, Warden Rivets and the Patina Aegis.",
				"Patina-Wächter - ein kolossaler oxidierter Golem. Beschwörung: einen Patina-Kern benutzen. Alle 15 Sekunden hebt er für 5 Sekunden einen Patinaschild: eingehender Schaden sinkt auf ein Viertel und die Hälfte davon wird auf den Angreifer zurückgeworfen. Unter halber Gesundheit wird er rasend und schildet öfter. Versuche nie, ihn mit Eisen zu heilen. Lässt Patinaplatten, Wächternieten und die Patina-Ägide fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "coil_hydra",
				"copper_inferno:coil_hydra_spawn_egg", null, null, null, 0,
				"Coil Hydra - a many-throated coil ghast. Summon: use a Hydra Sigil. It fires fanned volleys of fireballs around one large mother fireball that SPLITS mid-flight into four more. Below half health it hardens with Resistance and spits five-headed volleys even faster. Drops Coil Scales, Hydra Tears and the Hydra Diadem.",
				"Spulen-Hydra - ein vielkehliger Spulen-Ghast. Beschwörung: ein Hydrasiegel benutzen. Sie feuert gefächerte Feuerballsalven um einen großen Mutterfeuerball, der sich im Flug in vier weitere TEILT. Unter halber Gesundheit härtet sie sich mit Resistenz und spuckt fünfköpfige Salven noch schneller. Lässt Spulenschuppen, Hydratränen und das Hydra-Diadem fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "thunder_conductor",
				"copper_inferno:thunder_conductor_spawn_egg", null, null, null, 0,
				"Thunder Conductor - a storm-wired blaze lord. Summon: use a Conductor Core. It drops real lightning on its target, statically shocks anyone who stands too close, and its aura SUPER-CHARGES every creeper within 8 blocks - keep them apart! Below half health the strikes come twice as fast. Drops Storm Rods, Charged Filaments and the Thunder Scepter.",
				"Donnerleiter - ein sturmverdrahteter Lohenfürst. Beschwörung: einen Leiterkern benutzen. Er lässt echte Blitze auf sein Ziel fallen, verpasst jedem in seiner Nähe Stromschläge, und seine Aura ÜBERLÄDT jeden Creeper im Umkreis von 8 Blöcken - halte sie fern! Unter halber Gesundheit schlagen die Blitze doppelt so schnell ein. Lässt Sturmruten, Geladene Filamente und das Donnerzepter fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "the_mint_king",
				"copper_inferno:the_mint_king_spawn_egg", null, null, null, 0,
				"The Mint King - a monarch-sized mint slime. Summon: use a Mint King Core. His brain-freeze burst slows everyone within 6 blocks; below half health two elite honor guards leap out and his hops quicken. On death he does not shrink - he SPLITS into four elite slimes. Drops Royal Jellies, Mint Crystals and the Mint Crown.",
				"Der Minzkönig - ein monarchengroßer Minzschleim. Beschwörung: einen Minzkönig-Kern benutzen. Sein Hirnfrost-Stoß verlangsamt jeden im Umkreis von 6 Blöcken; unter halber Gesundheit springen zwei Elite-Ehrengarden heraus und seine Sprünge werden schneller. Beim Tod schrumpft er nicht - er TEILT sich in vier Elite-Schleime. Lässt Königsgelee, Minzkristalle und die Minzkrone fallen."));
		HandbookEntries.add(new HandbookEntry("bosses", "gilded_executioner",
				"copper_inferno:gilded_executioner_spawn_egg", null, null, null, 0,
				"Gilded Executioner - a gold-plated headsman. Summon: use an Executioner Core. He dashes at distant prey in a burst of gold dust, and every fourth axe blow DISARMS you - your weapon flies to the ground. Below half health he enrages and dashes relentlessly. Drops Gilded Scraps, Executioner Pendants and the Gilded Greataxe.",
				"Vergoldeter Scharfrichter - ein goldbeschlagener Henker. Beschwörung: einen Scharfrichter-Kern benutzen. Er stürmt in einer goldenen Staubwolke auf ferne Beute, und jeder vierte Axthieb ENTWAFFNET dich - deine Waffe fliegt zu Boden. Unter halber Gesundheit wird er rasend und stürmt unerbittlich. Lässt Vergoldeten Schrott, Scharfrichter-Anhänger und die Vergoldete Großaxt fallen."));

		HandbookEntries.add(new HandbookEntry("bosses", "pantheon_relic_recipe",
				"copper_inferno:pantheon_relic", "bosspantheon/pantheon_relic",
				new String[] {
						"minecraft:copper_ingot", "minecraft:amethyst_shard", "minecraft:copper_ingot",
						"minecraft:amethyst_shard", "minecraft:diamond", "minecraft:amethyst_shard",
						"minecraft:copper_ingot", "minecraft:amethyst_shard", "minecraft:copper_ingot"},
				"copper_inferno:pantheon_relic", 1,
				"Pantheon Relic - ring a Diamond with 4 Copper Ingots and 4 Amethyst Shards. The catalyst at the heart of every pantheon summon item.",
				"Pantheon-Reliquie - einen Diamanten mit 4 Kupferbarren und 4 Amethystscherben umringen. Der Katalysator im Herzen jedes Pantheon-Beschwörungsgegenstands."));
		HandbookEntries.add(new HandbookEntry("bosses", "prophet_sigil_recipe",
				"copper_inferno:prophet_sigil", "bosspantheon/prophet_sigil",
				new String[] {
						"minecraft:oxidized_copper", "minecraft:emerald", "minecraft:oxidized_copper",
						"minecraft:emerald", "copper_inferno:pantheon_relic", "minecraft:emerald",
						"minecraft:oxidized_copper", "minecraft:emerald", "minecraft:oxidized_copper"},
				"copper_inferno:prophet_sigil", 1,
				"Prophet Sigil - ring a Pantheon Relic with 4 Oxidized Copper and 4 Emeralds. Use it to summon The Verdigris Prophet.",
				"Prophetensiegel - eine Pantheon-Reliquie mit 4 Oxidiertem Kupfer und 4 Smaragden umringen. Benutzen, um den Grünspan-Propheten zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "patina_core_recipe",
				"copper_inferno:patina_core", "bosspantheon/patina_core",
				new String[] {
						"minecraft:cut_copper", "minecraft:iron_ingot", "minecraft:cut_copper",
						"minecraft:iron_ingot", "copper_inferno:pantheon_relic", "minecraft:iron_ingot",
						"minecraft:cut_copper", "minecraft:iron_ingot", "minecraft:cut_copper"},
				"copper_inferno:patina_core", 1,
				"Patina Core - ring a Pantheon Relic with 4 Cut Copper and 4 Iron Ingots. Use it to summon the Patina Warden.",
				"Patina-Kern - eine Pantheon-Reliquie mit 4 Geschnittenem Kupfer und 4 Eisenbarren umringen. Benutzen, um den Patina-Wächter zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "hydra_sigil_recipe",
				"copper_inferno:hydra_sigil", "bosspantheon/hydra_sigil",
				new String[] {
						"minecraft:fire_charge", "minecraft:ghast_tear", "minecraft:fire_charge",
						"minecraft:ghast_tear", "copper_inferno:pantheon_relic", "minecraft:ghast_tear",
						"minecraft:fire_charge", "minecraft:ghast_tear", "minecraft:fire_charge"},
				"copper_inferno:hydra_sigil", 1,
				"Hydra Sigil - ring a Pantheon Relic with 4 Fire Charges and 4 Ghast Tears. Use it to summon the Coil Hydra.",
				"Hydrasiegel - eine Pantheon-Reliquie mit 4 Feuerkugeln und 4 Ghast-Tränen umringen. Benutzen, um die Spulen-Hydra zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "conductor_core_recipe",
				"copper_inferno:conductor_core", "bosspantheon/conductor_core",
				new String[] {
						"minecraft:lightning_rod", "minecraft:blaze_rod", "minecraft:lightning_rod",
						"minecraft:blaze_rod", "copper_inferno:pantheon_relic", "minecraft:blaze_rod",
						"minecraft:lightning_rod", "minecraft:blaze_rod", "minecraft:lightning_rod"},
				"copper_inferno:conductor_core", 1,
				"Conductor Core - ring a Pantheon Relic with 4 Lightning Rods and 4 Blaze Rods. Use it to summon the Thunder Conductor.",
				"Leiterkern - eine Pantheon-Reliquie mit 4 Blitzableitern und 4 Lohenruten umringen. Benutzen, um den Donnerleiter zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "mint_king_core_recipe",
				"copper_inferno:mint_king_core", "bosspantheon/mint_king_core",
				new String[] {
						"minecraft:slime_ball", "minecraft:sugar", "minecraft:slime_ball",
						"minecraft:sugar", "copper_inferno:pantheon_relic", "minecraft:sugar",
						"minecraft:slime_ball", "minecraft:sugar", "minecraft:slime_ball"},
				"copper_inferno:mint_king_core", 1,
				"Mint King Core - ring a Pantheon Relic with 4 Slimeballs and 4 Sugar. Use it to summon The Mint King.",
				"Minzkönig-Kern - eine Pantheon-Reliquie mit 4 Schleimbällen und 4 Zucker umringen. Benutzen, um den Minzkönig zu beschwören."));
		HandbookEntries.add(new HandbookEntry("bosses", "executioner_core_recipe",
				"copper_inferno:executioner_core", "bosspantheon/executioner_core",
				new String[] {
						"minecraft:gold_ingot", "minecraft:gold_nugget", "minecraft:gold_ingot",
						"minecraft:gold_nugget", "copper_inferno:pantheon_relic", "minecraft:gold_nugget",
						"minecraft:gold_ingot", "minecraft:gold_nugget", "minecraft:gold_ingot"},
				"copper_inferno:executioner_core", 1,
				"Executioner Core - ring a Pantheon Relic with 4 Gold Ingots and 4 Gold Nuggets. Use it to summon the Gilded Executioner.",
				"Scharfrichter-Kern - eine Pantheon-Reliquie mit 4 Goldbarren und 4 Goldklumpen umringen. Benutzen, um den Vergoldeten Scharfrichter zu beschwören."));
	}
}
