package net.sonic0810.copperinferno.feature.infernofauna.client;

import net.minecraft.client.render.entity.BatEntityRenderer;
import net.minecraft.client.render.entity.CaveSpiderEntityRenderer;
import net.minecraft.client.render.entity.EndermiteEntityRenderer;
import net.minecraft.client.render.entity.EntityRendererFactories;
import net.minecraft.client.render.entity.EntityRendererFactory;
import net.minecraft.client.render.entity.FrogEntityRenderer;
import net.minecraft.client.render.entity.GhastEntityRenderer;
import net.minecraft.client.render.entity.GoatEntityRenderer;
import net.minecraft.client.render.entity.GuardianEntityRenderer;
import net.minecraft.client.render.entity.HoglinEntityRenderer;
import net.minecraft.client.render.entity.HuskEntityRenderer;
import net.minecraft.client.render.entity.IronGolemEntityRenderer;
import net.minecraft.client.render.entity.MagmaCubeEntityRenderer;
import net.minecraft.client.render.entity.ParrotEntityRenderer;
import net.minecraft.client.render.entity.PhantomEntityRenderer;
import net.minecraft.client.render.entity.PigEntityRenderer;
import net.minecraft.client.render.entity.SheepEntityRenderer;
import net.minecraft.client.render.entity.SilverfishEntityRenderer;
import net.minecraft.client.render.entity.SpiderEntityRenderer;
import net.minecraft.client.render.entity.StriderEntityRenderer;
import net.minecraft.client.render.entity.TurtleEntityRenderer;
import net.minecraft.client.render.entity.VexEntityRenderer;
import net.minecraft.client.render.entity.WolfEntityRenderer;
import net.minecraft.client.render.entity.state.BatEntityRenderState;
import net.minecraft.client.render.entity.state.FrogEntityRenderState;
import net.minecraft.client.render.entity.state.GhastEntityRenderState;
import net.minecraft.client.render.entity.state.GoatEntityRenderState;
import net.minecraft.client.render.entity.state.GuardianEntityRenderState;
import net.minecraft.client.render.entity.state.HoglinEntityRenderState;
import net.minecraft.client.render.entity.state.IronGolemEntityRenderState;
import net.minecraft.client.render.entity.state.LivingEntityRenderState;
import net.minecraft.client.render.entity.state.ParrotEntityRenderState;
import net.minecraft.client.render.entity.state.PhantomEntityRenderState;
import net.minecraft.client.render.entity.state.PigEntityRenderState;
import net.minecraft.client.render.entity.state.SheepEntityRenderState;
import net.minecraft.client.render.entity.state.SlimeEntityRenderState;
import net.minecraft.client.render.entity.state.StriderEntityRenderState;
import net.minecraft.client.render.entity.state.TurtleEntityRenderState;
import net.minecraft.client.render.entity.state.VexEntityRenderState;
import net.minecraft.client.render.entity.state.WolfEntityRenderState;
import net.minecraft.client.render.entity.state.ZombieEntityRenderState;
import net.minecraft.entity.mob.SpiderEntity;
import net.minecraft.util.Identifier;
import net.sonic0810.copperinferno.CopperInferno;
import net.sonic0810.copperinferno.feature.infernofauna.InfernoFaunaFeature;

/**
 * Client-side setup for the Inferno Wildlife mobs: every type reuses its vanilla renderer
 * subclassed ONLY to swap the texture — each subclass overrides the renderer's
 * {@code getTexture(<state>)} (exact state parameter type verified via javap per renderer:
 * SlimeEntityRenderState for magma cubes, ZombieEntityRenderState for husks,
 * LivingEntityRenderState for silverfish/spider/cave spider/endermite, and the entity-specific
 * states for the rest) to return a recolored copy of the vanilla entity texture generated by
 * {@code devtools/gen/infernofauna_gen.py} into
 * {@code assets/copper_inferno/textures/entity/infernofauna/}. All vanilla renderer ctors used
 * here are Context-only (javap-verified); the mobs extend the matching vanilla entities, so the
 * factories fit the {@code register(EntityType<? extends T>, EntityRendererFactory<T>)} bound
 * (vanilla register is access-widened by Fabric's transitive access wideners — the same proven
 * pattern as the Dr.Pepper golem and the infernomobs feature).
 *
 * <p>Texture-override caveats (accepted): feature layers keep their vanilla textures — the
 * soot sheep's wool overlay (tinted black via the BLACK DyeColor anyway), the char phantom's
 * glowing eyes, the pyroclast golem's crackiness layer and the glow strider's saddle.
 */
public final class InfernoFaunaFeatureClient {
	private InfernoFaunaFeatureClient() {
	}

	private static Identifier tex(String mob) {
		return CopperInferno.id("textures/entity/infernofauna/" + mob + ".png");
	}

	public static void initClient() {
		EntityRendererFactories.register(InfernoFaunaFeature.MAGMA_HOPPER, MagmaHopperRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.CINDER_HOUND, CinderHoundRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.EMBER_MOTH, EmberMothRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.SLAG_SNAIL, SlagSnailRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.PYRE_RAVEN,
				ctx -> new FaunaParrotRenderer(ctx, tex("pyre_raven")));
		EntityRendererFactories.register(InfernoFaunaFeature.ASH_STALKER,
				ctx -> new FaunaSpiderRenderer(ctx, tex("ash_stalker")));
		EntityRendererFactories.register(InfernoFaunaFeature.FUMAROLE_FROG,
				ctx -> new FaunaFrogRenderer(ctx, tex("fumarole_frog")));
		EntityRendererFactories.register(InfernoFaunaFeature.SOOT_PIGLET, SootPigletRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.SCORCH_GOAT, ScorchGoatRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.LAVA_EEL, LavaEelRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.EMBER_OWL,
				ctx -> new FaunaParrotRenderer(ctx, tex("ember_owl")));
		EntityRendererFactories.register(InfernoFaunaFeature.CINDER_TOAD,
				ctx -> new FaunaFrogRenderer(ctx, tex("cinder_toad")));
		EntityRendererFactories.register(InfernoFaunaFeature.FLARE_WISP, FlareWispRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.SMOLDER_TORTOISE, SmolderTortoiseRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.BRIMSTONE_BULL, BrimstoneBullRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.ASH_WANDERER, AshWandererRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.PYROCLAST_GOLEM, PyroclastGolemRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.EMBER_SERPENT, EmberSerpentRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.SOOT_SHEEP, SootSheepRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.GLOW_STRIDER, GlowStriderRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.KILN_SPIDER,
				ctx -> new FaunaSpiderRenderer(ctx, tex("kiln_spider")));
		EntityRendererFactories.register(InfernoFaunaFeature.CHAR_PHANTOM, CharPhantomRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.MOLTEN_MITE, MoltenMiteRenderer::new);
		EntityRendererFactories.register(InfernoFaunaFeature.INFERNO_GHASTLING, InfernoGhastlingRenderer::new);
	}

	private static final class MagmaHopperRenderer extends MagmaCubeEntityRenderer {
		private static final Identifier TEXTURE = tex("magma_hopper");

		MagmaHopperRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(SlimeEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class CinderHoundRenderer extends WolfEntityRenderer {
		private static final Identifier TEXTURE = tex("cinder_hound");

		CinderHoundRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(WolfEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class EmberMothRenderer extends BatEntityRenderer {
		private static final Identifier TEXTURE = tex("ember_moth");

		EmberMothRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(BatEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class SlagSnailRenderer extends SilverfishEntityRenderer {
		private static final Identifier TEXTURE = tex("slag_snail");

		SlagSnailRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(LivingEntityRenderState state) {
			return TEXTURE;
		}
	}

	/** Shared by the Pyre Raven and Ember Owl (both parrot-based). */
	private static final class FaunaParrotRenderer extends ParrotEntityRenderer {
		private final Identifier texture;

		FaunaParrotRenderer(EntityRendererFactory.Context context, Identifier texture) {
			super(context);
			this.texture = texture;
		}

		@Override
		public Identifier getTexture(ParrotEntityRenderState state) {
			return texture;
		}
	}

	/** Shared by the Ash Stalker and Kiln Spider (both spider-based). */
	private static final class FaunaSpiderRenderer extends SpiderEntityRenderer<SpiderEntity> {
		private final Identifier texture;

		FaunaSpiderRenderer(EntityRendererFactory.Context context, Identifier texture) {
			super(context);
			this.texture = texture;
		}

		@Override
		public Identifier getTexture(LivingEntityRenderState state) {
			return texture;
		}
	}

	/** Shared by the Fumarole Frog and Cinder Toad (both frog-based). */
	private static final class FaunaFrogRenderer extends FrogEntityRenderer {
		private final Identifier texture;

		FaunaFrogRenderer(EntityRendererFactory.Context context, Identifier texture) {
			super(context);
			this.texture = texture;
		}

		@Override
		public Identifier getTexture(FrogEntityRenderState state) {
			return texture;
		}
	}

	private static final class SootPigletRenderer extends PigEntityRenderer {
		private static final Identifier TEXTURE = tex("soot_piglet");

		SootPigletRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(PigEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class ScorchGoatRenderer extends GoatEntityRenderer {
		private static final Identifier TEXTURE = tex("scorch_goat");

		ScorchGoatRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(GoatEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class LavaEelRenderer extends GuardianEntityRenderer {
		private static final Identifier TEXTURE = tex("lava_eel");

		LavaEelRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(GuardianEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class FlareWispRenderer extends VexEntityRenderer {
		private static final Identifier TEXTURE = tex("flare_wisp");

		FlareWispRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(VexEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class SmolderTortoiseRenderer extends TurtleEntityRenderer {
		private static final Identifier TEXTURE = tex("smolder_tortoise");

		SmolderTortoiseRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(TurtleEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class BrimstoneBullRenderer extends HoglinEntityRenderer {
		private static final Identifier TEXTURE = tex("brimstone_bull");

		BrimstoneBullRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(HoglinEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class AshWandererRenderer extends HuskEntityRenderer {
		private static final Identifier TEXTURE = tex("ash_wanderer");

		AshWandererRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(ZombieEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class PyroclastGolemRenderer extends IronGolemEntityRenderer {
		private static final Identifier TEXTURE = tex("pyroclast_golem");

		PyroclastGolemRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(IronGolemEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class EmberSerpentRenderer extends CaveSpiderEntityRenderer {
		private static final Identifier TEXTURE = tex("ember_serpent");

		EmberSerpentRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(LivingEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class SootSheepRenderer extends SheepEntityRenderer {
		private static final Identifier TEXTURE = tex("soot_sheep");

		SootSheepRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(SheepEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class GlowStriderRenderer extends StriderEntityRenderer {
		private static final Identifier TEXTURE = tex("glow_strider");

		GlowStriderRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(StriderEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class CharPhantomRenderer extends PhantomEntityRenderer {
		private static final Identifier TEXTURE = tex("char_phantom");

		CharPhantomRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(PhantomEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class MoltenMiteRenderer extends EndermiteEntityRenderer {
		private static final Identifier TEXTURE = tex("molten_mite");

		MoltenMiteRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(LivingEntityRenderState state) {
			return TEXTURE;
		}
	}

	private static final class InfernoGhastlingRenderer extends GhastEntityRenderer {
		private static final Identifier TEXTURE = tex("inferno_ghastling");

		InfernoGhastlingRenderer(EntityRendererFactory.Context context) {
			super(context);
		}

		@Override
		public Identifier getTexture(GhastEntityRenderState state) {
			return TEXTURE;
		}
	}
}
