package net.sonic0810.copperinferno.feature.nightslate;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.sonic0810.copperinferno.core.ModBlockFamilies;
import net.sonic0810.copperinferno.core.ModBlockFamilies.BlockFamily;
import net.sonic0810.copperinferno.core.ModBlocks;
import net.sonic0810.copperinferno.core.ModCreativeTab;

/**
 * Nightslate block set: 224 building blocks across 14 dark volcanic stone materials
 * (nightslate, voidbasalt, duskstone, gloomstone, shadow tuff, umbral deepslate,
 * blacksoot stone, char obsidian, dark pumice, ebonstone, murkrock, cinderdark stone,
 * netherveil stone, obscura stone). Each material ships three full cube families
 * (base, polished, bricks; each base/slab/stairs/wall) plus tiles, cracked bricks,
 * chiseled bricks and a pillar.
 *
 * <p>Assets (blockstates, models, textures, item definitions, loot tables, recipes,
 * EN+DE lang fragments) are generated by {@code devtools/gen/nightslate_gen.py}; the
 * tag fragment lives at {@code devtools/tagfrag/nightslate.json}; handbook pages are
 * registered by {@link NightslateHandbook}.
 */
public final class NightslateFeature {
	private NightslateFeature() {
	}

	// Full cube families (base + slab + stairs + wall).
	public static BlockFamily NIGHTSLATE;
	public static BlockFamily POLISHED_NIGHTSLATE;
	public static BlockFamily NIGHTSLATE_BRICKS;
	public static BlockFamily VOIDBASALT;
	public static BlockFamily POLISHED_VOIDBASALT;
	public static BlockFamily VOIDBASALT_BRICKS;
	public static BlockFamily DUSKSTONE;
	public static BlockFamily POLISHED_DUSKSTONE;
	public static BlockFamily DUSKSTONE_BRICKS;
	public static BlockFamily GLOOMSTONE;
	public static BlockFamily POLISHED_GLOOMSTONE;
	public static BlockFamily GLOOMSTONE_BRICKS;
	public static BlockFamily SHADOW_TUFF;
	public static BlockFamily POLISHED_SHADOW_TUFF;
	public static BlockFamily SHADOW_TUFF_BRICKS;
	public static BlockFamily UMBRAL_DEEPSLATE;
	public static BlockFamily POLISHED_UMBRAL_DEEPSLATE;
	public static BlockFamily UMBRAL_DEEPSLATE_BRICKS;
	public static BlockFamily BLACKSOOT_STONE;
	public static BlockFamily POLISHED_BLACKSOOT_STONE;
	public static BlockFamily BLACKSOOT_STONE_BRICKS;
	public static BlockFamily CHAR_OBSIDIAN;
	public static BlockFamily POLISHED_CHAR_OBSIDIAN;
	public static BlockFamily CHAR_OBSIDIAN_BRICKS;
	public static BlockFamily DARK_PUMICE;
	public static BlockFamily POLISHED_DARK_PUMICE;
	public static BlockFamily DARK_PUMICE_BRICKS;
	public static BlockFamily EBONSTONE;
	public static BlockFamily POLISHED_EBONSTONE;
	public static BlockFamily EBONSTONE_BRICKS;
	public static BlockFamily MURKROCK;
	public static BlockFamily POLISHED_MURKROCK;
	public static BlockFamily MURKROCK_BRICKS;
	public static BlockFamily CINDERDARK_STONE;
	public static BlockFamily POLISHED_CINDERDARK_STONE;
	public static BlockFamily CINDERDARK_STONE_BRICKS;
	public static BlockFamily NETHERVEIL_STONE;
	public static BlockFamily POLISHED_NETHERVEIL_STONE;
	public static BlockFamily NETHERVEIL_STONE_BRICKS;
	public static BlockFamily OBSCURA_STONE;
	public static BlockFamily POLISHED_OBSCURA_STONE;
	public static BlockFamily OBSCURA_STONE_BRICKS;

	// Single blocks.
	public static Block NIGHTSLATE_TILES;
	public static Block CRACKED_NIGHTSLATE_BRICKS;
	public static Block CHISELED_NIGHTSLATE_BRICKS;
	public static Block NIGHTSLATE_PILLAR;
	public static Block VOIDBASALT_TILES;
	public static Block CRACKED_VOIDBASALT_BRICKS;
	public static Block CHISELED_VOIDBASALT_BRICKS;
	public static Block VOIDBASALT_PILLAR;
	public static Block DUSKSTONE_TILES;
	public static Block CRACKED_DUSKSTONE_BRICKS;
	public static Block CHISELED_DUSKSTONE_BRICKS;
	public static Block DUSKSTONE_PILLAR;
	public static Block GLOOMSTONE_TILES;
	public static Block CRACKED_GLOOMSTONE_BRICKS;
	public static Block CHISELED_GLOOMSTONE_BRICKS;
	public static Block GLOOMSTONE_PILLAR;
	public static Block SHADOW_TUFF_TILES;
	public static Block CRACKED_SHADOW_TUFF_BRICKS;
	public static Block CHISELED_SHADOW_TUFF_BRICKS;
	public static Block SHADOW_TUFF_PILLAR;
	public static Block UMBRAL_DEEPSLATE_TILES;
	public static Block CRACKED_UMBRAL_DEEPSLATE_BRICKS;
	public static Block CHISELED_UMBRAL_DEEPSLATE_BRICKS;
	public static Block UMBRAL_DEEPSLATE_PILLAR;
	public static Block BLACKSOOT_STONE_TILES;
	public static Block CRACKED_BLACKSOOT_STONE_BRICKS;
	public static Block CHISELED_BLACKSOOT_STONE_BRICKS;
	public static Block BLACKSOOT_STONE_PILLAR;
	public static Block CHAR_OBSIDIAN_TILES;
	public static Block CRACKED_CHAR_OBSIDIAN_BRICKS;
	public static Block CHISELED_CHAR_OBSIDIAN_BRICKS;
	public static Block CHAR_OBSIDIAN_PILLAR;
	public static Block DARK_PUMICE_TILES;
	public static Block CRACKED_DARK_PUMICE_BRICKS;
	public static Block CHISELED_DARK_PUMICE_BRICKS;
	public static Block DARK_PUMICE_PILLAR;
	public static Block EBONSTONE_TILES;
	public static Block CRACKED_EBONSTONE_BRICKS;
	public static Block CHISELED_EBONSTONE_BRICKS;
	public static Block EBONSTONE_PILLAR;
	public static Block MURKROCK_TILES;
	public static Block CRACKED_MURKROCK_BRICKS;
	public static Block CHISELED_MURKROCK_BRICKS;
	public static Block MURKROCK_PILLAR;
	public static Block CINDERDARK_STONE_TILES;
	public static Block CRACKED_CINDERDARK_STONE_BRICKS;
	public static Block CHISELED_CINDERDARK_STONE_BRICKS;
	public static Block CINDERDARK_STONE_PILLAR;
	public static Block NETHERVEIL_STONE_TILES;
	public static Block CRACKED_NETHERVEIL_STONE_BRICKS;
	public static Block CHISELED_NETHERVEIL_STONE_BRICKS;
	public static Block NETHERVEIL_STONE_PILLAR;
	public static Block OBSCURA_STONE_TILES;
	public static Block CRACKED_OBSCURA_STONE_BRICKS;
	public static Block CHISELED_OBSCURA_STONE_BRICKS;
	public static Block OBSCURA_STONE_PILLAR;

	/**
	 * Fresh settings per block ({@link ModBlocks#register} writes a registry key into the
	 * instance, so settings must never be shared). Requires-tool dark stone profile with
	 * deepslate-like strength (vanilla deepslate: 3.0F hardness, 6.0F resistance).
	 */
	private static AbstractBlock.Settings stoneSettings(MapColor color, BlockSoundGroup sounds) {
		return AbstractBlock.Settings.create()
				.mapColor(color)
				.strength(3.0F, 6.0F)
				.requiresTool()
				.sounds(sounds);
	}

	private static AbstractBlock.Settings nightslateSettings() {
		return stoneSettings(MapColor.DEEPSLATE_GRAY, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings voidbasaltSettings() {
		return stoneSettings(MapColor.BLACK, BlockSoundGroup.BASALT);
	}

	private static AbstractBlock.Settings duskstoneSettings() {
		return stoneSettings(MapColor.TERRACOTTA_BLUE, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings gloomstoneSettings() {
		return stoneSettings(MapColor.GRAY, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings shadowTuffSettings() {
		return stoneSettings(MapColor.TERRACOTTA_GRAY, BlockSoundGroup.TUFF);
	}

	private static AbstractBlock.Settings umbralDeepslateSettings() {
		return stoneSettings(MapColor.DEEPSLATE_GRAY, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings blacksootStoneSettings() {
		return stoneSettings(MapColor.BLACK, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings charObsidianSettings() {
		return stoneSettings(MapColor.BLACK, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings darkPumiceSettings() {
		return stoneSettings(MapColor.TERRACOTTA_BLACK, BlockSoundGroup.BASALT);
	}

	private static AbstractBlock.Settings ebonstoneSettings() {
		return stoneSettings(MapColor.BLACK, BlockSoundGroup.DEEPSLATE);
	}

	private static AbstractBlock.Settings murkrockSettings() {
		return stoneSettings(MapColor.TERRACOTTA_CYAN, BlockSoundGroup.STONE);
	}

	private static AbstractBlock.Settings cinderdarkStoneSettings() {
		return stoneSettings(MapColor.TERRACOTTA_BLACK, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings netherveilStoneSettings() {
		return stoneSettings(MapColor.DARK_CRIMSON, BlockSoundGroup.NETHER_BRICKS);
	}

	private static AbstractBlock.Settings obscuraStoneSettings() {
		return stoneSettings(MapColor.TERRACOTTA_PURPLE, BlockSoundGroup.DEEPSLATE);
	}

	public static void init() {
		NIGHTSLATE = ModBlockFamilies.registerCubeFamily(
				"nightslate", "nightslate", NightslateFeature::nightslateSettings, true);
		POLISHED_NIGHTSLATE = ModBlockFamilies.registerCubeFamily(
				"polished_nightslate", "polished_nightslate", NightslateFeature::nightslateSettings, true);
		NIGHTSLATE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"nightslate_bricks", "nightslate_brick", NightslateFeature::nightslateSettings, true);
		VOIDBASALT = ModBlockFamilies.registerCubeFamily(
				"voidbasalt", "voidbasalt", NightslateFeature::voidbasaltSettings, true);
		POLISHED_VOIDBASALT = ModBlockFamilies.registerCubeFamily(
				"polished_voidbasalt", "polished_voidbasalt", NightslateFeature::voidbasaltSettings, true);
		VOIDBASALT_BRICKS = ModBlockFamilies.registerCubeFamily(
				"voidbasalt_bricks", "voidbasalt_brick", NightslateFeature::voidbasaltSettings, true);
		DUSKSTONE = ModBlockFamilies.registerCubeFamily(
				"duskstone", "duskstone", NightslateFeature::duskstoneSettings, true);
		POLISHED_DUSKSTONE = ModBlockFamilies.registerCubeFamily(
				"polished_duskstone", "polished_duskstone", NightslateFeature::duskstoneSettings, true);
		DUSKSTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"duskstone_bricks", "duskstone_brick", NightslateFeature::duskstoneSettings, true);
		GLOOMSTONE = ModBlockFamilies.registerCubeFamily(
				"gloomstone", "gloomstone", NightslateFeature::gloomstoneSettings, true);
		POLISHED_GLOOMSTONE = ModBlockFamilies.registerCubeFamily(
				"polished_gloomstone", "polished_gloomstone", NightslateFeature::gloomstoneSettings, true);
		GLOOMSTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"gloomstone_bricks", "gloomstone_brick", NightslateFeature::gloomstoneSettings, true);
		SHADOW_TUFF = ModBlockFamilies.registerCubeFamily(
				"shadow_tuff", "shadow_tuff", NightslateFeature::shadowTuffSettings, true);
		POLISHED_SHADOW_TUFF = ModBlockFamilies.registerCubeFamily(
				"polished_shadow_tuff", "polished_shadow_tuff", NightslateFeature::shadowTuffSettings, true);
		SHADOW_TUFF_BRICKS = ModBlockFamilies.registerCubeFamily(
				"shadow_tuff_bricks", "shadow_tuff_brick", NightslateFeature::shadowTuffSettings, true);
		UMBRAL_DEEPSLATE = ModBlockFamilies.registerCubeFamily(
				"umbral_deepslate", "umbral_deepslate", NightslateFeature::umbralDeepslateSettings, true);
		POLISHED_UMBRAL_DEEPSLATE = ModBlockFamilies.registerCubeFamily(
				"polished_umbral_deepslate", "polished_umbral_deepslate", NightslateFeature::umbralDeepslateSettings, true);
		UMBRAL_DEEPSLATE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"umbral_deepslate_bricks", "umbral_deepslate_brick", NightslateFeature::umbralDeepslateSettings, true);
		BLACKSOOT_STONE = ModBlockFamilies.registerCubeFamily(
				"blacksoot_stone", "blacksoot_stone", NightslateFeature::blacksootStoneSettings, true);
		POLISHED_BLACKSOOT_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_blacksoot_stone", "polished_blacksoot_stone", NightslateFeature::blacksootStoneSettings, true);
		BLACKSOOT_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"blacksoot_stone_bricks", "blacksoot_stone_brick", NightslateFeature::blacksootStoneSettings, true);
		CHAR_OBSIDIAN = ModBlockFamilies.registerCubeFamily(
				"char_obsidian", "char_obsidian", NightslateFeature::charObsidianSettings, true);
		POLISHED_CHAR_OBSIDIAN = ModBlockFamilies.registerCubeFamily(
				"polished_char_obsidian", "polished_char_obsidian", NightslateFeature::charObsidianSettings, true);
		CHAR_OBSIDIAN_BRICKS = ModBlockFamilies.registerCubeFamily(
				"char_obsidian_bricks", "char_obsidian_brick", NightslateFeature::charObsidianSettings, true);
		DARK_PUMICE = ModBlockFamilies.registerCubeFamily(
				"dark_pumice", "dark_pumice", NightslateFeature::darkPumiceSettings, true);
		POLISHED_DARK_PUMICE = ModBlockFamilies.registerCubeFamily(
				"polished_dark_pumice", "polished_dark_pumice", NightslateFeature::darkPumiceSettings, true);
		DARK_PUMICE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"dark_pumice_bricks", "dark_pumice_brick", NightslateFeature::darkPumiceSettings, true);
		EBONSTONE = ModBlockFamilies.registerCubeFamily(
				"ebonstone", "ebonstone", NightslateFeature::ebonstoneSettings, true);
		POLISHED_EBONSTONE = ModBlockFamilies.registerCubeFamily(
				"polished_ebonstone", "polished_ebonstone", NightslateFeature::ebonstoneSettings, true);
		EBONSTONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"ebonstone_bricks", "ebonstone_brick", NightslateFeature::ebonstoneSettings, true);
		MURKROCK = ModBlockFamilies.registerCubeFamily(
				"murkrock", "murkrock", NightslateFeature::murkrockSettings, true);
		POLISHED_MURKROCK = ModBlockFamilies.registerCubeFamily(
				"polished_murkrock", "polished_murkrock", NightslateFeature::murkrockSettings, true);
		MURKROCK_BRICKS = ModBlockFamilies.registerCubeFamily(
				"murkrock_bricks", "murkrock_brick", NightslateFeature::murkrockSettings, true);
		CINDERDARK_STONE = ModBlockFamilies.registerCubeFamily(
				"cinderdark_stone", "cinderdark_stone", NightslateFeature::cinderdarkStoneSettings, true);
		POLISHED_CINDERDARK_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_cinderdark_stone", "polished_cinderdark_stone", NightslateFeature::cinderdarkStoneSettings, true);
		CINDERDARK_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"cinderdark_stone_bricks", "cinderdark_stone_brick", NightslateFeature::cinderdarkStoneSettings, true);
		NETHERVEIL_STONE = ModBlockFamilies.registerCubeFamily(
				"netherveil_stone", "netherveil_stone", NightslateFeature::netherveilStoneSettings, true);
		POLISHED_NETHERVEIL_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_netherveil_stone", "polished_netherveil_stone", NightslateFeature::netherveilStoneSettings, true);
		NETHERVEIL_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"netherveil_stone_bricks", "netherveil_stone_brick", NightslateFeature::netherveilStoneSettings, true);
		OBSCURA_STONE = ModBlockFamilies.registerCubeFamily(
				"obscura_stone", "obscura_stone", NightslateFeature::obscuraStoneSettings, true);
		POLISHED_OBSCURA_STONE = ModBlockFamilies.registerCubeFamily(
				"polished_obscura_stone", "polished_obscura_stone", NightslateFeature::obscuraStoneSettings, true);
		OBSCURA_STONE_BRICKS = ModBlockFamilies.registerCubeFamily(
				"obscura_stone_bricks", "obscura_stone_brick", NightslateFeature::obscuraStoneSettings, true);

		NIGHTSLATE_TILES = ModBlocks.register("nightslate_tiles", Block::new, nightslateSettings(), true);
		CRACKED_NIGHTSLATE_BRICKS = ModBlocks.register("cracked_nightslate_bricks", Block::new, nightslateSettings(), true);
		CHISELED_NIGHTSLATE_BRICKS = ModBlocks.register("chiseled_nightslate_bricks", Block::new, nightslateSettings(), true);
		NIGHTSLATE_PILLAR = ModBlocks.register("nightslate_pillar", PillarBlock::new, nightslateSettings(), true);
		VOIDBASALT_TILES = ModBlocks.register("voidbasalt_tiles", Block::new, voidbasaltSettings(), true);
		CRACKED_VOIDBASALT_BRICKS = ModBlocks.register("cracked_voidbasalt_bricks", Block::new, voidbasaltSettings(), true);
		CHISELED_VOIDBASALT_BRICKS = ModBlocks.register("chiseled_voidbasalt_bricks", Block::new, voidbasaltSettings(), true);
		VOIDBASALT_PILLAR = ModBlocks.register("voidbasalt_pillar", PillarBlock::new, voidbasaltSettings(), true);
		DUSKSTONE_TILES = ModBlocks.register("duskstone_tiles", Block::new, duskstoneSettings(), true);
		CRACKED_DUSKSTONE_BRICKS = ModBlocks.register("cracked_duskstone_bricks", Block::new, duskstoneSettings(), true);
		CHISELED_DUSKSTONE_BRICKS = ModBlocks.register("chiseled_duskstone_bricks", Block::new, duskstoneSettings(), true);
		DUSKSTONE_PILLAR = ModBlocks.register("duskstone_pillar", PillarBlock::new, duskstoneSettings(), true);
		GLOOMSTONE_TILES = ModBlocks.register("gloomstone_tiles", Block::new, gloomstoneSettings(), true);
		CRACKED_GLOOMSTONE_BRICKS = ModBlocks.register("cracked_gloomstone_bricks", Block::new, gloomstoneSettings(), true);
		CHISELED_GLOOMSTONE_BRICKS = ModBlocks.register("chiseled_gloomstone_bricks", Block::new, gloomstoneSettings(), true);
		GLOOMSTONE_PILLAR = ModBlocks.register("gloomstone_pillar", PillarBlock::new, gloomstoneSettings(), true);
		SHADOW_TUFF_TILES = ModBlocks.register("shadow_tuff_tiles", Block::new, shadowTuffSettings(), true);
		CRACKED_SHADOW_TUFF_BRICKS = ModBlocks.register("cracked_shadow_tuff_bricks", Block::new, shadowTuffSettings(), true);
		CHISELED_SHADOW_TUFF_BRICKS = ModBlocks.register("chiseled_shadow_tuff_bricks", Block::new, shadowTuffSettings(), true);
		SHADOW_TUFF_PILLAR = ModBlocks.register("shadow_tuff_pillar", PillarBlock::new, shadowTuffSettings(), true);
		UMBRAL_DEEPSLATE_TILES = ModBlocks.register("umbral_deepslate_tiles", Block::new, umbralDeepslateSettings(), true);
		CRACKED_UMBRAL_DEEPSLATE_BRICKS = ModBlocks.register("cracked_umbral_deepslate_bricks", Block::new, umbralDeepslateSettings(), true);
		CHISELED_UMBRAL_DEEPSLATE_BRICKS = ModBlocks.register("chiseled_umbral_deepslate_bricks", Block::new, umbralDeepslateSettings(), true);
		UMBRAL_DEEPSLATE_PILLAR = ModBlocks.register("umbral_deepslate_pillar", PillarBlock::new, umbralDeepslateSettings(), true);
		BLACKSOOT_STONE_TILES = ModBlocks.register("blacksoot_stone_tiles", Block::new, blacksootStoneSettings(), true);
		CRACKED_BLACKSOOT_STONE_BRICKS = ModBlocks.register("cracked_blacksoot_stone_bricks", Block::new, blacksootStoneSettings(), true);
		CHISELED_BLACKSOOT_STONE_BRICKS = ModBlocks.register("chiseled_blacksoot_stone_bricks", Block::new, blacksootStoneSettings(), true);
		BLACKSOOT_STONE_PILLAR = ModBlocks.register("blacksoot_stone_pillar", PillarBlock::new, blacksootStoneSettings(), true);
		CHAR_OBSIDIAN_TILES = ModBlocks.register("char_obsidian_tiles", Block::new, charObsidianSettings(), true);
		CRACKED_CHAR_OBSIDIAN_BRICKS = ModBlocks.register("cracked_char_obsidian_bricks", Block::new, charObsidianSettings(), true);
		CHISELED_CHAR_OBSIDIAN_BRICKS = ModBlocks.register("chiseled_char_obsidian_bricks", Block::new, charObsidianSettings(), true);
		CHAR_OBSIDIAN_PILLAR = ModBlocks.register("char_obsidian_pillar", PillarBlock::new, charObsidianSettings(), true);
		DARK_PUMICE_TILES = ModBlocks.register("dark_pumice_tiles", Block::new, darkPumiceSettings(), true);
		CRACKED_DARK_PUMICE_BRICKS = ModBlocks.register("cracked_dark_pumice_bricks", Block::new, darkPumiceSettings(), true);
		CHISELED_DARK_PUMICE_BRICKS = ModBlocks.register("chiseled_dark_pumice_bricks", Block::new, darkPumiceSettings(), true);
		DARK_PUMICE_PILLAR = ModBlocks.register("dark_pumice_pillar", PillarBlock::new, darkPumiceSettings(), true);
		EBONSTONE_TILES = ModBlocks.register("ebonstone_tiles", Block::new, ebonstoneSettings(), true);
		CRACKED_EBONSTONE_BRICKS = ModBlocks.register("cracked_ebonstone_bricks", Block::new, ebonstoneSettings(), true);
		CHISELED_EBONSTONE_BRICKS = ModBlocks.register("chiseled_ebonstone_bricks", Block::new, ebonstoneSettings(), true);
		EBONSTONE_PILLAR = ModBlocks.register("ebonstone_pillar", PillarBlock::new, ebonstoneSettings(), true);
		MURKROCK_TILES = ModBlocks.register("murkrock_tiles", Block::new, murkrockSettings(), true);
		CRACKED_MURKROCK_BRICKS = ModBlocks.register("cracked_murkrock_bricks", Block::new, murkrockSettings(), true);
		CHISELED_MURKROCK_BRICKS = ModBlocks.register("chiseled_murkrock_bricks", Block::new, murkrockSettings(), true);
		MURKROCK_PILLAR = ModBlocks.register("murkrock_pillar", PillarBlock::new, murkrockSettings(), true);
		CINDERDARK_STONE_TILES = ModBlocks.register("cinderdark_stone_tiles", Block::new, cinderdarkStoneSettings(), true);
		CRACKED_CINDERDARK_STONE_BRICKS = ModBlocks.register("cracked_cinderdark_stone_bricks", Block::new, cinderdarkStoneSettings(), true);
		CHISELED_CINDERDARK_STONE_BRICKS = ModBlocks.register("chiseled_cinderdark_stone_bricks", Block::new, cinderdarkStoneSettings(), true);
		CINDERDARK_STONE_PILLAR = ModBlocks.register("cinderdark_stone_pillar", PillarBlock::new, cinderdarkStoneSettings(), true);
		NETHERVEIL_STONE_TILES = ModBlocks.register("netherveil_stone_tiles", Block::new, netherveilStoneSettings(), true);
		CRACKED_NETHERVEIL_STONE_BRICKS = ModBlocks.register("cracked_netherveil_stone_bricks", Block::new, netherveilStoneSettings(), true);
		CHISELED_NETHERVEIL_STONE_BRICKS = ModBlocks.register("chiseled_netherveil_stone_bricks", Block::new, netherveilStoneSettings(), true);
		NETHERVEIL_STONE_PILLAR = ModBlocks.register("netherveil_stone_pillar", PillarBlock::new, netherveilStoneSettings(), true);
		OBSCURA_STONE_TILES = ModBlocks.register("obscura_stone_tiles", Block::new, obscuraStoneSettings(), true);
		CRACKED_OBSCURA_STONE_BRICKS = ModBlocks.register("cracked_obscura_stone_bricks", Block::new, obscuraStoneSettings(), true);
		CHISELED_OBSCURA_STONE_BRICKS = ModBlocks.register("chiseled_obscura_stone_bricks", Block::new, obscuraStoneSettings(), true);
		OBSCURA_STONE_PILLAR = ModBlocks.register("obscura_stone_pillar", PillarBlock::new, obscuraStoneSettings(), true);

		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.SETS_KEY).register(entries -> {
			entries.add(NIGHTSLATE.block());
			entries.add(NIGHTSLATE.stairs());
			entries.add(NIGHTSLATE.slab());
			entries.add(NIGHTSLATE.wall());
			entries.add(POLISHED_NIGHTSLATE.block());
			entries.add(POLISHED_NIGHTSLATE.stairs());
			entries.add(POLISHED_NIGHTSLATE.slab());
			entries.add(POLISHED_NIGHTSLATE.wall());
			entries.add(NIGHTSLATE_BRICKS.block());
			entries.add(NIGHTSLATE_BRICKS.stairs());
			entries.add(NIGHTSLATE_BRICKS.slab());
			entries.add(NIGHTSLATE_BRICKS.wall());
			entries.add(NIGHTSLATE_TILES);
			entries.add(CRACKED_NIGHTSLATE_BRICKS);
			entries.add(CHISELED_NIGHTSLATE_BRICKS);
			entries.add(NIGHTSLATE_PILLAR);
			entries.add(VOIDBASALT.block());
			entries.add(VOIDBASALT.stairs());
			entries.add(VOIDBASALT.slab());
			entries.add(VOIDBASALT.wall());
			entries.add(POLISHED_VOIDBASALT.block());
			entries.add(POLISHED_VOIDBASALT.stairs());
			entries.add(POLISHED_VOIDBASALT.slab());
			entries.add(POLISHED_VOIDBASALT.wall());
			entries.add(VOIDBASALT_BRICKS.block());
			entries.add(VOIDBASALT_BRICKS.stairs());
			entries.add(VOIDBASALT_BRICKS.slab());
			entries.add(VOIDBASALT_BRICKS.wall());
			entries.add(VOIDBASALT_TILES);
			entries.add(CRACKED_VOIDBASALT_BRICKS);
			entries.add(CHISELED_VOIDBASALT_BRICKS);
			entries.add(VOIDBASALT_PILLAR);
			entries.add(DUSKSTONE.block());
			entries.add(DUSKSTONE.stairs());
			entries.add(DUSKSTONE.slab());
			entries.add(DUSKSTONE.wall());
			entries.add(POLISHED_DUSKSTONE.block());
			entries.add(POLISHED_DUSKSTONE.stairs());
			entries.add(POLISHED_DUSKSTONE.slab());
			entries.add(POLISHED_DUSKSTONE.wall());
			entries.add(DUSKSTONE_BRICKS.block());
			entries.add(DUSKSTONE_BRICKS.stairs());
			entries.add(DUSKSTONE_BRICKS.slab());
			entries.add(DUSKSTONE_BRICKS.wall());
			entries.add(DUSKSTONE_TILES);
			entries.add(CRACKED_DUSKSTONE_BRICKS);
			entries.add(CHISELED_DUSKSTONE_BRICKS);
			entries.add(DUSKSTONE_PILLAR);
			entries.add(GLOOMSTONE.block());
			entries.add(GLOOMSTONE.stairs());
			entries.add(GLOOMSTONE.slab());
			entries.add(GLOOMSTONE.wall());
			entries.add(POLISHED_GLOOMSTONE.block());
			entries.add(POLISHED_GLOOMSTONE.stairs());
			entries.add(POLISHED_GLOOMSTONE.slab());
			entries.add(POLISHED_GLOOMSTONE.wall());
			entries.add(GLOOMSTONE_BRICKS.block());
			entries.add(GLOOMSTONE_BRICKS.stairs());
			entries.add(GLOOMSTONE_BRICKS.slab());
			entries.add(GLOOMSTONE_BRICKS.wall());
			entries.add(GLOOMSTONE_TILES);
			entries.add(CRACKED_GLOOMSTONE_BRICKS);
			entries.add(CHISELED_GLOOMSTONE_BRICKS);
			entries.add(GLOOMSTONE_PILLAR);
			entries.add(SHADOW_TUFF.block());
			entries.add(SHADOW_TUFF.stairs());
			entries.add(SHADOW_TUFF.slab());
			entries.add(SHADOW_TUFF.wall());
			entries.add(POLISHED_SHADOW_TUFF.block());
			entries.add(POLISHED_SHADOW_TUFF.stairs());
			entries.add(POLISHED_SHADOW_TUFF.slab());
			entries.add(POLISHED_SHADOW_TUFF.wall());
			entries.add(SHADOW_TUFF_BRICKS.block());
			entries.add(SHADOW_TUFF_BRICKS.stairs());
			entries.add(SHADOW_TUFF_BRICKS.slab());
			entries.add(SHADOW_TUFF_BRICKS.wall());
			entries.add(SHADOW_TUFF_TILES);
			entries.add(CRACKED_SHADOW_TUFF_BRICKS);
			entries.add(CHISELED_SHADOW_TUFF_BRICKS);
			entries.add(SHADOW_TUFF_PILLAR);
			entries.add(UMBRAL_DEEPSLATE.block());
			entries.add(UMBRAL_DEEPSLATE.stairs());
			entries.add(UMBRAL_DEEPSLATE.slab());
			entries.add(UMBRAL_DEEPSLATE.wall());
			entries.add(POLISHED_UMBRAL_DEEPSLATE.block());
			entries.add(POLISHED_UMBRAL_DEEPSLATE.stairs());
			entries.add(POLISHED_UMBRAL_DEEPSLATE.slab());
			entries.add(POLISHED_UMBRAL_DEEPSLATE.wall());
			entries.add(UMBRAL_DEEPSLATE_BRICKS.block());
			entries.add(UMBRAL_DEEPSLATE_BRICKS.stairs());
			entries.add(UMBRAL_DEEPSLATE_BRICKS.slab());
			entries.add(UMBRAL_DEEPSLATE_BRICKS.wall());
			entries.add(UMBRAL_DEEPSLATE_TILES);
			entries.add(CRACKED_UMBRAL_DEEPSLATE_BRICKS);
			entries.add(CHISELED_UMBRAL_DEEPSLATE_BRICKS);
			entries.add(UMBRAL_DEEPSLATE_PILLAR);
			entries.add(BLACKSOOT_STONE.block());
			entries.add(BLACKSOOT_STONE.stairs());
			entries.add(BLACKSOOT_STONE.slab());
			entries.add(BLACKSOOT_STONE.wall());
			entries.add(POLISHED_BLACKSOOT_STONE.block());
			entries.add(POLISHED_BLACKSOOT_STONE.stairs());
			entries.add(POLISHED_BLACKSOOT_STONE.slab());
			entries.add(POLISHED_BLACKSOOT_STONE.wall());
			entries.add(BLACKSOOT_STONE_BRICKS.block());
			entries.add(BLACKSOOT_STONE_BRICKS.stairs());
			entries.add(BLACKSOOT_STONE_BRICKS.slab());
			entries.add(BLACKSOOT_STONE_BRICKS.wall());
			entries.add(BLACKSOOT_STONE_TILES);
			entries.add(CRACKED_BLACKSOOT_STONE_BRICKS);
			entries.add(CHISELED_BLACKSOOT_STONE_BRICKS);
			entries.add(BLACKSOOT_STONE_PILLAR);
			entries.add(CHAR_OBSIDIAN.block());
			entries.add(CHAR_OBSIDIAN.stairs());
			entries.add(CHAR_OBSIDIAN.slab());
			entries.add(CHAR_OBSIDIAN.wall());
			entries.add(POLISHED_CHAR_OBSIDIAN.block());
			entries.add(POLISHED_CHAR_OBSIDIAN.stairs());
			entries.add(POLISHED_CHAR_OBSIDIAN.slab());
			entries.add(POLISHED_CHAR_OBSIDIAN.wall());
			entries.add(CHAR_OBSIDIAN_BRICKS.block());
			entries.add(CHAR_OBSIDIAN_BRICKS.stairs());
			entries.add(CHAR_OBSIDIAN_BRICKS.slab());
			entries.add(CHAR_OBSIDIAN_BRICKS.wall());
			entries.add(CHAR_OBSIDIAN_TILES);
			entries.add(CRACKED_CHAR_OBSIDIAN_BRICKS);
			entries.add(CHISELED_CHAR_OBSIDIAN_BRICKS);
			entries.add(CHAR_OBSIDIAN_PILLAR);
			entries.add(DARK_PUMICE.block());
			entries.add(DARK_PUMICE.stairs());
			entries.add(DARK_PUMICE.slab());
			entries.add(DARK_PUMICE.wall());
			entries.add(POLISHED_DARK_PUMICE.block());
			entries.add(POLISHED_DARK_PUMICE.stairs());
			entries.add(POLISHED_DARK_PUMICE.slab());
			entries.add(POLISHED_DARK_PUMICE.wall());
			entries.add(DARK_PUMICE_BRICKS.block());
			entries.add(DARK_PUMICE_BRICKS.stairs());
			entries.add(DARK_PUMICE_BRICKS.slab());
			entries.add(DARK_PUMICE_BRICKS.wall());
			entries.add(DARK_PUMICE_TILES);
			entries.add(CRACKED_DARK_PUMICE_BRICKS);
			entries.add(CHISELED_DARK_PUMICE_BRICKS);
			entries.add(DARK_PUMICE_PILLAR);
			entries.add(EBONSTONE.block());
			entries.add(EBONSTONE.stairs());
			entries.add(EBONSTONE.slab());
			entries.add(EBONSTONE.wall());
			entries.add(POLISHED_EBONSTONE.block());
			entries.add(POLISHED_EBONSTONE.stairs());
			entries.add(POLISHED_EBONSTONE.slab());
			entries.add(POLISHED_EBONSTONE.wall());
			entries.add(EBONSTONE_BRICKS.block());
			entries.add(EBONSTONE_BRICKS.stairs());
			entries.add(EBONSTONE_BRICKS.slab());
			entries.add(EBONSTONE_BRICKS.wall());
			entries.add(EBONSTONE_TILES);
			entries.add(CRACKED_EBONSTONE_BRICKS);
			entries.add(CHISELED_EBONSTONE_BRICKS);
			entries.add(EBONSTONE_PILLAR);
			entries.add(MURKROCK.block());
			entries.add(MURKROCK.stairs());
			entries.add(MURKROCK.slab());
			entries.add(MURKROCK.wall());
			entries.add(POLISHED_MURKROCK.block());
			entries.add(POLISHED_MURKROCK.stairs());
			entries.add(POLISHED_MURKROCK.slab());
			entries.add(POLISHED_MURKROCK.wall());
			entries.add(MURKROCK_BRICKS.block());
			entries.add(MURKROCK_BRICKS.stairs());
			entries.add(MURKROCK_BRICKS.slab());
			entries.add(MURKROCK_BRICKS.wall());
			entries.add(MURKROCK_TILES);
			entries.add(CRACKED_MURKROCK_BRICKS);
			entries.add(CHISELED_MURKROCK_BRICKS);
			entries.add(MURKROCK_PILLAR);
			entries.add(CINDERDARK_STONE.block());
			entries.add(CINDERDARK_STONE.stairs());
			entries.add(CINDERDARK_STONE.slab());
			entries.add(CINDERDARK_STONE.wall());
			entries.add(POLISHED_CINDERDARK_STONE.block());
			entries.add(POLISHED_CINDERDARK_STONE.stairs());
			entries.add(POLISHED_CINDERDARK_STONE.slab());
			entries.add(POLISHED_CINDERDARK_STONE.wall());
			entries.add(CINDERDARK_STONE_BRICKS.block());
			entries.add(CINDERDARK_STONE_BRICKS.stairs());
			entries.add(CINDERDARK_STONE_BRICKS.slab());
			entries.add(CINDERDARK_STONE_BRICKS.wall());
			entries.add(CINDERDARK_STONE_TILES);
			entries.add(CRACKED_CINDERDARK_STONE_BRICKS);
			entries.add(CHISELED_CINDERDARK_STONE_BRICKS);
			entries.add(CINDERDARK_STONE_PILLAR);
			entries.add(NETHERVEIL_STONE.block());
			entries.add(NETHERVEIL_STONE.stairs());
			entries.add(NETHERVEIL_STONE.slab());
			entries.add(NETHERVEIL_STONE.wall());
			entries.add(POLISHED_NETHERVEIL_STONE.block());
			entries.add(POLISHED_NETHERVEIL_STONE.stairs());
			entries.add(POLISHED_NETHERVEIL_STONE.slab());
			entries.add(POLISHED_NETHERVEIL_STONE.wall());
			entries.add(NETHERVEIL_STONE_BRICKS.block());
			entries.add(NETHERVEIL_STONE_BRICKS.stairs());
			entries.add(NETHERVEIL_STONE_BRICKS.slab());
			entries.add(NETHERVEIL_STONE_BRICKS.wall());
			entries.add(NETHERVEIL_STONE_TILES);
			entries.add(CRACKED_NETHERVEIL_STONE_BRICKS);
			entries.add(CHISELED_NETHERVEIL_STONE_BRICKS);
			entries.add(NETHERVEIL_STONE_PILLAR);
			entries.add(OBSCURA_STONE.block());
			entries.add(OBSCURA_STONE.stairs());
			entries.add(OBSCURA_STONE.slab());
			entries.add(OBSCURA_STONE.wall());
			entries.add(POLISHED_OBSCURA_STONE.block());
			entries.add(POLISHED_OBSCURA_STONE.stairs());
			entries.add(POLISHED_OBSCURA_STONE.slab());
			entries.add(POLISHED_OBSCURA_STONE.wall());
			entries.add(OBSCURA_STONE_BRICKS.block());
			entries.add(OBSCURA_STONE_BRICKS.stairs());
			entries.add(OBSCURA_STONE_BRICKS.slab());
			entries.add(OBSCURA_STONE_BRICKS.wall());
			entries.add(OBSCURA_STONE_TILES);
			entries.add(CRACKED_OBSCURA_STONE_BRICKS);
			entries.add(CHISELED_OBSCURA_STONE_BRICKS);
			entries.add(OBSCURA_STONE_PILLAR);
		});

		NightslateHandbook.register();
	}
}
