package net.sonic0810.copperinferno.feature.emberswarm.client;

import net.minecraft.client.render.entity.BlazeEntityRenderer;
import net.minecraft.client.render.entity.EndermiteEntityRenderer;
import net.minecraft.client.render.entity.EntityRendererFactories;
import net.minecraft.client.render.entity.MagmaCubeEntityRenderer;
import net.minecraft.client.render.entity.SilverfishEntityRenderer;
import net.minecraft.client.render.entity.VexEntityRenderer;
import net.sonic0810.copperinferno.feature.emberswarm.EmberSwarmFeature;

/**
 * Client-side setup for the Ember Swarm mobs: each type reuses its vanilla renderer
 * (all five ctors are Context-only, verified via javap). The mobs extend the matching
 * vanilla entities, so the factories fit the register(EntityType&lt;? extends T&gt;,
 * EntityRendererFactory&lt;T&gt;) bound; the vanilla register method is access-widened
 * by Fabric's transitive access wideners (same proven pattern as infernomobs).
 * Generated by {@code devtools/gen/emberswarm_gen.py} - do not edit by hand.
 */
public final class EmberSwarmFeatureClient {
	private EmberSwarmFeatureClient() {
	}

	public static void initClient() {
		EntityRendererFactories.register(EmberSwarmFeature.EMBER_BLAZE, BlazeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SOOT_BLAZE, BlazeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.PYRE_BLAZE, BlazeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.CINDER_BLAZE, BlazeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SLAGFIRE_BLAZE, BlazeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.MOLTEN_CUBE, MagmaCubeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.EMBER_CUBE, MagmaCubeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SOOT_CUBE, MagmaCubeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SCORIA_CUBE, MagmaCubeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.PYROCLAST_CUBE, MagmaCubeEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.CINDER_SILVERFISH, SilverfishEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.ASH_SILVERFISH, SilverfishEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.EMBER_SILVERFISH, SilverfishEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SOOT_SILVERFISH, SilverfishEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SLAG_SILVERFISH, SilverfishEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.FLAME_VEX, VexEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.EMBER_VEX, VexEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.CINDER_VEX, VexEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SMOKE_VEX, VexEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SPARK_VEX, VexEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.ASH_MITE, EndermiteEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.EMBER_MITE, EndermiteEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.CINDER_MITE, EndermiteEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SOOT_MITE, EndermiteEntityRenderer::new);
		EntityRendererFactories.register(EmberSwarmFeature.SLAG_MITE, EndermiteEntityRenderer::new);
	}
}
