package net.sonic0810.copperinferno.feature.foods;

import java.util.List;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.component.type.ConsumableComponent;
import net.minecraft.component.type.ConsumableComponents;
import net.minecraft.component.type.FoodComponent;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.item.consume.ApplyEffectsConsumeEffect;
import net.minecraft.util.Rarity;
import net.sonic0810.copperinferno.core.ModCreativeTab;
import net.sonic0810.copperinferno.core.ModItems;

/**
 * Foods feature (v2): 6 bottled soda drinks + 12 snack foods.
 *
 * <p>Follows the verified 1.21.9 consumable pattern from
 * {@code feature/drpepper/DrPepperFeature}: {@link FoodComponent.Builder} for hunger/saturation,
 * {@link ConsumableComponents#drink()} / {@link ConsumableComponents#food()} builders carrying an
 * {@link ApplyEffectsConsumeEffect}, and {@code Item.Settings.useRemainder(Items.GLASS_BOTTLE)}
 * so emptied drinks hand back the bottle.
 *
 * <p>Assets (items/*.json + models/item/*.json + 16x16 textures), recipes
 * ({@code data/copper_inferno/recipe/foods/}) and the lang fragment
 * ({@code lang/fragments/foods.json}) are generated by {@code devtools/gen/foods_gen.py}.
 */
public final class FoodsFeature {
	private FoodsFeature() {
	}

	// Drinks (maxCount 16, nutrition 2 / saturation 0.3, always drinkable, glass bottle back).
	public static Item CHERRY_DR_PEPPER;
	public static Item VANILLA_DR_PEPPER;
	public static Item CREAM_SODA;
	public static Item DR_PEPPER_ZERO;
	public static Item GRAPE_SODA;
	public static Item ORANGE_SODA;

	// Foods.
	public static Item SODA_SYRUP;
	public static Item CARAMEL_SYRUP;
	public static Item COPPER_APPLE;
	public static Item CANDIED_COPPER_APPLE;
	public static Item DR_PEPPER_ICE_CUBE;
	public static Item FIZZY_SUGAR_CRYSTALS;
	public static Item SODA_GUMMY;
	public static Item SODA_FLOAT;
	public static Item DR_PEPPER_COOKIE;
	public static Item INFERNO_PEPPER;
	public static Item COPPER_CARROT;
	public static Item DR_PEPPER_CAKE_SLICE;

	public static void init() {
		// ---- Drinks (themed effect, 10-30s, low amplifier) ----
		CHERRY_DR_PEPPER = registerDrink("cherry_dr_pepper",
				new StatusEffectInstance(StatusEffects.SPEED, 400, 0)); // Speed I 20s
		VANILLA_DR_PEPPER = registerDrink("vanilla_dr_pepper",
				new StatusEffectInstance(StatusEffects.REGENERATION, 100, 0)); // Regeneration I 5s
		CREAM_SODA = registerDrink("cream_soda",
				new StatusEffectInstance(StatusEffects.ABSORPTION, 400, 0)); // Absorption I 20s
		DR_PEPPER_ZERO = registerDrink("dr_pepper_zero",
				new StatusEffectInstance(StatusEffects.HASTE, 400, 0)); // Haste I 20s
		GRAPE_SODA = registerDrink("grape_soda",
				new StatusEffectInstance(StatusEffects.NIGHT_VISION, 600, 0)); // Night Vision 30s
		ORANGE_SODA = registerDrink("orange_soda",
				new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 200, 0)); // Fire Res 10s

		// ---- Plain foods ----
		SODA_SYRUP = ModItems.register("soda_syrup", Item::new, new Item.Settings()
				.food(food(3, 0.3f)));
		CARAMEL_SYRUP = ModItems.register("caramel_syrup", Item::new, new Item.Settings()
				.food(food(4, 0.3f)));
		SODA_GUMMY = ModItems.register("soda_gummy", Item::new, new Item.Settings()
				.food(food(2, 0.2f)));
		SODA_FLOAT = ModItems.register("soda_float", Item::new, new Item.Settings()
				.food(food(5, 0.6f)));
		DR_PEPPER_COOKIE = ModItems.register("dr_pepper_cookie", Item::new, new Item.Settings()
				.food(food(2, 0.1f)));
		COPPER_CARROT = ModItems.register("copper_carrot", Item::new, new Item.Settings()
				.food(food(4, 0.6f)));
		DR_PEPPER_CAKE_SLICE = ModItems.register("dr_pepper_cake_slice", Item::new, new Item.Settings()
				.food(food(3, 0.2f)));

		// ---- Foods with consume effects ----
		COPPER_APPLE = ModItems.register("copper_apple", Item::new, new Item.Settings()
				.rarity(Rarity.UNCOMMON)
				.food(food(4, 0.6f), effectFood(
						new StatusEffectInstance(StatusEffects.RESISTANCE, 600, 0)))); // Resistance I 30s
		CANDIED_COPPER_APPLE = ModItems.register("candied_copper_apple", Item::new, new Item.Settings()
				.rarity(Rarity.RARE)
				.food(alwaysEdibleFood(6, 0.9f), effectFood(
						new StatusEffectInstance(StatusEffects.ABSORPTION, 600, 1)))); // Absorption II 30s
		DR_PEPPER_ICE_CUBE = ModItems.register("dr_pepper_ice_cube", Item::new, new Item.Settings()
				.food(food(1, 0.1f), effectFood(
						new StatusEffectInstance(StatusEffects.SLOWNESS, 40, 0), // Slowness I 2s
						new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 200, 0)))); // Fire Res 10s
		FIZZY_SUGAR_CRYSTALS = ModItems.register("fizzy_sugar_crystals", Item::new, new Item.Settings()
				.food(alwaysEdibleFood(2, 0.1f), effectFood(
						new StatusEffectInstance(StatusEffects.SPEED, 200, 0)))); // Speed I 10s
		INFERNO_PEPPER = ModItems.register("inferno_pepper", Item::new, new Item.Settings()
				.food(alwaysEdibleFood(3, 0.3f), effectFood(
						new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 600, 0)))); // Fire Res 30s

		// Grouped: all 6 drinks first, then the 12 foods.
		ItemGroupEvents.modifyEntriesEvent(ModCreativeTab.FOODS_KEY).register(entries -> {
			entries.add(CHERRY_DR_PEPPER);
			entries.add(VANILLA_DR_PEPPER);
			entries.add(CREAM_SODA);
			entries.add(DR_PEPPER_ZERO);
			entries.add(GRAPE_SODA);
			entries.add(ORANGE_SODA);
			entries.add(SODA_SYRUP);
			entries.add(CARAMEL_SYRUP);
			entries.add(COPPER_APPLE);
			entries.add(CANDIED_COPPER_APPLE);
			entries.add(DR_PEPPER_ICE_CUBE);
			entries.add(FIZZY_SUGAR_CRYSTALS);
			entries.add(SODA_GUMMY);
			entries.add(SODA_FLOAT);
			entries.add(DR_PEPPER_COOKIE);
			entries.add(INFERNO_PEPPER);
			entries.add(COPPER_CARROT);
			entries.add(DR_PEPPER_CAKE_SLICE);
		});
	}

	/**
	 * Bottled soda: stack of 16, drink consumable with one themed effect, drinkable when full,
	 * returns the glass bottle when finished.
	 */
	private static Item registerDrink(String path, StatusEffectInstance effect) {
		return ModItems.register(path, Item::new, new Item.Settings()
				.maxCount(16)
				.useRemainder(Items.GLASS_BOTTLE)
				.food(
						alwaysEdibleFood(2, 0.3f),
						ConsumableComponents.drink()
								.consumeEffect(new ApplyEffectsConsumeEffect(List.of(effect)))
								.build()));
	}

	private static FoodComponent food(int nutrition, float saturation) {
		return new FoodComponent.Builder().nutrition(nutrition).saturationModifier(saturation).build();
	}

	private static FoodComponent alwaysEdibleFood(int nutrition, float saturation) {
		return new FoodComponent.Builder().nutrition(nutrition).saturationModifier(saturation).alwaysEdible().build();
	}

	/** Standard eat consumable (vanilla golden-apple pattern) carrying the given effects. */
	private static ConsumableComponent effectFood(StatusEffectInstance... effects) {
		return ConsumableComponents.food()
				.consumeEffect(new ApplyEffectsConsumeEffect(List.of(effects)))
				.build();
	}
}
